### ISSUE TITLE
Permission denied when doing ls /proc/sys/fs/binfmt_misc inside a container

### ISSUE THREAD

**Issue by dnegreira** [lxc/lxd#5688] opened 2019-04-19 10:19 UTC
# Required information

 * Distribution: Ubuntu
 * Distribution version: Ubuntu 18.04 / 19.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.18.0-17-generic #18~18.04.1-Ubuntu / 5.0.0-13-generic #14-Ubuntu 

# Issue description

I found this while testing a new version of sosreport inside LXD, this error does not break anything besides showing a 'permission denied' message on sosreport when trying to list /proc/sys/fs/binfmt_misc inside an LXD container.
I am reporting this only as I see a change of behavior from 3.0.3 to 3.12, not sure if intended or not, but might as well as let you guys know.

# Steps to reproduce

# Works with 3.0.3 on snap
dnegreira@freedom:~
 $ snap install lxd --channel=3.0/stable
lxd (3.0/stable) 3.0.3 from Canonical✓ installed

$ mount | grep binfmt
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=31,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=13962)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)

dnegreira@freedom:~ 
$ lxd init
(all default)

dnegreira@freedom:~ 
$ lxc launch ubuntu: c1

dnegreira@freedom:~ 
$ lxc exec c1 bash

root@c1:~# ls -al /proc/sys/fs/binfmt_misc/
total 0
drwxr-xr-x 2 nobody nogroup 0 Apr 19 07:03 .
dr-xr-xr-x 1 root   root    0 Apr 19 09:49 ..
[.. more stuff .. ]

root@c1:~# ls -alnd /proc/sys/fs/binfmt_misc/
drwxr-xr-x 2 65534 65534 0 Apr 19 07:03 /proc/sys/fs/binfmt_misc/

dnegreira@freedom:~ 
 $ snap remove lxd
lxd removed

# Does not work on 3.12 on snap
dnegreira@freedom:~ 
 $ snap install lxd

lxd 3.12 from Canonical✓ installed
dnegreira@freedom:~ 
 $ lxd init
(all default)

dnegreira@freedom:~ 
 $ lxc launch ubuntu: c1

dnegreira@freedom:~ 
$ lxc exec c1 bash

ls -al /proc/sys/fs/binfmt_misc/
ls: cannot open directory '/proc/sys/fs/binfmt_misc/': Permission denied

root@c1:~# ls -alnd /proc/sys/fs/binfmt_misc/
drwxr-xr-x 2 65534 65534 0 Apr 19 07:03 /proc/sys/fs/binfmt_misc/

**Comment by stgraber** [comment] 2019-04-19 17:59
This smells like apparmor, anything in `dmesg` about denials?

**Comment by stgraber** [comment] 2019-04-19 18:01
The apparmor policy states:
```
./lxd/apparmor.go:  # Handle binfmt
./lxd/apparmor.go:  mount fstype=binfmt_misc -> /proc/sys/fs/binfmt_misc/,
./lxd/apparmor.go:  deny /proc/sys/fs/binfmt_misc/{,**} rwklx,
```

So the result in the 3.12 case is the expected one. My guess is that on 3.0.3 it's allowing it due to a bug in our apparmor policy there which I've since fixed, so 3.0.4 should then start similarly denying it.

**Comment by stgraber** [comment] 2019-04-19 18:02
Ah yeah, indeed, looking at 3.0.3, we were blocking things with a different pattern which was causing a mismatch due to an apparmor parser bug (we keep having to workaround a bunch of those).

So short version is, 3.12 is correct, 3.0.3 is allowing more than it should, stable-3.0 already has the fix so 3.0.4 will fix it. Closing.

**Closed by stgraber** 2019-04-19 18:02 UTC

**Comment by slashdd** [comment] 2019-04-25 13:47
In sosreport, the system plugin is copying the whole` /proc/sys`
We would have to add a forbidden path for binfmt_misc based on Stephane's comment above.

I'll submit the PR to sosreport.

**Comment by slashdd** [comment] 2019-04-25 13:48
system.py
```
    def setup(self):
        self.add_copy_spec([
==>         "/proc/sys",
            "/etc/sysconfig",
            "/etc/default",
            "/etc/environment",
        ])
...
```

**Comment by BryanQuigley** [comment] 2019-09-17 20:23
This breaks sosreports assumptions on it's ability to collect data from /proc/sys.  I'd like to better understand the reasoning for this.

"The reason for passing all of those is legacy init systems which require those to be mounted or be mountabled inside the container.

The majority of those will not be writable (or even readable) from inside an unprivileged container and will be blocked by our AppArmor policy inside privileged containers."  -https://github.com/lxc/lxd/blob/master/doc/container-environment.md

Couldn't we just have them (or at least /proc/sys/fs/binfmt_misc) blank?   What old init system is this?

**Comment by stgraber** [comment] 2019-09-18 07:59
Upstart requires them to be mounted and with the right filesystem type or it will attempt to mount them again, fail and hold the entire boot.

So as long as we care about Ubuntu 12.04, Ubuntu 14.04 or Centos/Rhel/Oracle 6, we can't remove that logic.

**Comment by BryanQuigley** [comment] 2019-09-18 21:40
I was trying to figure out another way forward, so I booted a 14.04 Cloud Image, but don't see any way to tell that binfmt_misc in indeed a filesystem of that type:
https://pastebin.ubuntu.com/p/3xqnXB7bYF/

If you have any other bug/issue links I'd happily read up on it.  Just trying to evaluate if there is another way..  Thanks!

**Comment by BryanQuigley** [comment] 2020-05-13 00:33
Mostly for future me/visitors.. I was able to reproduce the issue with 14.04/12.04 and it does fail to fully bring up if it's not there - you can check `status rsyslog` as a test if it worked to boot up or not.

python's os.access can't check if an layer like apparmor will deny access.

pstore and binfmt are handled differently:
>>> import os
>>> os.access('/proc/sys/fs/binfmt_misc', os.R_OK)
True
>>> os.listdir('/proc/sys/fs/binfmt_misc')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
PermissionError: [Errno 13] Permission denied: '/proc/sys/fs/binfmt_misc'
>>> 

>>> os.access('/sys/fs/pstore', os.R_OK)
False
>>> os.listdir('/sys/fs/pstore')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
PermissionError: [Errno 13] Permission denied: '/sys/fs/pstore'
>>>

Also of note, you can use stat to confirm if things exist, even if access would be blocked by apparmor
