### ISSUE TITLE
Lxd 4.6/dqlite corruption: Failed to start dqlite server

### ISSUE THREAD

**Issue by diegomontoya** [lxc/lxd#8020] opened 2020-10-11 02:06 UTC
1) Ubuntu 20.04
2) snap lxd 4.6

Steps that may have contributed to corruption

1) multiple concurrent (10x) lxc copy from remote
2) while lxc copy was not complete on some volumes, performed lxc storage volume set default container/xxx block.mount_options=rw,noatime,nodiratime 
3) while lxc copy was not fully complete, perfomed snap set lxd lvm.external=true

I cannot reproduce the corruption after clean slate.

Can provide the original database/ files for private analysis. Where should I send the database files to?

```
t=2020-10-10T18:53:50-0700 lvl=info msg="LXD 4.6 is starting in normal mode" path=/var/snap/lxd/common/lxd
t=2020-10-10T18:53:50-0700 lvl=info msg="Kernel uid/gid map:" 
t=2020-10-10T18:53:50-0700 lvl=info msg=" - u 0 0 4294967295" 
t=2020-10-10T18:53:50-0700 lvl=info msg=" - g 0 0 4294967295" 
t=2020-10-10T18:53:50-0700 lvl=info msg="Configured LXD uid/gid map:" 
t=2020-10-10T18:53:50-0700 lvl=info msg=" - u 0 1000000 1000000000" 
t=2020-10-10T18:53:50-0700 lvl=info msg=" - g 0 1000000 1000000000" 
t=2020-10-10T18:53:50-0700 lvl=info msg="Kernel features:" 
t=2020-10-10T18:53:50-0700 lvl=info msg=" - closing multiple file descriptors efficiently: no" 
t=2020-10-10T18:53:50-0700 lvl=info msg=" - netnsid-based network retrieval: yes" 
t=2020-10-10T18:53:50-0700 lvl=info msg=" - pidfds: yes" 
t=2020-10-10T18:53:50-0700 lvl=info msg=" - uevent injection: yes" 
t=2020-10-10T18:53:50-0700 lvl=info msg=" - seccomp listener: yes" 
t=2020-10-10T18:53:50-0700 lvl=info msg=" - seccomp listener continue syscalls: yes" 
t=2020-10-10T18:53:50-0700 lvl=info msg=" - seccomp listener add file descriptors: no" 
t=2020-10-10T18:53:50-0700 lvl=info msg=" - attach to namespaces via pidfds: yes" 
t=2020-10-10T18:53:50-0700 lvl=info msg=" - safe native terminal allocation : no" 
t=2020-10-10T18:53:50-0700 lvl=info msg=" - unprivileged file capabilities: yes" 
t=2020-10-10T18:53:50-0700 lvl=info msg=" - cgroup layout: hybrid" 
t=2020-10-10T18:53:50-0700 lvl=warn msg=" - Couldn't find the CGroup blkio.weight, I/O weight limits will be ignored" 
t=2020-10-10T18:53:50-0700 lvl=info msg=" - shiftfs support: disabled" 
t=2020-10-10T18:53:50-0700 lvl=info msg="Initializing local database" 
t=2020-10-10T18:53:50-0700 lvl=eror msg="Failed to start the daemon: Failed to start dqlite server: raft_start(): io: load closed segment 0000000000000238-0000000000000244: entries batch 40 starting at byte 556824: entries count in preamble is zero" 
t=2020-10-10T18:53:50-0700 lvl=info msg="Starting shutdown sequence" 
```

```
-rw------- 1 root root      64 Oct 10 17:33 0000000000000001-0000000000000001
-rw------- 1 root root 5397320 Oct 10 18:38 0000000000000002-0000000000000237
-rw------- 1 root root  557056 Oct 10 18:47 0000000000000238-0000000000000244
-rw------- 1 root root  293232 Oct 10 18:47 0000000000000245-0000000000000270
-rw------- 1 root root  409600 Oct 10 18:47 db.bin
-rw------- 1 root root 1829312 Oct 10 18:47 db.bin-wal
-rw------- 1 root root      32 Oct 10 17:33 metadata1
```

**Comment by stgraber** [comment] 2020-10-11 02:32
Can you send the database to free dot ekanayaka at canonical dot com ?
@freeekanayaka should be able to take a look to see what's going on.

Based on the error, you could get LXD back online by moving both `0000000000000238-0000000000000244` and `0000000000000245-0000000000000270` aside. It's unclear how much data this may revert though.

**Comment by stgraber** [comment] 2020-10-11 02:33
Can you also look at `journalctl -u snap.lxd.daemon -n 300` for a LXD crash?

With the activity you described, it seems plausible that you hit a LXD bug which would have caused the daemon to crash and then cause the database issue as a side effect. So we may have a clear LXD crash in the log which we can track down and fix on its own.

**Comment by diegomontoya** [comment] 2020-10-11 03:00
@stgraber  @freeekanayaka Email sent with issue url as part of subject. 

I checked both systemctl log and lxd/logs/ and there were no crashes. 

A little bit more history on the issue as it appeared originally

0) Started the concurrent remote lxc copy and other stuff in above bug issue. All lxc copy completed without error.
1) Multiple sequential commands of  ```lxc list``` showed DIFFERENT list of containers. I would execute one command after another and one should show 2 more containers and another would show -2 containers, randomly. 
2) At that point, I decided to reboot the server to stop the weirdness.
3) After server reboot, lxd can no longer startup with error shown in bug issue.

**Comment by freeekanayaka** [comment] 2020-10-11 08:14
> I cannot reproduce the corruption after clean slate.

What do you mean exactly? That you have set up again a brand new lxd, tried to follow the same steps and did not hit the bug?

**Comment by diegomontoya** [comment] 2020-10-11 23:36
I manually removed the LXD database files, removed all LVM thin volumes, and performed LXD init again to recreate the clean database. Then I started the same concurrent remote lxc copy again only this time I waited for all to complete before making container config changes. No corruption encountered. 
> What do you mean exactly? That you have set up again a brand new lxd, tried to follow the same steps and did not hit the bug?

**Comment by diegomontoya** [comment] 2020-10-22 12:39
@freeekanayaka  Any luck decoding the corrupt db I sent?

**Comment by freeekanayaka** [comment] 2020-10-26 11:02
I can reproduce the startup issue, unfortunately that's not enough to understand how we got to that state in the first place. I was hoping that following more or less the same procedure you could come up with a reproducer.

**Comment by diegomontoya** [comment] 2020-10-27 12:25
I have a gut feeling the new issue, also caused by concurrent lxc copy, is related. https://github.com/lxc/lxd/issues/8082 The new issue is a more extreme example of concurrent lxc copy where 1 Source server is doing N copies to M servers, all concurrently.

**Comment by stgraber** [comment] 2020-11-11 21:03
What's the status on this one?
I believe that other issue ended up being network related?

**Comment by freeekanayaka** [comment] 2020-11-12 08:14
Do we have a reproducer?

**Comment by stgraber** [comment] 2020-11-18 23:40
@diegomontoya did you run into this again? I seem to remember the other issue being a network problem in the end, would this also have happened because of that network problem?

**Comment by diegomontoya** [comment] 2020-11-27 18:10
@stgraber We have not been able to reproduce this problem again since the initial report. So this may be an one-off concurrency bug that is hard to repeat. My last comment about relating to #8082 is wrong as that was linux network caused and unrelated to this issue.

**Comment by stgraber** [comment] 2020-11-27 18:27
Thanks. As there isn't enough data to go on and we haven't seen other similar crashes since, we'll close it for now.
Should this happen again, please let us know here and we'll be more than happy to re-open.

**Closed by stgraber** 2020-11-27 18:27 UTC
Labels: Incomplete
