### ISSUE TITLE
Making Error Messages More Helpful

### ISSUE THREAD

**Issue by lmlsna** [lxc/lxd#4229] opened 2018-02-08 20:34 UTC
# Required information

 * Distribution: `Ubuntu`
 * Distribution version:`Bionic (dev branch)`
 * Kernel version: `4.13.0-32-generic x86_64 x86_64 GNU/Linux`
 * LXC version: `2.21`
 * LXD version: `2.21`
 * Storage backend in use: `butterfs`

# Issue description

When a command is issued incorrectly on the console to the LXD client, it provides helpful information as to how that specific input was incorrect. It also provides a large wall of text constituting alll the possible sub commands for a given command, which (while also very helpful) is typically at least a screen's worth of text and ends up burying the more specific error message at the top of the terminal, out of sight. It took me a while to even realize it was there.

These specific error messages will _always_ be relevant to the previously issued bad command, and should, in my opinion, be prioritized as the _last_ thing rendered by the error message rather than the first.

I have 2 recommendations for improving this (an easy one and a probably less easy one). I would be happy to submit a pull request implementing either or both of these suggestions if the consensus is that these would actually be helpful changes, and not a personal idiosyncrasy:

### Easy (?) One
The specific error message explaining _why_ the previously issued command failed  should be moved to the bottom of the screen, making it the chronologically last thing rendered. For instance, issuing the command `lxc storage volume create` throws an error and the very first line explains why:

`error: wrong number of subcommand arguments`. 

This is the followed by 77 more rows (counting blank lines) demonstrating the correct syntax, and a short summany for each of the subcommands:
```
Usage: lxc storage <subcommand> [options]
Manage storage pools and volumes.

*Storage pools*
lxc storage list [<remote>:]
    List available storage pools.

lxc storage show [<remote>:]<pool> [--resources]
    Show details of a storage pool.

lxc storage create [<remote>:]<pool> <driver> [key=value]...
    Create a storage pool.

lxc storage get [<remote>:]<pool> <key>
    Get storage pool configuration.

lxc storage set [<remote>:]<pool> <key> <value>
    Set storage pool configuration.

lxc storage unset [<remote>:]<pool> <key>
    Unset storage pool configuration.

lxc storage delete [<remote>:]<pool>
    Delete a storage pool.

lxc storage edit [<remote>:]<pool>
    Edit storage pool, either by launching external editor or reading STDIN.

*Storage volumes*
lxc storage volume list [<remote>:]<pool>
    List available storage volumes on a storage pool.

lxc storage volume show [<remote>:]<pool> <volume>
    Show details of a storage volume on a storage pool.

lxc storage volume create [<remote>:]<pool> <volume> [key=value]...
    Create a storage volume on a storage pool.

lxc storage volume rename [<remote>:]<pool> <old name> <new name>
    Rename a storage volume on a storage pool.

lxc storage volume get [<remote>:]<pool> <volume> <key>
    Get storage volume configuration on a storage pool.

lxc storage volume set [<remote>:]<pool> <volume> <key> <value>
    Set storage volume configuration on a storage pool.

lxc storage volume unset [<remote>:]<pool> <volume> <key>
    Unset storage volume configuration on a storage pool.

lxc storage volume delete [<remote>:]<pool> <volume>
    Delete a storage volume on a storage pool.

lxc storage volume edit [<remote>:]<pool> <volume>
    Edit storage volume, either by launching external editor or reading STDIN.

lxc storage volume attach [<remote>:]<pool> <volume> <container> [device name] <path>
    Attach a storage volume to the specified container.

lxc storage volume attach-profile [<remote:>]<pool> <volume> <profile> [device name] <path>
    Attach a storage volume to the specified profile.

lxc storage volume detach [<remote>:]<pool> <volume> <container> [device name]
    Detach a storage volume from the specified container.

lxc storage volume detach-profile [<remote:>]<pool> <volume> <profile> [device name]
    Detach a storage volume from the specified profile.

Unless specified through a prefix, all volume operations affect "custom" (user created) volumes.

*Examples*
cat pool.yaml | lxc storage edit [<remote>:]<pool>
    Update a storage pool using the content of pool.yaml.

cat pool.yaml | lxc storage volume edit [<remote>:]<pool> <volume>
    Update a storage volume using the content of pool.yaml.

lxc storage volume show default data
    Will show the properties of a custom volume called "data" in the "default" pool.

lxc storage volume show default container/data
    Will show the properties of the filesystem for a container called "data" in the "default" pool.
```

The last 11 lines to be rendered, arguably the least useful in that they are rarely used outside of debugging, and are for the most part standard and expected features of most linux program;

```
Options:
    --debug  (= false)
        Enable debug mode
    --force-local  (= false)
        Force using the local unix socket
    --no-alias  (= false)
        Ignore aliases when determining what command to run
    --resources  (= false)
        Show the resources available to the storage pool
    --verbose  (= false)
        Enable verbose mode
```

While this adheres to the general format of a  manpage, and I get that it's probably easier to just print that out, I think this would be a step in the right direction as far as providing helpful feedback to users.

## Less Easy (more vague) One
If error message logic can be sufficiently tailored and actionable as to type it correctly the next line, without having to leave the console, that would obviously be the ideal. I think it would be possible to infer what the user is trying to accomplish (much the same way bash-autocomplete does) and deliver _just_ that information, or at least highlight or prioritize that information in some way.

### **TL;DNR:**
- **I think switching the first error message with the last block of of global flags documentation info would provide the information to the user in a more consistently helpful and less frustrating way.**
- **I will actually do a pull request for this and am not just complainging.**
- **Also, I really like LXC/D and I'm interested in contributing and thought this would be a good first issue to start on.**
-

**Comment by stgraber** [comment] 2018-02-08 20:40
Going to treat this as a duplicate of #490 

The ordering and lack of subcommand handling is all caused by gnuflag being terrible, switching to urfave/cli will take care of this and reduce the massive wall of text to just the subcommand in question and will also make re-ordering the output much easier.

**Closed by stgraber** 2018-02-08 20:40 UTC

**Comment by lmlsna** [comment] 2018-02-08 20:44
I figured something like that might be the case, just wanted to check before I dove in. Thanks.
