### ISSUE TITLE
Image creation from container doesn't work

### ISSUE THREAD

**Issue by xabierlaiseca** [lxc/lxd#750] opened 2015-06-09 21:45 UTC
I'm trying to create a new image from an existing container using LXD API. 

I'm doing a ```POST``` request to ```/1.0/images``` with this payload:
```{"public":true,"source":{"type":"container","name":"test"},"properties":{}}```

I'm getting ```500``` status code back with this body:
```{"error":"Unsupported compression.","error_code":500,"type":"error"}```

**Comment by stgraber** [comment] 2015-06-10 22:20
The feature isn't supported yet (although it's specced and so present in the API spec).

This bug is essentially a duplicate of #707 which will cover the implementation of both the API and the client side of it (the publish command).

Closing this issue as a duplicate.

**Closed by stgraber** 2015-06-10 22:20 UTC
