### ISSUE TITLE
Error: Failed to retrieve PID of executing child process.

### ISSUE THREAD

**Issue by xsoalokinx** [lxc/lxd#8577] opened 2021-03-16 15:40 UTC
# Required information

 * Distribution: Gentoo/Linux
   * Kernel version: 5.4.97
   * LXC version: 4.0.6
   * LXD version: 4.11
   * Storage backend in use: zfs

# Issue description

After starting a container, and waiting some period of time, lxc exec stops working and produces the error "Failed to retrieve PID of executing child process."
stopping/restarting the container gets rid of the error temporarily. Not really sure what triggers it. And while this error is produced, the same error happens for ALL running containers.

**Comment by stgraber** [comment] 2021-03-16 18:13
@brauner ideas?

**Comment by brauner** [comment] 2021-03-16 18:51
> @brauner ideas?

Is this with all our backports?

**Comment by brauner** [comment] 2021-03-16 18:52
And can I please get logs from a failing  container with the daemon switched into verbose and debug?

snap set lxd daemon.debug=true
snap set lxd daemon.verbose=true

:)

**Comment by stgraber** [comment] 2021-03-16 20:28
@brauner it's Gentoo is unlikely to be snap.

@xsoalokinx can you run `lxc monitor --type=logging --pretty` in one terminal while reproducing the `lxc exec` failure in another?
Then give us both that monitor output and the `lxc info --show-log NAME` for that container.

**Comment by brauner** [comment] 2021-03-16 21:09
Ah, didn't see that it was gentoo on my phone.

**Comment by fling-** [comment] 2021-03-17 03:42
@stgraber  This happens on gentoo when you use `lxc` command while running portage with `cgroup` feature enabled.
It is easily reproducible:
1. First run emerge command:
`FEATURES="cgroup" emerge -1BOq gcc`
2. Then use `lxc` command while emerge is still running:
`lxc exec test bash`
3. Done, now you get `Error: Failed to retrieve PID of executing child process.` in every container until you restart them.

The following error appear in the log when `lxc` errors out.
```
cgfsng - cgroups/cgfsng.c:get_hierarchy:172 - There is no useable name=portage controller
cgfsng - cgroups/cgfsng.c:cgfsng_get_cgroup_do:2158 - No such file or directory - Failed to find hierarchy for controller "name=portage"
```

I'm unable to reproduce this after restarting lxd!

Temporary workaround:
Do not use `cgroup` portage feature (which is the default).

**Comment by brauner** [comment] 2021-03-17 08:25
See https://github.com/lxc/lxc/pull/3708
I'll backport this to stabl-4.0. We should probably consider making a release soon-ish.

**Comment by stgraber** [comment] 2021-03-17 12:42
Closing as the issue was in LXC and a fix has been merged now.

**Closed** 2021-03-17 12:42 UTC
