### ISSUE TITLE
LXD seems to forget which user it is after running for a few hours since snap update around January 24th

### ISSUE THREAD

**Issue by MSoegtropIMC** [lxc/lxd#11401] opened 2023-02-24 13:17 UTC
I am using LXD to build snaps in GitHub CI using https://github.com/snapcore/action-build. It did run fine for > 1 years and stopped working on January 25th. This is 100% reproducible with several versions of snap supplied LXD (but I didn't try the version from February 23rd).

The effect is that after running for a few hours something around user or group assignments gets messed up.

Below are a few pointers in the logs which show this. Upfront let me say that I am using "opam", a package manager for OCaml to build a large project, which takes 5 to 6 hours. The Github user "runner" is recognised as root by opam, so each call of opam produces a message "Warning:  Running as root is not recommended". Interestingly after the LXD update this message is not given any more after a few hours - and the build fails then. I do first one call of opam which runs for 5..6 hours which shows the message and after that a few additional calls to opam, which pin certain package versions to specific versions. Prior to the update these also showed the message, but after the update not. The second of these pinning calls fails then.

- Good case (January 24th and before):
  - [warning initial call](https://github.com/coq/platform/actions/runs/3992049821/jobs/6847519445#step:7:2571)
  - [warning pinning call](https://github.com/coq/platform/actions/runs/3992049821/jobs/6847519445#step:7:2969)

- Bad case (January 25th and later):
  - [warning initial call](https://github.com/coq/platform/actions/runs/4001890725/jobs/6873605430#step:7:2571)
  - [no warning pinning call](https://github.com/coq/platform/actions/runs/4001890725/jobs/6873605430#step:7:2970)
 
Since this behaviour is reproducible with several snap supplied versions, I don't give version details. I expect that there was an update to LXD back merged to all snap supplied versions which has this effect.

I can reproduce this behaviour also on a private machine with Ubuntu 22.04 LTS and latest snap provided LXD of 2 weeks back. I can provide a script which runs into this situation 100% (> 50 tests so far).

I also can pretty much exclude any other cause than an issue with LXD. Notably snapcraft runs fine with multipass instead of LXD. And as I said it did run fine with LXD for > 1 year with daily builds.

If you need any logs or the like, please let me know what exactly you need - I wouldn't call myself a Linux expert, so I would appreciate the exact commands I should run.

I will try the February 23rd snap version in the next days.

**Comment by stgraber** [comment] 2023-04-14 04:16
LXD can't "forget" to be root, that's just not something that's possible.
What I think this is, is the same bug as https://github.com/lxc/lxd/issues/11422 which is causing some output (in this case the root warning) to go missing on systems with a high CPU load.

**Comment by stgraber** [comment] 2023-04-14 04:16
Closing as duplicate of 11422

**Closed by stgraber** 2023-04-14 04:16 UTC

**Comment by MSoegtropIMC** [comment] 2023-04-14 06:57
I am not sure if it is the same - I am not just loosing output - the process also fails in a way that suggests that something got messed up with access rights. Also I don't run short instances of lxd - I run it for 5 hours and it runs fine for 5 hours and suddenly it has issues with access rights.

Furthermore I did the local tests on a 32 core thread ripper with 128Gb RAM with (for that machine) only rather modest relative load - this also differs from #11422. But the issue might not be the relative, but the absolute load, which should be about 20 threads on average in the tests (the TR can handle 64).

Still the root cause could be the same and for sure #11422 is much easier to reproduce, so I agree that it makes most sense to first follow this thread. I will simply retry my case after a fix of #11422 and see if it also fixes my issue.

**Comment by stgraber** [comment] 2023-04-15 02:31
LXD needs to run through extra hoops to run as non-root in a container, that's only done if the API request for the exec session comes specifically asking for another uid/gid. If the issue happens later as part of a long running exec session rather than a new exec session, then it's either a problem with the software running in the container or with the kernel as LXD doesn't have any control on what's run on the container beyond spawning the terminal initially.

**Comment by MSoegtropIMC** [comment] 2023-04-15 08:35
Knowing close to nothing about how LXD works, I can't say much about technical details beyond the effects I observe.

I didn't think about the possibility of a kernel bug, but looking at the fact that it stopped working on all snap supplied reasonably recent versions of LXD, it might also be that there was a kernel update around that date. I thought it was LXD, because I saw that all versions which did not work any more have been updated around January 25th in snap. Unfortunately this has the effect that it is hard to test an older version - I am not sure how to access older versions in a snap once a stream has been updated.

What might make sense, would be to review what has been changed in the January 25th release. I expect that the change list which has been back merged to all older snap versions of LXD is not that long. If you could point me to the back merge list, I could have a look.

I could also test a pre January 25th LXD snap package - I just have no idea how to get one. I didn't use snap locally before stating to debug the GitHub issue, so I don't have any older versions local and I don't see a way to download it from snap either.

**Comment by stgraber** [comment] 2023-04-15 16:43
What track are you on?

If you're on the latest track, then Jan 25th doesn't correspond to anything as we pushed things around Jan 13th and then Feb 14th or thereabout.

If you're on the 5.0 track (now 5.0.2), then Jan 25th is close to when 5.0.2 would have rolled out to users.
The problem with the 5.0 track is that it gets changes only every 3-6 months, so the delta between 5.0.1 and 5.0.2 is 1063 commits, so not something that's easy to go through ;)

**Comment by MSoegtropIMC** [comment] 2023-04-17 08:34
I need to check - unfortunately on the machine I am doing this the coolant pump is broken and it will take a few days to get it repaired, so it will take a few days until I answer.

But as far as I remember it was not the latest track, because GitHub didn't use the latest rack either.
