### ISSUE TITLE
Image server on Amazon

### ISSUE THREAD

**Issue by htbase** [lxc/lxd#4536] opened 2018-05-04 20:32 UTC
Hello folks

We are trying to use Ansible to automate some of our tasks on LXD.

We are hosting an image server on an EC2 (AWS) instance. When we execute the command:

lxc launch AWSHUB:<image> 

It works fine but when we execute from Ansible, it has a problem with the external and internal IP from Amazon.

Here is the Ansible:

  tasks:
    - name: Create a started container
      lxd_container:
        name: "{{ ctname }}"
        state: started
        source:
          type: image
          mode: pull
          server: https://<amazon external ip for hub>:8443

We receive the following error message:

fatal: [SERVER2]: FAILED! => {"actions": [], "changed": false, "msg": "Get https://<amazon external ip for hub>:8443/1.0: x509: certificate is valid for <amazon internal ip for hub>, not <amazon external ip for hub>"}

Any ideas?

Again, from the command line (lxc launch), it works fine

**Comment by stgraber** [comment] 2018-05-04 21:09
Support questions are usually best to ask at https://discuss.linuxcontainers.org
Closing the issue since this is not a bug to be fixed in LXD.

**Closed by stgraber** 2018-05-04 21:09 UTC

**Comment by stgraber** [comment] 2018-05-04 21:10
The problem you're running into here is likely because your image server isn't using a CA issued certificate so it doesn't pass validation by the LXD's CA certificates.

You have two ways of fixing that:
 - Get a valid certificate installed on your image server, you can issue such a certificate with only a tiny bit of effort by using letsencrypt.org
 - There may be a way for you to pass the expected certificate (self-signed) through ansible so that it lands in the "certificate" field in the API call. That should be a standard PEM (base64) encoded version of the server's certificate.

Either of those should make the validation work on the target LXD server.
