### ISSUE TITLE
LXD (snap) fails due to failing group lookup

### ISSUE THREAD

**Issue by fredldotme** [lxc/lxd#5591] opened 2019-03-22 15:16 UTC
# Required information

 * Distribution: Ubuntu
 * Distribution version: 19.04
 * The output of "lxc info" or if that fails:
   * Kernel version: Linux Alfreds-Laptop 5.0.0-7-generic #8-Ubuntu SMP Mon Mar 4 16:27:25 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
   * LXC version: stable:        3.11        2019-03-11 (10343) 56MB
   * LXD version: stable:        3.11        2019-03-11 (10343) 56MB
   * Storage backend in use: dir

# Issue description

The lxd daemon (snap variant) fails to launch due to not being able to lookup the 'lxd' group.

# Steps to reproduce

 1. Stop any remaining lxd instances: `sudo snap stop lxd`
 2. Restart: `sudo snap start lxd`
- OR -
 1. Stop any remaining lxd instances: `sudo snap stop lxd`
 2. Manual start: `sudo lxd --debug --group lxd`

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [x] Main daemon log: https://paste.ubuntu.com/p/WkkMXNrjyF/
 - [ ] Output of the client with --debug
 - [x] Output of the daemon with --debug: https://paste.ubuntu.com/p/Kgw8g2n9fn/

**Comment by stgraber** [comment] 2019-03-22 16:09
The LXD snap has logic to automatically create that group, so there's something odd going on on your system which is preventing this somehow.

Can you do:
 - snap start lxd
 - systemctl -a | grep snap.lxd
 - journalctl -u snap.lxd.daemon -n 600

Hopefully that will shed some light on what's happening on your system.

**Comment by fredldotme** [comment] 2019-03-22 17:17
I have the 'lxd' group set up from before when the lxd snap created its own group (gid 999).
Interestingly the service dies with `ldconfig: Input/output error` and errno 2 while `snap start` output says it exited with code 1.

- snap start lxd:
```
alfred@Alfreds-Laptop:~$ sudo snap start lxd
Fehler: cannot perform the following tasks:
- start of [lxd.activate lxd.daemon] (# systemctl start snap.lxd.activate.service snap.lxd.daemon.service
Job for snap.lxd.activate.service failed because the control process exited with error code.
See "systemctl status snap.lxd.activate.service" and "journalctl -xe" for details.
)
- start of [lxd.activate lxd.daemon] (exit status 1)
```

- systemctl -a | grep snap.lxd:
```
  snap-lxd-10150.mount                                                                                           loaded    active     mounted   Mount unit for lxd, revision 10150                                                          
  snap-lxd-10343.mount                                                                                           loaded    active     mounted   Mount unit for lxd, revision 10343                                                          
  snap-lxd-10422.mount                                                                                           loaded    active     mounted   Mount unit for lxd, revision 10422                                                          
  snap-lxd-9886.mount                                                                                            loaded    active     mounted   Mount unit for lxd, revision 9886                                                           
  snap-lxd-9919.mount                                                                                            loaded    active     mounted   Mount unit for lxd, revision 9919                                                           
  var-snap-lxd-common-ns-mntns.mount                                                                             loaded    active     mounted   /var/snap/lxd/common/ns/mntns                                                               
  var-snap-lxd-common-ns-shmounts.mount                                                                          loaded    active     mounted   /var/snap/lxd/common/ns/shmounts                                                            
  var-snap-lxd-common-ns.mount                                                                                   loaded    active     mounted   /var/snap/lxd/common/ns                                                                     
● snap.lxd.activate.service                                                                                      loaded    failed     failed    Service for snap application lxd.activate                                                   
● snap.lxd.daemon.service                                                                                        loaded    failed     failed    Service for snap application lxd.daemon                                                     
● snap.lxd.daemon.unix.socket                                                                                    loaded    failed     failed    Socket unix for snap application lxd.daemon
```

- journalctl -u snap.lxd.daemon -n 600
https://paste.ubuntu.com/p/CZ4zg8VbQ9/

**Comment by stgraber** [comment] 2019-03-22 17:49
You have disk corruption going on:
```
Mär 22 15:50:58 Alfreds-Laptop lxd.daemon[2890]: /snap/lxd/10343/commands/daemon.start: 100: /snap/lxd/10343/commands/daemon.start: ldconfig: Input/output error
```

Please show `dmesg` but I suspect you're going to see a bunch of I/O errors in there.

**Comment by stgraber** [comment] 2019-03-22 22:21
Closing this as there are indications that the kernel is misbehaving or the squashfs is corrupted in a way which prevents reading its content properly, this leads to that startup error and it restarting in a loop.

Assuming this isn't caused by an underlying bad disk or kernel and it's just a corrupted squashfs somehow, you may be able to force it to re-download with something like:
 - snap refresh lxd --edge
 - snap refresh lxd --stable

Or if you don't have any data in LXD yet, try removing it and installing it again.

**Closed by stgraber** 2019-03-22 22:21 UTC
