### ISSUE TITLE
LXD "lxc publish" command

### ISSUE THREAD

**Issue by popsicl** [lxc/lxd#6438] opened 2019-11-12 06:49 UTC
`root@lxd11vgtult:/lib/systemd/system# lxc --version
3.0.0`

`api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  -  manual
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFVjCCAz6gAwIBAgIRANI0TAAEspY1xEEZ659R3t0wDQYJKoZIhvcNAQELBQAw
    OTEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEZMBcGA1UEAwwQcm9vdEBs
    eGQxMXZndHVsdDAeFw0xOTExMDgwOTE2MTVaFw0yOTExMDUwOTE2MTVaMDkxHDAa
    BgNVBA...
    -----END CERTIFICATE-----
  certificate_fingerprint: 9d18413dff45805dee690940482b0b...
  driver: lxc
  driver_version: 3.0.3
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-45-generic
  server: lxd
  server_pid: 5224
  server_version: 3.0.0
  storage: ""
  storage_version: ""
  server_clustered: true
  server_name: lxd11vgtult`

We have 11 lxd servers and we are facing one huge problem. From lxc servers we push our old containers to our array storage and then we put them in lxd. (we create container with same lsb-release in lxd, stop it, delete rootfs, paste old containers rootfs in that one) and after these steps we always run command lxc publish to rewrite permissions, because lxd uses 100000, with 9 lxd servers out of 11 it works fine, but last two servers doesn't rewrite permissions and owner like it should do. Can you suggest something, because i can't find anything wrong in server. 

thank you in advance. 
I'm new here so sorry if somethings wrong let me know how to correctly write.

**Comment by stgraber** [comment] 2019-11-12 15:22
You should make sure all your servers are up to date, 3.0.0 is out of date, assuming you're running Ubuntu (looks like it based on kernel), you should get 3.0.3.

I'm also not sure what you're doing with `lxc publish` here. All that this command does is turn a container into an image, the image itself should be unshifted, but the container will normally not be altered as part of that. So maybe you're somehow relying on a bug from an older LXD or something?

Assuming that what you're trying to do is import unshifted containers into LXD, the way you'd normally do that is:
 - lxc init some-name --empty -c security.privileged=true
 - Make sure that `/var/lib/lxd/containers/some-name` is mounted
 - Copy the content into `/var/lib/lxd/containers/some-name/rootfs/`
 - lxc config unset some-name security.privileged
 - lxc start some-name

Or you could use the `lxd-p2c` tool which lets you remotely import a container into LXD by passing the URL of the target server, the name you want for the container and the path to the current unshifted rootfs. It will then use the migration API to transfer the content.

**Comment by stgraber** [comment] 2019-11-12 15:22
(Closing as report is on out of date LXD and seems to be relying on undefined internal behaviors)

**Closed by stgraber** 2019-11-12 15:22 UTC

**Comment by popsicl** [comment] 2019-11-12 19:12
Yes, we're runing 3.0.0, but we don't have problems with other 9 lxd nodes in cluster. And we always did (with about 30 containers from LXC) to rewrite permisions. 
To tell you step by step, it should go like this. 
copy whole container from LXC to array storage.
Create container in LXD. Stop it. Delete whole "rootfs". Paste LXC containers rootfs in there and after that just run command lxc publish containers-name. 
And after it completes it makes an image of that container and also rewrites all permissions and oweners from root's - 1000 (if i'm correct), to lxd root's - 100000. And it works with other 9 nodes perfectly in 3.0.0 but does not on the new ones. And i'm asking this, because we can't add new nodes to cluster with newer version of 3.0.3 because we get error like this: "Error: Failed to configure cluster: failed to request to add node: API version mismatch: cluster has 81" even thou i understand it like update for cluster not like newer version of it, but we get error.

**Comment by stgraber** [comment] 2019-11-12 21:36
I'm sorry but we can't support what you're currently doing.

You are almost certainly relying on a shifting bug to get your current behavior, `lxc publish` isn't the way to get the container to shift/unshift, what you're describing sounds like a bug.

I told you about the proper way to do what you're doing above, if you still hit the same issue when using `lxd-p2c` or the `lxc init --empty` approach I described, then we can investigate it further (though would insist on this being reproduced on 3.0.3 first).
