### ISSUE TITLE
ZFS rootfs mounts vanish

### ISSUE THREAD

**Issue by TehMino** [lxc/lxd#4137] opened 2018-01-04 20:13 UTC
* Distribution: Ubuntu
 * Distribution version: 17.10
 * The output of "lxc info" or if that fails:
```
config:
  core.https_address: 192.168.1.200:8443
  core.trust_password: true
  images.auto_update_interval: "24"
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 192.168.1.200:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFTDCCAzSgAwIBAgIQD5tg9+cedBB6heLgrdd/ojANBgkqhkiG9w0BAQsFADA2
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRYwFAYDVQQDDA1yb290QHVi
    dXNydjAxMB4XDTE3MTIyOTEyMzcwOVoXDTI3MTIyNzEyMzcwOVowNjEcMBoGA1UE
    ChMTbGludXhjb250YWluZXJzLm9yZzEWMBQGA1UEAwwNcm9vdEB1YnVzcnYwMTCC
    AiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAKHb76nwSnjSnIFwmcaPCy63
    4BpUr3ZmXyaMSVkwxHNIOCPVzscLMZU+gHGW+qTGgPQGw9jK3g9dWH+HBT1jxT+/
    dvarf96umlGiAn2ZRg0JgQcb+BwIthIDJoYht2xj/CMm1o7FKftA+DbTO7fhTwLM
    4xRnC2D1mYW9iYfTmnx8CwSiyhbh3GDKG/atHsgjC5OvV05I0E+vJUpoohX6QHNH
    KKjy359S6q7mvk5YaSuHXH+pL7SBc/QKEmykOjxFwf2eCCZ4XIC+CyigzcNudZwS
    L5J+F68H+fm+76iLqQh/3di8YDN+lP+ZiVTLvYaPxQ8VpCScXKw7cR95/coLGWAN
    yGikbweNckgMeprX1dOtPCXYXiX2hj/tsmL2lC9gLxKCJ9rABUIvUxcfpLAw7lo4
    GcGf4zua96WQjVGRx+k2DmUIKjhPd2PlX7cqdrqCrKaCr7KGon0b3copJgKiryyG
    0cOkJsgX+pI29UE2cP4qeeSlieAHkF7PAbBmb/G2IX4FIcR2vhANWRlfvDB1hIri
    LE1m6K8L2MXhIXe7IvUVuQkw+GIZytawyY2v1M6lSW4jAoyzrVGSg61Kgim7oEDk
    V5AVeoEUfgRw3UWDRMEn8a/6FLeUXAZROI1PLsuWTJ8RpjMM4vwgdCJf+n99EPXU
    xmsqewoMmnt7MFmRk5h7AgMBAAGjVjBUMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUE
    DDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMB8GA1UdEQQYMBaCCHVidXNydjAx
    hwTAqAHIhwQKAAMBMA0GCSqGSIb3DQEBCwUAA4ICAQBSVTRDQI8hDmM4/y/75MV7
    z9FKjURlCDQmelqMxF09jAgFn+RrbdTJpaI603NfpVe1M/quPMCITPEGw5v/9Nw8
    f5CrzIEdMks0vIvkZKaX70uHvcH/IeMFO+bzN+g/+PiH5sPsu+pmTumMzGyjsJ6I
    g+r8Auyeth5bJeAZRDAZkQ7oMALfj792fGwiWuY6RlQZ8ScIeMwGgumSeIjsxx4A
    8IZPHwAPDB9zqhgARMOnBQZdrLHiPguD00Ukat+JxO0VqiUy0fcdUrDxK86N4yla
    Y5FwDRvlpzELhuK4IFx+OXiFzf+sV7eNnvgWZYDolAeEMIAv12Fo9nAYqAllC7Yo
    2bWzlZekZM+pdclfz+MryfKxRwcw1yMaGbMSZ6wDtGlOKs7631lqbyzn3tej+4n7
    qBwWWtEu1Pz0A+MPVdPYPnnJdrIUHbYSR1NxIl4ugmEg+iyiCKuA7aNrthaD8Vke
    7R6fEDAiQ6X8jfvxSPSk2k06Vh53IL5c6dX6MtHDvCeobD0/7enn4sO7c67iWHqw
    EENAmzbUBRSbAMU6p28UE7fqOyx0JxEZO+rA52LpOQ3y5IUmDHj3KvEq/gbBS/6a
    HcxgbkmDvsPnzjZehc5SiycuQjTTjjV1JoCrAoS1NiL6DnLxaUixm2lHg5nOWod5
    zej++aITWyu0vaiwNK3X0Q==
    -----END CERTIFICATE-----
  certificate_fingerprint: b076687cd1f691e6316127dac597debb6a82fc1edf3c0ff73061481ec1c89cf4
  driver: lxc
  driver_version: 2.1.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.13.0-21-generic
  server: lxd
  server_pid: 5204
  server_version: "2.18"
  storage: zfs
  storage_version: 0.6.5.11-1ubuntu3
```

# Issue description

The rootfs of my containers sometimes disappear and are not mounted anymore.

```
root@ubusrv01:~# lxc ls
+------------+---------+--------------------------------+------+------------+-----------+
|    NAME    |  STATE  |              IPV4              | IPV6 |    TYPE    | SNAPSHOTS |
+------------+---------+--------------------------------+------+------------+-----------+
| ubudhcp01  | RUNNING | 192.168.1.202 (ethext)         |      | PERSISTENT | 0         |
|            |         | 10.0.0.2 (ethint)              |      |            |           |
+------------+---------+--------------------------------+------+------------+-----------+
| ubudns01   | RUNNING | 192.168.1.201 (ethext)         |      | PERSISTENT | 0         |
|            |         | 10.0.0.1 (ethint)              |      |            |           |
+------------+---------+--------------------------------+------+------------+-----------+
| uburvprx01 | RUNNING | 192.168.1.204 (ethext)         |      | PERSISTENT | 0         |
|            |         | 10.0.0.4 (ethint)              |      |            |           |
+------------+---------+--------------------------------+------+------------+-----------+
| ubuvpn01   | RUNNING | 192.168.1.203 (ethext)         |      | PERSISTENT | 0         |
|            |         | 10.8.0.1 (tun0)                |      |            |           |
|            |         | 10.0.0.3 (ethint)              |      |            |           |
+------------+---------+--------------------------------+------+------------+-----------+
```

```
root@ubusrv01:~# zfs list
NAME                                                                                        USED  AVAIL  REFER  MOUNTPOINT
rpool                                                                                      33.7G   181G    96K  /
rpool/ROOT                                                                                  800M   181G    96K  none
rpool/ROOT/ubuntu                                                                           800M  19.2G   746M  /
rpool/home                                                                                  576K  15.0G    96K  /home
rpool/home/root                                                                             480K  10.0G   480K  /root
rpool/lxd                                                                                  1003M   181G    96K  none
rpool/lxd/containers                                                                        484M   181G    96K  none
rpool/lxd/containers/ubudhcp01                                                             80.3M  9.92G   294M  /var/lib/lxd/storage-pools/lxd/containers/ubudhcp01
rpool/lxd/containers/ubudns01                                                               219M  9.79G   432M  /var/lib/lxd/storage-pools/lxd/containers/ubudns01
rpool/lxd/containers/uburvprx01                                                             100M  9.90G   333M  /var/lib/lxd/storage-pools/lxd/containers/uburvprx01
rpool/lxd/containers/ubuvpn01                                                              85.1M  9.92G   298M  /var/lib/lxd/storage-pools/lxd/containers/ubuvpn01
rpool/lxd/custom                                                                             96K   181G    96K  none
rpool/lxd/deleted                                                                           260M   181G    96K  none
rpool/lxd/deleted/images                                                                    259M   181G    96K  none
rpool/lxd/deleted/images/6dd4a229f30af3b1aad308630c89080ab0363fb157e6a0e02ff7fa5b019fc4d8   259M   181G   259M  none
rpool/lxd/images                                                                            259M   181G    96K  none
rpool/lxd/images/9107c5337b1a5d480aa99d523cb82c34f0b948e35909ff99abe5556924ee1cb7           259M   181G   259M  none
rpool/lxd/snapshots                                                                          96K   181G    96K  none
rpool/srv                                                                                    96K  10.0G    96K  /srv
rpool/swap                                                                                 31.9G   213G    64K  -
rpool/var                                                                                  97.1M  29.9G    96K  /var
rpool/var/cache                                                                            95.4M  4.91G  95.4M  /var/cache
rpool/var/log                                                                              1.33M  10.0G  1.33M  legacy
rpool/var/spool                                                                              96K  5.00G    96K  /var/spool
rpool/var/tmp                                                                               136K  10.0G   136K  legacy
```
```
root@ubusrv01:~# zfs mount
rpool/ROOT/ubuntu               /
rpool/var/log                   /var/log
rpool/var/tmp                   /var/tmp
rpool/home                      /home
rpool/home/root                 /root
rpool/srv                       /srv
rpool/var/cache                 /var/cache
rpool/var/spool                 /var/spool
rpool/lxd/containers/ubuvpn01   /var/lib/lxd/storage-pools/lxd/containers/ubuvpn01
```

```
root@ubusrv01:/var/lib/lxd/storage-pools/lxd/containers# ll
total 11
drwxr-xr-x 6 root   root   6 Jan  4 21:02 .
drwxr-xr-x 6 root   root   6 Dec 31 12:31 ..
drwxr-xr-x 2 root   root   2 Jan  2 18:26 ubudhcp01
drwxr-xr-x 2 root   root   2 Jan  2 16:27 ubudns01
drwxr-xr-x 2 root   root   2 Jan  3 23:15 uburvprx01
drwxr-xr-x 4 100000 100000 6 Jan  4 18:48 ubuvpn01
```

```
root@ubusrv01:/var/lib/lxd/storage-pools/lxd/containers# du -sh *
512     ubudhcp01
512     ubudns01
512     uburvprx01
304M    ubuvpn01
```

The containers are running fine but i can't access the rootfs via the mountpoint...

**Comment by stgraber** [comment] 2018-01-04 20:31
That's normal, the snap environment has its own mount namespace so the mounts that LXD is doing aren't visible outside of the snap environment.

If you must see those for some reason, your best bet is to look through "ps" for the pid of the "lxd" daemon itself, `ps aux | grep lxd.*group` should find that one for you.

Then look at /proc/PID/root/var/lib/lxd/storage-pools/lxd/containers so that you can see what the LXD daemon sees.

Closing as this is expected behavior for a snap.

**Closed by stgraber** 2018-01-04 20:31 UTC

**Comment by TehMino** [comment] 2018-01-04 21:16
Hmm sorry if if misunderstand something, but how do you see this is a snap ?
Because i installed lxd from the repository. Maybe i'm thinking wrong here ?
```
root@ubusrv01:~# dpkg -L snapd
dpkg-query: package 'snapd' is not installed
```
```
root@ubusrv01:~# history | grep 'apt install lxd'
  341  [2017-12-29 13:25:51] apt install lxd lxd-client lxd-tools
```
```
root@ubusrv01:~# cat /etc/apt/sources.list
deb http://archive.ubuntu.com/ubuntu artful main universe
deb http://security.ubuntu.com/ubuntu artful-security main universe
deb http://archive.ubuntu.com/ubuntu artful-updates main universe
```
And what i don't understand is why i see some roots containers, as what i'm expecting is seeing nothing or all the containers rootfs.
I executed your command : 
```
root@ubusrv01:~# ps aux | grep lxd.*group | grep -v grep
root      5204  0.0  0.1 1660476 57080 ?       Ssl  18:59   0:02 /usr/bin/lxd --group lxd --logfile=/var/log/lxd/lxd.log
```
```
root@ubusrv01:~# ll /proc/5204/root/var/lib/lxd/storage-pools/lxd/containers
total 11
drwxr-xr-x 6 root   root   6 Jan  4 21:02 .
drwxr-xr-x 6 root   root   6 Dec 31 12:31 ..
drwxr-xr-x 2 root   root   2 Jan  2 18:26 ubudhcp01
drwxr-xr-x 2 root   root   2 Jan  2 16:27 ubudns01
drwxr-xr-x 2 root   root   2 Jan  3 23:15 uburvprx01
drwxr-xr-x 4 100000 100000 6 Jan  4 18:48 ubuvpn01
```
```
root@ubusrv01:~# du -sh /proc/5204/root/var/lib/lxd/storage-pools/lxd/containers/*
512     /proc/5204/root/var/lib/lxd/storage-pools/lxd/containers/ubudhcp01
512     /proc/5204/root/var/lib/lxd/storage-pools/lxd/containers/ubudns01
512     /proc/5204/root/var/lib/lxd/storage-pools/lxd/containers/uburvprx01
304M    /proc/5204/root/var/lib/lxd/storage-pools/lxd/containers/ubuvpn01
```

**Comment by stgraber** [comment] 2018-01-05 03:52
Oh, oops, I somehow misread the paths as /var/snap for some reason :)

So looks like you're instead just being caught by the fact that LXD mounts the containers on-demand, so only running containers will be mounted. You may also be hit by the issue that even for running containers, the host mount may go away if the image the container was based on gets expired.
Those are unfortunately zfs issues and are expected behavior as far as LXD is concerned...

If your containers aren't running and you need access to their filesystem, you should be able to arrange that using `zfs mount` and `zfs unmount`.
If the containers are running and zfs unmounted things automatically, then you're out of luck as zfs will not allow you to mount those again (this is being tracked as a zfs bug). In which case, rebooting the affected containers should solve this, or otherwise you'll need to use the /proc/PID/root/ trick but using the pid of something inside the container this time, which will let you see that zfs filesystem from inside the container.
