### ISSUE TITLE
Error when running shutdown of a instance

### ISSUE THREAD

**Issue by lucasmoura** [lxc/lxd#8331] opened 2021-01-13 18:32 UTC
# Required information

 * Distribution: bionic
 * Distribution version: 18.04.5
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-59-generic
   * LXC version: 4.10
   * LXD version: 4.10
   * Storage backend in use: ext4

# Issue description

Sometimes, when shutting down an instance. Looking at the logs, I get the following error msg:

```
Location: none
Remote: unix://
Architecture: x86_64
Created: 2021/01/13 15:45 UTC
Status: Stopped
Type: container
Profiles: default

Log:

lxc ubuntu-behave-image-build--xenial1610552373112973 20210113154521.142 WARN     cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1152 - File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.monitor.ubuntu-behave-image-build--xenial1610552373112973"
lxc ubuntu-behave-image-build--xenial1610552373112973 20210113154521.144 WARN     cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1152 - File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.payload.ubuntu-behave-image-build--xenial1610552373112973"
lxc ubuntu-behave-image-build--xenial1610552373112973 20210113154521.152 WARN     cgfsng - cgroups/cgfsng.c:fchowmodat:1573 - No such file or directory - Failed to fchownat(17, memory.oom.group, 1000000000, 0, AT_EMPTY_PATH | AT_SYMLINK_NOFOLLOW )
lxc 20210113154615.391 WARN     commands - commands.c:lxc_cmd_rsp_recv:126 - Connection reset by peer - Failed to receive response for command "get_state"
```

# Steps to reproduce
This issue seems to appear randomly, so there is no steps to reproduce it

**Comment by stgraber** [comment] 2021-01-13 18:36
Nothing shown here looks wrong. Those warning messages are harmless and seen on most containers.

**Comment by stgraber** [comment] 2021-01-13 18:41
Chatting privately, it seems like the issue is something in the container calling `shutdown` and then the container not actually shutting down. When this happens, the issue is usually in the container with some service not wanting to shut down or some systemd issue.

During such a clean shutdown, LXD isn't involved at all, other than once init in the container exits, it unmounts the storage of the instance and releases any of its devices.

Closing for now, feel free to reopen when you have more details about what's going on and if it then looks like there's still some issue involving LXD.

**Closed by stgraber** 2021-01-13 18:41 UTC
