### ISSUE TITLE
Failed to join cluster, master node now offline

### ISSUE THREAD

**Issue by 19wolf** [lxc/lxd#5434] opened 2019-01-26 04:02 UTC
This is a soft continuation of #5423, in that this is _probably_ the error I was trying to fix when I broke it last time.

I tried to connect Talos to Nephele with lxd clustering, and failed. Now Nephele won't start because it doesn't have enough votes. How can I fix this?

```
$ sudo lxd --debug --group lxd
DBUG[01-25|22:21:09] Connecting to a local LXD over a Unix socket 
DBUG[01-25|22:21:09] Sending request to LXD                   method=GET url=http://unix.socket/1.0 etag=
INFO[01-25|22:21:09] LXD 3.9 is starting in normal mode       path=/var/snap/lxd/common/lxd
INFO[01-25|22:21:09] Kernel uid/gid map: 
INFO[01-25|22:21:09]  - u 0 0 4294967295 
INFO[01-25|22:21:09]  - g 0 0 4294967295 
INFO[01-25|22:21:09] Configured LXD uid/gid map: 
INFO[01-25|22:21:09]  - u 0 1000000 1000000000 
INFO[01-25|22:21:09]  - g 0 1000000 1000000000 
WARN[01-25|22:21:09] CGroup memory swap accounting is disabled, swap limits will be ignored. 
INFO[01-25|22:21:09] Kernel features: 
INFO[01-25|22:21:09]  - netnsid-based network retrieval: no 
INFO[01-25|22:21:09]  - uevent injection: yes 
INFO[01-25|22:21:09]  - unprivileged file capabilities: yes 
INFO[01-25|22:21:09] Initializing local database 
DBUG[01-25|22:21:09] Initializing database gateway 
DBUG[01-25|22:21:09] Start database node                      id=1 address=192.168.1.1:8443
DBUG[01-25|22:21:09] Raft: Restored from snapshot 59-1868835-1548470755354 
DBUG[01-25|22:21:09] Raft: Initial configuration (index=1868866): [{Suffrage:Voter ID:1 Address:0} {Suffrage:Voter ID:5 Address:192.168.1.3:8443}] 
DBUG[01-25|22:21:09] Raft: Node at 192.168.1.1:8443 [Follower] entering Follower state (Leader: "") 
DBUG[01-25|22:21:09] Dqlite: starting event loop 
DBUG[01-25|22:21:09] Dqlite: accepting connections 
DBUG[01-25|22:21:09] Connecting to a local LXD over a Unix socket 
DBUG[01-25|22:21:09] Sending request to LXD                   method=GET url=http://unix.socket/1.0 etag=
DBUG[01-25|22:21:09] Detected stale unix socket, deleting 
DBUG[01-25|22:21:09] Detected stale unix socket, deleting 
INFO[01-25|22:21:09] Starting /dev/lxd handler: 
INFO[01-25|22:21:09]  - binding devlxd socket                 socket=/var/snap/lxd/common/lxd/devlxd/sock
INFO[01-25|22:21:09] REST API daemon: 
INFO[01-25|22:21:09]  - binding Unix socket                   socket=/var/snap/lxd/common/lxd/unix.socket
INFO[01-25|22:21:09]  - binding TCP socket                    socket=192.168.1.1:8443
INFO[01-25|22:21:09] Initializing global database 
DBUG[01-25|22:21:09] Found cert                               k=0
DBUG[01-25|22:21:09] Dqlite: server connection failed err=failed to establish network connection: 503 Service Unavailable address=192.168.1.1:8443 attempt=0 
DBUG[01-25|22:21:09] Dqlite: connection failed err=no available dqlite leader server found attempt=0 
DBUG[01-25|22:21:10] Found cert                               k=0
DBUG[01-25|22:21:10] Dqlite: server connection failed err=failed to establish network connection: 503 Service Unavailable address=192.168.1.1:8443 attempt=1 
DBUG[01-25|22:21:10] Dqlite: connection failed err=no available dqlite leader server found attempt=1 
DBUG[01-25|22:21:10] Found cert                               k=0
DBUG[01-25|22:21:10] Dqlite: server connection failed err=failed to establish network connection: 503 Service Unavailable address=192.168.1.1:8443 attempt=2 
DBUG[01-25|22:21:10] Dqlite: connection failed err=no available dqlite leader server found attempt=2 
DBUG[01-25|22:21:10] Found cert                               k=0
DBUG[01-25|22:21:10] Dqlite: server connection failed err=failed to establish network connection: 503 Service Unavailable address=192.168.1.1:8443 attempt=3 
DBUG[01-25|22:21:10] Dqlite: connection failed err=no available dqlite leader server found attempt=3 
DBUG[01-25|22:21:11] Found cert                               k=0
DBUG[01-25|22:21:11] Dqlite: server connection failed err=failed to establish network connection: 503 Service Unavailable address=192.168.1.1:8443 attempt=4 
DBUG[01-25|22:21:11] Dqlite: connection failed err=no available dqlite leader server found attempt=4 
DBUG[01-25|22:21:12] Found cert                               k=0
DBUG[01-25|22:21:12] Dqlite: server connection failed err=failed to establish network connection: 503 Service Unavailable address=192.168.1.1:8443 attempt=5 
DBUG[01-25|22:21:12] Dqlite: connection failed err=no available dqlite leader server found attempt=5 
DBUG[01-25|22:21:13] Found cert                               k=0
DBUG[01-25|22:21:13] Dqlite: server connection failed err=failed to establish network connection: 503 Service Unavailable address=192.168.1.1:8443 attempt=6 
DBUG[01-25|22:21:13] Dqlite: connection failed err=no available dqlite leader server found attempt=6 
WARN[01-25|22:21:13] Raft: Heartbeat timeout from "" reached, starting election 
DBUG[01-25|22:21:13] Raft: Node at 192.168.1.1:8443 [Candidate] entering Candidate state in term 489 
DBUG[01-25|22:21:14] Raft: Votes needed: 2 
DBUG[01-25|22:21:14] Raft: Vote granted from 1 in term 489. Tally: 1 
WARN[01-25|22:21:14] Raft: Unable to get address for server id 5, using fallback address 192.168.1.3:8443: No such object 
DBUG[01-25|22:21:14] Found cert                               k=0
DBUG[01-25|22:21:14] Dqlite: server connection failed err=failed to establish network connection: 503 Service Unavailable address=192.168.1.1:8443 attempt=7 
DBUG[01-25|22:21:14] Dqlite: connection failed err=no available dqlite leader server found attempt=7 
DBUG[01-25|22:21:15] Found cert                               k=0
^C
```

**Comment by 19wolf** [comment] 2019-01-26 05:02
I was able to restore from `/var/snap/lxd/common/lxd/database/global.bak/`

**Comment by stgraber** [comment] 2019-01-26 14:13
Can you run:
 - lxd sql global "SELECT * FROM nodes;"
 - lxd sql local "SELECT * FROM raft_nodes;"

**Comment by stgraber** [comment] 2019-01-26 14:14
Also, to track down the source of the clustering failure, can you show:
 - lxd sql global "SELECT * FROM config;"
 - lxd sql local "SELECT * FROM config;"

**Comment by 19wolf** [comment] 2019-01-28 02:16
Sorry, had a busy weekend. Here's the information you requested: 
```
[21:15:12] nephele@nephele:~$ lxd sql global "SELECT * FROM nodes;"
+----+------+-------------+---------+--------+----------------+-------------------------------------+---------+
| id | name | description | address | schema | api_extensions |              heartbeat              | pending |
+----+------+-------------+---------+--------+----------------+-------------------------------------+---------+
| 1  | none |             | 0.0.0.0 | 13     | 115            | 2019-01-27T21:15:12.943991774-05:00 | 0       |
+----+------+-------------+---------+--------+----------------+-------------------------------------+---------+
[21:15:16] nephele@nephele:~$ lxd sql local "SELECT * FROM raft_nodes;"
+----+------------------+
| id |     address      |
+----+------------------+
| 1  | 192.168.1.1:8443 |
+----+------------------+
[21:15:26] nephele@nephele:~$ lxd sql global "SELECT * FROM config;"
+----+---------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id |         key         |                                                                                              value                                                                                               |
+----+---------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1  | core.trust_password | 423adc98534597c2deba77bb439c052a2cb2c03dce69b42ca477afaa05dd904f0ac7c39e949d4ff21d2ce7cd4964c20186c128a3567aca11bc50915ed65c81198c613754583a57645c3134f89e6cfff25862b0b5ef2be3298c715c4d8b8b6dbc |
+----+---------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
[21:15:32] nephele@nephele:~$ lxd sql local "SELECT * FROM config;"
+----+-----------------------+------------------+
| id |          key          |      value       |
+----+-----------------------+------------------+
| 4  | core.https_address    | 192.168.1.1:8443 |
| 5  | cluster.https_address | 192.168.1.1:8443 |
+----+-----------------------+------------------+
```

**Comment by freeekanayaka** [comment] 2019-01-28 06:55
Your database is inconsistent. The ```raft_nodes``` table indicates that you are clustered, while the ```nodes``` table indicates that you are not.

If you provide the steps to reproduce the issue we can try to fix it.

To recover nephele, you can reset clustering manually:

```
lxd sql local "DELETE FROM raft_nodes;"
lxd sql local "DELETE FROM config;"
```

then restart LXD and reconfigure clustering.

**Comment by cyberwillis** [comment] 2019-02-12 06:33
@freeekanayaka 
I just made a test create a cluster with 3 nodes
removed one node of the cluster and tried to use the same --preseed again to join again gave me an error:
**Error: Failed to join cluster: This server is already clustered**

After executing this command you mentioned earlier I could reuse the preseed again
```
lxd sql local "DELETE FROM config;"
```

**Comment by freeekanayaka** [comment] 2019-02-12 07:41
@cyberwillis ok, thanks for the info. So I guess the bug happens when you remove a node from a cluster and then join it again immediately. Generally speaking, re-joining the same node it's not a operation that we currently support (doing that in way that works for any case might be tricky), so when a node gets removed you're expected to wipe it before joining it again. However we might fix simple cases like this one.

**Comment by stgraber** [comment] 2019-02-12 14:51
@freeekanayaka I would expect the node to fail to join due to having existing storage, network, projects, containers, ... but it shouldn't fail to join because it thinks it's still clustered, after leaving a cluster, the node should act like a standalone node.

**Comment by cyberwillis** [comment] 2019-02-12 16:00
@stgraber  , @freeekanayaka , thank you for the clear my mind, make much more sense now. :)

**Comment by stgraber** [comment] 2019-02-28 10:22
Ok, so to explain what we've done (and closing this).

The short version is that we cannot have a node leave the cluster and turn itself back into a standalone node without significant database surgery, including modifications to the raft log (and potentially having to first replicate the database if the node wasn't a DB node itself).

So instead what we'll be doing to avoid accidents is:
 - Prevent a node from leaving the cluster if it's got stuff on it (containers, images, storage volumes)
 - Allow for it to be forced with `--force` but print a very clear message of what's going to happen and require confirmation
 - Have the node better detect that they're no longer clustered on startup and refuse to respond to queries

This is by and large done with the pull request form free. Trying it here, I'm getting:
```
root@nuc02:~# lxc cluster remove nuc02
Error: Node still has the following containers: a2

root@nuc02:~# lxc cluster remove nuc02 --force
Forcefully removing a server from the cluster should only be done as a last
resort.

The removed server will not be functional after this action and will require a
full reset of LXD, losing any remaining container, image or storage volume
that the server may have held.

When possible, a graceful removal should be preferred, this will require you to
move any affected container, image or storage volume to another server prior to
the server being cleanly removed from the cluster.

The --force flag should only be used if the server has died, been reinstalled
or is otherwise never expected to come back up.

Are you really sure you want to force removing nuc02? (yes/no): ^C
root@nuc02:~# 
```

This should avoid most issues and still allow us for some very specific disaster/data recovery to happen if absolutely needed.

Closing the issue.

**Closed by stgraber** 2019-02-28 10:22 UTC
