### ISSUE TITLE
need a spec for profiles

### ISSUE THREAD

**Issue by tych0** [lxc/lxd#139] opened 2015-01-19 22:55 UTC
We need a spec for profiles, in particular:

* what meta-keys are we going to allow? e.g. resources.memory = 25%
* we're storing these in a DB (i.e. not in the LXC config file), so what does the schema look like (this is probably pretty simple)
* what happens if someone sets a lxc.foo key instead of one of our predefined ones above? I guess we want to provide some way to set (and get?) arbitrary lxc.* keys, perhaps it is via this mechanism.

**Comment by kunalkushwaha** [comment] 2015-01-20 12:16
Any specific reason to use DB over simple file?

I think, simple config file + entry points for simple(shell) provisioning scripts would be useful to user. 
i.e define LXC configuration like memory, cpu, storage, networking etc + any provisioning code like installing some packages or copying some config file.

something like vagrantfile or Dockerfile.

If profiles are stored in DB, There need to be an additional configuration tool, which should accept users input to generate config file.

**Comment by stgraber** [comment] 2015-01-20 15:32
Sounds like the first part of the database spec will have to be "why a database?" :)
And it's a fair question.

We actually didn't think we'd gain anything by using one until pretty recently (and that's why it's not already part of LXD).
The main goal behind using a database (and we're talking sqlite here, not a big fancy engine) is so we can do very quick queries without having to parse thousands of files.

We expect LXD to be able to handle several thousands containers even on relatively common hardware (I'm doing that on my Haswell i5 laptop with just 8GB of RAM), that means that answering "what containers are using br25" becomes a very expensive query which requires lxd to parse every single container config.

The LXD API and command line have also been designed to abstract the container technology away (though we will let users set lxc.* keys in their configs and profiles) so we really shouldn't be using LXC's own config files to store lxd config properties.

As a result the current thought is that we will:
 - Store the container settings, server settings, profiles, certificates, ... in a sqlite database.
 - On container startup, the LXC config files will be generated from the database config


Also to clarify exactly what profiles are. A profile is simply a set of config keys and it's meant as a way to avoid needless container config duplication.

An example without profiles would be:
lxc create images:lxc-images/ubuntu/trusty/amd64/default ct1
lxc config ct1 resources.cpus 2
lxc config ct1 resources.memory 2G
lxc config ct1 resources.networks lxcbr0,br1
lxc start ct1

lxc create images:lxc-images/ubuntu/trusty/amd64/default ct2
lxc config ct2 resources.cpus 2
lxc config ct2 resources.memory 2G
lxc config ct2 resources.networks lxcbr0,br1
lxc start ct2

Now with profiles, it'd be:
lxc config profile create test
lxc config profile set test resources.cpus 2
lxc config profile set test resources.memory 2G
lxc config profile set test resources.networks lxcbr0,br1

lxc start images:lxc-images/ubuntu/trusty/amd64/default ct1 -p test
lxc start images:lxc-images/ubuntu/trusty/amd64/default ct2 -p test

**Comment by kunalkushwaha** [comment] 2015-01-21 12:13
Thanks for background of this approach. 
It sounds well aligned with the problem you mentioned.

I was thinking from user/programmers perspective, who want to define LXC machine with distribute them among teams / clients etc.

A simple use-case. 
Migrating old RHEL/CentOS instances running on baremetal to LXC instances, 
One can write provisioning code along with machine definition, and could use this for build those instances in one command.

I was thinking from orchestration point of view.
May be a different tool, can be implemented to provide such feature.

**Comment by eraclitux** [comment] 2015-01-21 21:02
> Sounds like the first part of the database spec will have to be "why a database?" :)

In the future I think a fancy database backed could pay off. Let me do and example: powedns. It uses a modular backend architecture (mysql, postgres and others). This allows it to use native mysql's replication to make an HA setup easier (in fact dns replication is entirely realized via mysql).

So lxd could implement a pluggable backend architecture that allow to start simple and small (sqllite which doesn not need any daemon at all, just files on disk). My experience with mysql replication in production is very positive, it just works.

**Comment by stgraber** [comment] 2015-01-21 21:07
Well, I certainly see how it makes sense for a service but not so much for lxd.

lxd runs on each compute node of your cluster. If you loose a compute node, having a duplicate of its database will be no good to you since you'll have lost the containers anyway.

What needs to be HA is whatever talks to lxd and keeps track of containers at an higher level. That's typically going to be OpenStack which does support multiple databases and HA properly.

**Closed** 2015-01-30 14:12 UTC
Labels: Release critical, Specification
