### ISSUE TITLE
btrfs: disk usage optimisation when copying containers and images to a remote host

### ISSUE THREAD

**Issue by gaetanquentin** [lxc/lxd#2898] opened 2017-02-16 16:28 UTC
tested with lxd 2.0.6 and 2.8.

Just a question about btrfs disk  usage differences between source host and remote host destination.

If i copy image and containers created from it , from my source host to a remote host, should i have the same disk usage for the image and containers  between source host and destination host?

It looks like it is  not.

I am using this tool: https://github.com/agronick/btrfs-size.git   to show real size of btrfs subvolumes/snapshots : this tool show size of the volumes and exclusive size of volumes/snapshots. For example, when we do snapshot, we can see difference disk usage between source subvolume and snapshots.

on my source lxd host, btrfs-size show optimized size of containers.
But after copying into remote (images first and then containers), the containers are full sized, like it was not a snapshot.

Should we use btrfs tools (send/receive) directly instead of lxc copy to have optimized remote copies?

**Comment by stgraber** [comment] 2017-02-16 16:43
The disk usage will typically be a bit bigger on the target. The reason for that is that there is no reproducible way to import an image into a btrfs subvolume. So the source container is based on its image but when transferring to the target, the same image (if it exists) on the target is a different subvolume and so prevents us from using it as the parent of the container's subvolume.

So we instead have to send the container as a full individual subvolume, causing the container to use more disk space, especially if it shared a lot of files with its source image.

We'd love for there to be a reliable, supported way to reproducibly convert an identical filesytem tree into a btrfs subvolume or zfs filesystem with a reproducible uuid/guid that can then be used as the parent when copying between hosts. Unfortunately it doesn't appear to be something that the btrfs and zfs communities are interested in.

**Closed by stgraber** 2017-02-16 16:43 UTC

**Comment by gaetanquentin** [comment] 2017-02-17 08:11
Tools like buttersink (https://github.com/AmesCornish/buttersink) can  transfer snapshots specifying parent btrfs uuid , so sizes are same on destination: so it is possible? If lxd keep track of uuid / parent uuid while transfering, it could do the same?

**Comment by stgraber** [comment] 2017-02-17 15:24
No, LXD does specify the parent whenever it can, we do that when transfering the container snapshots so that there's no duplication with the container itself. But that fails when you try to do it with the container and the image it was created on, because even if you specify the parent btrfs uuid, btrfs will fail due to the parent not actually being identical.

That's what I tried to describe above.
