### ISSUE TITLE
Unable to start lxd daemon: "Error creating database"

### ISSUE THREAD

**Issue by balajeerc** [lxc/lxd#8106] opened 2020-10-31 12:51 UTC
I am trying to run lxd on admittedly unconventional hardware. This is basically an old Android Moto G5S Plus that I had lying around.

lxd is being run within a chroot environment with `Arch Linux armhf` build.

This kernel does not support `cgroups`, does not have support for user namespaces. 

When running lxd daemon, I run into an error talking about missing database. 

Output from `lxd` when starting with debug information:

```
-sh-5.0$ sudo lxd --debug
INFO[10-31|17:38:19] LXD 4.7 is starting in normal mode       path=/var/lib/lxd
INFO[10-31|17:38:19] Kernel uid/gid map: 
INFO[10-31|17:38:19]  - u 0 0 0 
INFO[10-31|17:38:19]  - g 0 0 0 
WARN[10-31|17:38:19] No available uid/gid map could be found 
WARN[10-31|17:38:19] Only privileged containers will be able to run 
WARN[10-31|17:38:19] AppArmor support has been disabled because of lack of kernel support 
INFO[10-31|17:38:19] Kernel features: 
INFO[10-31|17:38:19]  - closing multiple file descriptors efficiently: no 
DBUG[10-31|17:38:19] failed to set network namespace identifier 
INFO[10-31|17:38:19]  - netnsid-based network retrieval: no 
INFO[10-31|17:38:19]  - pidfds: no 
INFO[10-31|17:38:19]  - uevent injection: no 
INFO[10-31|17:38:19]  - seccomp listener: no 
INFO[10-31|17:38:19]  - seccomp listener continue syscalls: no 
INFO[10-31|17:38:19]  - seccomp listener add file descriptors: no 
INFO[10-31|17:38:19]  - attach to namespaces via pidfds: no 
INFO[10-31|17:38:19]  - safe native terminal allocation : no 
INFO[10-31|17:38:19]  - unprivileged file capabilities: no 
INFO[10-31|17:38:19]  - cgroup layout: legacy 
WARN[10-31|17:38:19]  - Couldn't find the CGroup blkio, I/O limits will be ignored 
WARN[10-31|17:38:19]  - Couldn't find the CGroup blkio.weight, I/O weight limits will be ignored 
WARN[10-31|17:38:19]  - Couldn't find the CGroup CPUset controller, CPU pinning will be ignored 
WARN[10-31|17:38:19]  - Couldn't find the CGroup devices controller, device access control won't work 
WARN[10-31|17:38:19]  - Couldn't find the CGroup freezer controller, pausing/resuming containers won't work 
WARN[10-31|17:38:19]  - Couldn't find the CGroup hugetlb controller, hugepage limits will be ignored 
WARN[10-31|17:38:19]  - Couldn't find the CGroup memory controller, memory limits will be ignored 
WARN[10-31|17:38:19]  - Couldn't find the CGroup network class controller, network limits will be ignored 
WARN[10-31|17:38:19]  - Couldn't find the CGroup pids controller, process limits will be ignored 
WARN[10-31|17:38:19]  - Couldn't find the CGroup memory swap accounting, swap limits will be ignored 
INFO[10-31|17:38:19]  - shiftfs support: no 
INFO[10-31|17:38:19] Initializing local database 
EROR[10-31|17:38:19] Failed to start the daemon: Error creating database: failed to begin transaction: unable to open database file: no such file or directory 
INFO[10-31|17:38:19] Starting shutdown sequence 
DBUG[10-31|17:38:19] Not unmounting temporary filesystems (containers are still running) 
Error: Error creating database: failed to begin transaction: unable to open database file: no such file or directory
```

Distribution version:

```
-sh-5.0$ cat /etc/os-release
NAME="Arch Linux ARM"
PRETTY_NAME="Arch Linux ARM"
ID=archarm
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinuxarm.org/"
DOCUMENTATION_URL="https://archlinuxarm.org/wiki"
SUPPORT_URL="https://archlinuxarm.org/forum"
BUG_REPORT_URL="https://github.com/archlinuxarm/PKGBUILDs/issues"
LOGO=archlinux
```

Kernel version:

```
-sh-5.0$ uname -a
Linux localhost 3.18.71-perf-gfde333e #1 SMP PREEMPT Tue Aug 13 15:23:08 CDT 2019 armv7l GNU/Linux
```

**Comment by stgraber** [comment] 2020-10-31 17:13
Can you run lxd under "strace -f" to see exactly what it's doing?

**Comment by balajeerc** [comment] 2020-11-01 04:13
@stgraber Thanks for responding.

Attaching the output from `strace -f lxd --debug > /tmp/strace_lxd.txt 2>&1`:

[strace_lxd.txt](https://github.com/lxc/lxd/files/5470184/strace_lxd.txt)

**Comment by stgraber** [comment] 2020-11-01 19:54
What do you have in `/var/lib/lxd/`?

The error suggests that `/var/lib/lxd/database` doesn't exist somehow.

**Comment by balajeerc** [comment] 2020-11-02 01:53
`/var/lib/lxd` seems to have a series of subdirectories, one of which is indeed `database` but that subdirectory seems to be empty.

```bash
[root@localhost lxd]# cd /var/lib/lxd
[root@localhost lxd]# ls
backups     database  devlxd  images	security  snapshots	 virtual-machines
containers  devices   disks   networks	shmounts  storage-pools  virtual-machines-snapshots
[root@localhost lxd]# cd database/
[root@localhost database]# ls
[root@localhost database]#
```

**Comment by stgraber** [comment] 2020-11-02 01:56
Ok, that's pretty weird. Your strace shows an open of /var/lib/lxd/database/local.db with O_CREAT which fails suggesting the parent directory doesn't exist...

What does `touch /var/lib/lxd/database/local.db` get you?

**Comment by balajeerc** [comment] 2020-11-02 01:59
Just works:

```
-sh-5.0$ sudo touch /var/lib/lxd/database/local.db
```

**Comment by balajeerc** [comment] 2020-11-02 02:07
From skimming through the code in `lxd/db/db.go::OpenNode` function where this error seems to be originating from, I can see that it's SQLITE libraries that the function attempts to create. 

If this is useful in anyway: I am able to confirm that sqlite3 is indeed installed and am able to create SQLITE files using the command-line `sqlite3` tool, create tables etc.

**Comment by stgraber** [comment] 2020-11-02 02:08
How does it behave now that the file exists (albeit empty)?

**Comment by balajeerc** [comment] 2020-11-02 02:19
Tried running it again with the empty file already present:

```
sh-5.0$ sudo lxd --debug
INFO[11-02|07:43:36] LXD 4.7 is starting in normal mode       path=/var/lib/lxd
INFO[11-02|07:43:36] Kernel uid/gid map: 
INFO[11-02|07:43:36]  - u 0 0 0 
INFO[11-02|07:43:36]  - g 0 0 0 
WARN[11-02|07:43:36] No available uid/gid map could be found 
WARN[11-02|07:43:36] Only privileged containers will be able to run 
WARN[11-02|07:43:36] AppArmor support has been disabled because of lack of kernel support 
INFO[11-02|07:43:36] Kernel features: 
sh-5.0$ sudo lxd --debug
INFO[11-02|07:46:11] LXD 4.7 is starting in normal mode       path=/var/lib/lxd
INFO[11-02|07:46:11] Kernel uid/gid map: 
INFO[11-02|07:46:11]  - u 0 0 0 
INFO[11-02|07:46:11]  - g 0 0 0 
WARN[11-02|07:46:11] No available uid/gid map could be found 
WARN[11-02|07:46:11] Only privileged containers will be able to run 
WARN[11-02|07:46:11] AppArmor support has been disabled because of lack of kernel support 
INFO[11-02|07:46:11] Kernel features: 
INFO[11-02|07:46:11]  - closing multiple file descriptors efficiently: no 
DBUG[11-02|07:46:11] failed to set network namespace identifier 
INFO[11-02|07:46:11]  - netnsid-based network retrieval: no 
INFO[11-02|07:46:11]  - pidfds: no 
INFO[11-02|07:46:11]  - uevent injection: no 
INFO[11-02|07:46:11]  - seccomp listener: no 
INFO[11-02|07:46:11]  - seccomp listener continue syscalls: no 
INFO[11-02|07:46:11]  - seccomp listener add file descriptors: no 
INFO[11-02|07:46:11]  - attach to namespaces via pidfds: no 
INFO[11-02|07:46:11]  - safe native terminal allocation : no 
INFO[11-02|07:46:11]  - unprivileged file capabilities: no 
INFO[11-02|07:46:11]  - cgroup layout: legacy 
WARN[11-02|07:46:11]  - Couldn't find the CGroup blkio, I/O limits will be ignored 
WARN[11-02|07:46:11]  - Couldn't find the CGroup blkio.weight, I/O weight limits will be ignored 
WARN[11-02|07:46:11]  - Couldn't find the CGroup CPUset controller, CPU pinning will be ignored 
WARN[11-02|07:46:11]  - Couldn't find the CGroup devices controller, device access control won't work 
WARN[11-02|07:46:11]  - Couldn't find the CGroup freezer controller, pausing/resuming containers won't work 
WARN[11-02|07:46:11]  - Couldn't find the CGroup hugetlb controller, hugepage limits will be ignored 
WARN[11-02|07:46:11]  - Couldn't find the CGroup memory controller, memory limits will be ignored 
WARN[11-02|07:46:11]  - Couldn't find the CGroup network class controller, network limits will be ignored 
WARN[11-02|07:46:11]  - Couldn't find the CGroup pids controller, process limits will be ignored 
WARN[11-02|07:46:11]  - Couldn't find the CGroup memory swap accounting, swap limits will be ignored 
INFO[11-02|07:46:11]  - shiftfs support: no 
INFO[11-02|07:46:11] Initializing local database 
EROR[11-02|07:46:11] Failed to start the daemon: Error creating database: failed to begin transaction: unable to open database file: no such file or directory 
INFO[11-02|07:46:11] Starting shutdown sequence 
DBUG[11-02|07:46:11] Not unmounting temporary filesystems (containers are still running) 
Error: Error creating database: failed to begin transaction: unable to open database file: no such file or directory
sh-5.0$ sudo ls /var/lib/lxd/database
local.db
sh-5.0$ sudo sqlite3 /var/lib/lxd/database/local.db
SQLite version 3.33.0 2020-08-14 13:23:32
Enter ".help" for usage hints.
sqlite> .tables
sqlite>
```

**Comment by stgraber** [comment] 2020-11-02 02:42
Can you show the output of `env`?

**Comment by balajeerc** [comment] 2020-11-02 02:45
```
sh-5.0$ env
SHELL=/bin/sh
TERMCAP=SC|screen.linux|VT 100/ANSI X3.64 virtual terminal:DO=\E[%dB:LE=\E[%dD:RI=\E[%dC:UP=\E[%dA:bs:bt=\E[Z:cd=\E[J:ce=\E[K:cl=\E[H\E[J:cm=\E[%i%d;%dH:ct=\E[3g:do=^J:nd=\E[C:pt:rc=\E8:rs=\Ec:sc=\E7:st=\EH:up=\EM:le=^H:bl=^G:cr=^M:it#8:ho=\E[H:nw=\EE:ta=^I:is=\E)0:li#26:co#95:am:xn:xv:LP:sr=\EM:al=\E[L:AL=\E[%dL:cs=\E[%i%d;%dr:dl=\E[M:DL=\E[%dM:dc=\E[P:DC=\E[%dP:im=\E[4h:ei=\E[4l:mi:IC=\E[%d@:ks=\E[?1h\E=:ke=\E[?1l\E>:vi=\E[?25l:ve=\E[34h\E[?25h:vs=\E[34l:ti=\E[?1049h:te=\E[?1049l:us=\E[4m:ue=\E[24m:so=\E[3m:se=\E[23m:mb=\E[5m:md=\E[1m:mh=\E[2m:mr=\E[7m:me=\E[m:ms:Co#8:pa#64:AF=\E[3%dm:AB=\E[4%dm:op=\E[39;49m:AX:vb=\Eg:as=\E(0:ae=\E(B:ac=\140\140aaffggjjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~..--++,,hhII00:Km=\E[M:k0=\E[10~:k1=\EOP:k2=\EOQ:k3=\EOR:k4=\EOS:k5=\E[15~:k6=\E[17~:k7=\E[18~:k8=\E[19~:k9=\E[20~:k;=\E[21~:F1=\E[23~:F2=\E[24~:kB=\E[Z:kh=\E[1~:@1=\E[1~:kH=\E[4~:@7=\E[4~:kN=\E[6~:kP=\E[5~:kI=\E[2~:kD=\E[3~:ku=\EOA:kd=\EOB:kr=\EOC:kl=\EOD:
WINDOW=0
PWD=/home/android
LOGNAME=android
MOTD_SHOWN=pam
HOME=/home/android
LANG=C
SSH_CONNECTION=10.0.0.9 60474 10.0.0.2 22
TERM=screen.linux
USER=android
SHLVL=2
SSH_CLIENT=10.0.0.9 60474 22
PATH=/home/android/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
STY=654.lxd
HG=/usr/bin/hg
MAIL=/var/spool/mail/android
SSH_TTY=/dev/pts/1
OLDPWD=/var/lib/lxd
_=/usr/bin/env
sh-5.0$ sudo env
LANG=C
TERM=screen.linux
PATH=/home/android/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
MAIL=/var/mail/root
LOGNAME=root
USER=root
HOME=/root
SHELL=/bin/bash
SUDO_COMMAND=/usr/bin/env
SUDO_USER=android
SUDO_UID=60000
SUDO_GID=60000
sh-5.0$
```

P.S: Thanks so much for taking the time out to help with quick replies. Much appreciated.

**Comment by stgraber** [comment] 2020-11-02 21:29
The error really makes no sense, the directory exists and file creation should succeed but the kernel says it didn't...

Can you maybe try mounting a tmpfs on `/var/lib/lxd` to see if it's the underlying filesystem causing issues somehow?
`mount -t tmpfs tmpfs /var/lib/lxd` then try starting LXD again?

**Comment by balajeerc** [comment] 2020-11-03 03:32
Results are identical to previous runs:

```
sh-5.0$ sudo mount -t tmpfs tmpfs /var/lib/lxd
sh-5.0$ sudo lxd --debug
INFO[11-03|09:00:07] LXD 4.7 is starting in normal mode       path=/var/lib/lxd
INFO[11-03|09:00:07] Kernel uid/gid map:
INFO[11-03|09:00:07]  - u 0 0 0
INFO[11-03|09:00:07]  - g 0 0 0
WARN[11-03|09:00:07] No available uid/gid map could be found
WARN[11-03|09:00:07] Only privileged containers will be able to run
WARN[11-03|09:00:07] AppArmor support has been disabled because of lack of kernel support
INFO[11-03|09:00:07] Kernel features:
INFO[11-03|09:00:07]  - closing multiple file descriptors efficiently: no
DBUG[11-03|09:00:07] failed to set network namespace identifier
INFO[11-03|09:00:07]  - netnsid-based network retrieval: no
INFO[11-03|09:00:07]  - pidfds: no
INFO[11-03|09:00:07]  - uevent injection: no
INFO[11-03|09:00:07]  - seccomp listener: no
INFO[11-03|09:00:07]  - seccomp listener continue syscalls: no
INFO[11-03|09:00:07]  - seccomp listener add file descriptors: no
INFO[11-03|09:00:07]  - attach to namespaces via pidfds: no
INFO[11-03|09:00:07]  - safe native terminal allocation : no
INFO[11-03|09:00:07]  - unprivileged file capabilities: no
INFO[11-03|09:00:07]  - cgroup layout: legacy
WARN[11-03|09:00:07]  - Couldn't find the CGroup blkio, I/O limits will be ignored
WARN[11-03|09:00:07]  - Couldn't find the CGroup blkio.weight, I/O weight limits will be ignored
WARN[11-03|09:00:07]  - Couldn't find the CGroup CPUset controller, CPU pinning will be ignored
WARN[11-03|09:00:07]  - Couldn't find the CGroup devices controller, device access control won't work
WARN[11-03|09:00:07]  - Couldn't find the CGroup freezer controller, pausing/resuming containers won't work
WARN[11-03|09:00:07]  - Couldn't find the CGroup hugetlb controller, hugepage limits will be ignored
WARN[11-03|09:00:07]  - Couldn't find the CGroup memory controller, memory limits will be ignored
WARN[11-03|09:00:07]  - Couldn't find the CGroup network class controller, network limits will be ignored
WARN[11-03|09:00:07]  - Couldn't find the CGroup pids controller, process limits will be ignored
WARN[11-03|09:00:07]  - Couldn't find the CGroup memory swap accounting, swap limits will be ignored
INFO[11-03|09:00:08]  - shiftfs support: no
INFO[11-03|09:00:08] Initializing local database
EROR[11-03|09:00:08] Failed to start the daemon: Error creating database: failed to begin transaction: unable to open database file: no such file or directory
INFO[11-03|09:00:08] Starting shutdown sequence
DBUG[11-03|09:00:08] Not unmounting temporary filesystems (containers are still running)
Error: Error creating database: failed to begin transaction: unable to open database file: no such file or directory
```

**Comment by stgraber** [comment] 2020-11-03 03:51
Try:
 - echo ".save/var/lib/lxd/database/local.db" | sqlite3
 - ls -lh /var/lib/lxd/database/
 - lxd --debug --group lxd

**Comment by stgraber** [comment] 2020-11-03 03:52
If that still doesn't work, I think we're going to be blaming the kernel because we're clearly issuing a syscall which should work and the kernel is giving us a nonsensical answer based on what you're showing.

**Comment by stgraber** [comment] 2020-11-03 03:53
Maybe look in `dmesg` for any weird kernel error. Sadly Android kernels do tend to be heavily modified by the manufacturers and already customized by Google with some unusual behaviors added for security reasons, so who knows what's really happening here.

**Comment by balajeerc** [comment] 2020-11-09 04:58
Sorry for the delayed response.

Here's the output you asked for:

```
# ls -lh /var/lib/lxd/database/
0K
-- 1 root root 4.0K Nov  9 10:18 local.db
# lxd --debug --group lxd
09|10:18:27] LXD 4.7 is starting in normal mode       path=/var/lib/lxd
09|10:18:27] Kernel uid/gid map:
09|10:18:27]  - u 0 0 0
09|10:18:27]  - g 0 0 0
09|10:18:27] No available uid/gid map could be found
09|10:18:27] Only privileged containers will be able to run
09|10:18:27] AppArmor support has been disabled because of lack of kernel support
09|10:18:27] Kernel features:
09|10:18:27]  - closing multiple file descriptors efficiently: no
09|10:18:27] failed to set network namespace identifier
09|10:18:27]  - netnsid-based network retrieval: no
09|10:18:27]  - pidfds: no
09|10:18:27]  - uevent injection: no
09|10:18:27]  - seccomp listener: no
09|10:18:27]  - seccomp listener continue syscalls: no
09|10:18:27]  - seccomp listener add file descriptors: no
09|10:18:27]  - attach to namespaces via pidfds: no
09|10:18:27]  - safe native terminal allocation : no
09|10:18:27]  - unprivileged file capabilities: no
09|10:18:27]  - cgroup layout: legacy
09|10:18:27]  - Couldn't find the CGroup blkio, I/O limits will be ignored
09|10:18:27]  - Couldn't find the CGroup blkio.weight, I/O weight limits will be ignored
09|10:18:27]  - Couldn't find the CGroup CPUset controller, CPU pinning will be ignored
09|10:18:27]  - Couldn't find the CGroup devices controller, device access control won't work
09|10:18:27]  - Couldn't find the CGroup freezer controller, pausing/resuming containers won't work
09|10:18:27]  - Couldn't find the CGroup hugetlb controller, hugepage limits will be ignored
09|10:18:27]  - Couldn't find the CGroup memory controller, memory limits will be ignored
09|10:18:27]  - Couldn't find the CGroup network class controller, network limits will be ignored
09|10:18:27]  - Couldn't find the CGroup pids controller, process limits will be ignored
09|10:18:27]  - Couldn't find the CGroup memory swap accounting, swap limits will be ignored
09|10:18:27]  - shiftfs support: no
09|10:18:27] Initializing local database
09|10:18:27] Failed to start the daemon: Error creating database: failed to begin transaction: unable to open database file: no such file or directory
09|10:18:27] Starting shutdown sequence
09|10:18:27] Not unmounting temporary filesystems (containers are still running)
rror creating database: failed to begin transaction: unable to open database file: no such file or directory
#
```

Whenever I try to run `lxd --debug` the following are the `dmesg` logs I see:

```
SELinux: unrecognized netlink message: protocol=0 nlmsg_type=88 sclass=30
11328] [RMNET:HI] rmnet_config_notify_cb(): Kernel is trying to unregister sit0
41624] [RMNET:HI] rmnet_config_notify_cb(): Kernel is trying to unregister sit0
44264] [RMNET:HI] rmnet_config_notify_cb(): Kernel is trying to unregister lo
81505] [RMNET:HI] rmnet_config_notify_cb(): Kernel is trying to unregister lo
```

**Comment by stgraber** [comment] 2020-11-11 21:06
Hmm, I'm really not sure what else may be going on there, this is pretty weird.
Honestly short of having access to that system to poke around, I'm not sure that I'll be of much help.

This very much feels like a kernel issue of some kind but maybe there's some way to trick it into working anyway.

I'm closing this issue just because I don't believe there's an actual LXD bug here, it's far more likely to be something odd with the kernel or underlying Android bits. I'd still like to figure it out though, seems interesting :)

**Closed by stgraber** 2020-11-11 21:06 UTC
Labels: Incomplete

**Comment by balajeerc** [comment] 2020-11-12 03:35
@stgraber Nevertheless, thanks for taking the time to debug this with me.

> I'd still like to figure it out though, seems interesting :)

If you would like ssh access to this device to poke around, I can make that happen via an ssh tunnel perhaps. Please let me know if you'd like that.

**Comment by stgraber** [comment] 2020-11-12 03:58
Yeah, that'd be interesting.

https://github.com/stgraber.keys has my current SSH key.

**Comment by balajeerc** [comment] 2020-11-12 05:22
@stgraber I've added your key. 

You should be able to access the device via: `ssh android@2.tcp.ngrok.io -p 18064`

**Comment by stgraber** [comment] 2020-11-12 17:50
@balajeerc SSH is prompting me for a password, so that suggests that my key isn't being considered for authentication

**Comment by balajeerc** [comment] 2020-11-13 03:16
@stgraber So sorry about that. There was a typo in `authorized_keys`. I have corrected it and rechecked your key. You should be able to login now.

**Comment by stgraber** [comment] 2020-11-13 04:25
Ok, so I think I figured it out.

Basically the issue is the chroot environment. LXD does some mount namespace manipulations during startup which effectively results in it seeing the host mount namespace rather than your chroot, causing the weird failure to locate files.

I think this could be avoided if you had PID namespace support on your kernel as the current chroot could be made more solid and avoiding the mix of processes from inside/outside the chroot.

If rebuilding the kernel with a proper set of namespaces enabled isn't an option, then you're going to be stuck I'm afraid.
Your kernel currently only support the mount and network namespaces. This is insufficient for any kind of containers. You at the very least need uts, ipc and pid for any of this to work.

**Comment by balajeerc** [comment] 2020-11-13 04:54
Yes, building a custom kernel is what I realised would be the way to go as well. 

Thanks again for debugging this.

**Comment by ben-skyportsystems** [comment] 2022-02-26 23:50
This is a very interesting discussion.  I'm trying to do something similar: run lxd in a chroot jail on top of Android.  I'm building **lxd** from source because I want to experiment with ways to work with Android's use of _--noprefix_ when mounting cgroupfs.
Anyway, I've added all namespace and cgroup support to my kernel.  @stgraber : can you please explain what you had in mind with "I think this could be avoided if you had PID namespace support on your kernel as the current chroot could be made more solid and avoiding the mix of processes from inside/outside the chroot."?

**Comment by stgraber** [comment] 2022-02-27 00:09
The idea would be to use `unshare -p` and then run a script which acts as PID1 in that namespace which would then run LXD.

That would effectively isolate those processes from everything else going on on the system.

**Comment by ben-skyportsystems** [comment] 2022-02-27 00:14
merci!
