### ISSUE TITLE
Live-migrating a running container with two different parent btrfs subvolumes fails

### ISSUE THREAD

**Issue by pcdummy** [lxc/lxd#2234] opened 2016-07-24 13:25 UTC
* Distribution: Ubuntu Xenial on both hosts
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-31-generic
   * LXC version: 2.0.3
   * LXD version: 2.0.3
   * Storage backend in use: btrfs

# Issue description

I try to live migrate a container from one host where /var/lib/lxd is its own subvolume (srv01) to 
another one where /var/lib/lxd is on the / subvolume (srv02).

    $ lxc move srv01:test-migratee srv02:

Moving a stopped container works.

# Steps to reproduce

 1. Create a subvolume @lxd and mount it to /var/lib/lxd on host srv01
 2. Launch a container on host A:

    lxc launch ubuntu:x local:test-migratee

 3. Try to migrate it:

    $ lxc move srv01:test-migratee srv02:

# Information to attach

 - [x] any relevant kernel output (dmesg)

    [23105.044922] BTRFS error (device sda2): could not find root 8
    [23105.291152] BTRFS error (device sda2): could not find root 8
    [23341.878645] BTRFS error (device sda2): could not find root 8
    [23376.192321] BTRFS error (device sda2): could not find root 

 - [x] main daemon log (/var/log/lxd.log)

    t=2016-07-24T14:57:23+0200 lvl=info msg=handling method=GET url=/1.0 ip=@
    t=2016-07-24T14:57:23+0200 lvl=info msg=handling method=GET url="/1.0/containers?recursion=1" ip=@
    t=2016-07-24T15:04:37+0200 lvl=info msg=handling method=GET url=/1.0/profiles ip=127.0.0.1:33858
    t=2016-07-24T15:04:37+0200 lvl=info msg=handling ip=127.0.0.1:33858 method=POST url=/1.0/containers
    t=2016-07-24T15:04:37+0200 lvl=info msg=handling method=GET url=/1.0/operations/e7e80ff3-c1d8-4a73-a36b-a639b289adfd/wait ip=127.0.0.1:33858
    t=2016-07-24T15:05:14+0200 lvl=eror msg="problem with btrfs receive" output="ERROR: cannot find parent subvolume\n"
    t=2016-07-24T15:05:14+0200 lvl=eror msg="Error during migration sink" err="exit status 1"

Will provide any informations you guys need or ssh access to both of this hosts.

**Comment by tych0** [comment] 2016-08-01 14:13
Can you post the contents of the /var/log/lxd/*/migration* files? I suspect this is due to mountopts not being the same, but those would confirm.

**Comment by pcdummy** [comment] 2016-08-01 15:59
Will do once i'm back home (some hours).

**Comment by pcdummy** [comment] 2016-08-02 16:07
[srv01_lxc.conf.txt](https://github.com/lxc/lxd/files/397503/srv01_lxc.conf.txt)
[srv01_lxc.log.old.txt](https://github.com/lxc/lxd/files/397504/srv01_lxc.log.old.txt)
[srv01_lxc.log.txt](https://github.com/lxc/lxd/files/397505/srv01_lxc.log.txt)
[srv01_migration_dump_2016-08-02T18:02:59+02:00.log.txt](https://github.com/lxc/lxd/files/397506/srv01_migration_dump_2016-08-02T18.02.59.02.00.log.txt)
[srv02_lxc.log.txt](https://github.com/lxc/lxd/files/397507/srv02_lxc.log.txt)

**Comment by pcdummy** [comment] 2016-08-02 16:08
t=2016-08-02T18:02:19+0200 lvl=info msg=handling ip=@ method=POST url=/1.0/containers
    t=2016-08-02T18:02:19+0200 lvl=info msg=handling method=GET url=/1.0/operations/4c802e02-1056-49a4-a3c2-443652e4ff26/wait ip=@
    t=2016-08-02T18:03:00+0200 lvl=eror msg="problem with btrfs receive" output="ERROR: cannot find parent subvolume\n"
    t=2016-08-02T18:03:00+0200 lvl=eror msg="Error during migration sink" err="exit status 1"

**Comment by stgraber** [comment] 2016-09-06 15:52
reproduced it here

**Comment by stgraber** [comment] 2016-09-06 19:55
Turns out that it's a CRIU bug. CRIU crashes when a unix socket is on a btrfs filesystem :)

**Comment by brauner** [comment] 2016-09-06 20:00
This is now tracked at: https://bugs.launchpad.net/ubuntu/+source/criu/+bug/1620805.

**Comment by stgraber** [comment] 2016-09-06 20:02
Closing this as LXD doesn't seem to need any fixing, we just need to take care of the criu bug.

**Closed by stgraber** 2016-09-06 20:02 UTC
Labels: Bug
