### ISSUE TITLE
question: incremental backups (again)

### ISSUE THREAD

**Issue by huegelc** [lxc/lxd#5600] opened 2019-03-25 14:13 UTC
Hi,
as there are multiple ways to backup lxd containers from one server to another (https://lxd.readthedocs.io/en/latest/backup/) this doesn`t quite fit for my use case.

I know, it would be much easier to have on both sides the same storage driver (btrfs/zfs) and use the filesystems send/receive capabilities but I cant use them in my current setup.

I have a production LXD server:

```
driver: lxc
  driver_version: 3.1.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-141-generic
  server: lxd
  server_pid: 32108
  server_version: "3.11"
  storage: btrfs
  storage_version: "4.4"
  server_clustered: false
  server_name: data-prod01
  project: default
```
and a backup LXD server also as a container running inside Proxmox:

```
driver: lxc
  driver_version: 3.0.3
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.18-12-pve
  server: lxd
  server_pid: 387
  server_version: 3.0.3
  storage: dir
  storage_version: "1"
  server_clustered: false
  server_name: data-bckp01
  project: ""
```
The containers inside Proxmox are running on a zfs pool

`lxc copy data-prod01:cont11 cont11` is woking fine but AFAIK this approach doesn`t do incremental transfers.(?!)

[sidenote]
The copy method changes also the file permissions:

source container 
```
drwxr-xr-x   1 root   root    1068 May 23  2016 bin
drwxr-xr-x   1 root   root       0 Jan 28  2014 boot
drwxr-xr-x   7 root   root     460 Feb 21 04:13 dev
drwxr-xr-x   1 root   root    2168 Mar 25 13:45 etc
drwxr-xr-x   1 root   root       0 Jan 28  2014 home
drwxr-xr-x   1 root   root      90 May 23  2016 lib
drwxr-xr-x   1 root   root      40 Aug 26  2016 lib64
drwxr-xr-x   1 root   root       0 Apr  2  2014 media
```
after lxc copy remote:cont11 cont11

```
drwx------   2 root   root    104 May 23  2016 bin
drwx------   2 root   root      2 Jan 28  2014 boot
drwxr-xr-x   6 root   root    440 Mar 25 14:02 dev
drwx------  63 root   root    134 Mar 25 14:02 etc
drwx------   2 root   root      2 Jan 28  2014 home
drwx------   8 root   root      9 May 23  2016 lib
drwx------   2 root   root      3 Aug 26  2016 lib64
drwx------   2 root   root      2 Apr  2  2014 media
```
why is this so?
[/sidenote]

I´ve also tried to rsync (rsnapshot) the snapshot from the prod01 server but for some reason rsync fails to transfer one of my container:

```
packet_write_wait: Connection to xxx.xxx.xxx.118 port 2006: Broken pipe
rsync: connection unexpectedly closed (22237737 bytes received so far) [receiver]
rsync error: error in rsync protocol data stream (code 12) at io.c(235) [receiver=3.1.2]
rsync: connection unexpectedly closed (3184714 bytes received so far) [generator]
rsync error: unexplained error (code 255) at io.c(235) [generator=3.1.2]
```
This particular container is 30GB big. 
Anyway, by rsync-ing the snapshot would mean to alter the backup.yaml file as the source datastore is btrfs, creating a symlink in `/var/lib/lxd/containers` and then do a `lxd import <container>`

So my question is, what would be the right approach do incremental backups of containers from one LXD instance to another?

Thanks

**Comment by stgraber** [comment] 2019-03-25 14:16
The right approach would be to use the `--refresh` options we introduce a few releases ago which lets you transfer only the data that has changed and re-sync the snapshot list with the source.

**Comment by stgraber** [comment] 2019-03-25 19:00
Been trying to reproduce the permission issue, so far no luck using an Alpine container, a LXD 3.11 source server and LXD 3.0.3 target server, source is on btrfs, target on dir, same as described above.

**Comment by stgraber** [comment] 2019-03-25 19:03
And tried with both the 3.0.3 snap and the 3.0.3 deb on the target, same behavior on both.

I also always remember us passing -a to rsync so I don't see how the permissions would get stripped during an rsync migration...

**Comment by stgraber** [comment] 2019-03-25 19:03
Do you have a reliable reproducer for the permission issue?

**Comment by huegelc** [comment] 2019-03-25 21:39
OK, since the --refresh option is available only on the newer releases, I´ve removed the deb 3.0.3 version and installed snap inside the container.

```
apt install squashfuse fuse snapd
snap install lxd 
```
```
driver: lxc
  driver_version: 3.1.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.18-12-pve
  server: lxd
  server_pid: 2270
  server_version: "3.11"
  storage: dir
  storage_version: "1"
  server_clustered: false
  server_name: data-bckp01
  project: default
```

I`ve created a snapshot on the source LXD server of container cont11 and this are the permissions:

```
ls -la /var/snap/lxd/common/lxd/storage-pools/default/containers-snapshots/cont11/rsnapshot/rootfs/
total 0
drwxr-xr-x 1 1000000 1000000  164 Feb  3  2018 .
drwx------ 1 1000000 1000000   34 May 15  2018 ..
drwx------ 1 1000000 1000000  108 Jun  6  2016 .keychain
drwxr-xr-x 1 1000000 1000000 1068 May 23  2016 bin
drwxr-xr-x 1 1000000 1000000    0 Jan 28  2014 boot
drwxr-xr-x 1 1000000 1000000  464 Feb  3  2018 dev
drwxr-xr-x 1 1000000 1000000 2168 Mar 25 13:07 etc
drwxr-xr-x 1 1000000 1000000    0 Jan 28  2014 home
drwxr-xr-x 1 1000000 1000000   90 May 23  2016 lib
drwxr-xr-x 1 1000000 1000000   40 Aug 26  2016 lib64
drwxr-xr-x 1 1000000 1000000    0 Apr  2  2014 media
drwxr-xr-x 1 1000000 1000000    0 Jan 28  2014 mnt
drwxr-xr-x 1 1000000 1000000    0 Apr  2  2014 opt
drwxr-xr-x 1 1000000 1000000    0 Jan 28  2014 proc
drwx--S--- 1 1000000 1000000  378 Oct 20 17:06 root
drwxr-xr-x 1 1000000 1000000  110 Jun 20  2016 run
drwxr-xr-x 1 1000000 1000000 1430 Aug 26  2016 sbin
drwxr-xr-x 1 1000000 1000000   14 Apr  2  2014 selinux
drwxr-xr-x 1 1000000 1000000    0 Apr  2  2014 srv
drwxr-xr-x 1 1000000 1000000    0 Jul 14  2013 sys
drwxrwxrwt 1 1000000 1000000   48 Mar 25 12:39 tmp
drwxr-xr-x 1 1000000 1000000   70 Apr  2  2014 usr
drwxr-xr-x 1 1000000 1000000   96 Apr  3  2014 var
```
Now on the backup LXD:
`root@data-bckp01:~# lxc copy remote:cont11/rsnapshot cont11`

```
lxc list
+--------+---------+----------------------+-----------------------------------------------+------------+-----------+
|  NAME  |  STATE  |         IPV4         |                     IPV6                      |    TYPE    | SNAPSHOTS |
+--------+---------+----------------------+-----------------------------------------------+------------+-----------+
| cont11 | RUNNING | 10.12.138.225 (eth0) | fd42:32aa:c1e5:a34d:216:3eff:fec3:ff79 (eth0) | PERSISTENT |           |
+--------+---------+----------------------+-----------------------------------------------+------------+-----------+
```
```
ls -la /var/snap/lxd/common/lxd/storage-pools/default/containers/cont11/rootfs/
total 103
drwx------ 23 root root  23 Mar 25 21:20 .
drwx------  3 root root   4 May 14  2018 ..
drwx------  2 root root   5 Jun  6  2016 .keychain
drwx------  2 root root 104 May 23  2016 bin
drwx------  2 root root   2 Jan 28  2014 boot
drwx------  3 root root  13 Feb  3  2018 dev
drwx------ 63 root root 134 Mar 25 21:20 etc
drwx------  2 root root   2 Jan 28  2014 home
drwx------  8 root root   9 May 23  2016 lib
drwx------  2 root root   3 Aug 26  2016 lib64
drwx------  2 root root   2 Apr  2  2014 media
drwx------  2 root root   2 Jan 28  2014 mnt
drwx------  2 root root   2 Apr  2  2014 opt
drwx------  2 root root   2 Jan 28  2014 proc
drwx------ 12 root root  23 Oct 20 15:06 root
drwx------  8 root root  11 Jun 20  2016 run
drwx------  2 root root  92 Aug 26  2016 sbin
drwx------  2 root root   3 Apr  2  2014 selinux
drwx------  2 root root   2 Apr  2  2014 srv
drwx------  2 root root   2 Jul 14  2013 sys
drwx------  3 root root   4 Mar 25 11:39 tmp
drwx------ 10 root root  10 Apr  2  2014 usr
drwx------ 12 root root  14 Apr  2  2014 var
```
Regarding the --refresh option: how is this supposed to be used?

```
lxc copy --refresh remote:cont11 cont11
Error: Failed container creation: Cannot refresh a running container
root@data-bckp01:~# lxc stop cont11
root@data-bckp01:~# lxc copy --refresh remote:cont11 cont11
Error: Failed container creation:
 - https://10.159.23.1:4443: Error transferring container data: Unable to connect to: 10.159.23.1:4443
 - https://example.com:4443: Error transferring container data: exit status 23
 - https://176.9.xxx.xxx:4443: Error transferring container data: websocket: bad handshake
```
10.159.23.1 is the bridge IP of the source LXD server. 
Thanks

**Comment by stgraber** [comment] 2019-03-25 22:41
```
root@vm04:~# lxc launch images:alpine/edge a1
Creating a1
Starting a1                                 
root@vm04:~# lxc snapshot a1
root@vm04:~# nsenter -t $(pgrep daemon.start) -m -- ls -lh /var/snap/lxd/common/lxd/storage-pools/default/containers-snapshots/a1/snap0/rootfs/
total 0
drwxr-xr-x 1 1000000 1000000  890 Mar 25 13:00 bin
drwxr-xr-x 1 1000000 1000000   20 Jun 26  2018 dev
drwxr-xr-x 1 1000000 1000000  696 Mar 25 13:00 etc
drwxr-xr-x 1 1000000 1000000    0 Jun 26  2018 home
drwxr-xr-x 1 1000000 1000000  322 Mar 25 13:00 lib
drwxr-xr-x 1 1000000 1000000   28 Jun 26  2018 media
drwxr-xr-x 1 1000000 1000000    0 Jun 26  2018 mnt
drwxr-xr-x 1 1000000 1000000    0 Mar 25 13:00 opt
dr-xr-xr-x 1 1000000 1000000    0 Jun 26  2018 proc
drwx------ 1 1000000 1000000    0 Jun 26  2018 root
drwxr-xr-x 1 1000000 1000000    0 Jun 26  2018 run
drwxr-xr-x 1 1000000 1000000 1.7K Mar 25 13:00 sbin
drwxr-xr-x 1 1000000 1000000    0 Jun 26  2018 srv
drwxr-xr-x 1 1000000 1000000    0 Jun 26  2018 sys
drwxrwxrwt 1 1000000 1000000   36 Mar 25 22:39 tmp
drwxr-xr-x 1 1000000 1000000   40 Jun 26  2018 usr
drwxr-xr-x 1 1000000 1000000   78 Mar 25 22:39 var
root@vm04:~# 
```

```
root@vm05:~# lxc remote add vm04 vm04.maas.mtl.stgraber.net
Generating a client certificate. This may take a minute...
Certificate fingerprint: cb14cddb04af55680471dd7e64a225d74d4f08e4ef2f739fbd84758bd8f40b5a
ok (y/n)? y
Admin password for vm04: 
Client certificate stored at server:  vm04
root@vm05:~# lxc copy vm04:a1/snap0 a1 --mode=relay
root@vm05:~# ls -lh /var/snap/lxd/common/lxd/storage-pools/default/
total 4.0K
drwx--x--x 3 root root 4.0K Mar 25 22:40 containers
root@vm05:~# ls -lh /var/snap/lxd/common/lxd/storage-pools/default/containers/a1
total 16K
-r--------  1 root    root    2.2K Mar 25 22:40 backup.yaml
-rw-r--r--  1 root    root     660 Mar 25 13:00 metadata.yaml
drwxr-xr-x 19 1000000 1000000 4.0K Mar 25 13:00 rootfs
drwxr-xr-x  2 root    root    4.0K Mar 25 13:00 templates
root@vm05:~# ls -lh /var/snap/lxd/common/lxd/storage-pools/default/containers/a1/rootfs
total 68K
drwxr-xr-x  2 1000000 1000000 4.0K Mar 25 13:00 bin
drwxr-xr-x  4 1000000 1000000 4.0K Jun 26  2018 dev
drwxr-xr-x 19 1000000 1000000 4.0K Mar 25 13:00 etc
drwxr-xr-x  2 1000000 1000000 4.0K Jun 26  2018 home
drwxr-xr-x  6 1000000 1000000 4.0K Mar 25 13:00 lib
drwxr-xr-x  5 1000000 1000000 4.0K Jun 26  2018 media
drwxr-xr-x  2 1000000 1000000 4.0K Jun 26  2018 mnt
drwxr-xr-x  2 1000000 1000000 4.0K Mar 25 13:00 opt
dr-xr-xr-x  2 1000000 1000000 4.0K Jun 26  2018 proc
drwx------  2 1000000 1000000 4.0K Jun 26  2018 root
drwxr-xr-x  2 1000000 1000000 4.0K Jun 26  2018 run
drwxr-xr-x  2 1000000 1000000 4.0K Mar 25 13:00 sbin
drwxr-xr-x  2 1000000 1000000 4.0K Jun 26  2018 srv
drwxr-xr-x  2 1000000 1000000 4.0K Jun 26  2018 sys
drwxrwxrwt  4 1000000 1000000 4.0K Mar 25 22:39 tmp
drwxr-xr-x  7 1000000 1000000 4.0K Jun 26  2018 usr
drwxr-xr-x 10 1000000 1000000 4.0K Mar 25 22:39 var
```

**Comment by stgraber** [comment] 2019-03-25 22:42
Though from what I understand, your target server is itself a container, I'll try that to see if I get a different behavior.

**Comment by stgraber** [comment] 2019-03-25 22:43
Ah and refresh works fine here too:
```
root@vm05:~# lxc copy vm04:a1 a1 --mode=relay --refresh
root@vm05:~# 
```

**Comment by stgraber** [comment] 2019-03-25 22:54
Ok, so yes, your problem is about running this inside a container. Rsync will attempt to do things like create device nodes which isn't going to work inside an unprivileged container, that explains the error 23, at least that's what I'm seeing here when looking at the source server logs:

```
t=2019-03-25T22:47:23+0000 lvl=eror msg="Rsync send failed: /var/snap/lxd/common/lxd/snapshots/a1/snap0/: exit status 23: rsync: mknod \"/var/snap/lxd/common/lxd/containers/a1/rootfs/dev/null\" failed: Operation not permitted (1)\nrsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]\n" 
```

**Comment by stgraber** [comment] 2019-03-25 22:57
After making the backup container privileged, the copy worked properly here, as did a refresh copy:
```
root@backup:~# lxc copy vm04:a1/snap0 a1 --mode=relay
root@backup:~# lxc copy vm04:a1 a1 --mode=relay --refresh
root@backup:~# 
```

So I think the answer to this issue is likely that if you want to run a backup LXD server inside a container, you should have it run privileged so that it can backup all file types from any container you may have around and avoid running into odd rsync issues when a particular file operation isn't allowed by the kernel. (rsync annoyingly only gives us pretty cryptic exit codes)

**Comment by huegelc** [comment] 2019-03-26 06:32
Thank you for being thorough in this matter. I`ve started the container in privileged mode but snap lxd doesn`t seem to like that

```
root@nas-10-backup:~#snap install lxd
error: cannot perform the following tasks:
- Setup snap "core" (6531) security profiles (cannot setup udev for snap "core": cannot reload udev rules: exit status 2
udev output:
)
- Setup snap "core" (6531) security profiles (cannot reload udev rules: exit status 2
udev output:
)
```

**Comment by stgraber** [comment] 2019-03-26 14:18
Run the install again

**Comment by stgraber** [comment] 2019-03-26 14:19
For whatever reason snaps need to tries inside privileged containers

**Comment by huegelc** [comment] 2019-03-27 12:11
```
root@nas-10-backup:~# snap install lxd
error: cannot perform the following tasks:
- Setup snap "core" (6531) security profiles (cannot setup udev for snap "core": cannot reload udev rules: exit status 2
udev output:
)
- Setup snap "core" (6531) security profiles (cannot reload udev rules: exit status 2
udev output:
)
root@nas-10-backup:~# snap install lxd
error: cannot perform the following tasks:
- Setup snap "core" (6531) security profiles (cannot setup apparmor for snap "core": cannot create host snap-confine apparmor configuration: cannot reload snap-confine apparmor profile: cannot load apparmor profiles: exit status 243
apparmor_parser output:
apparmor_parser: Unable to replace "mount-namespace-capture-helper".  Permission denied; attempted to load a profile while confined?
apparmor_parser: Unable to replace "/snap/core/6531/usr/lib/snapd/snap-confine".  Permission denied; attempted to load a profile while confined?
)
- Setup snap "core" (6531) security profiles (cannot create host snap-confine apparmor configuration: cannot reload snap-confine apparmor profile: cannot load apparmor profiles: exit status 243
apparmor_parser output:
apparmor_parser: Unable to replace "mount-namespace-capture-helper".  Permission denied; attempted to load a profile while confined?
apparmor_parser: Unable to replace "/snap/core/6531/usr/lib/snapd/snap-confine".  Permission denied; attempted to load a profile while confined?
)
```

`tail -f /var/log/syslog`

```
Mar 27 12:07:52 nas-10-backup snapd[153]: api.go:1077: Installing snap "lxd" revision unset
Mar 27 12:07:53 nas-10-backup systemd[1]: Reloading.
Mar 27 12:07:53 nas-10-backup systemd[1]: postfix.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:53 nas-10-backup systemd[1]: system-postfix.slice: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:53 nas-10-backup systemd[1]: keyboard-setup.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:53 nas-10-backup systemd[1]: system-container\x2dgetty.slice: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:53 nas-10-backup systemd[1]: systemd-sysctl.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:53 nas-10-backup systemd[1]: networkd-dispatcher.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:53 nas-10-backup systemd[1]: systemd-networkd.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:53 nas-10-backup systemd[1]: systemd-journald.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:53 nas-10-backup systemd[1]: snapd.seeded.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:53 nas-10-backup systemd[1]: snapd.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:53 nas-10-backup systemd[1]: user.slice: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:53 nas-10-backup systemd[1]: systemd-update-utmp.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:53 nas-10-backup systemd[1]: ssh.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:53 nas-10-backup systemd[1]: systemd-journal-flush.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:53 nas-10-backup systemd[1]: system-getty.slice: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:53 nas-10-backup systemd[1]: Failed to set devices.allow on /system.slice/systemd-resolved.service: Operation not permitted
Mar 27 12:07:53 nas-10-backup systemd[1]: Failed to set devices.allow on /system.slice/systemd-resolved.service: Operation not permitted
Mar 27 12:07:53 nas-10-backup systemd[1]: console-getty.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:53 nas-10-backup systemd[1]: ufw.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:53 nas-10-backup systemd[1]: systemd-logind.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:53 nas-10-backup systemd[1]: accounts-daemon.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:53 nas-10-backup systemd[1]: console-setup.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:53 nas-10-backup systemd[1]: cron.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:53 nas-10-backup systemd[1]: systemd-tmpfiles-setup.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:53 nas-10-backup systemd[1]: snap.mount: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:53 nas-10-backup systemd[1]: dbus.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:53 nas-10-backup systemd[1]: snapd.socket: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:53 nas-10-backup systemd[1]: systemd-user-sessions.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:53 nas-10-backup systemd[1]: rsyslog.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:53 nas-10-backup systemd[1]: dev-hugepages.mount: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:53 nas-10-backup systemd[1]: snap-core-6531.mount: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:53 nas-10-backup systemd[1]: Mounting Mount unit for core, revision 6531...
Mar 27 12:07:53 nas-10-backup systemd[1]: Mounted Mount unit for core, revision 6531.
Mar 27 12:07:54 nas-10-backup kernel: [23702.499799] audit: type=1400 audit(1553688474.237:117): apparmor="STATUS" operation="profile_replace" info="not policy admin" error=-13 label="lxc-102_</var/lib/lxc>//&:lxc-102_<-var-lib-lxc>:unconfined" pid=12682 comm="apparmor_parser"
Mar 27 12:07:54 nas-10-backup kernel: [23702.499869] audit: type=1400 audit(1553688474.237:118): apparmor="STATUS" operation="profile_replace" info="not policy admin" error=-13 label="lxc-102_</var/lib/lxc>//&:lxc-102_<-var-lib-lxc>:unconfined" pid=12682 comm="apparmor_parser"
Mar 27 12:07:54 nas-10-backup systemd[1]: Reloading.
Mar 27 12:07:54 nas-10-backup systemd[1]: postfix.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:54 nas-10-backup systemd[1]: system-postfix.slice: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:54 nas-10-backup systemd[1]: keyboard-setup.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:54 nas-10-backup systemd[1]: system-container\x2dgetty.slice: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:54 nas-10-backup systemd[1]: systemd-sysctl.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:54 nas-10-backup systemd[1]: networkd-dispatcher.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:54 nas-10-backup systemd[1]: systemd-networkd.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:54 nas-10-backup systemd[1]: systemd-journald.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:54 nas-10-backup systemd[1]: snapd.seeded.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:54 nas-10-backup systemd[1]: snapd.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:54 nas-10-backup systemd[1]: user.slice: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:54 nas-10-backup systemd[1]: systemd-update-utmp.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:54 nas-10-backup systemd[1]: ssh.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:54 nas-10-backup systemd[1]: systemd-journal-flush.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:54 nas-10-backup systemd[1]: system-getty.slice: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:54 nas-10-backup systemd[1]: Failed to set devices.allow on /system.slice/systemd-resolved.service: Operation not permitted
Mar 27 12:07:54 nas-10-backup systemd[1]: Failed to set devices.allow on /system.slice/systemd-resolved.service: Operation not permitted
Mar 27 12:07:54 nas-10-backup systemd[1]: console-getty.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:54 nas-10-backup systemd[1]: ufw.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:54 nas-10-backup systemd[1]: systemd-logind.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:54 nas-10-backup systemd[1]: accounts-daemon.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:54 nas-10-backup systemd[1]: console-setup.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:54 nas-10-backup systemd[1]: cron.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:54 nas-10-backup systemd[1]: systemd-tmpfiles-setup.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:54 nas-10-backup systemd[1]: snap.mount: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:54 nas-10-backup systemd[1]: dbus.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:54 nas-10-backup systemd[1]: snapd.socket: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:54 nas-10-backup systemd[1]: systemd-user-sessions.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:54 nas-10-backup systemd[1]: rsyslog.service: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:54 nas-10-backup systemd[1]: dev-hugepages.mount: Failed to reset devices.list: Operation not permitted
Mar 27 12:07:54 nas-10-backup snapd[153]: handlers.go:394: Reported install problem for "core" as already-reported
```

```
/etc/init.d/apparmor status
* apparmor.service - AppArmor initialization
   Loaded: loaded (/lib/systemd/system/apparmor.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2019-03-27 12:05:38 UTC; 4min 45s ago
     Docs: man:apparmor(7)
           http://wiki.apparmor.net/
 Main PID: 75 (code=exited, status=123)

Mar 27 12:05:38 nas-10-backup systemd[1]: Starting AppArmor initialization...
Mar 27 12:05:38 nas-10-backup systemd[75]: Failed to attach 75 to compat systemd cgroup /system.slice/apparmor.service: No such file or directory
Mar 27 12:05:38 nas-10-backup apparmor[75]: /sbin/apparmor_parser: Unable to replace "mount-namespace-capture-helper".  Permission denied; attempted to load a profile while confined?
Mar 27 12:05:38 nas-10-backup apparmor[75]: /sbin/apparmor_parser: Unable to replace "/usr/lib/snapd/snap-confine".  Permission denied; attempted to load a profile while confined?
Mar 27 12:05:38 nas-10-backup apparmor[75]: /sbin/apparmor_parser: Unable to replace "mount-namespace-capture-helper".  Permission denied; attempted to load a profile while confined?
Mar 27 12:05:38 nas-10-backup apparmor[75]: /sbin/apparmor_parser: Unable to replace "/usr/lib/snapd/snap-confine".  Permission denied; attempted to load a profile while confined?
Mar 27 12:05:38 nas-10-backup apparmor[75]:    ...fail!
Mar 27 12:05:38 nas-10-backup systemd[1]: apparmor.service: Main process exited, code=exited, status=123/n/a
Mar 27 12:05:38 nas-10-backup systemd[1]: apparmor.service: Failed with result 'exit-code'.
Mar 27 12:05:38 nas-10-backup systemd[1]: Failed to start AppArmor initialization.
```

**Comment by huegelc** [comment] 2019-03-27 12:16
However, lxd runs fine from the deb repository
```
driver: lxc
  driver_version: 3.0.3
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.18-12-pve
  server: lxd
  server_pid: 1794
  server_version: 3.0.3
  storage: dir
  storage_version: "1"
  server_clustered: false
  server_name: nas-10-backup
  project: ""
```
```
lxc list
+--------+---------+---------------------+-----------------------------------------------+------------+-----------+
|  NAME  |  STATE  |        IPV4         |                     IPV6                      |    TYPE    | SNAPSHOTS |
+--------+---------+---------------------+-----------------------------------------------+------------+-----------+
| bionic | RUNNING | 10.249.61.23 (eth0) | fd42:ac20:517b:a3e9:216:3eff:fe00:9331 (eth0) | PERSISTENT | 0         |
+--------+---------+---------------------+-----------------------------------------------+------------+-----------+
```

**Comment by huegelc** [comment] 2019-03-27 12:28
OK, adding
```
lxc.cap.drop =
lxc.cap.drop = mac_override sys_time sys_module sys_rawio
```
to the proxmox config  `/etc/pve/lxc/$vmid.conf` did the trick

```
 lxc list
+----------+---------+----------------------+-----------------------------------------------+------------+-----------+
|   NAME   |  STATE  |         IPV4         |                     IPV6                      |    TYPE    | SNAPSHOTS |
+----------+---------+----------------------+-----------------------------------------------+------------+-----------+
| lxd-snap | RUNNING | 10.88.161.152 (eth0) | fd42:7d71:c7f3:5c88:216:3eff:feab:22c8 (eth0) | PERSISTENT |           |
+----------+---------+----------------------+-----------------------------------------------+------------+-----------+
```

```
driver: lxc
  driver_version: 3.1.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.18-12-pve
  server: lxd
  server_pid: 1401
  server_version: "3.11"
  storage: dir
  storage_version: "1"
  server_clustered: false
  server_name: nas-10-backup
  project: default
```

What exactly happend? Thanks

**Comment by stgraber** [comment] 2019-03-27 14:56
Ah, it was most likely appamor misbehaving inside the proxmox managed container.
I assumed you were running the container on LXD which does have additional support for apparmor nesting.

Okay, so looks like we tracked this one down to:
 - LXD version without --refresh (now on 3.11 so should be fine)
 - Environment which didn't allow for enough uid/gid or mknod capability (now fixed with a privileged container)

**Closed by stgraber** 2019-03-27 14:56 UTC
Labels: Incomplete

**Comment by huegelc** [comment] 2019-03-27 23:01
Yes, thank you!
