### ISSUE TITLE
Memory leak over time

### ISSUE THREAD

**Issue by pranjalnanavaty** [lxc/lxd#7806] opened 2020-08-25 07:49 UTC
Required information

 * Distribution: **Ubuntu**
 * Distribution version: **Ubutnu 18.04.4 LTS**
 * The output of "lxc info"
    ```
    config:
    core.https_address: '[::]'
    core.proxy_http: http://10.10.12.10:8080
    core.proxy_https: http://10.10.12.10:8080
    core.trust_password: true
    api_extensions:
    - storage_zfs_remove_snapshots
    - container_host_shutdown_timeout
    - container_stop_priority
    - container_syscall_filtering
    - auth_pki
    - container_last_used_at
    - etag
    - patch
    - usb_devices
    - https_allowed_credentials
    - image_compression_algorithm
    - directory_manipulation
    - container_cpu_time
    - storage_zfs_use_refquota
    - storage_lvm_mount_options
    - network
    - profile_usedby
    - container_push
    - container_exec_recording
    - certificate_update
    - container_exec_signal_handling
    - gpu_devices
    - container_image_properties
    - migration_progress
    - id_map
    - network_firewall_filtering
    - network_routes
    - storage
    - file_delete
    - file_append
    - network_dhcp_expiry
    - storage_lvm_vg_rename
    - storage_lvm_thinpool_rename
    - network_vlan
    - image_create_aliases
    - container_stateless_copy
    - container_only_migration
    - storage_zfs_clone_copy
    - unix_device_rename
    - storage_lvm_use_thinpool
    - storage_rsync_bwlimit
    - network_vxlan_interface
    - storage_btrfs_mount_options
    - entity_description
    - image_force_refresh
    - storage_lvm_lv_resizing
    - id_map_base
    - file_symlinks
    - container_push_target
    - network_vlan_physical
    - storage_images_delete
    - container_edit_metadata
    - container_snapshot_stateful_migration
    - storage_driver_ceph
    - storage_ceph_user_name
    - resource_limits
    - storage_volatile_initial_source
    - storage_ceph_force_osd_reuse
    - storage_block_filesystem_btrfs
    - resources
    - kernel_limits
    - storage_api_volume_rename
    - macaroon_authentication
    - network_sriov
    - console
    - restrict_devlxd
    - migration_pre_copy
    - infiniband
    - maas_network
    - devlxd_events
    - proxy
    - network_dhcp_gateway
    - file_get_symlink
    - network_leases
    - unix_device_hotplug
    - storage_api_local_volume_handling
    - operation_description
    - clustering
    - event_lifecycle
    - storage_api_remote_volume_handling
    - nvidia_runtime
    - container_mount_propagation
    - container_backup
    - devlxd_images
    - container_local_cross_pool_handling
    - proxy_unix
    - proxy_udp
    - clustering_join
    - proxy_tcp_udp_multi_port_handling
    - network_state
    - proxy_unix_dac_properties
    - container_protection_delete
    - unix_priv_drop
    - pprof_http
    - proxy_haproxy_protocol
    - network_hwaddr
    - proxy_nat
    - network_nat_order
    - container_full
    - candid_authentication
    - backup_compression
    - candid_config
    - nvidia_runtime_config
    - storage_api_volume_snapshots
    - storage_unmapped
    - projects
    - candid_config_key
    - network_vxlan_ttl
    - container_incremental_copy
    - usb_optional_vendorid
    - snapshot_scheduling
    - container_copy_project
    - clustering_server_address
    - clustering_image_replication
    - container_protection_shift
    - snapshot_expiry
    - container_backup_override_pool
    - snapshot_expiry_creation
    - network_leases_location
    - resources_cpu_socket
    - resources_gpu
    - resources_numa
    - kernel_features
    - id_map_current
    - event_location
    - storage_api_remote_volume_snapshots
    - network_nat_address
    - container_nic_routes
    - rbac
    - cluster_internal_copy
    - seccomp_notify
    - lxc_features
    - container_nic_ipvlan
    - network_vlan_sriov
    - storage_cephfs
    - container_nic_ipfilter
    - resources_v2
    - container_exec_user_group_cwd
    - container_syscall_intercept
    - container_disk_shift
    - storage_shifted
    - resources_infiniband
    - daemon_storage
    - instances
    - image_types
    - resources_disk_sata
    - clustering_roles
    - images_expiry
    - resources_network_firmware
    - backup_compression_algorithm
    - ceph_data_pool_name
    - container_syscall_intercept_mount
    - compression_squashfs
    - container_raw_mount
    - container_nic_routed
    - container_syscall_intercept_mount_fuse
    - container_disk_ceph
    - virtual-machines
    - image_profiles
    - clustering_architecture
    - resources_disk_id
    - storage_lvm_stripes
    - vm_boot_priority
    - unix_hotplug_devices
    - api_filtering
    - instance_nic_network
    - clustering_sizing
    - firewall_driver
    - projects_limits
    - container_syscall_intercept_hugetlbfs
    - limits_hugepages
    - container_nic_routed_gateway
    - projects_restrictions                                                                                                       
    - custom_volume_snapshot_expiry
    - volume_snapshot_scheduling
    - trust_ca_certificates
    - snapshot_disk_usage
    - clustering_edit_roles
    - container_nic_routed_host_address
    - container_nic_ipvlan_gateway
    - resources_usb_pci
    - resources_cpu_threads_numa
    - resources_cpu_core_die
    - api_os
    - container_nic_routed_host_table
    - container_nic_ipvlan_host_table
    - container_nic_ipvlan_mode
    - resources_system
    - images_push_relay
    - network_dns_search
    - container_nic_routed_limits
    - instance_nic_bridged_vlan
    - network_state_bond_bridge
    - usedby_consistency
    - custom_block_volumes
    - clustering_failure_domains
    - resources_gpu_mdev
    - console_vga_type
    - projects_limits_disk
    - network_type_macvlan
    - network_type_sriov
    api_status: stable
    api_version: "1.0"
    auth: trusted
    public: false
    auth_methods:
    - tls
    environment:
    addresses:
    - 10.10.140.110:8443
    architectures:
    - x86_64
    - i686
    certificate: |
        -----BEGIN CERTIFICATE-----
        MIIFUzCCAzugAwIBAgIRANzPDnK/RdPT9VwguMqybIgwDQYJKoZIhvcNAQELBQAw
        OjEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEaMBgGA1UEAwwRcm9vdEBS
        TkktUEQtSE9TVDUwHhcNMTkwNDI1MTQxMTI0WhcNMjkwNDIyMTQxMTI0WjA6MRww
        GgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRowGAYDVQQDDBFyb290QFJOSS1Q
        RC1IT1NUNTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBALuow0QptsfX
        jJFC2iF7Xvsfb8Gt/bmBXd9jTEjB7+hCcRzeu+kLrBsrpzjz0zwlxhhfpjlOI9SI
        itkZsLYdpKVzXo0OQwjftgmY1E4/POTKQfCzmaJni+CxkkV7g0bRoC0ifUu8bFYS
        rfIGCA9GTVNlBilRdIex2jemBPJhzOLlRoiVVDCoe3PendEqyD6LV6eO2adnyPXB
        5sbHaSm788RIq8b7hQY0kJMseDs3RqjGxX7aZPKan62J/MImMJxO+s2HDhx6wrgy
        YZhPAoh4UlHA9MVvIEi0V0+wdTGTGnDMDz7G5PDIRnSuNL28gbUgBq025eTw49rB
        LHgjezonAWoXePQ3M/E9NaYI2wpSgbRnvBaobAxhWufc65r+spxUzi1LbUdAiCBb
        +CU5ylcxEmDvCuDX9FUW3cguESUgIRSUGjtfxX6FnEkEBPz84sF6pk5MMA54TlH3
        lLCdtVvg0VbY7ldSsxrM18SAmpbvK7Z7NRrA+61vPWN/H1GxkVvQJ8ofWTXWBOMw
        fFcEB5CHso2RL52zq2N/JZVym11a6fHeMnRspTcRbuhVKU5gc2EXzd+Ax5KsxRoX
        KNCuiIlNGHaRmo61Hi5ifqljHUFP/mdgAnsa142/JRwl4vzvIfQqHvPM4jqFIvJ7
        IjXBo5U48/a5s8LMryuOCHiMrH3iz+7DAgMBAAGjVDBSMA4GA1UdDwEB/wQEAwIF
        oDATBgMVHSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMB0GA1UdEQQWNBSC
        DFJOSS1QRC1IT1NUNYcECgqMbjANBgkqhkiG9w0BAQsFAAOCAgEAidaIMPpSrptN
        davd6Iqic2NKiKzYrBKv5lfrqZLKi/AQSVQOnvLY3xaoyFGFzLzAhx6Ddeqhs9mm
        FQXPK5Dubs+pOD8Ay3RmxlXvxvtIA2O1YSc4aCyzRvseDY4UL1BzXsDUN1ik71uY
        0AH89R594qfeav67hmIo0X239qtkNaItSXGBAdjPuXrryCEDs18I6Xy76XyUHWWr
        ThnAWkWEmtejOS9FmyZ8BCHejOpFkJ9y/kCESnNMLzyLPIj+E0iHA5itt5lc6F1A
        ee7tCMpA5YKPpb8vcfrlVVF2fJ1/V+YM+MXbsrR7lAippvJ2TFJWCiFBvFj9A4ZV
        kFQabIwkzRVQkJPIUo/a0sWpYJ7rNjMQ/LFrKw78vDaOyWANzatH9d1+FEWBr+Lg
        fuZwnbrZBzu4VSquXxbTjTKnzbPATQqjHd7wxWOWiO6rK5t3UlDimOD27JzS45cn
        GZarvtjZUNH+p/NJ/BwgMVoIuhWg2yLPk7cRjxtXI2kU9Hnarqw8hB8T6zY7V8mH
        n0cD55gaK/Bf9SjsFVXeTWVft2FWsRIdWieNcuEkZ2Dh2Q9eK5s861CKW4xmeFDS
        MXTAuQ3m34pp32MsZP5cUFvQLFXSrD+TEm+V/X9sLRdJ8RK3gQnzH01Q1HTw/PI7
        EJiXE1cri42WXzg9/6QWJeouMFDRM40=
        -----END CERTIFICATE-----
    certificate_fingerprint: a434de9497ea5c048a40c8a42cc929fb6c09a9cbc37e50cb0d5bd344ba43696e
    driver: lxc
    driver_version: 4.0.4
    firewall: xtables
    kernel: Linux
    kernel_architecture: x86_64
    kernel_features:
        netnsid_getifaddrs: "false"
        seccomp_listener: "false"
        seccomp_listener_continue: "false"
        shiftfs: "false"
        uevent_injection: "false"
        unpriv_fscaps: "true"
    kernel_version: 4.15.0-112-generic
    lxc_features:
        cgroup2: "true"
        devpts_fd: "false"
        mount_injection_file: "true"
        network_gateway_device_route: "true"
        network_ipvlan: "true"
        network_l2proxy: "true"
        network_phys_macvlan_mtu: "true"
        network_veth_router: "true"
        pidfd: "true"
        seccomp_allow_deny_syntax: "true"
        seccomp_notify: "true"
        seccomp_proxy_send_notify_fd: "false"
    os_name: Ubuntu
    os_version: "18.04"
    project: default
    server: lxd
    server_clustered: false
    server_name: HOST5
    server_pid: 99736
    server_version: "4.4"
    storage: zfs
    storage_version: 0.7.5-1ubuntu16.9
    ```

# Issue description

After the host machine is rebooted and all the containers are started, slowly over time I notice some memory leak, which builds-up to occupy more than 80% of total RAM on the host machine.

If I add up all the RAM utilized by the containers running on that host, it accounts for less than 20% of the total RAM utilised on that host.

If the host machine is not rebooted for a period of >25days, it results into the host machine's RAM constantly utilized ~99% whereas the summation of total RAM used by the containers is ~40%.

The is somewhat similar to #6362 

# Steps to reproduce (I'll describe my setup here):

 1. A host machine with 128GB RAM and 32 CPU(s).
 2. Close to 50 Containers, running application based on various technologies like Java, Python, Javascript etc.
 3. Within a week, the sum of RAM `Memory Usage: Memory (current)` as given by the output of `lxc-info NAME` for all the containers is much less than the output of `free -mh` on the host machine.

**Comment by freeekanayaka** [comment] 2020-08-25 07:57
Since when are you running this exact setup? Since when have you experienced the memory leak? In other words, is there a point in time you can say a regression occurred?

**Comment by pranjalnanavaty** [comment] 2020-08-25 08:32
I have been using this setup for the last 3 years. I am using `snap` to install `lxd`.

I have started to face this issue from the 3-4 months, can't say the exact `lxd version`, might be `4.0` or `4.1`.

**Comment by freeekanayaka** [comment] 2020-08-25 09:07
So would you be able to positively say that 3 months ago the bug was already there?

**Comment by pranjalnanavaty** [comment] 2020-08-25 09:22
Yes, I am positive about the fact that I am facing a memory leak since the last 3 months.

**Comment by freeekanayaka** [comment] 2020-08-25 09:48
Okay, it suggests that if we have regressed that's because of a change older than 3 months then.

**Comment by stgraber** [comment] 2020-08-25 12:48
I don't suppose you can give us access to one of them so we can try to sort out where the memory usage is coming from?

**Comment by pranjalnanavaty** [comment] 2020-08-25 14:53
The complete setup is within a private network and is running production environments, thus I regret to say that I won't able to give you access to any of the host.

Although I can run any specific commands that you can suggest and share their outputs or I can share my screen with you to debug this memory leak.

**Comment by stgraber** [comment] 2020-08-25 17:31
I guess a good starting point would be:
 - free -m
 - cat /proc/meminfo
 - ps fauxww
 - cat /proc/spl/kstat/zfs/arcstats
 - cat /sys/fs/cgroup/memory/lxc.payload.*/memory.usage_in_bytes
 - `df -h -Ta | grep tmpfs` in every container

That should let us check how much memory LXD and related processes actually use (those are the bits we control, so if those look okay, we'll close the issue) as well as check some of the other spots where your memory could be going, including tmpfs mounts in containers and the ZFS cache (which doesn't not count as cached/buffered).

**Comment by pranjalnanavaty** [comment] 2020-08-26 08:06
Here is a gist of outputs of all these commands https://gist.github.com/pranjalnanavaty/3d7a4bd3fbc1cdf34e70adca89cb7773

**Comment by pranjalnanavaty** [comment] 2020-09-01 08:23
Did you get a chance to look at the gist of outputs to check if there is any memory leak from LXD or the related processes?

**Comment by stgraber** [comment] 2020-09-09 23:15
Sorry for the long delay, I've been on vacation for the past 10 days or so and just catching up on things now.

**Comment by stgraber** [comment] 2020-09-09 23:23
A few observations so far:
 - You seem to have both the LXD snap and deb installed. You should remove the LXD deb, though that will only save you 20MB or so of RAM.
 - LXD snap uses 172MB of RAM
 - ZFS ARC is using 36.5GB of RAM
 - Your container use around 46GB of RAM

Your total used memory is 106GB of which:
 - VFS cache uses 21.5GB
 - Containers use 46GB
 - ZFS uses 36.5GB

This leaves you with 2GB of unaccounted memory which can probably be tracked down to the various tmpfs instances and to host processes other than LXD itself as well as some random in-kernel allocations.

So overall, not seeing anything unexpected. I suspect you got confused by ZFS and its built-in cache counting as normal memory usage rather than cache. This is fine as ZFS will release memory as needed by the system, however if you want to force it to use less, you can configure an ARC max value of just a few GBs.

**Closed by stgraber** 2020-09-09 23:23 UTC

**Comment by pranjalnanavaty** [comment] 2020-09-11 14:36
Thank you for the detailed explanation and pointing out the memory distribution.
