### ISSUE TITLE
Error: Failed to delete RBD storage volume for container "test" on storage pool "cheph_cluster"

### ISSUE THREAD

**Issue by bit** [lxc/lxd#4455] opened 2018-04-16 12:27 UTC
* Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info":
$ lxc info
config:
  core.https_address: x.x.x.x:8443
  core.trust_password: true
  images.auto_update_interval: "15"
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - x.x.x.x:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  certificate_fingerprint: xxx
  driver: lxc
  driver_version: 3.0.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-15-generic
  server: lxd
  server_pid: 5457
  server_version: 3.0.0
  storage: ceph
  storage_version: ceph version 12.2.4 (52085d5249a80c5f5121a76d6288429f35e4e77b)
    luminous (stable)
  server_clustered: true
  server_name: cluster01

# Issue description

$ lxc delete test

fails with:

Error: Failed to delete RBD storage volume for container "test" on storage pool "ceph_cluster"

# Steps to reproduce

 1. create container with ceph backend
 2. delete container (from other node?)
 3. delete fails with error above

**Comment by brauner** [comment] 2018-04-16 12:28
@free will best know what's going on since this is cluster related.

**Comment by bit** [comment] 2018-04-16 17:12
lvl=warn msg="Raft: Failed to get previous log: 94 log not found (last: 0)" t=2018-04-16T14:04:31+0200
lvl=eror msg="Failed to unmap RBD storage volume \"cluster/container_test\": Failed to run: rbd --id admin --cluster ceph --pool cluster unmap container_test: rbd:
lvl=eror msg="Failed to delete RBD storage volume for container \"test\" on storage pool \"cluster\"" t=2018-04-16T14:14:08+0200

those where the errors. could not reproduce the error so far after deleting the storage pool and re-creating the cluster.

**Comment by freeekanayaka** [comment] 2018-04-16 17:48
It seems the failure occurred when running:

```
rbd --id admin --cluster ceph --pool cluster unmap container_test
```

It's weird that the output of the above command (as logged by LXD) seems to just be "rbd:", at least as I understand the code that triggers it.

@brauner: does it ring any bell?

**Comment by brauner** [comment] 2018-04-17 18:51
That usually happens when the rbd kernel driver hangs. Anything interesting in `dmesg`?

**Comment by bit** [comment] 2018-04-18 05:13
did not see anything related in dmesg, the cluster was slow while this happened though.

**Comment by stgraber** [comment] 2018-04-18 19:49
Since the rbd call looked correct (right arguments) and the system has been reinstalled since, I'll close this issue for now. There's nothing obviously wrong in what LXD attempted and the best clue to figure out what happened would be to get another affected system, trying to manually interact with CEPH from it.

If anyone else runs into this on their setup, please comment here and we'll try to help you debug it as quickly as possible.

**Closed by stgraber** 2018-04-18 19:49 UTC

**Comment by bit** [comment] 2018-08-26 12:45
ran into this again the other day:
this happens after adding files to the container via api without specifying a target (i.e. using python-lxd).
in that case the ceph volume gets mounted on multiple nodes in the cluster, and never gets unmapped after use.

i would have assume those operations would always happen on the node the containers is running on or is scheduled to run on in the future.

as a workaround i was able to not use python-lxd but the rest-api directly and make sure that all operations happen on the node the container runs on.

**Comment by stgraber** [comment] 2018-08-26 20:12
Hmm, indeed, file operations should very much be forwarded to the node which is running the container.
@freeekanayaka any idea what's going on here?

**Comment by stgraber** [comment] 2018-08-26 22:58
@bit your container was running at the time, right?

I just did a few basic checks and our API does forward requests to the node running the container.

**Comment by stgraber** [comment] 2018-08-26 23:06
@bit just looked at the code around this and the forwarding logic is in place and working and the storage logic for pulling/pushing data in/out of the container seems fine too.

If you can easily reproduce this, can you please file a new issue, including the LXD version of all nodes and the full `lxc monitor` output while doing the API calls? Would also be nice if you could dump the rbdmap of the various nodes through this, to see exactly when it gets mapped on the wrong node.

FWIW, I checked the code for the current master branch of LXD, it could be that you're running an older version of LXD which differs somehow or that the mount issue is caused by something else.

**Comment by bit** [comment] 2018-08-27 08:10
stgraber, this was before running the container, create, copy files, start.
will try to create a test case, this is with lxd from ubuntu 18.04

**Comment by stgraber** [comment] 2018-08-27 14:07
@bit thanks, could be that we're missing a unmount call somewhere in there... it's happened before
