### ISSUE TITLE
A container created from images:ubuntu/xenial/i386 can't run sudo command

### ISSUE THREAD

**Issue by Inetgate** [lxc/lxd#2323] opened 2016-08-30 11:43 UTC
# Required information

 * Distribution: Ubuntu Server
 * Distribution version: 16.04.1
 * The output of "lxc info" or if that fails:
Name: ub0001-32
Architecture: i686
Created: 2016/08/30 10:54 UTC
Status: Running
Type: persistent
Profiles: default
Pid: 9444
Ips:
  eth0:	inet   	10.211.12.121  	vethUB50B3
  eth0:	inet6  	fe80::216:3eff:fec1:a28	vethUB50B3
  lo:  	inet   	127.0.0.1
  lo:  	inet6  	::1
Resources:
  Processes: 9
  Memory usage:
    Memory (current): 10.77MB
    Memory (peak): 15.37MB
  Network usage:
    eth0:
      Bytes received: 922 bytes
      Bytes sent: 1.34kB
      Packets received: 7
      Packets sent: 11
    lo:
      Bytes received: 0 bytes
      Bytes sent: 0 bytes
      Packets received: 0
      Packets sent: 0

   * Kernel version: 4.4.0-36-generic
   * LXC version: 2.0.4
   * LXD version: 2.0.4
   * Storage backend in use: directory

# Issue description
sudo command inside 32 bit xenial container fail.

A brief description of what failed or what could be improved.
When I create 64 bit xenial container, which have no issue, but I create 32 bit xenial container, which return error.
I checked both 2GB memory host and 4GB memory host, results of 32 bit containers are same.

# Steps to reproduce

 1. Step one: $ lxc launch images:ubuntu/xenial/i386 <container>
 2. Step two: $ lxc exec <container> bash
 3. Step three: # sudo -V, which return "sudo: main: unable to allocate memory"

# Information to attach

 - [ ] any relevant kernel output (dmesg)
 - [ ] container log (lxc info NAME --show-log)
 - [ ] main daemon log (/var/log/lxd.log)
 - [ ] output of the client with --debug
 - [ ] output of the daemon with --debug

**Comment by stgraber** [comment] 2016-08-30 17:15
This is related to the libc issue mentioned in #936 and in a number of other LXD issues.

There is some work in progress upstream by @hallyn to sort this out but it may take a while before they actually accept the patch and for it to make it into all distros.

Until then, you can run:

     lxc exec container -- script /dev/null -c bash

Which I've confirmed here was then able to run "sudo -V" properly.

**Comment by stgraber** [comment] 2016-08-30 17:16
Entering the container over SSH should also work around that particular issue.

**Comment by stgraber** [comment] 2016-08-30 17:16
Closing as this issue is caused by a glibc issue which we're already tracking upstream.

**Closed by stgraber** 2016-08-30 17:16 UTC
