### ISSUE TITLE
Order of commands using --project inconsistant

### ISSUE THREAD

**Issue by avsdev-cw** [lxc/lxd#7625] opened 2020-07-06 12:29 UTC
# Required information

 * Distribution: Debian
 * Distribution version: Buster
 * The output of "lxc info" or if that fails:
<details>
 <summary>Click to expand</summary>

```
config:
  core.https_address: 127.0.0.1:8443
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
- firewall_driver
- projects_limits
- container_syscall_intercept_hugetlbfs
- limits_hugepages
- container_nic_routed_gateway
- projects_restrictions
- custom_volume_snapshot_expiry
- volume_snapshot_scheduling
- trust_ca_certificates
- snapshot_disk_usage
- clustering_edit_roles
- container_nic_routed_host_address
- container_nic_ipvlan_gateway
- resources_usb_pci
- resources_cpu_threads_numa
- resources_cpu_core_die
- api_os
- container_nic_routed_host_table
- container_nic_ipvlan_host_table
- container_nic_ipvlan_mode
- resources_system
- images_push_relay
- network_dns_search
- container_nic_routed_limits
- instance_nic_bridged_vlan
- network_state_bond_bridge
- usedby_consistency
- custom_block_volumes
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 127.0.0.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    <<REDACT>>
  certificate_fingerprint: <<REDACT>>
  driver: lxc
  driver_version: 4.0.3
  firewall: xtables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "false"
    seccomp_listener: "false"
    seccomp_listener_continue: "false"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 4.19.0-8-amd64
  lxc_features:
    cgroup2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_notify: "true"
  os_name: Debian GNU/Linux
  os_version: "10"
  project: default
  server: lxd
  server_clustered: false
  server_name: genin
  server_pid: 16606
  server_version: "4.3"
  storage: lvm
  storage_version: 2.02.176(2) (2017-11-03) / 1.02.145 (2017-11-03) / 4.39.0

```
</details>

# Issue description

Most lxc commands allow you to place the `--project` arg immediately after `lxc` however some (shell specifically) do not:
```
$ lxc --project some-project list
+-----------+---------+-------------------+------+-----------+-----------+
|   NAME    |  STATE  |       IPV4        | IPV6 |   TYPE    | SNAPSHOTS |
+-----------+---------+-------------------+------+-----------+-----------+
| c1        | RUNNING | 10.5.5.178 (eth0) |      | CONTAINER | 0         |
+-----------+---------+-------------------+------+-----------+-----------+
$ lxc --project some-project shell c1
Error: unknown command "shell" for "lxc"
$ lxc shell --project some-project c1
mesg: ttyname failed: No such device
root@c1:~# exit
logout
```
# Steps to reproduce
Run the command with the `--project` arg straight after lxc

# Expected outcome
Usage of the `--project` arg should be consistent (I for one would prefer to use it directly after `lxc` since it makes creating alias's a lot easier: `alias lxc-p1='lxc --project some-project'`)

**Comment by stgraber** [comment] 2020-07-06 14:05
It is consistent, the problem is that `lxc shell` isn't a real command :)

`lxc shell` is an alias for `exec @ARGS@ -- su -l` (that's why it's never mentioned in help or anywhere in the official doc)

We'll have to see if we can somehow combine early flag arguments with aliases but it may just not be something we can really do with our parser.

**Comment by avsdev-cw** [comment] 2020-07-06 14:33
Ah.

I've no understanding of Go so please forgive any misunderstandings here:

When calling lxc how are the arguments handled? Obviously the command line parser doesn't just take the first parameter and assume it's a command because it picks up that the command I am trying to run is "shell" (judging from the "shell is not a command of lxc" error). I'm guessing that the `--project` parameter is parsed in 2 places: by the initial cli handler and by the command being run? So the initial handler doesn't just append the preceding arguments to the required command? This is my theory based on:
```
$ lxc list --fast
+-----------+---------+-------------------+------+-----------+-----------+
|   NAME    |  STATE  |       IPV4        | IPV6 |   TYPE    | SNAPSHOTS |
+-----------+---------+-------------------+------+-----------+-----------+
| c1        | RUNNING | 10.5.5.178 (eth0) |      | CONTAINER | 0         |
+-----------+---------+-------------------+------+-----------+-----------+
$lxc --fast list
Error: unknown flag: --fast
```
If that is the case, how is `--project` passed into the commands? Can the same method be used to pass it into the exec call?  I'm assuming the full alias unwrap might be something like `system("lxc exec @ARGS@ -- su -l")`?

**Comment by stgraber** [comment] 2020-07-06 15:30
`--project` is a top level argument (as seen if you just do `lxc --help`) whereas `--fast` is a command argument for `list`.

Arguments always must come after their respective owner, so it's valid to do `lxc --debug list` or `lxc list --debug` but it's not valid to do `lxc --fast list`.

And yeah, the way aliases work is pretty much looking at the first parameter to the command and looking it up in a map.
So `lxc shell --debug blah` has the command line look for `shell` in the map, then re-exec itself as `lxc exec --debug blah -- su -l`.

As that logic is done ahead of the parser, it's unaware of what flags are, so if you pass `lxc --project shell blah`, it tries to look up an alias called `--project` which doesn't exist, then goes into the normal parser which then reports that `shell` isn't a valid command.

The likely fix for this is to strip anything that looks like a flag and move those over to the @ARGS@ part.

**Comment by avsdev-cw** [comment] 2020-07-06 16:21
After looking around a bit further, I figure the following are the key files:
https://github.com/lxc/lxd/blob/master/lxc/main.go
https://github.com/lxc/lxd/blob/master/lxc/main_aliases.go

I see that the command parsing etc is all handled by cobra, had a little play around with it.

Initially I though you could perhaps use [`cobra.Find()`](https://godoc.org/github.com/spf13/cobra#Command.Find) to check if the command line matches a command that is registered and then handle the case where `error != <nil>`. Sadly it doesn't appear that the return tells you what it thinks the command was and I can't find a function that would do that, (you COULD parse the error string at a pinch). And using [`cobra.ParseFlags()`](https://godoc.org/github.com/spf13/cobra#Command.ParseFlags) only works if all the provided flags are global & valid.  [`cobra.Traverse()`](https://godoc.org/github.com/spf13/cobra#Command.Traverse) seems to be more useful, in fact it parses any global command args that precede a command (assuming there are no invalid ones) but it behaves much like `cobra.Find()` in that it doesn't return what it thinks the command might be (in fact it doesn't even error).

```
The likely fix for this is to strip anything that looks like a flag and move those over to the @Args@ part.
```
As you say, that may be the only way to handle it.  Out of curiosity, how come `lxc shell` ended up being the only built-in alias?

It seems like I may have opened a can of worms with this one.

**Comment by stgraber** [comment] 2020-07-06 16:54
Not sure how we ended up deciding to ship that one by default, I suspect we had an even more hardcoded version of that one before (before we introduced `lxc alias`), most likely coming from one of the other LXD devs using that constantly and wanting it built-in :)

I personally always use `lxc exec` and we make sure not to show `lxc shell` in docs as it doesn't work in some images and would lead to more confusion, but we also don't want to remove things and break existing users.

**Comment by avsdev-cw** [comment] 2020-07-06 21:28
Much appreciated

**Comment by avsdev-cw** [comment] 2020-09-16 09:25
I had assumed that this update had fixed it (at the time I didn't have a beta testing capability, so I waited until 4.4 was in stable), but apparently not:
```
cwilliams@snappy-bugs:~$ snap list
Name    Version    Rev    Tracking       Publisher   Notes
core    16-2.46.1  9993   latest/stable  canonical✓  core
core18  20200724   1885   latest/stable  canonical✓  base
lxd     4.4        16926  latest/beta    canonical✓  -
cwilliams@snappy-bugs:~$ lxc --project test shell c1
Error: unknown command "shell" for "lxc"
cwilliams@snappy-bugs:~$ snap list
Name    Version    Rev    Tracking       Publisher   Notes
core    16-2.46.1  9993   latest/stable  canonical✓  core
core18  20200724   1885   latest/stable  canonical✓  base
lxd     4.5        17147  latest/beta    canonical✓  -
cwilliams@snappy-bugs:~$ lxc --project test shell c1
Error: unknown command "shell" for "lxc"
cwilliams@snappy-bugs:~$ lxc --version
4.5
```

**Comment by stgraber** [comment] 2020-09-16 20:32
Sent a fix, though note that what you're trying to do above will never work.

It's impossible for the alias parser to know that `lxc --project test shell c1` should be split as:
 - Flags: --project test
 - Command: shell
 - Arguments: c1

Rather than:
 - Flags: --project
 - Command test
 - Arguments: shell c1

It first needs to know what the command is before any argument parsing can be done so there's a chicken and egg problem there.

Instead what my branch fixes is using this `lxc --project=test shell c1` as in such cases, we can easily identify and separate leading flags.

**Closed** 2020-09-17 04:30 UTC
