### ISSUE TITLE
Option to let rsync finish with errors if the operator desires

### ISSUE THREAD

**Issue by gaia** [lxc/lxd#9706] opened 2021-12-16 00:22 UTC
* Kernel version: 5.10.0-9-amd64 Debian (source)/5.4.0-89-generic Ubuntu (target)
   * LXC version: 4.0.11 | 6.1.0 (both)
   * LXD version: 4.21 (source)/4.0.8 (target)
   * Storage backend in use: dir (both`are dir drivers on underlying LVM using an entire partition)

# Issue description

When copying a container with

`lxc copy demo-container node4: --stateless --no-profiles --instance-only -s ssd`

i get

`Failed instance creation: Error transferring instance data: Rsync send failed: demo-container, /var/snap/lxd/common/lxd/storage-pools/default/containers/cdemo-container/: [exit status 24 read unix @lxd/ce8bdca1-4c47-49d8-aff8-278cb5ebc919->@: use of closed network connection] (file has vanished`

because as expected files are being written and deleted constantly. i do not expect a consistent copy, but the good news is that the part that is constantly changing is “self healing”, so it gets rebuilt when missing/corrupt.

with this in mind, is it possible to have the instance be created, in other words, ignore any file errors? I know that standard rsync ignores these errors when copying.

# Resolution

Have an option to let rsync finish with errors, if the operator desires.

[see this forum issue](https://discuss.linuxcontainers.org/t/lxc-copy-ignore-errors/12900)

**Comment by stgraber** [comment] 2021-12-16 04:34
There does not appear to be an rsync flag to control this behavior.

`--ignore-missing-args` handles files that are directly requested (on the command line) which don't exist at scanning time, but per the manpage, does not cause rsync to ignore files which vanish between the scanning and transferring stage.

So with that in mind, I'm not seeing any way to prevent rsync from exiting when encountering a vanished file and so no way for us to have it continue anyway.

We could have LXD ignore return code `24` which is the `partial transfer due to vanished source files` but just how partial the transfer is may be version dependent (the manpage doesn't tell us whether rsync will immediately exit with 24 upon finding a missing file or if it will continue with what's left and then exit).

As it's a source side option, I guess we could have LXD automatically ignore return code 24 when transferring a running instance and keep failing when transferring a snapshot or volume as those shouldn't hit this normally.

**Comment by gaia** [comment] 2021-12-16 05:07
> We could have LXD ignore return code `24` which is the `partial transfer due to vanished source files` but just how partial the transfer is may be version dependent (the manpage doesn't tell us whether rsync will immediately exit with 24 upon finding a missing file or if it will continue with what's left and then exit).

I am under the impression it finishes and exits with a code 24.

> As it's a source side option, I guess we could have LXD automatically ignore return code 24 when transferring a running instance and keep failing when transferring a snapshot or volume as those shouldn't hit this normally.

That would be incredibly useful!

PS: one day (one can dream) a subsequent copy could even be differential (only updated files, might as well since rsync is well equipped for this purpose)

**Comment by stgraber** [comment] 2021-12-16 05:56
@markylaing another thing you can look into, probably after that `lxc alias` thing from the forum.

For this one, the caller is effectively `lxd/storage/drivers/generic_vfs.go` and the `genericVFSMigrateVolume` function.

I think the easiest there would be to wrap the existing `rsync.Send` call into a check for:
 - vol.Type() == VolumeTypeContainer
 - !vol.IsSnapshot()

If both of those are true and the return code in the rsync.Send error is 24, then ignore it (make it equivalent to nil).

**Comment by tomponline** [comment] 2021-12-16 09:30
Making rsync ignore exit code 24 copy errors during a migration seems problematic (especially when we don't know for sure all the scenarios that exit code 24 occurs), especially if the migration is part of a move and at the end the source is deleted preventing any recovery of missing data should exit code 24 occur in another scenario.

Also, importantly, we already have catered for this scenario before in the `CreateInstanceFromCopy` storage pool function and in the storage drivers:

https://github.com/lxc/lxd/blob/86128969a8bbf5a81ce487062cfa647be5394926/lxd/storage/backend_lxd.go#L853-L861 

This includes handling the cross-pool migration scenario which uses (by way of `MigrateInstance` (https://github.com/lxc/lxd/blob/86128969a8bbf5a81ce487062cfa647be5394926/lxd/storage/backend_lxd.go#L924-L929) the same `genericVFSMigrateVolume` function we are talking about here).

So I would prefer that we bring the `MigrateInstance` function into line with the `CreateInstanceFromCopy` function so they behave consistently and freeze running instances when the storage pool has `RunningCopyFreeze=true` (which is currently ceph and dir).

Additionally for the storage drivers that have `RunningCopyFreeze=false` there is also room for improvement/consistency here by making those drivers that support fast snapshots take a temporary one as the source of the migration.

We already do this for backup sources on those drivers (before running genericVFSBackupVolume):

* https://github.com/lxc/lxd/blob/master/lxd/storage/drivers/driver_btrfs_volumes.go#L1020-L1059
* https://github.com/lxc/lxd/blob/master/lxd/storage/drivers/driver_zfs_volumes.go#L1474-L1525

But similar behaviour is missing from those drivers':

* https://github.com/lxc/lxd/blob/master/lxd/storage/drivers/driver_zfs_volumes.go#L1384-L1385
* https://github.com/lxc/lxd/blob/master/lxd/storage/drivers/driver_btrfs_volumes.go#L860-L861

Finally, the `lvm` driver may also benefit from some of this temporary snapshot logic (or if not should have `RunningCopyFreeze` set to `true`) when using thin pools, as I understand snapshots are cheap when using thinpools and don't impact performance like the non-thin pool ones do (although @stgraber knows more about this than I).

**Comment by stgraber** [comment] 2021-12-16 17:15
I guess the fsfreeze would indeed take care of the error and be overall consistent with what we've done with so far, though that will likely be problematic for the reporter of this issue and others with large instances as it will completely freeze any workload running on the source, potentially for minutes which could cause an outage.

**Comment by tomponline** [comment] 2021-12-16 17:18
Yeah, I suppose we need to decide what the default mode is and implement it consistently, and assuming that is the "safe but interrupting" mode by default, then after that we can add a "non-interrupting but inconsistent mode" for people to opt-in to.

**Comment by stgraber** [comment] 2021-12-16 17:19
For the LVM and Ceph cases, snapshots are problematic as xfs and btrfs will not allow concurrent mounting of a snapshot and original volume unless their identifiers are changed. That rewrite operation, at least on btrfs is very costly.

There's also the issue that we would take a snapshot while the instance is running, so writes wouldn't be flushed and the filesystem may be dirty.

**Comment by tomponline** [comment] 2021-12-16 17:20
> 

Thanks for that info, so I suppose we need to mark LVM as RunningCopyFreeze=false too. then.

**Comment by stgraber** [comment] 2021-12-16 17:21
Maybe the easy solution here is to allow for that rsync error in refresh mode?

And so require the instance be copied, not moved.

**Comment by tomponline** [comment] 2021-12-16 17:31
> Maybe the easy solution here is to allow for that rsync error in refresh mode?

So even without the specific issue that the OP is encountering (the `file has vanished` error) the copy (whether in refresh mode or otherwise) is inconsistent if running for some storage pool drivers and not others. That alone is not ideal as it could catch unsuspecting users who don't understand the limitations of their chosen storage pool, but more confusingly its inconsistently inconsistent, because backups of those running instances on those storage pools are consistent (by way of freezing the instance).

This is made more problematic because we often encourage users who are having trouble with the time it takes to make an instance backup using `lxc export` to setup another LXD server and then do `lxc copy --refresh` as their form of backup. This means in those cases the quality of the backups are reduced.

Fixing those issues by making the copy/move behaviour consistent with the backup behaviour would remove the ability for the OPs specific error to occur, but also remove the unreported inconsistencies that will still occur even if we ignore exit code 24.

As you say, although we achieve consistency via that approach, it probably won't work for the OP if they have lots of changes during a refresh or have a long initial copy as the instance will be effectively unresponsive for the duration of that copy (as it will be today with the backup process).

Perhaps we should default to consistent but interrupted for all of these operation types, and then add an `--allow-inconsistent` flag to `lxc export`, `lxc copy` and `lxc move` that doesn't freeze the instance and ignores exit code 24?

**Comment by gaia** [comment] 2021-12-16 19:29
> I guess the fsfreeze would indeed take care of the error and be overall consistent with what we've done with so far, though that will likely be problematic for the reporter of this issue and others with large instances as it will completely freeze any workload running on the source, potentially for minutes which could cause an outage.

this would nullify the utility of the proposed solution entirely in our situation. if we could forego relying on the container performing its function we would stop it before copying.

**Comment by gaia** [comment] 2021-12-16 19:36
> Perhaps we should default to consistent but interrupted for all of these operation types, and then add an `--allow-inconsistent` flag to `lxc export`, `lxc copy` and `lxc move` that doesn't freeze the instance and ignores exit code 24 from rsync?

this language is already a good warning of what's going to happen. it would also be useful to print a warning at the end stating that the "copy cannot be ensured to be consistent".

PS: as mentioned earlier, it might be best to disallow this flag on `lxc move`. this self healing aspect of our workload is very rarely the case in other workloads.

**Comment by tomponline** [comment] 2021-12-16 19:49
I think we need to fix the default inconsistent mode first (which we accept won't solve your issue), and then introduce an explycit inconsistent allow mode. As my point is even with ignoring exit code 24 the copy is still inconsistent, we need to fix that behavior first in my view (its just your issue has caused me to dig into it and find the additional problem)

**Comment by stgraber** [comment] 2021-12-16 20:17
How about we make the `--refresh` case the inconsistent one? It already has state and is meant for incremental changes, so we could have it detect exit code 24, go through the rest of the migration and then at the end return an error along the line of `Volume was refreshed but may be inconsistent`?

So basically we would:
 - Make the default `lxc copy` and `lxc move` consistent with the rest of the code and have that cause a fsfreeze of the source when running on a less featureful storage backend (needs to be clarified in doc/storage.md).
 - For Refresh handling, don't perform fsfreeze on any rsync operation, detect the 24 return code and don't fail immediately when hit, instead ultimately fail at the end with `Volume was refreshed but may be inconsistent`.

So OP would then be able to use `lxc copy --refresh` for this use case.
It would still fail as far as the client is concerned but also not fail the entire migration or cause things to be reverted server-side.
Then to get a fully consistent path, they can always `lxc pause` or `lxc stop` the source, do another `--refresh` run and that will be fully consistent with no error.

**Comment by tomponline** [comment] 2021-12-16 20:45
I like the idea of returning an error when inconsistent can occur and leaving it to the user to decide whether to pause, stop or (if we add it) procees in a knowingly inconsistent mode.

I still don't think making the refresh flag that mode, because the refresh flag is used for incremental backups to another server, and ignoring the exit code 24 issue, there is a wider problem of inconsistencies caused by each file being transferred whilst it and other files can be written to independently. That way as it stands ATM an rsync copy with or without refresh is inconsistent if the instance is running even if no vanishing files occur.

Perhaps we should make copy, move and export just return an error if the storage pool doesn't support running copying and the instance is running, informing the user they need to pause or stop the instance. This avoids any unexpected interruption to the instance.

Then we can add an --allow-inconsistent flag which will allow it to occur even if running, without freezing the instance. And in that mode it would ignore rsync exit status 24 (as the copy is inconsistent whether or not it occurs).

**Comment by stgraber** [comment] 2021-12-16 21:19
Yeah, I guess we can do that. It's just going to be a bit frustrating to do because we'll need to tie that to migration flags and make it all work across different versions.

**Comment by tomponline** [comment] 2021-12-17 09:04
> we'll need to tie that to migration flags

I don't quite understand what you mean by that? Do you mean the migration protobuf protocol?

**Comment by stgraber** [comment] 2021-12-17 18:39
Yeah, I was thinking of where we'd need to be aware of the new flag but maybe it ends up being simpler than I thought as only the source server really needs to handle it/

So passing `--allow-inconsistent` would set the matching property on the InstancePost struct and the source server will need it plumbed into migrate_instance and all the way through storage and storage drivers. If the source server doesn't support that API extension, then using that flag will fail. The target server doesn't need to be aware of it so this may keep things simple enough.

**Comment by tomponline** [comment] 2021-12-17 18:45
Yeah I think that should work as long as in pull mode the source still runs the rsync command .

**Comment by stgraber** [comment] 2021-12-17 19:25
Yeah, it always does, the different modes just change who sets up the websocket, but once we hit the migration.Do logic, it's all the same.

**Comment by tomponline** [comment] 2021-12-17 19:39
Excellent, that should make things simpler then.

**Comment by gaia** [comment] 2021-12-17 21:24
> Yeah, it always does, the different modes just change who sets up the websocket, but once we hit the migration.Do logic, it's all the same.

Feedback: this detail should become part of the manual/explanation on push/pull/relay modes. it's never been clear until i read this. thanks Stéphane!

More feedback: I would have saved literally days of work had I known that the best performance for IO heavy workloads is offered by the `dir` driver (the disadvantages are clear though).

**Comment by stgraber** [comment] 2021-12-17 22:52
Well, that part is very very workload specific, I've usually had better performance on ZFS but that's because I need raid and compression helps a lot with my workloads, so zfs with its builtin fs replication is far faster for me than ext4 on top of a mdraid.

But it's true that for many use cases, especially for databases, CoW filesystems like btrfs and zfs can have a significant performance impact. Both do have a number of manual tweaks you can do for such workloads (some are being directly added to LXD like #7901) but a number of others like the nodatacow attribute on btrfs are better left for the user to apply on a per-file/per-directory basis.

**Comment by gaia** [comment] 2021-12-23 05:39
checking in on this issue. also, this might be too case specific, but i had an idea that would help copying/moving CTs that shouldn't be powered off (continuity) and contain DBs and/or data that is hard to copy/move with consistency unless it is powered off (ephemeral data): an `--exclude` flag to `lxc copy/move` would skip the folder supplied to the flag and every subfolder of it.

PS: just to illustrate the DB in my case at least is mostly _leveldb_

**Comment by stgraber** [comment] 2022-01-05 17:02
So looks like the plan would be:
 - Extend `InstanceSource` to add `AllowInconsistent bool`
 - Add an API extension
 - Extend client code to allow for AllowInconsistent and check for API extension
 - Plug that in the CLI with a `--allow-inconsistent` argument

**Comment by tomponline** [comment] 2022-01-13 07:05
Reopening so we don't forget to address the inconsistent behavior that happens by default today.

**Comment by stgraber** [comment] 2022-01-13 13:35
Can we get a new issue for this instead?

**Comment by markylaing** [comment] 2022-01-13 16:07
> Can we get a new issue for this instead?

I'll create one now.

**Closed** 2022-01-13 16:14 UTC
Labels: Bug, Easy

**Comment by tomponline** [comment] 2022-01-13 16:40
Thanks !
