### ISSUE TITLE
Define default profile for image

### ISSUE THREAD

**Issue by randombenj** [lxc/lxd#4567] opened 2018-05-16 13:51 UTC
When I launch a new container I can specify which profile it should take instead of the default profile with the `-p` option:

```sh
lxc launch [<remote>:]<image> -p <some profile>
```
This profile can contain some default network setup (bridge, devices, ...) and the container won't work properly if you don't launch it with the correct profile.

It would be nice if you could specify a custom default profile to take when launching a container from a specific image instead of the real default profile. This could look something like this:
```sh
lxc image edit <image>
```
With the option:
```yaml
# ...
properties:
  default_profile: <profile>
# ...
``` 
Of course it would be nice to also include this option in the [metadata.yaml file for importing an image](https://github.com/lxc/lxd/blob/master/doc/image-handling.md#content)

This topic was already mentioned in a [linux container discussion thread](https://discuss.linuxcontainers.org/t/use-a-remote-profile/544) but I wanted to know if there is anything planed like this.

**Comment by stgraber** [comment] 2018-05-18 02:41
That's come up a couple of times. It wouldn't be something that we'd store as part of the image itself as we don't want the image producer to be able to trick users into using a particular profile, but I'd be fine with it being something that the local admin can mark an image with, so that any container created from it after that would use the profiles.

**Comment by jackstenglein** [comment] 2019-10-19 15:57
@stgraber 

Hello, myself and another student from UT Austin would like to take on this issue for our virtualization class.

**Comment by stgraber** [comment] 2019-10-20 19:00
Thanks, assigned to you.

For this issue, I think we want to extend the returned image structs to include a list of profiles to apply at creation time if none were provided by the user. When not set, the "default" profile will be assumed.

From a user's point of view, this will be visible in:
 - lxc image info
 - lxc image show
 - lxc image edit

This will show as a new "profiles" field which will default to nil.

There will be three valid values for it:
 - nil (the default, will cause lxd to use the default profile)
 - [] (an empty list indicates no profile will be applied at all, not even the default one)
 - A valid list of profiles, applied in order.

One catch is projects as projects may contain images and profiles but it's not guaranteed that both feature will be used together.

As a result, I think we'll want this list of profiles to be tied to the project and will become tied to the project if it has either the images or profiles feature enabled.

As for how to split this work, I'd suggest the following commits:
 - "api: Add image_profiles extension"
   - Add the entry to shared/version/api.go
   - Add a new section to doc/api-extensions.md
 - "doc/image-handling: Add image profiles"
   - Update the documentation to cover the new feature and explain the valid values
 - "shared/api: Add image profiles"
   - Update ImagePut to add the new Profiles field as a slice of string. Add it as the last field of the struct with a suitable API extension comment.
 - "lxd/db: Add images_profiles table"
   - Add a schema extension to create that table. It should have a foreign key to the image, profile and project with cascading enabled.
   - Run `make update-schema` to generate schema.go
   - Update the image functions to fill the profile list in the struct and to allow setting the list of profiles in the database.
 - "lxd/images: Add support for image profiles"
   - Update `lxd/image.go` to properly query and update the database based on the content of the Profiles attribute. This is where you'll need to be careful about how projects are handled.
 - "tests: Add test for image profiles"
   - You'll want to add a new suite in `test/suites`, link it in `test/main.sh` and have it validate:
   - Normal creation with nothing set
   - Creation with profiles set to empty list
   - Creation with profiles set to a list of alternate profiles
   - Each time, validate the profiles applied on the container.
   - Also test with a project that only has the images feature enabled, then one with only profiles and lastly with one that has both enabled.

One last thing to keep in mind, images can get refreshed by LXD. When this happens, we'll want those profiles to be copied to the new image.

Let me know if you have any questions or run into any problem!

**Comment by randombenj** [comment] 2019-10-21 14:21
Awesome! :confetti_ball: If you need something mabe I could help with some stuff too.
Or try/test things in our environment.

**Comment by ralubis** [comment] 2019-11-25 01:22
Hi @stgraber, we tried to run `make update-schema` on a clean version of master to get a better understanding of the proper behavior for `make update-schema`. However, we are faced with the following error: 
`Error: Generate code snippet: No declaration found for "Instance"`
Do you have any insight on what we can do to get around this error? I have attached the full output below.

Thanks!

<details>
<summary> Full Output </summary>

```cd shared/generate && go build -o lxd-generate -tags "libsqlite3"  && cd -
/home/ubuntu/go/src/github.com/lxc/lxd
mv shared/generate/lxd-generate /home/ubuntu/go/bin
go generate ./...
Error: Generate code snippet: No declaration found for "Instance"
Usage:
  lxd-generate db mapper stmt [kind] [flags]

Flags:
  -d, --database string   target database (default "cluster")
  -e, --entity string     database entity to generate the statement for
  -h, --help              help for stmt
  -p, --package string    Go package where the entity struct is declared (default "api")
  -t, --target string     target source file to generate (default "-")

lxd/db/containers.go:28: running "lxd-generate": exit status 1
Makefile:120: recipe for target 'update-schema' failed
make: *** [update-schema] Error 1
```

**Comment by stgraber** [comment] 2019-11-25 15:28
Seems to be running fine here, maybe try rebasing on master just in case?

**Comment by stgraber** [comment] 2019-11-25 15:32
@ralubis feel free to open a draft pull request so we can directly look at it too, it may be a change in your branch which is causing the generator to get confused.

**Comment by ralubis** [comment] 2019-11-25 22:40
We were able to get `make update-schema` run by including ~/go/bin in $PATH.

**Comment by jackstenglein** [comment] 2019-11-25 23:15
@stgraber We are a bit confused about how to store the profile information in the database in order to differentiate between the nil and empty list case. Assuming that a query to the images_profiles table for a given image id returns no profiles, is that supposed to indicate the nil case or the [] case?

**Comment by stgraber** [comment] 2019-11-26 03:13
The distinction between `nil` and `[]` should be done at the API level.
If you get `nil`, then at the DB level, you insert the `default` profile. If you get `[]`, you insert nothing.

To handle upgrades, you will need the schema update to also insert an entry for every existing image, tying them to the `default` profile.

**Comment by ralubis** [comment] 2019-11-26 18:12
Thank you! We will keep that information in mind.

Can you elaborate further on the change made to projects in this issue? We're not really sure what you meant with: 

> As a result, I think we'll want this list of profiles to be tied to the project and will become tied to the project if it has either the images or profiles feature enabled.

Will we need to modify lxc functions related to projects, such as lxc project edit or lxc project show?

**Comment by stgraber** [comment] 2019-11-26 18:31
No, it's just a database thing. The user will only be editing the image with `lxc image edit`.

The issue is that images can be tied to a project if `features.images=true` and profiles can be tied to projects too if `features.projects=true`.

So we have to deal with the following cases:
 - Default project
 - Project with neither images nor profiles enabled (effectively same as "Default project" case)
 - Project with both images and profiles enabled
 - Project with only images enabled
 - Project with only profiles enabled

The first three are pretty straightforward to handle as they are all within the same project.

The last two are where things get tricky because you effectively end up in a situation where either the image or the profile is coming from the default project when the other is coming from a separate project.

In the case where the images feature is enabled but the profiles feature isn't, the profile names will be resolved and linked to the default project.

In the case where the images feature isn't enabled but the profiles feature is, the profile names will be resolved against the current project and linked to the image in the default project.

The main issue with this is that when we create a new project like this:
 - lxc project create blah -c features.images=false

The project end up with its own set of profiles, starting with an empty `default` profile but gets the same list of images as the `default` project. This results in none of those existing images being linked to a profile. So you'll need to make project creation/configuration add the needed database entries so that all images available on the system at the time of the creation or configuration of a project with features.images=false get a new DB entry added linking them to the default profile in that project.

**Comment by jackstenglein** [comment] 2019-11-27 02:37
Thanks for the detailed response! Just to make sure we understand correctly, I wanted to run some scenarios by you.

In the case of the default project and in the case of the project with neither images nor profiles enabled, suppose the project has id 1, the image `foo` has id 2 and the profile `bar` has id 3. Adding the `bar` profile to `foo` would create an (image_id, profile_id, project_id) tuple of (2, 3, 1) in the `images_profiles` table.

Now suppose we are using a project with both images and profiles enabled. This project has id 4, the image `fizz` has id 5 and the profile `buzz` has id 6. Adding the `buzz` profile to image `fizz` would create an (image_id, profile_id, project_id) tuple of (5, 6, 4) in the `images_profiles` table.

Next suppose we are using a project with only images enabled. This project has id 7. The default project still has id 1. The image `hello` in project 7 has id 8 and the profile `world` in the default project has id 9. Adding the `world` profile to image `hello` would create an (image_id, profile_id, project_id) tuple of (8, 9, 1) in the `images_profiles` table.

Finally, suppose the `bar` profile has been added to the `foo` image in the default project as in the first example. We run `lxc project create blah -c features.images=false` and project `blah` is given the id 10. This results in an (image_id, profile_id, project_id) tuple of (2, 3, 10) in the `images_profiles` table to support the `bar` profile in the new project.

In all of the above cases, when querying the `images_profiles` table for the list of profiles applied to an image, we would search for the matching image id and either the default project id or the current project id. We use the current project id if `features.images=true` and the default project id otherwise.

Please let me know if any of these scenarios are incorrect. Also, how do we get the current project id and check the value of `features.images` for that project? And if the user tries to add a profile that does not exist in the current project, should we print some error message? If so, what should it say? Thanks again!

**Comment by stgraber** [comment] 2019-11-27 03:24
I don't think you need a `project_id` column in `images_profiles` at all, both `image_id` and `profile_id` refer to records that are tied to a project already.

You will always load the image record first which gets you the image_id, for the profiles, you get the provided names and resolve them to their ids within the current project, if the project doesn't have profiles enabled, then that goes to the default project.

Trying to link to a profile which doesn't exist in the current project should definitely fail with an error.
`BadRequest(fmt.Errorf("Project '%s' doesn't exist"))` would do the trick.

The codepath users will hit when changing those profiles is `imagePut` which  already has logic to get the current project name. The config check and resolving to the right project_id is usually done in the database functions (lxd/db/images.go) and you'll find quite a few examples of us using `ProjectHasImages` in there.

**Comment by jackstenglein** [comment] 2019-11-27 04:05
Excellent, thanks a lot! We should have a pull request for this later this week.

**Closed** 2019-12-07 03:46 UTC
Labels: API, Documentation, Easy, Feature
