### ISSUE TITLE
Compress migration stream

### ISSUE THREAD

**Issue by danielrobbins** [lxc/lxd#5210] opened 2018-10-26 23:28 UTC
I am performing container migrations using "lxc move" and noticing that when migrating a ZFS-backed container, optimal command-line options are not passed to zfs send. This results in excessive (2-4x on-disk bytes) being sent over the network in cases where ZFS compression is used (and it is commonly used.)

The "-c" option should be specified, which will allow ZFS to send already-compressed blocks in their compressed form. Without this option, ZFS will decompress the data prior to sending it over the network, and bandwidth used during container migration can be 3x of actual on-disk bytes. I also recommend looking at using "-L" option to play nice with large blocks that are compressed.

This should result in being able to migrate a container that uses 100GB on disk without using 300GB+ of network bandwidth, possibly across a WAN, speeding up migrations over ZFS by about 2-4x.

While I think -c should be enabled as a reasonable default, it should probably also be possible to tune the default settings used with zfs send via an lxd config option.

This should be a fairly simple fix.

**Comment by danielrobbins** [comment] 2018-10-26 23:43
Note: I'm using zfs 0.7.9 and 0.8.0 release candidate. According to dnegreira on #lxcontainers, the -c zfs send option was added in zfs 0.7.0.

**Comment by stgraber** [comment] 2018-10-27 05:19
Not a simple fix when we need to keep supporting 0.6.5 too.

**Comment by danielrobbins** [comment] 2018-10-27 18:18
How about, for now, add a configuration option so that additional options can be provided to zfs send, if the user desires it?

**Comment by danielrobbins** [comment] 2018-10-27 21:34
Then I am thinking that if the distro has zfs 0.7.0+, the distro packages can ship with a config that enables -c by default. So this can be addressed at the distro level rather than lxd level. Packages will know what versions are getting installed and can be set up with optimal settings at pkg install time.

**Comment by danielrobbins** [comment] 2018-10-27 23:38
Here's another option -- simply lz4 compress/decompress the filesytem data stream going through the websocket when migrating containers. This would be a solution that would work with zfs as well as potentially other filesystems with "optimized file transfer", and it would work with all versions of zfs as well :) There is probably a go library somewhere that would make this pretty easy to add.

**Comment by stgraber** [comment] 2018-10-27 23:47
Yeah, we may be able to do that. We'd still need negotiation in place due to having to support transferring from older LXD hosts and from other API clients which we don't have control over.

**Comment by danielrobbins** [comment] 2018-10-27 23:52
I think this is probably the ideal way to approach it, so that would be great. :)

**Comment by stgraber** [comment] 2018-11-26 05:35
Yeah, confirmed that `-c -L` is really what we want here with transfer going down to below half of normal and closely matching the dataset size (about +10% overhead due to websocket + crypto).

**Closed** 2018-11-26 16:08 UTC
Labels: Feature, Maybe
