### ISSUE TITLE
pipe files inside CT breaks 'lxc delete' and 'lxc import'

### ISSUE THREAD

**Issue by kautMaks** [lxc/lxd#7516] opened 2020-06-11 16:44 UTC
* Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version:5.4.0-33-generic
   * LXC version: 4.2
   * LXD version: 4.2
   * Storage backend in use: dir

# Issue description

When you create pipe file inside CT, after that 'lxc delete' and 'lxc import' of this CT hangs.

# Steps to reproduce
![issue](https://user-images.githubusercontent.com/45597971/84415909-22bb8d80-ac1c-11ea-8428-22f0d4fe2ba3.png)

**Comment by stgraber** [comment] 2020-06-11 17:54
@tomponline want to take a look at that one?

**Comment by tomponline** [comment] 2020-06-11 17:55
Will do

**Comment by tomponline** [comment] 2020-06-12 14:18
@kautMaks I'm afraid I cannot reproduce this:

```
lxc launch images:ubuntu/focal testvm --vm
lxc shell testvm
apt install snapd
snap install lxd
lxd init (accept defaults for zfs loopback storage pool)
lxc launch images:debian/10 test
lxc exec test -- mknod /test p
lxc exec test -- ls -la /test
prw-r--r-- 1 root root 0 Jun 12 14:14 /test
lxc stop test
lxc delete test (completes within 1s)
```

```
lxc launch images:debian/10 test
lxc exec test -- mknod /test p
lxc export test /root/test.tar.gz
lxc delete test -f
lxc import /root/test.tar.gz
lxc start test
lxc exec test -- ls -la /test
prw-r--r-- 1 root root 0 Jun 12 14:16 /test
```

I've also tested on master branch in a non-snap environment and don't see this.

What storage driver are you using when you see this?

**Comment by stgraber** [comment] 2020-06-12 14:25
Report says "dir"

**Comment by kautMaks** [comment] 2020-06-12 14:26
@tomponline I use 'dir' storage.
Non-snap environment.

**Comment by tomponline** [comment] 2020-06-12 14:28
Thanks, I missed that bit. 

I've tried this on dir now, both snap and non-snap, and also can't recreate it.

**Comment by kautMaks** [comment] 2020-06-12 14:35
@tomponline Maybe it will be useful, I use ext4 on host machine with prjquota enabled.
Sorry, that I didn't point it earlier.

**Comment by tomponline** [comment] 2020-06-12 15:48
OK that re-created it, thanks for the extra info.

**Comment by tomponline** [comment] 2020-06-12 16:20
Fixed in https://github.com/lxc/lxd/pull/7527

**Comment by s3rj1k** [comment] 2020-06-12 16:26
@tomponline Yay!)

**Closed** 2020-06-12 17:19 UTC
Labels: Bug, Easy
