### ISSUE TITLE
lxc stop does not stop my container

### ISSUE THREAD

**Issue by FransM** [lxc/lxd#2947] opened 2017-02-24 14:08 UTC
lxc 2.8 on 16.04 64 bit with 4.4.0 kernel

lxc stop does not stop my container; I know it is not guaranteed to do so, but ...
If  instead of lxc stop I do an lxc exec  of the command "shutdown now" my container does stop as expected; even after a long wait.

Any idea why lxc stop is less effective than shutdown ?

Some information fetched from the container (also running 16.04):
If I abort the lxc stop and check the container with lxc exec container -- bash I see in syslog that a lot of things are stopped:

eb 24 13:42:25 D-wan-61-1 systemd[1]: Received SIGRTMIN+3.
Feb 24 13:42:25 D-wan-61-1 systemd[1]: Removed slice system-getty.slice.
Feb 24 13:42:25 D-wan-61-1 systemd[1]: Stopped target Graphical Interface.
Feb 24 13:42:25 D-wan-61-1 systemd[1]: Stopped target Cloud-init target.
Feb 24 13:42:25 D-wan-61-1 snapd[546]: 2017/02/24 13:42:25.942455 main.go:67: Exiting on terminated signal.
Feb 24 13:42:25 D-wan-61-1 /usr/lib/snapd/snapd[546]: main.go:67: Exiting on terminated signal.
Feb 24 13:42:25 D-wan-61-1 systemd[1]: Stopped Execute cloud user/final scripts.
Feb 24 13:42:25 D-wan-61-1 systemd[1]: Stopped target Multi-User System.
Feb 24 13:42:25 D-wan-61-1 systemd[1]: Stopping OpenBSD Secure Shell server...
Feb 24 13:42:25 D-wan-61-1 systemd[1]: Stopping Deferred execution scheduler...
Feb 24 13:42:25 D-wan-61-1 systemd[1]: Stopping LSB: automatic crash report generation...
Feb 24 13:42:25 D-wan-61-1 systemd[1]: Stopped target Login Prompts.
Feb 24 13:42:25 D-wan-61-1 rsyslogd: [origin software="rsyslogd" swVersion="8.16.0" x-pid="518" x-info="http://www.rsyslog.com"] exiting on signal 15.

If I run a ps aux I see the following is still running:
# ps aux
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root          1  0.2  0.1  37684  4704 ?        Ss   13:41   0:00 /sbin/init
root         44  0.0  0.0  41724  2236 ?        Ss   13:41   0:00 /lib/systemd/systemd-udevd
root         49  0.0  0.0  35276  3288 ?        Ss   13:41   0:00 /lib/systemd/systemd-journald
message+    523  0.0  0.0  42900  2476 ?        Ss   13:41   0:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
root        714  0.0  0.0  18256  2476 ?        Ss   13:42   0:00 bash
root        727  0.0  0.0  34424  1948 ?        R+   13:44   0:00 ps aux

Noe that the number of processes left running is not always the same.
E.g. at another attempt I also had this one running:
   685 ?        Ss     0:00 /sbin/lvm vgchange --monitor n --ignoreskippedcluster

at this point doing a
kill -s SIGPWR immediately stops the container

Just getting out of it and retrying lxc stop does not, although I have seen that if I retry an lxc stop 5 minutes later or so it will have success (waiting 5 minutes does not).

**Comment by brauner** [comment] 2017-02-24 14:14
Can you please append the log for the container which can be found in `/var/log/lxd`?

**Comment by stgraber** [comment] 2017-02-24 19:43
Hmm, so I'm not sure exactly what's going on here and I've not really seen any of this before.

Your log does show that LXD did its job and delivered the stop signal to system in the container. Why systemd doesn't treat that as the same as when you run "shutdown" is a bit puzzling.

At the LXD level, our guarantee is that on both "lxc stop" and "lxc restart" when "--force" isn't passed, we will deliver the applicable signal to PID 1 in the container. If PID 1 decides to ignore that or then fails to fully complete the shutdown or reboot action, there's nothing LXD can really do about it.

I'd recommend you file a bug at https://launchpad.net/ubuntu/+source/systemd/+filebug showing the syslog/journal of the container when stopped with "lxc stop" and when stopped with "shutdown", that should be enough for someone familiar with systemd to track down why this seems to end in two different code paths...

I'm closing the LXD issue as based on your logs, LXD is doing its job. But please respond to this issue with the link to the Launchpad bug so that I can subscribe our team to it to keep track of that issue.

**Closed by stgraber** 2017-02-24 19:43 UTC
Labels: Incomplete

**Comment by FransM** [comment] 2017-02-25 21:19
The log in the container directory only says this:
            lxc 20160225102512.153 WARN     lxc_start - start.c:signal_handler:322 - Invalid pid for SIGCHLD. Received pid 76356, expected pid 76357.

The lxd.log says for this container only
action=shutdown created=2017-02-25T10:25:11+0000 ephemeral=false lvl=info msg="Shutting down container" name=D-wan-61-1 t=2017-02-25T11:27:12+0100 timeout=-1s used=2017-02-25T10:25:11+0000

I suspect this is related to the content of the container, but I have not been able to pinpoint the issue.
There are other containers derived from the same container that stop properly.
Difference is this one has two network interfaces, and a dhcp server and radvd running

**Comment by stgraber** [comment] 2017-02-25 21:46
Sounds like it's just a process in the container dying while the container is being killed and getting it re-parented to the monitor process, causing it to get and ignore the SIGCHLD.

This is just a warning and probably ought to be demoted to a debug message (and therefore not even show) as it's not the sign of an actual problem.


If systemd itself was multi-threaded an option would be for one of its thread to die somehow causing this and the shutdown issue. But I don't believe it is multi-threaded and such a failure would likely cause systemd to completely crash in which case the container would end up being stopped.

You may want to enable as much systemd logging as you can, including journald persistence and then try to reproduce the issue, that should better capture what's going on. And if the problem is a systemd failure, hopefully something will indicate that in the logs (though systemd isn't exactly the best at recording failures when it crashes...).

**Comment by FransM** [comment] 2017-02-26 12:00
I''l talk to the systemd people, but wanted to share my findings here too.

I did a journalctl -a on the failing container.
The log is below. There are quite some messages related to "operation not permiited".
Not sure if that is to be expected or not (this is an unprivileged container)

The syslog of this run can be found here: http://paste.ubuntu.com/24071244/

-- Logs begin at Sun 2017-02-26 11:19:12 UTC, end at Sun 2017-02-26 11:23:05 UTC. --
Feb 26 11:19:12 D-wan-61-1 systemd-journald[48]: Runtime journal (/run/log/journal/) is 8.0M, max 196.7M, 188.7M free.
Feb 26 11:19:12 D-wan-61-1 systemd-journald[48]: Journal started
Feb 26 11:19:12 D-wan-61-1 systemd-sysctl[42]: Couldn't write '4 4 1 7' to 'kernel/printk', ignoring: Permission denied
Feb 26 11:19:12 D-wan-61-1 systemd-sysctl[42]: Couldn't write '176' to 'kernel/sysrq', ignoring: Permission denied
Feb 26 11:19:12 D-wan-61-1 systemd-sysctl[42]: Couldn't write '1' to 'fs/protected_symlinks', ignoring: Permission denied
Feb 26 11:19:12 D-wan-61-1 systemd-sysctl[42]: Couldn't write '1' to 'net/ipv4/tcp_syncookies', ignoring: No such file or directory
Feb 26 11:19:12 D-wan-61-1 systemd-sysctl[42]: Couldn't write '1' to 'kernel/kptr_restrict', ignoring: Permission denied
Feb 26 11:19:12 D-wan-61-1 systemd-sysctl[42]: Couldn't write '1' to 'fs/protected_hardlinks', ignoring: Permission denied
Feb 26 11:19:12 D-wan-61-1 systemd-sysctl[42]: Couldn't write '1' to 'kernel/yama/ptrace_scope', ignoring: Permission denied
Feb 26 11:19:12 D-wan-61-1 systemd-sysctl[42]: Couldn't write '65536' to 'vm/mmap_min_addr', ignoring: Permission denied
Feb 26 11:19:12 D-wan-61-1 systemd[1]: systemd-sysctl.service: Main process exited, code=exited, status=1/FAILURE
Feb 26 11:19:12 D-wan-61-1 systemd[1]: Failed to start Apply Kernel Variables.
Feb 26 11:19:12 D-wan-61-1 systemd[1]: systemd-sysctl.service: Unit entered failed state.
Feb 26 11:19:12 D-wan-61-1 systemd[1]: systemd-sysctl.service: Failed with result 'exit-code'.
Feb 26 11:19:12 D-wan-61-1 systemd-journald[48]: Forwarding to syslog missed 1 messages.
Feb 26 11:19:12 D-wan-61-1 systemd[1]: Started Uncomplicated firewall.
Feb 26 11:19:12 D-wan-61-1 systemd[1]: Failed to reset devices.list on /system.slice/ufw.service: Operation not permitted
Feb 26 11:19:12 D-wan-61-1 systemd[1]: Started udev Kernel Device Manager.
Feb 26 11:19:12 D-wan-61-1 mount[45]: mount: permission denied
Feb 26 11:19:12 D-wan-61-1 systemd[1]: Started Nameserver information manager.
Feb 26 11:19:12 D-wan-61-1 systemd[1]: dev-hugepages.mount: Mount process exited, code=exited status=32
Feb 26 11:19:12 D-wan-61-1 systemd[1]: Failed to mount Huge Pages File System.
Feb 26 11:19:12 D-wan-61-1 systemd[1]: dev-hugepages.mount: Unit entered failed state.
Feb 26 11:19:12 D-wan-61-1 systemd-remount-fs[44]: mount: can't find LABEL=cloudimg-rootfs
Feb 26 11:19:12 D-wan-61-1 systemd-remount-fs[44]: /bin/mount for / exited with exit status 1.
Feb 26 11:19:12 D-wan-61-1 systemd[1]: systemd-remount-fs.service: Main process exited, code=exited, status=1/FAILURE
Feb 26 11:19:12 D-wan-61-1 systemd[1]: Failed to start Remount Root and Kernel File Systems.
Feb 26 11:19:12 D-wan-61-1 systemd[1]: systemd-remount-fs.service: Unit entered failed state.
Feb 26 11:19:12 D-wan-61-1 systemd[1]: systemd-remount-fs.service: Failed with result 'exit-code'.
Feb 26 11:19:12 D-wan-61-1 systemd[1]: Failed to reset devices.list on /system.slice/systemd-random-seed.service: Operation not perm
Feb 26 11:19:12 D-wan-61-1 systemd[1]: Starting Load/Save Random Seed...
Feb 26 11:19:12 D-wan-61-1 systemd[1]: Failed to reset devices.list on /system.slice/systemd-udev-trigger.service: Operation not per
Feb 26 11:19:12 D-wan-61-1 systemd[1]: Starting udev Coldplug all Devices...
Feb 26 11:19:12 D-wan-61-1 systemd[1]: Failed to reset devices.list on /system.slice/systemd-journal-flush.service: Operation not pe
Feb 26 11:19:12 D-wan-61-1 systemd[1]: Starting Flush Journal to Persistent Storage...
Feb 26 11:19:12 D-wan-61-1 systemd[1]: Failed to reset devices.list on /system.slice/cloud-init-local.service: Operation not permitt
Feb 26 11:19:12 D-wan-61-1 systemd[1]: Starting Initial cloud-init job (pre-networking)...
Feb 26 11:19:12 D-wan-61-1 systemd[1]: Failed to reset devices.list on /system.slice/resolvconf.service: Operation not permitted
Feb 26 11:19:12 D-wan-61-1 systemd[1]: Started Flush Journal to Persistent Storage.
Feb 26 11:19:12 D-wan-61-1 systemd[1]: Started Load/Save Random Seed.
Feb 26 11:19:12 D-wan-61-1 systemd[1]: lvm2-lvmetad.socket: Trigger limit hit, refusing further activation.
Feb 26 11:19:12 D-wan-61-1 lvm[43]:   Daemon lvmetad returned error 104
Feb 26 11:19:12 D-wan-61-1 lvm[43]:   WARNING: Failed to connect to lvmetad. Falling back to internal scanning.
Feb 26 11:19:12 D-wan-61-1 systemd[1]: lvm2-lvmetad.socket: Unit entered failed state.
Feb 26 11:19:12 D-wan-61-1 systemd[1]: Started Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling.
Feb 26 11:19:12 D-wan-61-1 systemd[1]: Reached target Local File Systems (Pre).
Feb 26 11:19:12 D-wan-61-1 systemd[1]: Reached target Local File Systems.
Feb 26 11:19:12 D-wan-61-1 systemd[1]: Failed to reset devices.list on /system.slice/system-getty.slice: Operation not permitted
Feb 26 11:19:12 D-wan-61-1 systemd[1]: Created slice system-getty.slice.
Feb 26 11:19:12 D-wan-61-1 systemd[1]: Failed to reset devices.list on /system.slice/systemd-tmpfiles-setup.service: Operation not p
Feb 26 11:19:12 D-wan-61-1 systemd[1]: Starting Create Volatile Files and Directories...
Feb 26 11:19:12 D-wan-61-1 systemd[1]: Failed to reset devices.list on /system.slice/plymouth-read-write.service: Operation not perm
Feb 26 11:19:12 D-wan-61-1 systemd[1]: Starting Tell Plymouth To Write Out Runtime Data...

**Comment by FransM** [comment] 2017-02-26 12:22
The systemd bug report is here: https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1668049

I also noticed that the SIGRTMIN+3 signal is sent to systemd. Apparently this was discussed before.
see this issue: https://github.com/lxc/lxc/issues/1085

**Comment by xnox** [comment] 2017-02-27 11:37
It seems above the user expectation is for `lxc stop` to poweroff the container (`shutdown now` defaults to poweroff). poweroff signal in systemd is SIGRTMIN+4; whereas SIGRTMIN+3 is halt signal (~= `shutdown -H now`). What is the design / expectation for `lxc stop` w.r.t. to container: halt or poweroff?

**Comment by brauner** [comment] 2017-02-27 12:22
So this was originally reported to us here: https://github.com/lxc/lxc/issues/1085 and the discussion around what signal to send was supposedly settled by systemd pointing out that it expects `SIGRTMIN+3` (see https://lists.freedesktop.org/archives/systemd-devel/2016-July/037166.html) and especially:
> 3. If the container manager wants to cleanly shutdown the container, it might be a good idea to send SIGRTMIN+3 to its init process. systemd will then do a clean shutdown. Note however, that only systemd understands SIGRTMIN+3 like this, this might confuse other init systems.

(https://www.freedesktop.org/wiki/Software/systemd/ContainerInterface/)

The corresponding PR addressing this is here: https://github.com/lxc/lxc/pull/1086 . So unless systemd suddenly has a different conception of what to send to it we're doing the right thing.

**Comment by FransM** [comment] 2017-02-27 13:22
short followup based upon a question from systemd:
shutdown now and shutdown --halt now stop the container whereas just shutdown or shutdown --halt do not.
The latter  two give:
Failed to set wall message, ignoring: Refusing activation, D-Bus is shutting down.
Failed to call ScheduleShutdown in logind, proceeding with immediate shutdown: Refusing activation, D-Bus is shutting down

not sure if that is related.

**Comment by brauner** [comment] 2017-02-27 14:05
Sounds like a systemd bug.
