### ISSUE TITLE
when lxc copy is interrupted, btrfs send/receive command should be killed

### ISSUE THREAD

**Issue by gaetanquentin** [lxc/lxd#3089] opened 2017-03-19 08:30 UTC
# Required information

 * Distribution:ubuntu
 * Distribution version: 16.04 and 16.10
 * The output of "lxc info" :
 config:
  core.https_address: :8443
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - :8443
  architectures:
  - x86_64
  - i686
  certificate: |

config:
  core.https_address: :8443
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - :8443
  architectures:
  - x86_64
  - i686
  certificate: |

# Issue description

when lxc command is interrupted (cctrl+c , or network break) , between remotes, "btrfs send" on one side, "btrfs receive" on the other side are not interrupted : this blocks clean up: 
   - cannot delete the container on the destination side:
     error: remove /var/lib/lxd/storage-pools/default/snapshots/XXX/XXX/snap0: operation not permitted
  - cannot relaunch the copy on the source side:
 error: Container 'XXX' already exists

# Steps to reproduce

 1. copy a container on the remote side
 2. while copying, do a network break (in my case: openvpn)
 3. stop the copy (ctrl+c)
 4. try to make the copy again (after network come back)

# Information to attach
after interruption, btfrs commands still running:
ps auxw | grep btrfs

source:
root      1198  0.0  0.0  23952  1192 ?        Sl   09:16   0:00 btrfs send /var/lib/lxd/storage-pools/default/snapshots/XXX/snap0
root      1302  0.1  0.0  23952  1200 ?        Sl   09:17   0:00 btrfs send /var/lib/lxd/storage-pools/default/snapshots/XXX/snap0

destination:
root     59560  0.0  0.0  15844  1152 ?        S    08:42   0:00 btrfs receive -e /var/lib/lxd/storage-pools/default/snapshots/XXX/XXX316810524

**Comment by stgraber** [comment] 2017-03-19 16:24
ctrl+c doesn't actually stop the copy as the operation is executed by the target LXD. The send/receive subcommands will be killed once LXD realizes that the network connection has been broken, that can unfortunately take a very long time due to the broken way http timeouts work in Go...

The cancellation part of this problem is covered in #2294 

Until that code exists or someone comes up with a sane way to implement http timeouts in Go (timing out after x seconds of transfer inactivity), your best bet in such cases is to restart the lxd daemon with "sudo systemctl restart lxd"...

**Comment by stgraber** [comment] 2017-03-19 16:24
(Closing as duplicate of the mentioned issue)

**Closed by stgraber** 2017-03-19 16:24 UTC
