### ISSUE TITLE
disk usage of container/vms is not displayed

### ISSUE THREAD

**Issue by badsmoke** [lxc/lxd#7910] opened 2020-09-22 09:29 UTC
# Required information

 * Distribution: ubuntu 
 * Distribution version: 20.04.1
 * The output of "lxc info" or if that fails: 
```
config:
  cluster.https_address: 192.168.1.50:8443
  core.https_address: '[::]'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
- firewall_driver
- projects_limits
- container_syscall_intercept_hugetlbfs
- limits_hugepages
- container_nic_routed_gateway
- projects_restrictions
- custom_volume_snapshot_expiry
- volume_snapshot_scheduling
- trust_ca_certificates
- snapshot_disk_usage
- clustering_edit_roles
- container_nic_routed_host_address
- container_nic_ipvlan_gateway
- resources_usb_pci
- resources_cpu_threads_numa
- resources_cpu_core_die
- api_os
- container_nic_routed_host_table
- container_nic_ipvlan_host_table
- container_nic_ipvlan_mode
- resources_system
- images_push_relay
- network_dns_search
- container_nic_routed_limits
- instance_nic_bridged_vlan
- network_state_bond_bridge
- usedby_consistency
- custom_block_volumes
- clustering_failure_domains
- resources_gpu_mdev
- console_vga_type
- projects_limits_disk
- network_type_macvlan
- network_type_sriov
- container_syscall_intercept_bpf_devices
- network_type_ovn
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 192.168.1.50:8443
  - 192.168.2.50:8443
  - '[2003:a:70a:fc00:50:5bff:fe8b:f30f]:8443'
  - 10.0.3.1:8443
  - 172.20.0.1:8443
  - 172.17.0.1:8443
  - 172.19.0.1:8443
  - 172.22.0.1:8443
  - 172.18.0.1:8443
  - 172.21.0.1:8443
  - 192.168.122.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
  certificate_fingerprint: fda4b441a343ee2ea0d5d6954cd14b80935bf265d5700991cc9cd9db4014e3dc
  driver: lxc
  driver_version: 4.0.4
  firewall: xtables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.4.0-47-generic
  lxc_features:
    cgroup2: "true"
    devpts_fd: "false"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "false"
  os_name: Ubuntu
  os_version: "20.04"
  project: default
  server: lxd
  server_clustered: true
  server_name: rhea
  server_pid: 735119
  server_version: "4.6"
  storage: btrfs
  storage_version: 4.15.1
```
   * Kernel version: 5.4.0-47-generic
   * LXC version: 4.6
   * LXD version: 4.6
   * Storage backend in use: btrfs

# Issue description

No more disk usage is displayed for the containers.
In the beginning it was sporadic, now there are no more values.

Container or VM makes no difference, I have about 18 containers and 2 vms.

No more output via the api, all other values work

i do not know which logs can be helpful, it is a productive system and restart is not possible 

api output

```
curl -s --unix-socket /var/snap/lxd/common/lxd/unix.socket a/1.0/instances/openshift/state | jq
{
  "type": "sync",
  "status": "Success",
  "status_code": 200,
  "operation": "",
  "error_code": 0,
  "error": "",
  "metadata": {
    "status": "Running",
    "status_code": 103,
    "disk": null,
    "memory": {
      "usage": 3156856832,
      "usage_peak": 3572752384,
      "swap_usage": 0,
      "swap_usage_peak": 0
    },
    "network": {
      "docker0": {
        "addresses": [
          {
            "family": "inet",
            "address": "172.17.0.1",
            "netmask": "16",
            "scope": "global"
          },
          {
            "family": "inet6",
            "address": "fe80::42:b1ff:fe17:ba22",
            "netmask": "64",
            "scope": "link"
          }
        ],
        "counters": {
          "bytes_received": 22786868,
          "bytes_sent": 80884046,
          "packets_received": 119869,
          "packets_sent": 122767
        },
        "hwaddr": "02:42:b1:17:ba:22",
        "host_name": "",
        "mtu": 1500,
        "state": "up",
        "type": "broadcast"
      },
      "enp5s0": {
        "addresses": [
          {
            "family": "inet",
            "address": "192.168.2.54",
            "netmask": "24",
            "scope": "global"
          },
          {
            "family": "inet6",
            "address": "2003:a:70a:fc00:216:3eff:fe94:fea3",
            "netmask": "64",
            "scope": "global"
          },
          {
            "family": "inet6",
            "address": "fe80::216:3eff:fe94:fea3",
            "netmask": "64",
            "scope": "link"
          }
        ],
        "counters": {
          "bytes_received": 684014434,
          "bytes_sent": 27131363,
          "packets_received": 553425,
          "packets_sent": 215825
        },
        "hwaddr": "00:16:3e:94:fe:a3",
        "host_name": "tap2815bd57",
        "mtu": 1500,
        "state": "up",
        "type": "broadcast"
      },
      "lo": {
        "addresses": [
          {
            "family": "inet",
            "address": "127.0.0.1",
            "netmask": "8",
            "scope": "local"
          },
          {
            "family": "inet6",
            "address": "::1",
            "netmask": "128",
            "scope": "local"
          }
        ],
        "counters": {
          "bytes_received": 702597529,
          "bytes_sent": 702597529,
          "packets_received": 1713350,
          "packets_sent": 1713350
        },
        "hwaddr": "",
        "host_name": "",
        "mtu": 65536,
        "state": "up",
        "type": "loopback"
      },
      "veth0992f44": {
        "addresses": [
          {
            "family": "inet6",
            "address": "fe80::109a:b2ff:fe88:699b",
            "netmask": "64",
            "scope": "link"
          }
        ],
        "counters": {
          "bytes_received": 11813,
          "bytes_sent": 19007,
          "packets_received": 145,
          "packets_sent": 159
        },
        "hwaddr": "12:9a:b2:88:69:9b",
        "host_name": "",
        "mtu": 1500,
        "state": "up",
        "type": "broadcast"
      }
    },
    "pid": 1665701,
    "processes": 28,
    "cpu": {
      "usage": 3823680325792
    }
  }
}


```

**Comment by stgraber** [comment] 2020-09-22 19:53
Can you show the output for a container too?

**Comment by badsmoke** [comment] 2020-09-23 05:46
api output from a container

`"disk": {},`

```
curl -s --unix-socket /var/snap/lxd/common/lxd/unix.socket a/1.0/instances/poseidon/state | jq
{
  "type": "sync",
  "status": "Success",
  "status_code": 200,
  "operation": "",
  "error_code": 0,
  "error": "",
  "metadata": {
    "status": "Running",
    "status_code": 103,
    "disk": {},
    "memory": {
      "usage": 1984552960,
      "usage_peak": 4571275264,
      "swap_usage": 0,
      "swap_usage_peak": 0
    },
    "network": {
      "br-1e26493e189f": {
        "addresses": [
          {
            "family": "inet",
            "address": "172.18.0.1",
            "netmask": "16",
            "scope": "global"
          },
          {
            "family": "inet6",
            "address": "fe80::42:ebff:fe80:569e",
            "netmask": "64",
            "scope": "link"
          }
        ],
        "counters": {
          "bytes_received": 151354192,
          "bytes_sent": 720824320,
          "packets_received": 916181,
          "packets_sent": 1200907
        },
        "hwaddr": "02:42:eb:80:56:9e",
        "host_name": "",
        "mtu": 1500,
        "state": "up",
        "type": "broadcast"
      },
      "br-f042fe5bd31c": {
        "addresses": [
          {
            "family": "inet",
            "address": "172.19.0.1",
            "netmask": "16",
            "scope": "global"
          }
        ],
        "counters": {
          "bytes_received": 0,
          "bytes_sent": 0,
          "packets_received": 0,
          "packets_sent": 0
        },
        "hwaddr": "02:42:12:1d:6f:8b",
        "host_name": "",
        "mtu": 1500,
        "state": "up",
        "type": "broadcast"
      },
      "docker0": {
        "addresses": [
          {
            "family": "inet",
            "address": "172.17.0.1",
            "netmask": "16",
            "scope": "global"
          }
        ],
        "counters": {
          "bytes_received": 0,
          "bytes_sent": 0,
          "packets_received": 0,
          "packets_sent": 0
        },
        "hwaddr": "02:42:b9:b5:f5:db",
        "host_name": "",
        "mtu": 1500,
        "state": "up",
        "type": "broadcast"
      },
      "eth0": {
        "addresses": [
          {
            "family": "inet",
            "address": "192.168.2.15",
            "netmask": "24",
            "scope": "global"
          },
          {
            "family": "inet6",
            "address": "2003:a:70a:fc00:216:3eff:feae:ce2f",
            "netmask": "64",
            "scope": "global"
          },
          {
            "family": "inet6",
            "address": "fe80::216:3eff:feae:ce2f",
            "netmask": "64",
            "scope": "link"
          }
        ],
        "counters": {
          "bytes_received": 1662160862,
          "bytes_sent": 192916049,
          "packets_received": 10004832,
          "packets_sent": 1735413
        },
        "hwaddr": "00:16:3e:ae:ce:2f",
        "host_name": "veth445b60c3",
        "mtu": 1500,
        "state": "up",
        "type": "broadcast"
      },
      "lo": {
        "addresses": [
          {
            "family": "inet",
            "address": "127.0.0.1",
            "netmask": "8",
            "scope": "local"
          },
          {
            "family": "inet6",
            "address": "::1",
            "netmask": "128",
            "scope": "local"
          }
        ],
        "counters": {
          "bytes_received": 2054328,
          "bytes_sent": 2054328,
          "packets_received": 25255,
          "packets_sent": 25255
        },
        "hwaddr": "",
        "host_name": "",
        "mtu": 65536,
        "state": "up",
        "type": "loopback"
      },
      "veth40da802": {
        "addresses": [
          {
            "family": "inet6",
            "address": "fe80::1042:a5ff:fe64:e636",
            "netmask": "64",
            "scope": "link"
          }
        ],
        "counters": {
          "bytes_received": 82071983,
          "bytes_sent": 676806474,
          "packets_received": 688949,
          "packets_sent": 1018339
        },
        "hwaddr": "12:42:a5:64:e6:36",
        "host_name": "br-71d04647ed09",
        "mtu": 1500,
        "state": "up",
        "type": "broadcast"
      },
      "veth49297fa": {
        "addresses": [
          {
            "family": "inet6",
            "address": "fe80::28ee:89ff:fe83:8a77",
            "netmask": "64",
            "scope": "link"
          }
        ],
        "counters": {
          "bytes_received": 8744015,
          "bytes_sent": 4434230,
          "packets_received": 68972,
          "packets_sent": 64255
        },
        "hwaddr": "2a:ee:89:83:8a:77",
        "host_name": "br2",
        "mtu": 1500,
        "state": "up",
        "type": "broadcast"
      },
      "veth70e1e01": {
        "addresses": [
          {
            "family": "inet6",
            "address": "fe80::b022:f8ff:fe26:859",
            "netmask": "64",
            "scope": "link"
          }
        ],
        "counters": {
          "bytes_received": 34749083,
          "bytes_sent": 32158842,
          "packets_received": 167472,
          "packets_sent": 144767
        },
        "hwaddr": "b2:22:f8:26:08:59",
        "host_name": "br-a3fffa3aee74",
        "mtu": 1500,
        "state": "up",
        "type": "broadcast"
      },
      "vethbb66095": {
        "addresses": [
          {
            "family": "inet6",
            "address": "fe80::b81d:1fff:fe9c:35e4",
            "netmask": "64",
            "scope": "link"
          }
        ],
        "counters": {
          "bytes_received": 14693169,
          "bytes_sent": 4532059,
          "packets_received": 12664,
          "packets_sent": 12236
        },
        "hwaddr": "ba:1d:1f:9c:35:e4",
        "host_name": "veth81af716",
        "mtu": 1500,
        "state": "up",
        "type": "broadcast"
      },
      "vethefac011": {
        "addresses": [
          {
            "family": "inet6",
            "address": "fe80::ccf2:19ff:febb:c8f",
            "netmask": "64",
            "scope": "link"
          }
        ],
        "counters": {
          "bytes_received": 1684198,
          "bytes_sent": 318688,
          "packets_received": 278,
          "packets_sent": 6347
        },
        "hwaddr": "ce:f2:19:bb:0c:8f",
        "host_name": "br-0925aa6cd110",
        "mtu": 1500,
        "state": "up",
        "type": "broadcast"
      },
      "vethffe98a8": {
        "addresses": [
          {
            "family": "inet6",
            "address": "fe80::c841:84ff:fe12:5a9",
            "netmask": "64",
            "scope": "link"
          }
        ],
        "counters": {
          "bytes_received": 65412284,
          "bytes_sent": 64477418,
          "packets_received": 128238,
          "packets_sent": 137489
        },
        "hwaddr": "ca:41:84:12:05:a9",
        "host_name": "",
        "mtu": 1500,
        "state": "up",
        "type": "broadcast"
      }
    },
    "pid": 11249,
    "processes": 419,
    "cpu": {
      "usage": 10882570241886
    }
  }
}


```

**Comment by stgraber** [comment] 2020-09-24 03:00
Thanks.

Can you query the container again but this time in a separate console run `lxc monitor --type=logging --pretty` and paste that output here?

I'm hoping that you're hitting a failure from the storage driver and that this will be recorded in that debug log.

**Comment by badsmoke** [comment] 2020-09-24 06:57
does not look very promising

```
lxc monitor --type=logging --pretty
DBUG[09-24|06:56:17] New event listener: 5726e791-26fb-4cc9-81d7-d1056c304eae 
DBUG[09-24|06:56:18] Handling                                 ip=@ method=GET url=/1.0/instances/poseidon/state user=
DBUG[09-24|06:56:18] GetInstanceUsage started                 project=default driver=btrfs instance=poseidon pool=LXDpro
DBUG[09-24|06:56:18] GetInstanceUsage finished                instance=poseidon pool=LXDpro project=default driver=btrfs
```

**Comment by stgraber** [comment] 2020-09-24 14:27
Ok, so it did hit the right function but then didn't return anything. I'll take a look.

**Comment by stgraber** [comment] 2020-09-24 14:34
@badsmoke do you have a disk limit in place on those instances?
If not, you won't get a btrfs quota group setup which would then prevent reporting the disk usage.

**Comment by badsmoke** [comment] 2020-09-24 14:52
yes I have set a disk limit

**Comment by stgraber** [comment] 2020-09-24 18:57
I've been unable to reproduce the issue here:

```
stgraber@castiana:~$ lxc storage create btrfs btrfs
Storage pool btrfs created
stgraber@castiana:~$ lxc launch images:ubuntu/20.04 f1 --storage btrfs
Creating f1
Starting f1                               
stgraber@castiana:~$ lxc query /1.0/instances/f1/state | jq .disk
{}
stgraber@castiana:~$ lxc stop f1
stgraber@castiana:~$ lxc config device set f1 root size 5GiB
stgraber@castiana:~$ lxc start f1
stgraber@castiana:~$ lxc query /1.0/instances/f1/state | jq .disk
{
  "root": {
    "usage": 12763136
  }
}
```

**Comment by badsmoke** [comment] 2020-09-25 06:02
yes that's the problem, from the beginning it worked for me without problems, then it didn't work for hours/days, then it worked again and now it doesn't work at all

**Comment by stgraber** [comment] 2020-09-25 20:54
Can you do `nsenter --mount=/run/snapd/ns/lxd.mnt` and then in that new shell, do:
 - /snap/lxd/current/bin/btrfs qgroup show -e -f --raw /var/snap/lxd/common/lxd/storage-pools/LXDpro/containers/poseidon/
 - /snap/lxd/current/bin/btrfs qgroup show --raw /var/snap/lxd/common/lxd/storage-pools/LXDpro/

**Comment by badsmoke** [comment] 2020-09-28 12:56
```
root@server:/# nsenter --mount=/run/snapd/ns/lxd.mnt
root@server:/# /snap/lxd/current/bin/btrfs qgroup show -e -f --raw /var/snap/lxd/common/lxd/storage-pools/LXDpro/containers/poseidon/
ERROR: can't list qgroups: quotas not enabled
root@server:/# /snap/lxd/current/bin/btrfs qgroup show --raw /var/snap/lxd/common/lxd/storage-pools/LXDpro/
ERROR: can't list qgroups: quotas not enabled
root@server:/#

```

**Comment by stgraber** [comment] 2020-09-28 13:49
Ok, that would be a problem, so quotas just aren't enabled at all...

Can you show `lxc storage show LXDpro`?

**Comment by badsmoke** [comment] 2020-09-28 14:50
```
root@rhea:/# lxc storage show LXDpro
config: {}
description: ""
name: LXDpro
driver: btrfs
used_by:
....
- /1.0/instances/charon
- /1.0/instances/darkwingduck
- /1.0/instances/poseidon
....
status: Created
locations:
- rhea
```

**Comment by stgraber** [comment] 2020-09-28 20:35
`lxc storage show LXDpro --target rhea`

I'm trying to figure out if storage is coming from a sub-path of a host-managed path or if it was provided a dedicated block device or loop file.

We only enable quotas on the device if we created the filesystem. If LXD uses a pre-existing filesystem, it will not mess with that feature, which may be what you're seeing.

**Comment by badsmoke** [comment] 2020-09-29 05:06
it should be an extra block device in this case even an extra ssd

```
root@rhea:/# lxc storage show LXDpro --target rhea
config:
  size: 94GB
  source: /dev/sdb
  volatile.initial_source: /dev/sdb
description: ""
name: LXDpro
driver: btrfs
used_by:
...
- /1.0/instances/charon
- /1.0/instances/darkwingduck
- /1.0/instances/poseidon
....
status: Created
locations:
- rhea

```

I have the drive additionally under "/mnt/LXD" mounted, could this cause problems?

**Comment by stgraber** [comment] 2020-09-30 03:17
This is weird, reading our logic, the first time you set a limit on a volume or instance it should hit code which will try to list the qgroups, if that fails, it will then try to turn on quotas and re-try the qgroup operation.

Can you try:
 - lxc monitor --type=logging --pretty

While this the monitor is running in a shell, in another run:
 - lxc init images:alpine/edge a1 --storage LXDpro --target rhea
 - lxc config device set a1 root size 50GiB
 - lxc start a1
 - lxc query /1.0/instances/a1/state

**Comment by badsmoke** [comment] 2020-10-01 06:06
have shortened the edition a little

```

INFO[10-01|05:54:12] Image downloaded                         alias=alpine/edge image=23cde75b994743cc904f72692f6a550d9f14559698bae2af36557d939e0e4d39 operation=5f9a4f75-1346-4f69-8b2f-63b294e8421e server=https://images.linuxcontainers.org trigger=/1.0/operations/5f9a4f75-1346-4f69-8b2f-63b294e8421e
INFO[10-01|05:54:12] Creating container                       name=a1 project=default ephemeral=false
INFO[10-01|05:54:12] Created container                        ephemeral=false name=a1 project=default
DBUG[10-01|05:54:12] CreateInstanceFromImage started          driver=btrfs instance=a1 pool=LXDpro project=default
DBUG[10-01|05:54:12] EnsureImage started                      driver=btrfs fingerprint=23cde75b994743cc904f72692f6a550d9f14559698bae2af36557d939e0e4d39 pool=LXDpro
DBUG[10-01|05:54:12] Database error: &errors.errorString{s:"No such object"} 
DBUG[10-01|05:54:13] Running filler function                  dev= driver=btrfs path=/var/snap/lxd/common/lxd/storage-pools/LXDpro/images/23cde75b994743cc904f72692f6a550d9f14559698bae2af36557d939e0e4d39 pool=LXDpro
DBUG[10-01|05:54:13] Updated metadata for task Operation: 5f9a4f75-1346-4f69-8b2f-63b294e8421e 
DBUG[10-01|05:54:13] Database error: &errors.errorString{s:"No such object"} 
DBUG[10-01|05:54:13] EnsureImage finished                     driver=btrfs fingerprint=23cde75b994743cc904f72692f6a550d9f14559698bae2af36557d939e0e4d39 pool=LXDpro
DBUG[10-01|05:54:13] CreateInstanceFromImage finished         project=default driver=btrfs instance=a1 pool=LXDpro
DBUG[10-01|05:54:13] UpdateInstanceBackupFile started         driver=btrfs instance=a1 pool=LXDpro project=default
DBUG[10-01|05:54:13] UpdateInstanceBackupFile finished        driver=btrfs instance=a1 pool=LXDpro project=default
DBUG[10-01|05:54:13] Success for task operation: 5f9a4f75-1346-4f69-8b2f-63b294e8421e 
DBUG[10-01|05:54:13] Handling                                 ip=@ method=GET url="/1.0/instances/a1?target=rhea" user=
DBUG[10-01|05:54:13] Event listener finished: 39205a94-c747-4816-ae40-cb0ad498d8bc 
DBUG[10-01|05:54:13] Disconnected event listener: 39205a94-c747-4816-ae40-cb0ad498d8bc 
.
.
.
DBUG[10-01|05:54:19] Handling                                 ip=@ method=GET url=/1.0/containers/a1/state user=
DBUG[10-01|05:54:19] GetInstanceUsage started                 driver=btrfs instance=a1 pool=LXDpro project=default
DBUG[10-01|05:54:19] GetInstanceUsage finished                pool=LXDpro project=default driver=btrfs instance=a1
DBUG[10-01|05:54:20] Handling                                 ip=@ method=GET url=/1.0 user=
DBUG[10-01|05:54:20] Handling                                 ip=@ method=GET url=/1.0/instances/a1 user=
DBUG[10-01|05:54:20] Handling                                 ip=@ method=GET url=/1.0/events user=
DBUG[10-01|05:54:20] New event listener: 05b73c16-e12b-4302-a3a8-719810e64242 
DBUG[10-01|05:54:20] Handling                                 method=PUT url=/1.0/instances/a1 user= ip=@
DBUG[10-01|05:54:20] New task Operation: f40ce6b9-2b13-45a2-a642-02f8e69a1481 
DBUG[10-01|05:54:20] Started task operation: f40ce6b9-2b13-45a2-a642-02f8e69a1481 
DBUG[10-01|05:54:20] Handling                                 ip=@ method=GET url=/1.0/operations/f40ce6b9-2b13-45a2-a642-02f8e69a1481 user=
DBUG[10-01|05:54:20] SetInstanceQuota started                 driver=btrfs instance=a1 pool=LXDpro project=default
DBUG[10-01|05:54:20] SetInstanceQuota finished                driver=btrfs instance=a1 pool=LXDpro project=default
DBUG[10-01|05:54:20] UpdateInstanceBackupFile started         instance=a1 pool=LXDpro project=default driver=btrfs
DBUG[10-01|05:54:20] UpdateInstanceBackupFile finished        driver=btrfs instance=a1 pool=LXDpro project=default
DBUG[10-01|05:54:20] Success for task operation: f40ce6b9-2b13-45a2-a642-02f8e69a1481 
DBUG[10-01|05:54:20] Event listener finished: 05b73c16-e12b-4302-a3a8-719810e64242 
DBUG[10-01|05:54:20] Disconnected event listener: 05b73c16-e12b-4302-a3a8-719810e64242
.
DBUG[10-01|05:54:35] MountInstance finished                   driver=btrfs instance=a1 pool=LXDpro project=default
INFO[10-01|05:54:35] Starting container                       used="1970-01-01 00:00:00 +0000 UTC" action=start created="2020-10-01 05:54:12.916852839 +0000 UTC" ephemeral=false name=a1 project=default stateful=false

INFO[10-01|05:54:35] Started container                        action=start created="2020-10-01 05:54:12.916852839 +0000 UTC" ephemeral=false name=a1 project=default stateful=false used="1970-01-01 00:00:00 +0000 UTC"
DBUG[10-01|05:54:35] Success for task operation: b17c793c-f8c2-4677-8a17-5b5fd2e63498 
DBUG[10-01|05:54:35] Event listener finished: d5b5091d-0041-4d28-af8b-e5c850fc33b5 
DBUG[10-01|05:54:35] Disconnected event listener: d5b5091d-0041-4d28-af8b-e5c850fc33b5
.
EROR[10-01|05:54:35] balance: Unable to set cpuset            err="Failed to set cgroup cpuset.cpus=\"14,2\": setting cgroup item for the container failed" name=bitrix value=14,2
EROR[10-01|05:54:35] balance: Unable to set cpuset            err="Failed to set cgroup cpuset.cpus=\"13,9\": setting cgroup item for the container failed" name=charon value=13,9
EROR[10-01|05:54:35] balance: Unable to set cpuset            err="Failed to set cgroup cpuset.cpus=\"0,10,12,15,17,18,19,28,3,30,4,8\": setting cgroup item for the container failed" name=hydra value=0,10,12,15,17,18,19,28,3,30,4,8
EROR[10-01|05:54:35] balance: Unable to set cpuset            err="Failed to set cgroup cpuset.cpus=\"13,16,21,22,6,9\": setting cgroup item for the container failed" name=demeter value=13,16,21,22,6,9
EROR[10-01|05:54:35] balance: Unable to set cpuset            err="Failed to set cgroup cpuset.cpus=\"0,10,11,13,15,2,20,22,23,27,28,8\": setting cgroup item for the container failed" name=poseidon value=0,10,11,13,15,2,20,22,23,27,28,8
EROR[10-01|05:54:35] balance: Unable to set cpuset            err="Failed to set cgroup cpuset.cpus=\"19,7\": setting cgroup item for the container failed" name=pamela-anderson value=19,7
EROR[10-01|05:54:35] balance: Unable to set cpuset            name=dreisenpimmel value=25,5 err="Failed to set cgroup cpuset.cpus=\"25,5\": setting cgroup item for the container failed"
EROR[10-01|05:54:35] balance: Unable to set cpuset            value=14,29 err="Failed to set cgroup cpuset.cpus=\"14,29\": setting cgroup item for the container failed" name=tartaros
EROR[10-01|05:54:35] balance: Unable to set cpuset            err="Failed to set cgroup cpuset.cpus=\"11,20,27\": setting cgroup item for the container failed" name=gateway-docker value=11,20,27
EROR[10-01|05:54:35] balance: Unable to set cpuset            err="Failed to set cgroup cpuset.cpus=\"1,12,18,24,26,3,30,4\": setting cgroup item for the container failed" name=hermes value=1,12,18,24,26,3,30,4
EROR[10-01|05:54:35] balance: Unable to set cpuset            name=gitcrawler value=19,7 err="Failed to set cgroup cpuset.cpus=\"19,7\": setting cgroup item for the container failed"
EROR[10-01|05:54:35] balance: Unable to set cpuset            name=hades value=1,16,21,22,23,24,25,26,29,31,5,6 err="Failed to set cgroup cpuset.cpus=\"1,16,21,22,23,24,25,26,29,31,5,6\": setting cgroup item for the container failed"

```
```
root@rhea:~# lxc init images:alpine/edge a1 --storage LXDpro --target rhea
Creating a1
root@rhea:~# lxc config device set a1 root size 50GiB
root@rhea:~# lxc start a1
root@rhea:~# lxc query /1.0/instances/a1/state
{
	"cpu": {
		"usage": 654316945
	},
	"disk": {
		"root": {
			"usage": 0
		}
	},
	"memory": {
		"swap_usage": 0,
		"swap_usage_peak": 0,
		"usage": 12201984,
		"usage_peak": 12984320
	},
	"network": {
		"eth0": {
			"addresses": [
				{
					"address": "2a02:8106:22b:6d00:216:3eff:fe2a:6db5",
					"family": "inet6",
					"netmask": "64",
					"scope": "global"
				},
				{
					"address": "fe80::216:3eff:fe2a:6db5",
					"family": "inet6",
					"netmask": "64",
					"scope": "link"
				}
			],
			"counters": {
				"bytes_received": 3012,
				"bytes_sent": 944,
				"packets_received": 34,
				"packets_sent": 8
			},
			"host_name": "veth6a4eaa31",
			"hwaddr": "00:16:3e:2a:6d:b5",
			"mtu": 1500,
			"state": "up",
			"type": "broadcast"
		},
		"lo": {
			"addresses": [
				{
					"address": "127.0.0.1",
					"family": "inet",
					"netmask": "8",
					"scope": "local"
				},
				{
					"address": "::1",
					"family": "inet6",
					"netmask": "128",
					"scope": "local"
				}
			],
			"counters": {
				"bytes_received": 0,
				"bytes_sent": 0,
				"packets_received": 0,
				"packets_sent": 0
			},
			"host_name": "",
			"hwaddr": "",
			"mtu": 65536,
			"state": "up",
			"type": "loopback"
		}
	},
	"pid": 48661,
	"processes": 9,
	"status": "Running",
	"status_code": 103
}

```
i don't know if this is the case since yesterday's reboot or only now after creating the new image, it will now be 0 byte for almost every container/vm

**Comment by badsmoke** [comment] 2020-10-02 05:15
ok before i executed the command i checked again now it is again""disk": {},"

then i created a new container and checked after every command how the disk usage is.

as soon as i execute "lxc config device set a1 root size 50GiB" almost all containers/vms have disk usage 0 byte again

in this state:
```
root@rhea:/# nsenter --mount=/run/snapd/ns/lxd.mnt
root@rhea:/# /snap/lxd/current/bin/btrfs qgroup show -e -f --raw /var/snap/lxd/common/lxd/storage-pools/LXDpro/containers/poseidon/
WARNING: rescan is running, qgroup data may be incorrect
qgroupid         rfer         excl     max_excl 
--------         ----         ----     -------- 
0/2091        4108288            0         none 
root@rhea:/# /snap/lxd/current/bin/btrfs qgroup show --raw /var/snap/lxd/common/lxd/storage-pools/LXDpro/
extrem long list
.
.
.
0/91760             0            0 
0/91761             0            0 
0/91762             0            0 
0/91763             0            0 
0/91765             0            0 
0/91766             0            0 
0/91767             0            0 
0/91768             0            0 
0/91769             0            0 
0/91770             0            0 
0/91771             0            0 
0/91774             0            0 
0/91775             0            0 
0/91776             0            0 
0/91777             0            0 
0/91778             0            0 
0/91801             0            0 
0/91803             0            0 
0/91804             0            0 
0/91805             0            0 
0/91806             0            0 
0/91807             0            0 
0/91808             0            0 
0/91809             0            0 
0/91812             0            0 
0/91827             0            0
```

**Comment by stgraber** [comment] 2020-10-02 14:28
The behavior you're reporting would be consistent with something running `btrfs quota disable`, effectively dropping all quotas you have in place and getting the filesystem to report `ERROR: can't list qgroups: quotas not enabled`.

LXD has no such code (I just looked through the code for `disabled` to make sure), so I'm wondering if it's not something outside of LXD messing with your btrfs filesystem...

Any chance you could run a script to try to list things every minute or so to identify exactly when this regresses?
Then maybe try to align that with your syslog to see if something was happening at the time.

**Comment by stgraber** [comment] 2020-10-22 22:36
@badsmoke any update on this?

**Comment by badsmoke** [comment] 2020-10-23 11:07
I'm in the process of setting up an equivalent server, so I'll check the next weeks if it works the same way (the old server worked the first time too).

I will then contact you again

**Comment by stgraber** [comment] 2020-10-28 19:36
Ok, closing this as there's nothing we can action at this stage. Feel free to commit in there and we'll re-open as needed.

**Closed by stgraber** 2020-10-28 19:36 UTC
Labels: Incomplete
