### ISSUE TITLE
changing raw.idmap causes container launch to fail

### ISSUE THREAD

**Issue by dfberger** [lxc/lxd#3933] opened 2017-10-12 01:06 UTC
* Distribution: ubuntu
 * Distribution version: 16.04.3
 * The output of "lxc info": $ lxc info
config: {}
api_extensions:
- id_map
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFXjCCA0agAwIBAgIQO5/9MaL381FJtmIwpcz8nTANBgkqhkiG9w0BAQsFADA4
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRgwFgYDVQQDDA9yb290QHVu
    ZGVyY3JvZnQwHhcNMTcxMDA5MjIyMDA0WhcNMjcxMDA3MjIyMDA0WjA4MRwwGgYD
    VQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRgwFgYDVQQDDA9yb290QHVuZGVyY3Jv
    ZnQwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC9F626+hvhB7SL2mCu
    ZJJwZvudekCYrjIeSNN1AWSd7oGbprXk4ylStYrBMqGyrFtZnIBOxU9mA6zbUsqv
    Lve5+bSDRrnbsqV4CMG+xP5QRuJncJXQpgGcjCzjZLHw+B5i9vL0LMhHpFwWuhGM
    lu9Y5gMWUbDoF6JXrfNlY+9np8M3e9MdSBK/mmTmc1gETynzd/QNJmxuvv4M4IXo
    ZmP701C18ZV5sBl6maQFYepVi5HXL777b6BnaHdWqTzBa/4uUCS+qu4UDH9E1i1G
    fr6w2Dqx00IRSszRuF31yFgb/Zvrz/AVswW3CfHVvWA5j1FCXgSFo9JrFHRkwdb1
    EtFHpbNTwPsdVgannWVaoaTiQoqKEKx0yBtzh9W8pAKAoOXUHivrgnIyOPFMjaFE
    iHIqFFOMAwSrNw0mSqtbccPR3XG8sW5NLpASplJFrIrmvjjra8b6zaoOsd9sjxvH
    FjCz9gfMXszvAZu44nzI22vyDJKGm0YtnHTHOknnE/QTbs2qbCKkWMIdETQ9BbgM
    Og3s987kPD7QoGi86anS1bXM1BBEtQfTXTZP9G/h4ry5xbETJRnzAmK2nbihjnn4
    WA2u7tZnjckEL9u7Wi22qSxLFZIMraDUNR+hphdhvKvWu3embFSE2hb8lrYTzHGk
    3V7aFGOSc+/NmKE2qUaFlK/wMQIDAQABo2QwYjAOBgNVHQ8BAf8EBAMCBaAwEwYD
    VR0lBAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADAtBgNVHREEJjAkggp1bmRl
    cmNyb2Z0hwTAqAC0hxD9rXpCTQYAAHbUNf/+ZDCjMA0GCSqGSIb3DQEBCwUAA4IC
    AQA/oBo6dQ3y2TD5iBm3Mp7HHZTsA4VmFudxup5M8Mt1sSJHmf3cqjlJlTxcXsAM
    OaTAHpPJWfH5XG0jvS/4i+dDOwOsvWLGe1sELW917zVy2lhK0XXhM70fl6GMLo5x
    EpaL5pZLddn1Q74/+TGrE12cmj3qZS7c+gi37XXhLU9ZkliBP2/p+Xrk6IEU1j4c
    96nRD7owbVkHhXjhkBTKfWWtX+1PGCLhC/ilAY2tKTApn/O9OiDDY8PwuD354SXe
    Zh6T8R3bFKHSgwNR/EpX03+NnHdhbXnXVe0TGbbzeJia6Q+SoZfBhD3kUvJQiDo6
    cQT4DfTr3udLZ/sW05gUznU3U4VYCgPBqR2jzvEWQc9dSOBfW9p9TpsLTluV+EpF
    71EHEtmFncRWLlp9nYekU/TX7OAEW+ojEm1PjMyhkAmuOWKibjV5spdKqqs5m1un
    v4ieULQ/BixtJlF6DBnP2ZCDtxLLokUDw+LNZJsv3q1IzvPLu5/4KF1AJUDlfvZm
    U4LZFOebrcR9EjWtA5V+/y/j2LejKteVbUrMpF9s8pXJh9bb5mmH9Tl2Q8pCdUbn
    GB4CxTE4B3+x+P5KnXKeecHtF9N/KLku5+Jtz5zgz0AMcadklS5Z4pcJbRQg876M
    AoVz3Rmwl6p3mCaPQCrAl2P3b5pAFINejy3iZn/B//xbgQ==
    -----END CERTIFICATE-----
  certificate_fingerprint: 6672400d2a1d1e76a2e6e4b4c407b205471f3d39ba938c28a49e639801944303
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-97-generic
  server: lxd
  server_pid: 21720
  server_version: 2.0.10
  storage: btrfs
  storage_version: "4.4"

# Issue description

I have a working container, with a uid/gid map.  I added a subgid to the /etc files, restarted lxd, modified the containers map to include the new gid, and the container fails to start with 
  lxc 20171012005152.955 ERROR lxc_conf - conf.c:userns_exec_1:4608 - Error setting up child mappings

removing the new entry in the containers idmap allows the container to start

# Steps to reproduce

 1. usermod --add-subgid 999-999 lxd ; usermod --add-subgid 999-999 root
 2. systemctl restart lxd
 3. echo -en "both 1000100 1000100\nboth 1000101 1000101\gid 999 999" | lxc config set <c> raw.idmap -
 4. lxc start <c>

# Information to attach
* contents of /etc/sub?id

$ cat /etc/subuid
root:100000:65536
lxd:100000:65536
administrator:165536:65536
lxd:1000003:197
root:1000003:197

$ cat /etc/subgid
root:100000:65536
lxd:100000:65536
administrator:165536:65536
root:1000003:197
lxd:1000003:197
root:999:1
lxd:999:1

container config, prior to modification:
[config-pre.txt](https://github.com/lxc/lxd/files/1377651/config-pre.txt)

container config, post modification (fails to start)
[config-post.txt](https://github.com/lxc/lxd/files/1377650/config-post.txt)

monitor during start attempt 
[lxc-monitor.txt](https://github.com/lxc/lxd/files/1377647/lxc-monitor.txt)

lxd.log
[lxd.log](https://github.com/lxc/lxd/files/1377652/lxd.log)

(note that despite the lxd log not showing the additional mappings, they are working in the container.)

I tried the same steps with a "normal" (>1000) gid, with the same results.

**Comment by stgraber** [comment] 2017-10-12 04:15
I suspect you're hitting the kernel limit of a total of 5 mappings.

What do you have in /var/log/lxd/NAME/lxc.conf?

**Comment by dfberger** [comment] 2017-10-12 15:54
$ cat /var/log/lxd/mail/lxc.conf
lxc.cap.drop = sys_time sys_module sys_rawio
lxc.mount.auto = proc:rw sys:rw
lxc.autodev = 1
lxc.pts = 1024
lxc.mount.entry = /dev/fuse dev/fuse none bind,create=file,optional
lxc.mount.entry = /dev/net/tun dev/net/tun none bind,create=file,optional
lxc.mount.entry = /proc/sys/fs/binfmt_misc proc/sys/fs/binfmt_misc none rbind,create=dir,optional
lxc.mount.entry = /sys/firmware/efi/efivars sys/firmware/efi/efivars none rbind,create=dir,optional
lxc.mount.entry = /sys/fs/fuse/connections sys/fs/fuse/connections none rbind,create=dir,optional
lxc.mount.entry = /sys/fs/pstore sys/fs/pstore none rbind,create=dir,optional
lxc.mount.entry = /sys/kernel/debug sys/kernel/debug none rbind,create=dir,optional
lxc.mount.entry = /sys/kernel/security sys/kernel/security none rbind,create=dir,optional
lxc.mount.entry = /dev/mqueue dev/mqueue none rbind,create=dir,optional
lxc.include = /usr/share/lxc/config/common.conf.d/
lxc.logfile = /var/log/lxd/mail/lxc.log
lxc.loglevel = warn
lxc.arch = linux64
lxc.hook.pre-start = /usr/bin/lxd callhook /var/lib/lxd 4 start
lxc.hook.post-stop = /usr/bin/lxd callhook /var/lib/lxd 4 stop
lxc.tty = 0
lxc.utsname = mail
lxc.mount.entry = /var/lib/lxd/devlxd dev/lxd none bind,create=dir 0 0
lxc.aa_profile = lxd-mail_</var/lib/lxd>//&:lxd-mail_<var-lib-lxd>:
lxc.seccomp = /var/lib/lxd/security/seccomp/mail
lxc.id_map = u 0 100000 65536
lxc.id_map = g 0 100000 65536
lxc.id_map = u 1000100 1000100 1
lxc.id_map = g 1000100 1000100 1
lxc.id_map = u 1000101 1000101 1
lxc.id_map = g 1000101 1000101 1
lxc.network.type = veth
lxc.network.flags = up
lxc.network.link = br0
lxc.network.hwaddr = 00:16:3e:a2:da:5a
lxc.network.name = eth0
lxc.rootfs.backend = dir
lxc.rootfs = /var/lib/lxd/containers/mail/rootfs
lxc.mount.entry = /var/lib/lxd/devices/mail/disk.silo-maildir silo/maildir none bind,create=dir
lxc.mount.entry = /var/lib/lxd/shmounts/mail dev/.lxd-mounts none bind,create=dir 0 0

**Comment by stgraber** [comment] 2017-10-12 16:03
Hmm, that doesn't line up with the raw.lxc you mentioned above.

**Comment by dfberger** [comment] 2017-10-12 16:21
Sorry, that was in the running (working) state.  If I restore the idmap to the state that breaks the container, that section looks like this:

lxc.id_map = u 0 100000 65536
lxc.id_map = g 0 100000 999
lxc.id_map = g 999 999 1
lxc.id_map = g 1000 101000 64536
lxc.id_map = u 1000100 1000100 1
lxc.id_map = g 1000100 1000100 1
lxc.id_map = u 1000101 1000101 1
lxc.id_map = g 1000101 1000101 1

**Comment by stgraber** [comment] 2017-10-12 16:28
Ok, so yeah, you're hitting the kernel limit. You have 5 gid entries to which LXC temporarily adds an extra one making it reach the hard limit and the kernel then fails in a rather cryptic way...

LXC 2.0.9 should fix that particular issue for you as we've reshuffled some code to avoid setting up that extra entry, making it possible to start a container with 5 idmap entries. You however won't be able to add any more than that.

Separately, we're driving a kernel change that will effectively raise the limit from 5 entries to several hundreds. @brauner is doing some final tweaks on that particular change to limit the risk of performance regressions.


Closing this issue as there's nothing LXD can do about this unfortunately. There's no way to probe liblxc or the kernel for the maximum number of mappings allowed so we can't detect that problem ahead of time...

**Closed by stgraber** 2017-10-12 16:28 UTC

**Comment by dfberger** [comment] 2017-10-12 19:39
Thanks for the explanation - it's unfortunate that lxd can't determine the cause of the failure and give the user guidance, and good to hear it will improve in the future.  Sounds like my best bet here, since I need to punch a number of uids into the container, may be to run it privileged (gulp).

**Comment by Meywether** [comment] 2018-06-15 14:47
Hi everyone!
@stgraber and @brauner  are there any updates concerning your mentioned kernel change tp increase the mapping limit ?? 
Thanks in advance!

Best regards
Meywether

**Comment by brauner** [comment] 2018-06-15 14:48
@Meywether the patch is available in 4.15 kernels. :)

**Comment by Meywether** [comment] 2018-06-15 15:49
@brauner very nice, within 4.15.0-23-generic it is still limited to five.

THX!

**Comment by brauner** [comment] 2018-06-19 15:15
The reason for this may not be the kernel but for example a misconfigured `/etc/subuid` or `/etc/subgid`. Can you show the config of the container and the two files I mentioned above.  That would be helpful.

**Comment by Meywether** [comment] 2018-06-20 05:55
@brauner  Thanks a lot for helping me!
Up to five are working without problems.
expect the same users and order at both pictures!

My subuid on the host: 

![image](https://user-images.githubusercontent.com/39849054/41639660-fe0434d4-745e-11e8-8ef1-134b48614000.png)


My subgid at the host: 
![image](https://user-images.githubusercontent.com/39849054/41639678-204f9a06-745f-11e8-90f2-0c9d0eb46789.png)


My container conf: 

root@ubuntu1804:/var/snap/lxd/common/lxd/logs/Python1604-1# cat lxc.conf 
lxc.log.file = /var/snap/lxd/common/lxd/logs/Python1604-1/lxc.log
lxc.log.level = warn
lxc.console.buffer.size = auto
lxc.console.size = auto
lxc.console.logfile = /var/snap/lxd/common/lxd/logs/Python1604-1/console.log
lxc.mount.auto = proc:rw sys:rw
lxc.autodev = 1
lxc.pty.max = 1024
lxc.mount.entry = /dev/fuse dev/fuse none bind,create=file,optional
lxc.mount.entry = /dev/net/tun dev/net/tun none bind,create=file,optional
lxc.mount.entry = /proc/sys/fs/binfmt_misc proc/sys/fs/binfmt_misc none rbind,create=dir,optional
lxc.mount.entry = /sys/fs/fuse/connections sys/fs/fuse/connections none rbind,create=dir,optional
lxc.mount.entry = /sys/fs/pstore sys/fs/pstore none rbind,create=dir,optional
lxc.mount.entry = /sys/kernel/debug sys/kernel/debug none rbind,create=dir,optional
lxc.mount.entry = /sys/kernel/security sys/kernel/security none rbind,create=dir,optional
lxc.mount.entry = /dev/mqueue dev/mqueue none rbind,create=dir,optional
lxc.include = /snap/lxd/current/lxc/config//common.conf.d/
lxc.arch = linux64
lxc.hook.pre-start = /snap/lxd/current/bin/lxd callhook /var/snap/lxd/common/lxd 2 start
lxc.hook.post-stop = /snap/lxd/current/bin/lxd callhook /var/snap/lxd/common/lxd 2 stop
lxc.tty.max = 0
lxc.uts.name = Python1604-1
lxc.mount.entry = /var/snap/lxd/common/lxd/devlxd dev/lxd none bind,create=dir 0 0
lxc.apparmor.profile = lxd-Python1604-1_</var/snap/lxd/common/lxd>//&:lxd-Python1604-1_<var-snap-lxd-common-lxd>:
lxc.seccomp.profile = /var/snap/lxd/common/lxd/security/seccomp/Python1604-1
lxc.idmap = u 0 1000000 1000
lxc.idmap = g 0 1000000 1000
lxc.idmap = u 1000 1000 1
lxc.idmap = g 1000 1000 1
lxc.idmap = u 1001 1001 1
lxc.idmap = g 1001 1001 1
lxc.idmap = u 1002 1002 1
lxc.idmap = g 1002 1002 1
lxc.idmap = u 1003 1003 1
lxc.idmap = g 1003 1003 1
lxc.idmap = u 1004 1004 1
lxc.idmap = g 1004 1004 1
lxc.idmap = u 1005 1001005 1
lxc.idmap = g 1005 1001005 1
lxc.idmap = u 1006 1006 1
lxc.idmap = g 1006 1006 1
lxc.idmap = u 1007 1001007 1
lxc.idmap = g 1007 1001007 1
lxc.idmap = u 1008 1008 1
lxc.idmap = g 1008 1008 1
lxc.idmap = u 1009 1001009 1
lxc.idmap = g 1009 1001009 1
lxc.idmap = u 1010 1010 1
lxc.idmap = g 1010 1010 1
lxc.idmap = u 1011 1001011 1
lxc.idmap = g 1011 1001011 1
lxc.idmap = u 1012 1012 1
lxc.idmap = g 1012 1012 1
lxc.idmap = u 1013 1001013 1
lxc.idmap = g 1013 1001013 1
lxc.idmap = u 1014 1014 1
lxc.idmap = g 1014 1014 1
lxc.idmap = u 1015 1001015 999998985
lxc.idmap = g 1015 1001015 999998985
lxc.idmap = u 1013 1013 1
lxc.idmap = g 1013 1013 1
lxc.idmap = u 1011 1011 1
lxc.idmap = g 1011 1011 1
lxc.idmap = u 1009 1009 1
lxc.idmap = g 1009 1009 1
lxc.idmap = u 1007 1007 1
lxc.idmap = g 1007 1007 1
lxc.idmap = u 1005 1005 1
lxc.idmap = g 1005 1005 1
lxc.cgroup.memory.soft_limit_in_bytes = 1073741824
lxc.cgroup.memory.swappiness = 0
lxc.cgroup.cpu.shares = 519
lxc.cgroup.cpu.cfs_period_us = 100000
lxc.cgroup.blkio.weight = 500
lxc.cgroup.pids.max = 500
lxc.rootfs.path = dir:/var/snap/lxd/common/lxd/containers/Python1604-1/rootfs
lxc.mount.entry = /var/snap/lxd/common/lxd/devices/Python1604-1/disk.homes.home- home/ none rbind,optional,create=dir
lxc.net.0.type = veth
lxc.net.0.flags = up
lxc.net.0.link = lxdbr0
lxc.net.0.hwaddr = 00:16:3e:ab:7e:02
lxc.net.0.name = eth0
lxc.mount.entry = /var/snap/lxd/common/lxd/shmounts/Python1604-1 dev/.lxd-mounts none bind,create=dir 0 0

Thanks a lot !
Best regards
Meywether

**Comment by Meywether** [comment] 2018-06-20 10:20
@brauner  
Thanks for your response and your very valueable feedback
Ok, if I got it right, then subuid and subgid should be like that: 

![image](https://user-images.githubusercontent.com/39849054/41652654-026d945a-7484-11e8-9db8-8276d5847236.png)

####

Logs: 
Is group mapping is also possible? 
lxc Python1604-1 20180620054628.776 WARN     lxc_conf - conf.c:lxc_map_ids:2855 - newuidmap binary is missing
lxc Python1604-1 20180620054628.777 WARN     lxc_conf - conf.c:lxc_map_ids:2861 - newgidmap binary is missing
lxc Python1604-1 20180620054628.777 ERROR    lxc_conf - conf.c:write_id_mapping:2742 - Invalid argument - Failed to write uid mapping to "/proc/12247/uid_map"
lxc Python1604-1 20180620054628.777 ERROR    lxc_conf - conf.c:lxc_map_ids:2926 - Failed to write mapping: 0 1000000 1000
1000 1000 1
1001 1001 1
1002 1002 1
1003 1003 1
1004 1004 1
1005 1001005 1
1006 1006 1
1007 1001007 1
1008 1008 1
1009 1001009 1
1010 1010 1
1011 1001011 1
1012 1012 1
1013 1001013 1
1014 1014 1
1015 1001015 999998985
1013 1013 1
1011 1011 1
1009 1009 1
1007 1007 1
1005 1005 1

lxc Python1604-1 20180620054628.778 ERROR    lxc_start - start.c:lxc_spawn:1661 - Failed to set up id mapping.
lxc Python1604-1 20180620054628.120 WARN     lxc_network - network.c:lxc_delete_network_priv:2607 - Failed to remove interface "veth4J5QOL" from "lxdbr0": Invalid argument
lxc Python1604-1 20180620054628.121 ERROR    lxc_container - lxccontainer.c:wait_on_daemonized_start:834 - Received container state "ABORTING" instead of "RUNNING"
lxc Python1604-1 20180620054628.121 ERROR    lxc_start - start.c:__lxc_start:1887 - Failed to spawn container "Python1604-1"
lxc Python1604-1 20180620054628.121 WARN     lxc_conf - conf.c:lxc_map_ids:2855 - newuidmap binary is missing
lxc Python1604-1 20180620054628.121 WARN     lxc_conf - conf.c:lxc_map_ids:2861 - newgidmap binary is missing
lxc 20180620054628.123 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:130 - Connection reset by peer - Failed to receive response for command "get_state"
lxc 20180620054628.128 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:130 - Connection reset by peer - Failed to receive response for command "get_state"


Thanks a lot! 
Best regards
Meywether

**Comment by brauner** [comment] 2018-06-20 10:34
In your config:
```
lxc.idmap = u 1015 1001015 999998985
lxc.idmap = g 1015 1001015 999998985
lxc.idmap = u 1013 1013 1
lxc.idmap = g 1013 1013 1
lxc.idmap = u 1011 1011 1
lxc.idmap = g 1011 1011 1
lxc.idmap = u 1009 1009 1
lxc.idmap = g 1009 1009 1
lxc.idmap = u 1007 1007 1
lxc.idmap = g 1007 1007 1
lxc.idmap = u 1005 1005 1
lxc.idmap = g 1005 1005 1
```
the nsuids `100{5,7,9,11,13}` are mapped twice and the range for `1015` is too large.

**Comment by Meywether** [comment] 2018-06-20 10:38
ah sorry I see!
so changing subid und and subgid and conf to match exactly and then it should work

**Comment by brauner** [comment] 2018-06-20 10:40
@Meywether, it's not required to be 1:1 but yes, that can be the trick.

**Comment by Meywether** [comment] 2018-06-20 10:40
Mmh I am using the lxd api, and all the config came from there.
strange. I have to see where it came from

**Comment by Meywether** [comment] 2018-06-21 17:21
Hi, ok, I got it running by a quit nice workaround.
Do not changed subid and subgid.
just mapped 5, than starting container - stopping
mapping 5 again, than starting container - stopping
and so on, and I got it ;)ä
Thanks @brauner for your help!
