### ISSUE TITLE
jessie or vivid container don't stop

### ISSUE THREAD

**Issue by vince06fr** [lxc/lxd#715] opened 2015-05-27 14:57 UTC
launch a jessie based container and try to stop it
```
$ lxc list
+--------+---------+------------+------+-----------+-----------+
|  NAME  |  STATE  |    IPV4    | IPV6 | EPHEMERAL | SNAPSHOTS |
+--------+---------+------------+------+-----------+-----------+
| jessie | RUNNING | 10.0.3.161 |      | NO        | 0         |
+--------+---------+------------+------+-----------+-----------+
:~$ lxc stop jessie
```
nothing happened and I am  forced to do ctrl+c for retrieve the prompt then  the container is always running but it had no ip adress : 
```
$ lxc list
+--------+---------+------+------+-----------+-----------+
|  NAME  |  STATE  | IPV4 | IPV6 | EPHEMERAL | SNAPSHOTS |
+--------+---------+------+------+-----------+-----------+
| jessie | RUNNING |      |      | NO        | 0         |
+--------+---------+------+------+-----------+-----------+
```

so delete and reinstall jessie  and try to stop container from inside it
```
$ lxc exec jessie -- /bin/bash
root@LXC_NAME:~# shutdown -h now
Warning! D-Bus connection terminated.
Failed to wait for response: Success
Failed to open initctl FIFO: No such device or address
Failed to talk to init daemon.
```
same thing happen with vivid or sid based container

**Comment by stgraber** [comment] 2015-05-27 15:22
Likely to be the same issue we have in Ubuntu vivid, specifically that systemd doesn't seem to react to SIGPWR.

**Comment by stgraber** [comment] 2015-05-27 15:22
Passing --force should work though

**Comment by vince06fr** [comment] 2015-05-27 15:31
yes it is working with the --force option
thank you

**Comment by stgraber** [comment] 2015-05-27 19:34
Closing as this is essentially a duplicate of #687

**Closed by stgraber** 2015-05-27 19:34 UTC
