### ISSUE TITLE
error: unable to open database file

### ISSUE THREAD

**Issue by raymov** [lxc/lxd#3915] opened 2017-10-08 13:39 UTC
# Required information
 * Distribution: Ubuntu
 * Distribution version: 16.04.3 LTS (livepatch enabled)
 * lxc info
```
config: {}
api_extensions:
- id_map
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    <redacted>
    -----END CERTIFICATE-----
  certificate_fingerprint: b8c73d9ec99a4b65bccf92ff1fb4e60fe2e4bc8b9ffefafffe3d486a6f3dc8a3
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-92-generic
  server: lxd
  server_pid: 20697
  server_version: 2.0.10
  storage: dir
  storage_version: ""
```

# Issue description
Attempting to launch new container.
Have tried on different systems.

# Steps to reproduce
1. lxc launch images:debian/stretch/amd64 db9
(successfully launches)

2. lxc launch images:centos/7 maipo-test
```
Creating maipo-test
error: unable to open database file
```
:boom:

# Information to attach
 - [ ] Container log
lxc info maipo-test --show-log
`error: not found`
 - [ ] Container configuration
lxc config show maipo-test --expanded
`error: not found`
 - [ ] Main daemon log (at /var/log/lxd/lxd.log)
```
lvl=info msg="Connecting to a remote simplestreams server" t=2017-10-07T21:14:58+1100
alias=centos/7 image=b92d6ee55b81f64475a1006cb9b12f0b8a30eb3aa42901eeb816a9a39c3aaf5f lvl=info msg="Downloading image" operation=41d386b3-41c9-4024-9e31-797c6cac0053 server=https://images.linuxcontainers.org t=2017-10-07T21:15:03+1100 trigger=/1.0/operations/41d386b3-41c9-4024-9e31-797c6cac0053
alias=centos/7 image=b92d6ee55b81f64475a1006cb9b12f0b8a30eb3aa42901eeb816a9a39c3aaf5f lvl=info msg="Image downloaded" operation=41d386b3-41c9-4024-9e31-797c6cac0053 server=https://images.linuxcontainers.org t=2017-10-07T21:15:14+1100 trigger=/1.0/operations/41d386b3-41c9-4024-9e31-797c6cac0053
ephemeral=false lvl=info msg="Creating container" name=maipo-test t=2017-10-07T21:15:14+1100
ephemeral=false lvl=info msg="Created container" name=maipo-test t=2017-10-07T21:15:14+1100
creation date=2017-10-07T21:15:14+1100 ephemeral=false lvl=info msg="Deleting container" name=maipo-test t=2017-10-07T21:15:14+1100
creation date=2017-10-07T21:15:14+1100 ephemeral=false lvl=info msg="Deleted container" name=maipo-test t=2017-10-07T21:15:15+1100
```

 - [ ] Output of the client with --debug
```
lxc launch images:centos/7 maipo-test --debug
DBUG[10-07|21:38:36] Raw response: {"type":"sync","status":"Success","status_code":200,"operation":"","error_code":0,"error":"","metadata":{"config":{},"api_extensions":["id_map"],"api_status":"stable","api_version":"1.0","auth":"trusted","public":false,"environment":{"addresses":[],"architectures":["x86_64","i686"],"certificate":"-----BEGIN CERTIFICATE-----\n<redacted>\n-----END CERTIFICATE-----\n","certificate_fingerprint":"0da66a937164a7b06458cc61aeab66fc0b3f37fd37df500aec93dbdcf0c9e7c3","driver":"lxc","driver_version":"2.0.8","kernel":"Linux","kernel_architecture":"x86_64","kernel_version":"4.4.0-92-generic","server":"lxd","server_pid":31758,"server_version":"2.0.10","storage":"dir","storage_version":""}}}

DBUG[10-07|21:38:36] Raw response: {"type":"sync","status":"Success","status_code":200,"operation":"","error_code":0,"error":"","metadata":{"config":{},"api_extensions":["id_map"],"api_status":"stable","api_version":"1.0","auth":"trusted","public":false,"environment":{"addresses":[],"architectures":["x86_64","i686"],"certificate":"-----BEGIN CERTIFICATE-----\n<redacted>\n-----END CERTIFICATE-----\n","certificate_fingerprint":"0da66a937164a7b06458cc61aeab66fc0b3f37fd37df500aec93dbdcf0c9e7c3","driver":"lxc","driver_version":"2.0.8","kernel":"Linux","kernel_architecture":"x86_64","kernel_version":"4.4.0-92-generic","server":"lxd","server_pid":31758,"server_version":"2.0.10","storage":"dir","storage_version":""}}}

DBUG[10-07|21:38:36] POST {"name":"maipo-test","source":{"certificate":"","fingerprint":"centos/7","mode":"pull","protocol":"simplestreams","server":"https://images.linuxcontainers.org","type":"image"}}
 to http://unix.socket/1.0/containers
DBUG[10-07|21:38:36] Raw response: {"type":"async","status":"Operation created","status_code":100,"operation":"/1.0/operations/1473fd20-1ee9-4136-84e3-d75443555249","error_code":0,"error":"","metadata":{"id":"1473fd20-1ee9-4136-84e3-d75443555249","class":"task","created_at":"2017-10-07T21:38:36.678857598+11:00","updated_at":"2017-10-07T21:38:36.678857598+11:00","status":"Running","status_code":103,"resources":{"containers":["/1.0/containers/maipo-test"]},"metadata":null,"may_cancel":false,"err":""}}

Creating maipo-test
DBUG[10-07|21:38:37] Raw response: {"type":"sync","status":"Success","status_code":200,"operation":"","error_code":0,"error":"","metadata":{"id":"1473fd20-1ee9-4136-84e3-d75443555249","class":"task","created_at":"2017-10-07T21:38:36.678857598+11:00","updated_at":"2017-10-07T21:38:36.678857598+11:00","status":"Failure","status_code":400,"resources":{"containers":["/1.0/containers/maipo-test"]},"metadata":null,"may_cancel":false,"err":"unable to open database file"}}

error: unable to open database file
```
 - [ ] Output of the daemon with --debug
sudo lxd --debug --group lxd &> [lxd.log](https://github.com/lxc/lxd/files/1364551/lxd.log)
(Can't see anything obvious here)

lxc image list
```
+-------+--------------+--------+---------------------------------------------+--------+----------+------------------------------+
| ALIAS | FINGERPRINT  | PUBLIC |                 DESCRIPTION                 |  ARCH  |   SIZE   |         UPLOAD DATE          |
+-------+--------------+--------+---------------------------------------------+--------+----------+------------------------------+
|       | b92d6ee55b81 | no     | Centos 7 amd64 (20171007_02:16)             | x86_64 | 82.22MB  | Oct 7, 2017 at 10:15am (UTC) |
+-------+--------------+--------+---------------------------------------------+--------+----------+------------------------------+
|       | 96092fbb7c95 | no     | Debian stretch amd64 (20171006_22:42)       | x86_64 | 103.42MB | Oct 7, 2017 at 5:22am (UTC)  |
+-------+--------------+--------+---------------------------------------------+--------+----------+------------------------------+
|       | 03c2fa6716b5 | no     | ubuntu 16.04 LTS amd64 (release) (20170919) | x86_64 | 156.13MB | Sep 21, 2017 at 1:01am (UTC) |
+-------+--------------+--------+---------------------------------------------+--------+----------+------------------------------+
```
lxc list
```
> +------+---------+---------------------+------+------------+-----------+
> | NAME |  STATE  |        IPV4         | IPV6 |    TYPE    | SNAPSHOTS |
> +------+---------+---------------------+------+------------+-----------+
> | db9  | RUNNING | 203.x.x.51   (eth0) |      | PERSISTENT | 0         |
> +------+---------+---------------------+------+------------+-----------+
```
lxc profile show default
```
config: {}
description: Default LXD profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
name: default
```
ls -las /var/lib/lxd
`0 lrwxrwxrwx 1 root root 13 Aug 31 14:06 /var/lib/lxd -> /mnt/bak2/lxd`

df /mnt/bak2
```
Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/sda4       44951964 38367436   6568144  86% /mnt/bak2
```

sudo sqlite3 /var/lib/lxd/lxd.db "pragma integrity_check;"
`ok`

**Comment by stgraber** [comment] 2017-10-08 17:30
I think the symlink may be the cause of this, I've seen similar issues where go-sqlite3 gets confused on symlinks before.

I'd recommend you stop lxd, remove the /var/lib/lxd symlink and instead replace it by a bind-mount which should avoid this issue.

 - systemctl stop lxd lxd.socket
 - rm /var/lib/lxd
 - mkdir /var/lib/lxd
 - mount -o bind /mnt/bak2/lxd /var/lib/lxd
 - systemctl start lxd

Once that's done, you'll want this to persist across reboot, which you can do with the following /etc/fstab entry:

```
/mnt/bak2/lxd /var/lib/lxd none bind 0 0
```

**Comment by raymov** [comment] 2017-10-09 07:51
Same error unfortunately

**Comment by brauner** [comment] 2017-10-09 08:31
Can you please show `findmnt | grep "/var/lib/lxd"?

**Comment by raymov** [comment] 2017-10-09 10:22
findmnt | grep "/var/lib/lxd"
```
└─/var/lib/lxd                              /dev/sda4[/lxd]        ext4            rw,relatime,data=ordered
  ├─/var/lib/lxd/shmounts                   tmpfs                  tmpfs           rw,relatime,size=100k,mode=711
  ├─/var/lib/lxd/devlxd                     tmpfs                  tmpfs           rw,relatime,size=100k,mode=755
  └─/var/lib/lxd                            /dev/sda4[/lxd]        ext4            rw,relatime,data=ordered
```

**Comment by brauner** [comment] 2017-10-09 10:45
Hm, why is it mounted twice? Can you please stop the lxd daemon and then umount one of the `/var/lib/lxd` mounts, please?

**Comment by raymov** [comment] 2017-10-09 11:20
Not sure why, umounted all of above before remounting.

findmnt | grep "/var/lib/lxd"
```
├─/var/lib/lxd                              /dev/sda4[/lxd]        ext4            rw,relatime,data=ordered
│ ├─/var/lib/lxd/shmounts                   tmpfs                  tmpfs           rw,relatime,size=100k,mode=711
│ └─/var/lib/lxd/devlxd                     tmpfs                  tmpfs           rw,relatime,size=100k,mode=755
```
Still getting same error though.

**Comment by stgraber** [comment] 2017-10-09 12:14
That looks reasonable to me.

What does "ls -lah /var/lib/lxd" show you?

**Comment by raymov** [comment] 2017-10-09 12:38
ls -lah /var/lib/lxd
```
total 80K
drwxr-xr-x  9 root root 4.0K Oct  9 23:28 .
drwxr-xr-x 77 root root 4.0K Oct  9 18:10 ..
drwx--x--x  3 root root 4.0K Oct  9 22:22 containers
drwx--x--x  3 root root 4.0K Aug 31 14:25 devices
drwxr-xr-x  2 root root   60 Oct  9 22:08 devlxd
drwx------  2 root root 4.0K Oct  9 16:09 images
-rw-r--r--  1 root root  43K Oct  9 22:22 lxd.db
drwx------  4 root root 4.0K Aug 31 14:25 security
-rw-r--r--  1 root root 1.9K Aug 31 14:17 server.crt
-rw-------  1 root root 3.2K Aug 31 14:17 server.key
drwx--x--x  3 root root   60 Oct  9 22:21 shmounts
drwx------  2 root root 4.0K Aug 31 14:10 snapshots
srw-rw----  1 root lxd     0 Oct  9 22:08 unix.socket
```
Have noticed that `lxc launch` does update the lxd.db timestamp (UTC+11), but not the contents.

**Comment by stgraber** [comment] 2017-10-09 12:43
Based on the fact that LXD at least starts up it looks like read only access is fine, write access isn't.

**Comment by raymov** [comment] 2017-10-09 13:49
Could this be a temporary file issue?
https://sqlite.org/rescode.html#cantopen
What's the easiest way to check?

**Comment by brauner** [comment] 2017-10-09 14:55
Hm, can you check `/var/tmp`, `/usr/tmp`, `/tmp` for sqlite tmp files?

**Comment by stgraber** [comment] 2017-10-09 18:41
@raymov can you try directly writing to the database, see if that hits the same issue?

sudo sqlite3 /var/lib/lxd/lxd.db

```
INSERT INTO config (key, value) VALUES ('user.test', 'blah');
DELETE FROM config WHERE key='user.test';
```

**Comment by raymov** [comment] 2017-10-09 22:41
Couldn't see anything obvious in /var/tmp or /tmp, whilst /usr/tmp doesn't exist.

sudo sqlite3 /var/lib/lxd/lxd.db
```
SQLite version 3.11.0 2016-02-15 17:29:24
Enter ".help" for usage hints.
sqlite> .schema config
CREATE TABLE config (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    key VARCHAR(255) NOT NULL,
    value TEXT,
    UNIQUE (key)
);
sqlite> INSERT INTO config (key, value) VALUES ('user.test', 'blah');
sqlite> SELECT * FROM config;
1|user.test|blah
sqlite> DELETE FROM config WHERE key='user.test';
sqlite> SELECT * FROM config;
sqlite> .quit
```
In summary didn't get any errors creating and deleting test record.

**Comment by stgraber** [comment] 2017-10-10 02:42
I'm really confused by this one... And you said you've reproduce this on another machine right?

Setting up a clean 16.04 system here, will try to create the same two containers and see if I can get sqlite3 to be similarly unhappy...

**Comment by raymov** [comment] 2017-10-10 06:05
Yes, tested on three different bare metal systems on two different hardware platforms with either NVMe or SATA SSD's, including relevant `ufw route allow` (ALLOW FWD) rules via br0 for container public IP's. Appreciated Stéphane.

**Comment by stgraber** [comment] 2017-10-10 15:16
```
stgraber@castiana:~$ rssh ubuntu@lantea.maas.mtl
Warning: Permanently added 'lantea.maas.mtl' (ECDSA) to the list of known hosts.
root@lantea:~# apt update
Hit:1 http://us.archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Get:5 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [638 kB]
Get:6 http://us.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [538 kB]
Get:7 http://us.archive.ubuntu.com/ubuntu xenial-updates/universe Translation-en [218 kB]
Fetched 1,702 kB in 0s (1,890 kB/s)                             
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
root@lantea:~# apt dist-upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@lantea:~# lxc launch images:debian/stretch/amd64 db9
Generating a client certificate. This may take a minute...
If this is your first time using LXD, you should also run: sudo lxd init
To start your first container, try: lxc launch ubuntu:16.04

Creating db9
Starting db9                                  
root@lantea:~# lxc launch images:centos/7 maipo-test
Creating maipo-test
Starting maipo-test       
```

So it doesn't seem to be as trivial as just launching both containers on a clean 16.04 server :(

**Comment by stgraber** [comment] 2017-10-10 15:17
would have been surprising if it was just because of the container names :)

**Comment by stgraber** [comment] 2017-10-10 15:18
On an affected system, just after a failure, can you post:

 - ps fauxww
 - cat /proc/self/mountinfo
 - cat /proc/PID-OF-LXD/mountinfo
 - ls -lh /proc/PID-OF-LXD/fd

**Comment by raymov** [comment] 2017-10-11 13:56
Thanks, will test on a new system being setup shortly ...

**Comment by stgraber** [comment] 2017-10-18 04:26
Any luck?

**Comment by raymov** [comment] 2017-10-19 14:18
Will endeavour to test by the weekend. Just got new system configured with a bridged bonded Ethernet connection using nmcli, thanks to this workaround shown in Comment 10:
[Bug 1183420 - Adding bond device to bridge with "bridge-slave" type doesn't work](https://bugzilla.redhat.com/show_bug.cgi?id=1183420#c10).

**Comment by raymov** [comment] 2017-10-22 13:57
Found it, was caused by **insufficient inodes** on a `mkfs.ext4 -T largefile4` formatted filesystem:
```
df --inodes /mnt/bak2
Filesystem     Inodes IUsed IFree IUse% Mounted on
/dev/sda4       11008 10432   576   95% /mnt/bak2
```
For example on a 64 GiB partition, this only creates 16K inodes (instead of 4M), which is fine for KVM images, but not for launching more file intensive containers. Here is a quick demo showing some inode numbers:

```
truncate --size 64G lxd-largefile4.img
mkfs.ext4 -T largefile4 lxd-largefile4.img
Creating filesystem with 16777216 4k blocks and 16384 inodes

truncate --size 64G lxd.img
mkfs.ext4 lxd.img
Creating filesystem with 16777216 4k blocks and 4194304 inodes

lxc launch images:centos/7 maipo-test
lxc launch images:debian/stretch/amd64 stretch-test
lxc launch ubuntu:16.04 xenial-test

du --inodes --human-readable --max-depth=1 /var/lib/lxd/containers
13K     /var/lib/lxd/containers/maipo-test
9.2K    /var/lib/lxd/containers/stretch-test
31K     /var/lib/lxd/containers/xenial-test
53K     /var/lib/lxd/containers
```
Didn't find any obvious clues in /var/log, such as ext4 errors. May I suggest a more user friendly error message such as **insufficient inodes** when unable to launch?

**Comment by stgraber** [comment] 2017-10-22 21:22
Hmm, well, the kernel isn't being particularly useful about this as it'll happily let you do stuff when you're out of inode. Checking for the free inode count would also cause false positives on quite a number of filesystems which use a variable inode count.

It feels like the main issue here is actually a squlite3 or go-sqlite3 bug where the actual kernel error (ENOSPC) should have been surfaced back to the user rather than showing that confusing "unable to open database file".

**Comment by stgraber** [comment] 2017-10-22 21:24
Looks like sqlite3 has a bunch of wrapper around that particular error to give a more useful error, but they don't appear to have anything for ENOSPC, so I suspect that's where this should be improved, which would then trickle down to go-sqlite3 and so show up in the LXD error message.

Closing this issue since we finally figured it out :)

**Closed by stgraber** 2017-10-22 21:24 UTC
Labels: Incomplete
