### ISSUE TITLE
lxd zpool and all container disappear

### ISSUE THREAD

**Issue by vince06fr** [lxc/lxd#2904] opened 2017-02-18 20:52 UTC
# Required information

 * Distribution: ubuntu
 * Distribution version: 13.10
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-62-generic  x86_64
   * LXC version: 2.9.1
   * LXD version: 2.9.1
   * Storage backend in use:

# Issue description

After last upgrade, lxd Job for lxd-containers.service failed because the control process exited with error code
systemctl show this error:
```
vl=eror msg="Error checking storage pool \"lxd\": Unable to import the ZFS pool: cannot import '/var/lib/lxd/disks/lxd.img':
Feb 18 08:13:03 NC-PH-1236-53 lxd[31351]: error: Failed to set ZFS config: cannot open 'lxd': no such pool
Feb 18 08:13:03 NC-PH-1236-53 systemd[1]: lxd.service: Main process exited, code=exited, status=1/FAILURE
```
then trying
```
# zpool status lxd
cannot open 'lxd': no such pool
```
and
```
# zpool list      
no pools available
```
then i have trying to install reinstall lxd and zfs so i don't have more information

reading the zfs documentation i have found this:
```
ZFS maintains a cache of active pools and their configuration on the root file system. If this file is corrupted or somehow becomes out of sync with what is stored on disk, the pool can no longer be opened. ZFS tries to avoid this situation, though arbitrary corruption is always possible given the qualities of the underlying storage. This situation typically results in a pool disappearing from the system when it should otherwise be available. This situation can also manifest itself as a partial configuration that is missing an unknown number of top-level virtual devices. In either case, the configuration can be recovered by exporting the pool (if it is visible at all), and re-importing it.
https://docs.oracle.com/cd/E19120-01/open.solaris/817-2271/gbbve/index.html
```
for me the pool was not visible so i can't do anything,

Luckily it was my test environment and not production. But this possibility of complete disappearance of the pool is very worrying for my migration in zfs.
I have used BTRFS with LXD for over a year without any similar problems.

**Comment by stgraber** [comment] 2017-02-18 21:02
@brauner one more for you :)

**Comment by stgraber** [comment] 2017-02-18 21:03
so /var/lib/lxd/disks/lxd.img doesn't exist on your system?
is there anything in /var/lib/lxd/disks/ ?
Does /var/lib/lxd/zfs.img exist?

**Comment by vince06fr** [comment] 2017-02-19 00:07
Not sure because i have do an apt purge lxd and autoremove --purge before reinstalling 

sorry, i don't know how to reproduce the problem

**Comment by brauner** [comment] 2017-02-19 02:19
@stgraber, is apt purge wiping the zfs pool? Because the storage upgrade doesn't delete storage pools.

**Comment by stgraber** [comment] 2017-02-19 02:46
Oh, yes, if you ask apt to purge the package, it's going to wipe /var/lib/lxd clean, including the zfs.img file...

**Comment by stgraber** [comment] 2017-02-19 02:49
@vince06fr Can you attach:
 -  /var/log/lxd/lxd.log
 - /var/log/syslog
 - output of "journalctl | cat"

With a bit of luck we'll be able to pick up some LXD errors in there that will let us reproduce your problem and fix it for everyone else.

**Comment by vince06fr** [comment] 2017-02-19 08:16
can you provide me a way to send these files privately because i think these files could contain some sensitive data

**Comment by stgraber** [comment] 2017-02-19 19:59
Thanks for the logs, they unfortunately don't go far back enough to get to the time of the first failure so it's not going to be enough for us to reproduce this issue :(

**Comment by brauner** [comment] 2017-02-19 21:05
I take it this is an apt-purge issue more than an actual upgrade issue or is this something we need to fix on our side too?

**Comment by stgraber** [comment] 2017-02-19 21:24
@brauner So the fact that the pool was dropped on purge is normal and expected. But my understanding is that @vince06fr only did that purge AFTER LXD broke during the 2.9 upgrade as a way to try and get a clean environment back.

So it'd have been nice to figure out what went wrong in the first place and fix that.

**Comment by vince06fr** [comment] 2017-02-19 22:09
I hope the problem never go again but if there is a next tim I will remember to save the logs before doing a purge

**Comment by nickmaleao** [comment] 2017-02-20 11:18
After the last upgrade, i have the same problem.

One thing i noticed, was that the zpool didn't got mounted automatically.

I had to do "zpool import -d /var/lib/lxd/disks/ -a", and now the pool is mouted , but the lxd still fails to start with the error, "error: UNIQUE constraint failed: storage_pools.name"

**Comment by vince06fr** [comment] 2017-02-20 12:11
Thank you for the command
doing `zpool import -d /var/lib/lxd/disks/ -a` save my life, everything seem to work again
:)

**Comment by stgraber** [comment] 2017-02-20 18:08
@nickmaleao your issue is unrelated, it's most likely a duplicate of #2907 

@vince06fr good to hear that this did the trick!

**Closed by stgraber** 2017-02-20 18:08 UTC
Labels: Bug

**Comment by mdalacu** [comment] 2017-09-12 14:55
I have the same issue....lost eveything after the first host reboot.
No *.img in /var/lib/lxd
Is there anything i can do to save my work? My head will eplode if i have lost the containers...a week work...
`mdalacu@mdonline:~$ sudo tree /var/lib/lxd
/var/lib/lxd
├── containers
│   ├── lxc-monitord.log
│   ├── mdopenhab -> /var/lib/lxd/containers/mdopenhab.zfs
│   └── mdopenhab.zfs
├── devices
│   └── mdopenhab
├── devlxd
│   └── sock
├── images
│   ├── 58f90cbf68927c3fc43e6ee1386446a04f3d8068c1a75a291339cb2be01dec08
│   ├── 58f90cbf68927c3fc43e6ee1386446a04f3d8068c1a75a291339cb2be01dec08.rootfs
│   └── 58f90cbf68927c3fc43e6ee1386446a04f3d8068c1a75a291339cb2be01dec08.zfs
├── lxd.db
├── security
│   ├── apparmor
│   │   ├── cache
│   │   │   └── lxd-mdopenhab
│   │   └── profiles
│   │       └── lxd-mdopenhab
│   └── seccomp
│       └── mdopenhab
├── server.crt
├── server.key
├── shmounts
├── snapshots
│   └── mdopenhab
│       ├── openhab_clean.zfs -> on-zfs
│       └── snap0.zfs -> on-zfs
└── unix.socket

`
This is the error i get when i start lxd service
`EROR[09-12|17:40:38] Could not initialize storage type ZFS: cannot open 'lxd': dataset does not exist - falling back to dir `

This is in systemctl

`zfs-import-cache.service   loaded failed failed    Import ZFS pools by cache f
`
