### ISSUE TITLE
HiveOS LXD Init

### ISSUE THREAD

**Issue by reterik** [lxc/lxd#8587] opened 2021-03-19 22:26 UTC
* Distribution: HiveOS 
 * Distribution version: 5.4.80-hiveos
 * The output of "lxc info" or if that fails:

kernel_version: 5.4.80-hiveos
driver_version: 4.0.6 | 5.2.0
storage backend in use: btrfs

# Issue description

I am trying to initialize an LXC container and getting the following error:

Error: Failed to create network “lxdbr0” in project “default”: Failed adding DHCP/DNS access rules for network “lxdbr0” (ip): Failed apply nftables config: Failed to run: nft
table ip lxd {
chain in.lxdbr0 {
type filter hook input priority 0; policy accept;
iifname “lxdbr0” tcp dport 53 accept
iifname “lxdbr0” udp dport 53 accept
iifname “lxdbr0” udp dport 67 accept

}

chain out.lxdbr0 {
type filter hook output priority 0; policy accept;
oifname “lxdbr0” tcp sport 53 accept
oifname “lxdbr0” udp sport 53 accept
oifname “lxdbr0” udp sport 67 accept

}
}
: Error: Could not process rule: Operation not supported

  ^^^^^^^^^
Error: Could not process rule: Operation not supported

  ^^^^^^^^^^
Error: Could not process rule: No such file or directory

  ^^^^^^^^^
Error: Could not process rule: No such file or directory

  ^^^^^^^^^
Error: Could not process rule: No such file or directory

  ^^^^^^^^^
Error: Could not process rule: No such file or directory

  ^^^^^^^^^^
Error: Could not process rule: No such file or directory

  ^^^^^^^^^^
Error: Could not process rule: No such file or directory

  ^^^^^^^^^^

# Steps to reproduce

 1. snap install lxd
 2. lxd init

**Comment by stgraber** [comment] 2021-03-19 22:35
Sounds like your Linux distro has partial or broken nft support in its kernel. You can file an issue against your distro to have its kernel maintainers add the missing bits.

You can also do something like `iptables -A OUTPUT -j ACCEPT` to populate something in xtables which will then make LXD use that rather than nft on next restart of the LXD daemon (you'll need to make sure that something is put into xtables prior to LXD starting up on every boot though).

Closing as the issue isn't with LXD but with the host system having partially available nft support.

**Closed by stgraber** 2021-03-19 22:35 UTC
