### ISSUE TITLE
CPU use in seconds.

### ISSUE THREAD

**Issue by kasra73** [lxc/lxd#1867] opened 2016-04-07 12:38 UTC
as we know there is a "cpu use" in the output of lxc-info command that show CPU usage of container in seconds, but it does't exist in "lxc info <container>" response. How can I get it? Is there another way of getting CPU clocks that a container used?
Node that lxd version is 2.0.0.rc8

**Comment by stgraber** [comment] 2016-04-07 16:51
It's not currently exposed over the API so can't be shown on the client, it is however something we certainly should be adding.

Marking it as "later" since it's too late for LXD 2.0.

**Comment by stgraber** [comment] 2016-04-27 03:24
This should be a reasonably straightforward addition to the container state information, reading cpuacct.usage, converting it to a more useful unit (seconds would be reasonable) and returning it as a datapoint in the API.

**Comment by stevenmunro** [comment] 2016-07-20 11:24
I would also like to see this reporting included in the json output of lxc list

**Comment by stgraber** [comment] 2016-07-20 18:48
Since we return the whole container state struct in the json output, it would be included just like every other limit.

**Comment by stevenmunro** [comment] 2016-07-20 22:44
Hi Stephane, which version is this available in? I'm using 2.0.3

**Comment by stgraber** [comment] 2016-07-21 20:51
It's not, that's why the issue is still open.

**Comment by stevenmunro** [comment] 2016-07-21 22:33
Ahh thanks

**Closed** 2016-09-08 23:43 UTC
Labels: API, Documentation, Easy, Feature
