### ISSUE TITLE
Pulling an image fails when properties hash is passed

### ISSUE THREAD

**Issue by jsuwo** [lxc/lxd#1772] opened 2016-03-17 17:26 UTC
# Required information

 * Distribution: Ubuntu
 * Distribution version: 14.04.4
 * The output of "lxc info" or if that fails:
   * Kernel version: 3.19.0-43-generic
   * LXC version: 1.1.5
   * LXD version: 2.0.0.rc2
   * Storage backend in use: btrfs

# Issue description

When `POST`-ing to `/1.0/images` with mode set to `pull` to copy an image from a remote LXD server, if you add a `properties` hash to the `POST`-ed data, the operation fails with an error.

```
curl -k -X POST \
  -H "Content-Type: application/json" \
  -d '{"auto_update":true,"public":false,"source":{"certificate":"","fingerprint":"07d1a93ca98d3480b4b763c4defb9d05b082b764b1abac7a4dc00f482d6faf09","mode":"pull","protocol":"","server":"https://images.linuxcontainers.org:8443","type":"image","properties":{"hello":"world"}}}' \
  --key ~/.config/lxc/client.key \
  --cert ~/.config/lxc/client.crt \
  https://127.0.0.1:8443/1.0/images
```

Error in the logs:

```
t=2016-03-17T12:52:26-0400 lvl=eror msg="Failed to get image metadata" function=getImgPostInfo err="detectCompression failed, err='Unsupported compression.', tarfile='/var/lib/lxd/images/lxd_build_368759448/lxd_tar_798899082'"
```

Yet, when you *don't* add the `properties` hash, the operation succeeds.  The following works just fine and properly imports the image:

```
$ curl -k -X POST \
  -H "Content-Type: application/json" \
  -d '{"auto_update":true,"public":false,"source":{"certificate":"","fingerprint":"07d1a93ca98d3480b4b763c4defb9d05b082b764b1abac7a4dc00f482d6faf09","mode":"pull","protocol":"","server":"https://images.linuxcontainers.org:8443","type":"image"}}' \
  --key ~/.config/lxc/client.key \
  --cert ~/.config/lxc/client.crt \
  https://127.0.0.1:8443/1.0/images

$ lxc image list
+-------+--------------+--------+----------------------------------------+--------+---------+------------------------------+
| ALIAS | FINGERPRINT  | PUBLIC |              DESCRIPTION               |  ARCH  |  SIZE   |         UPLOAD DATE          |
+-------+--------------+--------+----------------------------------------+--------+---------+------------------------------+
|       | 07d1a93ca98d | no     | Ubuntu xenial (amd64) (20160317_03:49) | x86_64 | 84.12MB | Mar 17, 2016 at 5:23pm (UTC) |
+-------+--------------+--------+----------------------------------------+--------+---------+------------------------------+
```

If I import from a local tarball and specify the properties in the `X-LXD-properties` header, it also works just fine:

```
$ lxc image list
+-------+-------------+--------+-------------+------+------+-------------+
| ALIAS | FINGERPRINT | PUBLIC | DESCRIPTION | ARCH | SIZE | UPLOAD DATE |
+-------+-------------+--------+-------------+------+------+-------------+

$ curl -k -X POST \
  -H "Content-Type: application/octet-stream" \
  -H "X-LXD-properties: hello=world" \
  --key ~/.config/lxc/client.key \
  --cert ~/.config/lxc/client.crt \
  -T /tmp/busybox-1.21.1-amd64-lxc.tar.xz \
  https://127.0.0.1:8443/1.0/images

$ lxc image list
+-------+--------------+--------+----------------+--------+--------+------------------------------+
| ALIAS | FINGERPRINT  | PUBLIC |  DESCRIPTION   |  ARCH  |  SIZE  |         UPLOAD DATE          |
+-------+--------------+--------+----------------+--------+--------+------------------------------+
|       | 097e75d6f741 | no     | Busybox x86_64 | x86_64 | 0.77MB | Mar 17, 2016 at 5:21pm (UTC) |
+-------+--------------+--------+----------------+--------+--------+------------------------------+

$ lxc image info 097
Fingerprint: 097e75d6f7419d3a5e204d8125582f2d7bdd4ee4c35bd324513321c645f0c415
Size: 0.77MB
Architecture: x86_64
Public: no
Timestamps:
    Created: 2016/01/11 17:17 UTC
    Uploaded: 2016/03/17 17:17 UTC
    Expires: never
Properties:
    architecture: x86_64
    description: Busybox x86_64
    hello: world                     <--------- note the property
    name: busybox-x86_64
    os: Busybox
Aliases:
Auto update: disabled
```

Not sure if this is a bug in LXD, or simply a doc bug.  The API docs contain the following, indicating that a `properties` hash can be passed:

```
In the source image case, the following dict must be used:

{
    "filename": filename,                   # Used for export (optional)
    "public": true,                         # Whether the image can be downloaded by untrusted users (defaults to false
    "properties": {                         # Image properties (optional, applied on top of source properties)
        "os": "Ubuntu"
    },
    "source": {
        "type": "image",
        "mode": "pull",                     # Only pull is supported for now
        "server": "https://10.0.2.3:8443",  # Remote server (pull mode only)
        "protocol": "lxd",                  # Protocol (one of lxd or simplestreams, defaults to lxd)
        "secret": "my-secret-string",       # Secret (pull mode only, private images only)
        "certificate": "PEM certificate",   # Optional PEM certificate. If not mentioned, system CA is used.
        "fingerprint": "SHA256",            # Fingerprint of the image (must be set if alias isn't)
        "alias": "ubuntu/devel",            # Name of the alias (must be set if fingerprint isn't)
    }
}
```

**Comment by stgraber** [comment] 2016-03-17 18:41
Reproduced it, looking into it now.

**Comment by stgraber** [comment] 2016-03-17 18:59
Oh, I found the problem, your request is incorrect.

The "properties" key isn't valid inside the "source" map, it's valid at the root of the request, so you instead want:

```
curl -k -X POST   -H "Content-Type: application/json"   -d '{"auto_update":true,"public":false,"source":{"certificate":"","fingerprint":"07d1a93ca98d3480b4b763c4defb9d05b082b764b1abac7a4dc00f482d6faf09","mode":"pull","protocol":"","server":"https://images.linuxcontainers.org:8443","type":"image"}, "properties":{"a":"b", "c": "d"}}'   --key ~/.config/lxc/client.key   --cert ~/.config/lxc/client.crt   https://127.0.0.1:8443/1.0/images
```

**Comment by stgraber** [comment] 2016-03-17 19:01
I just confirmed that our documentation looks correct.

I'll see if we can somehow return the json error instead of moving on and giving that very odd response.
The problem is that we currently use the fact that the body fails to parse as json as the way to detect that we've received a binary image rather than a json request...

**Comment by jsuwo** [comment] 2016-03-17 19:01
Sigh.  Yes, thank you, and sorry to waste your time.  Can't believe I missed that both in my Ruby code, and at the command line with curl.

**Comment by stgraber** [comment] 2016-03-17 19:07
Pushed a fix to my branch to return a proper error when we're told that the input is json and it fails to parse.

**Closed** 2016-03-17 20:11 UTC
Labels: Bug
