### ISSUE TITLE
Improve debugging on lxc exec failure

### ISSUE THREAD

**Issue by candlerb** [lxc/lxd#5044] opened 2018-09-18 10:49 UTC
# Required information

 * Distribution: ubuntu
 * Distribution version: 16.04.5
 * Tested both with stock lxd 2.0.11, and with 3.0.1 from backports. Behaviour is the same.

# Issue description

When `lxc exec` fails because the target binary does not exist, it silently returns to the command line with exit code 255.

The only clue as to what happened is if you dig into `/var/log/lxd/<containername>/lxc.log` where you can see:

```
lxc 20180918103430.791 ERROR    lxc_attach - attach.c:lxc_attach_run_command:1292 - No such file or directory - Failed to exec "/usr/bin/python".
```

This matters especially when invoking `lxc exec` from other applications, e.g. https://github.com/dw/mitogen/issues/373, as the lack of an error message makes debugging harder.

Note also that exit code 255 is technically invalid, although it's what you get if you call `exit(-1)`.  Valid exit codes are 0-127.  Bit 7 is supposed to indicate that the process terminated with a signal (e.g. SIGABRT = 6+128 = 134).  See macros `WIFEXITED`, `WIFSIGNALED` which test this bit.

# Steps to reproduce

Start a vanilla ubuntu 16.04 container (which by default does not have python2)

```
$ lxc exec gold-master -- /usr/bin/python -c 'print("hello")'
$ echo $?
255
```

For comparison, a normal shell will generate an error message on stderr, and return 127:

```
$ lxc exec gold-master -- /bin/sh -c '/usr/bin/python'
/bin/sh: 1: /usr/bin/python: not found
$ echo $?
127
```

# Expected behaviour

I would like `lxc exec` to return on stderr the message which the daemon already logs, in this example `No such file or directory - Failed to exec "/usr/bin/python"`.  If that's not possible, then generate some local error message saying that lxc exec failed.

I also think it would be better to return 127 than 255, but that would risk breaking backwards-compatibility.

**Comment by stgraber** [comment] 2018-09-18 14:29
Just spent about an hour looking into this again as I remembered coming to the conclusion in the past that this is unfortunately not doable and I can indeed confirm that it's not currently possible.

What we'd need to make this possible is a change to the `attach()` function in liblxc so that it would capture any error thrown by `execve` even when the process is spawned daemonized.

Right now the problem is that all we get when spawning a daemonized process is the pid of that process right before the `execve`. This lets us `wait()` on it and the kernel then gives us the errno for the task, unfortunately that's just `-1` so that's why you get 255.

I wonder if there's some pipe/socketpair trick that attach() could do to get notified that the `execve` call has happened. That'd let it block until after the execve and we could also have the subprocess handle execve's return code and send it through pipe back to the parent, letting us record and forward that errno all the way back to LXD.

@brauner opinion? If doable, can you file a liblxc bug for this?

I'm closing the LXD side of this as I've confirmed that we do in fact properly forward all errors from go-lxc and liblxc, we just aren't getting anything more than a -1 retval right now.

**Closed by stgraber** 2018-09-18 14:29 UTC

**Comment by candlerb** [comment] 2018-09-18 14:59
> Right now the problem is that all we get when spawning a daemonized process is the pid of that process right before the execve. This lets us wait() on it and the kernel then gives us the errno for the task, unfortunately that's just -1 so that's why you get 255.

Can you point me to the bit of code you're talking about?

I'm confused by what you said, because a standard `wait()` doesn't return a child's errno, it returns its exit status.  `execve()` can return -1 on failure, but in that case it sets `errno` to the correct code (e.g. ENOENT / file not found), and the child continues to run.  If the child decides to die at that point, it can choose its own exit status.

**Comment by stgraber** [comment] 2018-09-18 15:33
@candlerb that's in github.com/lxc/lxc

Basically, LXD spawns a go subprocess that uses go-lxc to call liblxc through CGO.
The function we end up calling is `c->attach()` in liblxc, when in detach mode as LXD uses it, it will spawn a subprocess, do various synchronization and eventually call `execve()` in that subprocess.

The parent process returns 0 if the child process initializes properly or -1 if it doesn't.
It also sets the pid of that subprocess through a pointer that the caller passes.

In the case where `execve` fails, it's after the child is done initializing, so the parent will return 0 and the PID of the child.

LXD is provided with that, so no initial error and some PID to watch. It then waits for that process to exit, which it does immediately, and then pulls the return code which is -1.

The errno of `execve` is never forwarded anywhere and so isn't accessible to users of liblxc, go-lxc or LXD.

To fix this we need some code added to liblxc so that attach() only ever returns 0 if the execve succeeded and if it doesn't, it should itself return a suitable return value which will let its downstreams (go-lxc and lxd) actually figure out what happened.

**Comment by candlerb** [comment] 2018-09-18 15:57
> that's in github.com/lxc/lxc

Do you mean [src/lxc/attach.c](https://github.com/lxc/lxc/blob/master/src/lxc/attach.c) ?  I see `lxc_attach_run_command` and `lxc_attach_run_shell` which return -1 on exit failure, but need to trace back where these are called from to see what they do in that situation.

I also see this:

```
                /* Try to run getent program. */
                (void) execvp("getent", arguments);
                exit(-1);
```

That's an invalid exit code, which gets masked to 255.  exit(127) would be what a shell does in this situation.

> The parent process returns 0 if the child process initializes properly or -1 if it doesn't.
It also sets the pid of that subprocess through a pointer that the caller passes.
> 
> In the case where execve fails, it's after the child is done initializing, so the parent will return 0 and the PID of the child.

With you so far.

> LXD is provided with that, so no initial error and some PID to watch.

No problem.

> It then waits for that process to exit, which it does immediately, and then pulls the return code which is -1.

And this is the value which the child *chose* as its exit status, by explicitly calling `exit(-1)`, which the kernel ANDs with a mask to make it 255.

> The errno of execve is never forwarded anywhere and so isn't accessible to users of liblxc, go-lxc or LXD.

The errno of execve is available in the child.  If the child has a socketpair for communicating to the parent - which I thought it had - then it can send a message back before it terminates.

At worst, even if it can't send a message back, it could return different status codes for different errors.  Silly example:

```
ret = execve(...)
if (ret == ENOENT) { exit(127); }
if (ret == EPERM) { exit(1); }
exit(2);
```

**Comment by candlerb** [comment] 2018-09-18 16:04
What I'm thinking is: at the point `lxc_attach_run_command` is run, stdin/stdout/stderr must already have been redirected already so the parent will pick them up. So why not change it like this:

```
int lxc_attach_run_command(void* payload)
{
        lxc_attach_command_t* cmd = (lxc_attach_command_t*)payload;

        execvp(cmd->program, cmd->argv);
        SYSERROR("Failed to exec \"%s\".", cmd->program);
        perror("exec");    // NOTE
        return 127;
}
```

The `perror` will send the error message over stderr, which the parent will pick up, and the return 127 gives a standard exit code for "command not found"

**Comment by stgraber** [comment] 2018-09-18 16:15
It's in `lxc_attach()` in attach.c and yes, it just uses EXIT_FAILURE right now as its exit code on failure.
I don't think we necessarily want to rely on the exit code to figure this out as that still won't tell us if the spawned command exited non-zero or if it's a failure to exec.

What we need is to setup a PIPE between the sub-process and caller and make it so that on succesful exec the caller can detect it (SIGPIPE on a CLOEXEC PIPE might do the trick) and otherwise read the errno as an int from the PIPE.

In any case, this is a liblxc issue and @brauner is the usual suspect for dealing with that stuff :)

**Comment by candlerb** [comment] 2018-09-18 16:44
> It's in lxc_attach() in attach.c and yes, it just uses EXIT_FAILURE right now as its exit code on failure.

Actually, EXIT_FAILURE is 1, not -1. (It's in `/usr/include/stdlib.h`)

> I don't think we necessarily want to rely on the exit code to figure this out as that still won't tell us if the spawned command exited non-zero or if it's a failure to exec.

That indeed is a general problem which the shell has too.  You can't tell the difference between a process which intentionally exited 127, versus a failure to start the process in the first case.

```
$ sh -c '/nonexistent'; echo $?
sh: 1: /nonexistent: not found
127
$ sh -c 'exit 127'; echo $?
127
```

However, it's (shell) convention that 127 is used to mean "failed to start the command".  Any command which decided to use 127 as a useful return code would fly in the face of this convention.

> What we need is to setup a PIPE between the sub-process and caller

This is where I fail to follow.  Clearly, if I do `lxc exec foo -- /bin/bar` then a chain of pipes is already set up, such that if the `exec()` succeeds, the stdout and stderr of `/bin/bar` is returned back via lxd to the client.  So why not just send a message on stderr if `exec()` fails?  It's already plumbed in.

**Comment by stgraber** [comment] 2018-09-18 16:48
Because you'd be getting that error on the stderr websocket rather than as an error message on the operation in the REST API. It may not matter for a direct user of the `lxc` command, but it does matter for API users.

**Comment by brauner** [comment] 2018-09-19 07:47
Please see https://github.com/lxc/lxc/pull/2622 .

**Comment by candlerb** [comment] 2018-09-19 09:05
Thank you - that's a step in the right direction.

So what do you think about changing the client, i.e. `lxc exec`, to generate a message in this situation?  Something like this:

```
...
if (ret == 126) { errno=ENOEXEC; perror("failed to exec"); }
else if (ret == 127) { errno=ENOENT; perror("failed to exec"); }
```
