### ISSUE TITLE
Unable to add zfs pool to running cluster

### ISSUE THREAD

**Issue by monstermunchkin** [lxc/lxd#8421] opened 2021-02-03 14:14 UTC
# Required information

 * Distribution: Ubuntu
 * Distribution version: 21.04
 * The output of "lxc info" or if that fails:
```
config:
  cluster.https_address: 10.2.1.10:8443
  core.https_address: 10.2.1.10:8443
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
- firewall_driver
- projects_limits
- container_syscall_intercept_hugetlbfs
- limits_hugepages
- container_nic_routed_gateway
- projects_restrictions
- custom_volume_snapshot_expiry
- volume_snapshot_scheduling
- trust_ca_certificates
- snapshot_disk_usage
- clustering_edit_roles
- container_nic_routed_host_address
- container_nic_ipvlan_gateway
- resources_usb_pci
- resources_cpu_threads_numa
- resources_cpu_core_die
- api_os
- container_nic_routed_host_table
- container_nic_ipvlan_host_table
- container_nic_ipvlan_mode
- resources_system
- images_push_relay
- network_dns_search
- container_nic_routed_limits
- instance_nic_bridged_vlan
- network_state_bond_bridge
- usedby_consistency
- custom_block_volumes
- clustering_failure_domains
- resources_gpu_mdev
- console_vga_type
- projects_limits_disk
- network_type_macvlan
- network_type_sriov
- container_syscall_intercept_bpf_devices
- network_type_ovn
- projects_networks
- projects_networks_restricted_uplinks
- custom_volume_backup
- backup_override_name
- storage_rsync_compression
- network_type_physical
- network_ovn_external_subnets
- network_ovn_nat
- network_ovn_external_routes_remove
- tpm_device_type
- storage_zfs_clone_copy_rebase
- gpu_mdev
- resources_pci_iommu
- resources_network_usb
- resources_disk_address
- network_physical_ovn_ingress_mode
- network_ovn_dhcp
- network_physical_routes_anycast
- projects_limits_instances
- network_state_vlan
- instance_nic_bridged_port_isolation
- instance_bulk_state_change
- network_gvrp
- instance_pool_move
- gpu_sriov
- pci_device_type
- storage_volume_state
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 10.2.1.10:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIICADCCAYegAwIBAgIRAO1NrxBYoaSRJeozwYBXPUEwCgYIKoZIzj0EAwMwMzEc
    MBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzETMBEGA1UEAwwKcm9vdEBhdGxh
    czAeFw0yMTAyMDMwNzU4MDhaFw0zMTAyMDEwNzU4MDhaMDMxHDAaBgNVBAoTE2xp
    bnV4Y29udGFpbmVycy5vcmcxEzARBgNVBAMMCnJvb3RAYXRsYXMwdjAQBgcqhkjO
    PQIBBgUrgQQAIgNiAAQO6UGn6WNeRbLkF4Z0Jrs2nLxY3pcjFdCNfkFYw8ER3kYn
    bJ4ZjLIUlefLeWn5wmr9CQP4zzBBJxwNxgLI+nkM8eQ0EVGXsH1CFxThZdev+BfN
    2A2VExkfh0EDJwwfh0WjXzBdMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggr
    BgEFBQcDATAMBgNVHRMBAf8EAjAAMCgGA1UdEQQhMB+CBWF0bGFzhwR/AAABhxAA
    AAAAAAAAAAAAAAAAAAABMAoGCCqGSM49BAMDA2cAMGQCMFo101+iYBQPrKImnMNj
    c+5xH3m77HiQkCjnswSCm1zAQrtSPI2IiyK60ufiQl5KOgIwBDxDl8k4n+mkuywE
    CkbCz+VMkhgQNJnV+eI5U9s8qgBhTTyybnif+TcIyHzJSfoH
    -----END CERTIFICATE-----
  certificate_fingerprint: 28fbc1d39a8943d14ed3e080ce747617e893184a56866f14987ff00da0935920
  driver: lxc | qemu
  driver_version: 4.0.0 (devel) | 5.2.0
  firewall: nftables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "true"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.8.0-36-generic
  lxc_features:
    cgroup2: "true"
    devpts_fd: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Ubuntu
  os_version: "21.04"
  project: default
  server: lxd
  server_clustered: true
  server_name: node1
  server_pid: 796300
  server_version: "4.10"
  storage: ceph
  storage_version: ceph version 15.2.7 (88e41c6c49beb18add4fdb6b4326ca466d931db8) octopus (stable)
```
# Issue description

I have a cluster with 5 nodes.
```
$ lxc cluster list cluster:
+-------+------------------------+----------+--------+-------------------+--------------+----------------+
| NAME  |          URL           | DATABASE | STATE  |      MESSAGE      | ARCHITECTURE | FAILURE DOMAIN |
+-------+------------------------+----------+--------+-------------------+--------------+----------------+
| node1 | https://10.2.1.10:8443 | NO       | ONLINE | fully operational | x86_64       | default        |
+-------+------------------------+----------+--------+-------------------+--------------+----------------+
| node2 | https://10.2.1.20:8443 | NO       | ONLINE | fully operational | x86_64       | default        |
+-------+------------------------+----------+--------+-------------------+--------------+----------------+
| node3 | https://10.2.1.30:8443 | YES      | ONLINE | fully operational | x86_64       | default        |
+-------+------------------------+----------+--------+-------------------+--------------+----------------+
| node4 | https://10.2.1.40:8443 | YES      | ONLINE | fully operational | x86_64       | default        |
+-------+------------------------+----------+--------+-------------------+--------------+----------------+
| node5 | https://10.2.1.50:8443 | YES      | ONLINE | fully operational | x86_64       | default        |
+-------+------------------------+----------+--------+-------------------+--------------+----------------+
```

 When trying to add a zfs storage pool once the cluster is up and running, it fails with
```
$ lxc storage create cluster:zfs zfs 
Error: failed to notify peer 10.2.1.20:8443: Failed to run: zpool create -f -m none -O compression=on zfs /home/thomas/work/lxd/cluster/2/disks/zfs.img: cannot create 'zfs': pool already exists
```
The `zfs.img` is created on every node, but, judging by the error, it's trying to do so a second time.

# Steps to reproduce

 1. Setup cluster
 2. `lxc storage create cluster:zfs zfs --target node{1..5}`
 3. `lxc storage create cluster:zfs zfs`
 4. fail

**Comment by stgraber** [comment] 2021-02-03 15:25
Interesting, I'll take a look at this one.

**Comment by stgraber** [comment] 2021-02-04 16:57
- Step 2) above only touches the database as planned, no sign of zfs.img in disks/ or zpool entries.
 - Step 3) properly creates the zfs.img file and zpool on all nodes here
 - lxc storage delete properly destroys zpools and zfs.img on all nodes.

Tested on current latest/edge.

**Comment by stgraber** [comment] 2021-02-04 16:58
```
root@vm04:~# lxc storage create zfs zfs --target vm04
Storage pool zfs pending on member vm04
root@vm04:~# lxc storage create zfs zfs --target vm05
Storage pool zfs pending on member vm05
root@vm04:~# lxc storage create zfs zfs --target vm06
Storage pool zfs pending on member vm06
root@vm04:~# lxc storage create zfs zfs
Storage pool zfs created
root@vm04:~# lxc storage delete zfs
Storage pool zfs deleted
root@vm04:~# lxc storage create zfs zfs --target vm04
Storage pool zfs pending on member vm04
root@vm04:~# lxc storage create zfs zfs --target vm05
Storage pool zfs pending on member vm05
root@vm04:~# lxc storage create zfs zfs --target vm06
Storage pool zfs pending on member vm06
root@vm04:~# lxc storage create zfs zfs
Storage pool zfs created
root@vm04:~# lxc storage delete zfs
Storage pool zfs deleted
```

**Comment by tomponline** [comment] 2021-02-04 17:00
Perhaps the `zfs` pool was left over from a previous pool on one of the nodes?

**Comment by stgraber** [comment] 2021-02-04 17:25
Yeah, a pool that wasn't properly deleted by ZFS would cause this error indeed (even if zfs.img was deleted).

**Comment by stgraber** [comment] 2021-02-04 17:47
Played with it some more and can't reproduce it, so assuming that it was indeed a dirty system and closing this.

**Closed by stgraber** 2021-02-04 17:47 UTC
Labels: Bug, Incomplete

**Comment by monstermunchkin** [comment] 2021-02-04 18:56
> Perhaps the `zfs` pool was left over from a previous pool on one of the nodes?

Nope, that's not it. `zpool list` doesn't show any pools.

**Comment by stgraber** [comment] 2021-02-04 19:05
Track it down to running multiple LXD daemons on the same system, source= would avoid such issues.
