### ISSUE TITLE
 ERROR    lxc_start - start.c:start:1439 - No such file or directory - failed to exec /sbin/init

### ISSUE THREAD

**Issue by taozongwang** [lxc/lxd#2433] opened 2016-09-29 01:46 UTC
os: ubuntu 14.04.1
kernel: 4.4.0-38-generic
```
$ lxc start causal-elk 
error: Error calling 'lxd forkstart causal-elk /var/lib/lxd/containers /var/log/lxd/causal-elk/lxc.conf': err='exit status 1'
  lxc 20160929013307.005 ERROR lxc_start - start.c:start:1439 - No such file or directory - failed to exec /sbin/init
  lxc 20160929093307.005 ERROR lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 5)
  lxc 20160929093307.005 ERROR lxc_start - start.c:__lxc_start:1354 - failed to spawn 'causal-elk'
  lxc 20160929093307.523 ERROR lxc_conf - conf.c:run_buffer:347 - Script exited with status 1
  lxc 20160929093307.523 ERROR lxc_start - start.c:lxc_fini:555 - failed to run post-stop hooks for container 'causal-elk'.
```

debug info 
```
$ lxc info --show-log causal-elk
Name: causal-elk
Architecture: x86_64
Created: 2016/09/28 09:44 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:

            lxc 20160929093256.696 INFO     lxc_start - start.c:lxc_check_inherited:252 - closed inherited fd 3
            lxc 20160929093256.696 INFO     lxc_start - start.c:lxc_check_inherited:252 - closed inherited fd 7
            lxc 20160929093256.711 INFO     lxc_container - lxccontainer.c:do_lxcapi_start:797 - Attempting to set proc title to [lxc monitor] /var/lib/lxd/containers causal-elk
            lxc 20160929093256.711 INFO     lxc_start - start.c:lxc_check_inherited:252 - closed inherited fd 7
            lxc 20160929093256.711 INFO     lxc_lsm - lsm/lsm.c:lsm_init:48 - LSM security driver AppArmor
            lxc 20160929093256.711 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: ..
            lxc 20160929093256.711 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for  action 0
            lxc 20160929093256.711 WARN     lxc_seccomp - seccomp.c:do_resolve_add_rule:228 - Seccomp: failed to resolve syscall: 
            lxc 20160929093256.711 WARN     lxc_seccomp - seccomp.c:do_resolve_add_rule:229 - This syscall will NOT be blacklisted
            lxc 20160929093256.711 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for  action 0
            lxc 20160929093256.711 WARN     lxc_seccomp - seccomp.c:do_resolve_add_rule:228 - Seccomp: failed to resolve syscall: 
            lxc 20160929093256.711 WARN     lxc_seccomp - seccomp.c:do_resolve_add_rule:229 - This syscall will NOT be blacklisted
            lxc 20160929093256.711 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .reject_force_umount  # comment this to allow umount -f;  not recommended.
            lxc 20160929093256.711 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for reject_force_umount action 0
            lxc 20160929093256.711 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:216 - Setting seccomp rule to reject force umounts

            lxc 20160929093256.711 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for reject_force_umount action 0
            lxc 20160929093256.711 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:216 - Setting seccomp rule to reject force umounts

            lxc 20160929093256.711 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .[all].
            lxc 20160929093256.711 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .kexec_load errno 38.
            lxc 20160929093256.711 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for kexec_load action 327718
            lxc 20160929093256.711 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for kexec_load action 327718
            lxc 20160929093256.711 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .open_by_handle_at errno 38.
            lxc 20160929093256.712 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for open_by_handle_at action 327718
            lxc 20160929093256.712 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for open_by_handle_at action 327718
            lxc 20160929093256.712 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .init_module errno 38.
            lxc 20160929093256.712 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for init_module action 327718
            lxc 20160929093256.712 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for init_module action 327718
            lxc 20160929093256.712 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .finit_module errno 38.
            lxc 20160929093256.712 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for finit_module action 327718
            lxc 20160929093256.712 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for finit_module action 327718
            lxc 20160929093256.712 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .delete_module errno 38.
            lxc 20160929093256.712 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for delete_module action 327718
            lxc 20160929093256.712 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for delete_module action 327718
            lxc 20160929093256.712 INFO     lxc_seccomp - seccomp.c:parse_config_v2:456 - Merging in the compat seccomp ctx into the main one
            lxc 20160929093256.712 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/bin/lxd callhook /var/lib/lxd 36 start' for container 'causal-elk', config section 'lxc'
            lxc 20160929093256.712 INFO     lxc_start - start.c:lxc_check_inherited:252 - closed inherited fd 3
            lxc 20160929093256.712 INFO     lxc_start - start.c:lxc_check_inherited:252 - closed inherited fd 7
            lxc 20160929093256.713 INFO     lxc_monitor - monitor.c:lxc_monitor_sock_name:178 - using monitor sock name lxc/d78a9d7e97b4b375//var/lib/lxd/containers
            lxc 20160929093306.874 DEBUG    lxc_start - start.c:setup_signal_fd:290 - sigchild handler set
            lxc 20160929093306.874 DEBUG    lxc_console - console.c:lxc_console_peer_default:469 - no console peer
            lxc 20160929093306.874 INFO     lxc_start - start.c:lxc_init:489 - 'causal-elk' is initialized
            lxc 20160929093306.874 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 231072 range 65536
            lxc 20160929093306.874 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 231072 range 65536
            lxc 20160929093306.874 DEBUG    lxc_start - start.c:__lxc_start:1327 - Not dropping cap_sys_boot or watching utmp
            lxc 20160929093306.874 INFO     lxc_start - start.c:resolve_clone_flags:1014 - Cloning a new user namespace
            lxc 20160929093306.876 DEBUG    lxc_conf - conf.c:instantiate_veth:2615 - instantiated veth 'veth7VVTWJ/vethTK6IPX', index is '20'
            lxc 20160929093306.876 INFO     lxc_cgroup - cgroups/cgroup.c:cgroup_init:68 - cgroup driver cgroupfs-ng initing for causal-elk
            lxc 20160929093306.932 DEBUG    lxc_conf - conf.c:lxc_assign_network:3058 - move 'eth0' to '13891'
            lxc 20160929093306.932 NOTICE   lxc_start - start.c:do_start:778 - switching to gid/uid 0/0 in new user namespace
            lxc 20160929093306.932 DEBUG    lxc_conf - conf.c:setup_rootfs:1215 - mounted '/var/lib/lxd/containers/causal-elk/rootfs' on '/usr/lib/x86_64-linux-gnu/lxc'
            lxc 20160929093306.932 INFO     lxc_conf - conf.c:setup_utsname:843 - 'causal-elk' hostname has been setup
            lxc 20160929093306.948 DEBUG    lxc_conf - conf.c:setup_hw_addr:2146 - mac address '00:16:3e:0c:1c:42' on 'eth0' has been setup
            lxc 20160929093306.948 DEBUG    lxc_conf - conf.c:setup_netdev:2373 - 'eth0' has been setup
            lxc 20160929093306.948 INFO     lxc_conf - conf.c:setup_network:2394 - network has been setup
            lxc 20160929093306.948 INFO     lxc_conf - conf.c:mount_autodev:1072 - Mounting container /dev
            lxc 20160929093306.948 INFO     lxc_conf - conf.c:mount_autodev:1095 - Mounted tmpfs onto /usr/lib/x86_64-linux-gnu/lxc/dev
            lxc 20160929093306.948 INFO     lxc_conf - conf.c:mount_autodev:1113 - Mounted container /dev
            lxc 20160929093306.948 DEBUG    lxc_conf - conf.c:mount_entry:1657 - remounting /dev/fuse on /usr/lib/x86_64-linux-gnu/lxc/dev/fuse to respect bind or remount options
            lxc 20160929093306.948 DEBUG    lxc_conf - conf.c:mount_entry:1672 - (at remount) flags for /dev/fuse was 4096, required extra flags are 0
            lxc 20160929093306.948 DEBUG    lxc_conf - conf.c:mount_entry:1681 - mountflags already was 4096, skipping remount
            lxc 20160929093306.948 DEBUG    lxc_conf - conf.c:mount_entry:1707 - mounted '/dev/fuse' on '/usr/lib/x86_64-linux-gnu/lxc/dev/fuse', type 'none'
            lxc 20160929093306.948 DEBUG    lxc_conf - conf.c:mount_entry:1657 - remounting /dev/net/tun on /usr/lib/x86_64-linux-gnu/lxc/dev/net/tun to respect bind or remount options
            lxc 20160929093306.948 DEBUG    lxc_conf - conf.c:mount_entry:1672 - (at remount) flags for /dev/net/tun was 4096, required extra flags are 0
            lxc 20160929093306.948 DEBUG    lxc_conf - conf.c:mount_entry:1681 - mountflags already was 4096, skipping remount
            lxc 20160929093306.948 DEBUG    lxc_conf - conf.c:mount_entry:1707 - mounted '/dev/net/tun' on '/usr/lib/x86_64-linux-gnu/lxc/dev/net/tun', type 'none'
            lxc 20160929093306.948 DEBUG    lxc_conf - conf.c:mount_entry:1657 - remounting /proc/sys/fs/binfmt_misc on /usr/lib/x86_64-linux-gnu/lxc/proc/sys/fs/binfmt_misc to respect bind or remount options
            lxc 20160929093306.948 DEBUG    lxc_conf - conf.c:mount_entry:1672 - (at remount) flags for /proc/sys/fs/binfmt_misc was 4110, required extra flags are 14
            lxc 20160929093306.948 DEBUG    lxc_conf - conf.c:mount_entry:1707 - mounted '/proc/sys/fs/binfmt_misc' on '/usr/lib/x86_64-linux-gnu/lxc/proc/sys/fs/binfmt_misc', type 'none'
            lxc 20160929093306.948 DEBUG    lxc_conf - conf.c:mount_entry:1657 - remounting /sys/firmware/efi/efivars on /usr/lib/x86_64-linux-gnu/lxc/sys/firmware/efi/efivars to respect bind or remount options
            lxc 20160929093306.948 DEBUG    lxc_conf - conf.c:mount_entry:1672 - (at remount) flags for /sys/firmware/efi/efivars was 4096, required extra flags are 0
            lxc 20160929093306.948 DEBUG    lxc_conf - conf.c:mount_entry:1681 - mountflags already was 20480, skipping remount
            lxc 20160929093306.948 DEBUG    lxc_conf - conf.c:mount_entry:1707 - mounted '/sys/firmware/efi/efivars' on '/usr/lib/x86_64-linux-gnu/lxc/sys/firmware/efi/efivars', type 'none'
            lxc 20160929093306.948 DEBUG    lxc_conf - conf.c:mount_entry:1657 - remounting /sys/fs/fuse/connections on /usr/lib/x86_64-linux-gnu/lxc/sys/fs/fuse/connections to respect bind or remount options
            lxc 20160929093306.948 DEBUG    lxc_conf - conf.c:mount_entry:1672 - (at remount) flags for /sys/fs/fuse/connections was 4096, required extra flags are 0
            lxc 20160929093306.948 DEBUG    lxc_conf - conf.c:mount_entry:1681 - mountflags already was 20480, skipping remount
            lxc 20160929093306.948 DEBUG    lxc_conf - conf.c:mount_entry:1707 - mounted '/sys/fs/fuse/connections' on '/usr/lib/x86_64-linux-gnu/lxc/sys/fs/fuse/connections', type 'none'
            lxc 20160929093306.948 DEBUG    lxc_conf - conf.c:mount_entry:1657 - remounting /sys/fs/pstore on /usr/lib/x86_64-linux-gnu/lxc/sys/fs/pstore to respect bind or remount options
            lxc 20160929093306.948 DEBUG    lxc_conf - conf.c:mount_entry:1672 - (at remount) flags for /sys/fs/pstore was 4096, required extra flags are 0
            lxc 20160929093306.948 DEBUG    lxc_conf - conf.c:mount_entry:1681 - mountflags already was 20480, skipping remount
            lxc 20160929093306.948 DEBUG    lxc_conf - conf.c:mount_entry:1707 - mounted '/sys/fs/pstore' on '/usr/lib/x86_64-linux-gnu/lxc/sys/fs/pstore', type 'none'
            lxc 20160929093306.949 DEBUG    lxc_conf - conf.c:mount_entry:1657 - remounting /sys/kernel/debug on /usr/lib/x86_64-linux-gnu/lxc/sys/kernel/debug to respect bind or remount options
            lxc 20160929093306.949 DEBUG    lxc_conf - conf.c:mount_entry:1672 - (at remount) flags for /sys/kernel/debug was 4096, required extra flags are 0
            lxc 20160929093306.949 DEBUG    lxc_conf - conf.c:mount_entry:1681 - mountflags already was 20480, skipping remount
            lxc 20160929093306.949 DEBUG    lxc_conf - conf.c:mount_entry:1707 - mounted '/sys/kernel/debug' on '/usr/lib/x86_64-linux-gnu/lxc/sys/kernel/debug', type 'none'
            lxc 20160929093306.949 DEBUG    lxc_conf - conf.c:mount_entry:1657 - remounting /sys/kernel/security on /usr/lib/x86_64-linux-gnu/lxc/sys/kernel/security to respect bind or remount options
            lxc 20160929093306.949 DEBUG    lxc_conf - conf.c:mount_entry:1672 - (at remount) flags for /sys/kernel/security was 4096, required extra flags are 0
            lxc 20160929093306.949 DEBUG    lxc_conf - conf.c:mount_entry:1681 - mountflags already was 20480, skipping remount
            lxc 20160929093306.949 DEBUG    lxc_conf - conf.c:mount_entry:1707 - mounted '/sys/kernel/security' on '/usr/lib/x86_64-linux-gnu/lxc/sys/kernel/security', type 'none'
            lxc 20160929093306.949 DEBUG    lxc_conf - conf.c:mount_entry:1657 - remounting /var/lib/lxd/devlxd on /usr/lib/x86_64-linux-gnu/lxc/dev/lxd to respect bind or remount options
            lxc 20160929093306.949 DEBUG    lxc_conf - conf.c:mount_entry:1672 - (at remount) flags for /var/lib/lxd/devlxd was 4096, required extra flags are 0
            lxc 20160929093306.949 DEBUG    lxc_conf - conf.c:mount_entry:1681 - mountflags already was 4096, skipping remount
            lxc 20160929093306.949 DEBUG    lxc_conf - conf.c:mount_entry:1707 - mounted '/var/lib/lxd/devlxd' on '/usr/lib/x86_64-linux-gnu/lxc/dev/lxd', type 'none'
            lxc 20160929093306.949 DEBUG    lxc_conf - conf.c:mount_entry:1657 - remounting /var/lib/lxd/shmounts/causal-elk on /usr/lib/x86_64-linux-gnu/lxc/dev/.lxd-mounts to respect bind or remount options
            lxc 20160929093306.949 DEBUG    lxc_conf - conf.c:mount_entry:1672 - (at remount) flags for /var/lib/lxd/shmounts/causal-elk was 4096, required extra flags are 0
            lxc 20160929093306.949 DEBUG    lxc_conf - conf.c:mount_entry:1681 - mountflags already was 4096, skipping remount
            lxc 20160929093306.949 DEBUG    lxc_conf - conf.c:mount_entry:1707 - mounted '/var/lib/lxd/shmounts/causal-elk' on '/usr/lib/x86_64-linux-gnu/lxc/dev/.lxd-mounts', type 'none'
            lxc 20160929093306.949 INFO     lxc_conf - conf.c:mount_file_entries:1927 - mount points have been setup
            lxc 20160929093306.949 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/share/lxcfs/lxc.mount.hook' for container 'causal-elk', config section 'lxc'
            lxc 20160929093306.986 INFO     lxc_conf - conf.c:fill_autodev:1141 - Creating initial consoles under container /dev
            lxc 20160929093306.986 INFO     lxc_conf - conf.c:fill_autodev:1152 - Populating container /dev
            lxc 20160929093306.986 INFO     lxc_conf - conf.c:fill_autodev:1189 - Populated container /dev
            lxc 20160929093306.986 INFO     lxc_conf - conf.c:setup_dev_console:1437 - console has been setup
            lxc 20160929093306.986 INFO     lxc_utils - utils.c:mount_proc_if_needed:1726 - I am 1, /proc/self points to '1'
            lxc 20160929013307.004 DEBUG    lxc_conf - conf.c:setup_rootfs_pivot_root:1050 - pivot_root syscall to '/usr/lib/x86_64-linux-gnu/lxc' successful
            lxc 20160929013307.004 INFO     lxc_conf - conf.c:setup_tty:995 - 0 tty(s) has been setup
            lxc 20160929013307.004 INFO     lxc_conf - conf.c:setup_personality:1393 - set personality to '0x0'
            lxc 20160929013307.004 DEBUG    lxc_conf - conf.c:setup_caps:2057 - drop capability 'mac_admin' (33)
            lxc 20160929013307.004 DEBUG    lxc_conf - conf.c:setup_caps:2057 - drop capability 'mac_override' (32)
            lxc 20160929013307.004 DEBUG    lxc_conf - conf.c:setup_caps:2057 - drop capability 'sys_time' (25)
            lxc 20160929013307.004 DEBUG    lxc_conf - conf.c:setup_caps:2057 - drop capability 'sys_module' (16)
            lxc 20160929013307.004 DEBUG    lxc_conf - conf.c:setup_caps:2057 - drop capability 'sys_rawio' (17)
            lxc 20160929013307.004 DEBUG    lxc_conf - conf.c:setup_caps:2066 - capabilities have been setup
            lxc 20160929013307.004 NOTICE   lxc_conf - conf.c:lxc_setup:3850 - 'causal-elk' is setup.
            lxc 20160929013307.004 INFO     lxc_apparmor - lsm/apparmor.c:apparmor_process_label_set:238 - changed apparmor profile to lxd-causal-elk_</var/lib/lxd>
            lxc 20160929013307.005 NOTICE   lxc_start - start.c:start:1436 - exec'ing '/sbin/init'
            lxc 20160929013307.005 ERROR    lxc_start - start.c:start:1439 - No such file or directory - failed to exec /sbin/init
            lxc 20160929093307.005 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 5)
            lxc 20160929093307.005 ERROR    lxc_start - start.c:__lxc_start:1354 - failed to spawn 'causal-elk'
            lxc 20160929093307.005 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/share/lxcfs/lxc.reboot.hook' for container 'causal-elk', config section 'lxc'
            lxc 20160929093307.514 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/bin/lxd callhook /var/lib/lxd 36 stop' for container 'causal-elk', config section 'lxc'
            lxc 20160929093307.523 ERROR    lxc_conf - conf.c:run_buffer:347 - Script exited with status 1
            lxc 20160929093307.523 ERROR    lxc_start - start.c:lxc_fini:555 - failed to run post-stop hooks for container 'causal-elk'.
            lxc 20160929093307.523 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - command get_cgroup failed to receive response
            lxc 20160929093307.523 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - command get_cgroup failed to receive response
            lxc 20160929093322.678 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 231072 range 65536
            lxc 20160929093322.678 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 231072 range 65536
            lxc 20160929093403.389 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 231072 range 65536
            lxc 20160929093403.389 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 231072 range 65536
            lxc 20160929093403.393 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 231072 range 65536
            lxc 20160929093403.393 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 231072 range 65536
```

I don't know what happens, or it is my operation fault,thanks.

**Comment by stgraber** [comment] 2016-09-29 02:26
Please include all the information requested in the bug reporting template. Especially important in this case is the output of "lxc info" (without any argument).

**Comment by taozongwang** [comment] 2016-09-29 04:45
this is lxc info 
```
$ lxc info causal-elk 
Name: causal-elk
Architecture: x86_64
Created: 2016/09/28 09:44 UTC
Status: Stopped
Type: persistent
Profiles: default
```
the image is my Integrated image,which is my configrution.
metadata.yaml
```
$ cat metadata.yaml 
architecture: "x86_64"
creation_date: 1458040203
properties:
    architecture: "x86_64"
    description: "Ubuntu 14.04 LTS server (20160809.1)"
    os: "ubuntu"
    release: "trusty"
templates:
    /var/lib/cloud/seed/nocloud-net/meta-data:
        when:
            - create
            - copy
        template: cloud-init-meta.tpl
    /var/lib/cloud/seed/nocloud-net/user-data:
        when:
            - create
            - copy
        template: cloud-init-user.tpl
        properties:
            default: |
                #cloud-config
                {}
    /var/lib/cloud/seed/nocloud-net/vendor-data:
        when:
            - create
            - copy
        template: cloud-init-vendor.tpl
        properties:
            default: |
                #cloud-config
                {}
    /etc/network/interfaces.d/eth0.cfg:
        when:
            - create
        template: interfaces.tpl
    /etc/init/console.override:
        when:
            - create
        template: upstart-override.tpl
    /etc/init/tty1.override:
        when:
            - create
        template: upstart-override.tpl
    /etc/init/tty2.override:
        when:
            - create
        template: upstart-override.tpl
    /etc/init/tty3.override:
        when:
            - create
        template: upstart-override.tpl
    /etc/init/tty4.override:
        when:
            - create
        template: upstart-override.tpl
```

this is template directory,sorry,it copyed by a running lxd container, so like other running containers, and the `rootfs/` comes from the running container and tared by myself`tar ...`, maybe it is my fault that is a wrong way to import  an iamge.Thanks

**Comment by stgraber** [comment] 2016-10-09 00:23
Closing this issue as the reporter is repeatedly not providing the required information.

The best guess for the error is an old version of LXD that's got the old zfs backend code, combined with the random unmounts caused by ZFS. LXD 2.0.4 or higher would fix this.

**Closed by stgraber** 2016-10-09 00:23 UTC
Labels: Incomplete

**Comment by taozongwang** [comment] 2016-10-15 16:16
Sorry, this is my fault, because when I use `tar` starting with a directory `rootfs`, but  `/`(/bin /etc ...) , so ... ,Thank a lot. @stgraber
