### ISSUE TITLE
Howto migrate to another storage

### ISSUE THREAD

**Issue by nlienard** [lxc/lxd#4444] opened 2018-04-12 16:16 UTC
Hi,
I've 1 container using default LXD storage.
I've a new server with default LXD Storage and another storage called LXD-ZDATA
Now, i want to migrate the container from SERVER1 (Storage LXD) to SERVER 2 (Storage LXD-ZDATA).
How can i achieve this ?
By default, when i migrate, the container goes to SERVER2 LXD Storage, i don't know how to specify the Storage.
Thanks

SERVER 1
```
root@inxovh-hy001 (node1):~# lxc storage list
+----------+-------------+--------+-----------+---------+
|   NAME   | DESCRIPTION | DRIVER |  SOURCE   | USED BY |
+----------+-------------+--------+-----------+---------+
| default  |             | zfs    | zdata/lxd | 34      |
+----------+-------------+--------+-----------+---------+
| lxd-pool |             | ceph   | lxd-pool  | 2       |
+----------+-------------+--------+-----------+---------+
```
SERVER2:
```
root@atxscw-hy006:~# lxc storage list
+-----------+-------------+--------+----------------------------+---------+
|   NAME    | DESCRIPTION | DRIVER |           SOURCE           | USED BY |
+-----------+-------------+--------+----------------------------+---------+
| lxd       |             | zfs    | /var/lib/lxd/disks/lxd.img | 7       |
+-----------+-------------+--------+----------------------------+---------+
| lxd-zdata |             | zfs    | zdata/lxd                  | 0       |
+-----------+-------------+--------+----------------------------+---------+
```

Should i change the default profile ?

```
root@atxscw-hy006:~# lxc profile show default
config:
  raw.lxc: lxc.aa_allow_incomplete=1
description: Default LXD profile
devices:
  root:
    path: /
    pool: lxd <===== to change ????
    size: 10GB
    type: disk
name: default
```

got an error while trying to change it

```
root@atxscw-hy006:~# lxc profile edit default
Config parsing error: At least one container relies on this profile's root disk device.
Press enter to open the editor again
```

I found this way but need to migrate at first the container 

```
root@atxscw-hy006:~# lxc stop test1
root@atxscw-hy006:~# lxc publish -f test1 --alias test1
Container published with fingerprint: a52f8be900912f2917567a6aadcb4121b60534e3746cc68cb03b279ead711df7
root@atxscw-hy006:~# lxc delete test1
root@atxscw-hy006:~# lxc init test1 test1 -s lxd-zdata
Creating test1
The container you are starting doesn't have any network attached to it.
  To create a new network, use: lxc network create
  To attach a network to a container, use: lxc network attach
root@atxscw-hy006:~# lxc start test1
root@atxscw-hy006:~# zfs list |grep test1
zdata/lxd/containers/test1                                                         5.12M   134G   599M  /var/lib/lxd/storage-pools/lxd-zdata/containers/test1
root@atxscw-hy006:~#
```
I lost network when doing this.

i get it back with : 

```
root@atxscw-hy006:~# lxc network attach lxdbr0 inxscw-xmpp002  eth1
root@atxscw-hy006:~#
```

**Comment by brauner** [comment] 2018-04-12 18:16
Hm, the easiest way would be to add a new flag `-s/--storage` to `lxc copy` which would let you specify a pool on the target server.

**Comment by nlienard** [comment] 2018-04-12 18:37
this flag ```-s/--storage``` would be also good for ```lxc move``` no ?

**Comment by brauner** [comment] 2018-04-12 19:57
`copy` and `move` are covered by the same codepath in the `lxc *` tools so that's happening automatically.

We have logic in  `lxd/containers_post.go` that figures out a suitable storage pool based on the profile devices and local devices of the container. That is to say one can send the container even if it has a pool specified in its profile devices or root devices that does not exist on the target. We need to keep this logic for backwards compatibility. This also means that we can't simply override the value in the profile and local devices since we would want to report back to the user when the pool that they targeted failed. But we can't because that would break the valid case of not specifying a pool or just not removing an invalid pool from the profile and local devices. Also, we likely want to have API users have the same benefit.

So, we should add an API extension `storage_api_migration_pool_target` and add a `Pool string` field to `shared/api/container.go/ContainersPost` and to `client/interfaces.go:{ContainerCopyArgs,ContainerSnapshotCopyArgs}` this would let us easily communicate which pool to target even for API-only users.
//@stgraber

**Comment by stgraber** [comment] 2018-04-12 21:31
@brauner at the API level, we can override Devices during copy/move, so adding `-s` to lxc copy/move should be possible today by just having them add a container-specifc disk with path=/, without requiring any API changes.

@nlienard for now, I think your best bet is to do something like this on your target server:
```
lxc profile create storage-zdata
lxc profile device add storage-zdata root disk path=/ pool=lxd-zdata
```

And then pass `-p default -p storage-zdata` to `lxc copy`. That should result in the new container using the lxd-zdata pool and would be somewhat similar to what a `-s` option would do (except we wouldn't need a profile to hold that device, it'd be directly attached to the container).

**Comment by nlienard** [comment] 2018-04-13 19:07
Ok i did it on SERVER2 (target)

```
root@atxscw-hy006:~# lxc profile show storage-zfs
config: {}
description: ""
devices:
  root:
    path: /
    pool: lxd-zdata
    size: 10GB
    type: disk
name: storage-zfs
used_by: []
```

so, now, from SERVER 1 (source:

```
lxc copy inxovh-dun001 node16: -p default -p storage-zfs
```
Right ?

**Comment by stgraber** [comment] 2018-04-14 17:45
Oh, it's a bug we fixed recently I think, the issue is duplicate profiles in container config.

My example was bad, you should just use:

    lxc copy inxovh-dun001 node16: -p storage-zfs

As `-p` doesn't override the profiles but adds to the existing list, so passing `default` isn't needed.

**Comment by nlienard** [comment] 2018-04-14 17:54
excellent, it worked:

```
root@inxovh-hy001 (node1):~# lxc copy inxovh-dun001 node16: -p storage-zfs
root@inxovh-hy001 (node1):~#
```

On target:

```
root@atxscw-hy006:~# lxc config show inxovh-dun001
architecture: x86_64
config:
  volatile.apply_quota: 10GB
  volatile.apply_template: copy
  volatile.base_image: b1b87ba5fde28e52d0ba8dec4717da54a088a78e9a4f75f0f386ce6796a899a7
  volatile.eth0.hwaddr: 00:16:3e:b6:02:2d
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":493216,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":493216,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":165536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br_lan10
    type: nic
ephemeral: false
profiles:
- default
- storage-zfs
stateful: false
description: ""
```

and i can see it on the new zfs pool:

```
root@atxscw-hy006:~# zfs list |grep dun
zdata/lxd/containers/inxovh-dun001                                                          478M  9.53G   478M  /var/lib/lxd/storage-pools/lxd-zdata/containers/inxovh-dun001
```

Thanks !!

**Comment by nlienard** [comment] 2018-04-14 18:03
how can i do the same locally to migrate my container running on zfs file into zfs datavol ?

i tried

```
root@atxscw-hy006:~# lxc copy nliscw-www001 nliscw-www002 -p storage-zfs
root@atxscw-hy006:~#
```

But www002 is also on zfs file instead of zdata/lxd (lxd-zdata)

**Comment by nlienard** [comment] 2018-04-14 18:05
ok i remove in the config of the container the part about root

now got this error:

```
root@atxscw-hy006:~# lxc copy nliscw-www001 nliscw-www002 -p storage-zfs
error: copying containers between different storage pools is not implemented
```

**Comment by stgraber** [comment] 2018-04-14 21:14
Right, that's #3315.

So looks like this got you sorted for the remote copy case.
I'll keep the issue open until I've confirmed that the error you hit is the same I already fixed a few days ago, if not, I'll use this issue to track fixing this error.

**Comment by nlienard** [comment] 2018-04-16 11:24
After a copy with new storage, i got also this log, should i worry ?

```
Apr 16 11:17:59 atxscw-hy006 lxd[5234]: lvl=warn msg="Unable to update backup.yaml at this time." name=eurovh-dev001 t=2018-04-16T11:17:59+0000
Apr 16 11:17:59 atxscw-hy006 lxd[5234]: lvl=warn msg="Unable to update backup.yaml at this time." name=eurovh-dev001 t=2018-04-16T11:17:59+0000
Apr 16 11:23:31 atxscw-hy006 kernel: [1031004.173896] audit: type=1400 audit(1523877811.641:28): apparmor="STATUS" operation="profile_load" name="lxd-eurovh-dev001_</var/lib/lxd>" pid=15457 comm="apparmor_parser"
Apr 16 11:23:31 atxscw-hy006 systemd-udevd[15462]: Could not generate persistent MAC address for veth9BKN7R: No such file or directory
Apr 16 11:23:31 atxscw-hy006 kernel: [1031004.209236] device vethWHYN9K entered promiscuous mode
Apr 16 11:23:31 atxscw-hy006 kernel: [1031004.209519] IPv6: ADDRCONF(NETDEV_UP): vethWHYN9K: link is not ready
Apr 16 11:23:31 atxscw-hy006 kernel: [1031004.209542] br_lan10: port 7(vethWHYN9K) entered forwarding state
Apr 16 11:23:31 atxscw-hy006 kernel: [1031004.209555] br_lan10: port 7(vethWHYN9K) entered forwarding state
Apr 16 11:23:31 atxscw-hy006 kernel: [1031004.210269] br_lan10: port 7(vethWHYN9K) entered disabled state
Apr 16 11:23:31 atxscw-hy006 kernel: [1031004.387397] eth0: renamed from veth9BKN7R
Apr 16 11:23:31 atxscw-hy006 kernel: [1031004.451541] IPv6: ADDRCONF(NETDEV_CHANGE): vethWHYN9K: link becomes ready
Apr 16 11:23:31 atxscw-hy006 kernel: [1031004.451735] br_lan10: port 7(vethWHYN9K) entered forwarding state
Apr 16 11:23:31 atxscw-hy006 kernel: [1031004.451754] br_lan10: port 7(vethWHYN9K) entered forwarding state
Apr 16 11:23:32 atxscw-hy006 ntpd[25003]: bind(40) AF_INET6 fe80::fce3:8aff:fec5:6d48%67#123 flags 0x11 failed: Cannot assign requested address
Apr 16 11:23:32 atxscw-hy006 ntpd[25003]: unable to create socket on vethWHYN9K (59) for fe80::fce3:8aff:fec5:6d48%67#123
Apr 16 11:23:32 atxscw-hy006 ntpd[25003]: failed to init interface for address fe80::fce3:8aff:fec5:6d48%67
Apr 16 11:23:34 atxscw-hy006 ntpd[25003]: Listen normally on 60 vethWHYN9K [fe80::fce3:8aff:fec5:6d48%67]:123
Apr 16 11:23:34 atxscw-hy006 ntpd[25003]: new interface(s) found: waking up resolver
Apr 16 11:23:41 atxscw-hy006 lxcfs[9299]: bindings.c: 2080: send_creds: Failed at sendmsg: No such process.
Apr 16 11:23:43 atxscw-hy006 lxcfs[9299]: bindings.c: 2056: send_creds: Error getting reply from server over socketpair.
Apr 16 11:23:43 atxscw-hy006 lxcfs[9299]: bindings.c: 2126: recv_creds: Timed out waiting for scm_cred: Success
Apr 16 11:23:43 atxscw-hy006 lxcfs[9299]: bindings.c: 2318: do_read_pids: Failed to ask child to exit: No such process.
Apr 16 11:23:46 atxscw-hy006 kernel: [1031019.475488] br_lan10: port 7(vethWHYN9K) entered forwarding state
```

thks

**Comment by brauner** [comment] 2018-04-16 12:08
No, that's nothing to worry about.

**Comment by stgraber** [comment] 2018-04-16 17:55
```
stgraber@castiana:~/data/code/lxc/lxd (stgraber/master)$ lxc copy distrobuilder s-sateda: --mode=push -p default
Error: Duplicate profile found in request
```

That's when copying to a LXD daemon running the current code, so that confirms that this particular error is now properly handled, closing.

**Closed by stgraber** 2018-04-16 17:55 UTC
