### ISSUE TITLE
Issues with custom volume copies

### ISSUE THREAD

**Issue by Spunge** [lxc/lxd#5586] opened 2019-03-21 10:14 UTC
# Required information

```
root@host-0001:~# uname -a
Linux host-0001 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

root@host-0001:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

root@host-0001:~# lxc info
config:
  cluster.https_address: 10.254.0.4:8443
  core.https_address: 10.254.0.4:8443
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 10.254.0.4:8443
  architectures:
  - x86_64
  - i686
  certificate: -
  certificate_fingerprint: de16ae4695a119aa59b84a9cb75a0b1026236cebb7276860e3cd35199a1a0d79
  driver: lxc
  driver_version: 3.1.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-46-generic
  server: lxd
  server_pid: 4850
  server_version: "3.11"
  storage: zfs | ceph
  storage_version: 0.7.5-1ubuntu16.4 | ceph version 10.2.11 (e4b061b47f07f583c92a050d9e84b1813a35671e)
  server_clustered: true
  server_name: host-0001
  project: default
```

# Issue description
I can't seem to copy ceph volumes that have snapshots, and i'm unable to copy ceph volume snapshots to new volumes.

# Steps to reproduce

 1. Create volume on ceph pool 
`lxc storage volume create pool0 volume0`
 2. Snapshot the volume 
`lxc storage volume snapshot pool0 volume0 snap0`
 3. Try to copy the volume 
`lxc storage volume copy pool0/volume0 pool0/volume1`, this fails.
 4. Try to copy the snapshot to new volume 
`lxc storage volume copy pool0/volume0/snap0 pool0/volume1`, this fails.
 
Copying the volume without snapshot succeeds `lxc storage volume copy pool0/volume0 pool0/volume1 --volume-only`

# Information to attach
Both of the command in 3 & 4 give the following output: 
```
Error: Failed to run: rbd --id admin --cluster ceph --pool lxd snap create --snap 666d5602-a3c1-4a75-a2a1-b7f7102a1360 custom_volume0/snap0: rbd: error opening pool custom_volume0: (2) No such file or directory                                                        
```

**Comment by stgraber** [comment] 2019-03-21 16:53
Thanks, that should be reasonably easy to reproduce and track down.

**Comment by stgraber** [comment] 2019-03-22 23:10
Running into other problems when creating the snapshot, my test systems appear to just hang during the creation, trying to track down what's going on.

**Comment by stgraber** [comment] 2019-03-26 18:17
Fixed that hang issue now, looking at the original problem now.

**Comment by stgraber** [comment] 2019-03-26 18:18
And reproduce the issue here.

**Comment by stgraber** [comment] 2019-03-26 21:53
Okay, so I just spent the past 3 hours reading through all that custom volume code, especially the CEPH implementation of it and there are a lot of issues with it...

I've sent a first pull request which fixes:
 - Complete host hang during copy if volume isn't currently in use
 - Leak of rbd devices on copy
 - Failure to copy custom volume snapshot into new custom volume

But I suspect this may just be the tip of the iceberg as far as what needs fixing.

## CEPH copy of a custom volume with snapshots is broken
Looking at the copy of a custom volume with snapshots into a new custom volume while retaining snapshots, I noticed that we just don't have any code which does that for CEPH. What we need is logic to detect existing snapshots, create an empty volume and copy snapshot one after the other, re-creating the snapshots in order. That's a major pain with CEPH, but something that @brauner did for containers and that approach appears to be working for those.

## There is no code for cross-pool copy from CEPH to something else
In the case where the source and target pools aren't the same, no CEPH action is performed, instead we go straight into mounting the CEPH volume, which won't exist, causing a failure.

## Copy with snapshots in other storage backends is broken too
Looking at ZFS, doing a local copy of a custom volume with snapshots, succeeded, but then additional storage volumes got created for no reason and in a way that aren't tracked or deletable.

Example is `blah` custom volume with `snap0` and `snap1` as snapshots, ZFS datasets:
 - blah
 - blah@snap0
 - blah@snap1

The copy `blah1` does properly get `snap0` and `snap1` snapshots but also gets additional datasets:
 - blah1
 - blah1@snap0
 - blah1@snap1
 - blah1/snap0
 - blah1/snap1

Those two additional datasets aren't needed and are caused by the StorageVolumeCopy function being called for every snapshot. For dir and btrfs, this happens to work okay, for CEPH and LVM, this fails pretty badly and for ZFS we get those weird datasets...

## Clearly missing tests to catch all of this
Looks like we at the very least need:
 - Test to copy a snapshot of a custom volume into its own new custom volume
 - Test to copy a custom volume that has snapshots into a new custom volume (and confirm that snapshots are still there)
 - Same two tests but between two storage pools

## Suggestions
Similarly to containers, I suspect we want to have StoragePoolVolumeCopy handle the VolumeOnly bit itself. So this needs to be passed to it so it can then deal with:
 - Single volume copy (no snapshots)
 - Volume-only copy of a volume with snapshots (same as previous)
 - Volume copy with snapshots
 - Snapshot of a volume copied to new volume

With it dealing with both the within-pool and cross-pool case for all of those (though cross-pool is likely to be somewhat shared logic based on rsync).

The database entries should still be handled by the API handler, but we should only ever have a single call to StoragePoolVolumeCopy per copy.

**Comment by stgraber** [comment] 2019-03-26 21:53
@monstermunchkin this is your new priority, we really need all of this cleaned up and tested for LXD 3.12 as the current code will at best give confusing errors, at worst silently skip copying data potentially causing our users data loss.

**Comment by stgraber** [comment] 2019-03-26 22:52
@monstermunchkin I have vm02 setup with a CEPH storage pool if it helps testing your fixes.
 - Access by `ssh ubuntu@canonical-lxd.stgraber.org` and then `ssh vm02.maas.mtl`
 - LXD is installed through the snap, replace binary at /var/snap/lxd/common/lxd.debug and reload with `systemctl reload snap.lxd.daemon`

**Comment by monstermunchkin** [comment] 2019-04-01 17:06
**Quick update**

The tests are still missing but so far the following items should be fixed:
- CEPH: cross-pool volume copy and volume copy with snapshots
- ZFS: volume copy with snapshots

The volume copy code now uses a single call for both the actual volume and the snapshots as suggested. All volume copy code is being changed to look similar to the container copy code which works well even with snapshots.

Currently working on fixing LVM. There also was a bug in the LV naming which made it impossible to figure out which LVs are actual volumes and which are snapshots. That's been fixed as well.

**Closed** 2019-04-04 23:15 UTC
Labels: Bug
