### ISSUE TITLE
Possible LXD-5.7 dnsmasq management bug - containers die over time + container restart fail

### ISSUE THREAD

**Issue by davidfavor** [lxc/lxd#11111] opened 2022-11-12 15:41 UTC
# Required information

 * Distribution: Ubuntu
 * Distribution version: Focal
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-131-generic
   * LXC version: 5.7-c62733b
   * LXD version: 5.7-c62733b
   * Storage backend in use: ext4

# Issue description

Containers die over time. Container restart fail.

# Steps to reproduce

 1. Run LXD
 2. No action taken. Containers just randomly die. No rhyme or reason. 
 3. Nothing works to bring containers back online.

# Information to attach

No useful information. Nothing in per container logs. Nothing produced by **lxc start --debug --verbose CNAME** of any use.

Here's an example...

```
net13 # lxc start net13-template-focal 
Error: Failed start validation for device "eno1": Instance DNS name "net13-template-focal" already used on network
Try `lxc info --show-log net13-template-focal` for more info
```
```
net13 # lxc info --show-log net13-template-focal
Name: net13-template-focal
Status: STOPPED
Type: container
Architecture: x86_64
Created: 2022/02/08 22:21 UTC
Last Used: 2022/07/02 14:33 UTC

Log:
```
Rebooting has no effect.

The problem seems to be dnsmasq has cruft stuck in it's craw related to cached container + interface relationships.

The dir /var/snap/lxd/common/lxd/networks/lxdbr0/dnsmasq.hosts seems to container these relationships.

Destroying all files in this directory + reboot also has no effect.

Looking back through snap update history, the problem seemed to have started around the recent snap auto update of LXD.

This problem effects all machines I manage. When it starts, the fix is fairly simple.
```
sudo snap refresh --channel=5.6 lxd
```
Since all machines + containers seem involved... and the reversion fixes the problem instantly...

Seems like this might be some sort of LXD-5.7-c62733b bug.

Once the LXD-5.6 reversion completes, some containers automagically start themselves (likely where lxc start was done recently).

Other containers that have been dead for a while require a manual start.

**Comment by tomponline** [comment] 2022-11-12 15:42
This is a duplicate of https://discuss.linuxcontainers.org/t/error-failed-start-validation-for-device-enp3s0f0-instance-dns-name-net17-nicole-munoz-marketing-already-used-on-network/15586 please could you reply to my question there.

**Closed by tomponline** 2022-11-12 15:42 UTC

**Comment by davidfavor** [comment] 2022-11-13 15:14
Replied to your question.

And saying it's intentional for LXD to kill off all containers, then have container start operations fail... seems... odd...
