### ISSUE TITLE
Error getting LVM logical volume list for storage pool "default"

### ISSUE THREAD

**Issue by curupira** [lxc/lxd#7431] opened 2020-05-26 07:24 UTC
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version:   5.4.0-31-generic
   * LXC version: 4.1
   * LXD version: 4.1
   * Storage backend in use:lvm

# Issue description

t=2020-05-26T09:07:30+0200 lvl=eror msg="Failed to start the daemon: Failed applying patch \"storage_lvm_skipactivation\": Error getting LVM logical volume list for storage pool \"default\": Failed to run: lvs --noheadings -o lv_name,lv_attr default: Volume group \"default\" not found\n  Cannot process volume group default" 

Happened on all servers running lxd 4.1 from snapsince yesterday snap refresh of lxd. The Servers running lxd 3 are still fine. lxd stopped working totally.

# Information to attach

 - [lvscan ] 

```
  ACTIVE            '/dev/lxc-virt-9/LXDThinPool' [<1022.00 GiB] inherit
  inactive          '/dev/lxc-virt-9/images_fc7562a3ac52534c657b26a56cd1ea35a673d687ca6161157d1c4a19a5de5f0a' [<9.32 GiB] inherit
  inactive          '/dev/lxc-virt-9/containers_guest3' [<9.32 GiB] inherit
  ACTIVE            '/dev/lxc-virt-9/containers_guest10' [<279.40 GiB] inherit
  inactive          '/dev/lxc-virt-9/containers_guest59' [<46.57 GiB] inherit
  ACTIVE            '/dev/lxc-virt-8/LXDThinPool' [<1022.00 GiB] inherit
  inactive          '/dev/lxc-virt-8/containers_guest24_restore' [18.00 GiB] inherit
  inactive          '/dev/lxc-virt-8/containers_guest24' [<18.63 GiB] inherit
  inactive          '/dev/lxc-virt-8/containers_guest43' [<9.32 GiB] inherit
  inactive          '/dev/lxc-virt-8/images_a432d50ad433e6d781982a50b2b72c5b88435ffae507ad2459959d498a39003e' [<9.32 GiB] inherit
```

 - [ less /var/snap/lxd/common/lxd/logs/lxd.log] 
```
t=2020-05-26T09:07:30+0200 lvl=info msg="LXD 4.1 is starting in normal mode" path=/var/snap/lxd/common/lxd
t=2020-05-26T09:07:30+0200 lvl=info msg="Kernel uid/gid map:" 
t=2020-05-26T09:07:30+0200 lvl=info msg=" - u 0 0 4294967295" 
t=2020-05-26T09:07:30+0200 lvl=info msg=" - g 0 0 4294967295" 
t=2020-05-26T09:07:30+0200 lvl=info msg="Configured LXD uid/gid map:" 
t=2020-05-26T09:07:30+0200 lvl=info msg=" - u 0 1000000 1000000000" 
t=2020-05-26T09:07:30+0200 lvl=info msg=" - g 0 1000000 1000000000" 
t=2020-05-26T09:07:30+0200 lvl=info msg="Kernel features:" 
t=2020-05-26T09:07:30+0200 lvl=info msg=" - netnsid-based network retrieval: yes" 
t=2020-05-26T09:07:30+0200 lvl=info msg=" - uevent injection: yes" 
t=2020-05-26T09:07:30+0200 lvl=info msg=" - seccomp listener: yes" 
t=2020-05-26T09:07:30+0200 lvl=info msg=" - seccomp listener continue syscalls: yes" 
t=2020-05-26T09:07:30+0200 lvl=info msg=" - unprivileged file capabilities: yes" 
t=2020-05-26T09:07:30+0200 lvl=info msg=" - cgroup layout: hybrid" 
t=2020-05-26T09:07:30+0200 lvl=warn msg=" - Couldn't find the CGroup blkio.weight, I/O weight limits will be ignored" 
t=2020-05-26T09:07:30+0200 lvl=warn msg=" - Couldn't find the CGroup memory swap accounting, swap limits will be ignored" 
t=2020-05-26T09:07:30+0200 lvl=info msg=" - shiftfs support: disabled" 
t=2020-05-26T09:07:30+0200 lvl=info msg="Initializing local database" 
t=2020-05-26T09:07:30+0200 lvl=info msg="Starting /dev/lxd handler:" 
t=2020-05-26T09:07:30+0200 lvl=info msg=" - binding devlxd socket" socket=/var/snap/lxd/common/lxd/devlxd/sock
t=2020-05-26T09:07:30+0200 lvl=info msg="REST API daemon:" 
t=2020-05-26T09:07:30+0200 lvl=info msg=" - binding Unix socket" socket=/var/snap/lxd/common/lxd/unix.socket
t=2020-05-26T09:07:30+0200 lvl=info msg="Initializing global database" 
t=2020-05-26T09:07:30+0200 lvl=info msg="Firewall loaded driver \"nftables\"" 
t=2020-05-26T09:07:30+0200 lvl=info msg="Initializing storage pools" 
t=2020-05-26T09:07:30+0200 lvl=info msg="Applying patch \"storage_lvm_skipactivation\"" 
t=2020-05-26T09:07:30+0200 lvl=eror msg="Failed to start the daemon: Failed applying patch \"storage_lvm_skipactivation\": Error getting LVM logical volume list for storage pool \"default\": Failed to run: lvs --noheadings -o lv_name,lv_attr default: Volume group \"default\" not found\n  Cannot process volume group default" 
t=2020-05-26T09:07:30+0200 lvl=info msg="Starting shutdown sequence" 
t=2020-05-26T09:07:30+0200 lvl=info msg="Closing the database" 
t=2020-05-26T09:07:30+0200 lvl=info msg="Stop database gateway" 
t=2020-05-26T09:07:30+0200 lvl=info msg="Stopping REST API handler:" 
t=2020-05-26T09:07:30+0200 lvl=info msg=" - closing socket" socket=/var/snap/lxd/common/lxd/unix.socket
t=2020-05-26T09:07:30+0200 lvl=info msg="Stopping /dev/lxd handler:" 
t=2020-05-26T09:07:30+0200 lvl=info msg=" - closing socket" socket=/var/snap/lxd/common/lxd/devlxd/sock
t=2020-05-26T09:07:30+0200 lvl=info msg="Unmounting temporary filesystems" 
t=2020-05-26T09:07:30+0200 lvl=info msg="Done unmounting temporary filesystems" 

```

 - [ systemctl status snap.lxd.daemon]

```
● snap.lxd.daemon.service - Service for snap application lxd.daemon
     Loaded: loaded (/etc/systemd/system/snap.lxd.daemon.service; static; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2020-05-26 09:07:31 CEST; 1s ago
TriggeredBy: ● snap.lxd.daemon.unix.socket
    Process: 9712 ExecStart=/usr/bin/snap run lxd.daemon (code=exited, status=1/FAILURE)
   Main PID: 9712 (code=exited, status=1/FAILURE)

May 26 09:07:31 virt-8 systemd[1]: snap.lxd.daemon.service: Scheduled restart job, restart counter is at 5.
May 26 09:07:31 virt-8 systemd[1]: Stopped Service for snap application lxd.daemon.
May 26 09:07:31 virt-8 systemd[1]: snap.lxd.daemon.service: Start request repeated too quickly.
May 26 09:07:31 virt-8 systemd[1]: snap.lxd.daemon.service: Failed with result 'exit-code'.
May 26 09:07:31 virt-8 systemd[1]: Failed to start Service for snap application lxd.daemon.

```

**Comment by tomponline** [comment] 2020-05-26 07:37
This is a duplicate of https://github.com/lxc/lxd/issues/7427 and has been fixed with https://github.com/lxc/lxd/commit/72e4c54e395b00af4b371bdc773dc82a465a38ea

**Closed by tomponline** 2020-05-26 07:37 UTC

**Comment by curupira** [comment] 2020-05-26 08:04
Thanks for fast response.
