### ISSUE TITLE
LVM storage problem - all container  stopped

### ISSUE THREAD

**Issue by esosan** [lxc/lxd#8904] opened 2021-06-17 06:18 UTC
# Required information

 * Distribution: ubuntu
 * Distribution version: 18.04.4
 * The output of "lxc info" or if that fails:
   * Kernel version:4.15.0-144-generic
   * LXC version: 4.15
   * LXD version: 4.15
   * Storage backend in use: LVM (xfs/no thinpool)

# Issue description

All Containers doesn't start anymore. Seems to be a LVM problem. But all PVS and VGS are present

```
Error: Failed preparing container for start: Failed to activate LVM logical volume "/dev/pool_0/containers_iceCast": Failed to run: lvchange --activate y --ignoreactivationskip /dev/pool_0/containers_iceCast: Volume group "pool_0" not found
  Cannot process volume group pool_0
```

**Comment by tomponline** [comment] 2021-06-17 08:15
Closing in place of https://discuss.linuxcontainers.org/t/lvm-storage-problem-all-container-stopped-and-doesnt-start-anymore/11358, support issues are better handled on the forum. Thanks.

**Comment by tomponline** [comment] 2021-06-17 09:23
Reopening as after discussion on https://discuss.linuxcontainers.org/t/lvm-storage-problem-all-container-stopped-and-doesnt-start-anymore/11358 it seems that enabling:

```
sudo snap set lxd lvm.external=true
sudo systemctl reload snap.lxd.daemon
``` 

Fixes the LVM issue, but it should not be required. Suggesting a core20 snap issue. 

Also related to https://github.com/lxc/lxd/issues/8905

**Comment by tomponline** [comment] 2021-06-17 09:55
@esosan please can you switch back to the snap's LVM tools using:

```


sudo snap set lxd lvm.external=false
sudo systemctl reload snap.lxd.daemon
```

And then check your back in a situation where the containers dont start with the error "Cannot process volume group pool_0"

Then can you run:

```
sudo nsenter --mount=/run/snapd/ns/lxd.mnt -- bash
LD_LIBRARY_PATH=/snap/lxd/current/lib/:/snap/lxd/current/lib/x86_64-linux-gnu/ /snap/lxd/current/bin/lvs
```

**Comment by esosan** [comment] 2021-06-17 09:58
`LD_LIBRARY_PATH=/snap/lxd/current/lib/:/snap/lxd/current/lib/x86_64-linux-gnu/ /snap/lxd/current/bin/lvs
  LV             VG Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  home           vg -wi-ao---- <19.53g                                                    
  lxc_pool00     vg -wi-ao----  60.00g                                                    
  lxc_pool01     vg -wi-ao----  20.00g                                                    
  lxc_poolOC00   vg -wi-ao---- 220.00g                                                    
  lxc_pooldata00 vg -wi-ao----  50.00g                                                    
  lxc_pooldata01 vg -wi-a-----  50.00g     `

**Comment by tomponline** [comment] 2021-06-17 10:02
Interesting, can you do the same but run `vgs` instead.

**Comment by esosan** [comment] 2021-06-17 10:03
bash: vgs: command not found

(when I return to lvm.external=false the containers continue to be RUNNING.)

**Comment by tomponline** [comment] 2021-06-17 10:04
I meant like this:

```
LD_LIBRARY_PATH=/snap/lxd/current/lib/:/snap/lxd/current/lib/x86_64-linux-gnu/ sudo --preserve-env=LD_LIBRARY_PATH nsenter --mount=/run/snapd/ns/lxd.mnt -- /snap/lxd/current/bin/vgs
```

**Comment by esosan** [comment] 2021-06-17 10:06
```
sudo nsenter --mount=/run/snapd/ns/lxd.mnt -- bash
root@olivia3:/# LD_LIBRARY_PATH=/snap/lxd/current/lib/:/snap/lxd/current/lib/x86_64-linux-gnu/ sudo --preserve-env=LD_LIBRARY_PATH nsenter --mount=/run/snapd/ns/lxd.mnt -- /snap/lxd/current/bin/vgs
sudo: unable to stat /etc/sudoers: No such file or directory
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin
```

**Comment by tomponline** [comment] 2021-06-17 10:07
OK looks your sudo isnt happy.

Try this:

```
sudo nsenter --mount=/run/snapd/ns/lxd.mnt -- bash
LD_LIBRARY_PATH=/snap/lxd/current/lib/:/snap/lxd/current/lib/x86_64-linux-gnu/ /snap/lxd/current/bin/vgs
```

**Comment by esosan** [comment] 2021-06-17 10:08
```
LD_LIBRARY_PATH=/snap/lxd/current/lib/:/snap/lxd/current/lib/x86_64-linux-gnu/ /snap/lxd/current/bin/vgs
  VG #PV #LV #SN Attr   VSize  VFree 
  vg   1   6   0 wz--n- <1.80t <1.39t
```

**Comment by tomponline** [comment] 2021-06-17 10:12
OK so there's the problem then, inside the snap, your pool_0 pool volume group isn't being detected.

I suspect this is due to a change in the lvm tooling in the core20 base snap that is for some reason not doing a scan of available pools when we run the lvs or vgs commands. We may need to look at modifying the command we run or use a custom config file inside the snap. For now using the external fix I suggested earlier will ensure LXD uses your host's tooling.

**Comment by esosan** [comment] 2021-06-17 10:16
ok, great. If you need further testing, I am of course available!

**Comment by stgraber** [comment] 2021-06-17 14:51
@esosan can you show the `lxc storage show NAME` output for your pool?

**Comment by tomponline** [comment] 2021-06-17 14:58
@stgraber its in the forum post:

```
lxc storage show pool0

config:
  lvm.use_thinpool: "false"
  lvm.vg_name: pool_0
  source: pool_0
  volatile.initial_source: pool_0
  volume.block.filesystem: xfs
  volume.size: "3221225472"
description: ""
name: pool0
driver: lvm
used_by:
- /1.0/instances/gdg
- /1.0/instances/git
- /1.0/instances/iceCast
- /1.0/instances/m-clamav
- /1.0/instances/m-clamavOLD
- /1.0/instances/m-dcc
- /1.0/instances/m-dcot
- /1.0/instances/m-pfix
- /1.0/instances/m-spam18
- /1.0/instances/mysql
- /1.0/instances/named
- /1.0/instances/owncloud
- /1.0/instances/rCube
- /1.0/instances/rCube14
- /1.0/instances/redis
- /1.0/instances/solr
- /1.0/instances/www-ext
- /1.0/instances/www-std
- /1.0/instances/wwwHurdega
- /1.0/profiles/default
- /1.0/storage-pools/pool0/volumes/custom/git_data
status: Created
locations:
- none
-
```

**Comment by tomponline** [comment] 2021-06-17 15:19
@esosan please can you show the output of:

```
sudo pvs # on the host
sudo nsenter --mount=/run/snapd/ns/lxd.mnt -- bash
pvs # inside the snap
```

**Comment by tomponline** [comment] 2021-06-17 15:30
@stgraber I'm wondering if the OP's volume group is on a device that is not scanned by default in the snap's lvm.conf config, but is from the host's config.

**Comment by tomponline** [comment] 2021-06-17 15:31
@esosan can you post contents of `/etc/lvm/lvm.conf` too please

**Comment by esosan** [comment] 2021-06-17 15:33
sudo pvs # on the host

```
  PV                     VG        Fmt  Attr PSize    PFree  
  /dev/md5               vg        lvm2 a--    <1.80t  <1.39t
  /dev/vg/lxc_pool00     pool_0    lvm2 a--   <60.00g  <3.00g
  /dev/vg/lxc_pool01     pool_0    lvm2 a--   <20.00g <17.00g
  /dev/vg/lxc_poolOC00   pool_OC   lvm2 a--  <220.00g <27.00g
  /dev/vg/lxc_pooldata00 pool_data lvm2 a--   <50.00g   4.50g
  /dev/vg/lxc_pooldata01 pool_data lvm2 a--   <50.00g <50.00g
```

sudo nsenter --mount=/run/snapd/ns/lxd.mnt -- bash
pvs # inside the snap
`bash: pvs: command not found`

**Comment by tomponline** [comment] 2021-06-17 15:34
@esosan sorry I meant:

```
sudo nsenter --mount=/run/snapd/ns/lxd.mnt -- bash
/snap/lxd/current/bin/pvs # inside the snap
```

I can't get used to these unfamiliar snap locations. :)

**Comment by esosan** [comment] 2021-06-17 15:35
no problem!

`/snap/lxd/current/bin/pvs: error while loading shared libraries: libdevmapper-event.so.1.02.1: cannot open shared object file: No such file or directory`

**Comment by tomponline** [comment] 2021-06-17 15:36
Third times the charm!

```
sudo nsenter --mount=/run/snapd/ns/lxd.mnt -- bash
LD_LIBRARY_PATH=/snap/lxd/current/lib/:/snap/lxd/current/lib/x86_64-linux-gnu/ /snap/lxd/current/bin/pvs # inside the snap
```

**Comment by esosan** [comment] 2021-06-17 15:36
```
  PV         VG Fmt  Attr PSize  PFree 
  /dev/md5   vg lvm2 a--  <1.80t <1.39t
```

**Comment by esosan** [comment] 2021-06-17 15:38
tell me when I can restore my containers by resetting lvm.external=true

**Comment by tomponline** [comment] 2021-06-17 15:39
@esosan so you `pool_0` vg inside a volume group `vg` on  /dev/md5  ?

**Comment by esosan** [comment] 2021-06-17 15:41
yes, they are nested.  is the only solution with the hosting I use (not very elegant)...

**Comment by tomponline** [comment] 2021-06-17 15:42
@esosan so are `/dev/vg/lxc_pool00` and `/dev/vg/lxc_pool01` volume groups or logical volumes?

**Comment by tomponline** [comment] 2021-06-17 15:43
@stgraber in that case the problem is likely that by default `/etc/lvm/lvm.conf` contains `scan_lvs = 0`

```
# Configuration option devices/scan_lvs.
        # Scan LVM LVs for layered PVs, allowing LVs to be used as PVs.
        # When 1, LVM will detect PVs layered on LVs, and caution must be
        # taken to avoid a host accessing a layered VG that may not belong
        # to it, e.g. from a guest image. This generally requires excluding
        # the LVs with device filters. Also, when this setting is enabled,
        # every LVM command will scan every active LV on the system (unless
        # filtered), which can cause performance problems on systems with
        # many active LVs. When this setting is 0, LVM will not detect or
        # use PVs that exist on LVs, and will not allow a PV to be created on
        # an LV. The LVs are ignored using a built in device filter that
        # identifies and excludes LVs.
        scan_lvs = 0
```

**Comment by tomponline** [comment] 2021-06-17 15:45
@esosan I suspect in your setup we would prefer you to use `lvm.external=true`, rather than incurring the performance penalty for more, shall we say, "common" setups.

For completeness could you post your host's `/etc/lvm/lvm.conf` file here please.

**Comment by stgraber** [comment] 2021-06-17 15:47
Ah, okay, then I think that particular case I'm happy to have handled through `lvm.external=true` as having the snap scan all LVs every time would get very expensive and this is enough of a corner case that needing that bit of extra config seems reasonable.

With my testing I'm reasonably confident that the more common LVM setups (loop, dedicated disk/partition and dedicated non-nested VG) are all working as expected on both core18 and core20.

**Comment by esosan** [comment] 2021-06-17 15:48
[lvm.conf.txt](https://github.com/lxc/lxd/files/6671516/lvm.conf.txt)

**Comment by esosan** [comment] 2021-06-17 15:49
By using lvm.external=true will I have to watch out for something in the future?

**Comment by stgraber** [comment] 2021-06-17 15:50
Nope, should work fine so long as you don't remove the LVM tools from your host (which in your case isn't really an option since you use LVM for other things anyway).

**Comment by stgraber** [comment] 2021-06-17 15:51
@tomponline I suspect scan_lvs wasn't a thing on 18.04 which is in use here, was introduced later and defaults to not scanning, explaining the change in behavior.

**Comment by stgraber** [comment] 2021-06-17 15:59
Okay, so I think we fully figured out what happened here, good!
And given that it's a corner case that we don't really want to handle by default (would slow down everyone else's experience), I don't think there's any further work to do here.

If there was a good way to public channel-specific changelogs/advisories in the snap, I'd add a node there for anyone else hitting this issue. But as that's not something we can do, we'll have to hope that Google does a good job at indexing this issue and the forum thread.

**Comment by tomponline** [comment] 2021-06-17 15:59
It looks like lvm2 has flip-flopped from enabling this by default to disabling it by default a few times:

https://github.com/lvmteam/lvm2/search?q=scan_lvs&type=commits

It look like it broke the tests disabling it by default, so they disabled it in the default config in the end.

**Closed** 2021-06-17 16:00 UTC
Labels: Bug

**Comment by tomponline** [comment] 2021-06-17 16:01
> we'll have to hope that Google does a good job at indexing this issue and the forum thread.

I added some salient keywords to the issue title to try and help that along :)

**Comment by stgraber** [comment] 2021-06-17 16:02
Conclusion is that for anyone who's using nested LVM (VG in a LV), the change of LVM version that occurred by LXD moving from a core18 to a core20 base changed LVM's behavior to not scanning such LVs. As having LVM perform this scan every time is quite resource intensive, we don't want to alter the default LVM configuration to do it.

Instead anyone depending on such a setup should do `snap set lxd lvm.external=true` followed by `systemctl reload snap.lxd.daemon`. This will reconfigure the snap to rely on your system's LVM tools and configuration rather than the snap's.
This will work seamlessly with the only requirement being that you must have the LVM tools installed on your system.
