### ISSUE TITLE
Inconsistent of device names between host and guest os

### ISSUE THREAD

**Issue by TommyLike** [lxc/lxd#9546] opened 2021-11-19 03:56 UTC
# Required information

 * Distribution: LXD
 * Distribution version: 4.20

# Issue description
We are trying to create a openEuler vm image by distrobuilder, this is how we configure our network device in yaml:
```
  - name: ifcfg-enp5s0
    path: /etc/sysconfig/network-scripts/ifcfg-enp5s0
    generator: dump
    templated: true
    content: |-
      DEVICE=enp5s0
      BOOTPROTO=dhcp
      ONBOOT=yes
      HOSTNAME=LXC_NAME
      TYPE=Ethernet
      MTU=
      DHCP_HOSTNAME=LXC_NAME
    types:
      - vm
```
We can successfully launch our vm instances and the network device works well as below:
```
[coder@tommylike ~]$ ifconfig
enp5s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.23.179.101  netmask 255.255.255.0  broadcast 10.23.179.255
        inet6 fd42:66c0:cb02:b124:216:3eff:fece:b9ab  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::216:3eff:fece:b9ab  prefixlen 64  scopeid 0x20<link>
        ether 00:16:3e:ce:b9:ab  txqueuelen 1000  (Ethernet)
        RX packets 8401  bytes 38580037 (36.7 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 4973  bytes 361218 (352.7 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 240  bytes 18240 (17.8 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 240  bytes 18240 (17.8 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
the IP address is correct, but the thing is when show instance detail with lxc command we can see the device name is `eth0` instead of `enp5s0`
how can we fix the inconsistent of device names between lxd and instance.
```
Resources:
  Processes: -1
  Disk usage:
    root: 117.35MiB
  Network usage:
    eth0:
      Type: broadcast
      State: UP
      Host interface: tap8abdd576
      MAC address: 00:16:3e:ce:b9:ab
      MTU: 1500
      Bytes received: 38.58MB
      Bytes sent: 365.13kB
      Packets received: 8434
      Packets sent: 5002
      IP addresses:
        inet:  10.23.179.101/24 (global)
        inet6: fd42:66c0:cb02:b124:216:3eff:fece:b9ab/64 (global)
        inet6: fe80::216:3eff:fece:b9ab/64 (link)
```
Thanks in advance

**Comment by stgraber** [comment] 2021-11-19 04:57
So basically LXD can't control the name in the instance, so you're getting enp5s0 regardless of what's configured on the LXD side. You could rename it in your LXD config from the default of `eth0` to `enp5s0` but that would then cause the interface to change in all containers too which isn't ideal.

But if your main concern is to have `lxc info` and `lxc list` show `enp5s0` instead of `eth0`. This will happen as soon as you get the `lxd-agent` process running in the VM.

(Closing as not a bug, but happy to keep chatting here)

**Closed by stgraber** 2021-11-19 04:57 UTC

**Comment by TommyLike** [comment] 2021-11-19 05:12
@stgraber thanks, I will fix the 9p /virtiofs issue first then.

**Comment by stgraber** [comment] 2021-11-19 05:19
Ah yeah, you'll need one of those to work so you can get the agent up, then the rest should just work.
