### ISSUE TITLE
Erratic network behavior with physical NIC

### ISSUE THREAD

**Issue by ajthemacboy** [lxc/lxd#3638] opened 2017-08-07 22:41 UTC
# Required information

 * Distribution: Ubuntu 17.04 for both host and container
 * The output of "lxc info":
- Host: https://gist.github.com/ajthemacboy/1f8a3d0919e6bd6cfb7f90a1b7ca673c
- Guest: https://gist.github.com/ajthemacboy/36ced35a9b5df8e2765ad4f82cb1745f

- Guest configuration: https://gist.github.com/ajthemacboy/9c338c4ba22f89f4de17ea21d9c4809b
- Guest profile: https://gist.github.com/ajthemacboy/591f7c1b1d4a8348b87a7d39a313497a

# Issue description

My physical network device is behaving erratically in my nested LXD guest. I have attached one of my host's NICs, `enp7s0f1`, to a LXD guest. `enp7s0f1` does disappear from the host as expected.

When I attempt to use a network in my **privileged** container, this is the result:
```
root@lxd0:~# lxc network create lxdbr0 ipv4.address=100.10.0.1/24 ipv4.nat=true
error: Failed to list ipv6 rules for lxdbr0 (table )
root@lxd0:~# lxc init ubuntu:17.04 nestedguest
Creating nestedguest

The container you are starting doesn't have any network attached to it.
  To create a new network, use: lxc network create
  To attach a network to a container, use: lxc network attach

root@lxd0:~# lxc network attach lxdbr0 nestedguest eth0
root@lxd0:~# lxc start nestedguest
error: Missing parent 'lxdbr0' for nic 'eth0'
Try `lxc info --show-log nestedguest` for more info
root@lxd0:~# lxc info --show-log nestedguest
Name: nestedguest
Remote: unix:/var/lib/lxd/unix.socket
Architecture: x86_64
Created: 2017/08/07 22:22 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:
```
There is nothing after `Log:`. I get the error `error: Failed to list ipv6 rules for lxdbr0 (table )` after I create the network, but the network _is_ actually created. When I try to start the guest, I get the error `error: Missing parent 'lxdbr0' for nic 'eth0'` and the guest does not start.

-----------------------------------------------------

In an **unprivileged** container, things are totally different. Services do not start, and the network takes a long time to connect.
```
root@lxd0:~# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 2601:782:8200:f3c0:21e:67ff:fe7b:648  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::21e:67ff:fe7b:648  prefixlen 64  scopeid 0x20<link>
        ether 00:1e:67:7b:06:48  txqueuelen 1000  (Ethernet)
        RX packets 282996  bytes 409257722 (409.2 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 113175  bytes 10162635 (10.1 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0xd1100000-d111ffff

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

root@lxd0:~# service ssh status
● ssh.service - OpenBSD Secure Shell server
   Loaded: loaded (/lib/systemd/system/ssh.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
root@lxd0:~# service networking status
● networking.service - Raise network interfaces
   Loaded: loaded (/lib/systemd/system/networking.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:interfaces(5)
root@lxd0:~# lxd init
error: Unable to talk to LXD: Get http://unix.socket/1.0: dial unix /var/lib/lxd/unix.socket: connect: connection refused
root@lxd0:~# service lxd status
● lxd.service - LXD - main daemon
   Loaded: loaded (/lib/systemd/system/lxd.service; indirect; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:lxd(1)
```
**Several minutes pass before the guest gets an IPv4 address.** Once it does, the networking service is started, but other services still do not.
```
root@lxd0:~# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.0.30  netmask 255.255.255.0  broadcast 10.0.0.255
        inet6 2601:782:8200:f3c0:21e:67ff:fe7b:648  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::21e:67ff:fe7b:648  prefixlen 64  scopeid 0x20<link>
        ether 00:1e:67:7b:06:48  txqueuelen 1000  (Ethernet)
        RX packets 283055  bytes 409267717 (409.2 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 113178  bytes 10163361 (10.1 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0xd1100000-d111ffff

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

root@lxd0:~# service networking status
● networking.service - Raise network interfaces
   Loaded: loaded (/lib/systemd/system/networking.service; enabled; vendor preset: enabled)
   Active: active (exited) since Mon 2017-08-07 22:31:39 UTC; 1min 3s ago
     Docs: man:interfaces(5)
 Main PID: 179 (code=exited, status=0/SUCCESS)
    Tasks: 1 (limit: 23347)
   Memory: 9.6M
      CPU: 273ms
   CGroup: /system.slice/networking.service
           └─315 /sbin/dhclient -1 -v -pf /run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases -I -df /var/lib/dhcp/dhclient6.eth0.leases eth0

Aug 07 22:31:39 lxd0 dhclient[282]: DHCPREQUEST of 10.0.0.30 on eth0 to 255.255.255.255 port 67 (xid=0x55e64fd0)
Aug 07 22:31:39 lxd0 ifup[179]: DHCPREQUEST of 10.0.0.30 on eth0 to 255.255.255.255 port 67 (xid=0x55e64fd0)
Aug 07 22:31:39 lxd0 ifup[179]: DHCPOFFER of 10.0.0.30 from 10.0.0.1
Aug 07 22:31:39 lxd0 dhclient[282]: DHCPOFFER of 10.0.0.30 from 10.0.0.1
Aug 07 22:31:39 lxd0 dhclient[282]: DHCPACK of 10.0.0.30 from 10.0.0.1
Aug 07 22:31:39 lxd0 ifup[179]: DHCPACK of 10.0.0.30 from 10.0.0.1
Aug 07 22:31:39 lxd0 ifup[179]: bound to 10.0.0.30 -- renewal in 270760 seconds.
Aug 07 22:31:39 lxd0 systemd[1]: Started Raise network interfaces.
Aug 07 22:31:39 lxd0 systemd[1]: networking.service: Failed to reset devices.list: Operation not permitted
Aug 07 22:31:39 lxd0 systemd[1]: networking.service: Failed to set invocation ID on control group /system.slice/networking.service, ignoring: Operation not p
root@lxd0:~# service ssh status
● ssh.service - OpenBSD Secure Shell server
   Loaded: loaded (/lib/systemd/system/ssh.service; enabled; vendor preset: enabled)
   Active: inactive (dead)
root@lxd0:~# service lxd status
● lxd.service - LXD - main daemon
   Loaded: loaded (/lib/systemd/system/lxd.service; indirect; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:lxd(1)
root@lxd0:~# ps -aux
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root          1  0.0  0.0  57392  7132 ?        Ss   22:30   0:00 /sbin/init
root         50  0.0  0.0  46216  7916 ?        Ss   22:30   0:00 /lib/systemd/systemd-journald
root         58  0.0  0.0  43380  3216 ?        Ss   22:30   0:00 /lib/systemd/systemd-udevd
root        106  0.0  0.0  21800  3840 ?        Ss   22:30   0:00 bash
root        315  0.0  0.0  16120   860 ?        Ss   22:31   0:00 /sbin/dhclient -1 -v -pf /run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases -I -
root        431  0.0  0.0   4496   768 console  Ss+  22:31   0:00 /bin/sh -c /sbin/sulogin; /bin/systemctl --job-mode=fail --no-block default
root        432  0.0  0.0  25736  2748 console  S+   22:31   0:00 /sbin/sulogin
root        452  0.0  0.0  40224  3396 ?        R+   22:33   0:00 ps -aux
```

I can initialize LXD after I manually start the LXD service:
```
root@lxd0:~# lxd init
error: Unable to talk to LXD: Get http://unix.socket/1.0: dial unix /var/lib/lxd/unix.socket: connect: connection refused
root@lxd0:~# service lxd start
root@lxd0:~# lxd init
Do you want to configure a new storage pool (yes/no) [default=yes]? yes
Name of the new storage pool [default=default]:
Name of the storage backend to use (dir, btrfs) [default=dir]: dir

We detected that you are running inside an unprivileged container.
This means that unless you manually configured your host otherwise,
you will not have enough uid and gid to allocate to your containers.

LXD can re-use your container's own allocation to avoid the problem.
Doing so makes your nested containers slightly less safe as they could
in theory attack their parent container and gain more privileges than
they otherwise would.

Would you like to have your containers share their parent's allocation (yes/no) [default=yes]? yes
Would you like LXD to be available over the network (yes/no) [default=no]? no
Would you like stale cached images to be updated automatically (yes/no) [default=yes]? no
Would you like to create a new network bridge (yes/no) [default=yes]? yes
What should the new bridge be called [default=lxdbr0]?
What IPv4 address should be used (CIDR subnet notation, “auto” or “none”) [default=auto]?
What IPv6 address should be used (CIDR subnet notation, “auto” or “none”) [default=auto]?

error: Failed to list ipv6 rules for lxdbr0 (table )
```
But I get the same errors as in a privileged container when creating a network and when starting a container.

# Steps to reproduce

This is the script I use to initialize my primary container (lxd0):
```
#!/bin/bash

lxc profile create lxd0
lxc profile set lxd0 raw.lxc lxc.aa_profile=unconfined
#lxc profile set lxd0 security.privileged=true

lxc profile device add lxd0 sdc3 unix-block path=/dev/sdc3
lxc profile device add lxd0 sda unix-block path=/dev/sda
lxc profile device add lxd0 sda1 unix-block path=/dev/sda1
lxc profile device add lxd0 sda9 unix-block path=/dev/sda9
lxc profile device add lxd0 sdb unix-block path=/dev/sdb
lxc profile device add lxd0 sdb1 unix-block path=/dev/sdb1
lxc profile device add lxd0 sdb9 unix-block path=/dev/sdb9
lxc profile device add lxd0 zfs unix-char path=/dev/zfs
lxc profile device add lxd0 kvm unix-char path=/dev/kvm
lxc profile device set lxd0 kvm gid 116

lxc init -p default -p lxd0 -c security.nesting=true ubuntu:17.04 lxd0
lxc config device add lxd0 eth0 nic nictype=physical parent=enp7s0f1

lxc start lxd0

sleep 30

lxc exec lxd0 -- bash -c 'echo "root:65536:65536" >> /etc/subuid'
lxc exec lxd0 -- bash -c 'echo "root:65536:65536" >> /etc/subgid'
lxc exec lxd0 -- apt update
lxc exec lxd0 -- apt upgrade -y
lxc exec lxd0 -- apt install -y zfsutils-linux
lxc exec lxd0 -- mkdir /mnt/ssd
lxc exec lxd0 -- wget "https://pastebin.com/raw/hwaQFxsy" -O /etc/systemd/system/mounts.service
lxc exec lxd0 -- systemctl enable mounts.service
lxc exec lxd0 -- wget "https://pastebin.com/raw/MxedhLHa" -O /usr/local/bin/mounts.sh
lxc exec lxd0 -- chmod +x /usr/local/bin/mounts.sh
lxc exec lxd0 -- bash -c "echo '/dev/sdc3       /mnt/ssd        ext4    noatime 0       2' >> /etc/fstab"
lxc exec lxd0 -- mkdir /root/.ssh
lxc exec lxd0 -- bash -c "echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDA3ZyyE223l9eDM69oz+9He9ZTjTOwkkXZWoTJcQWIflmAO/UeOCyv/0u1V4D5xbMyWrZcYtWCu06LKZIK5x8HJfRBAmWpWxepd3MCYWV+EbCQU24bwFmDwItwaS6IXkVlh8flwnkcvYxSvy6p5qSG9gmlODgjaB+H0sOLOpTT2V86pOLxsTLW0Pum4s9Q1wrYNdtupjmPV5p+SUf1lcIbGR3UHoZMHm2820ah1YdAugk7ICFocgmU9SkTxVpzzbQwFChQCqXgAABFcWJR2xH+X2coUWvy0vBgJGqMa/XP0+Ux2Q9czUPKFZY1w1vShrz7092fMABysz9PDXZiJILv aj@DESKTOP-UPLD3I1' > /root/.ssh/authorized_keys"
lxc exec lxd0 -- chmod 0644 /root/.ssh/authorized_keys
lxc exec lxd0 -- bash -c "echo 'PermitRootLogin prohibit-password' >> /etc/ssh/sshd_config"

lxc restart lxd0
```
I have tested without installing any additional programs, adding any additional unix-blocks, or enabling any custom services. The same issues occur.

**Comment by stgraber** [comment] 2017-08-08 03:16
Hi,

So as a first step, I'd recommend getting closer to the current upstream release by updating from zesty-backports.

    apt install -t zesty-backports lxd lxd-client

This should get you LXD 2.15 (2.16 pretty soon). I'd recommend upgrading both your host and container, then trying again. I seem to remember us doing something about the ipv6 firewalling error at least.

**Comment by ajthemacboy** [comment] 2017-08-08 12:09
Updating the host to LXD version 2.15 does not resolve the network startup delay in an unprivileged container. Services still do not load and the network takes a few minutes to become active. The same LXD bridge/network issues still occur. 

In a privileged container with LXD 2.15, the same LXD bridge/network issues still occur.

**Comment by ajthemacboy** [comment] 2017-08-09 17:13
I can add a macvlan NIC to the nested guest like this: `lxc config device add ubu1 eth0 nic nictype=bridged parent=eth0`

The container starts up fine and receives an IP on the host's LAN.

**Comment by stgraber** [comment] 2017-08-10 19:19
I'm trying to reproduce this bug running into issues as there's a lot of stuff in this issue which feel unrelated to the problem.

So my understanding is that you are:
 - Using LXD 2.16
 - Creating a privileged or unprivileged container, with nesting enabled using a physical host nic as eth0 for the container
 - In that container, you attempt to create a "lxdbr0" bridge and that results in a failure.

Is that correct?

The fact that your host isn't running a bridge itself means that a number of kernel modules won't be loaded. Those kernel modules are required by your container however which causes the problem.

Can you try applying the following your container's config:

    linux.kernel_modules: ip6table_nat,ip6table_filter,ip6table_mangle,iptable_nat,iptable_filter,iptable_mangle

This should have all those modules be loaded if necessary before your container starts.

**Comment by ajthemacboy** [comment] 2017-08-11 11:26
Adding those kernel modules allowed me to create a bridge and start my nested container in the privileged container. However, I still have the same issues with services/networking taking several minutes to start in an unprivileged container. 

I should add that the unprivileged container gets an IPV6 IP from DHCP as fast as normal, it seems only IPV4 is slow.

**Comment by stgraber** [comment] 2017-08-11 19:22
Can you try not setting "raw.lxc=lxc.aa_profile=unconfined"? Because that turns off apparmor which may then cause the host apparmor profile to cover processes inside the container.

The most visible behavior of this happening is "dhclient" failing to run and you not getting an IPv4 address in your container.

**Comment by ajthemacboy** [comment] 2017-08-11 19:32
I removed that option and the same issues still occur. Here is my profile config:

```config:
  linux.kernel_modules: ip6table_nat,ip6table_filter,ip6table_mangle,iptable_nat,iptable_filter,iptable_mangle
  security.nesting: "true"
description: ""
devices:
  kvm:
    gid: "116"
    path: /dev/kvm
    type: unix-char
  sda:
    path: /dev/sda
    type: unix-block
  sda1:
    path: /dev/sda1
    type: unix-block
  sda9:
    path: /dev/sda9
    type: unix-block
  sdb:
    path: /dev/sdb
    type: unix-block
  sdb1:
    path: /dev/sdb1
    type: unix-block
  sdb9:
    path: /dev/sdb9
    type: unix-block
  sdc3:
    path: /dev/sdc3
    type: unix-block
  zfs:
    path: /dev/zfs
    type: unix-char
name: lxd0
used_by:
- /1.0/containers/lxd0```

Here is my container config:

```architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 17.04 amd64 (release) (20170811)
  image.label: release
  image.os: ubuntu
  image.release: zesty
  image.serial: "20170811"
  image.version: "17.04"
  volatile.base_image: d4b61f799ac371b36f790eaceff06d406c72729c0383c651df09fc546cd09d86
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    nictype: physical
    parent: enp7s0f1
    type: nic
ephemeral: false
profiles:
- default
- lxd0
stateful: false
description: ""```

**Comment by ajthemacboy** [comment] 2017-08-11 19:34
Here is the networking.service log:

```
● networking.service - Raise network interfaces
   Loaded: loaded (/lib/systemd/system/networking.service; enabled; vendor preset: enabled)
   Active: active (exited) since Fri 2017-08-11 19:32:47 UTC; 58s ago
     Docs: man:interfaces(5)
 Main PID: 210 (code=exited, status=0/SUCCESS)
    Tasks: 1 (limit: 23347)
   Memory: 9.7M
      CPU: 267ms
   CGroup: /system.slice/networking.service
           └─346 /sbin/dhclient -1 -v -pf /run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases -I -df /var/lib/dhcp/dhclient6.eth0.leases eth0

Aug 11 19:32:47 lxd0 dhclient[313]: Listening on LPF/eth0/00:1e:67:7b:06:48
Aug 11 19:32:47 lxd0 dhclient[313]: Sending on   LPF/eth0/00:1e:67:7b:06:48
Aug 11 19:32:47 lxd0 dhclient[313]: Sending on   Socket/fallback
Aug 11 19:32:47 lxd0 dhclient[313]: DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 3 (xid=0xf5c42957)
Aug 11 19:32:47 lxd0 dhclient[313]: DHCPREQUEST of 10.0.0.30 on eth0 to 255.255.255.255 port 67 (xid=0x5729c4f5)
Aug 11 19:32:47 lxd0 dhclient[313]: DHCPOFFER of 10.0.0.30 from 10.0.0.1
Aug 11 19:32:47 lxd0 dhclient[313]: DHCPACK of 10.0.0.30 from 10.0.0.1
Aug 11 19:32:47 lxd0 systemd[1]: Started Raise network interfaces.
Aug 11 19:32:47 lxd0 systemd[1]: networking.service: Failed to reset devices.list: Operation not permitted
Aug 11 19:32:47 lxd0 systemd[1]: networking.service: Failed to set invocation ID on control group /system.slice/networking.service, ignoring: Operation not permitted
```

**Comment by stgraber** [comment] 2017-08-11 19:59
Can you paste the full "journalctl" output for that container? That should show where the delay is coming from as the output you posted above doesn't seem to indicate any delay for that particular unit.

**Comment by ajthemacboy** [comment] 2017-08-11 20:17
http://termbin.com/wmf4

**Comment by stgraber** [comment] 2017-08-11 22:06
Based on the log, the /dev/sdc* devices are the problem. Can you try without those devices?

For some reason systemd appears to try to do something with them, that fails and then causes it to wait for a timeout.

**Comment by ajthemacboy** [comment] 2017-08-12 00:50
When I remove the /dev/sdc3 from /etc/fstab, the network seems to work fine. I realize now I can only mount /dev/sdc3 within a privileged container. How can I work around this?

**Comment by stgraber** [comment] 2017-08-12 01:40
For ext4, you can do:

    echo Y > /sys/module/ext4/parameters/userns_mounts

This is exclusive to the Ubuntu kernel as upstream is reluctant to allow such privileged mounts to be allowed to unprivileged users, but hopefully that's enough for you.

**Comment by stgraber** [comment] 2017-08-12 01:41
So sounds like we can close this issue. The problem with your privileged container was a bunch of missing kernel modules. The same was affecting the unprivileged container, but then you also have the mount issue on top due to it being unprivileged.

**Closed by stgraber** 2017-08-12 01:41 UTC
Labels: Incomplete

**Comment by ajthemacboy** [comment] 2017-08-12 10:56
I already have that taken care of. I have a service to set that option automatically on boot:
```
[Unit]
Description=Enable userspace ext4 mounts
After=network.target

[Service]
Type=oneshot
User=root
ExecStart=/bin/bash -c "/bin/echo Y > /sys/module/ext4/parameters/userns_mounts"
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
```
```
root@corehost:~# cat /sys/module/ext4/parameters/userns_mounts
Y
```
Without this option, I am unable to mount /dev/sdc3 even with the mount command:
```
root@corehost:~# echo N > /sys/module/ext4/parameters/userns_mounts
root@corehost:~# lxc restart lxd0
root@corehost:~# lxc exec lxd0 bash
root@lxd0:~# mount /dev/sdc3 /mnt/ssd
mount: permission denied
```
Setting it again:
```
root@corehost:~# echo Y > /sys/module/ext4/parameters/userns_mounts
root@corehost:~# lxc restart lxd0
root@corehost:~# lxc exec lxd0 bash
root@lxd0:~# mount /dev/sdc3 /mnt/ssd
root@lxd0:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdc2        15G  5.9G  8.0G  43% /
none            492K     0  492K   0% /dev
udev             63G     0   63G   0% /dev/tty
tmpfs           100K     0  100K   0% /dev/lxd
tmpfs           100K     0  100K   0% /dev/.lxd-mounts
tmpfs            63G     0   63G   0% /dev/shm
tmpfs            63G  8.2M   63G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            63G     0   63G   0% /sys/fs/cgroup
/dev/sdc3       204G   61M  194G   1% /mnt/ssd
```

**Comment by ajthemacboy** [comment] 2017-08-15 01:09
@stgraber Can I get some more help on this issue? I have been unable to resolve it.

**Comment by stgraber** [comment] 2017-08-15 02:17
What's the problem?

You last comment shows that you can't mount ext4 in an unprivileged container unless userns_mounts is set to Y, which is exactly the behavior I'd expect. What am I missing?

**Comment by ajthemacboy** [comment] 2017-08-15 11:36
When I add /dev/sdc3 to fstab in an unprivileged container, even with userns_mounts set to Y, services do not start and there are errors in journalctl. 

Here is another journalctl log: http://termbin.com/bbeo

Here is /etc/fstab:
```
LABEL=cloudimg-rootfs   /        ext4   defaults        0 0
/dev/sdc3       /mnt/ssd        ext4    noatime 0       2
```
df and fdisk:
```
root@lxd0:/mnt/ssd# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdc2        15G  6.0G  8.0G  43% /
none            492K     0  492K   0% /dev
udev             63G     0   63G   0% /dev/tty
tmpfs           100K     0  100K   0% /dev/lxd
tmpfs           100K     0  100K   0% /dev/.lxd-mounts
tmpfs            63G     0   63G   0% /dev/shm
tmpfs            63G  8.1M   63G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            63G     0   63G   0% /sys/fs/cgroup
root@lxd0:/mnt/ssd# fdisk -l
Disk /dev/sda: 2.7 TiB, 3000592982016 bytes, 5860533168 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 196EC057-64DD-6541-87C8-628B48A3E211

Device          Start        End    Sectors  Size Type
/dev/sda1        2048 5860515839 5860513792  2.7T Solaris /usr & Apple ZFS
/dev/sda9  5860515840 5860532223      16384    8M Solaris reserved 1


Disk /dev/sdb: 2.7 TiB, 3000592982016 bytes, 5860533168 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 54B8BCB4-B0BE-BB44-BECA-D6A908994191

Device          Start        End    Sectors  Size Type
/dev/sdb1        2048 5860515839 5860513792  2.7T Solaris /usr & Apple ZFS
/dev/sdb9  5860515840 5860532223      16384    8M Solaris reserved 1
```
Services like ssh, lxd, and lxcfs do not start automatically. The networking service takes several minutes to start.

**Comment by ajthemacboy** [comment] 2017-08-15 11:38
These are the relevant lines in journalctl:
```
Aug 15 11:32:42 lxd0 systemd[1]: dev-sdc3.device: Job dev-sdc3.device/start timed out.
Aug 15 11:32:42 lxd0 systemd[1]: Timed out waiting for device dev-sdc3.device.
Aug 15 11:32:42 lxd0 systemd[1]: Dependency failed for File System Check on /dev/sdc3.
Aug 15 11:32:42 lxd0 systemd[1]: Dependency failed for /mnt/ssd.
Aug 15 11:32:42 lxd0 systemd[1]: Dependency failed for Local File Systems.
Aug 15 11:32:42 lxd0 systemd[1]: local-fs.target: Job local-fs.target/start failed with result 'dependency'.
Aug 15 11:32:42 lxd0 systemd[1]: local-fs.target: Triggering OnFailure= dependencies.
Aug 15 11:32:42 lxd0 systemd[1]: mnt-ssd.mount: Job mnt-ssd.mount/start failed with result 'dependency'.
Aug 15 11:32:42 lxd0 systemd[1]: systemd-fsck@dev-sdc3.service: Job systemd-fsck@dev-sdc3.service/start failed with result 'dependency'.
Aug 15 11:32:42 lxd0 systemd[1]: dev-sdc3.device: Job dev-sdc3.device/start failed with result 'timeout'.
Aug 15 11:32:42 lxd0 systemd[1]: dev-sdc2.device: Job dev-sdc2.device/start timed out.
Aug 15 11:32:42 lxd0 systemd[1]: Timed out waiting for device dev-sdc2.device.
Aug 15 11:32:42 lxd0 systemd[1]: dev-sdc2.device: Job dev-sdc2.device/start failed with result 'timeout'.
```
```
Aug 15 11:32:43 lxd0 systemd[1]: dev-sda1.mount: Failed to reset devices.list: Operation not permitted
Aug 15 11:32:43 lxd0 systemd[1]: dev-sdc3.mount: Failed to reset devices.list: Operation not permitted
Aug 15 11:32:43 lxd0 systemd[1]: dev-sda9.mount: Failed to reset devices.list: Operation not permitted
```
There are countless other "Operation not permitted" errors in the log as well.

**Comment by stgraber** [comment] 2017-08-15 15:11
The operation not permitted ones are safe to ignore.

**Comment by stgraber** [comment] 2017-08-15 15:12
Can you post "systemctl cat dev-sdc3.device" and "systemctl cat mnt-ssd.mount"?

**Comment by stgraber** [comment] 2017-08-15 15:13
The log kinda suggests that systemd isn't detecting that /dev/sdc3 is present... which would most likely be a systemd bug, but I'll need to play with this a bit myself to be sure.

**Comment by ajthemacboy** [comment] 2017-08-15 15:28
systemctl cat dev-sdc3.device results in "No files found for dev-sdc3.device." on both the host and the container.
```
root@lxd0:~# systemctl cat mnt-ssd.mount
# /run/systemd/generator/mnt-ssd.mount
# Automatically generated by systemd-fstab-generator

[Unit]
SourcePath=/etc/fstab
Documentation=man:fstab(5) man:systemd-fstab-generator(8)
Before=local-fs.target
Requires=systemd-fsck@dev-sdc3.service
After=systemd-fsck@dev-sdc3.service

[Mount]
What=/dev/sdc3
Where=/mnt/ssd
Type=ext4
Options=noatime
```

**Comment by stgraber** [comment] 2017-08-15 15:33
What does "systemctl cat systemd-fsck@dev-sdc3.service" show?

**Comment by ajthemacboy** [comment] 2017-08-15 15:33
```
root@lxd0:~# systemctl cat systemd-fsck@dev-sdc3.service
# /lib/systemd/system/systemd-fsck@.service
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

[Unit]
Description=File System Check on %f
Documentation=man:systemd-fsck@.service(8)
DefaultDependencies=no
BindsTo=%i.device
Wants=systemd-fsckd.socket
After=%i.device systemd-fsck-root.service local-fs-pre.target systemd-fsckd.socket
Before=systemd-quotacheck.service shutdown.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/lib/systemd/systemd-fsck %f
TimeoutSec=0
```

**Comment by ajthemacboy** [comment] 2017-08-15 15:37
Both the mnt-ssd and systemd-fsck services have this error in their log:
```
Aug 15 11:32:42 lxd0 systemd[1]: Dependency failed for /mnt/ssd.
Aug 15 11:32:42 lxd0 systemd[1]: mnt-ssd.mount: Job mnt-ssd.mount/start failed with result 'dependency'.
```

**Comment by stgraber** [comment] 2017-08-15 16:30
Ok, so the problem seems to be that systemd won't generate the ".device" units inside containers.
Not sure how those units are usually generated and why they don't appear in containers.

@xnox any idea?

**Comment by brauner** [comment] 2017-08-15 16:49
That must be a fairly recent change to systemd though.

**Comment by stgraber** [comment] 2017-08-15 16:56
Why would you think that?

Mounting a block passed into the container is the only case where the lack of .device units is likely to really be a problem and very little people seem to be doing such mounts.

I've confirmed that systemd in 16.04 at least is affected by this.

**Comment by xnox** [comment] 2017-08-16 09:11
@stgraber `.device` units require a running udevd. If those units are missing, it is possible that something is broken with `udevd`. I've only skimmed this issue, to reproduce this - I should pass a `/dev/sd*` device from host to lxd container and then mount it using a `.mount` unit in the container right? With current problem reported that it would fail due to lack of `.device` unit.

**Comment by stgraber** [comment] 2017-08-16 16:56
@xnox we do have a running udevd in the container.

Reproducing steps:
```
stgraber@castiana:~$ truncate -s 10G test.img
stgraber@castiana:~$ sudo losetup -f test.img
stgraber@castiana:~$ sudo losetup -a
/dev/loop1: [0022]:169383 (/var/lib/snapd/snaps/core_2381.snap)
/dev/loop2: [0022]:770242 (/var/lib/snapd/snaps/core_2312.snap)
/dev/loop0: [0022]:1170310 (/var/lib/snapd/snaps/core_2462.snap)
/dev/loop3: [0045]:309158 (/home/stgraber/test.img)
stgraber@castiana:~$ lxc launch ubuntu:16.04 issue3638
Creating issue3638
Starting issue3638
stgraber@castiana:~$ lxc config device add issue3638 sda unix-block source=/dev/loop3 path=/dev/sda
Device sda added to issue3638
stgraber@castiana:~$ lxc exec issue3638 -- mkfs.ext4 /dev/sda
mke2fs 1.42.13 (17-May-2015)
Discarding device blocks: done                            
Creating filesystem with 2621440 4k blocks and 655360 inodes
Filesystem UUID: 77832ca2-b16d-4b94-8f7d-9ea08c5e6913
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (32768 blocks): done
Writing superblocks and filesystem accounting information: done 

stgraber@castiana:~$ echo Y | sudo tee /sys/module/ext4/parameters/userns_mounts
Y
stgraber@castiana:~$ lxc exec issue3638 -- mount /dev/sda /mnt
stgraber@castiana:~$ lxc exec issue3638 bash
root@issue3638:~# echo "/dev/sda /mnt ext4 defaults 0 0" >> /etc/fstab
root@issue3638:~# cat /etc/fstab 
LABEL=cloudimg-rootfs	/	 ext4	defaults	0 0
/dev/sda /mnt ext4 defaults 0 0
root@issue3638:~# exit
stgraber@castiana:~$ lxc exec issue3638 -- umount /mnt
stgraber@castiana:~$ lxc exec issue3638 -- mount /mnt
stgraber@castiana:~$ lxc stop issue3638
stgraber@castiana:~$ lxc start issue3638
stgraber@castiana:~$ lxc exec issue3638 -- mount | grep mnt
stgraber@castiana:~$ lxc exec issue3638 -- systemctl -a | grep mnt
  mnt.mount                                  loaded    inactive dead      start /mnt
stgraber@castiana:~$ lxc exec issue3638 -- systemctl -a | grep sda
  dev-sda.device                             loaded    inactive dead      start dev-sda.device
  dev-sda.mount                              loaded    active   mounted         /dev/sda
stgraber@castiana:~$ lxc exec issue3638 -- ps aux | grep udev
root        54  0.0  0.0  41720  1864 ?        Ss   16:55   0:00 /lib/systemd/systemd-udevd
stgraber@castiana:~$ 
```

**Comment by ajthemacboy** [comment] 2017-08-23 11:56
Any update on this? Perhaps I should open another issue since this is a completely different discussion.

**Comment by stgraber** [comment] 2017-08-23 16:17
Looks like a systemd issue. You could file a bug at https://launchpad.net/ubuntu/+source/systemd/+filebug and post the URL here so we can subscribe to it.

**Comment by ajthemacboy** [comment] 2017-08-25 15:03
Created the issue here: https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1713086

**Comment by stgraber** [comment] 2017-08-25 19:11
thanks, subscribed the lxd team to it
