### ISSUE TITLE
Vintage containers (e.g. Debian jessie) fail to get an IPv4 address

### ISSUE THREAD

**Issue by lueschem** [lxc/lxd#7262] opened 2020-04-27 17:27 UTC
# Setup

 * Distribution: Ubuntu
 * Distribution version: 20.04
```
$ lxc info
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
- firewall_driver
- projects_limits
- container_syscall_intercept_hugetlbfs
- limits_hugepages
- container_nic_routed_gateway
- projects_restrictions
- custom_volume_snapshot_expiry
- volume_snapshot_scheduling
- trust_ca_certificates
- snapshot_disk_usage
- clustering_edit_roles
- container_nic_routed_host_address
- container_nic_ipvlan_gateway
- resources_usb_pci
- resources_cpu_threads_numa
- resources_cpu_core_die
- api_os
- resources_system
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
...
    -----END CERTIFICATE-----
  certificate_fingerprint: 
...  
  driver: lxc
  driver_version: 4.0.2
  firewall: nftables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.4.0-26-generic
  lxc_features:
    cgroup2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    seccomp_notify: "true"
  os_name: Ubuntu
  os_version: "20.04"
  project: default
  server: lxd
  server_clustered: false
  server_name: ***
  server_pid: 1718
  server_version: 4.0.1
  storage: dir
  storage_version: "1"
```

# Issue description

Older containers (e.g. Debian jessie) or newer containers that run in an emulated environment (e.g. Debian buster armhf running on amd64 host) do no get an IPv4 address.

# Steps to reproduce

 1. Launch a jessie container: `lxc launch images:debian/8 my-jessie-container`
 2. Verify that the jessie container does not get an IPv4 address: `lxc list my-jessie-container`

# Additional information

The following log shows, that the container does not get the IPv4 address due to a legacy issue of isc-dhcp-client:

```
$ lxc exec my-jessie-container bash
root@my-jessie-container:~# ifdown eth0
Killed old client process
Internet Systems Consortium DHCP Client 4.3.1
Copyright 2004-2014 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/

Listening on LPF/eth0/00:16:3e:ca:47:9a
Sending on   LPF/eth0/00:16:3e:ca:47:9a
Sending on   Socket/fallback
root@my-jessie-container:~# ifup eth0
Internet Systems Consortium DHCP Client 4.3.1
Copyright 2004-2014 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/

Listening on LPF/eth0/00:16:3e:ca:47:9a
Sending on   LPF/eth0/00:16:3e:ca:47:9a
Sending on   Socket/fallback
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 5
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 10
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 14
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 17
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 15
5 bad udp checksums in 5 packets
No DHCPOFFERS received.
No working leases in persistent database - sleeping.
```

On Ubuntu 18.04, the situation gets solved by an iptables rule (CHECKSUM fill):

```
$ sudo iptables -t mangle -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
CHECKSUM   udp  --  anywhere             anywhere             udp dpt:bootpc /* generated for LXD network lxdbr0 */ CHECKSUM fill
```

On Ubuntu 20.04 this rule is not present:

```
$ sudo iptables -t mangle -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
```

As a workaround I can use ethtool to turn off checksum offloading on lxdbr0:

```
$ sudo ethtool -K lxdbr0 tx off
```
After some time the container will now get an IPv4 address.

This is the related issue on my edi project: https://github.com/lueschem/edi-pi/issues/12

If I got this correctly, nftables no longer supports the checksum-fill feature that iptables used to support. Therefore I was thinking about adding a udev rule that executes the above ethtool command. However, I am pretty sure that there are more elegant solutions.

**Comment by stgraber** [comment] 2020-04-27 17:39
@tomponline under iptables we had a mangle rule which would fill in the needed udp checksums.
Is there an equivalent for that we can implement?

**Comment by tomponline** [comment] 2020-04-27 18:04
Ill dig more deeply into that but at the time I implemented nftables driver I looked in the nftables docs for an equivalent and their position was that only older distros are affected and they wont run nftables. So not considering the container scenario.

**Comment by stgraber** [comment] 2020-04-27 18:50
Yeah, clearly they missed this use case :)

Having to turn off offloading is a bit annoying too.
That being said, if all our publishes images running on `nft` work properly, then I'm not too concerned. For others, the trick of turning off offloading on the nic in the container isn't all that bad, though unfortunate for sure.

**Comment by tomponline** [comment] 2020-04-28 15:23
@stgraber this was the page I was referring to:

https://wiki.nftables.org/wiki-nftables/index.php/Supported_features_compared_to_xtables#CHECKSUM

Confirmed debian 8 doesn't get DHCP on Focal with nftables.

What did you mean by "if all our published images running on nft work properly...for others the trick of turning off offloading on the nic in the container isn't all that bad" in this case I presume that debian 8 is something we would consider "published by us", and yet it doesn't work with nftables.

Perhaps we could add some sort of setting/env variable to force a particular firewall driver (iptables)?

**Comment by stgraber** [comment] 2020-04-28 15:33
We should test all our images on nft, any image we build that doesn't work, we should patch to run ethtool on boot.

**Comment by tomponline** [comment] 2020-04-28 15:35
@stgraber I see, thanks.

**Comment by tomponline** [comment] 2020-04-28 16:05
@stgraber there's a snag with this, it needs the TX checksum offload feature to be disabled on the sending interface, so lxdbr0, not the interface inside the container.

**Comment by stgraber** [comment] 2020-04-28 20:14
I've changed our tests to run on Ubuntu 20.04 with nft now.
The result is:
 - debian 8
 - oracle 8
 - voidlinux

All need some tweaks. Looking at doing that now.

**Comment by tomponline** [comment] 2020-04-28 20:33
I tried disabling tx offloading on eth0 inside the debian 8 container and it didnt work. Do you have something else in mind?

**Comment by stgraber** [comment] 2020-04-28 20:38
Haven't found anything that works yet...

**Comment by tomponline** [comment] 2020-04-28 20:43
Im surprised oracle 8 doesn't work as that is current and based off rhel 8 right?

**Comment by stgraber** [comment] 2020-04-28 20:49
I have a working fix for voidlinux (uses dhclient instead of dhcpcd)

**Comment by stgraber** [comment] 2020-04-28 20:59
oracle 8 seems to just be racy

**Comment by stgraber** [comment] 2020-04-28 21:18
Got a workaround for Debian jessie. Replacing isc-dhcp-client with udhcpc does the trick.

**Comment by stgraber** [comment] 2020-04-28 22:17
Committed all the workarounds into our image branch and images are building now. Closing.

For those with existing installs, the options are effectively:
 - voidlinux => Switch to dhclient
 - debian => Switch to udhcpc

If that's not an option, you can turn off the offloading with ethtool on lxdbr0, that should work, but for high performance use, this may have a significant impact.

**Closed by stgraber** 2020-04-28 22:17 UTC
Labels: Bug

**Comment by tomponline** [comment] 2020-04-29 07:58
@stgraber thanks.

The commits were:

https://github.com/lxc/lxc-ci/commit/f75de00dde22d66ce319dcb9b5ad0a67a4631f51
https://github.com/lxc/lxc-ci/commit/d636a1b2960eeee74c53a4c6c9af79b9b1d0cab3
https://github.com/lxc/lxc-ci/commit/56fb4f42b236b885bd66fdf0e13d5c04f7274845

**Comment by tomponline** [comment] 2020-04-29 10:59
@stgraber is it worth also introducing an ENV var for forcing a particular firewall driver and then having our tests run both iptables and nftables to catch any future issues with iptables?

**Comment by stgraber** [comment] 2020-04-29 11:59
I'm not sure that it is, because this may then see folks forcing it into xtables mode when they have nft rules present, which then gets extremely confusing.

**Comment by tomponline** [comment] 2020-04-29 12:13
@stgraber can we test iptables by adding a dummy rule first before the test suite starts to get LXD to use iptables, or perhaps uninstall nftables commands?

**Comment by stgraber** [comment] 2020-04-29 12:36
yeah, adding a dummy rule works, I've usually been using something like `iptables -A INPUT -j ACCEPT`

**Comment by lueschem** [comment] 2020-04-30 08:14
Hi @stgraber and @tomponline 

Many thanks for the fix and your excellent work on LXD!
In my project I was not able to fix the problem within the container and therefore I developed the following solution:

Within the configuration you can tell edi to attach the container to edibr0 instead of lxdbr0 (I did not want to do changes on lxdbr0 that might have a slightly negative performance impact). If edibr0 is not available edi will automatically create it using the command `lxd network create edibr0`. For all bridges matching `edibr0` I have added the following udev rule:

```
$ cat /lib/udev/rules.d/81-edi.rules 
# Switch off tx offloading on edibr* to avoid dhcp issues on old or emulated containers.
# This rule gets added by the edi package.
ACTION=="add", SUBSYSTEM=="net", KERNEL=="edibr*", RUN+="/sbin/ethtool -K $env{INTERFACE} tx off"
```

Maybe this setup will also be helpful for other LXD users (that are dealing with emulated or old containers). Of course the udev rule can also be directly applied to lxdbr0.

**Comment by tomponline** [comment] 2020-05-04 13:24
@stgraber would it be worth updating our proxy, network and bridged nic tests to detect nftables and run one iteration with an iptables rule added as above to force it into iptables mode and then again without for nftables mode? Or is it easier to run it was a separate iteration in jenkins with one specific iteration adding the iptables rule?

**Comment by stgraber** [comment] 2020-05-04 13:35
Hmm, actually, i suspect the best would be to put a few isolation commands in place in our snap test.
That one is run on all distros so a wide variety of kernels, some with nft, some without.

On jenkins, it'd be tricky because we'd need a completely separate network namespace just for that one test so it can't see any of the rules used by the other LXD daemons. Running an entire testsuite run would work, but then which one do we pick...

**Comment by tomponline** [comment] 2020-05-04 13:53
@stgraber ah ok yes I was thinking having separate namespaces for the jenkins tests, but the snap tests sound easier (and quick without having to incur another pass of all the suites for that combination). How often do the snap tests run?

**Comment by stgraber** [comment] 2020-05-04 17:38
They're run once a day on every architecture, for every track and every channel and version of core.
On top of that, they're also run for every distribution we support every time a new build appears in any of the channels (including edge).
