### ISSUE TITLE
LXD leaks file handles from liblxc

### ISSUE THREAD

**Issue by geaaru** [lxc/lxd#11780] opened 2023-06-02 09:17 UTC
# Required information

 * Distribution: Macaroni/Ubuntu
 * Distribution version: Macaroni 23.04/Ubuntu 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 6.1.28-macaroni / 5.4.0-149-generic 166-Ubuntu, 
   * LXC version: 5.0.2 (macaroni) / 5.0.2 (ubuntu)
   * LXD version: 5.13 (macaroni) / 5.11 (ubuntu/snapd)
   * Storage backend in use: BTRFS

# Issue description

It seems that the liblxc library or LXD doesn't correctly close the FD of the lxc logs. This is more critical for use cases where the containers are used for executing CD/CI tasks like MottainaiCI.

```
# find /proc/*/fd -ls 2>/dev/null | grep  '(deleted)' | grep lxd 
 50180225      0 lr-x------   1 root      root           64 Jun  2 11:04 /proc/13439/fd/29 -> /var/lib/lxd/storage-pools/btrfs-pool/containers/mottainai-macaroni-funtoo-bui-149455107/rootfs/.lxc_keep\ (deleted)
 50186345      0 l-wx------   1 root      root           64 Jun  2 11:04 /proc/5534/fd/21 -> /var/log/lxd/mottainai-macaroni-phoenix-bu-137605241/lxc.log.old\ (deleted)
 50186348      0 l-wx------   1 root      root           64 Jun  2 11:04 /proc/5534/fd/24 -> /var/log/lxd/mottainai-macaroni-funtoo-bui-137372590/lxc.log.old\ (deleted)
 50186349      0 l-wx------   1 root      root           64 Jun  2 11:04 /proc/5534/fd/25 -> /var/log/lxd/mottainai-macaroni-funtoo-bui-136889355/lxc.log.old\ (deleted)
 50186350      0 l-wx------   1 root      root           64 Jun  2 11:04 /proc/5534/fd/26 -> /var/log/lxd/mottainai-macaroni-funtoo-bui-136889347/lxc.log.old\ (deleted)
 50186355      0 l-wx------   1 root      root           64 Jun  2 11:04 /proc/5534/fd/31 -> /var/log/lxd/mottainai-macaroni-funtoo-bui-134099449/lxc.log.old\ (deleted)
 50186356      0 l-wx------   1 root      root           64 Jun  2 11:04 /proc/5534/fd/32 -> /var/log/lxd/mottainai-macaroni-funtoo-bui-134127450/lxc.log.old\ (deleted)
 50186357      0 l-wx------   1 root      root           64 Jun  2 11:04 /proc/5534/fd/33 -> /var/log/lxd/mottainai-macaroni-funtoo-bui-134174011/lxc.log.old\ (deleted)
 50186358      0 l-wx------   1 root      root           64 Jun  2 11:04 /proc/5534/fd/34 -> /var/log/lxd/mottainai-macaroni-funtoo-bui-134207437/lxc.log.old\ (deleted)
 50186359      0 l-wx------   1 root      root           64 Jun  2 11:04 /proc/5534/fd/35 -> /var/log/lxd/mottainai-macaroni-funtoo-bui-134102559/lxc.log.old\ (deleted)

```
The process 5534 is LXD:

```
$> # ps ax | grep 5534
1052 pts/1    S+     0:00 grep --colour=auto 5534
5534 ?        Ssl   28:41 /usr/sbin/lxd --group lxd --debug --syslog
```
The `lxc.log.old` is the file not correctly closed. I'm not sure yet that the .lxc_keep file is yet correct there but it's not so clear when is created that file.

# Steps to reproduce

 1. Create the container
 2. Destroy the container

**Comment by tomponline** [comment] 2023-06-02 10:55
This is caused by calls to `initLXC()` that do not subsequently call `d.c.Release()`.
Eventually Go's garbage collector will clear out the struct in memory and will call `lxcUnload` which calls `d.c.Release()` and closes the handle to liblxc.

We can probably do better and proactively call `d.c.Release()` when liblxc isn't needed anymore, but because a parent function call maybe calling multiple functions that call `initLXC`, we need to be careful not to be releasing it prematurely and either causing it to be reintialised unnecessary or failing due to it not being available.

**Comment by stgraber** [comment] 2023-06-07 16:10
Marking as incomplete because we already do have testing specifically for this: https://github.com/lxc/lxd/blob/master/test/suites/fdleak.sh

So we'd likely want to change the test in a way that catches this issue before trying to alter LXD to force those to expire faster.

**Comment by geaaru** [comment] 2023-06-07 16:15
@stgraber have you some idea about how I could identify the reproducibility? In my case, I just create/destroy ephemeral containers.

This is my status also with LXD 5.14:
```
$> find /proc/*/fd -ls 2>/dev/null | grep  '(deleted)' | grep lxd  | wc -l
164
```

**Comment by stgraber** [comment] 2023-06-07 16:21
@geaaru It may be useful to do:
 - lxc config set core.debug_address 127.0.0.1:8444
 - curl http://127.0.0.1:8444/debug/pprof/goroutine?debug=2

That should let us see if there's any goroutine running in the background that could be holding up the go-lxc struct.

**Comment by geaaru** [comment] 2023-06-07 16:25
What I could to add is that probably there are different issues and/or use cases but the more critical is related to `lxc.log.old`:
```
$> find /proc/*/fd -ls 2>/dev/null | grep  '(deleted)' | grep lxc.log.old  | wc -l
149
$> find /proc/*/fd -ls 2>/dev/null | grep  '(deleted)' | grep console.log  | wc -l
6
$> find /proc/*/fd -ls 2>/dev/null | grep  '(deleted)' | grep proxy.lxd-socket.log  | wc -l
2
```

The second is related to `console.log`, I'm not sure that if this is a normal behaviour (an example on running container):
```
 14699711      0 lrwx------   1 root      root           64 Jun  7 18:13 /proc/5838/fd/58 -> /var/log/lxd/fs3-next/console.log\ (deleted)
```
The pid 5838 is related to this:
```
5838 ?        Ss     0:05 [lxc monitor] /var/lib/lxd/containers fs3-next
```

The third is related to proxy lxd-socket:
```
14700288      0 lrwx------   1 root       root           64 Jun  7 18:13 /proc/6777/fd/1 -> /var/log/lxd/mottainai-macaroni-agent1/proxy.lxd-socket.log\ (deleted)
```
Where in this case is related to forkproxy process:
```
# ps ax | grep 6777
 6777 ?        Ssl    1:55 /usr/sbin/lxd forkproxy -- 6654 3 unix:/var/lib/lxd/unix.socket 5430 4 unix:/var/lib/lxd/unix.socket 994 0 0777 994 0
```

Attaching the curl output:


[lxd-debug-goroutine.txt](https://github.com/lxc/lxd/files/11679816/lxd-debug-goroutine.txt)

**Comment by tomponline** [comment] 2023-06-07 17:06
> Marking as incomplete because we already do have testing specifically for this: https://github.com/lxc/lxd/blob/master/test/suites/fdleak.sh
> 
> So we'd likely want to change the test in a way that catches this issue before trying to alter LXD to force those to expire faster.

Ok I can di that, as its easily reproducible in my observations.

**Comment by tomponline** [comment] 2023-06-09 13:34
@stgraber the fdleak test has two weaknesses that I can see that are masking the problem:

1. It calls /internal/gc at the end to force a garbage collection run.
2. But actually there are leaks that are continuing beyond the garbage collection, which are being masked because the fdleak checks requires >5 FDs to have leaked to be considered a failure. There are infact 5 FDs that have leaked (one for each container created), but because one of the original starting FDs has (a socket by the looks of it) has been closed since LXD started, the fdleak count is tested at 4.

So it looks to me like we have 1 "real" leak and a general case of "lingering" fd leaks that only get cleaned up periodically on garbage collection.

**Closed** 2023-06-13 08:04 UTC
Labels: Bug
