### ISSUE TITLE
Feature request: container name tab autocomplete

### ISSUE THREAD

**Issue by jasonbayton** [lxc/lxd#1797] opened 2016-03-23 11:28 UTC
# Issue description

It would be super handy if tab autocomplete could extend to container names following an LXC command in the same way package names autocomplete when using apt-get install.

# Steps to reproduce

1. type a command with beginning of conainter name (ex: `lxc exec myfir`)
2. hit tab
3. watch it autocomplete to `lxc exec myfirstcontainer`

# Required information

 * Distribution: Ubuntu
 * Distribution version: 15.10
 * The output of "lxc info" or if that fails:

apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures: x86_64
  driver: lxc
  driverversion: 2.0.0.rc12
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.2.0-34-generic
  server: lxd
  serverpid: 66430
  serverversion: 2.0.0.rc5
  storage: dir
  storageversion: ""
config: {}
public: false

**Comment by tych0** [comment] 2016-03-23 13:47
So we have a bash completion profile that is installed with the package, but it's not sourced, and I'm not sure why. For now if you source it manually it hsould work:

`. /usr/share/bash-completion/completions/lxd-client`

presumably we need to drop it in `/etc/bash_completion.d`? @stgraber probably knows :)

**Comment by jasonbayton** [comment] 2016-03-23 14:27
Happy to hear! That's an easy one then.
I could edit my request to source the completion file for 2.0?

**Comment by stgraber** [comment] 2016-03-23 15:36
/etc/bash_completion.d is deprecated

Looks like the problem is that /usr/share/bash-completion requires the files to match the command name...

So we need to rename the lxc one to lxc1, introduce symlinks for all its commands and then rename the lxd-client one to just lxc...

**Comment by stgraber** [comment] 2016-03-23 15:39
Yep, confirmed that it does the trick, I'll figure out the packaging update later.

Closing this issue as there's nothing to do in LXD upstream, it's purely a distribution issue.

**Closed by stgraber** 2016-03-23 15:39 UTC

**Comment by C0rn3j** [comment] 2018-02-22 10:09
Not sure if I should bother opening up a new issue since the distro is different and this was resolved, but the end issue is the same.

---

I cannot autocomplete on a new Arch install with `lxd` package from AUR.

Neither using `bash` or `zsh` will autocomplete `lxc exec bol` to `lxc exec bold-piranha` when pressing TAB. (using the root account)

Trying to source the completions (which needs bash-completions package installed) works under bash, but it doesn't seem to be automatically picked up like in Ubuntu.

Further sourcing this file https://github.com/theblazehen/lxd-zsh-completion/blob/master/lxd-completion.zsh makes the completions work on zsh. Is there any official way to get zsh LXD completion?

LXD and LXC versions

```
[root@Acedia ~]# pacman -Q lxd lxc
lxd 2.21-4
lxc 1:2.1.1-1
```

**Comment by utkarsh2102** [comment] 2021-03-22 12:42
FWIW, https://github.com/endaaman/lxd-completion-zsh by @endaaman is a superb one for zsh.

**Comment by pellcorp** [comment] 2023-04-21 07:39
For what its worth on Manjaro can fix the issue with non snap lxd with:

```
sudo ln -s /usr/share/bash-completion/completions/lxd /usr/share/bash-completion/completions/lxc
```

As alluded to above, the name of the completion has to match, so that `lxd` completion installed by the `lxd` package does not work for the lxc command.

At least that is my experience.
