### ISSUE TITLE
storage_lvm: created LV fadesout during "lvc init"

### ISSUE THREAD

**Issue by Laguna-x** [lxc/lxd#2829] opened 2017-01-29 19:17 UTC
//start service
//copying image remote:debian/jessie to local --alias=debian_j-amd64
 lxc init debian_j-amd64 debNetMgmt

> Creating debNetMgmt
> error: Error mounting snapshot LV: no such file or directory

# lvm version
  LVM version:     2.02.111(2) (2014-09-01)
  Library version: 1.02.90 (2014-09-01)
  Driver version:  4.27.0
# uname -a
Linux mSys 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux

# /var/log/lxd/lxd.log
```
lvl=info msg="LXD 2.8 is starting in normal mode" path=/var/lib/lxd t=2017-01-28T06:32:21+0300
...
lvl=info msg="Done updating images" t=2017-01-30T00:07:04+0300
ephemeral=false lvl=info msg="Creating container" name=debNetMgmt t=2017-01-30T00:07:18+0300
ephemeral=false lvl=info msg="Created container" name=debNetMgmt t=2017-01-30T00:07:18+0300
created=2017-01-29T21:07:18+0000 ephemeral=false lvl=info msg="Deleting container" name=debNetMgmt t=2017-01-30T00:07:18+0300 used=1970-01-01T00:00:00+0000
created=2017-01-29T21:07:18+0000 ephemeral=false lvl=info msg="Deleted container" name=debNetMgmt t=2017-01-30T00:07:19+0300 used=1970-01-01T00:00:00+0000
```
# lxc config show
```
config:
  core.https_address: '[::]:8443'
  core.https_allowed_headers: Content-Type
  core.https_allowed_methods: GET, POST, PUT, DELETE, OPTIONS
  core.https_allowed_origin: '*'
  core.trust_password: true
  images.auto_update_cached: "false"
  images.auto_update_interval: "24"
  images.remote_cache_expiry: "5"
  storage.lvm_vg_name: Data
```

Next i'm trying to edit ...go/src/github.com/lxc/lxd/lxd/storage_lvm.go to catch the problem. So:
find function 
> func (s *storageLvm) ContainerCreateFromImage(

next wright something like <<return fmt.Errorf("!EBUGGING:")>> after "destPath := container.Path()"
then
```
# lxc init debian_j-amd64 debNetMgmt
Creating debNetMgmt
error: !EBUGGING:
# lvs |grep deb
  debNetMgmt                                                       Data   Vwi---tz-k  10,00g LXDPool 40e7...
```

!BUT! if <<return fmt.Errorf("!EBUGGING:")>> move after
 ```
       if err := os.MkdirAll(destPath, 0755); err != nil {
                return fmt.Errorf("Error creating container directory: %v", err)
        }
```
then << lvs |grep deb>> return nothing, so there is new LV disapperes after "os.MkdirAll(destPath, 0755)" (or what?)

PS. trying to create dir by hands - thats ok
```
# lvs |grep deb
  debNetMgmt                                                       Data   Vwi---tz-k  10,00g LXDPool 40e7...   
# lxc list
+------+-------+------+------+------+-----------+
| NAME | STATE | IPV4 | IPV6 | TYPE | SNAPSHOTS |
+------+-------+------+------+------+-----------+
# mkdir /var/lib/lxd/containers/debNetMgmt
# lvs |grep deb
  debNetMgmt                                                       Data   Vwi---tz-k  10,00g LXDPool 40e...   

```

**Comment by stgraber** [comment] 2017-01-29 19:27
Does /dev/Data/debNetMgmt exist on your system?

**Comment by Laguna-x** [comment] 2017-01-29 20:00
# storage_lvm.go
```
        destPath := container.Path()
        return fmt.Errorf("!EBUGGING:")
        if err := os.MkdirAll(destPath, 0755); err != nil {
                return fmt.Errorf("Error creating container directory: %v", err)
        }
        //return fmt.Errorf("!EBUGGING: %s", destPath)

```
# system

```
 lxc init debian_j-amd64 debNetMgmt
Creating debNetMgmt
error: !EBUGGING:
# lvs |grep deb
  debNetMgmt                                                       Data   Vwi---tz-k  10,00g LXDPool 40e77  
# ls /dev/Data
home  home_root  opt  Store  swap  tmp  usr  var  var_log

```

**Comment by Laguna-x** [comment] 2017-01-29 20:29
pool device was not created
```
 --- Logical volume ---
  LV Path                /dev/Data/40e7716a8f0760ff643f9baedb8dee657a395e08e167ccb6147ad66136b9c605
  LV Name                40e7716a8f0760ff643f9baedb8dee657a395e08e167ccb6147ad66136b9c605
  VG Name                Data
```
but thereis no so dir  in /dev/Data

**Comment by Laguna-x** [comment] 2017-01-29 21:00
addition:
> func (s *storageLvm) createThinLV...
poolname := daemonConfig["storage.lvm_thinpool_name"].Get()

but:
```
# lxc config get storage.lvm_thinpool_name

# lxc config set storage.lvm_thinpool_name LXDPool
error: Can not change LVM config. Images or containers are still using LVs: [40e7716a8f0760ff643f9baedb8dee657a395e08e167ccb6147ad66136b9c605]
```

it can't get and change pool name

**Comment by Laguna-x** [comment] 2017-01-29 21:15
wtf?
removed all images, setted lxc config get storage.lvm_thinpool_name LXDPool
but after init, lvm_thinpool reseted to nothing and continues same issue

**Comment by Laguna-x** [comment] 2017-01-30 19:33
don't know what happening, but after rebooting system thats seems ok:
image initialized. (but maybe http://unix.stackexchange.com/questions/11125/lvm-devices-under-dev-mapper-missing was here something)
```
ls /dev/Data
55e7e7018ccb651dd5119479a8d200ea273ce28e4b0410fb9a169cff8d69a382  debNetMgmt
```
problem may be freezed until next one

**Comment by stgraber** [comment] 2017-01-30 22:41
Yeah, everything which was mentioned so far would be consistent with /dev being mispopulated.

**Comment by Laguna-x** [comment] 2017-01-31 07:31
1 question is: why storage.lvm_thinpool_name is not accessable?

**Comment by stgraber** [comment] 2017-01-31 20:40
@Laguna-x I'm not too familiar with our LVM backend, maybe @mikemccracken remembers :)

An empty config value means it'll use its default value, in this case "LXDPool" (per doc/configuration.md). I suspect changes to it are rejected once some containers are already using it.

**Comment by mikemccracken** [comment] 2017-02-02 19:56
Hi, it's been a while, so I don't know off the top of my head. I went looking to see how that config is handled. @stgraber is right that changing the thinpool name should not be allowed if there are containers, snapshots, or images using the pool.

However, it should have shown the error from this line in the validator function: https://github.com/lxc/lxd/blob/a81dc78ddb800f286b01a4f93ff4a699b7d9292b/lxd/storage_lvm.go#L98

The config setting code has changed since I last worked on LXD - it looks like there are situations where the validator is not called, like when you're trying to set it to the same value it already is set to. So you wouldn't see the error then. I'm not sure why it doesn't print the correct value on your second line though.

Sorry I can't be more helpful here.

**Comment by stgraber** [comment] 2017-02-08 18:32
Going to close this as it looks like it was mostly caused by the kernel being confused and not showing all the dm entries in /dev/mapper.

For the latter part, @brauner is about to land a branch which adds support for concurrent storage pools, effectively deprecating those two storage.* keys in favor of per-pool ones which will hopefully work in a more consistent way.

**Closed by stgraber** 2017-02-08 18:32 UTC
