### ISSUE TITLE
Can still ping container IP address after removing container

### ISSUE THREAD

**Issue by bigjools** [lxc/lxd#2224] opened 2016-07-22 04:50 UTC
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
  <snip>
  certificatefingerprint: e52d273b75695a9b8fb6e7b08164af9448434c2cf7d2fd428011bfa17a8ccf59
  driver: lxc
  driverversion: 2.0.3
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-22-generic
  server: lxd
  serverpid: 17579
  serverversion: 2.0.3
  storage: btrfs
  storageversion: "4.4"
config: {}
public: false

# Issue description

I created a container, and then put a tagged vlan on top of lxdbr0 so that I can talk to the host and other containers on a second network.

I gave the host's lxdbr0.1215 an IP address, and made eth0.1215 in the container also with its own IP address.

After removing the container, I can still ping the address on the VLAN! It also responds with duplicates:

$ arping -I lxdbr0.1215 192.168.15.20
ARPING 192.168.15.20 from 192.168.15.1 lxdbr0.1215
Unicast reply from 192.168.15.20 [00:16:3E:B1:9B:0C] 0.599ms
Unicast reply from 192.168.15.20 [00:16:3E:B1:9B:0C] 0.607ms
Unicast reply from 192.168.15.20 [00:16:3E:B1:9B:0C] 0.609ms
Unicast reply from 192.168.15.20 [00:16:3E:B1:9B:0C] 0.534ms
Unicast reply from 192.168.15.20 [00:16:3E:B1:9B:0C] 0.541ms

$ ping 192.168.15.20
PING 192.168.15.20 (192.168.15.20) 56(84) bytes of data.
64 bytes from 192.168.15.20: icmp_seq=1 ttl=64 time=0.108 ms
64 bytes from 192.168.15.20: icmp_seq=1 ttl=64 time=0.126 ms (DUP!)
64 bytes from 192.168.15.20: icmp_seq=1 ttl=64 time=0.144 ms (DUP!)
64 bytes from 192.168.15.20: icmp_seq=2 ttl=64 time=0.051 ms

Bizarrely:

$ nmap 192.168.15.20

Starting Nmap 7.01 ( https://nmap.org ) at 2016-07-21 19:01 AEST
Note: Host seems down. If it is really up, but blocking our ping probes, try -Pn
Nmap done: 1 IP address (0 hosts up) scanned in 3.02 seconds

(Supplying -Pn shows all ports are closed.)

# Steps to reproduce

As above.

# Information to attach

Let me know if you can't reproduce and I'll get logs.

**Comment by stgraber** [comment] 2016-07-22 14:53
```
stgraber@dakara:~$ sudo ip link add link lxdbr0 name lxdbr0.1215 type vlan id 1215
stgraber@dakara:~$ sudo ip addr add 10.1.1.1/24 dev lxdbr0.1215
stgraber@dakara:~$ sudo ip link set lxdbr0.1215 up
stgraber@dakara:~$ lxc exec xenial1 -- ip link add link eth0 name eth0.1215 type vlan id 1215
stgraber@dakara:~$ lxc exec xenial1 -- ip addr add 10.1.1.2/24 dev eth0.1215
stgraber@dakara:~$ lxc exec xenial1 -- ip link set eth0.1215 up
stgraber@dakara:~$ ping 10.1.1.2
PING 10.1.1.2 (10.1.1.2) 56(84) bytes of data.
64 bytes from 10.1.1.2: icmp_seq=1 ttl=64 time=0.121 ms
64 bytes from 10.1.1.2: icmp_seq=2 ttl=64 time=0.077 ms
^C
--- 10.1.1.2 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 999ms
rtt min/avg/max/mdev = 0.077/0.099/0.121/0.022 ms
stgraber@dakara:~$ lxc exec xenial1 -- ping 10.1.1.1
PING 10.1.1.1 (10.1.1.1) 56(84) bytes of data.
64 bytes from 10.1.1.1: icmp_seq=1 ttl=64 time=0.101 ms
64 bytes from 10.1.1.1: icmp_seq=2 ttl=64 time=0.093 ms
^C
--- 10.1.1.1 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 999ms
rtt min/avg/max/mdev = 0.093/0.097/0.101/0.004 ms
stgraber@dakara:~$ lxc stop xenial1
stgraber@dakara:~$ ping 10.1.1.2
PING 10.1.1.2 (10.1.1.2) 56(84) bytes of data.
^C
--- 10.1.1.2 ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms

stgraber@dakara:~$ 
```

**Comment by stgraber** [comment] 2016-07-22 14:59
So I can't seem to reproduce what you're seeing.

Unless you actually have an IP/MAC conflict somewhere, the most likely hypothesis is that the network namespace is somehow being kept alive.

This can happen because of:
 - Some kind of unkillable zombie process that won't go away (usually kernel bug)
 - The container somehow managed to send an fd or other reference to its network namespace to the outside. This can be done by bind-mounting /proc/<PID>/ns/net from a container's process to some path on the host for example. Misconfigured indexing or backup services on the host, could in theory cause this, albeit very temporarily.
 - The kernel is just bad at refcounting (definitely a kernel bug)

**Comment by bigjools** [comment] 2016-07-22 15:00
Can you try with a centos 7 container, that's what I was using, apologies
for not mentioning it.

**Comment by bigjools** [comment] 2016-07-22 15:03
It's entirely possible that a process was still running because I had to
force kill the container when it wouldn't stop normally. I was using
pacemaker inside it with a virtual ip, which was not coming up sometimes.

I'll try to reproduce again tomorrow.

**Comment by stgraber** [comment] 2016-07-22 15:11
Trying with images:centos/7/amd64 now

**Comment by stgraber** [comment] 2016-07-22 15:20
```
stgraber@dakara:~$ lxc launch images:centos/7/amd64 centos7
Creating centos7
Retrieving image: 100%
Starting centos7
stgraber@dakara:~$ lxc exec centos7 -- ip link add link eth0 name eth0.1215 type vlan id 1215
stgraber@dakara:~$ lxc exec centos7 -- ip addr add 10.1.1.2/24 dev eth0.1215
stgraber@dakara:~$ lxc exec centos7 -- ip link set eth0.1215 up
stgraber@dakara:~$ lxc exec centos7 -- ping 10.1.1.1
PING 10.1.1.1 (10.1.1.1) 56(84) bytes of data.
64 bytes from 10.1.1.1: icmp_seq=1 ttl=64 time=0.125 ms
64 bytes from 10.1.1.1: icmp_seq=2 ttl=64 time=0.129 ms
^C
--- 10.1.1.1 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1000ms
rtt min/avg/max/mdev = 0.125/0.127/0.129/0.002 ms
stgraber@dakara:~$ ping 10.1.1.2
PING 10.1.1.2 (10.1.1.2) 56(84) bytes of data.
64 bytes from 10.1.1.2: icmp_seq=1 ttl=64 time=0.111 ms
64 bytes from 10.1.1.2: icmp_seq=2 ttl=64 time=0.066 ms
^C
--- 10.1.1.2 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 999ms
rtt min/avg/max/mdev = 0.066/0.088/0.111/0.024 ms
stgraber@dakara:~$ lxc stop centos7 --force
stgraber@dakara:~$ ping 10.1.1.2
PING 10.1.1.2 (10.1.1.2) 56(84) bytes of data.
^C
--- 10.1.1.2 ping statistics ---
2 packets transmitted, 0 received, 100% packet loss, time 1008ms

stgraber@dakara:~$ 
```

**Comment by bigjools** [comment] 2016-07-26 00:38
I've reproduced it but not in the same way. I don't think the VLAN is pertinent any more. What I did was roll back a snapshot, and my container's eth0 didn't come up. When I tried to ifup it manually Centos complained that it was already taken - and sure enough I can ping the IP from the host, but lxc list shows the container doesn't have that IP address any more.

Now, I was running pacemaker across a few containers which may have caused problems perhaps? Either way I think you're right about it being a kernel bug.

Also I noted before restoring my snapshot that "lxc stop" or "lxc restart" would just hang forever. I could do "lxc exec host reboot" instead which did work.

**Comment by bigjools** [comment] 2016-07-26 00:41
I should say that I rolled back three containers at the same time and only one of them experienced the bug. It seems like a race, somewhere.

**Comment by bigjools** [comment] 2016-07-26 09:04
Some more info.

Using arping gets me the MAC address behind the IP:
```
$ arping -I lxdbr0 10.198.190.21          
ARPING 10.198.190.21 from 10.198.190.1 lxdbr0
Unicast reply from 10.198.190.21 [00:16:3E:BF:FB:D5]  0.557ms
```

Then we can use brctl to get the macs for the bridge, the first one shown matches the mac above:
```
$ sudo brctl showmacs lxdbr0
port no mac addr                is local?       ageing timer
  3     00:16:3e:bf:fb:d5       no                 1.72
```
If I look for the mac in the "ip address"  output there's no match:
```
$ ip a|grep -i '00:16:3E:BF:FB:D5'
$
```

**Comment by bigjools** [comment] 2016-07-26 09:14
Furthermore:
```
$ sudo brctl showstp lxdbr0
<snip>
vethMVSXKO (3)
 port id                8003                    state                forwarding
 designated root        8000.fe01c745c2f0       path cost                  2
 designated bridge      8000.fe01c745c2f0       message age timer          0.00
 designated port        8003                    forward delay timer        0.00
 designated cost           0                    hold timer                 0.00
 flags
<snip>
```
So that IP comes from vethMVSXKO:
```
77: vethMVSXKO@if76: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue master lxdbr0 state UP group default qlen 1000
```
It's pointing at host device 76, which doesn't exist any more.

In fact I have a whole load of veth devices which are not attached to anything. This looks like a major bug.

**Comment by bigjools** [comment] 2016-07-26 09:21
If I remove the veth device above, the phantom IP address no longer responds to pings.

**Comment by stgraber** [comment] 2016-07-26 11:28
ok, so yes, your problem is that the kernel isn't destroying the network namespace as it should.

When the last process in a network namespace dies, the namespace should be destroyed by the kernel, which causes any physical device to be moved back to the host and any virtual device (including your veth) to be destroyed, killing the host side device in the process.

That's why there is no logic in lxd or lxc to actually do network cleanup because by design, the kernel is the one doing that.

If you can confirm that you have no zombie processes left around on the host which would keep that namespace alive, then it's most definitely a kernel bug.
Usually when that happens, you'll see ref counting warnings in dmesg, usually related to the loopback device.

**Comment by bigjools** [comment] 2016-07-27 06:01
If you're talking about network namespace as in "ip netns" there is nothing there, I presume you mean the bridge ports?

I didn't see any zombie processes, but I'll check again next time this happens - which is basically all the time, I see unattached veths after closing down the container.

I nearly always have to do a stop -f as a regular stop hangs. This is probably a clue?  I can't see any warnings in dmesg output.

**Comment by stgraber** [comment] 2016-07-27 07:47
No, I do mean network namespaces, but "ip netns" only lists those which were created with the ip command, not all of the ones the kernel currently has.

There is in fact no way to list all the network namespaces currently setup by the kernel (well, you could inspect the inode number of the netns of every process on the system but that won't tell you much).


Having to use --force to stop/restart, just means that the init system in your container isn't properly reacting to SIGPWR or SIGINT. --force has LXD kill PID1 in the container which then causes the kernel to get rid of everything else in the namespace.

**Comment by bigjools** [comment] 2016-08-01 05:54
Ok this looks like a kernel bug then. What do you want to do with it?

**Comment by stgraber** [comment] 2016-08-01 19:01
Can you file a kernel bug at https://launchpad.net/ubuntu/+source/linux ?

Include as good a reproducer as you have and hopefully one of the kernel folks can setup some tracing or something to figure out what's keeping your network namespace alive when all processes are gone.

**Comment by stgraber** [comment] 2016-08-26 21:39
Closing this issue as there's really nothing we can do about it at the LXD or even LXC level, this is a kernel refcounting bug in the network namespace (or something along those lines).

**Closed by stgraber** 2016-08-26 21:39 UTC
Labels: Incomplete
