### ISSUE TITLE
default profile under new created project works incorrectly

### ISSUE THREAD

**Issue by nanjj** [lxc/lxd#5493] opened 2019-02-14 15:44 UTC
# Required information

 * Distribution: ubuntu 18.04 amd64 snap
 * Distribution version: 3.10
 * The output of "lxc info" or if that fails:
```
config:
  cluster.https_address: 192.168.0.48:8443
  core.https_address: 192.168.0.48:8443
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  architectures:
  - x86_64
  - i686
  driver: lxc
  driver_version: 3.1.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-45-generic
  server: lxd
  server_pid: 22006
  server_version: "3.10"
  storage: zfs
  storage_version: 0.7.5-1ubuntu16.4
  server_clustered: true
```
# Issue description
New project works incorrectly
# Steps to reproduce
1. `lxc launch ubuntu:b test`,
2. `lxc project create nats`,
3. `lxc project switch nats`,
4. `lxc profile show default` =>
     ```
    config: {}
    description: Default LXD profile for project nats
    devices: {}
    name: default
    used_by: []
     ```
5. `lxc profile edit default` =>
     ```
     Config parsing error: failed to notify peer 192.168.0.46:8443: The following containers failed to update (profile change still saved):
      - test: The storage pool of the root disk can only be changed through move
      Press enter to open the editor again
     ```
Questions:
1. Since container test is under project default, and why profile default under project nats being updated, container test under project default being updated?
2. Why the default profile under project nats is empty?
 
# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment] 2019-02-14 15:56
I'll take a look, I thought I caught all of those...

**Comment by stgraber** [comment] 2019-02-15 23:31
@nanjj so I'm unable to reproduce this failure here.

```
root@vm02:~# lxc launch ubuntu:b test
To start your first container, try: lxc launch ubuntu:18.04

Creating test
Starting test 
root@vm02:~# lxc project create nats
Project nats created
root@vm02:~# lxc project switch nats
root@vm02:~# lxc profile show default
config: {}
description: Default LXD profile for project nats
devices: {}
name: default
used_by: []
root@vm02:~# lxc profile edit default
```

**Comment by stgraber** [comment] 2019-02-15 23:32
The default profile in your newly created project is empty because projects also have their own set of profiles. You can opt out of that by setting features.profiles=false when creating the project in which case the list of profiles will match what's in the default project.

**Comment by nanjj** [comment] 2019-02-22 04:36
@stgraber yes, use ubuntu:18.04 to launch. I alias `18.04` to `b` in my environment.
The problem I found is after I updated `default` profile under `nats` project, it notify container `test` under `default` project to update profile. I think it's incorrect.

**Comment by stgraber** [comment] 2019-02-22 14:26
@nanjj ubuntu:b and ubuntu:18.04 are the exact same thing just two aliases to the same image.

What did I miss in my steps above that you did to see this behavior? Editing the default project in nats is not causing a config update trigger to containers in the default project here.

**Comment by nanjj** [comment] 2019-02-28 07:56
@stgraber Look: https://asciinema.org/a/230483

**Comment by stgraber** [comment] 2019-02-28 09:33
Oh, I missed that this is clustered, I suspect that's the difference in code path.

**Comment by stgraber** [comment] 2019-02-28 10:23
Reproduced the issue on a test cluster, will look into the fix now.

**Comment by stgraber** [comment] 2019-02-28 10:36
Got a fix for this now.

**Closed** 2019-02-28 13:01 UTC
Labels: Bug
