### ISSUE TITLE
LXC's functionalities missing in LXD

### ISSUE THREAD

**Issue by jmdelafe** [lxc/lxd#3540] opened 2017-07-12 18:18 UTC
Hi there,

First of all, I want to congrats for the great work you're doing. This is one of the most active project that I've ever seen.

My situation: I have been an active user of LXC since it was released couple years ago. I used LXC with block devices (_loop_ if I use filesystems and _rbd_ if Ceph).

My question: Is there a plan to implement using a file image (or a _loop_ device) as _root_ for containers like LXC does? There's a Ceph compatibility entry in the roadmap but I don't see an approach to _loop_ devices :(

I know I can use ZFS or BRTFS and LVM as backend to acomplish that but I have my hands tied regarding the storage backend. LVM is the only one I could use but not in inmediate future :(

Thanks

**Comment by stgraber** [comment] 2017-07-12 18:27
So we did look at adding loop support in the past, but it just didn't fit with the features that LXD implements, specifically there wasn't any useful way for us to do snapshots.

That being said, you can trick LXD to do what you want. You can setup your storage to be the directory backend and then mount your container's filesystem on top of /var/lib/lxd/storage-pools/default/containers/NAME/rootfs or even (untested) set the raw.lxc config key in LXD to lxc.rootfs=/path/to/your/image, effectively bypassing LXD's storage handling.

Do note that both approaches aren't officially supported, will not work with snapshots and migration or file transfers when the container is stopped. The rest of the functionality should be mostly fine.

As for creating such containers, our default client only supports creating from an image so that won't quite work for you. Our API however does let you define an empty container ("none" type) which isn't backed by any image. That's what you'd want to use with either of the approaches above.

You can trigger this through curl with:

```bash
curl --unix-socket /var/lib/lxd/unix.socket -X POST -d '{"name": "some-name", source: {"type": "none"}}' lxd/1.0/containers
```

**Comment by jmdelafe** [comment] 2017-07-12 18:35
@stgraber, thanks.

> will not work with snapshots and migration or file transfers when the container is stopped

Snapshots will not work? Sad news :( What did you mean by "file transfers"?

**Comment by stgraber** [comment] 2017-07-12 18:41
"lxc file pull" and "lxc file push" can work even when the container isn't running, but if you're using a custom lxc.rootfs, then LXD won't know what to do and will tell you the files don't exist.

Should be fine if the container is running though.

**Comment by stgraber** [comment] 2017-07-12 18:44
And yeah, LXD snapshots are backend optimized. So we do LVM snapshots, btrfs subvolume snapshots, zfs snapshots. For the dir backend, we transfer the whole filesystem using rsync, which is terribly inefficient but still kinda works.

The problem is that on snapshot restore, we delete the source and copy the snapshot into place. If you're not using a normal directory path, the delete step will fail (as it's going to be a mountpoint), so yeah, snapshots are very unlikely to work if doing your own setup with loop devices.

I actually suspect that making the snapshots will succeed. In the first setup, it will actually snapshot the data but outside of the container's loop device, then likely fail on restore. In the second setup, it will very happily snapshot an empty "rootfs" directory for you, and restore it too. But as LXD won't be aware of where your data actually is (since you use lxc.rootfs to point somewhere else behind its back), the data itself won't be snapshotted.

**Comment by jmdelafe** [comment] 2017-07-12 18:52
That is, if we use the first setup, and the loop device is always mounted, snapshots will work, isn't it?

**Comment by stgraber** [comment] 2017-07-12 19:09
You'd have to test it. As I said above, I think that making the snapshots should work (they'll be stored on the host filesystem though, not as part of your loop device) but restoring them may fail.

**Comment by jmdelafe** [comment] 2017-07-12 19:13
Ok. I will try it and let you know. Thanks for your time.

**Comment by stgraber** [comment] 2017-07-13 20:57
Closing this as there's no LXD issue to work on here. Please comment if you run into problems with the snapshot restore. If it fails, it's something we could probably fix in LXD to help with people running such advanced setups.

**Closed by stgraber** 2017-07-13 20:57 UTC
