### ISSUE TITLE
lxd 3.0.3 clustered with ceph. Copy fails to start. 

### ISSUE THREAD

**Issue by vvolas** [lxc/lxd#5701] opened 2019-04-25 11:58 UTC
# Required information

 * Distribution:Buntu18.04
 * The output of "lxc info" or if that fails: Nothing, no output under /var/log either
   * LXD version:3.0.3 from official buntu repos.
   * Storage backend in use: ceph

Thing is I can start just 1 of these containers. I mean if I start rabit1 then I cant start rabit2 but if I will stop rabit1 then I can start rabit2. **With more copies of same machine still just 1 can be running on 1 server. But if I move 1 machine on 1 server second to another it does start.**

# Steps to reproduce
lxc launch ubuntu
lxc stop rabid-rabit
lxc copy rabid-rabit2
lxc start rabid-rabit
Error: Common start logic: invalid argument
Try `lxc info --show-log strong-muskrat2` for more info
log: is empty
no logs under /var/log/lxd/rabid-rabit except lxc.log.old which is empty.
main lxd.log
> t=2019-04-25T14:47:43+0300 lvl=info msg="Shutting down container" action=shutdown created=2019-04-25T14:46:27+0300 ephemeral=false name=strong-muskrat timeout=-1s used=2019-04-25T14:47:24+0300
> t=2019-04-25T14:47:45+0300 lvl=info msg="Shut down container" action=shutdown created=2019-04-25T14:46:27+0300 ephemeral=false name=strong-muskrat timeout=-1s used=2019-04-25T14:47:24+0300
> t=2019-04-25T14:47:58+0300 lvl=info msg="Creating container" ephemeral=false name=strong-muskrat2
> t=2019-04-25T14:47:59+0300 lvl=info msg="Created container" ephemeral=false name=strong-muskrat2
> t=2019-04-25T14:48:03+0300 lvl=warn msg="Unable to update backup.yaml at this time" name=strong-muskrat2
> t=2019-04-25T14:48:03+0300 lvl=warn msg="Unable to update backup.yaml at this time" name=strong-muskrat2
> t=2019-04-25T14:48:49+0300 lvl=warn msg="Unable to update backup.yaml at this time" name=strong-muskrat2
> t=2019-04-25T14:49:04+0300 lvl=warn msg="Unable to update backup.yaml at this time" name=strong-muskrat
> t=2019-04-25T14:49:04+0300 lvl=info msg="Starting container" action=start created=2019-04-25T14:46:27+0300 ephemeral=false name=strong-muskrat stateful=false used=2019-04-25T14:47:24+0300
> t=2019-04-25T14:49:05+0300 lvl=info msg="Started container" action=start created=2019-04-25T14:46:27+0300 ephemeral=false name=strong-muskrat stateful=false used=2019-04-25T14:47:24+0300
> t=2019-04-25T14:49:09+0300 lvl=warn msg="Unable to update backup.yaml at this time" name=strong-muskrat2
> t=2019-04-25T14:49:19+0300 lvl=eror msg="Failed to mount RBD storage volume for container \"strong-muskrat2\": invalid argument" 
> t=2019-04-25T15:00:33+0300 lvl=warn msg="Unable to update backup.yaml at this time" name=strong-muskrat2
> t=2019-04-25T15:00:43+0300 lvl=eror msg="Failed to mount RBD storage volume for container \"strong-muskrat2\": invalid argument"

**Comment by stgraber** [comment] 2019-04-25 12:43
Sounds like the filesystem UUID not being reset properly, I believe that's something we've fixed in later releases and should be fixed when we release 3.0.4.

Could you look at `dmesg` for any filesystem errors in there?

**Comment by vvolas** [comment] 2019-04-25 13:11
Yes you are right

> [Kt bal. 25 16:10:41 2019] XFS (rbd2): Filesystem has duplicate UUID fa323d85-c1d6-4dea-86c0-c30ce353c557 - can't mount
Sorry for dublicate.

**Comment by stgraber** [comment] 2019-04-25 13:15
Lets keep this issue around until I've confirmed that this is fixed in 3.12 and that the commit is queued for 3.0.4

**Comment by stgraber** [comment] 2019-04-26 15:14
Ok, so the issue is that CEPH based rbd copy doesn't reset the uuid whereas a local copy does, will fix

**Closed** 2019-04-26 23:07 UTC
