### ISSUE TITLE
lxd keeps deleted log opened

### ISSUE THREAD

**Issue by AceSlash** [lxc/lxd#7538] opened 2020-06-16 15:53 UTC
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04.4 LTS (Bionic Beaver) with HWE kernel 5.3.0-51-generic
 * The output of "lxc info" or if that fails:
```
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
- firewall_driver
- projects_limits
- container_syscall_intercept_hugetlbfs
- limits_hugepages
- container_nic_routed_gateway
- projects_restrictions
- custom_volume_snapshot_expiry
- volume_snapshot_scheduling
- trust_ca_certificates
- snapshot_disk_usage
- clustering_edit_roles
- container_nic_routed_host_address
- container_nic_ipvlan_gateway
- resources_usb_pci
- resources_cpu_threads_numa
- resources_cpu_core_die
- api_os
- resources_system
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 10.12.1.229:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
redacted
    -----END CERTIFICATE-----
  certificate_fingerprint: redacted
  driver: lxc
  driver_version: 4.0.2
  firewall: xtables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.3.0-51-generic
  lxc_features:
    cgroup2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_notify: "true"
  os_name: Ubuntu
  os_version: "18.04"
  project: default
  server: lxd
  server_clustered: false
  server_name: srv-229
  server_pid: 131380
  server_version: 4.0.1
  storage: zfs
  storage_version: 0.8.1-1ubuntu14.4
```
   * Storage backend in use: ZFS 0.8.1-1ubuntu14.4

# Issue description

On several servers, our monitoring system saw that the `/var` volumes were almost out of space. Analyze of the space used reveals that the space is taken by deleted log files still opened by LXD and visibly never closed.

This is an example on a server with 41 days uptime, which is not a lot by our standard (we live patch the kernel):
```
# lsof /var/|grep deleted | numfmt --field=7 --to=iec
dbus-daem  25895        messagebus    5r   REG  253,4       10M 6299789 /var/lib/sss/mc/initgroups (deleted)
lxd        26294              root    8w   REG  253,4      269M 2125827 /var/snap/lxd/common/lxd/logs/doc2/lxc.log (deleted)
lxd        26294              root   11u   REG  253,4       21K 2125832 /var/snap/lxd/common/lxd/logs/doc2/console.log (deleted)
rsyslogd   26325            syslog    6r   REG  253,4       10M 6299789 /var/lib/sss/mc/initgroups (deleted)
sssd       26405              root   15r   REG  253,4       10M 6299789 /var/lib/sss/mc/initgroups (deleted)
sssd_be    36222              root   19r   REG  253,4       10M 6299789 /var/lib/sss/mc/initgroups (deleted)
unattende  39487              root    3w   REG  253,4       112 5249090 /var/log/unattended-upgrades/unattended-upgrades-shutdown.log.1 (deleted)
lxd        41651              root    8w   REG  253,4      288M 3184845 /var/snap/lxd/common/lxd/logs/redacted-intranet/lxc.log (deleted)
lxd        41651              root   11u   REG  253,4      9.7K 3184854 /var/snap/lxd/common/lxd/logs/redacted-intranet/console.log (deleted)
lxd        42715              root    8w   REG  253,4      304M 6333512 /var/snap/lxd/common/lxd/logs/redacted-intranet-test/lxc.log (deleted)
lxd        42715              root   11u   REG  253,4      9.6K 6333515 /var/snap/lxd/common/lxd/logs/redacted-intranet-test/console.log (deleted)
lxd        43953              root    8w   REG  253,4      267M 7476553 /var/snap/lxd/common/lxd/logs/box/lxc.log (deleted)
lxd        43953              root   11u   REG  253,4      7.8K 7476560 /var/snap/lxd/common/lxd/logs/box/console.log (deleted)
lxd        44712              root    8w   REG  253,4      286M 3184856 /var/snap/lxd/common/lxd/logs/redacted-app/lxc.log (deleted)
lxd        44712              root   11u   REG  253,4      8.6K 3184863 /var/snap/lxd/common/lxd/logs/redacted-app/console.log (deleted)
lxd        45624              root    8w   REG  253,4      279M   21892 /var/snap/lxd/common/lxd/logs/db-doc-1/lxc.log (deleted)
lxd        45624              root   11u   REG  253,4      8.1K   21900 /var/snap/lxd/common/lxd/logs/db-doc-1/console.log (deleted)
lxd        50301              root    8w   REG  253,4      275M 6294723 /var/snap/lxd/common/lxd/logs/redacted-5/lxc.log (deleted)
lxd        50301              root   11u   REG  253,4      4.9K 6294728 /var/snap/lxd/common/lxd/logs/redacted-5/console.log (deleted)
lxd        51338              root   11u   REG  253,4      8.4K   13324 /var/snap/lxd/common/lxd/logs/pub-app-1/console.log (deleted)
lxd        51947              root    8w   REG  253,4      285M 6294729 /var/snap/lxd/common/lxd/logs/redacted-demo-7/lxc.log (deleted)
lxd        51947              root   11u   REG  253,4      5.8K 6294732 /var/snap/lxd/common/lxd/logs/redacted-demo-7/console.log (deleted)
lxd        53920              root    8w   REG  253,4      298M   21902 /var/snap/lxd/common/lxd/logs/redacted-redacted-admin-1/lxc.log (deleted)
lxd        53920              root   11u   REG  253,4      7.9K   21904 /var/snap/lxd/common/lxd/logs/redacted-redacted-admin-1/console.log (deleted)
lxd        54975              root    8w   REG  253,4       973 6293567 /var/snap/lxd/common/lxd/logs/redacted-wal-repository-1/lxc.log (deleted)
lxd        54975              root   11u   REG  253,4      6.8K 6294730 /var/snap/lxd/common/lxd/logs/redacted-wal-repository-1/console.log (deleted)
lxd        55923              root    8w   REG  253,4      283M 7476563 /var/snap/lxd/common/lxd/logs/redacted-ldap-1/lxc.log (deleted)
lxd        55923              root   11u   REG  253,4      8.6K 7476566 /var/snap/lxd/common/lxd/logs/redacted-ldap-1/console.log (deleted)
lxd        57834              root    8w   REG  253,4      287M 3403782 /var/snap/lxd/common/lxd/logs/redacted-priv-ns1/lxc.log (deleted)
lxd        57834              root   11u   REG  253,4      5.9K 3403791 /var/snap/lxd/common/lxd/logs/redacted-priv-ns1/console.log (deleted)
lxd        60148              root    8w   REG  253,4      287M 5252112 /var/snap/lxd/common/lxd/logs/pg-internal-2/lxc.log (deleted)
lxd        60148              root   11u   REG  253,4       17K 5252116 /var/snap/lxd/common/lxd/logs/pg-internal-2/console.log (deleted)
lxd        62021              root    8w   REG  253,4      291M 2121734 /var/snap/lxd/common/lxd/logs/pg-internal-3/lxc.log (deleted)
lxd        62021              root   11u   REG  253,4      4.7K 2121736 /var/snap/lxd/common/lxd/logs/pg-internal-3/console.log (deleted)
lxd        64365              root    8w   REG  253,4      299M   21907 /var/snap/lxd/common/lxd/logs/pgbouncer-dmz-redacted/lxc.log (deleted)
lxd        64365              root   11u   REG  253,4       12K   21909 /var/snap/lxd/common/lxd/logs/pgbouncer-dmz-redacted/console.log (deleted)
lxd        66469              root    8w   REG  253,4      289M 5252121 /var/snap/lxd/common/lxd/logs/priv-auth-ns1/lxc.log (deleted)
lxd        66469              root   11u   REG  253,4       18K 5252125 /var/snap/lxd/common/lxd/logs/priv-auth-ns1/console.log (deleted)
lxd        70344              root    8w   REG  253,4      298M 8521790 /var/snap/lxd/common/lxd/logs/redacted-prod-2/lxc.log (deleted)
lxd        70344              root   11u   REG  253,4       17K 8540416 /var/snap/lxd/common/lxd/logs/redacted-prod-2/console.log (deleted)
lxd        74429              root    8w   REG  253,4      284M 4229315 /var/snap/lxd/common/lxd/logs/repeater-1/lxc.log (deleted)
lxd        74429              root   11u   REG  253,4      8.9K 4229314 /var/snap/lxd/common/lxd/logs/repeater-1/console.log (deleted)
lxd        76671              root    8w   REG  253,4      275M 3403792 /var/snap/lxd/common/lxd/logs/st-redacted/lxc.log (deleted)
lxd        76671              root   11u   REG  253,4       17K 3403796 /var/snap/lxd/common/lxd/logs/st-redacted/console.log (deleted)
lxd        80025              root    8w   REG  253,4      283M   21918 /var/snap/lxd/common/lxd/logs/st-disco-1/lxc.log (deleted)
lxd        80025              root   11u   REG  253,4       17K   21920 /var/snap/lxd/common/lxd/logs/st-disco-1/console.log (deleted)
lxd        82834              root    8w   REG  253,4      283M 3403798 /var/snap/lxd/common/lxd/logs/st-relay-1/lxc.log (deleted)
lxd        82834              root   11u   REG  253,4       17K 3403813 /var/snap/lxd/common/lxd/logs/st-relay-1/console.log (deleted)
lxd        85005              root    8w   REG  253,4      290M 6294734 /var/snap/lxd/common/lxd/logs/still-terrapin/lxc.log (deleted)
lxd        85005              root   11u   REG  253,4       17K 6294736 /var/snap/lxd/common/lxd/logs/still-terrapin/console.log (deleted)
lxd        88531              root    8w   REG  253,4      280M   13325 /var/snap/lxd/common/lxd/logs/wiki-redacted/lxc.log (deleted)
lxd        88531              root   11u   REG  253,4      9.3K   13330 /var/snap/lxd/common/lxd/logs/wiki-redacted/console.log (deleted)
lxd       131380              root   22w   REG  253,4         0 6293564 /var/snap/lxd/common/lxd/logs/redacted-wal-repository-1/lxc.log.old (deleted)
lxd       144579              root    8w   REG  253,4       756   21899 /var/snap/lxd/common/lxd/logs/pub-auth-ns1/lxc.log (deleted)
lxd       144579              root   11u   REG  253,4       14K   21908 /var/snap/lxd/common/lxd/logs/pub-auth-ns1/console.log (deleted)
```
The issue didn't appear just after the reboot and change to kernel HWE but 23 days after, as you can see here:
![var_space](https://user-images.githubusercontent.com/5392990/84797477-2b380d80-affa-11ea-9b61-f5382b3c7ce1.png)

If you have an idea how to fix it without rebooting the server, that would be nice.

# Steps to reproduce

 1. Run any container
 2. Wait

# Information to attach

Should be self-explanatory, tell me if any more logs are necessary.

**Comment by AceSlash** [comment] 2020-06-16 16:01
Update: restart of the corresponding container does close the deleted log file and reclaims the space.

**Comment by stgraber** [comment] 2020-06-16 16:12
Unable to reproduce this behavior here nor finding any evidence of it on any of our long running servers.

Please show:
 - `ps fauxww`
 - `ls -lh /proc/$(cat /var/snap/lxd/common/lxd.pid)/fd/`

**Comment by AceSlash** [comment] 2020-06-16 17:58
I have restarted several containers to reclaim some space, so here is the lsof and the ls -lh:
```
# lsof /var/|grep deleted | numfmt --field=7 --to=iec
dbus-daem  25895        messagebus    5r   REG  253,4       10M 6299789 /var/lib/sss/mc/initgroups (deleted)
lxd        26294              root    8w   REG  253,4      271M 2125827 /var/snap/lxd/common/lxd/logs/doc2/lxc.log (deleted)
lxd        26294              root   11u   REG  253,4       21K 2125832 /var/snap/lxd/common/lxd/logs/doc2/console.log (deleted)
rsyslogd   26325            syslog    6r   REG  253,4       10M 6299789 /var/lib/sss/mc/initgroups (deleted)
sssd       26405              root   15r   REG  253,4       10M 6299789 /var/lib/sss/mc/initgroups (deleted)
sssd_be    36222              root   19r   REG  253,4       10M 6299789 /var/lib/sss/mc/initgroups (deleted)
unattende  39487              root    3w   REG  253,4       112 5249090 /var/log/unattended-upgrades/unattended-upgrades-shutdown.log.1 (deleted)
lxd        43953              root    8w   REG  253,4      269M 7476553 /var/snap/lxd/common/lxd/logs/box/lxc.log (deleted)
lxd        43953              root   11u   REG  253,4      7.8K 7476560 /var/snap/lxd/common/lxd/logs/box/console.log (deleted)
lxd        45624              root    8w   REG  253,4      281M   21892 /var/snap/lxd/common/lxd/logs/db-doc-1/lxc.log (deleted)
lxd        45624              root   11u   REG  253,4      8.1K   21900 /var/snap/lxd/common/lxd/logs/db-doc-1/console.log (deleted)
lxd        50301              root    8w   REG  253,4      277M 6294723 /var/snap/lxd/common/lxd/logs/app1-5/lxc.log (deleted)
lxd        50301              root   11u   REG  253,4      4.9K 6294728 /var/snap/lxd/common/lxd/logs/app1-5/console.log (deleted)
lxd        51947              root    8w   REG  253,4      286M 6294729 /var/snap/lxd/common/lxd/logs/app1-demo-7/lxc.log (deleted)
lxd        51947              root   11u   REG  253,4      5.8K 6294732 /var/snap/lxd/common/lxd/logs/app1-demo-7/console.log (deleted)
lxd        55923              root    8w   REG  253,4      284M 7476563 /var/snap/lxd/common/lxd/logs/cust1-ldap-1/lxc.log (deleted)
lxd        55923              root   11u   REG  253,4      8.6K 7476566 /var/snap/lxd/common/lxd/logs/cust1-ldap-1/console.log (deleted)
lxd        57834              root    8w   REG  253,4      288M 3403782 /var/snap/lxd/common/lxd/logs/cust1-priv-ns1/lxc.log (deleted)
lxd        57834              root   11u   REG  253,4      5.9K 3403791 /var/snap/lxd/common/lxd/logs/cust1-priv-ns1/console.log (deleted)
lxd        60148              root    8w   REG  253,4      289M 5252112 /var/snap/lxd/common/lxd/logs/pg-internal-2/lxc.log (deleted)
lxd        60148              root   11u   REG  253,4       17K 5252116 /var/snap/lxd/common/lxd/logs/pg-internal-2/console.log (deleted)
lxd        62021              root    8w   REG  253,4      293M 2121734 /var/snap/lxd/common/lxd/logs/pg-internal-3/lxc.log (deleted)
lxd        62021              root   11u   REG  253,4      4.7K 2121736 /var/snap/lxd/common/lxd/logs/pg-internal-3/console.log (deleted)
lxd        64365              root    8w   REG  253,4      300M   21907 /var/snap/lxd/common/lxd/logs/pgbouncer-dmz-loc1/lxc.log (deleted)
lxd        64365              root   11u   REG  253,4       12K   21909 /var/snap/lxd/common/lxd/logs/pgbouncer-dmz-loc1/console.log (deleted)
lxd        80025              root    8w   REG  253,4      284M   21918 /var/snap/lxd/common/lxd/logs/st-disco-1/lxc.log (deleted)
lxd        80025              root   11u   REG  253,4       17K   21920 /var/snap/lxd/common/lxd/logs/st-disco-1/console.log (deleted)
lxd        82834              root    8w   REG  253,4      284M 3403798 /var/snap/lxd/common/lxd/logs/st-relay-1/lxc.log (deleted)
lxd        82834              root   11u   REG  253,4       17K 3403813 /var/snap/lxd/common/lxd/logs/st-relay-1/console.log (deleted)
lxd       131380              root   22w   REG  253,4         0 6293564 /var/snap/lxd/common/lxd/logs/app2-repository-1/lxc.log.old (deleted)
lxd       144579              root    8w   REG  253,4       756   21899 /var/snap/lxd/common/lxd/logs/pub-auth-ns1/lxc.log (deleted)
lxd       144579              root   11u   REG  253,4       14K   21908 /var/snap/lxd/common/lxd/logs/pub-auth-ns1/console.log (deleted)
```
```
total 0
lr-x------ 1 root root 64 Jun  4 20:18 0 -> /dev/null
lrwx------ 1 root root 64 Jun  4 20:18 1 -> socket:[1837314010]
lr-x------ 1 root root 64 Jun  4 20:18 10 -> pipe:[1837328731]
l-wx------ 1 root root 64 Jun  4 20:18 11 -> pipe:[1837328731]
lr-x------ 1 root root 64 Jun  4 20:18 12 -> pipe:[1837328732]
l-wx------ 1 root root 64 Jun  4 20:18 13 -> pipe:[1837328732]
lrwx------ 1 root root 64 Jun  4 20:18 14 -> anon_inode:[eventfd]
lrwx------ 1 root root 64 Jun  4 20:18 15 -> socket:[1837321744]
lr-x------ 1 root root 64 Jun  4 20:18 16 -> /dev/null
lrwx------ 1 root root 64 Jun  4 20:18 17 -> socket:[1837330214]
lrwx------ 1 root root 64 Jun  4 20:18 18 -> socket:[1837314024]
lrwx------ 1 root root 64 Jun  4 20:18 19 -> socket:[1837314028]
lrwx------ 1 root root 64 Jun  4 20:18 2 -> socket:[1837314010]
lrwx------ 1 root root 64 Jun  4 20:18 20 -> socket:[1837314029]
lrwx------ 1 root root 64 Jun  4 20:18 21 -> socket:[1837321745]
l-wx------ 1 root root 64 Jun  4 20:18 22 -> /var/snap/lxd/common/lxd/logs/app2-repository-1/lxc.log.old (deleted)
l-wx------ 1 root root 64 Jun  4 19:39 24 -> /var/snap/lxd/common/lxd/logs/app1-5/lxc.log
l-wx------ 1 root root 64 Jun 16 03:36 25 -> /var/snap/lxd/common/lxd/logs/db-doc-1/lxc.log
l-wx------ 1 root root 64 Jun 15 03:36 26 -> /var/snap/lxd/common/lxd/logs/pub-app-1/lxc.log
l-wx------ 1 root root 64 Jun  4 20:18 27 -> /var/snap/lxd/common/lxd/database/global/open-2
l-wx------ 1 root root 64 Jun  4 20:18 28 -> /var/snap/lxd/common/lxd/database/global/open-3
lr-x------ 1 root root 64 Jun  4 20:18 29 -> anon_inode:inotify
l-wx------ 1 root root 64 Jun  5 03:25 3 -> /var/snap/lxd/common/lxd/database/global/open-4
lrwx------ 1 root root 64 Jun  4 20:18 30 -> socket:[1837337608]
lrwx------ 1 root root 64 Jun 13 01:39 31 -> anon_inode:[eventfd]
l-wx------ 1 root root 64 Jun 16 03:37 32 -> /var/snap/lxd/common/lxd/logs/box/lxc.log
l-wx------ 1 root root 64 Jun  4 20:18 4 -> /var/snap/lxd/common/lxd/logs/lxd.log
lrwx------ 1 root root 64 Jun  4 20:18 5 -> anon_inode:[eventpoll]
lrwx------ 1 root root 64 Jun  4 20:18 57 -> socket:[1837328735]
lr-x------ 1 root root 64 Jun  4 20:18 6 -> pipe:[1837318010]
l-wx------ 1 root root 64 Jun  4 20:18 7 -> pipe:[1837318010]
lrwx------ 1 root root 64 Jun  4 20:18 8 -> /var/snap/lxd/common/lxd/database/local.db
lrwx------ 1 root root 64 Jun  4 20:18 9 -> anon_inode:[eventpoll]
```
Unfortunately, it's very very long to look at the ps output and anonymize everything, there are critical production data so I can't give you the output since I may miss something. If you can narrow down what you need, I'll can give you a more succinct extract.

**Comment by stgraber** [comment] 2020-06-16 18:52
I need to know what every one of the PIDs listed in your lsof refer to.

**Comment by stgraber** [comment] 2020-06-16 18:52
The listing above shows that LXD itself is not holding those files open which matches what I'm seeing here, so it's something else, likely a subproces of LXD or the LXC monitor which is keeping those open.

**Comment by stgraber** [comment] 2020-06-19 23:03
Any update on this?

**Comment by stgraber** [comment] 2020-06-22 21:38
Closing for now as we can't reproduce it and the information needed to track it down is missing.

**Closed by stgraber** 2020-06-22 21:38 UTC
Labels: Incomplete

**Comment by AceSlash** [comment] 2020-06-26 09:45
Same issue as #3459 .

**Comment by stgraber** [comment] 2020-06-26 13:32
The latest version of the snap in stable has the fix cherry-picked. Note that it won't help with logs that are already overly large but at least they won't grow more than that.

**Comment by aivanise** [comment] 2023-05-14 21:42
i still see this in 5.11. I can reproduce it by doing lxc rm -f container; lxc launch image container a couple of times in a row, but also happens on long running containers

in the example below, BTI22 has an uptime of 48 days, whereas AUA21 has been rebuilt several times today

# lsof +L1
COMMAND     PID     USER   FD   TYPE DEVICE SIZE/OFF NLINK   NODE NAME
lxd        8479     root    8w   REG   0,45      706     0   1281 /var/snap/lxd/common/lxd/logs/BTI22/lxc.log (deleted)
lxd        8479     root   46u   REG   0,45     8131     0   1283 /var/snap/lxd/common/lxd/logs/BTI22/console.log (deleted)
lxd      435281     root   33w   REG   0,45        0     0   3922 /var/snap/lxd/common/lxd/logs/AUA21/lxc.log.old (deleted)
lxd      435281     root   35w   REG   0,45        0     0   3692 /var/snap/lxd/common/lxd/logs/AUA21/lxc.log.old (deleted)
lxd      435281     root   40w   REG   0,45        0     0   4305 /var/snap/lxd/common/lxd/logs/AUA21/lxc.log.old (deleted)

systemctl reload snap.lxd.daemon resolves it, but its still annoying
