### ISSUE TITLE
How to recreate deleted shared library symlink in a container?

### ISSUE THREAD

**Issue by 10101010101010001** [lxc/lxd#8046] opened 2020-10-16 16:45 UTC
# Required information

 * Distribution: Ubuntu 
 * Distribution version: focal 20.04, container 18.04
 * The output of "lxc info"
Name: sql
Location: none
Remote: unix://
Architecture: x86_64
Created: 2020/05/19 15:32 UTC
Status: Running
Type: container
Profiles: public
Pid: 1021997
Ips:
  eth2: inet    172.#.#.#   eno2np1
  lo:   inet    127.0.0.1
  eth1: inet    10.#.#.#  eno1np0
  eth1: inet6   ffff::436:3eff:fe2f:1416        eno1np0
Resources:
  Processes: 4
  Disk usage:
    root: 34.32TB
  CPU usage:
    CPU usage (in seconds): 6145
  Memory usage:
    Memory (current): 608.73MB
    Memory (peak): 32.44GB
  Network usage:
    eth1:
      Bytes received: 1.16GB
      Bytes sent: 88.74MB
      Packets received: 649491
      Packets sent: 280913
    eth2:
      Bytes received: 15.12MB
      Bytes sent: 1.35MB
      Packets received: 193625
      Packets sent: 982
    lo:
      Bytes received: 33.53MB
      Bytes sent: 33.53MB
      Packets received: 82550
      Packets sent: 82550

Log:
lxc sql 20201016161330.501 ERROR    attach - attach.c:lxc_attach_run_command:1451 - No such file or directory - Failed to exec "ln -s  /lib/x86_64-linux-gnu/libc.so.6 libc-2.27.so"

# Issue description

A brief description of the problem. Should include what you were
attempting to do, what you did, what happened and what you expected to
see happen.

Mistakenly removed shared library symlink "rm /lib/x86_64-linux-gnu/libc.so.6" where  **/lib/x86_64-linux-gnu/libc.so.6 -> libc-2.27.so** 

Could you provide any guidance on undoing this? Looks on baremetal you could boot into resuce mode and install via rpm.

# Steps to reproduce
$ lxc create test-container
$ lxc exec test-container -- 'rm /lib/x86_64-linux-gnu/libc.so.6'

$ lxc exec test-container bash
bash: error while loading shared libraries: libc.so.6: cannot open shared object file: No such file or directory

**Comment by stgraber** [comment] 2020-10-16 16:52
I very much doubt you could boot such a system even with rescue mode :)
It's true that you could for most libraries, but your C library would prevent anything from running.

In this case, a workaround may be:
 - lxc file pull test-container/lib/x86_64-linux-gnu/libc-2.27.so .
 - lxc file push libc-2.27.so test-container/lib/x86_64-linux-gnu/libc.so.6

This doesn't make it back into a symlink, you'll have to fix that later on, but it should give you a working C library again.

**Comment by stgraber** [comment] 2020-10-16 16:52
(Closing as not a bug, support questions are usually better handled at https://discuss.linuxcontainers.org)

**Closed by stgraber** 2020-10-16 16:52 UTC

**Comment by stgraber** [comment] 2020-10-16 16:54
Ah, just thought of an alternative which may or may not work.

`lxc exec test-container /bin/busybox sh`

This assumes the presence of a static busybox, but there's a good chance that your distro will have one.

**Comment by 10101010101010001** [comment] 2020-10-16 17:02
@stgraber  Thanks for your help in resolving this. I really appreciate all your hard work, I've learned a lot from your forum posts, keep it up!!!
