### ISSUE TITLE
lxc stop should support --console

### ISSUE THREAD

**Issue by brauner** [lxc/lxd#8546] opened 2021-03-11 07:43 UTC
While `lxc start` and `lxc restart` already support `--console` the `lxc stop` subcommand doesn't but often it is quite useful to see the shutdown sequence of an instance without having to pull it from the console log afterwards. I would expect
```
lxc stop --console <instance>
```
to first connect to the instance console and then initialize the actual shutdown so no messages get lost.

**Comment by stgraber** [comment] 2021-03-11 12:57
@brauner want to send a PR?
Should be trivial to do in lxc/action.go, just make sure not to allow it when --force is passed.

**Comment by Fl4v** [comment] 2021-03-11 22:29
@stgraber I am trying to improve my golang skills, I am happy to take this on.

**Comment by stgraber** [comment] 2021-03-11 22:40
Sure, assigned it to you!

**Comment by Fl4v** [comment] 2021-03-14 19:36
@stgraber Do you know if lxd plays nicely with WSL2? I have followed the docs and the build completed succesfully, however, when I invoke lxd, it just hangs, nothing happens.

**Comment by stgraber** [comment] 2021-03-14 19:38
@Fl4v I believe it's possible to make it work, but you indeed need to start it manually as there is no systemd daemon running on WSL2.

Normally I'd expect you to run `lxd --debug` in one terminal, this should show some initialization messages and then hang once it's ready to process requests. In another terminal you should then be able to run `lxc list` and similar commands.

**Comment by Fl4v** [comment] 2021-03-14 19:45
Thanks, I will give it a Go!

**Comment by Fl4v** [comment] 2021-03-18 22:07
Hi @stgraber, I do have another question. Let's say I have made some changes and want to test them, would I just need to run `make deps`?

**Comment by tomponline** [comment] 2021-03-18 22:14
Just `make` is sufficient if you already have a full build (including the `make deps` step).

**Comment by Fl4v** [comment] 2021-03-20 18:23
Ok, so I have made the appropriate changes to allow `--console` to be passed to the stop action, I have also made sure not to allow it if `--force` was present. However, this is all I get:

```bash
To detach from the console, press: <ctrl>+a q
Error: Instance is not running
```

I believe that the instance is shut down before the console can actually read the stop sequence. If you can point me in the right direction, that would be great.

**Comment by stgraber** [comment] 2021-03-20 18:55
Can you send a PR with your code? It would make it easier to see what's going on.
I suspect the issue is that you're calling the console logic after the stop action was sent (and possibly completed).

Instead for stop, it'd make sense to start the console prior to actually processing the action.

**Comment by Fl4v** [comment] 2021-03-20 18:58
Hi @stgraber, I have submitted the PR: https://github.com/lxc/lxd/pull/8588

**Comment by stgraber** [comment] 2021-03-20 19:02
Right, as I suspected the issue is that the call to spawn the console is happening too late in the stop case.

So you need to start the console before the `UpdateInstanceState` call when the action is stop.
And you need to modify the call to the console later in that function to exclude stop.

That way the console should get attached just prior to the shutdown command being sent out to the instance.

**Comment by Fl4v** [comment] 2021-03-20 19:05
Ok, I think that makes sense, thank you.

**Comment by Fl4v** [comment] 2021-03-21 18:42
Hi @stgraber I have made good progress and I will soon be ready to update my PR. Before I do so, I noticed that this is displayed: `To detach from the console, press: <ctrl>+a q`, which makes sense to present when you are starting or restarting your instance, however, I think it's superfluous when you are stopping the instance. Do you agree? Do you want me to amend the Console function so it can accept an extra argument: `Action`, and when the `Action` is `stop` the above won't be displayed.

**Comment by stgraber** [comment] 2021-03-21 22:53
It's still relevant as `lxc stop` just asks the instance to shutdown, if the init system in the instance does not actually shut it down, you will need to detach from the console and run `lxc stop --force` or go fix things with `lxc exec`.

**Comment by Fl4v** [comment] 2021-03-22 09:24
Makes sense. I have pushed my recent changes: https://github.com/lxc/lxd/pull/8588, I had to attach the console after `UpdateInstanceState` otherwise the instance would have never been shutdown.

**Closed** 2021-03-23 20:11 UTC
Labels: Easy, Feature
