### ISSUE TITLE
lxc start failed with error: Error calling 'lxd forkstart wedgeiq /var/lib/lxd/containers /var/log/lxd/wedgeiq/lxc.conf': err='exit status 1'

### ISSUE THREAD

**Issue by gusijia** [lxc/lxd#3552] opened 2017-07-14 15:59 UTC
* The output of "lxc info"
```
Name: wedgeiq
Remote: unix:/var/lib/lxd/unix.socket
Architecture: x86_64
Created: 2017/07/07 22:31 UTC
Status: Running
Type: persistent
Profiles: int-mgmt0
Pid: 22006
Ips:
  lo:	inet	127.0.0.1
  lo:	inet6	::1
  eth0:	inet	10.50.0.145
  eth0:	inet6	fe80::216:3eff:fee9:bd28
Resources:
  Processes: 279
  Disk usage:
    root: 1.85GB
  Memory usage:
    Memory (current): 1.35GB
    Memory (peak): 1.38GB
  Network usage:
    eth0:
      Bytes received: 88.18kB
      Bytes sent: 38.12kB
      Packets received: 280
      Packets sent: 337
    lo:
      Bytes received: 1.27MB
      Bytes sent: 1.27MB
      Packets received: 6682
      Packets sent: 6682
```
error: Error calling 'lxd forkstart wedgeiq /var/lib/lxd/containers /var/log/lxd/wedgeiq/lxc.conf': err='exit status 1'
```
  lxc 20170714111600.680 ERROR lxc_conf - conf.c:setup_netdev:2366 - failed to set 'eth0' up : Device or resource busy
  lxc 20170714111600.680 ERROR lxc_conf - conf.c:setup_network:2467 - failed to setup netdev
  lxc 20170714111600.680 ERROR lxc_conf - conf.c:lxc_setup:3844 - failed to setup the network for 'wedgeiq'
  lxc 20170714111600.680 ERROR lxc_start - start.c:do_start:811 - Failed to setup container "wedgeiq".
  lxc 20170714111600.681 ERROR lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 3)
  lxc 20170714111600.681 ERROR lxc_start - start.c:__lxc_start:1346 - Failed to spawn container "wedgeiq".
  lxc 20170714111601.239 ERROR lxc_conf - conf.c:run_buffer:405 - Script exited with status 1.
  lxc 20170714111601.239 ERROR lxc_start - start.c:lxc_fini:546 - Failed to run lxc.hook.post-stop for container "wedgeiq".# Issue description
```

This happened occasionally when I run the script on jenkins and it never happen when I run it manually.

**Comment by stgraber** [comment] 2017-07-14 21:05
Can you paste the output of "lxc config show --expanded wedgeiq"?

**Comment by gusijia** [comment] 2017-07-14 21:10
@stgraber the output of "lxc config show --expanded wedgeiq" is 
architecture: x86_64
config:
  boot.autostart: "true"
  limits.cpu: "2"
  limits.memory: 2GB
  user.user-data: |
    #cloud-config
    ssh_authorized_keys:
     - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDWj6Iv5VOm8tCdbOIu5FUrgTZSVJogt7f4mSQuLVLzXKDMfc1vLRltruYg326CVWicvvaYNp5EZbcj5UqyLE/4HBGUn33uUKPoxtHpLaM7jrjDf9ExJzNItWbafMGZKrP9+v49MrIgrFmE1pwMWQVJnFkIkBXo8IPExEMvJnBMHiLDZ3OLGy1rf838orIZ4X0enrLzJRTrbh3j7/wa0ef8YwGRDsTDWXig7ajGKcAsctpWP4/5hCOPuPmA0RG+kLs3N7ao1kyB2LRFbjzTO/qkOIXwkpoQOwd9iCQPp8nZrN2Jvijf6c6lPM3ftldxY3QMFdLLhNjqAZUJ7ksb3Csn created-by-lxc_start.sh
  volatile.base_image: 7a7ff654cbd8f5f09bec03aa19d8d7d92649127d18659036a963b1ea63f90d25
  volatile.eth0.hwaddr: 00:16:3e:e9:bd:28
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    name: eth0
    nictype: macvlan
    parent: ens160
    type: nic
  root:
    path: /
    size: 20GB
    type: disk
ephemeral: false
profiles:
- int-mgmt0

**Comment by stgraber** [comment] 2017-07-14 21:13
Thanks, so that's an issue with the network device being brought up after it's created by liblxc, odd.

Can you also paste the output of "lxc info" (without any argument passed to it)?

**Comment by stgraber** [comment] 2017-07-14 21:13
I want to check what's the LXC version in use on the system so I can make sure that the error string is indeed only returned if the issue is with the device being brought up, rather than say, with it being created (which would be a more logical place for such an error to occur).

**Comment by stgraber** [comment] 2017-07-14 21:15
I can see some other reports of such issues out there, but no clear link between kernel version, device type, ... just random people saying that "Device or resource busy" randomly happened to them (none of those are directly tied to LXD/LXC, most are just plain old ethX physical devices).

**Comment by gusijia** [comment] 2017-07-14 21:17
@stgraber the output for "lxc info"
config:
  storage.zfs_pool_name: pool1
apiextensions:
- id_map
apistatus: stable
apiversion: "1.0"
auth: trusted
public: false
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFfDCCA2SgAwIBAgIQIZQ+TJm6Q6CreUYdAn2NBjANBgkqhkiG9w0BAQsFADA8
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRwwGgYDVQQDDBNyb290QHJv
    Ym90ZnJhbWV3b3JrMB4XDTE3MDcwNzIyMzEwNloXDTI3MDcwNTIyMzEwNlowPDEc
    MBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEcMBoGA1UEAwwTcm9vdEByb2Jv
    dGZyYW1ld29yazCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAOh0OoTT
    FpNpRZycEAVbDqAITvZP9B8cOX6Fy+HQkkAKMTpStQtvVWQLbKTpvwvb+66ewx4N
    B/V/rnupM6IyC6D55kzcECz+gSBKppG1X3FZZecG00RN4j9xKSuwGm6Cv3PI04Fe
    swNk/neMbYJfJ0d/+xtnz2OUD6JYVL67l3ufw35rTlaT+Sf4vrmcXxt6DTKuVyPO
    NRCXuUcHGfnSXhQbIawbczTJ1HMy73smBEaHoLcGxHdm6XAgYR8TrWbruUOX6mj2
    yKwcBL+CADNjuAAxJPGV2unF/8fwlLctzPio4cQb7A73wVsRpaOPlOJ4MZnSyHNx
    N0W+E8zbFRFNxdj/uCoFefVmxugQ07y1kawDD+viRcvko2vqrcGL0JXzdTh2TN4I
    eASiMlFDKvRRD5X78xqugIoycHYLZi7iqYS3SwX/OTPcfPWX8pgPXb8oqU3rFrDK
    rArWlfYGOqHFiJ9BbJ8ZkU2kXQ+/RvaRCGNdG4cAbhXtKVDiSZN3/UtaMXFIf8sy
    DTAfhRhCaJHZfudbN4pS8zoRQ5swDH0gdK2z6XA519yUfgLZvodw/qk+VweZN+EI
    i+VPegytyIgLHdOo88XK6nokkAOcLVDpuudqrs9J63XpPuhzl+Gx1jRUXvc4YQBY
    7rFUbmb5P0gjVQ5s0zPTL98uH79e8b+LSnmfAgMBAAGjejB4MA4GA1UdDwEB/wQE
    AwIFoDATBgNVHSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMEMGA1UdEQQ8
    MDqCDnJvYm90ZnJhbWV3b3JrhwQKMgAKhwSsEgABhwSsEQABhwSsFAABhwSsEgIB
    hwQKAAMBhwQKMgCPMA0GCSqGSIb3DQEBCwUAA4ICAQAnJcA1YmP3n4Hn2CDzml4/
    N8zwhgevq787EN32w8nB2lv6FYCxdUkEpw2/KhvqZfYg77n8ZOTKWCNNjpHGlqN0
    lb3TwRUUPYp6EgkSXwTYDL1Fq2TRTsFSeVO4CT6vCug8QC0InUxOyZOFANqHBDFx
    X4CV67Fkg1EBKAnBAtM1Zyh0YVOX0kwsn6H1FOT0Ib84BLHb6/XSRosr+eKJvH/Q
    uXf/tQLoHSw4rpWRrN7Chykf0qotCPLkhJwRlYb5IlM9RkUAv+Ax3++Fjmu4T8t/
    UyrZaoS63088AY8H+CMr6yQPT3WEdq6u+/3UQm29MIFe+jK3CLgPowj41u5jAaae
    t9QYnY9eAdUAS2Lt51tiv+K0s5okCOT0EFnpT5VEUsM0+lehR1XtJL/pjBkMqpBg
    tTS6jIUMlJzOpJ/ALlDvGa6piDf0t3RzxrHUOusylgDps+Smei+D+uCIDJvHRwJQ
    Jg63g8Fz/IqKgX2wJBJ+JoJeTs4C1vR84hdL97pzc1/O6ArMtnag1tkOYS/okvIm
    K53FqcvPbstuxLGr64Ij8Fg/eAhYyGW0fc6kPIGMe8P1GiWG132WkDYo/txc59dV
    y1mEpsnuobrJJaiOWE50LAF+9qlYjRDtsnmImqGwytEOWVTyGj9BWFdkL7qpxkSP
    Pbl7t/6CzTHiRmhdaIEfsQ==
    -----END CERTIFICATE-----
  certificatefingerprint: ea0cbe56d26bad0cf95bcab0629f1244e1cb8553ba40e704f7aaa74d25605e4e
  driver: lxc
  driverversion: 2.0.7
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-83-generic
  server: lxd
  serverpid: 4386
  serverversion: 2.0.9
  storage: zfs
  storageversion: "5"

**Comment by gusijia** [comment] 2017-07-14 21:18
@stgraber I find someone have the same issue with me but without an answer. https://lists.linuxcontainers.org/pipermail/lxc-users/2014-October/007941.html

**Comment by stgraber** [comment] 2017-07-14 23:44
Hmm, so it looks like it may actually be a hardware limitation. Cards which can only have a very low number of concurent MAC addresses will refuse to bring up additional MACs...

**Comment by stgraber** [comment] 2017-07-14 23:46
Does the kernel log anything else in "dmesg"? It'd be kinda nice if it would make this clearer than with this pretty useless syscall response :)

**Comment by stgraber** [comment] 2017-07-14 23:50
What's your underlying NIC and driver?

**Comment by stgraber** [comment] 2017-07-14 23:53
Can you also paste "lxc config show --expanded" of all your containers using macvlan on this particular parent device? Looking at the macvlan code, some kind of MAC duplication would also lead to this error.

**Comment by gusijia** [comment] 2017-07-17 20:38
@stgraber Nothing was logged in dmesg. what do you mean underlying NIC and driver? The host is a ubuntu 16.04 vm running in exsi server. the output of "lxc config show --expanded" is only: 
config:
  storage.zfs_pool_name: pool1

**Comment by stgraber** [comment] 2017-07-17 22:18
"lspci -nnn" on the host should help

**Comment by stgraber** [comment] 2017-07-17 22:19
for "lxc config show --expanded", I meant "lxc config show --expanded NAME" where NAME is the name of every single one of your containers that's using that particular parent device.

**Comment by stgraber** [comment] 2017-07-17 22:19
I'm trying to confirm that there's no MAC conflicts within the data that LXD has about the containers, since that would cause the error you received.

**Comment by gusijia** [comment] 2017-07-17 22:24
root@robotframework:~/jenkins/workspace/robot-deploy/robot/script$ lxc config show --expanded wedgeds
architecture: x86_64
config:
  boot.autostart: "true"
  user.user-data: |
    #cloud-config
    ssh_authorized_keys:
     - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDWj6Iv5VOm8tCdbOIu5FUrgTZSVJogt7f4mSQuLVLzXKDMfc1vLRltruYg326CVWicvvaYNp5EZbcj5UqyLE/4HBGUn33uUKPoxtHpLaM7jrjDf9ExJzNItWbafMGZKrP9+v49MrIgrFmE1pwMWQVJnFkIkBXo8IPExEMvJnBMHiLDZ3OLGy1rf838orIZ4X0enrLzJRTrbh3j7/wa0ef8YwGRDsTDWXig7ajGKcAsctpWP4/5hCOPuPmA0RG+kLs3N7ao1kyB2LRFbjzTO/qkOIXwkpoQOwd9iCQPp8nZrN2Jvijf6c6lPM3ftldxY3QMFdLLhNjqAZUJ7ksb3Csn created-by-lxc_start.sh
  volatile.base_image: 7a7ff654cbd8f5f09bec03aa19d8d7d92649127d18659036a963b1ea63f90d25
  volatile.eth0.hwaddr: 00:16:3e:42:e1:4d
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    name: eth0
    nictype: macvlan
    parent: ens160
    type: nic
  root:
    path: /
    type: disk
ephemeral: false
profiles:
- int-mgmt0
root@robotframework:~/jenkins/workspace/robot-deploy/robot/script$ lxc config show --expanded wedgeiq
architecture: x86_64
config:
  boot.autostart: "true"
  limits.cpu: "2"
  limits.memory: 2GB
  user.user-data: |
    #cloud-config
    ssh_authorized_keys:
     - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDWj6Iv5VOm8tCdbOIu5FUrgTZSVJogt7f4mSQuLVLzXKDMfc1vLRltruYg326CVWicvvaYNp5EZbcj5UqyLE/4HBGUn33uUKPoxtHpLaM7jrjDf9ExJzNItWbafMGZKrP9+v49MrIgrFmE1pwMWQVJnFkIkBXo8IPExEMvJnBMHiLDZ3OLGy1rf838orIZ4X0enrLzJRTrbh3j7/wa0ef8YwGRDsTDWXig7ajGKcAsctpWP4/5hCOPuPmA0RG+kLs3N7ao1kyB2LRFbjzTO/qkOIXwkpoQOwd9iCQPp8nZrN2Jvijf6c6lPM3ftldxY3QMFdLLhNjqAZUJ7ksb3Csn created-by-lxc_start.sh
  volatile.base_image: 7a7ff654cbd8f5f09bec03aa19d8d7d92649127d18659036a963b1ea63f90d25
  volatile.eth0.hwaddr: 00:16:3e:2c:a7:3a
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    name: eth0
    nictype: macvlan
    parent: ens160
    type: nic
  root:
    path: /
    size: 20GB
    type: disk
ephemeral: false
profiles:
- int-mgmt0
root@robotframework:~/jenkins/workspace/robot-deploy/robot/script$ lxc config show --expanded wedgeiq2
architecture: x86_64
config:
  boot.autostart: "true"
  user.user-data: |
    #cloud-config
    ssh_authorized_keys:
     - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDWj6Iv5VOm8tCdbOIu5FUrgTZSVJogt7f4mSQuLVLzXKDMfc1vLRltruYg326CVWicvvaYNp5EZbcj5UqyLE/4HBGUn33uUKPoxtHpLaM7jrjDf9ExJzNItWbafMGZKrP9+v49MrIgrFmE1pwMWQVJnFkIkBXo8IPExEMvJnBMHiLDZ3OLGy1rf838orIZ4X0enrLzJRTrbh3j7/wa0ef8YwGRDsTDWXig7ajGKcAsctpWP4/5hCOPuPmA0RG+kLs3N7ao1kyB2LRFbjzTO/qkOIXwkpoQOwd9iCQPp8nZrN2Jvijf6c6lPM3ftldxY3QMFdLLhNjqAZUJ7ksb3Csn created-by-lxc_start.sh
  volatile.base_image: 7a7ff654cbd8f5f09bec03aa19d8d7d92649127d18659036a963b1ea63f90d25
  volatile.eth0.hwaddr: 00:16:3e:b8:30:39
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    name: eth0
    nictype: macvlan
    parent: ens160
    type: nic
  root:
    path: /
    type: disk
ephemeral: false
profiles:
- int-mgmt0

**Comment by gusijia** [comment] 2017-07-17 22:28
@stgraber This error only occur occasionally on jenkins build. Never happened if I run the script manually on the host vm. I cannot reproduce it today. currently there seems no MAC conflict. I will double check the "lxc config show --expanded" next time the error happened.

**Comment by gusijia** [comment] 2017-07-17 22:29
the output for  "lspci -nnn":
00:00.0 Host bridge [0600]: Intel Corporation 440BX/ZX/DX - 82443BX/ZX/DX Host bridge [8086:7190] (rev 01)
00:01.0 PCI bridge [0604]: Intel Corporation 440BX/ZX/DX - 82443BX/ZX/DX AGP bridge [8086:7191] (rev 01)
00:07.0 ISA bridge [0601]: Intel Corporation 82371AB/EB/MB PIIX4 ISA [8086:7110] (rev 08)
00:07.1 IDE interface [0101]: Intel Corporation 82371AB/EB/MB PIIX4 IDE [8086:7111] (rev 01)
00:07.3 Bridge [0680]: Intel Corporation 82371AB/EB/MB PIIX4 ACPI [8086:7113] (rev 08)
00:07.7 System peripheral [0880]: VMware Virtual Machine Communication Interface [15ad:0740] (rev 10)
00:0f.0 VGA compatible controller [0300]: VMware SVGA II Adapter [15ad:0405]
00:10.0 SCSI storage controller [0100]: LSI Logic / Symbios Logic 53c1030 PCI-X Fusion-MPT Dual Ultra320 SCSI [1000:0030] (rev 01)
00:11.0 PCI bridge [0604]: VMware PCI bridge [15ad:0790] (rev 02)
00:15.0 PCI bridge [0604]: VMware PCI Express Root Port [15ad:07a0] (rev 01)
00:15.1 PCI bridge [0604]: VMware PCI Express Root Port [15ad:07a0] (rev 01)
00:15.2 PCI bridge [0604]: VMware PCI Express Root Port [15ad:07a0] (rev 01)
00:15.3 PCI bridge [0604]: VMware PCI Express Root Port [15ad:07a0] (rev 01)
00:15.4 PCI bridge [0604]: VMware PCI Express Root Port [15ad:07a0] (rev 01)
00:15.5 PCI bridge [0604]: VMware PCI Express Root Port [15ad:07a0] (rev 01)
00:15.6 PCI bridge [0604]: VMware PCI Express Root Port [15ad:07a0] (rev 01)
00:15.7 PCI bridge [0604]: VMware PCI Express Root Port [15ad:07a0] (rev 01)
00:16.0 PCI bridge [0604]: VMware PCI Express Root Port [15ad:07a0] (rev 01)
00:16.1 PCI bridge [0604]: VMware PCI Express Root Port [15ad:07a0] (rev 01)
00:16.2 PCI bridge [0604]: VMware PCI Express Root Port [15ad:07a0] (rev 01)
00:16.3 PCI bridge [0604]: VMware PCI Express Root Port [15ad:07a0] (rev 01)
00:16.4 PCI bridge [0604]: VMware PCI Express Root Port [15ad:07a0] (rev 01)
00:16.5 PCI bridge [0604]: VMware PCI Express Root Port [15ad:07a0] (rev 01)
00:16.6 PCI bridge [0604]: VMware PCI Express Root Port [15ad:07a0] (rev 01)
00:16.7 PCI bridge [0604]: VMware PCI Express Root Port [15ad:07a0] (rev 01)
00:17.0 PCI bridge [0604]: VMware PCI Express Root Port [15ad:07a0] (rev 01)
00:17.1 PCI bridge [0604]: VMware PCI Express Root Port [15ad:07a0] (rev 01)
00:17.2 PCI bridge [0604]: VMware PCI Express Root Port [15ad:07a0] (rev 01)
00:17.3 PCI bridge [0604]: VMware PCI Express Root Port [15ad:07a0] (rev 01)
00:17.4 PCI bridge [0604]: VMware PCI Express Root Port [15ad:07a0] (rev 01)
00:17.5 PCI bridge [0604]: VMware PCI Express Root Port [15ad:07a0] (rev 01)
00:17.6 PCI bridge [0604]: VMware PCI Express Root Port [15ad:07a0] (rev 01)
00:17.7 PCI bridge [0604]: VMware PCI Express Root Port [15ad:07a0] (rev 01)
00:18.0 PCI bridge [0604]: VMware PCI Express Root Port [15ad:07a0] (rev 01)
00:18.1 PCI bridge [0604]: VMware PCI Express Root Port [15ad:07a0] (rev 01)
00:18.2 PCI bridge [0604]: VMware PCI Express Root Port [15ad:07a0] (rev 01)
00:18.3 PCI bridge [0604]: VMware PCI Express Root Port [15ad:07a0] (rev 01)
00:18.4 PCI bridge [0604]: VMware PCI Express Root Port [15ad:07a0] (rev 01)
00:18.5 PCI bridge [0604]: VMware PCI Express Root Port [15ad:07a0] (rev 01)
00:18.6 PCI bridge [0604]: VMware PCI Express Root Port [15ad:07a0] (rev 01)
00:18.7 PCI bridge [0604]: VMware PCI Express Root Port [15ad:07a0] (rev 01)
03:00.0 Ethernet controller [0200]: VMware VMXNET3 Ethernet Controller [15ad:07b0] (rev 01)
0b:00.0 Ethernet controller [0200]: VMware VMXNET3 Ethernet Controller [15ad:07b0] (rev 01)
13:00.0 Ethernet controller [0200]: VMware VMXNET3 Ethernet Controller [15ad:07b0] (rev 01)

**Comment by stgraber** [comment] 2017-07-18 10:38
Ok, so my best guesses based on the kernel code are:
 - The vmxnet3 driver has some kind of hard limit on the number of MACs it can track. Once the number of tracked MAC addresses hit the limit, any additional macvlan device will fail to come up with EBUSY.
 - The MAC address used for your container is already bound to the physical NIC somehow. It can be because the container was previously running and the network namespace hasn't been entirely flushed by the kernel yet (there have been a number of kernel issues around that in the past) or because of a bug in macvlan or vmxnet3 where the list of MAC for the NIC doesn't get properly updated.

Based on your output above and your manual checks, it doesn't look like it's LXD's fault in that it does generate unique MAC addresses for you and so isn't causing a misconfiguration itself. It looks like you're running into a lower level problem at the network namespace, macvlan or vmxnet3 level.

You could reconfigure your VM to use a different virtualized NIC (realtek or something) and see if that fixes the issue somehow, that'd be a good check to see if vmxnet3 is at fault, which is a pretty good guess given that we've never seen any other report of macvlan failing in such a way and most people seem to be using virtio or intel NICs rather than the virtual vmware ones.

If that doesn't do the trick, then tracking down the issue for sure will get annoying. If it's the network namespace issue and they take over a minute to be flushed, there will be logging in dmesg complaining about ref counting for the loopback device (kinda obscure but at least it's there). If there's none of that, then it may be a macvlan bug.

If you just want things to work, you may just want to switch to a regular Linux bridge which doesn't have any of those MAC addresses related restrictions but can be slightly more annoying to setup.

**Comment by stgraber** [comment] 2017-07-23 01:27
Closing as this appears to be a lower level issue (kernel or macvlan level) rather than a LXD bug (as would be the case if we'd setup a conflicting MAC address).

**Closed by stgraber** 2017-07-23 01:27 UTC
Labels: Incomplete
