### ISSUE TITLE
Failed to initialize storage volume, after copy over zfs

### ISSUE THREAD

**Issue by kim0** [lxc/lxd#5359] opened 2018-12-14 13:53 UTC
# Issue description

I'm trying to have a container + data volume, where I snapshot both of them, execute a shell command then snapshot both of them again .. so that I have an audit trail along the way. The below set of commands fail consistently

# Steps to reproduce

 1. Run the below shell commands on a fresh lxd/pool
 2. Watch the error?

```

lxc launch ubuntu:18.04 container-6d8a1e8771ad200e1d616b238125830db412fc86
lxc storage volume create s data-6d8a1e8771ad200e1d616b238125830db412fc86
lxc storage volume attach s data-6d8a1e8771ad200e1d616b238125830db412fc86 container-6d8a1e8771ad200e1d616b238125830db412fc86 /data

lxc storage volume copy s/data-6d8a1e8771ad200e1d616b238125830db412fc86 s/data-ea258f44566afa4feb9480843af24075b9662d9a
lxc cp container-6d8a1e8771ad200e1d616b238125830db412fc86 container-ea258f44566afa4feb9480843af24075b9662d9a
lxc config device remove container-ea258f44566afa4feb9480843af24075b9662d9a data-6d8a1e8771ad200e1d616b238125830db412fc86
lxc config device add container-ea258f44566afa4feb9480843af24075b9662d9a data-ea258f44566afa4feb9480843af24075b9662d9a disk source=data-ea258f44566afa4feb9480843af24075b9662d9a path=/data pool=s
lxc start container-ea258f44566afa4feb9480843af24075b9662d9a
```
The last line to start the new container, fails with the below error!
```

Error: Common start logic: Failed to initialize storage volume "data-ea258f44566afa4feb9480843af24075b9662d9a" of type "custom" on storage pool "s": No such file or director
y: "/var/snap/lxd/common/lxd/storage-pools/s/custom/data-ea258f44566afa4feb9480843af24075b9662d9a"
Try `lxc info --show-log container-ea258f44566afa4feb9480843af24075b9662d9a` for more info
```

**Comment by kim0** [comment] 2018-12-14 13:58
@stgraber  Really appreciating all the great help you're offering :) and congrats on the new 3.8 release 👍 
Hope you can answer this question too. As you see, I'm copying a container and copying its custom data volume. This will be repeated a lot. I am _hoping_ this uses zfs clones under the hood, in order to be fast even when the data volume is huge. However, I think I saw zfs send|recv processes once!

* Can you confirm whether the method I'm using above, results in zfs clones (not send| recv) ?
* Is there any benefits to doing a snapshot of the container+volume, before copying them .. vs just copying them directly ?

**Comment by stgraber** [comment] 2018-12-14 15:17
I'm confused, isn't that the bug I fixed two days ago?

**Comment by stgraber** [comment] 2018-12-14 17:21
1) yes
2) no

Are you running LXD 3.8? If not, then you don't yet have the fix for this issue.

**Comment by kim0** [comment] 2018-12-14 17:31
Thanks! I should be tracking edge .. Check below
```
snap-id:      J60k4JY0HppjwOjW8dZdYc8obXKxujRu
tracking:     edge
refresh-date: today at 15:34 EET
channels:
  stable:        3.7         (9664) 53MB -
  candidate:     3.8         (9786) 54MB -
  beta:          ↑
  edge:          git-ae0a670 (9788) 54MB -
  3.0/stable:    3.0.3       (9663) 53MB -
  3.0/candidate: 3.0.3       (9663) 53MB -
  3.0/beta:      ↑
  3.0/edge:      git-18c9b88 (9673) 53MB -
  2.0/stable:    2.0.11      (8023) 28MB -
  2.0/candidate: 2.0.11      (8023) 28MB -
  2.0/beta:      ↑
  2.0/edge:      git-c7c4cc8 (9257) 26MB -
installed:       git-ae0a670 (9788) 54MB -
```

**Comment by stgraber** [comment] 2018-12-14 21:19
```
root@vm02:~# lxc launch ubuntu:18.04 c1
Creating c1
Starting c1                                   
root@vm02:~# lxc storage volume create default data-c1
Storage volume data-c1 created
root@vm02:~# lxc storage volume attach default data-c1 c1 /data
root@vm02:~# lxc exec c1 -- df -h
Filesystem              Size  Used Avail Use% Mounted on
default/containers/c1    14G  335M   13G   3% /
none                    492K     0  492K   0% /dev
udev                    3.9G     0  3.9G   0% /dev/tty
tmpfs                   100K     0  100K   0% /dev/lxd
tmpfs                   100K     0  100K   0% /dev/.lxd-mounts
tmpfs                   3.9G     0  3.9G   0% /dev/shm
tmpfs                   3.9G  156K  3.9G   1% /run
tmpfs                   5.0M     0  5.0M   0% /run/lock
tmpfs                   3.9G     0  3.9G   0% /sys/fs/cgroup
default/custom/data-c1   13G     0   13G   0% /data
root@vm02:~# lxc storage volume copy default/data-c1 default/data-c2
Storage volume copied successfully!
root@vm02:~# lxc copy c1 c2
root@vm02:~# lxc config device remove c2 data-c1
Device data-c1 removed from c2
root@vm02:~# lxc storage volume attach default data-c2 c2 /data
root@vm02:~# lxc start c2
root@vm02:~# lxc exec c1 -- df -h
Filesystem              Size  Used Avail Use% Mounted on
default/containers/c1    14G  335M   13G   3% /
none                    492K     0  492K   0% /dev
udev                    3.9G     0  3.9G   0% /dev/tty
tmpfs                   100K     0  100K   0% /dev/lxd
tmpfs                   100K     0  100K   0% /dev/.lxd-mounts
tmpfs                   3.9G     0  3.9G   0% /dev/shm
tmpfs                   3.9G  152K  3.9G   1% /run
tmpfs                   5.0M     0  5.0M   0% /run/lock
tmpfs                   3.9G     0  3.9G   0% /sys/fs/cgroup
default/custom/data-c1   13G     0   13G   0% /data
root@vm02:~# lxc exec c2 -- df -h
Filesystem              Size  Used Avail Use% Mounted on
default/containers/c2    14G  336M   13G   3% /
none                    492K     0  492K   0% /dev
udev                    3.9G     0  3.9G   0% /dev/tty
tmpfs                   100K     0  100K   0% /dev/lxd
default/custom/data-c2   13G     0   13G   0% /data
tmpfs                   100K     0  100K   0% /dev/.lxd-mounts
tmpfs                   3.9G     0  3.9G   0% /dev/shm
tmpfs                   3.9G  156K  3.9G   1% /run
tmpfs                   5.0M     0  5.0M   0% /run/lock
tmpfs                   3.9G     0  3.9G   0% /sys/fs/cgroup
```

**Comment by stgraber** [comment] 2018-12-14 21:21
Oh, I remember I gave you a test binary of LXD a while back to put in /var/snap/lxd/common/lxd.debug, did you remove it since?

If not, that'd explain why you're seeing no difference as you'd effectively not be running the newer version.

**Comment by kim0** [comment] 2018-12-14 21:34
Well thanks for looking into this. I do not currently have `lxd.debug` .. probably bec I `snap remove lxd` and delete the zfs dataset whenever I want to start fresh! (Any easier way?)

However, I see you're using `lxc storage volume attach` while I'm using `lxc config device add` which I guess are not doing the same thing? Let me try your way and see if it makes a difference. Thanks

**Comment by stgraber** [comment] 2018-12-14 21:45
Oh, sorry, I didn't see that difference, let me try but this should be identical as far as API calls made from the client.

**Comment by kim0** [comment] 2018-12-14 21:57
Just tried the whole thing from scratch (blow away zfs dataset, remove/reinstall lxd ...etc) used your attach command .. and still hit the same issue! 

I wanted to see what OS commands were being executed, so I issued the below bpftrace command and could see it is unable to zfs mount the data disk! I guess lxd keeps retrying for a bit, bec that command keeps repeating and probably failing! And is consistent with the error message lxc emits in the end. The weird thing, is that running the same command manually succeeds, and the directory mounts normally!! I have no idea why it would be failing only under lxd. You can see the trace commands below. If it would be helpful, I can log you into the test server I'm using. Let me know!

```
# bpftrace -e ' tracepoint:syscalls:sys_enter_execve { printf("%-10u %-5d ", 0 / 1000000, pid); join(args->argv); }'
Attaching 1 probe...
0          115532 /bin/sh -c iptables --version
0          115533 iptables --version
0          115534 /bin/sh -c iptables -w -t security -C OUTPUT -d 168.63.129.16 -p tcp -m conntrack --ctstate INVALID,NEW -j DROP
0          115535 iptables -w -t security -C OUTPUT -d 168.63.129.16 -p tcp -m conntrack --ctstate INVALID,NEW -j DROP
0          115558 lxc start container-ea258f44566afa4feb9480843af24075b9662d9a
0          115558 lxc start container-ea258f44566afa4feb9480843af24075b9662d9a
0          115558 /snap/core/6034/usr/lib/snapd/snap-confine snap.lxd.lxc /usr/lib/snapd/snap-exec lxd.lxc start container-ea258f44566afa4feb9480843af24075b9662d9a
0          115558 /usr/lib/snapd/snap-exec lxd.lxc start container-ea258f44566afa4feb9480843af24075b9662d9a
0          115558 /snap/lxd/9788/command-lxc.wrapper start container-ea258f44566afa4feb9480843af24075b9662d9a
0          115558 /snap/lxd/9788/commands/lxc start container-ea258f44566afa4feb9480843af24075b9662d9a
0          115570 cat /proc/self/attr/current
0          115558 aa-exec -p unconfined -- /snap/lxd/9788/commands/lxc start container-ea258f44566afa4feb9480843af24075b9662d9a
0          115558 aa-exec -p unconfined -- /snap/lxd/9788/commands/lxc start container-ea258f44566afa4feb9480843af24075b9662d9a
0          115558 aa-exec -p unconfined -- /snap/lxd/9788/commands/lxc start container-ea258f44566afa4feb9480843af24075b9662d9a
0          115558 aa-exec -p unconfined -- /snap/lxd/9788/commands/lxc start container-ea258f44566afa4feb9480843af24075b9662d9a
0          115558 aa-exec -p unconfined -- /snap/lxd/9788/commands/lxc start container-ea258f44566afa4feb9480843af24075b9662d9a
0          115558 aa-exec -p unconfined -- /snap/lxd/9788/commands/lxc start container-ea258f44566afa4feb9480843af24075b9662d9a
0          115558 aa-exec -p unconfined -- /snap/lxd/9788/commands/lxc start container-ea258f44566afa4feb9480843af24075b9662d9a
0          115558 /snap/lxd/9788/commands/lxc start container-ea258f44566afa4feb9480843af24075b9662d9a
0          115571 cat /proc/self/attr/current
0          115573 ss -nlpx src /var/lib/lxd/unix.socket
0          115575 sed -e s/.*pid=// -e s/,.*//g
0          115574 grep /var/lib/lxd/unix.socket
0          115558 lxc start container-ea258f44566afa4feb9480843af24075b9662d9a
0          115558 lxc start container-ea258f44566afa4feb9480843af24075b9662d9a
0          115558 lxc start container-ea258f44566afa4feb9480843af24075b9662d9a
0          115558 lxc start container-ea258f44566afa4feb9480843af24075b9662d9a
0          115583 zfs get -H -o name type zdocker/lxd/containers/container-ea258f44566afa4feb9480843af24075b9662d9a
0          115584 ebtables -L --Lmac2 --Lx
0          115585 iptables -w -t nat -S
0          115586 ip6tables -w -t nat -S
0          115587 zfs mount zdocker/lxd/custom/data-ea258f44566afa4feb9480843af24075b9662d9a
0          115588 zfs mount zdocker/lxd/custom/data-ea258f44566afa4feb9480843af24075b9662d9a
0          115589 zfs mount zdocker/lxd/custom/data-ea258f44566afa4feb9480843af24075b9662d9a
0          115590 zfs mount zdocker/lxd/custom/data-ea258f44566afa4feb9480843af24075b9662d9a
0          115591 zfs mount zdocker/lxd/custom/data-ea258f44566afa4feb9480843af24075b9662d9a
0          115609 /bin/sh -c iptables --version
0          115610 iptables --version
0          115614 /bin/sh -c iptables -w -t security -C OUTPUT -d 168.63.129.16 -p tcp -m conntrack --ctstate INVALID,NEW -j DROP
0          115615 iptables -w -t security -C OUTPUT -d 168.63.129.16 -p tcp -m conntrack --ctstate INVALID,NEW -j DROP
0          115700 worker_nscd 0
0          115701 zfs mount zdocker/lxd/custom/data-ea258f44566afa4feb9480843af24075b9662d9a
0          115702 zfs mount zdocker/lxd/custom/data-ea258f44566afa4feb9480843af24075b9662d9a
0          115721 zfs mount zdocker/lxd/custom/data-ea258f44566afa4feb9480843af24075b9662d9a
0          115722 zfs mount zdocker/lxd/custom/data-ea258f44566afa4feb9480843af24075b9662d9a
0          115723 zfs mount zdocker/lxd/custom/data-ea258f44566afa4feb9480843af24075b9662d9a
0          115736 zfs mount zdocker/lxd/custom/data-ea258f44566afa4feb9480843af24075b9662d9a
0          115737 zfs mount zdocker/lxd/custom/data-ea258f44566afa4feb9480843af24075b9662d9a
0          115744 zfs mount zdocker/lxd/custom/data-ea258f44566afa4feb9480843af24075b9662d9a
0          115748 zfs mount zdocker/lxd/custom/data-ea258f44566afa4feb9480843af24075b9662d9a
0          115754 zfs mount zdocker/lxd/custom/data-ea258f44566afa4feb9480843af24075b9662d9a
0          115755 /bin/sh -c iptables --version
0          115756 iptables --version
0          115757 /bin/sh -c iptables -w -t security -C OUTPUT -d 168.63.129.16 -p tcp -m conntrack --ctstate INVALID,NEW -j DROP
0          115758 iptables -w -t security -C OUTPUT -d 168.63.129.16 -p tcp -m conntrack --ctstate INVALID,NEW -j DROP
0          115911 zfs mount zdocker/lxd/custom/data-ea258f44566afa4feb9480843af24075b9662d9a
0          115912 zfs mount zdocker/lxd/custom/data-ea258f44566afa4feb9480843af24075b9662d9a
0          115913 zfs mount zdocker/lxd/custom/data-ea258f44566afa4feb9480843af24075b9662d9a
0          115916 zfs mount zdocker/lxd/custom/data-ea258f44566afa4feb9480843af24075b9662d9a
0          115919 zfs mount zdocker/lxd/custom/data-ea258f44566afa4feb9480843af24075b9662d9a
```
The error I get the first time is
```
$ lxc start container-ea258f44566afa4feb9480843af24075b9662d9a
Error: Common start logic: Failed to initialize storage volume "data-ea258f44566afa4feb9480843af24075b9662d9a" of type "custom" on storage pool "s": No such file or directory: "/var/snap/lxd/common/lxd/storage-pools/s/custom/data-ea258f44566afa4feb9480843af24075b9662d9a"
Try `lxc info --show-log container-ea258f44566afa4feb9480843af24075b9662d9a` for more info
```

After I tried to manually run the `zfs mount` command and unmounted again. The error is slightly different as below

```
# zfs get mounted zdocker/lxd/custom/data-ea258f44566afa4feb9480843af24075b9662d9a
NAME                                                              PROPERTY  VALUE    SOURCE
zdocker/lxd/custom/data-ea258f44566afa4feb9480843af24075b9662d9a  mounted   no       -

$ lxc start container-ea258f44566afa4feb9480843af24075b9662d9a
Error: Common start logic: Failed to initialize storage volume "data-ea258f44566afa4feb9480843af24075b9662d9a" of type "custom" on storage pool "s": Failed to mount ZFS filesystem:
cannot mount 'zdocker/lxd/custom/data-ea258f44566afa4feb9480843af24075b9662d9a': filesystem already mounted

Try `lxc info --show-log container-ea258f44566afa4feb9480843af24075b9662d9a` for more info
```

**Comment by stgraber** [comment] 2018-12-14 22:00
I'll try using your pool and volume names see if maybe that makes it hit this issue somehow.

**Comment by stgraber** [comment] 2018-12-14 22:05
```
stgraber@castiana:~/data/code/lxc/lxd (stgraber/master)$ rssh ubuntu@vm02.maas.mtl
Warning: Permanently added 'vm02.maas.mtl' (ECDSA) to the list of known hosts.
root@vm02:~# snap install lxd --edge ; lxd.migrate -yes
2018-12-14T22:03:31Z INFO Waiting for restart...
lxd (edge) git-ae0a670 from 'canonical' installed
=> Connecting to source server
=> Connecting to destination server
=> Running sanity checks
The source server is empty, no migration needed.

The migration is now complete and your containers should be back online.

All done. You may need to close your current shell and open a new one to have the "lxc" command work.
To migrate your existing client configuration, move ~/.config/lxc to ~/snap/lxd/current/.config/lxc
root@vm02:~# lxd init
Would you like to use LXD clustering? (yes/no) [default=no]: 
Do you want to configure a new storage pool? (yes/no) [default=yes]: 
Name of the new storage pool [default=default]: s
Name of the storage backend to use (btrfs, ceph, dir, lvm, zfs) [default=zfs]: 
Create a new ZFS pool? (yes/no) [default=yes]: 
Would you like to use an existing block device? (yes/no) [default=no]: 
Size in GB of the new loop device (1GB minimum) [default=15GB]: 
Would you like to connect to a MAAS server? (yes/no) [default=no]: 
Would you like to create a new local network bridge? (yes/no) [default=yes]: 
What should the new bridge be called? [default=lxdbr0]: 
What IPv4 address should be used? (CIDR subnet notation, “auto” or “none”) [default=auto]: 
What IPv6 address should be used? (CIDR subnet notation, “auto” or “none”) [default=auto]: 
Would you like LXD to be available over the network? (yes/no) [default=no]: 
Would you like stale cached images to be updated automatically? (yes/no) [default=yes] 
Would you like a YAML "lxd init" preseed to be printed? (yes/no) [default=no]: 
root@vm02:~# lxc launch ubuntu:18.04 container-6d8a1e8771ad200e1d616b238125830db412fc86
To start your first container, try: lxc launch ubuntu:18.04

Creating container-6d8a1e8771ad200e1d616b238125830db412fc86
Starting container-6d8a1e8771ad200e1d616b238125830db412fc86
root@vm02:~# lxc storage volume create s data-6d8a1e8771ad200e1d616b238125830db412fc86
Storage volume data-6d8a1e8771ad200e1d616b238125830db412fc86 created
root@vm02:~# lxc storage volume attach s data-6d8a1e8771ad200e1d616b238125830db412fc86 container-6d8a1e8771ad200e1d616b238125830db412fc86 /data
root@vm02:~# lxc storage volume copy s/data-6d8a1e8771ad200e1d616b238125830db412fc86 s/data-ea258f44566afa4feb9480843af24075b9662d9a
Storage volume copied successfully!
root@vm02:~# lxc cp container-6d8a1e8771ad200e1d616b238125830db412fc86 container-ea258f44566afa4feb9480843af24075b9662d9a
root@vm02:~# lxc config device remove container-ea258f44566afa4feb9480843af24075b9662d9a data-6d8a1e8771ad200e1d616b238125830db412fc86
Device data-6d8a1e8771ad200e1d616b238125830db412fc86 removed from container-ea258f44566afa4feb9480843af24075b9662d9a
root@vm02:~# lxc config device add container-ea258f44566afa4feb9480843af24075b9662d9a data-ea258f44566afa4feb9480843af24075b9662d9a disk source=data-ea258f44566afa4feb9480843af24075b9662d9a path=/data pool=s
Device data-ea258f44566afa4feb9480843af24075b9662d9a added to container-ea258f44566afa4feb9480843af24075b9662d9a
root@vm02:~# lxc start container-ea258f44566afa4feb9480843af24075b9662d9a
root@vm02:~# 
```

**Comment by stgraber** [comment] 2018-12-14 22:06
What distribution, release and kernel are you running this on?

**Comment by kim0** [comment] 2018-12-14 22:07
```
# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
root@docker01:/tmp#
root@docker01:/tmp#
root@docker01:/tmp# uname -a
Linux docker01 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by stgraber** [comment] 2018-12-14 22:07
Ok, so same I'm using...

**Comment by kim0** [comment] 2018-12-14 22:11
Let me try with a loopback zfs pool

**Comment by stgraber** [comment] 2018-12-14 22:12
Can you show `lxc storage show s`?

**Comment by kim0** [comment] 2018-12-14 22:16
Weird .. with a new zpool things are working!! What would you rather I do now? rebuild using normal zpool and send `lxc storage show s` ?

**Comment by kim0** [comment] 2018-12-14 22:18
I guess one slightly significant difference, is that with my normal pool, I am using a zfs dataset (zdocker/lxd) as the root pool for lxd .. not using the whole pool!

**Comment by stgraber** [comment] 2018-12-14 22:20
Yeah, that's what I wanted to see with `lxc storage show s`, ok, so that's a good pointer, I'll reset my test system and try with that, hopefully that's the reason why things are failing.

**Comment by stgraber** [comment] 2018-12-14 22:35
Yep, that did it, I've got a reproducer so should be able to figure it out quickly from here.

**Comment by stgraber** [comment] 2018-12-15 00:06
Sent a fix now

**Closed** 2018-12-17 09:34 UTC
