### ISSUE TITLE
Millon of close syscalls on lxd container when run a simple python scrip

### ISSUE THREAD

**Issue by carlosduelo** [lxc/lxd#3860] opened 2017-09-27 16:06 UTC
# Required information

 * Distribution:=Ubuntu
 * Distribution version:="Ubuntu 16.04.3 LTS"
 * The output of "
````
config:
  storage.zfs_pool_name: debtool
api_extensions:
- id_map
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  driver: lxc
  driver_version: 2.0.7
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-96-generic
  server: lxd
  server_pid: 17398
  server_version: 2.0.10
  storage: zfs
  storage_version: "5"
````
   * LXC and LXD versions:

````
$ apt-cache policy lxd
lxd:
  Installed: 2.0.10-0ubuntu1~16.04.2

$ apt-cache policy lxc
lxc:
  Installed: 2.0.7-0ubuntu1~16.04.1
````
   * Storage backend in use: zfs

# Issue description

I noticed a very different performance running commands on lxd container so, simple as **sh.nice()** 

Host
```
    $ time python -c "import sh; sh.nice()"
    real	0m0.077s
    user	0m0.052s
    sys	0m0.012s
```

Container
```
    $ time python -c "import sh; sh.nice()"
    real	0m0.215s
    user	0m0.088s
    sys	0m0.120s
```

My next step was use strace which says that the container version call 1048796 times the syscall close!! The majority of the times it returns EBADF (Bad file descriptor).

I do not know if it is a sh module issue or not but it is happening with lxd and not with lxc

# Steps to reproduce

```
    $ uname -a
    Linux cmp-1 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
    $ lxc launch ubuntu:precise new-precise-sh
    $ lxc exec new-precise-sh -- bash
    $ apt-get install python-pip
    $ pip install sh
    $ strace -f -e close python -c "import sh; sh.nice()" 2>&1 | wc -l
    1048796
```
# Information to attach

Running strace with output in different files. There is one too big **strace.2618**

```
    $ strace -ff -o strace python -c "import sh; sh.nice()"
    $ ls -la
    total 75276
    drwxrwxr-x  2 user user     4096 Sep 27 16:58 .
    drwxr-xr-x 41 user user     4096 Sep 27 16:45 ..
    -rw-r--r--  1 root   root     121780 Sep 27 16:33 strace.2615
    -rw-r--r--  1 root   root       3995 Sep 27 16:33 strace.2616
    -rw-r--r--  1 root   root       6108 Sep 27 16:33 strace.2617
    -rw-r--r--  1 root   root   76558803 Sep 27 16:33 strace.2618
    -rw-r--r--  1 root   root     362363 Sep 27 16:33 strace.2619
    -rw-r--r--  1 root   root      10748 Sep 27 16:33 strace.2620
```

The content of the file something like this:

```
    $ cat strace.2618
    ...................
    ...................
    getrlimit(RLIMIT_NOFILE, {rlim_cur=1024*1024, rlim_max=1024*1024}) = 0
    close(3)                                = 0
    close(4)                                = 0
    close(5)                                = -1 EBADF (Bad file descriptor)
    close(6)                                = -1 EBADF (Bad file descriptor)
    close(7)                                = 0
    close(8)                                = 0
    close(9)                                = -1 EBADF (Bad file descriptor)
    close(10)                               = 0
    close(11)                               = -1 EBADF (Bad file     descriptor)
    ...................
    ...................
    close(33)                               = -1 EBADF (Bad file descriptor)
    close(34)                               = -1 EBADF (Bad file descriptor)
    close(35)                               = -1 EBADF (Bad file descriptor)
    close(36)                               = -1 EBADF (Bad file descriptor)
    close(37)                               = -1 EBADF (Bad file descriptor)
    close(38)                               = -1 EBADF (Bad file descriptor)
    ...................
    ...................
    close(1048568)                          = -1 EBADF (Bad file descriptor)
    close(1048569)                          = -1 EBADF (Bad file descriptor)
    close(1048570)                          = -1 EBADF (Bad file descriptor)
    close(1048571)                          = -1 EBADF (Bad file descriptor)
    close(1048572)                          = -1 EBADF (Bad file descriptor)
    close(1048573)                          = -1 EBADF (Bad file descriptor)
    close(1048574)                          = -1 EBADF (Bad file descriptor)
    close(1048575)                          = -1 EBADF (Bad file descriptor)
    ioctl(1, SNDCTL_TMR_TIMEBASE or TCGETS, {B38400 -opost -isig -icanon -echo ...}) = 0
```

**Comment by stgraber** [comment] 2017-09-27 16:19
Can you try running the same test but under a "script /dev/null bash" session?

So:

    lxc exec new-precise-sh -- script /dev/null -c bash

This will cause your shell to use container-allocated pts rather than host allocated. I suspect this may be the source of the confusion in python or the python module you're using.

**Comment by carlosduelo** [comment] 2017-09-27 16:28
It did not work, same think

```
strace -f -e close python -c "import sh; sh.nice()" 2>&1 | wc -l
1048798
```

**Comment by stgraber** [comment] 2017-09-27 19:37
Ok, so the problem is just that this piece of python code is crap.

```
                # don't inherit file descriptors
                max_fd = resource.getrlimit(resource.RLIMIT_NOFILE)[0]
                os.closerange(3, max_fd)
```

This iterates over every single fd number up to RLIMIT_NOFILE, closing them all one by one, regardless of whether the fd actually does exist.

On a normal system, this will be capped at 1024 as the most comment NOFILE limit. In LXD containers, we have it bumped to a much higher value, causing it to take longer.

I'd strongly recommend you tell the upstream to look at /proc/self/fd/ and just close those fds rather than iterate through the entire possible range.

Closing this issue as it's not a LXD bug, it's just bad python code which would cause the same problem on a system that's got an increased NOFILE limit.

**Closed by stgraber** 2017-09-27 19:37 UTC
Labels: Incomplete

**Comment by carlosduelo** [comment] 2017-09-27 20:15
Thanks!!
