### ISSUE TITLE
LXC can't delete containers with very long paths in it

### ISSUE THREAD

**Issue by bionade24** [lxc/lxd#9479] opened 2021-11-04 17:13 UTC
Due to an accident I got this super-long path in a container. Deleting the container was impossible.  Deleting the path inside the container and then the container worked.

lxc version: 4.19 (snap)
Distro: Ubuntu 18.04(container) Ubuntu20.04 (host)

```
$ lxc delete --force build-test
Error: Error deleting storage volume: lstat /var/snap/lxd/common/lxd/storage-pools/build_cd/container
s/oskar-build-test/rootfs/home/user/home/user/home/user/home/user/home/user/home/user/hom
e/user/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/cor
vus/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/user/h
ome/user/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/c
orvus/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/user
/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home
/user/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/corv
us/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/user/ho
me/user/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/co
rvus/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/user/
home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/
user/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/corvu
s/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/user/hom
e/user/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/cor
vus/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/user/h
ome/user/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/c
orvus/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/user
/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home
/user/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/corv
us/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/user/ho
me/user/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/co
rvus/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/user/
home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/
user/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/corvu
s/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/user/hom
e/user/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/cor
vus/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/user/h
ome/user/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/c
orvus/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/user
/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home
/user/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/corv
us/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/user/ho
me/user/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/co
rvus/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/user/
home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/
user/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/corvu
s/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/user/hom
e/user/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/cor
vus/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/user/h
ome/user/home/user/home/user/home/user/home/user/home/user/home/user/home/user/home/user: file name too long
```

**Comment by brauner** [comment] 2021-11-04 17:37
Transferring to LXD.

**Comment by dillonsamra9** [comment] 2021-11-15 16:29
Hi. I'm a CS student at UT Austin and am currently taking a Virtualization class. I would be happy to take a look at this issue?

**Comment by bionade24** [comment] 2021-11-15 18:02
> Hi. I'm a CS student at UT Austin and am currently taking a Virtualization class. I would be happy to take a look at this issue?

It's Open Souce. You can see that there isn't a WIP PR referenced in this issues, so just start. If you're not super slow you're the first submitting a PR for this. If it doens't get merged, you still learned something. There will be no one in the FOSS community promising to strangers that their PR definately  gets merged.

**Comment by stgraber** [comment] 2021-11-15 18:03
@dillonsamra9 sounds good, assigning it to you!

**Comment by stgraber** [comment] 2021-11-15 18:06
@bionade24 we're used to working with UT Austin students, every year we get a few groups of students who get to contribute to open source projects as part of their virtualization class. We steer them towards our issues labeled as Easy since those are achievable within their allotted time and the LXD team has a good idea of what needs to be done and will help them should they have questions.

For tracking purposes, each member of a group looking at a specific issue/feature will comment so we can assign the issue to them and keep track on our side of what's going on and where we may need to provide additional help :)

**Comment by bionade24** [comment] 2021-11-15 18:09
> @bionade24 we're used to working with UT Austin students, every year we get a few groups of students who get to contribute to open source projects as part of their virtualization class. We steer them towards our issues labeled as Easy since those are achievable within their allotted time and the LXD team has a good idea of what needs to be done and will help them should they have questions.
> 
> For tracking purposes, each member of a group looking at a specific issue/feature will comment so we can assign the issue to them and keep track on our side of what's going on and where we may need to provide additional help :)

Cool, didn't know that, whish my university would do such things.

**Comment by stgraber** [comment] 2021-11-15 18:13
Yep, it'd be really nice if more universities would do this. It helps open source projects get a few lower priority bugs and features off their plate and shows students how the open source community works and how easy it can be to add or fix something in a random piece of software :)

**Comment by stgraber** [comment] 2022-01-13 02:30
Taking this over so we can hopefully have a fix in 4.22

**Comment by stgraber** [comment] 2022-01-13 20:40
I'm having a surprisingly hard time reproducing this issue.

**Comment by stgraber** [comment] 2022-01-13 20:46
Marking as Incomplete and dropping milestone as I'm unable to reproduce it...

I managed to create myself a tree about 2500 level deep, trying to even access it from within the container gets me the `File name too long` but delete still works flawlessly, so Go's `RemoveAll` function seems to be handling it well.

That was on the `dir` backend too (ext4).

**Comment by bionade24** [comment] 2022-01-13 22:08
> @bionade24 can you confirm that you had this issue on `dir` too (others wouldn't really make sense as they don't delete individual files) and maybe try to reproduce the behavior on your side?
> 
> Here I basically had a loop do `for i in $(seq 5000); do mkdir -p home/user || break && cd home/user; done` which will create a tree as deep as I possibly can. When that didn't work, I went the crazy way and ran through such loops to have three hierarchies each about 1490 level deep and then I moved them one at the end of the other causing a tree around 5000 level deep. Trying to run `find` or `du` against such a tree would immediately fail as it was way too deep, but I still had no problem getting rid of the instance with `lxc delete`.

I'm not exactly sure anymore how I made this recursive copy, but I definately used the `btrfs` storage backend. 
If I remeber in the next days, I'll try again, both with `dir? and `btrfs` backend.

**Comment by stgraber** [comment] 2022-01-13 22:22
Ah, btrfs, that may explain it, will need to try with that instead.

**Comment by stgraber** [comment] 2022-01-13 22:22
For btrfs, we don't do a standard recursive delete so much as try to locate all subvolumes, delete those and then delete the main subvolume for the instance, so there may be something there.

**Comment by bionade24** [comment] 2022-01-13 22:34
Another thing: I'm somewhat certain that my path was way deeper than 5000. The recursive copy did run ~10s before I realized it. Not sure if this makes any effect, though.

**Comment by stgraber** [comment] 2022-01-13 22:54
The 5k deep one took quite a while to create, you'd think it'd be very fast but it really slows down after 1k or so.

**Comment by stgraber** [comment] 2022-01-20 22:28
Got it reproduced, it's indeed btrfs specific.

**Comment by stgraber** [comment] 2022-01-20 22:48
Sent in a fix which works for me here.

**Closed** 2022-01-21 07:14 UTC
Labels: Bug
