### ISSUE TITLE
[feature request] support for parallel compression of images

### ISSUE THREAD

**Issue by bsod90** [lxc/lxd#1862] opened 2016-04-07 00:21 UTC
It would be great to be able to specify pigz or any other parallel compression algorithm implementation for publishing images.

I briefly tried to do `lxc config set images.compression_algorithm pigz`, it seemed that compression step took much less time, but then publish command failed saying "unexpected EOF". Not sure where this exception came from as there were no stack trace.

Anyways, faster image creation would be super useful for those, who want to build and publish them on a regular basis.

Thank you.

**Comment by stgraber** [comment] 2016-04-07 00:58
It should actually have worked but when adding reproducible compression support I accidentally broke most compression algorithms in the process, pushed a fix for that now.

**Comment by bsod90** [comment] 2016-04-07 01:03
Awesome, thank you!

**Closed** 2016-04-07 01:41 UTC
Labels: Bug, Easy

**Comment by bsod90** [comment] 2016-04-12 01:36
@stgraber seems that this change didn't help with pigz
here's what I'm getting: http://d.pr/i/1flML

**Comment by bsod90** [comment] 2016-04-12 02:03
I've just tried pbzip2 instead of pigz and it succeeded
so, the problem is probably pigz related and should not be adressed on lxc side
however, even with pbzip2, it seemed to be using parallel compression only for one particular step during publishing.
http://d.pr/i/1k1Vi <- here I can see it uses pbzip2
it passes this state pretty quickly and then it runs something, that looks like this http://d.pr/i/1kP3N
and it takes quite a lot of time. It would be great if images.compression_algorithm can be applied there too.
Note: my resulting image size is ~9Gb, that's why I care about compression speed so much :)

**Comment by kbrenneman** [comment] 2017-08-28 18:59
I just stumbled across this today, and I found that the problem with using pigz is actually in the command line that lxd uses.

When lxd runs the compression command, it puts the command-line flags after the source filename:

`pigz source_file -c`

That fails with pigz, because it follows normal POSIX rules, where option flags like `-c` must precede positional arguments. Gzip (and probably most others) work because the glibc version of getopt(3) allows mixing positional and optional arguments.

To work correctly in all cases, you'd need to put the option flags first:

`pigz -c -- source_file`
