### ISSUE TITLE
Dir quota issue, non-snap build

### ISSUE THREAD

**Issue by s3rj1k** [lxc/lxd#6333] opened 2019-10-22 11:10 UTC
* Distribution: ```Ubuntu```
 * Distribution version: ```19.10```
 * `lxc info`:
```
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIB6TCCAW+gAwIBAgIRAMipi1laDv98az4lOTcezGcwCgYIKoZIzj0EAwMwMTEc
    MBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzERMA8GA1UEAwwIcm9vdEB2bTEw
    HhcNMTkxMDIyMTA0MTUxWhcNMjkxMDE5MTA0MTUxWjAxMRwwGgYDVQQKExNsaW51
    eGNvbnRhaW5lcnMub3JnMREwDwYDVQQDDAhyb290QHZtMTB2MBAGByqGSM49AgEG
    BSuBBAAiA2IABKsQRg/BlGLXNA5Il9Nz3mj0aG7ZeYxXNuiytzSMXyvB273HAba5
    kx15faQCdX+FfoW4yzngahGDW2vU+T7DMqZvbF7o0OT+7OB4SeNW1LqEDooMMXkv
    hq3NofHvJ5Zv4aNLMEkwDgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUF
    BwMBMAwGA1UdEwEB/wQCMAAwFAYDVR0RBA0wC4IDdm0xhwRZuERuMAoGCCqGSM49
    BAMDA2gAMGUCMBysBOJy0cjMSCq4k1Obh19bscduDa60Uz1NI4uVxXKED7SHVcP2
    AefxN5wYpwzqdQIxAMiZBEyirelLYXgPkmaCs20q+v/ypZaFf06Oq9gEh+AT9hEW
    STeU0KuRAYERDIY2Ig==
    -----END CERTIFICATE-----
  certificate_fingerprint: ed7df8975917d48705b272c51a1e04a611ce3e01d79a5ce28204ee5dc88c7ae2
  driver: lxc
  driver_version: 3.2.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    shiftfs: "true"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.3.0-19-generic
  lxc_features:
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    seccomp_notify: "true"
  project: default
  server: lxd
  server_clustered: false
  server_name: vm1
  server_pid: 8694
  server_version: "3.18"
  storage: dir
  storage_version: "1"
```
 * `mount | grep prjquota`: 
```
/dev/md1 on /var/lib/lxd/storage-pools/default type ext4 (rw,relatime,prjquota)
```
 * `tune2fs -l /dev/md1 | grep features`: 
```
Filesystem features:      has_journal ext_attr resize_inode dir_index filetype needs_recovery extent 64bit flex_bg sparse_super large_file huge_file dir_nlink extra_isize quota metadata_csum project 
```
 * CT Storage config:
```
devices:
  root:
    path: /
    pool: default
    size: 8GB
    type: disk
```
 * ```repquota -avugPs```:
```
*** Report for project quotas on device /dev/md1
Block grace time: 7days; Inode grace time: 7days
                        Space limits                File limits
Project         used    soft    hard  grace    used  soft  hard  grace
----------------------------------------------------------------------
#0        --      8K      0K      0K              2     0     0       
#10001    --   1722M      0K   7630M          35869     0     0     
```
 * ```lxc exec test -- sh -c "df -h"```:
```
Filesystem                                                 Size  Used Avail Use% Mounted on
/var/lib/lxd/storage-pools/default/containers/test/rootfs  7.5G  1.7G  5.8G  23% /
none                                                       492K  4.0K  488K   1% /dev
udev                                                       967M     0  967M   0% /dev/tty
tmpfs                                                      100K     0  100K   0% /dev/lxd
tmpfs                                                      100K     0  100K   0% /dev/.lxd-mounts
tmpfs                                                      994M     0  994M   0% /dev/shm
tmpfs                                                      994M  148K  994M   1% /run
tmpfs                                                      5.0M     0  5.0M   0% /run/lock
tmpfs                                                      994M     0  994M   0% /sys/fs/cgroup
```

Project quota on Dir storage backend backed by ext4 filesystem on soft-raid (mdadm) device works incorectly when this configuration is used in non-snap build of LXD.

To reproduce:
 - setup VM with above configuration, creating softraid and enabling prjquota on ext4 mount
 - compile LXC and LXD from sources, install, start, preseed default config
 - create CT with any OS inside
 - configure quota inside CT (8GB)
 - run command to create 1GB file, this command is succesfull:
``` 
# lxc exec test -- sh -c "fallocate -l 1G big"
```
 -  run command to create 2GB file, this command fails:
```
# lxc exec test -- sh -c "fallocate -l 2G big"
fallocate: fallocate failed: File too large
```

Same issue can be reproduced in Ubuntu 18.04.3 with kernel 5.0.x in similar configuration

Any ideas how to fix this?

**Comment by stgraber** [comment] 2019-10-22 13:12
I'll need to play with it a bit, but this isn't going to be a LXD bug, `repquota` shows we set the quota properly and the kernel shows it applied through `df`, so any issue with accounting/enforcement after that would be a kernel bug.

**Comment by s3rj1k** [comment] 2019-10-22 13:19
@stgraber LXD snap version works with this disk layout and configs.

**Comment by stgraber** [comment] 2019-10-22 15:52
And a container without a quota doesn't hit that error?

**Comment by stgraber** [comment] 2019-10-22 15:54
`File too large` sounds like you may be hitting a prlimit/ulimit rather than it being a quota issue, which would explain why you would see something different between snap and manual build as one is started through systemd and our wrapper while the other isn't, possibly leading to different limits being applied.

**Comment by s3rj1k** [comment] 2019-10-22 16:10
CT without quota behaves as expected, no errors

**Comment by s3rj1k** [comment] 2019-10-22 16:21
Inside CT:
```
root@test:~# ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 7730
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) unlimited
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

I am actually using systemd to unit to start LXD

```
[Unit]
Description=LXD - main daemon
After=network-online.target openvswitch-switch.service lxcfs.service lxd.socket
Requires=network-online.target lxcfs.service lxd.socket

[Service]
EnvironmentFile=-/etc/environment
# ExecStartPre=/usr/lib/x86_64-linux-gnu/lxc/lxc-apparmor-load
ExecStart=/usr/bin/lxd --group lxd --logfile=/var/log/lxd/lxd.log
ExecStartPost=/usr/bin/lxd waitready --timeout=600
KillMode=process
TimeoutStartSec=600s
TimeoutStopSec=30s
Restart=on-failure
LimitNOFILE=infinity
LimitNPROC=infinity
LimitFSIZE=infinity
TasksMax=infinity

[Install]
Also=lxd-containers.service lxd.socket
```

add LimitFSIZE=infinity, still seeing error

**Comment by s3rj1k** [comment] 2019-10-22 16:24
Actually yes, without quota still have this error, WTF?

**Comment by s3rj1k** [comment] 2019-10-22 16:53
@stgraber this is shitfs related. removing /lib/modules/5.3.0-19-generic/kernel/fs/shiftfs.ko fixed above error with large file.

Now the questing is how do i disable shifts property. blacklisting module did not help last time I tried.

Also there are no shiftfs settings in LXD itself

**Comment by s3rj1k** [comment] 2019-10-22 17:00
@stgraber I can confirm that quota works as expected without ```shiftfs``.

Why on earth this is enabled by default on all kernels and LXD and in [snap is disabled](https://github.com/lxc/lxd-pkg-snap/blob/latest-edge/patches/0001-lxd-Add-temporary-variable-to-disable-shiftfs.patch)?

**Comment by stgraber** [comment] 2019-10-22 18:54
LXD uses shiftfs whenever available, though due to kernel issues that are still being worked on, we have a patch in the snap that adds a knob to control it, disabling it by default and eventually enabling it if we're running on a known good kernel.

So sounds like this issue has nothing to do with project quotas but instead with handling of a particular filesystem operation. We'll need @brauner to look into that one and see if it's something we've fixed already in shiftfs or that needs extra fixing.

**Comment by stgraber** [comment] 2019-10-22 18:55
Closing as there isn't any action for us to pursue in LXD, but will put it on @brauner's todo to sort this out at the shiftfs level.

**Closed by stgraber** 2019-10-22 18:55 UTC

**Comment by brauner** [comment] 2019-10-22 19:17
```diff
diff --git a/fs/shiftfs.c b/fs/shiftfs.c
index 55bb32b611f2..49b7777dde22 100644
--- a/fs/shiftfs.c
+++ b/fs/shiftfs.c
@@ -2045,6 +2045,7 @@ static int shiftfs_fill_super(struct super_block *sb, void *raw_data,
                err = -EINVAL;
                goto out_put_path;
        }
+       sb->s_maxbytes = MAX_LFS_FILESIZE;

        inode = new_inode(sb);
        if (!inode) {
```

This should fix it.

**Comment by stgraber** [comment] 2019-10-22 19:19
@brauner thanks, that was quick :)
Can you get a test kernel for @s3rj1k to validate that his stuff works fine?
And do the usual sending of the fix through the usual Ubuntu channels :)

One of these days we'll actually have shiftfs behave the way we want it!

**Comment by s3rj1k** [comment] 2019-10-22 19:19
@stgraber @brauner Thanks )

**Comment by s3rj1k** [comment] 2019-10-22 19:20
I am willing to test this out as soon as I get test kernel

**Comment by brauner** [comment] 2019-10-22 19:24
I think having Kinderkrankheiten like this is pretty normal for something like shiftfs. I'm actually more and more happy since it also allowed us to find bugs in other filesystems. I'm pretty sure that our overlayfs changes should be upstreamed but there's only so hours in one day. :)

**Comment by brauner** [comment] 2019-10-22 19:24
@s3rj1k building a kernel atm.

**Comment by brauner** [comment] 2019-10-22 20:39
With my fix:
```sh
Script started on 2019-10-22 20:37:32+0000
root@b3:~# fallocate --length 5g aaaa
root@b3:~# du -sh ./aaaa 
5.0G	./aaaa
root@b3:~# rm aaaa 
root@b3:~# exit
Script done on 2019-10-22 20:37:50+0000
```

Here is a kernel for you to test:
https://drive.google.com/open?id=15pLG3FAE52h6njRCfzgkZnG3tLen4ct0

**Comment by brauner** [comment] 2019-10-22 20:39
@s3rj1k ^^

**Comment by s3rj1k** [comment] 2019-10-22 21:05
@brauner kernel fixes ```File too large``` error but breaks quota enforcement 
![2019-10-23_00-02-55](https://user-images.githubusercontent.com/11349489/67333007-86c40100-f528-11e9-9d0b-f22a65794353.png)

as seen in screen I can create file larger then available quota

**Comment by brauner** [comment] 2019-10-22 21:11
@stgraber, any idea about the quota stuff for the underlay?

**Comment by brauner** [comment] 2019-10-22 21:46
I can reproduce this on non-shiftfs as well though.

**Comment by s3rj1k** [comment] 2019-10-22 21:51
@brauner did you do ```tune2fs -O project,quota -Q prjquota /dev/sda1``` on fs before mounting it with ```prjquota``` ?

**Comment by brauner** [comment] 2019-10-22 22:19
Might be as simple as:
```diff
PTRACE_EVENTMSG_SYSCALL_EXIT BugLink: https://bugs.launchpad.net/bugs/1848817

    [ Upstream commit 710ec38b0f633ab3e2581f07a73442d809e28ab0 ]
 (cherry picked from commit 0eebfed2954f152259cae0ad57b91d3ea92968e8
     https://git.kernel.org/pub/scm/linux/kernel/git/kees/linux.git)
    Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>
BugLink: https://bugs.launchpad.net/bugs/1849281diff --git a/fs/shiftfs.c b/fs/shiftfs.c
index 55bb32b611f2..49b7777dde22 100644
--- a/fs/shiftfs.c
+++ b/fs/shiftfs.c
@@ -2045,6 +2045,7 @@ static int shiftfs_fill_super(struct super_block *sb, void *raw_data,
                err = -EINVAL;
                goto out_put_path;
        }
+       sb->s_maxbytes = MAX_LFS_FILESIZE;

        inode = new_inode(sb);
        if (!inode) {
index 55bb32b611f2..49b7777dde22 100644
--- a/fs/shiftfs.c
+++ b/fs/shiftfs.c
@@ -2045,6 +2045,7 @@ static int shiftfs_fill_super(struct super_block *sb, void *raw_data,
                err = -EINVAL;
                goto out_put_path;
        }
+       sb->s_maxbdiff --git a/fs/shiftfs.c b/fs/shiftfs.c
index 55bb32b611f2..49b7777dde22 100644
--- a/fs/shiftfs.c
+++ b/fs/shiftfs.c
@@ -2045,6 +2045,7 @@ static int shiftfs_fill_super(struct super_block *sb, void *raw_data,
                err = -EINVAL;
                goto out_put_path;
        }
+       sb->s_maxbytes = MAX_LFS_FILESIZE;

        inode = new_inode(sb);
        if (!inode) {
commit 69a28dcd8c22b3afb71ba867837f508e14424910 (HEAD -> shiftfs_fallocate, origin/shiftfs_fallocate)
Author: Christian Brauner <christian.brauner@ubuntu.com>
Date:   Wed Oct 23 00:16:17 2019 +0200

    shiftfs: drop CAP_SYS_RESOURCE to avoid overriding disk quotas

    Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

diff --git a/fs/shiftfs.c b/fs/shiftfs.c
index 49b7777dde22..81a73b87c395 100644
--- a/fs/shiftfs.c
+++ b/fs/shiftfs.c
@@ -2046,6 +2046,8 @@ static int shiftfs_fill_super(struct super_block *sb, void *raw_data,
                goto out_put_path;
        }
        sb->s_maxbytes = MAX_LFS_FILESIZE;
+       /* Don't override disk quota limits or use reserved space. */
+       cap_lower(sbinfo->creator_cred->cap_effective, CAP_SYS_RESOURCE);

        inode = new_inode(sb);
        if (!inode) {
commit 69a28dcd8c22b3afb71ba867837f508e14424910 (HEAD -> shiftfs_fallocate, origin/shiftfs_fallocate)
Author: Christian Brauner <christian.brauner@ubuntu.com>
Date:   Wed Oct 23 00:16:17 2019 +0200

    shiftfs: drop CAP_SYS_RESOURCE to avoid overriding disk quotas

    Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

diff --git a/fs/shiftfs.c b/fs/shiftfs.c
index 49b7777dde22..81a73b87c395 100644
--- a/fs/shiftfs.c
+++ b/fs/shiftfs.c
@@ -2046,6 +2046,8 @@ static int shiftfs_fill_super(struct super_block *sb, void *raw_data,
                goto out_put_path;
        }
        sb->s_maxbytes = MAX_LFS_FILESIZE;
+       /* Don't override disk quota limits or use reserved space. */
+       cap_lower(sbinfo->creator_cred->cap_effective, CAP_SYS_RESOURCE);

        inode = new_inode(sb);
        if (!inode) {
```

**Comment by s3rj1k** [comment] 2019-10-22 22:30
@brauner I can check later today (in morning by CEST) in my setup if you prepare updated kernel.

**Comment by brauner** [comment] 2019-10-22 22:32
@s3rj1k sure, will link to a new kernel here.

**Comment by stgraber** [comment] 2019-10-22 22:45
@brauner yeah, enabling project quotas needs some effort, the tooling for it is rather awful :)
LXD dir containers on a filesystem that's had the tune2fs property set and is mounted with the prjquota option will normally do the right thing then.

**Comment by brauner** [comment] 2019-10-22 22:46
> @brauner yeah, enabling project quotas needs some effort, the tooling for it is rather awful :)
> LXD dir containers on a filesystem that's had the tune2fs property set and is mounted with the prjquota option will normally do the right thing then.

My Ubuntu vm doesn't support it and I got pretty mad when I realized that adding `prjquota` as a mount option in `/etc/fstab` forced me to reboot into rescue mode and remount my rootfs rw, so I could edit my fstab...

**Comment by brauner** [comment] 2019-10-22 23:40
@s3rj1k
https://drive.google.com/open?id=1hZFPw7cqCQL1ptCHQINgb2NBi4A5rTp2

**Comment by s3rj1k** [comment] 2019-10-23 06:33
@brauner Confirming that latest kernel works correctly with quotas and shiftfs. Yay))

When this fix is expected to be publicly available? (To double test this on public kernel)

**Comment by brauner** [comment] 2019-10-23 09:00
> @brauner Confirming that latest kernel works correctly with quotas and shiftfs. Yay))

Excellent.

> When this fix is expected to be publicly available? (To double test this on public kernel)

In a couple of weeks. I'll give you a link to the launchpad bug here.

**Comment by brauner** [comment] 2019-10-23 12:25
@s3rj1k here are the launchpad bugs to track:
- [shiftfs: prevent exceeding project quotas](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1849483)
- [shiftfs: fix fallocate()](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1849482)

Once a kernel will be proposed it'll be mentioned in these bugs. You can subscribe to them to get notified when that happens.

**Comment by s3rj1k** [comment] 2019-10-23 12:49
@brauner Thanks, hoping to see this fix soon )

**Comment by s3rj1k** [comment] 2019-10-23 12:54
@stgraber Small not related question. How can I programmatically match container with project quota ID, to get usage statistics?

**Comment by stgraber** [comment] 2019-10-23 13:02
The id is 10000 + id of container as you'd find them in `lxd sql global "SELECT id, name FROM instances;"`

Note that the used space is also reported through `lxc info NAME`.

**Comment by s3rj1k** [comment] 2019-10-23 13:06
@stgraber Thanks, ```lxc info NAME``` sadly does not report correct usage

**Comment by s3rj1k** [comment] 2019-10-23 13:54
@stgraber Should I do separate Issue for ```lxc info NAME``` bug?

**Comment by stgraber** [comment] 2019-10-23 13:58
Yeah, that'd be good to track down, I would have expected data to be returned just fine for dir backend.

**Comment by stgraber** [comment] 2019-10-23 17:54
```
4825  quotactl(QCMD(Q_GETQUOTA, PRJQUOTA), "/dev/md1", 10001, {dqb_bhardlimit=7812500, dqb_bsoftlimit=0, dqb_curspace=8000000000, dqb_ihardlimit=0, dqb_isoftlimit=0, dqb_curinodes=35839, ...}) = 0
4825  write(2, "\33[31mEROR\33[0m[10-23|20:48:42] stgraber: ContainerGetUsage failed, err=Failed to get project consumption for id '10001' on '/dev/md1' \n", 134) = 134
```

That's weird, it shows success and the right data, then prints the error anyway :)
