### ISSUE TITLE
LXD Go client API requires Cgo components

### ISSUE THREAD

**Issue by zenitraM** [lxc/lxd#2417] opened 2016-09-22 18:44 UTC
Doing just `GOOS=linux GOARCH=amd64 go build` from OSX to Linux from an app that has an import to "github.com/lxc/lxd" to use the Client API:

```
# github.com/lxc/lxd/shared
../../lxc/lxd/shared/idmapset_linux.go:221: undefined: GetFileStat
../../lxc/lxd/shared/idmapset_linux.go:248: undefined: ShiftOwner
```

This seems to be due to the usage of a cgo library that cannot be cross-compiled from OSX, and that doesn't seem related to the client but rather to the LXD daemon itself.

Maybe the client / client libraries should be on a separate package to allow importing them without dragging the rest of the daemon.

(Probably related to #1926?)

**Comment by zenitraM** [comment] 2016-09-22 20:33
It's just a minor annoyance for us now, but some people may find it easier to just reimplement a separate client for the LXD REST api from scratch than going though those hoops to integrate the (otherwise fine) client API.

(I can see it for the CLI client, but why would termios be needed for an API client?)

**Comment by stgraber** [comment] 2016-09-22 20:41
Yeah, it's only used by the CLI right now. As I said, we have #1926 where I intend to publish a new LXD client library that's better suited for use by downstream projects.

client.go as it is right now, really isn't a stable API, it's a side effect of us needing the same client code in both the CLI and the daemon and then for a couple of more downstream projects that we maintain, rather than a well thought through package for us by other projects.

**Comment by tych0** [comment] 2016-09-22 20:52
On Thu, Sep 22, 2016 at 11:54:18AM -0700, Stéphane Graber wrote:
> Possibly, I have a vague plan to make client.go and lxc/* independent from shared/ but that's very much not a priority for us.
> 
> We do care a bit about building the client on MacOS or Windows, but we care much less about people cross-building Linux binaries on another OS.
> 
> Note that even with those two sorted out, you'll still hit a build failure on shared/termios which is very much used in the client.

Yeah, although I don't think it's used in the daemon or client.go, so
it could me moved into lxc/*.

For that matter, there's a bunch of stuff (the stuff in the OP
included) which isn't really shared and could be moved into the daemon
or client directories respectively. I'd be happy to review patches for
that, although stgraber is right we've got some other stuff to finish
before yakkety and probably can't do it ourselves right now.

**Comment by stgraber** [comment] 2016-09-22 21:01
Yeah and such a change will make cherry-picks a pain for the stable branch, so I'd rather we do that at the same time as we break client.go too, that way I only need to deal with the mess once :)

**Comment by stgraber** [comment] 2016-09-23 21:05
I added a note to #1926 that we should keep outside dependencies to a minimum, so considering this issue a duplicate of that now. This will be addressed when we publish a proper client library for downstreams.

**Closed by stgraber** 2016-09-23 21:05 UTC
