### ISSUE TITLE
Make `lxc version --verbose` expose build timestamp/hash

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#3239] opened 2017-04-27 18:11 UTC
It is useful for testing if `lxc --version` exposed build timestamp and hash. Maybe with `--verbose`.

```
>lxc --version
2.12
```

```
>lxc --version --verbose
2.12 699f8fc 2017-03-23T20:18:06Z
```

**Comment by stgraber** [comment] 2017-04-27 18:13
We can't include the git commit because our builds are made from the release tarball which doesn't include any git information (on purpose). The build time should be possible but I really fail to see the point.

**Comment by techtonik** [comment] 2017-04-27 23:21
The point is 1. automated testing, 2. manual debug runs.

**Comment by stgraber** [comment] 2017-04-27 23:44
Closing this issue. As mentioned, the Go build system doesn't let us include the result of arbitrary commands, so we can't include the git commit. The build timestamp may be extractable (though I don't know how) but wouldn't be very useful without the git commit information.

The other problem with this whole thing is that it'd by definition make the build non-reproducible since every build even of the exact same thing would contain a different string built into the code. This would cause problems for distributions which use reproducible builds mechanisms.

**Closed by stgraber** 2017-04-27 23:44 UTC

**Comment by techtonik** [comment] 2017-04-28 00:52
> This would cause problems for distributions which use reproducible builds mechanisms.

Which distributions exactly? Hash builds are reproducible.

**Comment by stgraber** [comment] 2017-04-28 02:30
Debian has been doing reproducible builds, Ubuntu has been looking at following suit. I don't know for the RPM based distros. If there was an easy way to include the git hash, I wouldn't be opposed to doing that, but there isn't. Go doesn't use autotools or a similar build system which allows to expose such things easily. Not that the hash would be particularly useful either as it wouldn't tell you anything about all the imported code that's more often than not, the cause of the actual problems.
