### ISSUE TITLE
daily image 20160127 ubuntu container on 14.04.3 host causes errors in cloud-init

### ISSUE THREAD

**Issue by mikemccracken** [lxc/lxd#1549] opened 2016-01-28 18:16 UTC
using lxd from ppa:ubuntu-lxc/lxd-stable  on trusty is showing an issue that's new to me:

with both the most recent release image and with the most recent daily image:
```
ubuntu@rickross:~⟫ lxc image list
+--------+--------------+--------+--------------------------------------+--------+----------+-------------------------------+
| ALIAS  | FINGERPRINT  | PUBLIC |             DESCRIPTION              |  ARCH  |   SIZE   |          UPLOAD DATE          |
+--------+--------------+--------+--------------------------------------+--------+----------+-------------------------------+
| ubuntu | 1032903165a6 | no     | Ubuntu 14.04 LTS server (20160114.5) | x86_64 | 118.21MB | Jan 27, 2016 at 11:00pm (UTC) |
+--------+--------------+--------+--------------------------------------+--------+----------+-------------------------------+

# and this one:

> lxc image list
+--------+--------------+--------+------------------------------------+--------+----------+------------------------------+
| ALIAS  | FINGERPRINT  | PUBLIC |            DESCRIPTION             |  ARCH  |   SIZE   |         UPLOAD DATE          |
+--------+--------------+--------+------------------------------------+--------+----------+------------------------------+
| ubuntu | 691637707b72 | no     | Ubuntu 14.04 LTS server (20160127) | x86_64 | 118.17MB | Jan 28, 2016 at 6:05pm (UTC) |
+--------+-------------
```

`lxc init foo` and `lxc start foo` bring up a working container, but cloud-init throws an error.
if you then `lxc exec foo -- tail /var/log/cloud-init-output.log`, you get this:

```
Generation complete.
Cloud-init v. 0.7.5 running 'modules:final' at Thu, 28 Jan 2016 17:14:07 +0000. Up 6.0 seconds.
ci-info: no authorized ssh keys fingerprints found for user ubuntu.
2016-01-28 17:14:07,258 - util.py[WARNING]: Running ssh-authkey-fingerprints (<module 'cloudinit.config.cc_ssh_authkey_fingerprints' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_ssh_authkey_fingerprints.pyc'>) failed
2016-01-28 17:14:07,278 - cc_keys_to_console.py[WARNING]: Writing keys to the system console failed!
2016-01-28 17:14:07,279 - util.py[WARNING]: Running keys-to-console (<module 'cloudinit.config.cc_keys_to_console' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_keys_to_console.pyc'>) failed
Cloud-init v. 0.7.5 finished at Thu, 28 Jan 2016 17:14:07 +0000. Datasource DataSourceNoCloudNet [seed=/var/lib/cloud/seed/nocloud-net][dsmode=net].  Up 6.0 seconds
```

**Comment by nehaljwani** [comment] 2016-01-28 22:34
So, to dig further on this issue, I edited the file: `/usr/lib/python2.7/dist-packages/cloudinit/config/cc_keys_to_console.py` inside the container before launching it for the first time, and added the line...
```
log.warn(traceback.format_exc())
```
...and got the following in the error log:
```
[root@lxc-dev ~]# lxc exec ubuntu -- tail -f /var/log/cloud-init-output.log
2016-01-28 22:28:39,290 - cc_keys_to_console.py[WARNING]: Writing keys to the system console failed! YOLO
2016-01-28 22:28:39,290 - cc_keys_to_console.py[WARNING]: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cloudinit/config/cc_keys_to_console.py", line 50, in handle
    stderr=False, console=True)
  File "/usr/lib/python2.7/dist-packages/cloudinit/util.py", line 371, in multi_log
    with open(conpath, 'wb') as wfh:
IOError: [Errno 1] Operation not permitted: '/dev/console'

2016-01-28 22:28:39,290 - util.py[WARNING]: Running keys-to-console (<module 'cloudinit.config.cc_keys_to_console' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_keys_to_console.py'>) failed
Cloud-init v. 0.7.5 finished at Thu, 28 Jan 2016 22:28:39 +0000. Datasource DataSourceNoCloudNet [seed=/var/lib/cloud/seed/nocloud-net][dsmode=net].  Up 10098.92 seconds
```

**Comment by stgraber** [comment] 2016-01-29 08:24
This is a duplicate of #1463

**Closed by stgraber** 2016-01-29 08:24 UTC
