### ISSUE TITLE
error when ipv4.address is set

### ISSUE THREAD

**Issue by ldsbiblibre** [lxc/lxd#3920] opened 2017-10-09 10:51 UTC
* Distribution: ubuntu 
 * Distribution version:16.04.3 LTS
 * The output of "lxc info" or if that fails:
  driver: lxc
  driver_version: 2.1.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-96-generic
  server: lxd
  server_pid: 22809
  server_version: "2.18"
  storage: dir
  storage_version: "1"

   * Kernel version: 4.4.0-96-generic
   * LXC version: 2.1.0
   * LXD version: 2.18
   * Storage backend in use: dir

# Issue description

since passing in lxd 2.18 I can no longer assign ip to my containers

# Steps to reproduce

lxc network attach lxdbr0 test eth0
lxc config device set test eth0 ipv4.address 10.215.181.249
error: LXC doesn't know about this device and the host_name property isn't set, can't find host side veth name

# Information to attach

 - [ ] Container log (`lxc info NAME --show-log`)
Name: test
Remote: unix://
Architecture: x86_64
Created: 2017/10/03 13:36 UTC
Status: Running
Type: persistent
Profiles: default
Pid: 132946
Ips:
  lo:	inet	127.0.0.1
  lo:	inet6	::1
Resources:
  Processes: 59
  CPU usage:
    CPU usage (in seconds): 8
  Memory usage:
    Memory (current): 474.80MB
    Memory (peak): 476.00MB
  Network usage:
    eth1:
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0
    lo:
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0

Log:

            lxc 20171009091416.522 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20171009091416.522 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20171009091416.767 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20171009091416.767 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.

 - [ ] Container configuration (`lxc config show NAME --expanded`)
architecture: x86_64
config:
  environment.http_proxy: ""
  image.description: test  (stop) (20171003_15:26)
  limits.cpu: "4"
  limits.memory: 4GB
  user.network_mode: ""
  volatile.base_image: ff532373af026e57b4da0ac6ee385ca2e77a6678331c480a0e05fd4521e99fc0
  volatile.eth0.hwaddr: 00:16:3e:2e:75:37
  volatile.eth0.name: eth1
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""

**Comment by brauner** [comment] 2017-10-09 10:58
Hm, can you restart the daemon and report back? What happens if you reboot one of those containers - if possible to do for you?

**Comment by ldsbiblibre** [comment] 2017-10-09 11:51
ok after restart ( systemctl restart lxd-containers.service lxd.service lxd.socket) the error disappears
 but I have to manually run dhclient in the container to get the ipv4

**Comment by ldsbiblibre** [comment] 2017-10-09 11:53
oh very strange it's a eth1@if631 interface

**Comment by stgraber** [comment] 2017-10-09 12:10
Hmm, so there's a bug in that we apparently attempt to remove and re-add the interface when all you're changing is ipv4.address/ipv6.address. Since those properties don't actually affect the nic, we should remove/re-add it if changed.

@brauner can you send a fix for that?

**Comment by stgraber** [comment] 2017-10-09 12:11
As for why it doesn't get auto-configured after a restart of the container, only eth0 is configured in most Linux distributions, so if you want DHCP on eth1, you'll have to configure your container's network configuration to do so.

**Comment by ldsbiblibre** [comment] 2017-10-09 12:18
In fact, I do not understand why this eth1 interface is mounted
all my container network interface are in eth0 (dhcp) !!!
The "bug" it is only when I want to set up the ipv4 myself

**Comment by brauner** [comment] 2017-10-09 12:29
Actually, this works perfectly fine for me here with `2.18`. I can change the address and everything.

**Comment by stgraber** [comment] 2017-10-09 12:40
@brauner that's when you hotplug a nic and then set ipv4.address afterwards without restarting the container?

**Comment by brauner** [comment] 2017-10-09 12:45
@stgraber, is that what yo mean: https://asciinema.org/a/141446

**Comment by ldsbiblibre** [comment] 2017-10-09 12:59
the error message appears again for another container.
error: LXC doesn't know about this device and the host_name property isn't set, can't find host side veth name

**Comment by brauner** [comment] 2017-10-09 13:20
Did you only upgrade lxd or did you also upgrade liblxc?

**Comment by ldsbiblibre** [comment] 2017-10-09 14:13
my liblxc version is 2.1.0-0ubuntu1~ubuntu16.04.1~ppa1

**Comment by brauner** [comment] 2017-10-09 18:04
@stgraber, I have a possible explanation for this behavior: Imagine a `LXD` + `liblxc` update was performed. The currently running container has `liblxc < 2.1` loaded. Then LXD gets updated, the daemon gets restarted and any new requests will cause LXD to load `liblxc >= 2.1`. Now, the user issues a `ipv4.address` request. `LXD`, because it has `liblxc >= 2.1` loaded will now try to retrieve the value for `lxc.net.[idx].ipv4.address` and will receive `""` since the container still runs with `liblxc < 2.1` and hence the container expects `lxc.network.[idx].ipv4`.

**Comment by stgraber** [comment] 2017-10-09 18:28
@brauner nope, that's not what ipv4.address and ipv6.address do, they setup static DHCP entries in dnsmasq

**Comment by stgraber** [comment] 2017-10-09 18:29
@brauner whether you can reproduce the error or not, we should change the Update() function in container_lxc.go to NOT remove/re-add the network device when all that's changed is the ipv4.address or ipv6.addres properties as those do not require any configuration change to the running container.

**Comment by brauner** [comment] 2017-10-09 18:33
Sorry, my last comment was wrong. I didn't mean `lxc.net.[idx].ipv4.address` what I obviously was getting at is retrieving the host side veth name from the running container. Specifically, what I was referring to is this codepath:

```
	if c.IsRunning() {
		networkKeyPrefix := "lxc.net"
		if !lxc.VersionAtLeast(2, 1, 0) {
			networkKeyPrefix = "lxc.network"
		}

		for i := 0; i < len(c.c.ConfigItem(networkKeyPrefix)); i++ {
			nicName := c.c.RunningConfigItem(fmt.Sprintf("%s.%d.name", networkKeyPrefix, i))[0]
			if nicName != name {
				continue
			}

			veth := c.c.RunningConfigItem(fmt.Sprintf("%s.%d.veth.pair", networkKeyPrefix, i))[0]
			if veth != "" {
				return veth
			}
		}
	}
```
Which is where the error is thrown from `getHostInterface()` in `container_lxc.go`.

**Comment by stgraber** [comment] 2017-10-09 18:44
@brauner right, my point is that if your only changes are ipv4.address or ipv6.address, we shouldn't hit any of that code at all

**Comment by brauner** [comment] 2017-10-09 18:46
@stgraber, yeah I know but I wanted to understand how this happened. Because I couldn't reproduce. I don't like making changes without knowing why. :)

**Comment by stgraber** [comment] 2017-10-09 18:47
:)

**Comment by brauner** [comment] 2017-10-10 11:55
Note to self: This can also happen when a device is hotplugged in which case liblxc does not know anything about this device and hence retrieving any useful information for it from liblxc via `get_config_item()`/`get_running_config_item()` is not possible.

**Comment by brauner** [comment] 2017-10-10 11:59
LXD is handling the case where liblxc knows about the device - the case where the device is not hotplugged - correctly i.e. it does not remove and then add the network device again. Instead it simply updated the lease file. So the only codepath here that is questionable is trying to query liblxc for the name of the device when it can' t possibly know about it.

**Comment by stgraber** [comment] 2017-10-10 14:42
Ok, so if we're not removing/re-adding, then it's more reasonable.

Ideally we wouldn't even query the device name if we don't need to, but if that's too big a change then I'm fine with just closing this and adding it to the pile of LXC 2.1 changes that need a container restart.

**Comment by brauner** [comment] 2017-10-10 14:53
@stgraber, the proper solution would be to enable LXD to tell liblxc: "please add this netdev to your config". I looked at the LXD code and the thing is that all of the ingress and egress limits call out to tc which needs the name of the device. I didn't sent a patch yet because I wasn't sure if we need to call tc even if we change only ipv{4,6}.

**Comment by stgraber** [comment] 2017-10-10 15:07
Oh right because we use a shared codepath for the limits and for ipv4/ipv6 address, if it was separate then ipv4/ipv6 address wouldn't need that information.

**Comment by brauner** [comment] 2017-10-11 08:09
Actually the codepaths are separate. The limits update is performed in a different function and in a different place then the ipv{4,6} upgrade. The problem with the limits lies in the fact that LXD currently doesn't check prior to trying to query liblxc for the device name whether any of those keys actually needs to be updated. Sending a branch with a minimal fix now.

**Comment by brauner** [comment] 2017-10-11 10:25
@stgraber, I've sent a fix to LXD for this now. I also made a POC for container live patching whereby you can patch the container's in-memory config. This can be used by LXD to inform liblxc of hotplugged network devices.

**Closed** 2017-10-11 21:27 UTC
Labels: Bug, Easy
