### ISSUE TITLE
snapd upgrade to 3.19: Error: Get http://unix.socket/1.0: dial unix /var/snap/lxd/common/lxd/unix.socket: connect: connection refused

### ISSUE THREAD

**Issue by tchwpkgorg** [lxc/lxd#6762] opened 2020-01-23 23:23 UTC
After lxd from snap was upgraded to 3.19, lxd process no longer works, and lxc commands error with "Error: Get http://unix.socket/1.0: dial unix /var/snap/lxd/common/lxd/unix.socket: connect: connection refused":

```
# lxc list
Error: Get http://unix.socket/1.0: dial unix /var/snap/lxd/common/lxd/unix.socket: connect: connection refused
```

```
# systemctl status  snap.lxd.daemon.service  
● snap.lxd.daemon.service - Service for snap application lxd.daemon
   Loaded: loaded (/etc/systemd/system/snap.lxd.daemon.service; static; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2020-01-23 14:43:32 UTC; 8h ago
 Main PID: 20484 (code=exited, status=1/FAILURE)

Jan 23 14:43:42 samsung lxd.daemon[1230]:   4: fd:  12: devices
Jan 23 14:43:42 samsung lxd.daemon[1230]:   5: fd:  13: net_cls,net_prio
Jan 23 14:43:42 samsung lxd.daemon[1230]:   6: fd:  14: perf_event
Jan 23 14:43:42 samsung lxd.daemon[1230]:   7: fd:  15: pids
Jan 23 14:43:42 samsung lxd.daemon[1230]:   8: fd:  16: cpu,cpuacct
Jan 23 14:43:42 samsung lxd.daemon[1230]:   9: fd:  17: hugetlb
Jan 23 14:43:42 samsung lxd.daemon[1230]:  10: fd:  18: freezer
Jan 23 14:43:42 samsung lxd.daemon[1230]:  11: fd:  19: name=systemd
Jan 23 14:43:42 samsung lxd.daemon[1230]:  12: fd:  20: unified
Jan 23 14:43:42 samsung lxd.daemon[1230]: lxcfs.c: 152: do_reload: lxcfs: reloaded

```

```
# systemctl status  snap.lxd.daemon.unix.socket
● snap.lxd.daemon.unix.socket - Socket unix for snap application lxd.daemon
   Loaded: loaded (/etc/systemd/system/snap.lxd.daemon.unix.socket; enabled; vendor preset: enabled)
   Active: failed (Result: service-start-limit-hit) since Thu 2020-01-23 14:43:32 UTC; 8h ago
   Listen: /var/snap/lxd/common/lxd/unix.socket (Stream)

Jan 23 14:33:43 samsung.virtall.com systemd[1]: Listening on Socket unix for snap application lxd.daemon.
Jan 23 14:43:32 samsung.virtall.com systemd[1]: snap.lxd.daemon.unix.socket: Failed with result 'service-start-limit-hit'.

```

Nothing listens here:

```
# netstat -lnp | grep 8443
```

The container is still running, according to ps auxf output.

**Comment by tomponline** [comment] 2020-01-23 23:29
Can you check your not affected by this issue and upgrade to latest stable snap to check https://discuss.linuxcontainers.org/t/3-19-update-lxd-daemon-wont-startup-dir-backend-storage-init-problem/6576

**Comment by tchwpkgorg** [comment] 2020-01-23 23:39
Yes, looks like it.

**Comment by tomponline** [comment] 2020-01-23 23:41
So the lxd snap on stable channel has a fix for this now. Duplicate of https://github.com/lxc/lxd/issues/6759

**Comment by stgraber** [comment] 2020-01-24 06:07
`snap refresh lxd` will force the upgrade, if that doesn't resolve it, let us know.

**Closed** 2020-01-24 06:06 UTC
