### ISSUE TITLE
Implement networking features from LXC

### ISSUE THREAD

**Issue by reversecipher** [lxc/lxd#1250] opened 2015-10-28 14:33 UTC
I would like to see some of the networking features from LXC be implemented in LXD:

* Ability to set nictype to other than bridged, for example create only veth pair without attaching to any bridge
* lxc.network.veth.pair (for privileged containers)
* ability to set container IP address and gateway
* lxc.network.script.up & lxc.network.script.down

I know these can be accomplished by raw.lxc, but it would be nice to be able to configure them under the device configuration.

**Comment by stgraber** [comment] 2015-10-28 14:44
Create only a veth pair and not attach it as well as allowing for the host side veth to be set through the API is fine with me.

LXD will not allow random scripts to be run on the host at container start/stop as this leads to unknown results, especially when you factor in (live) migration where your target may lack said script. The long term plan is to have an official hook system provided by LXD which will allow programs to register with LXD and get (possibly blocking) notifications at various time in the container lifecycle. Those hooks would be required to implement a standard communication protocol including error reporting and timeout so that LXD can now exactly what failed and respond to the user accordingly.

As for pre-configuring the network namespace (that's what you mean with the LXC address/gateway keys), we have no plan to implement this in LXD.
The reason for that is that most (currently all) supported distributions will wipe such information at boot or will otherwise be confused by it (fail to bring up network due to duplicate default gateway).
This LXC feature was designed for application containers and was indeed very useful for things like Docker. LXD focuses only on infrastructure containers, which are guaranteed to have a normal init system that will take care of networking for you.
Note that with current LXD you can seed networking from the outside by using mechanisms such as cloud-init or the image templating mechanism. Those will let you set container properties which will then be used to set configuration or render files inside the container.

**Comment by stgraber** [comment] 2015-10-28 14:45
I'll use this issue to track allowing getting just an unbridged veth pair and allowing to set the host side name of a veth pair.

**Comment by kfix** [comment] 2015-10-29 20:26
Sorry to pile-on, but what about `lxc.network.type = none`?
assuming one templates a `lo`-only /etc/network/interfaces and purged redundant management daemons
(avahi, sshd), `none` allowed creating an infrastructure-lite container for apps which don't need individual addresses.

**Comment by stgraber** [comment] 2015-10-29 20:30
Given that LXD currently only focuses on machine containers, it seems unlikely that we would be adding such an option. Someone wishing to run single apps in a partial container ought to build on top of liblxc1 directly or use one of the many application container technologies.

**Comment by stgraber** [comment] 2016-01-26 22:12
Closing this as I believe we've now implemented all the network features that we plan on supporting in LXD.

**Closed by stgraber** 2016-01-26 22:12 UTC
