### ISSUE TITLE
lxc image export gives a permission denied error

### ISSUE THREAD

**Issue by MirtoBusico** [lxc/lxd#3636] opened 2017-08-06 12:35 UTC
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu
 * Distribution version: Kubuntu 16.04 updated at 6 Aug 2017
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-89-generic #112-Ubuntu SMP Mon Jul 31 19:38:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
   * LXC version: 2.16
   * LXD version: (snap) lxd   2.16        3235  canonical  -
   * Storage backend in use: zfs

# Issue description

A brief description of what failed or what could be improved.
Executing "lxc image export $c-image $c-image.tar.gz" (with $c = db-server) gives this error:
error: open db-server-image.tar.gz: permission denied

# Steps to reproduce

 1. Step one - create a container based on ubuntu 16.04 named db-server
 2. Step two
    execute sudo -i
    execute this script:
`#!/bin/bash
# ATTENTION execute with sudo -i
echo " "
echo 'Backup of all containers:'
cd /BACKUP/LXC/
for c in db-server
do
    echo " "
    echo " "
    echo "================== container: $c ========================"
    echo "      ================= stop: $c ========================"
    lxc stop $c
    echo "      ========= delete image: $c ========================"
    lxc image delete $c-image
    echo "      ============== publish: $c ========================"
    lxc publish $c --alias $c-image
    sleep 10
    echo "      =============== export: $c ========================"
    lxc image export $c-image $c-image.tar.gz
    echo "      ================ start: $c ========================"
    lxc start $c
done
echo " "`

 3. Step three
   verify the output containing the error:
`sysop@vx00:~$ sudo -i
[sudo] password di sysop: 
root@vx00:~# /home/sysop/lxcbackup 
 
Backup of all containers:
 
 
================== container: db-server ========================
      ================= stop: db-server ========================
      ========= delete image: db-server ========================
      ============== publish: db-server ========================
Container published with fingerprint: 793188959ee7206b7a0990058faae321db401477e1307976f639981b7d1011f3
      =============== export: db-server ========================
error: open db-server-image.tar.gz: permission denied
      ================ start: db-server ========================
 
root@vx00:~#`

# Information to attach

 - [ ] any relevant kernel output (`dmesg`)
 - [ ] container log (`lxc info NAME --show-log`)
 - [ ] main daemon log (`cat /var/log/lxd/lxd.log`)
 - [ ] output of the client with --debug
 - [ ] output of the daemon with --debug

**Comment by stgraber** [comment] 2017-08-07 06:00
Duplicate of #3592

**Comment by stgraber** [comment] 2017-08-07 06:02
Marked this as a duplicate of an earlier issue. The short answer being that this is a snapd bug.
The LXD snap uses the "home" interface to allow writing in your home directory, unfortunately that snapd interface doesn't include /root. So if you're running the "lxc image export" command as the root user, you'll get permission denied.

Your best bet is to create a "lxd" group on your system, restart the lxd daemon which will then pick up that group and allow all its members to talk to LXD. You can then add your normal user to the group and have that user run the "lxc" command, which will then be allowed by snapd to write to your home directory.

**Closed by stgraber** 2017-08-07 06:02 UTC
