### ISSUE TITLE
Ephemeral containers not removed from file system after a failed restart

### ISSUE THREAD

**Issue by diegolagoglez** [lxc/lxd#2555] opened 2016-10-25 08:12 UTC
# Basic information

Ubuntu MATE 16.04.1 (amd64)

lxc info:

```
apiextensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFZzCCA0+gAwIBAgIRAIcY4+BoWuloI4mJ7k6I9H8wDQYJKoZIhvcNAQELBQAw
    MzEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzETMBEGA1UEAwwKcm9vdEBk
    ejYwMDAeFw0xNjA0MjgwOTQ3NTlaFw0yNjA0MjYwOTQ3NTlaMDMxHDAaBgNVBAoT
    E2xpbnV4Y29udGFpbmVycy5vcmcxEzARBgNVBAMMCnJvb3RAZHo2MDAwggIiMA0G
    CSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC9qVpuHObZPmoDnxB8wRR4an5akGEG
    MrrMhWWby0kbBou8D1ZYd6l0LokQsUj6fdbkRShAsAGZjV3RXtHNQffBd2Z08mt3
    YY3r13NFhthGASC/a329VMrxHjOL9gEuQVyZz/gKAelxWCiR6YHoAEN6JUltuKQU
    JPS8px0FtmJOSb+MkHqncZr9tVDe6d8d6U7TRrZsoT4XCK3oc+MrNu/VpHHa5mcc
    C/zITfWpPap72YbASo2m+NeNATeZ8ZuamiUugm0xBb10gzjliWg1XDAe2h3CjvOi
    kDSYZiWzhiWtpEwyfvrBwqyDJhq+8MuQfb9e+kIPuHFQDhUz1dEV9fg525cK0pHM
    gxOPMe8CggBOXrvkvcNtlSiJtdLuZIbixWfRcv3tLlk3tcpg7CUFTZsCEK0Y+uTq
    XPpVcOBvmCkbb3xkh0PCgO56mvzgQdt6v4ahOUEZHKqGso+XFUx+n9UR/8H6htQZ
    wHTPP3m2aJ/y3JWw0K8nAxcpqxw7MqLiwzuknVu8Wkjqp+UqSksuBJnLYLfa1tYn
    mYd0lPaQykObRphFl+t7C5uHh/xFlR2i4mGzqhtOiFHoRNJJd+QI0J/iwIqt0HRU
    cJ9Vgr5CNya6N9bXjdQoLX4FF9qVlMNPVl3BE94UBLouX0dN8Mrd5xbltngdIIxO
    xeoyKT4glHPHRQIDAQABo3YwdDAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYI
    KwYBBQUHAwEwDAYDVR0TAQH/BAIwADA/BgNVHREEODA2ggVkejYwMIIPMTUuMjMu
    MTguMTc1LzIyghxmZTgwOjpkNjg1OjY0ZmY6ZmVjNDo2NmNmLzY0MA0GCSqGSIb3
    DQEBCwUAA4ICAQBRVZPJmFpGbSsSwCYYjL3AESCTZveBwpe5GcRYc/ZFVjBB7Dlr
    Q4X72L3MswuR+EuLwJkPI6R3x6gOsh/3Lo0kC6kpKWRDY7lcLlUEF7cNQzGmIZ9g
    1gb1n0y5uPgZv53aBTJbndURoFwfyqngEVMOOMOVGLIGzm6p2hL8jye4JVHGLTY3
    Nz4N5xM2V7aN4SGI242AkV0a9hlVhdKRfIhhpeuUoOjQraAS19pBp9Vfd2BliJr2
    p4Y3MgMuO6z3w9QdHRugdFJ12K+O6BsaEZ3Or0UzANkRu9n7c9o1aJ6C5e+hwS1g
    VSd86p7lY0pf0lDb3JBcBGXZCxT7ILZP3w+kJgi+KRKrxhKP8OquOkBDcCZzJKK8
    CPYOEFCk0osv8l9AKY1VaDv9YxWuO66hJye//JN1YSeBK+U6mmMM3xkxagV8pQjK
    hHL6MIBlS+dyJiyGJSuCTrN+6zqg3iiwXaWYZ6LCo7gJdImmq2Ykg7SHPuuFdIkH
    /8G5rNf047+jrgaUk2RbD1bV5nBpjmYnFBw5EBbI898PlbKVyoNnI6t8tT7jnUEZ
    h+9S5yEiBVAwkZWUI4OBrp7e6t0KiekPflVAIiCJY1FrBpd4fl+wI8Awoh9EOMP9
    VtFelMCyh3v2vF+9O2YCHSpgx3kRPiCi/vdkqRT8dftljnRZTDcOkmzqaQ==
    -----END CERTIFICATE-----
  certificatefingerprint: 22147652d0f647e1b7884a504dc7059231c1b4cdd357c3e6d1750dc98c5f1e4e
  driver: lxc
  driverversion: 2.0.5
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-38-generic
  server: lxd
  serverpid: 109024
  serverversion: 2.4.1
  storage: dir
  storageversion: ""
config: ***proxy configuration omitted***
public: false
```

# Issue description

Ephemeral containers are not removed from the file system after a (failed) restart attempt.

# Steps to reproduce

1. Create an ephemeral container, for example: `lxc launch images:xenial x1e -e`

2. Try to restart the container: `lxc restart x1e`

  Next error is returned:
  ```
  error: Error calling 'lxd forkstart x1e /var/lib/lxd/containers /var/log/lxd/x1e/lxc.conf': err='exit status 1'
    lxc 20161025095214.959 ERROR lxc_conf - conf.c:run_buffer:347 - Script exited with status 1
    lxc 20161025095214.959 ERROR lxc_start - start.c:lxc_init:465 - failed to run pre-start hooks for container 'x1e'.
    lxc 20161025095214.959 ERROR lxc_start - start.c:__lxc_start:1313 - failed to initialize the container
  Try `lxc info --show-log x1e` for more info
  ```

3. `lxc info --show-log x1e` does not work (log not found).

4. If you try to create a new container with the same name (either ephemeral or not), `lxc` says **it already exists**, but if you run `lxc list`, the container does not appear. If you go to `/var/lib/lxd/containers`, the container file system is there, but the container does not appear when `lxc list` is run.

# Information to attach

 Relevant `/var/log/lxd/lxd.log` information:

```
t=2016-10-25T09:52:01+0200 lvl=info msg="Starting container" name=x1e action=start created=2016-10-25T07:51:51+0000 ephemeral=true used=1970-01-01T00:00:00+0000 stateful=false
t=2016-10-25T09:52:01+0200 lvl=info msg="Started container" name=x1e action=start created=2016-10-25T07:51:51+0000 ephemeral=true used=1970-01-01T00:00:00+0000 stateful=false
t=2016-10-25T09:52:11+0200 lvl=info msg="Shutting down container" created=2016-10-25T07:51:51+0000 ephemeral=true used=2016-10-25T07:52:01+0000 timeout=-1s name=x1e action=shutdown
t=2016-10-25T09:52:13+0200 lvl=info msg="Deleting container" ephemeral=true used=2016-10-25T07:52:01+0000 name=x1e created=2016-10-25T07:51:51+0000
t=2016-10-25T09:52:14+0200 lvl=info msg="Deleted container" name=x1e created=2016-10-25T07:51:51+0000 ephemeral=true used=2016-10-25T07:52:01+0000
t=2016-10-25T09:52:14+0200 lvl=info msg="Shut down container" created=2016-10-25T07:51:51+0000 ephemeral=true used=2016-10-25T07:52:01+0000 timeout=-1s name=x1e action=shutdown
t=2016-10-25T09:52:14+0200 lvl=info msg="Starting container" name=x1e action=start created=2016-10-25T07:51:51+0000 ephemeral=true used=2016-10-25T07:52:01+0000 stateful=false
t=2016-10-25T09:52:19+0200 lvl=eror msg="Failed starting container" created=2016-10-25T07:51:51+0000 ephemeral=true used=2016-10-25T07:52:01+0000 stateful=false name=x1e action=start
```

**Comment by brauner** [comment] 2016-10-25 08:28
Can reproduce this here with current master. My first intuition is though that you should be able to reboot ephemeral container without them being destroyed. They should only be deleted on "proper" shutdown.

**Comment by brauner** [comment] 2016-10-25 11:17
I'm working on a fix for this.

**Comment by brauner** [comment] 2016-10-25 14:12
So this is sort of tricky since `lxc restart` actually fully stops the container and then starts it again so you would end up destroying ephemeral containers.

**Comment by stgraber** [comment] 2016-10-25 19:25
Not sure if this fixes it all, but it does fix the "lxc restart destroys ephemeral" bit anyway which should mean that Delete() is only called in the right cases, which hopefully fixes the rest of the problem.

**Closed** 2016-10-25 19:45 UTC
