### ISSUE TITLE
Failed to set up mount namespacing

### ISSUE THREAD

**Issue by florian-bellencontre** [lxc/lxd#7065] opened 2020-03-20 15:59 UTC
# Required information

 * Distribution: Ubuntu 18.04.4 LTS
*  LXD with snapd
 * The output of "lxc info" or if that fails:
```
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
- firewall_driver
- projects_limits
- container_syscall_intercept_hugetlbfs
- limits_hugepages
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate:
REMOVE
  driver: lxc
  driver_version: 3.2.1
  firewall: xtables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "false"
    seccomp_listener: "false"
    seccomp_listener_continue: "false"
    shiftfs: "false"
    uevent_injection: "false"
    unpriv_fscaps: "true"
  kernel_version: 4.15.0-38-generic
  lxc_features:
    cgroup2: "false"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    seccomp_notify: "true"
  project: default
  server: lxd
  server_clustered: false
  server_name: erebus
  server_pid: 157990
  server_version: "3.22"
  storage: zfs
  storage_version: 0.7.5-1ubuntu16.4
```

# Issue description

After a restart of my container I have an error which is related to systemd:
```
Mar 20 16:43:19 beta-wordpress systemd[1]: Starting MariaDB 10.3.22 database server...
Mar 20 16:43:20 beta-wordpress systemd[350]: mariadb.service: Failed to set up mount namespacing: Permission denied
Mar 20 16:43:20 beta-wordpress systemd[350]: mariadb.service: Failed at step NAMESPACE spawning /usr/sbin/mysqld: Permission denied
Mar 20 16:43:20 beta-wordpress systemd[1]: mariadb.service: Main process exited, code=exited, status=226/NAMESPACE
Mar 20 16:43:20 beta-wordpress systemd[1]: mariadb.service: Failed with result 'exit-code'.
Mar 20 16:43:20 beta-wordpress systemd[1]: Failed to start MariaDB 10.3.22 database server.
```

I got the same error on the systemd-networkd service.

I have not changed anything in my container configuration. If I start the service manually it works perfectly. 

I had the case on another container where the "redis" service was not working with the same error.

**Comment by stgraber** [comment] 2020-03-20 16:09
What's the distro in the container?
Can you also show your `dmesg` output around the time this happens?

**Comment by florian-bellencontre** [comment] 2020-03-20 16:12
Nothing into dmesg but in syslog I see this:
```
Mar 20 17:07:45 host kernel: [43286694.926594] audit: type=1400 audit(1584720465.171:19664): apparmor="DENIED" operation="mount" info="failed flags match" error=-13 profile="lxd-beta-wordpress_</var/snap/lxd/common/lxd>" name="/run/systemd/unit-root/bin/" pid=92914 comm="(mysqld)" flags="ro, remount, noatime, bind"
Mar 20 17:09:04 host kernel: [43286774.575423] audit: type=1400 audit(1584720544.818:19666): apparmor="DENIED" operation="mount" info="failed flags match" error=-13 profile="lxd-beta-wordpress_</var/snap/lxd/common/lxd>" name="/run/systemd/unit-root/bin/" pid=96632 comm="(ionclean)" flags="ro, remount, noatime, bind"
```

* The 2 containers are a Debian 10

**Comment by stgraber** [comment] 2020-03-20 16:15
Can you see if setting `security.nesting=true` on the container and restarting it fixes that?

**Comment by florian-bellencontre** [comment] 2020-03-20 16:17
Yes after passing the parameter all services are working again.

**Comment by stgraber** [comment] 2020-03-20 16:18
I just checked LXD's source code and we do set the right options for the filter in this case.
The problem is likely one of the very many apparmor mount enforcement bugs that we have opened over the years...

If `security.nesting=true` works for you, I'd suggest you do that for the time being. It comes with no additional security concerns so long as the container isn't also privileged.

I'm closing the issue as unfortunately the profile we generate is correct and does allow the action you show as denied above, the issue is a parser/kernel bug in apparmor.

**Closed by stgraber** 2020-03-20 16:18 UTC
Labels: Incomplete

**Comment by florian-bellencontre** [comment] 2020-03-20 16:28
Thank you for your quick help!
Where can I see in the documentation what the parameter "security.nesting" does? I saw on this link that it was used to launch Docker but what does it do exactly ?
https://lxd.readthedocs.io/en/latest/

**Comment by stgraber** [comment] 2020-03-20 17:22
Yeah, it does two main things:
 - Propagate a /proc and /sys mount into a hidden location to bypass a kernel limitation
 - Allow arbitrary bind-mounts, so that a container filesystem can be setup.

The second part is what's making systemd work in your case.
