### ISSUE TITLE
Docker can't seem to bootstrap an lxd container :(

### ISSUE THREAD

**Issue by socketwiz** [lxc/lxd#2965] opened 2017-02-27 12:16 UTC
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04.2 LTS
 * The output of "lxc info" or if that fails:
```
config:
  core.https_address: '[::]'
apiextensions:
- id_map
apistatus: stable
apiversion: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 10.0.1.10:8443
  - 10.0.8.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFTDCCAzSgAwIBAgIQX/Z+Fo2jEr+0qozyt1mg8TANBgkqhkiG9w0BAQsFADA4
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRgwFgYDVQQDDA9yb290QGt1
    YmVybmV0ZXMwHhcNMTcwMjI3MDAwNTI1WhcNMjcwMjI1MDAwNTI1WjA4MRwwGgYD
    VQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRgwFgYDVQQDDA9yb290QGt1YmVybmV0
    ZXMwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC7wVlLDeeqEPLphNWe
    vdkydp8P9nC2+TmSxYhnuQ4ZF4+SdtzoH4drvf2wR9pevMtgAZGYpY0iwQf/CGvR
    h+1rY4WNxAhiFRME0b9NaulzsF6c6beljt7VlGNEdNtMJGR/2j3xxgGc5CGjkpBa
    wjHy4oZ4C+yvYgEy8QJb5g3KFLfosJWaqsjm/nA0vLDQO6pVdQPvp0URf01+mkX7
    C64bV2XHHPLE2ROhQFPR3ljZUUSULivyW1Ykq+40jCu5UmmPHZY+gcV2bxJ+oWHj
    FO/0CUhFUnRcNQD4wxhCp9G/5Tin9kiznigLIyfiTvXYebGUI4UH2G+MVzGQ+pND
    smwZOJV9TlWLXjqipZ2GzYJ209BnlOj6C7zwFqvmFyXUKukGYJTQB9nIAdEhCGgt
    hIjsuC87Uqf2IphXfrjse1ePQAq35fE00rhCjAS6RfbdouYT1TOvpHyw+iK8ndF1
    Fa5zifCGqLGMXfl7u7s8av/EQEoKLyMhJMGnYqClBo6zTLZEGNL+HO9ILnUW+gJ8
    OsGjQhLpyrh7Jbflktj9v8ZMSjK9NcKJcv2rI4WluF5M57hOYa5IfvFp+Sogd/xO
    hSRe7B7o3QekrUvkiDl5KGIWBXBX1XnnYFfT51e1ZQ0LxuIDx8LvN8dpI0Ag0ATF
    N4G3dwxCqRWLdrA37Gh4cqXTbQIDAQABo1IwUDAOBgNVHQ8BAf8EBAMCBaAwEwYD
    VR0lBAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADAbBgNVHREEFDASggprdWJl
    cm5ldGVzhwQKAAEKMA0GCSqGSIb3DQEBCwUAA4ICAQCw8E5ZamnxpduCiYgkstm6
    xmBUk5oJUHHeFNc47iG4yda4GhSRLoZxoqk1jON10+TTNOz6XK0s7c7tnGCQPQE6
    zWho3rprgIZ3XXU0vPa4FD0Tyc1+rGpDI+4wrG6MZag7yHB/SySFOHQCC734J3iK
    9/dPlhzzF1/nFujKyQ2cxhi7wM30gaJJk9EoywcrAkYKn4wg+hs9PEc/LnjnTEyd
    fUeFj0EsKXo6FN9i8augxLBZAP+jNpby3Lq+47IxFgKCGj1kVYJEhFa+0A48jmRK
    iwnPmfkcAsn0/ZrXaoOQ/QiTUqhSJ6EkL7oXCQylrg5l2SUfQlXqdHtonOCNx/wi
    9KLw+oK2h/l8VIJNW5H1gha+BGy4EkXwH6NtQ1/mgN+HbUvPAFBN7zokTGqGjHpu
    onXf9Vve0a1igZWJIQS/OGjVbQ8krJKt9UfSzCsRKiXZgYW861g2xcbDuMYr8dtm
    p1allkIVR1XKzxQ43OlHjvrp7FLsO7dlql3n9o3eDF7LuLQxKGZR1avvyGqTZdP2
    +F3ijAYvcjvFC7/Z1G7xPkLphwBK0qRbXCrEnTHu3pj/6bJMzgoQKuyIc9PNsE6I
    KWB3kH7ukHPLvj3L9YwOnhlloXbnIkNmMeWwZh2G+KFJX7wxe50eW099AZnms4l+
    PGzXU8+HCGDDbDjJjP36og==
    -----END CERTIFICATE-----
  certificatefingerprint: 21d52c7926e56685fa3c0e31ac0a73ca39092731092e4a41f9116a9fca889fc3
  driver: lxc
  driverversion: 2.0.7
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-64-generic
  server: lxd
  serverpid: 2004
  serverversion: 2.0.9
  storage: dir
  storageversion: ""
```
# Issue description

Docker will not run inside a container when bootstrapped with docker-machine.

# Steps to reproduce

 1. `$ sudo lxd init`
 2. `$ lxc launch ubuntu: first-machine`
 3. `$ docker-machine create --driver generic --generic-ip-address=<ip address of first-machine> --generic-ssh-key ~/.ssh/id_rsa --generic-ssh-user=root first-machine`

# Information to attach

--output from docker-machine
```
Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "10.0.8.84:2376": read tcp 10.0.1.114:43634
->10.0.8.84:2376: read: connection reset by peer
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which might stop running containers.
```

--output from dockerd inside container when run manually
```
INFO[0000] libcontainerd: new containerd process, pid: 4838 
WARN[0000] containerd: low RLIMIT_NOFILE changing to max  current=1024 max=65536
Error starting daemon: error initializing graphdriver: driver not supported
```

**Comment by stgraber** [comment] 2017-02-27 17:22
So I don't know docker-machine, but it sounds like it's a tool which will use SSH to enter the container and install Docker inside it. If so, there are a few problems with your setup:
 - You're not using the "docker" profile for your container. You'd instead want: "lxc launch ubuntu: first-machine -p default -p docker"
 - It's unclear what version of Docker this would install. If it's installing an upstream build of Docker, then it's very unlikely to work. You instead should use the version of Docker coming from Ubuntu (docker.io package) which includes the needed bits to run inside a LXD container.

**Comment by socketwiz** [comment] 2017-02-27 23:42
> So I don't know docker-machine, but it sounds like it's a tool which will use SSH to enter the container and install Docker inside it.

That is correct.  It is a utility that is a part of the Docker suite that allows you to manage various different "docker machines" or VM's that have docker installed.  I believe it works the way you've described.

https://docs.docker.com/machine/

> You'd instead want: "lxc launch ubuntu: first-machine -p default -p docker"

Hmm, I'm not sure what that does but I'll certainly look into it.  That might be a work-around for now.  I think I'll lose the functionality of docker-machine but it might be tolerable, at least for now.  The cool thing about docker-machine that I really like is I can just do `eval $(docker-machine env <docker machine name>)` and it sets the environment such that all docker commands now run in the context of that machine.  Its very, very handy because you're still on your machine and not ssh'd into the docker VM but the docker commands are being run against that VM.

> It's unclear what version of Docker this would install. If it's installing an upstream build of Docker, then it's very unlikely to work.

I'm almost positive it would be some upstream version, thus the reason I made the ticket.

>  You instead should use the version of Docker coming from Ubuntu (docker.io package) which includes the needed bits to run inside a LXD container.

That would most certainly work, but again the problem with that is that you lose the convenience that docker-machine provides :(

**Comment by stgraber** [comment] 2017-02-28 00:37
Ok, so sounds like this was caused by a mix of a Docker version which doesn't work inside LXD and the LXD container itself missing some configuration.

I'm closing this issue since there's nothing for us to fix at the LXD level.

At the Docker level, we do regularly contribute patches and our goal is absolutely to allow for unpatched upstream docker to work inside LXD. In fact, that was true with the early 1.13 builds but regressed since...

**Closed by stgraber** 2017-02-28 00:37 UTC
