### ISSUE TITLE
"database is locked" after encountering out of disk space condition

### ISSUE THREAD

**Issue by dshcherb** [lxc/lxd#6226] opened 2019-09-21 07:27 UTC
# Required information

 * Distribution: ubuntu
 * Distribution version: 19.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.3.0-050300rc7-generic
   * LXC version: 3.17
   * LXD version: 3.17
   * Storage backend in use: btrfs

# Issue description

- System ran out of disk space (apparently building chrome requires > 50G);
- snapcraft --use-lxd was used so this was triggered by a container;
- lxd stopped responding to client commands ("database is locked shown in the log")
- freed some disk space;
- some lxc commands started to work but not all of them;
- restarted LXD via systemctl - LXD fails while trying to use the DB (it is still locked).

It would be good if there was some method to unlock it.

# Relevant Information

A portion of `journalctl -u snap.lxd.daemon.service`:
```
сен 21 10:10:23 blade lxd.daemon[2318]: t=2019-09-21T10:10:23+0300 lvl=dbug msg="Database error: bindings.Error{Code:5, Message:\"database is locked\"}"
сен 21 10:10:23 blade lxd.daemon[2318]: t=2019-09-21T10:10:23+0300 lvl=dbug msg="Retry failed db interaction (database is locked)"
сен 21 10:10:23 blade lxd.daemon[2318]: t=2019-09-21T10:10:23+0300 lvl=dbug msg=Handling ip=@ method=GET url="/1.0/containers/snapcraft-chromium/files?path=%2Ftmp%2Fs
сен 21 10:10:23 blade lxd.daemon[2318]: t=2019-09-21T10:10:23+0300 lvl=dbug msg="\n\t{\n\t\t\"error\": \"not found\",\n\t\t\"error_code\": 404,\n\t\t\"type\": \"error
сен 21 10:10:23 blade lxd.daemon[2318]: t=2019-09-21T10:10:23+0300 lvl=dbug msg="Database error: bindings.Error{Code:5, Message:\"database is locked\"}"
сен 21 10:10:23 blade lxd.daemon[2318]: t=2019-09-21T10:10:23+0300 lvl=dbug msg=Handling ip=@ method=GET url=/1.0/containers/snapcraft-chromium user=
сен 21 10:10:23 blade lxd.daemon[2318]: t=2019-09-21T10:10:23+0300 lvl=dbug msg="Retry failed db interaction (database is locked)"


# systemctl restart snap.lxd.daemon.service goes below

сен 21 10:14:58 blade lxd.daemon[2318]: t=2019-09-21T10:14:58+0300 lvl=dbug msg="\n\t{\n\t\t\"action\": \"stop\",\n\t\t\"timeout\": -1,\n\t\t\"force\": false,\n\t\t\"
сен 21 10:14:58 blade lxd.daemon[2318]: t=2019-09-21T10:14:58+0300 lvl=dbug msg="Database error: bindings.Error{Code:5, Message:\"database is locked\"}"
сен 21 10:14:58 blade lxd.daemon[2318]: t=2019-09-21T10:14:58+0300 lvl=dbug msg="Retry failed db interaction (database is locked)"
сен 21 10:14:58 blade lxd.daemon[2318]: t=2019-09-21T10:14:58+0300 lvl=dbug msg="Database error: bindings.Error{Code:5, Message:\"database is locked\"}"
сен 21 10:14:58 blade lxd.daemon[2318]: t=2019-09-21T10:14:58+0300 lvl=dbug msg="Retry failed db interaction (database is locked)"
сен 21 10:14:58 blade lxd.daemon[2318]: t=2019-09-21T10:14:58+0300 lvl=dbug msg="Database error: bindings.Error{Code:5, Message:\"database is locked\"}"
сен 21 10:14:58 blade lxd.daemon[2318]: t=2019-09-21T10:14:58+0300 lvl=dbug msg="Retry failed db interaction (database is locked)"
сен 21 10:14:59 blade lxd.daemon[2318]: t=2019-09-21T10:14:59+0300 lvl=dbug msg="Database error: bindings.Error{Code:5, Message:\"database is locked\"}"
сен 21 10:14:59 blade lxd.daemon[2318]: t=2019-09-21T10:14:59+0300 lvl=dbug msg="Retry failed db interaction (database is locked)"
сен 21 10:14:59 blade lxd.daemon[2318]: t=2019-09-21T10:14:59+0300 lvl=dbug msg="Database error: bindings.Error{Code:5, Message:\"database is locked\"}"
сен 21 10:14:59 blade lxd.daemon[2318]: t=2019-09-21T10:14:59+0300 lvl=dbug msg="Retry failed db interaction (database is locked)"
сен 21 10:14:59 blade lxd.daemon[2318]: t=2019-09-21T10:14:59+0300 lvl=dbug msg="\n\t{\n\t\t\"error\": \"failed to add operation d63a7dd9-a67e-43bc-aea5-46e273443a89 
сен 21 10:15:11 blade systemd[1]: Stopping Service for snap application lxd.daemon...
сен 21 10:15:11 blade lxd.daemon[4367]: => Stop reason is: host shutdown
сен 21 10:15:11 blade lxd.daemon[4367]: => Stopping LXD (with container shutdown)
сен 21 10:15:12 blade lxd.daemon[2318]: t=2019-09-21T10:15:12+0300 lvl=dbug msg=Handling ip=@ method=PUT url=/internal/shutdown user=
сен 21 10:15:12 blade lxd.daemon[2318]: t=2019-09-21T10:15:12+0300 lvl=dbug msg="Disconnected event listener: 14a81db0-da0c-4b43-9c5f-3fd094ccd99f"
сен 21 10:15:12 blade lxd.daemon[2318]: t=2019-09-21T10:15:12+0300 lvl=dbug msg="\n\t{\n\t\t\"type\": \"sync\",\n\t\t\"status\": \"Success\",\n\t\t\"status_code\": 20
сен 21 10:15:12 blade lxd.daemon[2318]: t=2019-09-21T10:15:12+0300 lvl=info msg="Asked to shutdown by API, shutting down containers"
сен 21 10:15:12 blade lxd.daemon[2318]: t=2019-09-21T10:15:12+0300 lvl=dbug msg="Cancel ongoing or future gRPC connection attempts"
сен 21 10:15:12 blade lxd.daemon[2318]: t=2019-09-21T10:15:12+0300 lvl=dbug msg=Handling ip=@ method=GET url=/1.0/events user=
сен 21 10:15:12 blade lxd.daemon[2318]: t=2019-09-21T10:15:12+0300 lvl=dbug msg="New event listener: fd45a367-a970-46d7-a0c8-e22a5654edc7"
сен 21 10:15:12 blade lxd.daemon[2318]: t=2019-09-21T10:15:12+0300 lvl=dbug msg="Database error: bindings.Error{Code:5, Message:\"database is locked\"}"
сен 21 10:15:12 blade lxd.daemon[2318]: t=2019-09-21T10:15:12+0300 lvl=dbug msg="Retry failed db interaction (database is locked)"
сен 21 10:15:12 blade lxd.daemon[2318]: t=2019-09-21T10:15:12+0300 lvl=dbug msg="Database error: bindings.Error{Code:5, Message:\"database is locked\"}"
сен 21 10:15:12 blade lxd.daemon[2318]: t=2019-09-21T10:15:12+0300 lvl=dbug msg="Retry failed db interaction (database is locked)"
сен 21 10:15:12 blade lxd.daemon[2318]: t=2019-09-21T10:15:12+0300 lvl=dbug msg="Database error: bindings.Error{Code:5, Message:\"database is locked\"}"
сен 21 10:15:12 blade lxd.daemon[2318]: t=2019-09-21T10:15:12+0300 lvl=dbug msg="Retry failed db interaction (database is locked)"
сен 21 10:15:12 blade lxd.daemon[2318]: t=2019-09-21T10:15:12+0300 lvl=dbug msg="Database error: bindings.Error{Code:5, Message:\"database is locked\"}"
сен 21 10:15:12 blade lxd.daemon[2318]: t=2019-09-21T10:15:12+0300 lvl=dbug msg="Retry failed db interaction (database is locked)"
сен 21 10:15:13 blade lxd.daemon[2318]: t=2019-09-21T10:15:13+0300 lvl=dbug msg="Database error: bindings.Error{Code:5, Message:\"database is locked\"}"
сен 21 10:15:13 blade lxd.daemon[2318]: t=2019-09-21T10:15:13+0300 lvl=dbug msg="Retry failed db interaction (database is locked)"
сен 21 10:15:13 blade lxd.daemon[2318]: t=2019-09-21T10:15:13+0300 lvl=info msg="Starting shutdown sequence"
сен 21 10:15:13 blade lxd.daemon[2318]: t=2019-09-21T10:15:13+0300 lvl=info msg="Stopping REST API handler:"
сен 21 10:15:13 blade lxd.daemon[2318]: t=2019-09-21T10:15:13+0300 lvl=info msg=" - closing socket" socket=[::]:8443
сен 21 10:15:13 blade lxd.daemon[2318]: t=2019-09-21T10:15:13+0300 lvl=info msg=" - closing socket" socket=/var/snap/lxd/common/lxd/unix.socket

# LXD is unable to create an API socket because the DB is locked

 lxc info --debug
DBUG[09-21|10:23:57] Connecting to a local LXD over a Unix socket 
DBUG[09-21|10:23:57] Sending request to LXD                   method=GET url=http://unix.socket/1.0 etag=
Error: Get http://unix.socket/1.0: dial unix /var/snap/lxd/common/lxd/unix.socket: connect: connection refused

```

**Comment by dshcherb** [comment] 2019-09-21 12:04
I did the following to unblock myself:

```
rm -f /var/snap/lxd/common/lxd/database/global/18*
rm -f /var/snap/lxd/common/lxd/database/global/19*
rm -f /var/snap/lxd/common/lxd/database/global/20*
rm -f /var/snap/lxd/common/lxd/database/global/snapshot-41-*
```

But I still have the backed up database files which have the broken state.

**Comment by stgraber** [comment] 2019-09-22 19:15
Could you e-mail a tarball of the database to stgraber at ubuntu dot com and I'll forward it to @freeekanayaka to look at any potential fix/improvements to do in dqlite upstream for such cases?

Closing as the issue is likely in dqlite rather than LXD and we'll have @freeekanayaka take a look at it once we get access to the DB.

Thanks!

**Closed by stgraber** 2019-09-22 19:15 UTC

**Comment by dshcherb** [comment] 2019-09-22 19:43
@stgraber 

Done, thanks!

**Comment by freeekanayaka** [comment] 2019-09-24 09:54
I can reproduce the issue with the database dump that @dshcherb sent us. Like in another cases we have seen, raft refuses to start because it finds that the last segment has some trailing zeros that should have been truncated instead. Since the logic to finalize open segments first truncates the file then renames it (with an fsync in between) that situation should never happen.

I'll try to run the daemon on a loopback fs with limited space and try to reproduce the conditions under this issue occurred.
