### ISSUE TITLE
Iteration and Container Selection

### ISSUE THREAD

**Issue by srkunze** [lxc/lxd#8310] opened 2021-01-07 09:35 UTC
### Hi everyone,

quite recently, I found myself having a handful of containers and want to keep them up to date. For this purpose, I felt to do something like

```
lxc shell myprefix-* -- apt update
lxc shell myprefix-* -- apt upgrade
```

As far as I read the docs, this is currently not possible.

### 2 Questions
1) What would be the simplest way of doing it now without knowing the complete list of containers?
2) Do you think it's worth adding container selection (based on name globbing, name regexes, container profile, container profile attributes etc.)?

**Comment by stgraber** [comment] 2021-01-07 19:29
Duplicate of https://github.com/lxc/lxd/issues/1045

For now, you could do `for ctn in $(lxc list -cn -f csv myprefix); do lxc exec ${ctn} -- apt update; done`

**Closed by stgraber** 2021-01-07 19:29 UTC
