### ISSUE TITLE
lxc OpenGL performance

### ISSUE THREAD

**Issue by mismacku** [lxc/lxd#3826] opened 2017-09-20 16:44 UTC
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04.3
 * The output of "lxc info":
```
config:
  core.https_address: 10.137.124.205:8443
  core.trust_password: true
  images.auto_update_interval: "0"
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 10.137.124.205:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFSjCCAzKgAwIBAgIRALOV81CO5ptrLTnECdbbzPEwDQYJKoZIhvcNAQELBQAw
    NTEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEVMBMGA1UEAwwMcm9vdEBo
    ZXgtYy0xMB4XDTE3MDgxMTIxMDQ0NFoXDTI3MDgwOTIxMDQ0NFowNTEcMBoGA1UE
    ChMTbGludXhjb250YWluZXJzLm9yZzEVMBMGA1UEAwwMcm9vdEBoZXgtYy0xMIIC
    IjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAtQi+AMOoSR+VXy5/Nyd4EmZa
    zir1BVCkyIiHGm2HQv3rf1Jlnc1EaUryFbTNJ7/UmvqSDM7Ki29aHC85q09XHm80
    rdpraD6V/pLIH+iZc7jf1DgEbkPL0K/ae618QU9ZiIx4Woq/2hz2ZcE68jRNUNME
    oQGm39OhLGqYCp+/JxX+DzHpjjd+0X8ltDTCv098FgazY/DGdL2uq6+7mHEdEWAW
    9Mg+m2p1exHuK4GNgm775AQIbmSLjq6EFeV/Vh5Lp665Gf5YF9Pqhy+IW72LSRMI
    q1u79KBrXcC7p00kewFmnobxfKEcLlPU+eYNZwDAejePzjWag6e3z0cxCg73q388
    MEqXVL35RydJR2kiuencAckpa0wvnY7VNCdlYGkrg8s+QnQ9tujuvT8xcYt41wVl
    Dj8FTvkJKesUGlvaLeZYJoUeWtzgFDcFBCiDR3YpkyCmR4HzMmy/CamuRQh9ctN8
    zYG7m13cX4G2GXuTl1kI+WhZ6QhgUpNmEGaLFM0btwECq/fcaVdb0Q3YS5fmepak
    PzA5N1KFKxMvhrT7XG+hofUT1M/x2hBvFN1Mx89xE781uaRRc4gsjkETuy/K6EqC
    DLQoZAw7BhgjNDpNqxB1V45mFgQHqsd89lLeGYJ8Zrytnvi92ZV7gU5d0jOoRDxE
    /vcNUf6/rT4h+PnURu0CAwEAAaNVMFMwDgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQM
    MAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwHgYDVR0RBBcwFYIHaGV4LWMtMYcE
    Col8zYcErBEAATANBgkqhkiG9w0BAQsFAAOCAgEArQRaGYAcsOm5NbDp4moE3etn
    ajATQhWTS0YJMAVOwFcjWJJWMPEjS4V0JEa7W0ASLIRpFycEwiAI7v9ATn8le9TW
    JgkixeHLcZqTIGq5NpNaHT8b2ite43LInc0fCNsRKQv1IKJbBgk75Zem/qcpDgyw
    maQi+jsu7L+KyZb4zf/TsQsU//py4asD/vvMUa0uFaTyeSDKMIF1pKaBIS7VW1Dy
    3BznWbL0C0DU+BzwYu7PKd4jt2pYJmP8y4Q4fhxpEzPVUHN2M7N+MNHvRflN/KFk
    AJrSqfPtOkZzHNDAk01MoDuoYMfCqFnWNFa0eJjez5+d981BZQWzXKKb7hnxSRW/
    VQe+zUy3OpSrz7HeuJf67CED/HXewNps15L8/Mflq8aFW+Dmvbov/SuAut/OJ5ji
    e8hycaiNrGAumznW9vcfGsgVJoUBq8J5ic+Si5U+/ksUVFXCdMkL0pMonM6H1sr6
    BkX2EFeZIS4dC1k2pXg7rL9vvaZaEiG1EUvFWUn3F8m1CoB94r5/yEDJtuYPOWXj
    EseI2Lf7uKrfrRIJJ6ATBY2Fnga5jH6LcrkXEUIWQhFTAguaz5qsCCI9zvYNbzDU
    CViYHE/b3aIJTI5hTgMb5WRthOxnGY89bx2J+uTXqQguBnY5AhKcnaCSNTRVrDVf
    kG9s0yqkK2xenuRQpW4=
    -----END CERTIFICATE-----
  certificate_fingerprint: 896be80f481b22a4c73daaec6e6f2555dd8b9d4d2636706e7497ce3508211824
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.11.0-14-generic
  server: lxd
  server_pid: 3955
  server_version: "2.17"
  storage: dir
  storage_version: "1"
```
Container config:
```
architecture: x86_64
config:
  image.architecture: x86_64
  image.description: Ubuntu 16.04 gl test
  image.os: ubuntu
  image.release: xenial
  raw.idmap: both 1000 1000
  security.privileged: "true"
  volatile.base_image: e48aea6a5adc6148e8143e8e6c5ebdaf9f322e18c8e3a530c2024f57f3a18274
  volatile.eth0.hwaddr: 00:16:3e:29:c4:41
  volatile.idmap.base: "0"
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
devices: {}
ephemeral: false
profiles:
- default
stateful: false
```
Profile:
```
config:
  environment.http_proxy: ""
  raw.lxc: |-
    lxc.aa_profile = unconfined
    lxc.hook.pre-start = /var/lib/lxd/lxc.hook.pre-start/pulseaudio.sh
  user.network_mode: ""
description: Default LXD profile
devices:
  data1:
    path: /data1
    source: /data1
    type: disk
  eth0:
    name: eth0
    nictype: macvlan
    parent: em2
    type: nic
  gpu:
    type: gpu
  root:
    path: /
    pool: default
    type: disk
  tmp-X11:
    path: /tmp/.X11-unix
    source: /tmp/.X11-unix
    type: disk
name: default
```
# Issue description
I'm running lxc containers on machines with (3) Nvidia K5000's driving (9) 1080p displays and using glmark2 for testing. X is running at a resolution of 5916x3448. It looks as though the lxc (and docker) containers perform at roughly half that of the host. I realize this isn't necessarily an lxc / lxd issue, but I'm hoping that the cause of this problem will be obvious to someone.

# glmark2 benchmark results
## host at 800x600 (on screen framebuffer)
`$ glmark2 -s 800x600`
```
=======================================================
    glmark2 2017.07
=======================================================
    OpenGL Information
    GL_VENDOR:     NVIDIA Corporation
    GL_RENDERER:   Quadro K5000/PCIe/SSE2
    GL_VERSION:    4.5.0 NVIDIA 384.66
=======================================================
[build] use-vbo=false: FPS: 2816 FrameTime: 0.355 ms
[build] use-vbo=true: FPS: 6256 FrameTime: 0.160 ms
[texture] texture-filter=nearest: FPS: 6200 FrameTime: 0.161 ms
[texture] texture-filter=linear: FPS: 6182 FrameTime: 0.162 ms
[texture] texture-filter=mipmap: FPS: 6150 FrameTime: 0.163 ms
[shading] shading=gouraud: FPS: 4649 FrameTime: 0.215 ms
[shading] shading=blinn-phong-inf: FPS: 6211 FrameTime: 0.161 ms
[shading] shading=phong: FPS: 6250 FrameTime: 0.160 ms
[shading] shading=cel: FPS: 6043 FrameTime: 0.165 ms
[bump] bump-render=high-poly: FPS: 5673 FrameTime: 0.176 ms
[bump] bump-render=normals: FPS: 6190 FrameTime: 0.162 ms
[bump] bump-render=height: FPS: 6178 FrameTime: 0.162 ms
[effect2d] kernel=0,1,0;1,-4,1;0,1,0;: FPS: 6343 FrameTime: 0.158 ms
[effect2d] kernel=1,1,1,1,1;1,1,1,1,1;1,1,1,1,1;: FPS: 5126 FrameTime: 0.195 ms
[pulsar] light=false:quads=5:texture=false: FPS: 5992 FrameTime: 0.167 ms
[desktop] blur-radius=5:effect=blur:passes=1:separable=true:windows=4: FPS: 2505 FrameTime: 0.399 ms
[desktop] effect=shadow:windows=4: FPS: 3147 FrameTime: 0.318 ms
[buffer] columns=200:interleave=false:update-dispersion=0.9:update-fraction=0.5:update-method=map: FPS: 727 FrameTime: 1.376 ms
[buffer] columns=200:interleave=false:update-dispersion=0.9:update-fraction=0.5:update-method=subdata: FPS: 917 FrameTime: 1.091 ms
[buffer] columns=200:interleave=true:update-dispersion=0.9:update-fraction=0.5:update-method=map: FPS: 755 FrameTime: 1.325 ms
[ideas] speed=duration: FPS: 4048 FrameTime: 0.247 ms
[jellyfish] <default>: FPS: 5381 FrameTime: 0.186 ms
[terrain] <default>: FPS: 650 FrameTime: 1.538 ms
[shadow] <default>: FPS: 4427 FrameTime: 0.226 ms
[refract] <default>: FPS: 1920 FrameTime: 0.521 ms
[conditionals] fragment-steps=0:vertex-steps=0: FPS: 6330 FrameTime: 0.158 ms
[conditionals] fragment-steps=5:vertex-steps=0: FPS: 6014 FrameTime: 0.166 ms
[conditionals] fragment-steps=0:vertex-steps=5: FPS: 6244 FrameTime: 0.160 ms
[function] fragment-complexity=low:fragment-steps=5: FPS: 5801 FrameTime: 0.172 ms
[function] fragment-complexity=medium:fragment-steps=5: FPS: 6188 FrameTime: 0.162 ms
[loop] fragment-loop=false:fragment-steps=5:vertex-steps=5: FPS: 6272 FrameTime: 0.159 ms
[loop] fragment-steps=5:fragment-uniform=false:vertex-steps=5: FPS: 6206 FrameTime: 0.161 ms
[loop] fragment-steps=5:fragment-uniform=true:vertex-steps=5: FPS: 5984 FrameTime: 0.167 ms
=======================================================
                                  glmark2 Score: 4841
=======================================================
```
## host at 800x600 (off-screen framebuffer)
`$ glmark2 -s 800x600 --off-screen`
```
=======================================================
    glmark2 2017.07
=======================================================
    OpenGL Information
    GL_VENDOR:     NVIDIA Corporation
    GL_RENDERER:   Quadro K5000/PCIe/SSE2
    GL_VERSION:    4.5.0 NVIDIA 384.66
=======================================================
[build] use-vbo=false: FPS: 3323 FrameTime: 0.301 ms
[build] use-vbo=true: FPS: 17045 FrameTime: 0.059 ms
[texture] texture-filter=nearest: FPS: 15618 FrameTime: 0.064 ms
[texture] texture-filter=linear: FPS: 15625 FrameTime: 0.064 ms
[texture] texture-filter=mipmap: FPS: 16592 FrameTime: 0.060 ms
[shading] shading=gouraud: FPS: 15084 FrameTime: 0.066 ms
[shading] shading=blinn-phong-inf: FPS: 15061 FrameTime: 0.066 ms
[shading] shading=phong: FPS: 14417 FrameTime: 0.069 ms
[shading] shading=cel: FPS: 13929 FrameTime: 0.072 ms
[bump] bump-render=high-poly: FPS: 8885 FrameTime: 0.113 ms
[bump] bump-render=normals: FPS: 18018 FrameTime: 0.056 ms
[bump] bump-render=height: FPS: 17506 FrameTime: 0.057 ms
[effect2d] kernel=0,1,0;1,-4,1;0,1,0;: FPS: 12869 FrameTime: 0.078 ms
[effect2d] kernel=1,1,1,1,1;1,1,1,1,1;1,1,1,1,1;: FPS: 7891 FrameTime: 0.127 ms
[pulsar] light=false:quads=5:texture=false: FPS: 14185 FrameTime: 0.070 ms
[desktop] blur-radius=5:effect=blur:passes=1:separable=true:windows=4: FPS: 1930 FrameTime: 0.518 ms
[desktop] effect=shadow:windows=4: FPS: 3441 FrameTime: 0.291 ms
[buffer] columns=200:interleave=false:update-dispersion=0.9:update-fraction=0.5:update-method=map: FPS: 930 FrameTime: 1.075 ms
[buffer] columns=200:interleave=false:update-dispersion=0.9:update-fraction=0.5:update-method=subdata: FPS: 900 FrameTime: 1.111 ms
[buffer] columns=200:interleave=true:update-dispersion=0.9:update-fraction=0.5:update-method=map: FPS: 1021 FrameTime: 0.979 ms
[ideas] speed=duration: FPS: 6008 FrameTime: 0.166 ms
[jellyfish] <default>: FPS: 6935 FrameTime: 0.144 ms
[terrain] <default>: FPS: 496 FrameTime: 2.016 ms
[shadow] <default>: FPS: 6885 FrameTime: 0.145 ms
[refract] <default>: FPS: 2181 FrameTime: 0.459 ms
[conditionals] fragment-steps=0:vertex-steps=0: FPS: 15028 FrameTime: 0.067 ms
[conditionals] fragment-steps=5:vertex-steps=0: FPS: 14357 FrameTime: 0.070 ms
[conditionals] fragment-steps=0:vertex-steps=5: FPS: 14759 FrameTime: 0.068 ms
[function] fragment-complexity=low:fragment-steps=5: FPS: 15004 FrameTime: 0.067 ms
[function] fragment-complexity=medium:fragment-steps=5: FPS: 14433 FrameTime: 0.069 ms
[loop] fragment-loop=false:fragment-steps=5:vertex-steps=5: FPS: 14687 FrameTime: 0.068 ms
[loop] fragment-steps=5:fragment-uniform=false:vertex-steps=5: FPS: 14326 FrameTime: 0.070 ms
[loop] fragment-steps=5:fragment-uniform=true:vertex-steps=5: FPS: 14373 FrameTime: 0.070 ms
=======================================================
                                  glmark2 Score: 10719
=======================================================
```
## lxc container at 800x600 (on-screen framebuffer)
`$ glmark2 -s 800x600`
```
=======================================================
    glmark2 2017.07
=======================================================
    OpenGL Information
    GL_VENDOR:     NVIDIA Corporation
    GL_RENDERER:   Quadro K5000/PCIe/SSE2
    GL_VERSION:    4.5.0 NVIDIA 384.66
=======================================================
[build] use-vbo=false: FPS: 1766 FrameTime: 0.566 ms
[build] use-vbo=true: FPS: 3047 FrameTime: 0.328 ms
[texture] texture-filter=nearest: FPS: 2992 FrameTime: 0.334 ms
[texture] texture-filter=linear: FPS: 2824 FrameTime: 0.354 ms
[texture] texture-filter=mipmap: FPS: 2895 FrameTime: 0.345 ms
[shading] shading=gouraud: FPS: 3082 FrameTime: 0.324 ms
[shading] shading=blinn-phong-inf: FPS: 3167 FrameTime: 0.316 ms
[shading] shading=phong: FPS: 2911 FrameTime: 0.344 ms
[shading] shading=cel: FPS: 2937 FrameTime: 0.340 ms
[bump] bump-render=high-poly: FPS: 2381 FrameTime: 0.420 ms
[bump] bump-render=normals: FPS: 3191 FrameTime: 0.313 ms
[bump] bump-render=height: FPS: 2801 FrameTime: 0.357 ms
[effect2d] kernel=0,1,0;1,-4,1;0,1,0;: FPS: 2592 FrameTime: 0.386 ms
[effect2d] kernel=1,1,1,1,1;1,1,1,1,1;1,1,1,1,1;: FPS: 2298 FrameTime: 0.435 ms
[pulsar] light=false:quads=5:texture=false: FPS: 3260 FrameTime: 0.307 ms
[desktop] blur-radius=5:effect=blur:passes=1:separable=true:windows=4: FPS: 1396 FrameTime: 0.716 ms
[desktop] effect=shadow:windows=4: FPS: 1685 FrameTime: 0.593 ms
[buffer] columns=200:interleave=false:update-dispersion=0.9:update-fraction=0.5:update-method=map: FPS: 631 FrameTime: 1.585 ms
[buffer] columns=200:interleave=false:update-dispersion=0.9:update-fraction=0.5:update-method=subdata: FPS: 735 FrameTime: 1.361 ms
[buffer] columns=200:interleave=true:update-dispersion=0.9:update-fraction=0.5:update-method=map: FPS: 758 FrameTime: 1.319 ms
[ideas] speed=duration: FPS: 2672 FrameTime: 0.374 ms
[jellyfish] <default>: FPS: 2358 FrameTime: 0.424 ms
[terrain] <default>: FPS: 533 FrameTime: 1.876 ms
[shadow] <default>: FPS: 2606 FrameTime: 0.384 ms
[refract] <default>: FPS: 1342 FrameTime: 0.745 ms
[conditionals] fragment-steps=0:vertex-steps=0: FPS: 2816 FrameTime: 0.355 ms
[conditionals] fragment-steps=5:vertex-steps=0: FPS: 3029 FrameTime: 0.330 ms
[conditionals] fragment-steps=0:vertex-steps=5: FPS: 2684 FrameTime: 0.373 ms
[function] fragment-complexity=low:fragment-steps=5: FPS: 2863 FrameTime: 0.349 ms
[function] fragment-complexity=medium:fragment-steps=5: FPS: 2894 FrameTime: 0.346 ms
[loop] fragment-loop=false:fragment-steps=5:vertex-steps=5: FPS: 2874 FrameTime: 0.348 ms
[loop] fragment-steps=5:fragment-uniform=false:vertex-steps=5: FPS: 3087 FrameTime: 0.324 ms
[loop] fragment-steps=5:fragment-uniform=true:vertex-steps=5: FPS: 2888 FrameTime: 0.346 ms
=======================================================
                                  glmark2 Score: 2424
=======================================================
```
## lxc container at 800x600 (off-screen framebuffer)
`$ glmark2 -s 800x600 --off-screen`
```
=======================================================
    glmark2 2017.07
=======================================================
    OpenGL Information
    GL_VENDOR:     NVIDIA Corporation
    GL_RENDERER:   Quadro K5000/PCIe/SSE2
    GL_VERSION:    4.5.0 NVIDIA 384.66
=======================================================
[build] use-vbo=false: FPS: 1725 FrameTime: 0.580 ms
[build] use-vbo=true: FPS: 4067 FrameTime: 0.246 ms
[texture] texture-filter=nearest: FPS: 3813 FrameTime: 0.262 ms
[texture] texture-filter=linear: FPS: 3474 FrameTime: 0.288 ms
[texture] texture-filter=mipmap: FPS: 3452 FrameTime: 0.290 ms
[shading] shading=gouraud: FPS: 3724 FrameTime: 0.269 ms
[shading] shading=blinn-phong-inf: FPS: 3686 FrameTime: 0.271 ms
[shading] shading=phong: FPS: 3813 FrameTime: 0.262 ms
[shading] shading=cel: FPS: 3599 FrameTime: 0.278 ms
[bump] bump-render=high-poly: FPS: 2975 FrameTime: 0.336 ms
[bump] bump-render=normals: FPS: 3720 FrameTime: 0.269 ms
[bump] bump-render=height: FPS: 3537 FrameTime: 0.283 ms
[effect2d] kernel=0,1,0;1,-4,1;0,1,0;: FPS: 3328 FrameTime: 0.300 ms
[effect2d] kernel=1,1,1,1,1;1,1,1,1,1;1,1,1,1,1;: FPS: 2818 FrameTime: 0.355 ms
[pulsar] light=false:quads=5:texture=false: FPS: 3482 FrameTime: 0.287 ms
[desktop] blur-radius=5:effect=blur:passes=1:separable=true:windows=4: FPS: 1165 FrameTime: 0.858 ms
[desktop] effect=shadow:windows=4: FPS: 1217 FrameTime: 0.822 ms
[buffer] columns=200:interleave=false:update-dispersion=0.9:update-fraction=0.5:update-method=map: FPS: 653 FrameTime: 1.531 ms
[buffer] columns=200:interleave=false:update-dispersion=0.9:update-fraction=0.5:update-method=subdata: FPS: 563 FrameTime: 1.776 ms
[buffer] columns=200:interleave=true:update-dispersion=0.9:update-fraction=0.5:update-method=map: FPS: 594 FrameTime: 1.684 ms
[ideas] speed=duration: FPS: 2058 FrameTime: 0.486 ms
[jellyfish] <default>: FPS: 2674 FrameTime: 0.374 ms
[terrain] <default>: FPS: 239 FrameTime: 4.184 ms
[shadow] <default>: FPS: 2447 FrameTime: 0.409 ms
[refract] <default>: FPS: 1260 FrameTime: 0.794 ms
[conditionals] fragment-steps=0:vertex-steps=0: FPS: 4968 FrameTime: 0.201 ms
[conditionals] fragment-steps=5:vertex-steps=0: FPS: 4844 FrameTime: 0.206 ms
[conditionals] fragment-steps=0:vertex-steps=5: FPS: 4752 FrameTime: 0.210 ms
[function] fragment-complexity=low:fragment-steps=5: FPS: 4967 FrameTime: 0.201 ms
[function] fragment-complexity=medium:fragment-steps=5: FPS: 4575 FrameTime: 0.219 ms
[loop] fragment-loop=false:fragment-steps=5:vertex-steps=5: FPS: 3674 FrameTime: 0.272 ms
[loop] fragment-steps=5:fragment-uniform=false:vertex-steps=5: FPS: 3626 FrameTime: 0.276 ms
[loop] fragment-steps=5:fragment-uniform=true:vertex-steps=5: FPS: 3617 FrameTime: 0.276 ms
=======================================================
                                  glmark2 Score: 3003
=======================================================
```
# Information to attach
 - nothing notable in dmesg
## Container info
```
Remote: unix://
Architecture: x86_64
Created: 2017/09/15 15:10 UTC
Status: Running
Type: persistent
Profiles: default
Pid: 5078
Ips:
  eth0:	inet	10.137.124.145
  eth0:	inet6	fe80::216:3eff:fe29:c441
  lo:	inet	127.0.0.1
  lo:	inet6	::1
Resources:
  Processes: 28
  CPU usage:
    CPU usage (in seconds): 593
  Memory usage:
    Memory (current): 232.13MB
    Memory (peak): 357.64MB
  Network usage:
    eth0:
      Bytes received: 614.31kB
      Bytes sent: 19.90kB
      Packets received: 3530
      Packets sent: 174
    lo:
      Bytes received: 156B
      Bytes sent: 156B
      Packets received: 4
      Packets sent: 4
Snapshots:
  glmark-wo-xserver (taken at 2017/09/18 18:59 UTC) (stateless)

Log:

```

**Comment by stgraber** [comment] 2017-09-20 17:02
@3XX0 does that ring a bell?

**Comment by 3XX0** [comment] 2017-09-20 23:47
Um difficult to say, GLX is really not container friendly right now.
We're working on it but it might take a while until we figure out all the nitty-gritty details.
Headless EGL on the other hand shouldn't incur any overhead. We're planning on releasing proper support soon for libnvidia-container/nvidia-docker2 which should work seamlessly in LXC.

**Comment by stgraber** [comment] 2017-09-26 20:48
I tried to reproduce the glmark issue but I can't get it to run even on the host, presumably because our GPU test machine doesn't actually have a display :)

Testing some random computation (CUDA) workloads gets me the same numbers inside and outside the container, but I'm not sure what else I could use to play directly with the dri/drm stuff.


LXD isn't doing anything particularly weird here, we're passing straight device nodes so there shouldn't be any overhead here. For X11, you're passing the unix-socket directly through, so that also shouldn't come with any overhead.

One thing I've seen in the past, but I can't really tell if that's an issue here is that some X/GL drivers would opportunistically use shared memory (/dev/shm or similar) to share data between client and server. If the shared memory path didn't exist, they'd fallback to communicating over the X socket, which would cause some performance degradation. But I may be way off on this one :)

I'm closing the LXD issue because I don't think there's anything that LXD can do about this issue. I suspect it's either a X setup issue (shared memory or the like) or is some kind of driver limitation that you're hitting. If you do track down what's going on, let us know here as that's sure to be useful to other users.

**Comment by stgraber** [comment] 2017-09-26 20:57
Just for kicks, I tried it on my laptop (Intel graphics):

```
stgraber@castiana:~$ glmark2 -s 800x600 -b build
=======================================================
    glmark2 2014.03+git20150611.fa71af2d
=======================================================
    OpenGL Information
    GL_VENDOR:     Intel Open Source Technology Center
    GL_RENDERER:   Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) 
    GL_VERSION:    3.0 Mesa 17.2.1
=======================================================
[build] <default>: FPS: 1935 FrameTime: 0.517 ms
=======================================================
                                  glmark2 Score: 1935 
=======================================================
stgraber@castiana:~$ lxc exec glmark -- env DISPLAY=:0 glmark2 -s 800x600 -b build
=======================================================
    glmark2 2014.03+git20150611.fa71af2d
=======================================================
    OpenGL Information
    GL_VENDOR:     Intel Open Source Technology Center
    GL_RENDERER:   Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) 
    GL_VERSION:    3.0 Mesa 17.2.1
=======================================================
[build] <default>: FPS: 1955 FrameTime: 0.512 ms
=======================================================
                                  glmark2 Score: 1955 
=======================================================
stgraber@castiana:~$ 
```

That's widely different from your setup, but it shows that there's at least no systematic 50% performance impact from running inside a container. It even somehow managed to be slightly faster in the container here :)

**Closed by stgraber** 2017-09-26 20:57 UTC
