### ISSUE TITLE
Docker 17.11.0 not working under LXD

### ISSUE THREAD

**Issue by parak** [lxc/lxd#4061] opened 2017-11-28 19:13 UTC
* Distribution: Ubuntu
 * Distribution version: 14.04
 * The output of "lxc info":
```
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIGCjCCA/KgAwIBAgIQRq23baD5WReX+yF62IiHTDANBgkqhkiG9w0BAQsFADBQ
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMTAwLgYDVQQDDCdyb290QGJ1
    aWxkMzAuanVuLmRldi5iYi5zY2hyb2Rpbmdlci5jb20wHhcNMTYxMDE5MTMyMzE1
    WhcNMjYxMDE3MTMyMzE1WjBQMRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3Jn
    MTAwLgYDVQQDDCdyb290QGJ1aWxkMzAuanVuLmRldi5iYi5zY2hyb2Rpbmdlci5j
    b20wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDqd0/KQTjJ56EOzPqz
    x13vHYFyyFS9H4kpwR1BsPPUVnGAKkUPYrZeX2f3AxJ3kkXZMLvGZBahX9fsSHTu
    8Eww4pmxWmtDkpzEBzMCiDruFHe7A3c33+roHTx99IPejylJzCdxDIaM9/inYWLu
    zvxnXrMjQRi77kgYqjV6HtVuJOhyfaGayErE+ZmSM9ZoEZyw6S1rmtB5mrQ8q/pl
    Tm5bBvmx9OzGuc6vnob7AwVS9tYSehPwaVZDfMNSE25j+Cv1QIUp+Pm4NUa4pyV+
    QqcwdLp9l0GQPjqCjN+kI94RqKDypMsc23Ee7PWiOnJMSzyGJYmp4QIxZQUavk5H
    Owp6hUU6p/3q8JVv7KRvI+WW2BPt7Q5nZQ7MOmQwTjwBt74194QZs3ZwiI0rMCD9
    An+fhgbA5OVnjNwb5ewIzf4mdVgzzFv0KUNA+Z6QuHYB4GFXSCNDMsx6alSnhenq
    FjnngxGk7nKgGE0KyyOgfhaqKfMmuT7Tp2Tc5rtOnENCVhdeNIUwirZINRqi+3Tq
    +i6Ior2Gc1/qCjIFkwx8REVXXl1m3j4FrRq+VpiA2UDLs+l0ZES8nLQds4MoEqBV
    2TWWCNymlQ9/nuAFK1tbjwz5IrJ1McpcPSkx9OLWqhEaHkilm4AaGAICLJK+6FLx
    93jnRvCqz2t+xQV/dV0J2Dw3twIDAQABo4HfMIHcMA4GA1UdDwEB/wQEAwIFoDAT
    BgNVHSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMIGmBgNVHREEgZ4wgZuC
    ImJ1aWxkMzAuanVuLmRldi5iYi5zY2hyb2Rpbmdlci5jb22CDzE3Mi4yMy43LjIw
    MS8yMoIbZmU4MDo6YzNjOmZhZmY6ZmVkYTo3Y2U0LzY0gg4xMC4xMDEuMjYuMS8y
    NIIZZmQzODo1MDUxOjQzOTg6MmNmZDo6MS82NIIcZmU4MDo6ZGM4YzplYWZmOmZl
    NzI6ZTg0MC82NDANBgkqhkiG9w0BAQsFAAOCAgEAyAaGIgNpR2CvlMJztJca9VmD
    hLZQTBSj2TRlbwjAT1ID5gAKjNgXF6CfBsGsSm4Q7+Oqdv3MsXJc1H0xqEtSBLLx
    VJ2wq7voutwDOobORcENlHx66XVGnqSUcjskcz9yfXHANvUsJajwoTJX2c893fBP
    /88sTmsl/hms/n/1hhyG6DNqBdrzOhs3qaEaM6DGpkl5sikI1LVYXSWpiaIdKtm1
    yZr7YIelOHTYixlDWqlnqNypIc4P4zCyk4bWSKCliOPIZEiIVxGlqp8Hyia1wX6L
    DI7FftdDzfKXr3jx4Y87Sj/p/Jii5aH56nngo4iUPHMe/RILKUy51ud38lllM6Fb
    Zg05ldmIIWI2re/QxZq8kMz03MV5IAtKCwGlW/tfKY1F1Ul3aiWik6VR2Xmysgbk
    8IuchgFCjc0UGB1FtYaBx9lArsOaKPV1yywbaZSiFaiuerfA3u6B9RmossHM3ONO
    FYUb8re+U3aC/eOhtDTxH6iFWclQr5bTWKAEMO/lDBwNgZULdk9nzTusw7Gl3MOh
    n30UQk7N65sdAariUYI4IcnNfDoHV3QnQuvvmCJjjpubIzbcnRrVO7keyuiHJriv
    MCjE3ZD8JKxbGC60ZmIc7h+scCHYIE+I8a9L6Mce8XvSJLKAAqZZX5hvEFPAxcq0
    Oo9zJantrQCS4PmttbU=
    -----END CERTIFICATE-----
  certificate_fingerprint: e34fe1a87a744c6f4f7d9a642c0563f7721aff65989ce7179f5afcc9300821a7
  driver: lxc
  driver_version: 2.1.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-101-generic
  server: lxd
  server_pid: 1363
  server_version: "2.20"
  storage: dir
  storage_version: "1"
```
 * lxc config of the container:
```
architecture: x86_64
config:
  environment.http_proxy: ""
  image.architecture: x86_64
  image.description: Ubuntu 14.04 LTS server (20160516)
  image.os: ubuntu
  image.release: trusty
  security.nesting: "true"
  security.privileged: "true"
  user.network_mode: ""
  volatile.base_image: b817f5d6c738e52d820fe54178dc64cb99c7245699ed21803e30615840a55fd0
  volatile.eth0.hwaddr: 00:16:3e:f7:b4:29
  volatile.idmap.base: "0"
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  logs:
    path: /var/log/chef-reports
    source: /tmp/kitchen-logs/chef/0/ubuntu-1404
    type: disk
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

# Issue description

It seems that as of this docker version something no longer works right. I'm not sure which is the correct place to file this, but thought I'd try here first. Prior to this version, Docker worked fine for me under LXD, and 17.11.0 works fine outside of LXD as tested on a fresh deployment.

Actual issue follows with docker information:

```
root@ubuntu-1404:~# docker --debug=true run hello-world
DEBU[0000] [hijack] End of stdout                       
docker: Error response from daemon: cgroups: cannot found cgroup mount destination: unknown.
ERRO[0000] error waiting for container: context canceled 
```
```
root@ubuntu-1404:~# docker info
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 2
Server Version: 17.11.0-ce
Storage Driver: vfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 992280e8e265f491f7a624ab82f3e238be086e49
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.4.0-101-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 59.97GiB
Name: ubuntu-1404
ID: P2T7:GYKP:RDBV:U6QQ:Z6BN:TCJY:5WD4:NGF2:NGFV:NXHT:RBPU:IYFU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

Thanks either way :)

**Comment by brauner** [comment] 2017-11-28 19:20
On the host and in the container please show:

    cat /proc/1/mountinfo | grep cgroup
    cat /proc/self/cgroup

**Comment by parak** [comment] 2017-11-28 19:57
Well, the hosts themselves are different, as the one that runs LXD doesn't run Docker outside of it, and the host that runs Docker outside of LXD doesn't run LXD. If that's okay, here's the output from the container:

```
root@ubuntu-1404:~# cat /proc/1/mountinfo | grep cgroup
64 119 0:52 / /sys/fs/cgroup rw,relatime - tmpfs none rw,size=4k,mode=755
68 64 0:27 / /sys/fs/cgroup/cpuset rw,relatime - cgroup cgroup rw,cpuset
69 64 0:28 / /sys/fs/cgroup/cpu rw,relatime - cgroup cgroup rw,cpu
70 64 0:29 / /sys/fs/cgroup/cpuacct rw,relatime - cgroup cgroup rw,cpuacct
71 64 0:30 / /sys/fs/cgroup/blkio rw,relatime - cgroup cgroup rw,blkio
72 64 0:31 / /sys/fs/cgroup/memory rw,relatime - cgroup cgroup rw,memory
73 64 0:32 / /sys/fs/cgroup/devices rw,relatime - cgroup cgroup rw,devices
74 64 0:33 / /sys/fs/cgroup/freezer rw,relatime - cgroup cgroup rw,freezer
75 64 0:34 / /sys/fs/cgroup/net_cls rw,relatime - cgroup cgroup rw,net_cls
76 64 0:35 / /sys/fs/cgroup/perf_event rw,relatime - cgroup cgroup rw,perf_event
77 64 0:36 / /sys/fs/cgroup/net_prio rw,relatime - cgroup cgroup rw,net_prio
78 64 0:37 / /sys/fs/cgroup/hugetlb rw,relatime - cgroup cgroup rw,hugetlb
79 64 0:38 / /sys/fs/cgroup/pids rw,relatime - cgroup cgroup rw,pids
root@ubuntu-1404:~# cat /proc/self/cgroup
13:name=systemd:/
12:pids:/
11:hugetlb:/
10:net_prio:/
9:perf_event:/
8:net_cls:/
7:freezer:/
6:devices:/
5:memory:/
4:blkio:/
3:cpuacct:/
2:cpu:/
1:cpuset:/
```

And the host where 17.11.0 works:

```
root@docker-test:~# cat /proc/1/mountinfo | grep cgroup
23 17 0:17 / /sys/fs/cgroup rw,relatime - tmpfs none rw,size=4k,mode=755
32 23 0:24 / /sys/fs/cgroup/cpuset rw,relatime - cgroup cgroup rw,cpuset
33 23 0:25 / /sys/fs/cgroup/cpu rw,relatime - cgroup cgroup rw,cpu
34 23 0:26 / /sys/fs/cgroup/cpuacct rw,relatime - cgroup cgroup rw,cpuacct
35 23 0:27 / /sys/fs/cgroup/memory rw,relatime - cgroup cgroup rw,memory
36 23 0:28 / /sys/fs/cgroup/devices rw,relatime - cgroup cgroup rw,devices
37 23 0:29 / /sys/fs/cgroup/freezer rw,relatime - cgroup cgroup rw,freezer
38 23 0:30 / /sys/fs/cgroup/blkio rw,relatime - cgroup cgroup rw,blkio
39 23 0:31 / /sys/fs/cgroup/perf_event rw,relatime - cgroup cgroup rw,perf_event
40 23 0:32 / /sys/fs/cgroup/hugetlb rw,relatime - cgroup cgroup rw,hugetlb
50 23 0:35 / /sys/fs/cgroup/systemd rw,nosuid,nodev,noexec,relatime - cgroup systemd rw,name=systemd
root@docker-test:~# cat /proc/self/cgroup
11:name=systemd:/user/9339.user/1.session
10:hugetlb:/user/9339.user/1.session
9:perf_event:/user/9339.user/1.session
8:blkio:/user/9339.user/1.session
7:freezer:/user/9339.user/1.session
6:devices:/user/9339.user/1.session
5:memory:/user/9339.user/1.session
4:cpuacct:/user/9339.user/1.session
3:cpu:/user/9339.user/1.session
2:cpuset:/
```

**Comment by brauner** [comment] 2017-11-28 22:01
Can you please give me the same information from inside the LXD container in which you run Docker.

**Comment by parak** [comment] 2017-11-28 22:07
The first section for 'ubuntu-1404' is from inside the LXD container where 17.11.0 is installed.

**Comment by stgraber** [comment] 2017-11-29 20:43
Ok, so this is Ubuntu 14.04 with the 4.10 kernel on the host, correct?
Then LXD 2.20 installed from trusty-backports?
And then an Ubuntu 14.04 container on top of that with Docker 17.11.0?

Or am I missing something? This is an odd kernel to run on Ubuntu 14.04 (it's not in the archive) so that's why I'm triple checking.

**Comment by parak** [comment] 2017-11-29 21:42
Agh, sorry, the original post (not the cgroup info) was from a newer machine running 17.04 with 4.10 kernel.. was easier to get that stuff from it at the time as it was having the same issue as the 14.04 box with 4.40 kernel. Let me correct the original for that box instead, will update when done..

**Comment by parak** [comment] 2017-11-29 22:37
Updated top comment for the 14.04 boxes, sorry for the confusion. But yeah, version of ubuntu or kernel doesn't seem to matter in this case, just version of docker.

**Comment by parak** [comment] 2017-11-30 18:51
If it helps any, I've also observed that so far this is only an issue on ubuntu containers, centos containers (7.3 at least) work fine with that version of docker.

**Comment by stgraber** [comment] 2017-12-07 02:40
On that 14.04 box, how did you install LXD 2.20? Using the snap or using the PPA? (backports only has 2.0.10)

**Comment by stgraber** [comment] 2017-12-07 02:41
One thing that may cause part of the issue is that 14.04 containers don't know how to configure apparmor inside a container. For that you need 16.04 or higher. Depending on whether docker uses that particular feature, that could explain the problem.

**Comment by parak** [comment] 2017-12-08 17:16
lxd is installed from ppa:

```
lxd:
  Installed: 2.20-0ubuntu4~14.04.1~ppa1
  Candidate: 2.20-0ubuntu4~14.04.1~ppa1
  Version table:
 *** 2.20-0ubuntu4~14.04.1~ppa1 0
        500 http://ppa.launchpad.net/ubuntu-lxc/lxd-stable/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
```

I don't think it's 14.04 specific.. I could check with 16.04, but I don't see it being very helpful as CentOS 7.3 containers can't run Docker 17.11.0 either. For now I'm working around the issue by uninstalling 17.11.0 and installing 17.10.0...

**Comment by stgraber** [comment] 2017-12-08 23:40
Ok, going to test on 14.04 + HWE kernel + LXD 2.20 from PPA with 14.04 container on top.

**Comment by stgraber** [comment] 2017-12-09 00:19
Confirmed the issue with Docker 17.11 inside a 14.04 or 16.04 container on a 14.04 host.
Docker 17.11 appears to work fine if run on a 16.04 host using a 16.04 container though.

**Comment by stgraber** [comment] 2017-12-09 00:19
So looks like it's got more to do with the version of the host than it does the version of the container.

**Comment by stgraber** [comment] 2017-12-09 00:22
Looking at the cgroup layout on 14.04 and 16.04, my guess is that docker is unhappy about the lack of the cpu,cpuacct cgroups or net_cls,net_prio cgroups as those aren't present due to 14.04 mounting things differently.

**Comment by stgraber** [comment] 2017-12-09 00:24
Indeed, manually altering the layout inside the container to mount the few cgroups that systemd skipped due to the host layout, does fix the issue:

```
root@docker-1604:~# mount -o remount,rw /sys/fs/cgroup/
root@docker-1604:~# mkdir /sys/fs/cgroup/cpu
root@docker-1604:~# mkdir /sys/fs/cgroup/cpuacct
root@docker-1604:~# mkdir /sys/fs/cgroup/net_cls
root@docker-1604:~# mkdir /sys/fs/cgroup/net_prio
root@docker-1604:~# mount -t cgroup cgroup -o cpu /sys/fs/cgroup/cpu
root@docker-1604:~# mount -t cgroup cgroup -o cpuacct /sys/fs/cgroup/cpuacct
root@docker-1604:~# mount -t cgroup cgroup -o net_cls /sys/fs/cgroup/net_cls
root@docker-1604:~# mount -t cgroup cgroup -o net_prio /sys/fs/cgroup/net_prio
root@docker-1604:~# docker --debug=true run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://cloud.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/engine/userguide/

DEBU[0000] [hijack] End of stdout                       
root@docker-1604:~# 
```

So you could put those cgroup handling commands inside a systemd unit (or rc.local type script) to have those containers get the few extra cgroups that docker uses nowadays without having to upgrade your host.


Closing as this is the result of different cgroup layout on different distros and kernel restrictions combined with the version of systemd and docker running in the container. LXD itself doesn't setup or mount any of those cgroups so there's nothing we can directly fix ourselves.

**Closed by stgraber** 2017-12-09 00:24 UTC
