### ISSUE TITLE
failed to ensure schema: locking protocol

### ISSUE THREAD

**Issue by ubojan** [lxc/lxd#6322] opened 2019-10-21 12:14 UTC
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04.2 LTS
 * The output of "lxc info" or if that fails: Error: Get http://unix.socket/1.0: EOF
   * Kernel version: 5.0.0-1020-gcp
   * LXC version: 3.18
   * LXD version: 3.18
   * Storage backend in use: ZFS

# Issue description

We've updated lxd snap on bunch of servers and in two cases (from 3.16 to 3.18) lxd couldn't start properly after update, it keeps restarting.

# Steps to reproduce

 1. lxd snap version 3.16 is installed and working on server, set to stable channel.
 2. snap refresh
 3. lxd daemon keeps restarting

# Information to attach

 - [/] Any relevant kernel output (`dmesg`)
 - [X] Container log (`lxc info NAME --show-log`)
Error: Get http://unix.socket/1.0: EOF
 - [X] Container configuration (`lxc config show NAME --expanded`)
Error: Get http://unix.socket/1.0: EOF
 - [X] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
t=2019-10-21T12:08:20+0000 lvl=info msg="LXD 3.18 is starting in normal mode" path=/var/snap/lxd/common/lxd
t=2019-10-21T12:08:20+0000 lvl=info msg="Kernel uid/gid map:"
t=2019-10-21T12:08:20+0000 lvl=info msg=" - u 0 0 4294967295"
t=2019-10-21T12:08:20+0000 lvl=info msg=" - g 0 0 4294967295"
t=2019-10-21T12:08:20+0000 lvl=info msg="Configured LXD uid/gid map:"
t=2019-10-21T12:08:20+0000 lvl=info msg=" - u 0 1000000 1000000000"
t=2019-10-21T12:08:20+0000 lvl=info msg=" - g 0 1000000 1000000000"
t=2019-10-21T12:08:20+0000 lvl=warn msg="Couldn't find the CGroup blkio.weight, I/O weight limits will be ignored."
t=2019-10-21T12:08:20+0000 lvl=info msg="Kernel features:"
t=2019-10-21T12:08:20+0000 lvl=info msg=" - netnsid-based network retrieval: yes"
t=2019-10-21T12:08:20+0000 lvl=info msg=" - uevent injection: yes"
t=2019-10-21T12:08:20+0000 lvl=info msg=" - seccomp listener: yes"
t=2019-10-21T12:08:20+0000 lvl=info msg=" - unprivileged file capabilities: yes"
t=2019-10-21T12:08:20+0000 lvl=info msg=" - shiftfs support: no"
t=2019-10-21T12:08:20+0000 lvl=info msg="Initializing local database"
t=2019-10-21T12:08:29+0000 lvl=info msg="Starting /dev/lxd handler:"
t=2019-10-21T12:08:29+0000 lvl=info msg=" - binding devlxd socket" socket=/var/snap/lxd/common/lxd/devlxd/sock
t=2019-10-21T12:08:29+0000 lvl=info msg="REST API daemon:"
t=2019-10-21T12:08:29+0000 lvl=info msg=" - binding Unix socket" inherited=true socket=/var/snap/lxd/common/lxd/unix.socket
t=2019-10-21T12:08:29+0000 lvl=info msg=" - binding TCP socket" socket=10.240.0.211:8443
t=2019-10-21T12:08:29+0000 lvl=info msg="Initializing global database"
t=2019-10-21T12:08:29+0000 lvl=info msg="Updating the LXD global schema. Backup made as \"global.bak\""
t=2019-10-21T12:08:58+0000 lvl=eror msg="Failed to start the daemon: failed to open cluster database: failed to ensure schema: locking protocol"
t=2019-10-21T12:08:58+0000 lvl=info msg="Starting shutdown sequence"
t=2019-10-21T12:08:58+0000 lvl=info msg="Stopping REST API handler:"
t=2019-10-21T12:08:58+0000 lvl=info msg=" - closing socket" socket=10.240.0.211:8443
t=2019-10-21T12:08:58+0000 lvl=info msg=" - closing socket" socket=/var/snap/lxd/common/lxd/unix.socket
t=2019-10-21T12:08:58+0000 lvl=info msg="Stopping /dev/lxd handler:"
t=2019-10-21T12:08:58+0000 lvl=info msg=" - closing socket" socket=/var/snap/lxd/common/lxd/devlxd/sock
 - [/] Output of the client with --debug
 - [X] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)
DBUG[10-21|12:11:35] Connecting to a local LXD over a Unix socket
DBUG[10-21|12:11:35] Sending request to LXD                   method=GET url=http://unix.socket/1.0 etag=
INFO[10-21|12:12:02] LXD 3.18 is starting in normal mode      path=/var/snap/lxd/common/lxd
INFO[10-21|12:12:02] Kernel uid/gid map:
INFO[10-21|12:12:02]  - u 0 0 4294967295
INFO[10-21|12:12:02]  - g 0 0 4294967295
INFO[10-21|12:12:02] Configured LXD uid/gid map:
INFO[10-21|12:12:02]  - u 0 1000000 1000000000
INFO[10-21|12:12:02]  - g 0 1000000 1000000000
WARN[10-21|12:12:02] Couldn't find the CGroup blkio.weight, I/O weight limits will be ignored.
INFO[10-21|12:12:02] Kernel features:
INFO[10-21|12:12:02]  - netnsid-based network retrieval: yes
INFO[10-21|12:12:02]  - uevent injection: yes
INFO[10-21|12:12:02]  - seccomp listener: yes
INFO[10-21|12:12:02]  - unprivileged file capabilities: yes
INFO[10-21|12:12:02]  - shiftfs support: no
INFO[10-21|12:12:02] Initializing local database
DBUG[10-21|12:12:02] Initializing database gateway
DBUG[10-21|12:12:02] Start database node                      id=1 address=
INFO[10-21|12:12:11] Starting /dev/lxd handler:
INFO[10-21|12:12:11]  - binding devlxd socket                 socket=/var/snap/lxd/common/lxd/devlxd/sock
INFO[10-21|12:12:11] REST API daemon:
INFO[10-21|12:12:11]  - binding Unix socket                   socket=/var/snap/lxd/common/lxd/unix.socket
INFO[10-21|12:12:11]  - binding TCP socket                    socket=10.240.0.211:8443
INFO[10-21|12:12:11] Initializing global database
DBUG[10-21|12:12:11] Dqlite: connected address=1 attempt=0
INFO[10-21|12:12:12] Updating the LXD global schema. Backup made as "global.bak"
DBUG[10-21|12:12:14] Updating global DB schema from 14 to 15
DBUG[10-21|12:12:14] Updating global DB schema from 15 to 16
DBUG[10-21|12:12:38] Updating global DB schema from 16 to 17
DBUG[10-21|12:12:38] Updating global DB schema from 17 to 18
DBUG[10-21|12:12:38] Database error: bindings.Error{Code:15, Message:"locking protocol"}
EROR[10-21|12:12:38] Failed to start the daemon: failed to open cluster database: failed to ensure schema: locking protocol
INFO[10-21|12:12:38] Starting shutdown sequence
INFO[10-21|12:12:38] Stopping REST API handler:
INFO[10-21|12:12:38]  - closing socket                        socket=10.240.0.211:8443
INFO[10-21|12:12:38]  - closing socket                        socket=/var/snap/lxd/common/lxd/unix.socket
INFO[10-21|12:12:38] Stopping /dev/lxd handler:
INFO[10-21|12:12:38]  - closing socket                        socket=/var/snap/lxd/common/lxd/devlxd/sock
DBUG[10-21|12:12:38] Stop database gateway
DBUG[10-21|12:12:40] Not unmounting temporary filesystems (containers are still running)
Error: failed to open cluster database: failed to ensure schema: locking protocol

**Comment by freeekanayaka** [comment] 2019-10-21 14:30
We haven't seen this issue before. It might be an edge case that we didn't know about. Please could you make a tarball of the ```/var/snap/lxd/common/lxd/database``` directory and send it to me? (free dot ekanayaka at canonical dot com)

**Comment by ubojan** [comment] 2019-10-21 15:17
Thanks for your fast response! I've emailed you download link (even compressed folder is too much for email attachment).

**Comment by freeekanayaka** [comment] 2019-10-21 16:05
Okay, the fact it's so big might be related to the issue. The database should be typically be at most 100MB. I'll have a look tomorrow.

**Comment by freeekanayaka** [comment] 2019-10-22 08:23
Just a quick check: it appear the database contains 167 containers and 4658 snapshots of them. Does that match what you'd expect?

**Comment by freeekanayaka** [comment] 2019-10-22 08:40
Okay, I think I figured the cause of the problem. The database schema change from version 17 to version 18 is rather big, since it involves migrating snapshots to a standalone table and you have lots of them. Unfortunately the underlying database has currently some limitations about the size of a single transaction, so this particular update fails to get committed.

Probably the quickest solution to get this instance back online would be to delete some of those snapshots (e.g. all those older than a specific time). Would that be acceptable to you?

Otherwise we'll need to figure out something else, but it might take some time.

**Comment by freeekanayaka** [comment] 2019-10-22 08:47
For example deleting all snapshots older than the first of October 2019 seems to fix the issue:

```bash
# make sure lxd is stopped, then run
echo "DELETE FROM containers WHERE type=1 AND creation_date < '2019-10-01';" > /var/snap/lxd/common/lxd/database/patch.global.sql
# and start lxd again
```

**Comment by ubojan** [comment] 2019-10-22 09:00
Yup I would expect those number for containers and snapshots.
We would like to avoid deleting snapshots if possible, but if fix won't come soon, we might actually consider this.
BTW do you know what would be best (or easiest) way to detect and delete those snapshots (by hand)?

**Comment by freeekanayaka** [comment] 2019-10-22 09:08
@ubojan you might be able to delete them from the database as suggested above, leave them on disk and then re-import them using the ```lxd import``` command. I think @stgraber might be able to confirm that, as I'm not very familiar with the import feature.

You could make a backup, try the above, and revert if it doesn't work.

**Comment by ubojan** [comment] 2019-10-22 10:32
Thanks for the tip! I've deleted snapshots older than 2019-10-01 from the DB and that did the trick, lxd service is running again. I'll wait for @stgraber's advice regarding import.

**Comment by stgraber** [comment] 2019-10-22 13:02
You could try `lxd import NAME`, I suspect it will require you pass `lxd import -f NAME` to let you operate on a container that already exists in the database though. The container filesystem itself needs to be mounted for the backup.yaml file to be located.

**Comment by stgraber** [comment] 2019-10-22 13:02
@freeekanayaka did you file a matching issue against dqlite? We really need this sorted. We already know we'll have a re-shuffle of storage_volumes next cycle which will cause even more changes in a single transaction than this one did.

**Comment by freeekanayaka** [comment] 2019-10-22 15:37
@stgraber issued filed, see above.

**Comment by stgraber** [comment] 2019-10-22 15:56
Ok, closing the LXD side of this then in favor of the dqlite issue.

This is the first report we have of someone hitting this, but likely won't be the last and as I said, we've got more changes coming up soon which will lead to even larger transactions, so it'd be good to prioritize that work accordingly.

**Closed by stgraber** 2019-10-22 15:56 UTC
