### ISSUE TITLE
lxd snap v4.0.0: lxc commands hang for some time

### ISSUE THREAD

**Issue by stiobhan** [lxc/lxd#7124] opened 2020-04-02 21:04 UTC
This is on an Ubuntu 18.04 host running kernel 4.15.0-91-generic

Since the automatic update of the lxd snap to v4.0.0 basic lxc commands hang for almost a minute,e.g.:
```
$ time lxc list
[...]
real  0m51,010s
user  0m0,084s
sys   0m0,103s
```

`lxc info CONTAINER` shows output until here:
```
[...]
  Network usage:
    eth1:
      Bytes received: 9.77MB
      Bytes sent: 375.59MB
      Packets received: 94351
      Packets sent: 41851
    lo:
      Bytes received: 48.59MB
      Bytes sent: 48.59MB
      Packets received: 168219
      Packets sent: 168219
```
then hangs for the same amount of time before finally showing the snapshots.

This is with few containers (around 10). Storage backend is ZFS. Reboot of the server did not help. I'm happy to provide more info, just tell me where to look. I didn't see anything strange in the logs so far.

Here's some output from `strace lxc info CONTAINER`:
```
[...]
getsockname(6, {sa_family=AF_UNIX}, [112->2]) = 0
getpeername(6, {sa_family=AF_UNIX, sun_path="/var/snap/lxd/common/lxd/unix.socket"}, [112->39]) = 0
futex(0xc000100148, FUTEX_WAKE_PRIVATE, 1) = 1
write(6, "GET /1.0 HTTP/1.1\r\nHost: unix.so"..., 144) = 144
futex(0xc000180148, FUTEX_WAKE_PRIVATE, 1) = 1
epoll_pwait(3, [], 128, 0, NULL, 824635513768) = 0
futex(0x1383a28, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
epoll_pwait(3, [], 128, 0, NULL, 0)     = 0
epoll_pwait(3, [{EPOLLOUT, {u32=212315976, u64=140308203941704}}], 128, -1, NULL, 0) = 1
epoll_pwait(3, [], 128, 0, NULL, 20633544) = 0
futex(0x1383a28, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
epoll_pwait(3, [], 128, 0, NULL, 0)     = 0
mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f9c0c840000
openat(AT_FDCWD, "/etc//localtime", O_RDONLY) = 6
read(6, "TZif2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\5\0\0\0\5\0\0\0\0"..., 4096) = 1918
read(6, "", 4096)                       = 0
close(6)                                = 0
futex(0xc000180148, FUTEX_WAKE_PRIVATE, 1) = 1
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 6
setsockopt(6, SOL_SOCKET, SO_BROADCAST, [1], 4) = 0
connect(6, {sa_family=AF_UNIX, sun_path="/var/snap/lxd/common/lxd/unix.socket"}, 39) = 0
epoll_ctl(3, EPOLL_CTL_ADD, 6, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=212315976, u64=140308203941704}}) = 0
getsockname(6, {sa_family=AF_UNIX}, [112->2]) = 0
getpeername(6, {sa_family=AF_UNIX, sun_path="/var/snap/lxd/common/lxd/unix.socket"}, [112->39]) = 0
futex(0xc000180148, FUTEX_WAKE_PRIVATE, 1) = 1
read(6, 0xc000476000, 4096)             = -1 EAGAIN (Resource temporarily unavailable)
futex(0x1383a28, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x1383a28, FUTEX_WAIT_PRIVATE, 0, NULL
```
and this is where it hangs. Does that help?

PS: just occurred to me, should I have filed this under lxc/lxc?

**Comment by stgraber** [comment] 2020-04-02 21:35
Does `lxc list --fast` behave differently?

**Comment by stgraber** [comment] 2020-04-02 21:36
Tracing the client is very unlikely to be helpful, all it does is send a REST request to the daemon.

**Comment by stgraber** [comment] 2020-04-02 21:38
I suspect that's the feature where we go and fetch the snapshot sizes now.

I already talked with @tomponline about not doing that when we list all containers (`lxc list`).
`lxc info` has a stronger case for fetching that information, though we need to look into why ZFS is being that slow in your case.

**Comment by stiobhan** [comment] 2020-04-02 21:39
Yes `--fast` does not hang.

RIght... I wasn't aware how lxc and the daemon communicate.

**Comment by stiobhan** [comment] 2020-04-02 21:55
I've checked `lxc info` for all the containers now, and it only hangs for some of them. But it doesn't seem to depend on the number of snapshots. `lxc snapshot CONTAINER SNAPSHOTNAME` hangs too for these containers. `lxc delete CONTAINER/SNAPSHOTNAME` is fast however.

**Comment by stgraber** [comment] 2020-04-02 22:13
Yeah, so that's hitting some kind of ZFS issue. So we'll be landing some changes in logic to at least speed up list and look at how we retrieve the size of snapshots in info.

But if creating a new snapshot is slow too, that does hint at some ZFS issues maybe.

Can you try manually creating and deleting a snapshot on the dataset?

```
zfs snapshot pool/dataset@blah
zfs destroy pool/dataset@blah
```

And see if that also is slow for those containers?

**Comment by stiobhan** [comment] 2020-04-02 22:20
Manually creating and destroying snapshots on these containers is fast (command returns in less than 0.1 seconds)

**Comment by stiobhan** [comment] 2020-04-02 22:23
```
NAME                                                                                            USED  AVAIL  REFER  MOUNTPOINT
tank/containers/zulip                                                                          9,96G  1,29T  6,39G  /var/snap/lxd/common/lxd/storage-pools/tank/containers/zulip
tank/containers/zulip@snapshot-clean                                                           51,4M      -   701M  -
tank/containers/zulip@snapshot-zulip-clean                                                      735M      -  1,66G  -
tank/containers/zulip@snapshot-2.0.4                                                            904M      -  4,54G  -
tank/containers/zulip@snapshot-pre-2.1.2                                                       82,9M      -  5,75G  -
tank/containers/zulip@snapshot-2.1.2                                                           83,4M      -  6,13G  -
tank/containers/zulip@snapshot-pre-2.1.3                                                       82,6M      -  6,52G  -
tank/containers/zulip@snapshot-2.1.3                                                           9,38M      -  6,39G  -
```

**Comment by stiobhan** [comment] 2020-04-02 22:26
Just noticed that `zpool status` tells me
```
status: Some supported features are not enabled on the pool. The pool can
	still be used, but some features are unavailable.
action: Enable all features using 'zpool upgrade'. Once this is done,
	the pool may no longer be accessible by software that does not support
	the features. See zpool-features(5) for details.
```
I suppose this is safe to do for lxd 4.0.0?

**Comment by stgraber** [comment] 2020-04-02 23:09
Yeah, you can upgrade your pool, that's fine. What matters is that your kernel supports it but that should be the case here.

**Comment by stgraber** [comment] 2020-04-02 23:11
Interesting about snapshot creation being fast at the ZFS level, this may suggest that something in the LXD code calls for the snapshot details and causes the same slowdown.

**Comment by stiobhan** [comment] 2020-04-03 06:55
Seems that way. I also copied one of the containers to a different host (running lxd 3.0.3), deleted it, and copied it back. Problem still persist. Let me know if you need more info, debug logs or anything

**Comment by stiobhan** [comment] 2020-04-03 07:05
> I suspect that's the feature where we go and fetch the snapshot sizes now.
Should I see the snapshot size there somewhere? Neither `lxc list` nor `lxc info CONTAINER` shows anything about snapshot size. I just see the time when the snapshot was taken.
```
[...]
Snapshots:
  1.9.2-ready-to-go (taken at 2019/10/28 16:11 UTC) (stateless)
  2.0.4 (taken at 2019/10/28 16:14 UTC) (stateless)
  pre-2.1.2 (taken at 2020/02/19 18:45 UTC) (stateless)
  2.1.2 (taken at 2020/02/19 19:03 UTC) (stateless)
```
and the number of snapshots with `lxc list`.

**Comment by tomponline** [comment] 2020-04-03 07:58
@stiobhan so this PR (https://github.com/lxc/lxd/pull/7117) that got merged yesterday should partially alleviate the issue somewhat as it removes the mounting of snapshots when listing information introduced in https://github.com/lxc/lxd/pull/7071.

@stgraber you are correct that when taking a snapshot before https://github.com/lxc/lxd/pull/7117 is cherry-picked into the snapd package, the issue is that LXD updates the instance's backup.yaml file when creating a snapshot, which i turn populates info about all prior snapshots, which in turn calls mount on each snapshot. This was particularly bad on filesystems that needed UUID regeneration before mount, but would likely slow down the process for instances on other storage backends too.

**Comment by tomponline** [comment] 2020-04-03 08:00
@stiobhan I am going to put a PR up shortly that totally removes the snapshot usage metric from the `RenderFull()` function used in in `lxc list`

**Comment by tomponline** [comment] 2020-04-03 08:10
@stiobhan accessing the actual snapshot usage is currently only in API, e.g.

```
lxc query /1.0/instances/c1/snapshots/snap0 | jq .size
61440
```

**Comment by stiobhan** [comment] 2020-04-03 08:16
@tomponline any guess why `lxc query /1.0/instances/c1/snapshots/snap0` takes about 10 seconds for some containers and less than a second for others in my case?

**Comment by tomponline** [comment] 2020-04-03 08:24
@stiobhan can you provide the `lxc config show <conainer> --expanded` for a container that is quick and a container that is slow please.

Also can you show the output of `zfs list` on the host? Thanks

**Comment by stiobhan** [comment] 2020-04-03 08:44
quick: https://pastebin.com/ReStBdQe
slow: https://pastebin.com/qmAXPEU7
`zfs list`: https://pastebin.com/mvAUnTfw

**Comment by tomponline** [comment] 2020-04-03 09:00
Cheers, can you get me the output of `zfs list -t snapshot` too please

**Comment by stiobhan** [comment] 2020-04-03 11:51
pastebin is down, here's everything again on a different site (also nicer without big commercial banners ;-) ).

quick (ganglia): https://paste.ubuntu.com/p/kg59qGFPz9/
slow (zulip): https://paste.ubuntu.com/p/CNByzJg3q3/
`zfs list`: https://paste.ubuntu.com/p/kMGXDzsh2z/
`zfs list -t snapshot`: https://paste.ubuntu.com/p/XccyMJZq8x/

**Comment by stiobhan** [comment] 2020-04-03 12:19
Another observation, this is fast:
```
$ lxc query /1.0/instances/zulip/snapshots
[
	"/1.0/instances/zulip/snapshots/2.0.4",
	"/1.0/instances/zulip/snapshots/clean",
	"/1.0/instances/zulip/snapshots/zulip-clean",
	"/1.0/instances/zulip/snapshots/2.1.2",
	"/1.0/instances/zulip/snapshots/pre-2.1.2",
	"/1.0/instances/zulip/snapshots/2.1.3",
	"/1.0/instances/zulip/snapshots/pre-2.1.3"
]
```
But accessing the snapshots with e.g. `lxc query /1.0/instances/zulip/snapshots/2.0.4` takes around 10 seconds, _except_ for the last two, which I think I created with lxd 4.0.0. So does lxd store additional info now in the snapshot that needs to be retrieved in some other way if not present?

**Closed** 2020-04-03 12:50 UTC
Labels: Bug

**Comment by stiobhan** [comment] 2020-04-03 16:59
Does that also fix the slow output for `lxc query ...` and `lxc info ...` I mentioned above?

**Comment by stgraber** [comment] 2020-04-03 17:57
It will fix `lxc list` for sure, for the others, it should be a bit better because there will not be any attempt at mounting the pool, there's still a bit more work needed to optimize fetching the value, but those fixes may be good enough for most already.

**Comment by stiobhan** [comment] 2020-04-06 08:58
I would like to test this. Is it safe to install the snap from latest/edge, and then downgrade to 3.23/stable? Or is it in general not a good idea to downgrade from 4.0 to 3.23?

**Comment by stgraber** [comment] 2020-04-06 12:19
In general, assume that downgrades will not work. If any change had to be made to the database or on disk structure, LXD will refuse to start after a downgrade.

**Comment by stiobhan** [comment] 2020-04-06 13:33
I tried the latest/edge snap (git-fcbba26) on a different machine, and indeed both `lxc list` and `lxc info CONTAINER` are as quick as they used to be. Any plans to push this to 4.0/stable any time soon?

**Comment by stgraber** [comment] 2020-04-06 13:43
It's rolling out to stable now

**Comment by stiobhan** [comment] 2020-04-06 13:57
Hi @stgraber @tomponline ! I just found the real issue, I think. I found it quite suspicious that commands like this:
```
lxc query /1.0/instances/zulip/snapshots/2.1.2
```
took just slightly above 10 seconds as I mentioned here https://github.com/lxc/lxd/issues/7124#issuecomment-608296972

And as I mentioned here https://github.com/lxc/lxd/issues/7124#issuecomment-608402234 only the snapshots created with 4.0.0 have directories under `/var/snap/lxd/common/lxd/storage-pools/tank/containers-snapshots/zulip/`. If I create the missing directories for the other snapshots there manually the query returns immediately. So I suspect mounting fails if that directory does not exist and there must be a 10 second timeout somewhere in snapshot mounting code.

**Comment by stgraber** [comment] 2020-04-06 14:11
Oh, yes, that could definitely be an issue :)

@tomponline can you send a branch to sort that out?
We either need a patch that creates all the missing bits one time or we need to have logic which creates the mountpoint if missing on mount.

**Comment by tomponline** [comment] 2020-04-06 14:25
@stgraber will do
