### ISSUE TITLE
Mounting cgroup in Trusty container

### ISSUE THREAD

**Issue by kimh** [lxc/lxd#2322] opened 2016-08-30 08:47 UTC
# Required information

 * Distribution: Ubuntu Xenial
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-34-generic
   * LXD version: 2.0.3
   * Storage backend in use: dir

# Issue description

Most of cgroup is not mounted in Trusty container whereas they are fine in Xenial container.

**Xenial**

```
ubuntu@ubuntu-xenial:~$ lxc launch ubuntu-daily:16.04 xenial-container -p default
Creating xenial-container
Starting xenial-container

ubuntu@ubuntu-xenial:~$ lxc exec xenial-container -- /bin/bash -c "cat /proc/self/mountinfo | grep cgroup"
75 147 0:60 / /sys/fs/cgroup ro,nosuid,nodev,noexec - tmpfs tmpfs ro,mode=755,uid=100000,gid=100000
76 75 0:22 / /sys/fs/cgroup/systemd rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd
77 75 0:31 / /sys/fs/cgroup/cpu,cpuacct rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,cpu,cpuacct
78 75 0:33 / /sys/fs/cgroup/hugetlb rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,hugetlb
79 75 0:24 / /sys/fs/cgroup/net_cls,net_prio rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,net_cls,net_prio
80 75 0:25 / /sys/fs/cgroup/perf_event rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,perf_event
81 75 0:29 / /sys/fs/cgroup/pids rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,pids
82 75 0:28 / /sys/fs/cgroup/cpuset rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,cpuset
83 75 0:32 / /sys/fs/cgroup/memory rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,memory
84 75 0:26 / /sys/fs/cgroup/freezer rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,freezer
85 75 0:30 / /sys/fs/cgroup/blkio rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,blkio
86 75 0:27 / /sys/fs/cgroup/devices rw,nosuid,nodev,noexec,relatime - cgroup cgroup rw,devices u
```

**Trusty**

```
ubuntu@ubuntu-xenial:~$ lxc launch ubuntu-daily:14.04 trusty-container -p default
Creating trusty-container
Starting trusty-container

ubuntu@ubuntu-xenial:~$ lxc exec trusty-container -- /bin/bash -c "cat /proc/self/mountinfo | grep cgroup"
64 111 0:47 / /sys/fs/cgroup rw,nodev,relatime - tmpfs none rw,size=4k,mode=755,uid=100000,gid=100000
```

As you can see, most of cgroup controller is not available in Trusty. How can I mount cgroup in Trusty just like in Xenial?

**Comment by stgraber** [comment] 2016-08-30 17:09
That's because Ubuntu 14.04 simply doesn't mount the cgroup controllers.

You can install something like cgroup-lite in the container which will setup those mounts for you.

**Comment by stgraber** [comment] 2016-08-30 17:10
I just confirmed in a 14.04 container that installing cgroup-lite indeed does setup those mounts, so there's no LXD issue here. Closing.

**Closed by stgraber** 2016-08-30 17:10 UTC
