### ISSUE TITLE
Installation via snap and backports causing issues

### ISSUE THREAD

**Issue by despens** [lxc/lxd#4301] opened 2018-03-06 01:32 UTC
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.10.0-40-generic
   * LXC version: 2.21
   * LXD version: 2.21
   * Storage backend in use: nothing yet

# Issue description

Installing LXD via snap or backports causes issues. LXD installation cannot be finished.

# Steps to reproduce

1. Install lxd via snap: results in a mix of 2.21 (from snap) and 2.0.x (pre-installed) lxd/lxc tools. 
2. Remove lxd via snap.
3. Install lxd via xenial backports
4. dpkg hangs at:

```
Processing triggers for ureadahead (0.100.0-19) ...
Setting up lxd (2.21-0ubuntu3~16.04.1) ...   
```

# Information to attach

Nothing yet :)

**Comment by stgraber** [comment] 2018-03-06 07:00
Trying to reproduce this here. I can see how there could be some odd conflict if installing the deb after the snap is installed, but I'm not sure as to why things would hang if the snap is removed... Lets see what happens on a clean 16.04 system matching your description.

**Comment by stgraber** [comment] 2018-03-06 07:53
I'm unable to reproduce this here:
```
root@vm02:~# apt update
Hit:1 http://us.archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Hit:3 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease
Get:4 http://us.archive.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Get:5 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [738 kB]
Get:6 http://us.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [595 kB]
Fetched 1,538 kB in 0s (2,060 kB/s)                      
Reading package lists... Done
Building dependency tree       
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
root@vm02:~# apt dist-upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  cloud-init
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 346 kB of archives.
After this operation, 49.2 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 cloud-init all 17.2-35-gf576b2a2-0ubuntu1~16.04.2 [346 kB]
Fetched 346 kB in 0s (20.5 MB/s)   
Preconfiguring packages ...
(Reading database ... 60182 files and directories currently installed.)
Preparing to unpack .../cloud-init_17.2-35-gf576b2a2-0ubuntu1~16.04.2_all.deb ...
Unpacking cloud-init (17.2-35-gf576b2a2-0ubuntu1~16.04.2) over (17.1-46-g7acc9e68-0ubuntu1~16.04.1) ...
Processing triggers for ureadahead (0.100.0-19) ...
Setting up cloud-init (17.2-35-gf576b2a2-0ubuntu1~16.04.2) ...
Leaving 'diversion of /etc/init/ureadahead.conf to /etc/init/ureadahead.conf.disabled by cloud-init'

root@vm02:~# dpkg -l | grep lxd
ii  lxd                                  2.0.11-0ubuntu1~16.04.4                    amd64        Container hypervisor based on LXC - daemon
ii  lxd-client                           2.0.11-0ubuntu1~16.04.4                    amd64        Container hypervisor based on LXC - client

root@vm02:~# snap install lxd
2018-03-06T07:51:25Z INFO Waiting for restart...
lxd 2.21 from 'canonical' installed

root@vm02:~# ps fauxww
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         2  0.0  0.0      0     0 ?        S    07:04   0:00 [kthreadd]
root         3  0.0  0.0      0     0 ?        S    07:04   0:00  \_ [ksoftirqd/0]
root         5  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [kworker/0:0H]
root         7  0.0  0.0      0     0 ?        S    07:04   0:00  \_ [rcu_sched]
root         8  0.0  0.0      0     0 ?        S    07:04   0:00  \_ [rcu_bh]
root         9  0.0  0.0      0     0 ?        S    07:04   0:00  \_ [migration/0]
root        10  0.0  0.0      0     0 ?        S    07:04   0:00  \_ [watchdog/0]
root        11  0.0  0.0      0     0 ?        S    07:04   0:00  \_ [watchdog/1]
root        12  0.0  0.0      0     0 ?        S    07:04   0:00  \_ [migration/1]
root        13  0.0  0.0      0     0 ?        S    07:04   0:00  \_ [ksoftirqd/1]
root        15  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [kworker/1:0H]
root        16  0.0  0.0      0     0 ?        S    07:04   0:00  \_ [watchdog/2]
root        17  0.0  0.0      0     0 ?        S    07:04   0:00  \_ [migration/2]
root        18  0.0  0.0      0     0 ?        S    07:04   0:00  \_ [ksoftirqd/2]
root        19  0.0  0.0      0     0 ?        S    07:04   0:00  \_ [kworker/2:0]
root        20  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [kworker/2:0H]
root        21  0.0  0.0      0     0 ?        S    07:04   0:00  \_ [watchdog/3]
root        22  0.0  0.0      0     0 ?        S    07:04   0:00  \_ [migration/3]
root        23  0.0  0.0      0     0 ?        S    07:04   0:00  \_ [ksoftirqd/3]
root        25  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [kworker/3:0H]
root        26  0.0  0.0      0     0 ?        S    07:04   0:00  \_ [kdevtmpfs]
root        27  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [netns]
root        28  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [perf]
root        29  0.0  0.0      0     0 ?        S    07:04   0:00  \_ [khungtaskd]
root        30  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [writeback]
root        31  0.0  0.0      0     0 ?        SN   07:04   0:00  \_ [ksmd]
root        32  0.0  0.0      0     0 ?        SN   07:04   0:00  \_ [khugepaged]
root        33  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [crypto]
root        34  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [kintegrityd]
root        35  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [bioset]
root        36  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [kblockd]
root        37  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [ata_sff]
root        38  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [md]
root        39  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [devfreq_wq]
root        42  0.0  0.0      0     0 ?        S    07:04   0:00  \_ [kworker/3:1]
root        44  0.0  0.0      0     0 ?        S    07:04   0:00  \_ [kswapd0]
root        45  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [vmstat]
root        46  0.0  0.0      0     0 ?        S    07:04   0:00  \_ [fsnotify_mark]
root        47  0.0  0.0      0     0 ?        S    07:04   0:00  \_ [ecryptfs-kthrea]
root        63  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [kthrotld]
root        64  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [acpi_thermal_pm]
root        65  0.0  0.0      0     0 ?        S    07:04   0:00  \_ [vballoon]
root        66  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [bioset]
root        67  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [bioset]
root        68  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [bioset]
root        69  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [bioset]
root        70  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [bioset]
root        71  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [bioset]
root        72  0.0  0.0      0     0 ?        S    07:04   0:00  \_ [kworker/0:1]
root        73  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [bioset]
root        74  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [bioset]
root        75  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [bioset]
root        76  0.0  0.0      0     0 ?        S    07:04   0:00  \_ [scsi_eh_0]
root        77  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [scsi_tmf_0]
root        78  0.0  0.0      0     0 ?        S    07:04   0:00  \_ [scsi_eh_1]
root        79  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [scsi_tmf_1]
root        84  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [ipv6_addrconf]
root        97  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [deferwq]
root        98  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [charger_manager]
root        99  0.0  0.0      0     0 ?        S    07:04   0:00  \_ [kworker/1:1]
root       158  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [bioset]
root       159  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [bioset]
root       160  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [bioset]
root       161  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [bioset]
root       162  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [bioset]
root       163  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [bioset]
root       164  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [bioset]
root       165  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [bioset]
root       166  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [kpsmoused]
root       266  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [raid5wq]
root       293  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [bioset]
root       315  0.0  0.0      0     0 ?        S    07:04   0:00  \_ [jbd2/vda1-8]
root       316  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [ext4-rsv-conver]
root       370  0.0  0.0      0     0 ?        S    07:04   0:00  \_ [kworker/3:2]
root       386  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [iscsi_eh]
root       402  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [kworker/0:1H]
root       403  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [ib_addr]
root       406  0.0  0.0      0     0 ?        S    07:04   0:00  \_ [kworker/1:2]
root       407  0.0  0.0      0     0 ?        S    07:04   0:00  \_ [kauditd]
root       409  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [ib_mcast]
root       414  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [ib_nl_sa_wq]
root       421  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [ib_cm]
root       424  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [iw_cm_wq]
root       425  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [rdma_cm]
root       440  0.0  0.0      0     0 ?        S    07:04   0:00  \_ [kworker/0:2]
root       504  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [kvm-irqfd-clean]
root       631  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [kworker/2:1H]
root       690  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [kworker/1:1H]
root       958  0.0  0.0      0     0 ?        S<   07:04   0:00  \_ [kworker/3:1H]
root      2351  0.0  0.0      0     0 ?        S    07:15   0:00  \_ [kworker/u8:2]
root      2366  0.0  0.0      0     0 ?        S    07:19   0:00  \_ [kworker/2:2]
root      2397  0.0  0.0      0     0 ?        S    07:42   0:00  \_ [kworker/u8:1]
root      2863  0.0  0.0      0     0 ?        S    07:51   0:00  \_ [kworker/u8:0]
root      2944  0.0  0.0      0     0 ?        S    07:51   0:00  \_ [kworker/2:1]
root      2947  0.2  0.0      0     0 ?        S<   07:51   0:00  \_ [loop0]
root      3024  0.0  0.0      0     0 ?        S    07:51   0:00  \_ [kworker/3:0]
root      3234  0.0  0.0      0     0 ?        S    07:51   0:00  \_ [kworker/0:0]
root      3236  0.1  0.0      0     0 ?        S<   07:51   0:00  \_ [loop1]
root         1  0.1  0.0  37868  5920 ?        Ss   07:04   0:03 /sbin/init
root       400  0.0  0.0  35420  3776 ?        Ss   07:04   0:00 /lib/systemd/systemd-journald
root       445  0.0  0.0  94772  1484 ?        Ss   07:04   0:00 /sbin/lvmetad -f
root       468  0.0  0.0  44344  3976 ?        Ss   07:04   0:00 /lib/systemd/systemd-udevd
systemd+   675  0.0  0.0 100324  2512 ?        Ssl  07:04   0:00 /lib/systemd/systemd-timesyncd
root       994  0.0  0.0   5220   152 ?        Ss   07:04   0:00 /sbin/iscsid
root       995  0.0  0.0   5720  3512 ?        S<Ls 07:04   0:00 /sbin/iscsid
root       998  0.0  0.0  26068  2584 ?        Ss   07:04   0:00 /usr/sbin/cron -f
message+  1003  0.0  0.0  42900  3876 ?        Ss   07:04   0:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
root      1014  0.0  0.0   4396  1304 ?        Ss   07:04   0:00 /usr/sbin/acpid
root      1016  0.0  0.0  95368  1512 ?        Ssl  07:04   0:00 /usr/bin/lxcfs /var/lib/lxcfs/
root      1025  0.0  0.0  28544  3092 ?        Ss   07:04   0:00 /lib/systemd/systemd-logind
root      1027  0.0  0.0 272944  5912 ?        Ssl  07:04   0:00 /usr/lib/accountsservice/accounts-daemon
syslog    1045  0.0  0.0 260628  5452 ?        Ssl  07:04   0:00 /usr/sbin/rsyslogd -n
daemon    1051  0.0  0.0  26044  2132 ?        Ss   07:04   0:00 /usr/sbin/atd -f
root      1090  0.0  0.0 277176  6064 ?        Ssl  07:04   0:00 /usr/lib/policykit-1/polkitd --no-debug
root      1091  0.0  0.0  13372   160 ?        Ss   07:04   0:00 /sbin/mdadm --monitor --pid-file /run/mdadm/monitor.pid --daemonise --scan --syslog
root      1164  0.0  0.0  19472   236 ?        Ss   07:04   0:00 /usr/sbin/irqbalance --pid=/var/run/irqbalance.pid
root      1168  0.0  0.0  14656  1740 tty1     Ss+  07:04   0:00 /sbin/agetty --noclear tty1 linux
root      1213  0.0  0.0  65508  5708 ?        Ss   07:04   0:00 /usr/sbin/sshd -D
root      2406  0.0  0.0  92796  6980 ?        Ss   07:50   0:00  \_ sshd: ubuntu [priv]
ubuntu    2464  0.2  0.0  92796  3248 ?        S    07:50   0:00      \_ sshd: ubuntu@pts/0
root      2468  0.0  0.0  55740  3984 pts/0    Ss   07:50   0:00          \_ sudo -i
root      2469  0.0  0.0  21296  5204 pts/0    S    07:50   0:00              \_ -bash
root      3581  0.0  0.0  36228  3572 pts/0    R+   07:52   0:00                  \_ ps fauxww
ntp       2259  0.0  0.0 110032  5004 ?        Ssl  07:04   0:00 /usr/sbin/ntpd -p /var/run/ntpd.pid -g -u 112:116
ubuntu    2408  0.0  0.0  45276  4716 ?        Ss   07:50   0:00 /lib/systemd/systemd --user
ubuntu    2411  0.0  0.0  61320  2028 ?        S    07:50   0:00  \_ (sd-pam)
root      3035 11.9  0.4 384716 33532 ?        Ssl  07:51   0:04 /usr/lib/snapd/snapd
root      3471  0.3  0.0   4504  1744 ?        Ss   07:51   0:00 /bin/sh /snap/lxd/5866/commands/daemon.start
root      3557 41.0  0.3 576740 29592 ?        Sl   07:51   0:05  \_ lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd
root      3545  0.1  0.0  95384  3436 ?        Sl   07:51   0:00 lxcfs /var/snap/lxd/common/var/lib/lxcfs -p /var/snap/lxd/common/lxcfs.pid

root@vm02:~# snap remove lxd
lxd removed

root@vm02:~# apt install -t xenial-backports lxd
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  ebtables lxd-client xdelta3
Suggested packages:
  criu lxd-tools
The following NEW packages will be installed:
  ebtables xdelta3
The following packages will be upgraded:
  lxd lxd-client
2 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 6,276 kB of archives.
After this operation, 2,320 kB disk space will be freed.
Do you want to continue? [Y/n] 
Get:1 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 ebtables amd64 2.0.10.4-3.4ubuntu2 [79.4 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu xenial-backports/main amd64 lxd amd64 2.21-0ubuntu3~16.04.1 [3,703 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu xenial-backports/main amd64 lxd-client amd64 2.21-0ubuntu3~16.04.1 [2,427 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 xdelta3 amd64 3.0.8-dfsg-1ubuntu2 [67.1 kB]
Fetched 6,276 kB in 0s (43.9 MB/s)
Selecting previously unselected package ebtables.
(Reading database ... 60185 files and directories currently installed.)
Preparing to unpack .../ebtables_2.0.10.4-3.4ubuntu2_amd64.deb ...
Unpacking ebtables (2.0.10.4-3.4ubuntu2) ...
Preparing to unpack .../lxd_2.21-0ubuntu3~16.04.1_amd64.deb ...
Warning: Stopping lxd.service, but it can still be activated by:
  lxd.socket
Unpacking lxd (2.21-0ubuntu3~16.04.1) over (2.0.11-0ubuntu1~16.04.4) ...
Warning: Stopping lxd.service, but it can still be activated by:
  lxd.socket
Preparing to unpack .../lxd-client_2.21-0ubuntu3~16.04.1_amd64.deb ...
Unpacking lxd-client (2.21-0ubuntu3~16.04.1) over (2.0.11-0ubuntu1~16.04.4) ...
Selecting previously unselected package xdelta3.
Preparing to unpack .../xdelta3_3.0.8-dfsg-1ubuntu2_amd64.deb ...
Unpacking xdelta3 (3.0.8-dfsg-1ubuntu2) ...
Processing triggers for systemd (229-4ubuntu21.1) ...
Processing triggers for ureadahead (0.100.0-19) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up ebtables (2.0.10.4-3.4ubuntu2) ...
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
Setting up lxd-client (2.21-0ubuntu3~16.04.1) ...
Setting up xdelta3 (3.0.8-dfsg-1ubuntu2) ...
Setting up lxd (2.21-0ubuntu3~16.04.1) ...
Installing new version of config file /etc/init.d/lxd ...
Removing obsolete conffile /etc/init/lxd.conf ...
Setting up lxd dnsmasq configuration.

Old bridge configuration detected in /etc/default/lxd-bridge, upgrading
Unsetting deprecated profile options
Attempting to kill current lxd-bridge
Stock LXD installation detected, resetting to new defaults
Cleaning up lxd-bridge state files

Processing triggers for systemd (229-4ubuntu21.1) ...
Processing triggers for ureadahead (0.100.0-19) ...
root@vm02:~# 
```

**Comment by despens** [comment] 2018-03-06 22:13
Thank for these hints!
I executed the commands and tried to filter for lxd. Indeed as you suggested, `lxd waitready` is there.
However it impossible to `kill -9` it, there is just no change.

```
# ps fauxww | grep lxd
root     15689  0.0  0.1 320676 19168 ?        Ssl  22:53   0:00 /usr/bin/lxd waitready --timeout=600

#
 systemctl -a | grep lxd
  sys-devices-virtual-net-lxdbr0.device                                                                                   loaded    active     plugged          /sys/devices/virtual/net/lxdbr0
  sys-subsystem-net-devices-lxdbr0.device                                                                                 loaded    active     plugged          /sys/subsystem/net/devices/lxdbr0
● lxd-bridge.service                                                                                                      not-found active     exited           lxd-bridge.service
● lxd-containers.service                                                                                                  loaded    failed     failed           LXD - container startup/shutdown
  lxd.service                                                                                                             loaded    activating start-post start LXD - main daemon
  lxd.socket                                                                                                              loaded    active     running          LXD - unix socket


# journalctl -n 300 _SYSTEMD_UNIT=lxd-containers.service
-- Logs begin at Mo 2018-03-05 04:46:50 CET, end at Di 2018-03-06 23:04:30 CET. --
Mär 06 02:33:00 eiger lxd[20266]: error: Get http://unix.socket/1.0: dial unix /var/lib/lxd/unix.socket: connect: resource temporarily unavailable
Mär 06 02:43:00 eiger lxd[20531]: error: Get http://unix.socket/1.0: dial unix /var/lib/lxd/unix.socket: connect: resource temporarily unavailable
Mär 06 02:53:00 eiger lxd[20777]: error: Get http://unix.socket/1.0: dial unix /var/lib/lxd/unix.socket: connect: resource temporarily unavailable
```

**Comment by stgraber** [comment] 2018-03-06 22:57
Hmm, the resource temporarily unavailable suggests that systemd socket activation isn't quite working in this case. Can you search a bit more widely in the journal, specifically for the lxd.service and lxd.socket units too?

**Comment by despens** [comment] 2018-03-06 23:11
The lxd.service unit suggests that it tries to look for a container that was created and deleted before. The zfs dataset has been destroyed since then. Where would I erase the reference to that non-existing container?

```
# journalctl -n 300 _SYSTEMD_UNIT=lxd.service
Mär 06 21:03:28 eiger lxd[13011]: lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2018-03-06T21:03:28+0100
Mär 06 21:03:28 eiger lxd[13011]: lvl=warn msg="Incorrectly applied \"storage_api\" patch. Skipping storage pool initialization as it might be corrupt." t=2018-03-06T21:03:28+0100
Mär 06 21:03:28 eiger lxd[13011]: lvl=warn msg="Database already contains a valid entry for the storage pool: default." t=2018-03-06T21:03:28+0100
Mär 06 21:03:28 eiger lxd[13011]: lvl=warn msg="Storage volumes database already contains an entry for the container." t=2018-03-06T21:03:28+0100
Mär 06 21:03:28 eiger lxd[13011]: lvl=warn msg="Failed to set new ZFS mountpoint: cannot open 'EigerStorage/LXD/containers/ubuntu-16-04': dataset does not exist\n." t=2018-03-06T21:03:28+0100
Mär 06 21:03:28 eiger lxd[13011]: lvl=warn msg="Storage volumes database already contains an entry for the image." t=2018-03-06T21:03:28+0100
Mär 06 21:03:28 eiger lxd[13011]: lvl=warn msg="Failed to set new ZFS mountpoint: cannot open 'EigerStorage/LXD/images/b5f3a547289fabf26d90250605dc3067f1863ee46c802f004aa97954cc852c33': dataset does not exist\n." t=2018
Mär 06 21:03:28 eiger lxd[13011]: lvl=warn msg="Storage volumes database already contains an entry for the image." t=2018-03-06T21:03:28+0100
Mär 06 21:03:28 eiger lxd[13011]: lvl=warn msg="Failed to set new ZFS mountpoint: cannot open 'EigerStorage/LXD/images/c23b37d4885c51f3734117e37a489eec7fbb53db3702b534d956431d13d2d8fd': dataset does not exist\n." t=2018
Mär 06 21:03:28 eiger lxd[13011]: error: containers/ubuntu-16-04: Failed to set new zfs mountpoint: Failed to run: zfs set mountpoint=/var/lib/lxd/storage-pools/default/containers/ubuntu-16-04 EigerStorage/LXD/container
Mär 06 21:13:28 eiger lxd[13012]: error: LXD still not running after 600s timeout.
Mär 06 21:13:28 eiger lxd[13525]: lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2018-03-06T21:13:28+0100
Mär 06 21:13:28 eiger lxd[13525]: lvl=warn msg="Incorrectly applied \"storage_api\" patch. Skipping storage pool initialization as it might be corrupt." t=2018-03-06T21:13:28+0100
Mär 06 21:13:28 eiger lxd[13525]: lvl=warn msg="Database already contains a valid entry for the storage pool: default." t=2018-03-06T21:13:28+0100
Mär 06 21:13:28 eiger lxd[13525]: lvl=warn msg="Storage volumes database already contains an entry for the container." t=2018-03-06T21:13:28+0100
Mär 06 21:13:28 eiger lxd[13525]: lvl=warn msg="Failed to set new ZFS mountpoint: cannot open 'EigerStorage/LXD/containers/ubuntu-16-04': dataset does not exist\n." t=2018-03-06T21:13:28+0100

journalctl -n 300 _SYSTEMD_UNIT=lxd.socket
-- No entries --
```

**Comment by stgraber** [comment] 2018-03-07 07:46
Ah, okay, that'd explain it. The easiest is probably going to be to wipe /var/lib/lxd and then restart the lxd.socket and lxd.service units, that should reset everything.

**Comment by despens** [comment] 2018-03-07 20:34
Yes indeed that did the trick.
I guess the issues came from an incomplete uninstall, or the uninstall not being able to deal with LXD data leftover, although I had chosen during uninstall that the storage pool should be destroyed.

**Comment by stgraber** [comment] 2018-03-07 21:51
Yeah, purging LXD from the package manager is always a bit tricky since it may be holding a bunch of kernel mounts... With recent LXD you can delete all storage pools through `lxc storage` which usually takes care of that, but for LXC 2.0 most of that happened outside of LXD's control so there are more moving pieces and more manual work.

Anyway, sounds like there's no direct LXD problem here, it was mostly incomplete cleanup during package removal, so I guess we can close this.

**Closed by stgraber** 2018-03-07 21:51 UTC
Labels: Incomplete

**Comment by despens** [comment] 2018-03-08 14:23
Again, thank you Stéphane!
