### ISSUE TITLE
Devices with additional "/" in name are not properly added/removed

### ISSUE THREAD

**Issue by tpeeters** [lxc/lxd#2091] opened 2016-06-08 16:03 UTC
I'm running lxd (from trusty-backports) on a trusty host, and my container contains xenial.

# Required information
 * Distribution: Ubuntu
 * Distribution version: 14.04.4 LTS
 * The output of "lxc info" or if that fails:
tim@XPS-13-9350:~$ lxc info
apicompat: 0
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  driver: lxc
  driverversion: 2.0.1
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 3.19.0-59-generic
  server: lxd
  serverpid: 15758
  serverversion: 2.0.2
  storage: dir
  storageversion: ""
config: {}
public: false

# Issue description

I added several devices to my container using: http://pastebin.ubuntu.com/17119608/
After that I tried to change permissions or remove devices, see: http://pastebin.ubuntu.com/17120003/

So, I could not remove or change the permissions of some devices with more than one / in the filename. Checking inside the container, it appears that those files do not exist in /dev, but still they are listed with lxc config device list.

**Comment by tpeeters** [comment] 2016-06-08 16:09
After trying to remove the (non-existant) devices from the container, they are now missing on my host!

**Comment by tpeeters** [comment] 2016-06-08 16:15
Host reboot restored the devices on my host.
Removing the device from the container seems to work now, but it also removes it from the host.

tim@XPS-13-9350:~$ lxc config device list xenial1
/dev/video0: unix-char
dri: disk
root: disk
x11tmp: disk
/dev/dri/card0: unix-char
/dev/dri/controlD64: unix-char
/dev/fb0: unix-char
tim@XPS-13-9350:~$ lxc config device remove xenial1 /dev/dri/card0 
Device /dev/dri/card0 removed from xenial1
tim@XPS-13-9350:~$ ls -alh /dev/dri/
total 0
drwxr-xr-x   2 root root        80 jun  8 18:14 .
drwxr-xr-x  18 root root      4,2K jun  8 18:11 ..
crw-rw----   1 root video 226,  64 jun  8 18:11 controlD64
crw-rw----+  1 root video 226, 128 jun  8 18:11 renderD128

**Comment by stgraber** [comment] 2016-07-05 14:29
Looking into this now

**Comment by stgraber** [comment] 2016-07-08 18:28
I'm unable to reproduce this:
```
stgraber@dakara:~$ lxc launch ubuntu:16.04 xenial1
Creating xenial1
Starting xenial1
stgraber@dakara:~$ ls -lh /dev/dri/
total 0
crw-rw----+ 1 root video 226,   0 Jun 23 14:24 card0
crw-rw----  1 root video 226,  64 Jun 23 14:24 controlD64
crw-rw----+ 1 root video 226, 128 Jun 23 14:24 renderD128
stgraber@dakara:~$ lxc config device add xenial1 /dev/dri/card0 unix-char path=/dev/dri/card0
Device /dev/dri/card0 added to xenial1
stgraber@dakara:~$ lxc exec xenial1 -- ls -lh /dev/dri/
total 0
crw-rw---- 1 root root 226, 0 Jul  8 18:23 card0
stgraber@dakara:~$ lxc config device remove xenial1 /dev/dri/card0
Device /dev/dri/card0 removed from xenial1
stgraber@dakara:~$ lxc exec xenial1 -- ls -lh /dev/dri/
total 0
stgraber@dakara:~$ lxc config device add xenial1 /dev/dri/card0 unix-char path=/dev/dri/card0
Device /dev/dri/card0 added to xenial1
stgraber@dakara:~$ lxc config device add xenial1 /dev/dri/controlD64 unix-char path=/dev/dri/controlD64
Device /dev/dri/controlD64 added to xenial1
stgraber@dakara:~$ lxc config device add xenial1 /dev/dri/renderD128 unix-char path=/dev/dri/renderD128
Device /dev/dri/renderD128 added to xenial1
stgraber@dakara:~$ lxc config device add xenial1 /dev/video0 unix-char path=/dev/video0
Device /dev/video0 added to xenial1
stgraber@dakara:~$ lxc config device add xenial1 /dev/fb0 unix-char path=/dev/fb0
Device /dev/fb0 added to xenial1
stgraber@dakara:~$ lxc config device remove xenial1 /dev/dri/card0
Device /dev/dri/card0 removed from xenial1
stgraber@dakara:~$ lxc config device add xenial1 /dev/dri/card0 unix-char path=/dev/dri/card0 gid=44
Device /dev/dri/card0 added to xenial1
stgraber@dakara:~$ lxc config device list xenial1
root: disk
/dev/dri/card0: unix-char
/dev/dri/controlD64: unix-char
/dev/dri/renderD128: unix-char
/dev/fb0: unix-char
/dev/video0: unix-char
stgraber@dakara:~$ lxc config device remove xenial1 /dev/fb0
Device /dev/fb0 removed from xenial1
stgraber@dakara:~$ lxc config device add xenial1 /dev/fb0 unix-char path=/dev/fb0 gid=44
Device /dev/fb0 added to xenial1
stgraber@dakara:~$ lxc exec xenial1 -- ls -lh /dev/dri/
total 0
crw-rw---- 1 root video 226,   0 Jul  8 18:26 card0
crw-rw---- 1 root root  226,  64 Jul  8 18:26 controlD64
crw-rw---- 1 root root  226, 128 Jul  8 18:26 renderD128
```

**Comment by stgraber** [comment] 2016-08-26 21:18
So this has been over a month without added information on the environment which would let me reproduce the issue and see what may have been going on for the reporter.

I'm closing this issue for now. If you find a way for me to reproduce it, I'll re-open and look into it.

**Closed by stgraber** 2016-08-26 21:18 UTC
Labels: Incomplete
