### ISSUE TITLE
[snap/3.21] bogus GPT partition info

### ISSUE THREAD

**Issue by simondeziel** [lxc/lxd#6929] opened 2020-02-24 16:19 UTC
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04.4
 * The output of "lxc info" or if that fails:

```
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  certificate_fingerprint: fingerprint
  driver: lxc
  driver_version: 3.2.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.3.0-40-generic
  lxc_features:
    cgroup2: "false"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    seccomp_notify: "true"
  project: default
  server: lxd
  server_clustered: false
  server_name: simon-lemur
  server_pid: 12273
  server_version: "3.21"
  storage: zfs
  storage_version: 0.8.1-1ubuntu14.3
```

# Issue description

Creating a VM with ```lxc launch ubuntu:18.04 v1 --vm --profile default --profile vm``` results in the following kernel logs:

```
kernel: GPT:Primary header thinks Alt. header is not at the end of the disk.
kernel: GPT:4612095 != 19531247
kernel: GPT:Alternate GPT header not at the end of the disk.
kernel: GPT:4612095 != 19531247
kernel: GPT: Use GNU Parted to correct GPT errors.
kernel:  zd112: p1 p14 p15
```

Aside from those warnings, the VM seems to behave normally but I didn't test it extensively.

**Comment by stgraber** [comment] 2020-02-24 16:23
Hmm, would be interesting to know if it's an issue in the image itself or in the resized volume only.

@tomponline @monstermunchkin can you sort this out quickly please?

**Comment by tomponline** [comment] 2020-02-24 16:28
@stgraber @simondeziel I've just tried this now from master on ubuntu:18.04 and dont see the kernel messages and the VM boots fine. What backend storage driver are you using? I'll test inside a snap version too to check its not snap specific.

**Comment by simondeziel** [comment] 2020-02-24 16:36
@tomponline I'm using ZFS and used this image:

```
|                | 8bac6546bbc5 | no     | ubuntu 18.04 LTS amd64 (release) (20200218) | x86_64       | VIRTUAL-MACHINE | 329.06MB | Feb 23, 2020 at 9:34pm (UTC) |
```

**Comment by simondeziel** [comment] 2020-02-24 16:38
> Hmm, would be interesting to know if it's an issue in the image itself or in the resized volume only.

The resize theory makes a lot of sense as the end of the disk moves so it the alt GPT table needs to be moved as well.

**Comment by simondeziel** [comment] 2020-02-24 16:41
@tomponline the image I used is the latest one:

```
$ lxc image info 8bac6546bbc5
Fingerprint: 8bac6546bbc5cfbe5c490f2c991cff8cff1428b57fb9a74d33a64cb6dff66601
Size: 329.06MB
Architecture: x86_64
Type: virtual-machine
Public: no
Timestamps:
    Created: 2020/02/18 00:00 UTC
    Uploaded: 2020/02/23 21:34 UTC
    Expires: 2023/04/26 00:00 UTC
    Last used: 2020/02/24 16:18 UTC
Properties:
    label: release
    os: ubuntu
    release: bionic
    serial: 20200218
    type: disk1.img
    version: 18.04
    architecture: amd64
    description: ubuntu 18.04 LTS amd64 (release) (20200218)
Aliases:
Cached: yes
Auto update: enabled
Source:
    Server: https://cloud-images.ubuntu.com/releases
    Protocol: simplestreams
    Alias: 18.04
Profiles:
    - default
```

**Comment by tomponline** [comment] 2020-02-24 16:42
Recreated issue on zfs on master, it doesn't occur on lvm. It doesn't prevent boot. Will look into how it can be fixed for zfs.

**Comment by tomponline** [comment] 2020-02-24 16:54
The error only occurs when the VM is created, it doesn't occur on boot.

**Comment by simondeziel** [comment] 2020-02-24 17:07
Indeed, the error only occurs during VM creation. I tried resizing the rootfs by editing the config and it didn't result in this error showing again.

**Comment by tomponline** [comment] 2020-02-24 17:08
I'm thinking there might be something in the zfs driver that is causing the host OS to try and mount the VM's partition during initial creation (which shouldn't happen because it is a partitioned block device).

**Comment by simondeziel** [comment] 2020-02-24 17:14
I think you are onto something as simply cloning the $vm.block ZVol result in this being logged by the kernel:

```
kernel:  zd128: p1 p14 p15
```

I did this with:

```
zfs snapshot data/lxd/virtual-machines/v1.block@test
zfs clone data/lxd/virtual-machines/v1.block@test data/lxd/virtual-machines/v2.block
```

So mapping parts boundaries seems to occur naturally.

**Comment by tomponline** [comment] 2020-02-24 17:18
This seems related: https://bugs.launchpad.net/cirros/+bug/1605588

@stgraber is this outside of the scope of LXD to modify the volume's partition table (like we don't when resizing the volume) as we don't know how it is constructed? In the case of cloud-init I understand that the VM will resize its own partitions on first boot.

**Comment by tomponline** [comment] 2020-02-24 17:28
More info (using LVM which has same issue but doesn't generate the warnings) as I couldn't figure out where the ZFS devices were:

Parted warns of issue when trying to print partition table, lets ignore:
```
lxc init ubuntu:18.04 v1 --vm -p vm -s lvm
Creating v1
user@user-MS-7821:~/go/src/github.com/lxc/lxd$ sudo parted /dev/lvm/virtual-machines_test_v1.block 
GNU Parted 3.2
Using /dev/dm-45
Welcome to GNU Parted! Type 'help' to view a list of commands.
(parted) p                                                                
Warning: Not all of the space available to /dev/dm-45 appears to be used, you can fix the GPT to use all of the space (an extra 14925824 blocks) or continue with the current setting? 
Fix/Ignore? i                                                             
Model: Linux device-mapper (thin) (dm)
Disk /dev/dm-45: 10.0GB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags: 

Number  Start   End     Size    File system  Name  Flags
14      1049kB  5243kB  4194kB                     bios_grub
15      5243kB  116MB   111MB   fat32              boot, esp
 1      116MB   2361MB  2245MB  ext4
```

Using `sgparted` with the `--move-second-header` flag (
```
sudo sgdisk /dev/lvm/virtual-machines_test_v1.block --move-second-header
Warning: The kernel is still using the old partition table.
The new table will be used at the next reboot or after you
run partprobe(8) or kpartx(8)
The operation has completed successfully.
```

No error second time running parted:
```
sudo parted /dev/lvm/virtual-machines_test_v1.block 
GNU Parted 3.2
Using /dev/dm-45
Welcome to GNU Parted! Type 'help' to view a list of commands.
(parted) p                                                                
Model: Linux device-mapper (thin) (dm)
Disk /dev/dm-45: 10.0GB
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags: 

Number  Start   End     Size    File system  Name  Flags
14      1049kB  5243kB  4194kB                     bios_grub
15      5243kB  116MB   111MB   fat32              boot, esp
 1      116MB   2361MB  2245MB  ext4
```

@stgraber so I suppose we could runs this from LXD, but do we know that the partition in the images will also be GPT?

**Comment by stgraber** [comment] 2020-02-24 18:52
We don't. I'm also not sure why this is a problem here and not with the stock Ubuntu images. I wonder if they have a different GPT setup so there's no error is the secondary table isn't right at the end.

**Comment by stgraber** [comment] 2020-02-24 18:53
What's our default volume size again? 10GB?

**Comment by tomponline** [comment] 2020-02-24 18:57
> We don't. I'm also not sure why this is a problem here and not with the stock Ubuntu images. I wonder if they have a different GPT setup so there's no error is the secondary table isn't right at the end.

These are the stock ubuntu images arent they?

**Comment by tomponline** [comment] 2020-02-24 18:59
> What's our default volume size again? 10GB?

Thats correct. It makes sense that the gpt 2nd header isnt moved as we just unpack the image onto the raw device and dont manipulate the partition table. However we only see the warning message with zfs, even though it exists with that and lvm.

**Comment by tomponline** [comment] 2020-02-24 19:01
@stgraber perhaps we can detect a gpt table in the image and only move it if needed.

**Comment by stgraber** [comment] 2020-02-24 23:12
Yeah, that may be what we have to do... I was hoping the issue was just with `images:ubuntu/bionic` and not `ubuntu:18.04`, but reading the report again, it does affect the cloud images...

It's indeed odd that it would affect ZFS but not LVM, do you think it's because of block size differences or something like that?

**Comment by tomponline** [comment] 2020-02-25 09:07
@stgraber so there's a couple of things going on here:

1. The issue of the kernel messages is only occurring with ZFS, and only at VM create time. The messages I have seen are listing the partitions in the image, e.g. `kernel:  zd112: p1 p14 p15` which suggests something in the ZFS driver is attempting to probe the image for its partition table, triggering the messages. Perhaps there is a tweak we can make to the LXD ZFS driver to set `volmode=none` sooner.

2. The GPT header not being at the end of the driver issue is affecting all of the storage drivers (I've tested ZFS, LVM, DIR at least), its just the kernel doesn't report it because there isn't any partition probing going on with the others.

I don't believe the issue is related to block sizes, instead, apparently its occurring because the GPT standard expects the alternative header to be at the end of the disk. When we unpack the cloud image onto a device that is larger than the original image then naturally the alternative header in the image is no longer at the end of the disk. There's some more info here in relation to RAID devices: https://lore.kernel.org/patchwork/patch/726024/

So if we can detect a GPT header at the start of the disk, we can run that `sgdisk --move-second-header` command during initial creation and any resize operation.

**Comment by tomponline** [comment] 2020-02-25 09:16
@stgraber I've also noticed than when cloud-init inside the VM resizes the partition to use the remaining space in the disk image, it also moves the GPT alternative header to end of the disk, so VMs using cloud-init appear to be fixed on first boot.

**Comment by tomponline** [comment] 2020-02-25 09:25
@stgraber according to the `sgdisk` manual if we try and run `sgdisk --move-second-header` on a non-GPT disk, it will detect this and exit with status code `3`. I've confirmed this is the case, so we could just run this command on all VM disk images created after unpack/resize.

**Comment by stgraber** [comment] 2020-02-25 11:22
Sounds good. For ZFS, we should check the clone call and make sure we pass it volmode=none instead of doing on a later step

**Comment by tomponline** [comment] 2020-02-25 14:30
@stgraber so this is interesting, clone with the volmode option seems to apply but actually doesn't:

Image source volume volmode=dev:
```
zfs get volmode default/images/8bac6546bbc5cfbe5c490f2c991cff8cff1428b57fb9a74d33a64cb6dff66601.block
NAME                                                                                   PROPERTY  VALUE    SOURCE
default/images/8bac6546bbc5cfbe5c490f2c991cff8cff1428b57fb9a74d33a64cb6dff66601.block  volmode   dev      local
```

Image source read only snapshot (volmode not relevant):

```
zfs get volmode default/images/8bac6546bbc5cfbe5c490f2c991cff8cff1428b57fb9a74d33a64cb6dff66601.block@readonly
NAME                                                                                            PROPERTY  VALUE    SOURCE
default/images/8bac6546bbc5cfbe5c490f2c991cff8cff1428b57fb9a74d33a64cb6dff66601.block@readonly  volmode   -        -
```

Clone from snapshot passing volmode at time of clone:

```
zfs clone -o  volmode=dev  default/images/8bac6546bbc5cfbe5c490f2c991cff8cff1428b57fb9a74d33a64cb6dff66601.block@readonly default/virtual-machines/test_v2.block
```

Confirm volmode=dev is set on new volume, yes it is, great.
```
zfs get volmode default/virtual-machines/test_v2.block
NAME                                    PROPERTY  VALUE    SOURCE
default/virtual-machines/test_v2.block  volmode   dev      local
```

Check there are no partition devices in /dev/zvol/:
Hrm that's not right...

```
ls -l /dev/zvol/default/virtual-machines/
total 0
lrwxrwxrwx 1 root root 13 Feb 25 14:27 test_v2.block -> ../../../zd32
lrwxrwxrwx 1 root root 15 Feb 25 14:27 test_v2.block-part1 -> ../../../zd32p1
lrwxrwxrwx 1 root root 16 Feb 25 14:27 test_v2.block-part14 -> ../../../zd32p14
lrwxrwxrwx 1 root root 16 Feb 25 14:27 test_v2.block-part15 -> ../../../zd32p15
```

Set volmode=dev again on volume (remember apparently its already set above):

```
zfs set volmode=dev default/virtual-machines/test_v2.block
```

Check again for devices:

```
ls -l /dev/zvol/default/virtual-machines/
total 0
lrwxrwxrwx 1 root root 13 Feb 25 14:27 test_v2.block -> ../../../zd32
```

Thats more like it! So this looks like a bug in ZFS (on 18.04 at least, but running the HWE kernel).

**Comment by tomponline** [comment] 2020-02-25 16:43
So there's defo some weird behaviour here:

Test 1: Parent volmode=none, clone volmode=dev: Works as expected, only disk device appears.

```
root@user-MS-7821:/dev/zvol/default# zfs set volmode=none default/virtual-machines
root@user-MS-7821:/dev/zvol/default# zfs clone -o  volmode=dev  default/images/8bac6546bbc5cfbe5c490f2c991cff8cff1428b57fb9a74d33a64cb6dff66601.block@readonly default/virtual-machines/test_v2.block
root@user-MS-7821:/dev/zvol/default# ls -l /dev/zvol/default/virtual-machines/
total 0
lrwxrwxrwx 1 root root 12 Feb 25 16:38 test_v2.block -> ../../../zd0
```

Test 2: Parent volmode=default, clone volmode=dev: Doesn't work as expected, partition devices appear.

```
root@user-MS-7821:/dev/zvol/default# zfs set volmode=default default/virtual-machines
root@user-MS-7821:/dev/zvol/default# zfs clone -o  volmode=dev  default/images/8bac6546bbc5cfbe5c490f2c991cff8cff1428b57fb9a74d33a64cb6dff66601.block@readonly default/virtual-machines/test_v2.block
root@user-MS-7821:/dev/zvol/default# ls -l /dev/zvol/default/virtual-machines/
total 0
lrwxrwxrwx 1 root root 12 Feb 25 16:40 test_v2.block -> ../../../zd0
lrwxrwxrwx 1 root root 14 Feb 25 16:40 test_v2.block-part1 -> ../../../zd0p1
lrwxrwxrwx 1 root root 15 Feb 25 16:40 test_v2.block-part14 -> ../../../zd0p14
lrwxrwxrwx 1 root root 15 Feb 25 16:40 test_v2.block-part15 -> ../../../zd0p15
```

But it gets weirder, if I set the parent volmode now to something else, e.g. "none", then it seems to notice the volmode=dev on the volume and applies it.

```
root@user-MS-7821:/dev/zvol/default# zfs set volmode=none default/virtual-machines
root@user-MS-7821:/dev/zvol/default# ls -l /dev/zvol/default/virtual-machines/
total 0
lrwxrwxrwx 1 root root 12 Feb 25 16:41 test_v2.block -> ../../../zd0
```

The good news is that it does seem to initially inherit the volmode of the parent and only later applies the clone volmode option if different.

Now when we clone, we get no devices as the parent volmode=none is inherited.

```
root@user-MS-7821:/dev/zvol/default# zfs set volmode=none default/virtual-machines
root@user-MS-7821:/dev/zvol/default# zfs clone -o  volmode=none  default/images/8bac6546bbc5cfbe5c490f2c991cff8cff1428b57fb9a74d33a64cb6dff66601.block@readonly default/virtual-machines/test_v2.block
root@user-MS-7821:/dev/zvol/default# ls -l /dev/zvol/default/virtual-machines/
ls: cannot access '/dev/zvol/default/virtual-machines/': No such file or directory
```

And later changing the parent volmode doesn't affect the cloned volume:

```
root@user-MS-7821:/dev/zvol/default# zfs set volmode=dev default/virtual-machines
root@user-MS-7821:/dev/zvol/default# ls -l /dev/zvol/default/virtual-machines/
ls: cannot access '/dev/zvol/default/virtual-machines/': No such file or directory
```

**Comment by tomponline** [comment] 2020-02-27 09:27
@simondeziel The PRs https://github.com/lxc/lxd/pull/6933 and https://github.com/lxc/lxd/pull/6932 should fix this issue for all storage drivers except Ceph.

The issue was two-fold:
1. There was a genuine issue with the GPT alternative header not being moved to the end of the disk (that the GPt standard mandates) when we unpack VM images onto storage devices that are larger than the source image.

2. The host kernel was incorrectly probing the VM's partition table (causing the GPT warnings to be triggered) due to what looks like a bug in ZFS that causes the `volmode` option specified during zfs clone to be ignored temporarily. We have worked around this by setting the `volmode=none` to the parent which ZFS does appear to correctly inherit when doing a clone.

**Closed** 2020-02-27 09:32 UTC
Labels: Bug

**Comment by simondeziel** [comment] 2020-02-27 15:25
@tomponline thanks for the quick turnaround!

**Comment by sbromberger** [comment] 2020-09-21 15:16
Sorry to resurrect this issue, but I've just come across similar messages in my new lxc/lxd install (snap version 4.0.3 on Ubuntu 20.04):
```
[Mon Sep 21 02:58:06 2020] GPT:Primary header thinks Alt. header is not at the end of the disk.
[Mon Sep 21 02:58:06 2020] GPT:8388607 != 19531247
[Mon Sep 21 02:58:06 2020] GPT:Alternate GPT header not at the end of the disk.
[Mon Sep 21 02:58:06 2020] GPT:8388607 != 19531247
[Mon Sep 21 02:58:06 2020] GPT: Use GNU Parted to correct GPT errors.
[Mon Sep 21 02:58:06 2020]  zd16: p1 p2
[Mon Sep 21 02:58:07 2020]  zd16: p1 p2
```

I'm using a zfs loop (.img) file on two containers and a VM:
```
+seth@elemental:~ $ lxc storage list
+---------+-------------+--------+--------------------------------------------+---------+
|  NAME   | DESCRIPTION | DRIVER |                   SOURCE                   | USED BY |
+---------+-------------+--------+--------------------------------------------+---------+
| default |             | zfs    | /var/snap/lxd/common/lxd/disks/default.img | 8       |
+---------+-------------+--------+--------------------------------------------+---------+
+seth@elemental:~ $ lxc storage show default
config:
  size: 300GB
  source: /var/snap/lxd/common/lxd/disks/default.img
  zfs.pool_name: default
description: ""
name: default
driver: zfs
used_by:
- /1.0/images/b1900a3455dd9ce8d2a7e77f755d72974803f2d7dd0f06a27724a1aa847a9a24
- /1.0/images/d54ab845b6d21563e7f71c8714990aa9fc42e86f7ae8be2af97bcc8da93ea868
- /1.0/instances/helium
- /1.0/instances/hydrogen
- /1.0/instances/lithium
- /1.0/profiles/default
- /1.0/profiles/vlan1
- /1.0/profiles/vlan2
status: Created
locations:
- none
```

What other information can I include that will be helpful?

**Comment by sbromberger** [comment] 2020-09-21 18:24
Per discussion with @tomponline , here's some possibly relevant output:
```
root@elemental:/home/seth# lxc config show helium --expanded
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Ubuntu focal amd64 (20200920_07:42)
  image.os: Ubuntu
  image.release: focal
  image.serial: "20200920_07:42"
  image.type: disk-kvm.img
  volatile.base_image: 533ebfff30c74253e0c544a452c77d11dc1452d99e3e6cc4ecb5df3f25e6c71a
  volatile.eth0.host_name: tap1553bc4e
  volatile.eth0.hwaddr: 00:16:3e:2b:6a:d6
  volatile.last_state.power: RUNNING
  volatile.vm.uuid: 50abf35f-129f-4d47-bb2b-38f29907c05a
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br2
    type: nic
  root:
    path: /
    pool: default
    size: 50GB
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

Note that I set the root size to 50GB from its original (4GB) and then used `growpart` and `resize2fs` within the VM to expand it. I wonder if that had anything to do with this issue (though it seems to have worked properly).

**Comment by tomponline** [comment] 2020-09-22 09:07
@sbromberger I've tried reproducing this using the master branch on a ZFS storage pool backed by a loopback file and have been unable, here are the steps I took:

```bash
lxc launch images:ubuntu/20.04 v1 --vm
lxc shell v1
root@v1:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            478M     0  478M   0% /dev
tmpfs            98M  688K   98M   1% /run
/dev/sda2       3.8G  731M  3.0G  20% /

poweroff
```

Now resize:

```
lxc config device override v1 root size=20GB
lxc start v1
lxc shell v1
apt install cloud-guest-utils
growpart /dev/sda 2
resize2fs /dev/sda2
df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            478M     0  478M   0% /dev
tmpfs            98M  684K   98M   1% /run
/dev/sda2        18G  802M   18G   5% /

poweroff
```

Please can you try to post a set of reproducer commands like the above.

**Comment by tomponline** [comment] 2020-09-22 09:09
@sbromberger also please can you check your logs for this line:

"
Skipped moving GPT alternative header to end of disk as sgdisk command not found
"

**Comment by sbromberger** [comment] 2020-09-23 06:56
I decided to do a complete wipe/reinstall of the machine. I haven't seen the issue crop back up so far. Thanks.
