### ISSUE TITLE
Fail to start first container

### ISSUE THREAD

**Issue by IcarusWizard** [lxc/lxd#6262] opened 2019-09-30 17:13 UTC
# Required information
* Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
```
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIICMDCCAbagAwIBAgIQezjmdunLDwA0Sp2sZRXeCDAKBggqhkjOPQQDAzA7MRww
    GgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRswGQYDVQQDDBJyb290QGljYXJ1
    cy1YNTUwSkswHhcNMTkwOTMwMTYyODIwWhcNMjkwOTI3MTYyODIwWjA7MRwwGgYD
    VQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRswGQYDVQQDDBJyb290QGljYXJ1cy1Y
    NTUwSkswdjAQBgcqhkjOPQIBBgUrgQQAIgNiAAS/u+pVjMcD7lt0kiyk39ozKsr1
    BeEE5d02dakmye/BQdR630dvSsB3rQijzGmCoxf4SNERepa1KBHxkjyKL7jpfCkL
    jCXBJYgfqc/oORtB7P05AzuXkjQ4azFTe34EmjqjfzB9MA4GA1UdDwEB/wQEAwIF
    oDATBgNVHSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMEgGA1UdEQRBMD+C
    DWljYXJ1cy1YNTUwSkuHBKwUJCOHECABAlD+AQEwFAQCZHN2ebKHECABAlD+AQEw
    9r5NoqNQBe6HBAoOAAEwCgYIKoZIzj0EAwMDaAAwZQIxAKQOqgqMHw4d5Y01Hxia
    ah/D5VB678MUQTuOXA9OpxWBrrUOD+k5jWtWXn1miulTiAIwbRJtfwCeGNz7VhPm
    JAFshK3NDcV/t/NGEtJBCr+Be4Z/tu8B0rIDACJZr1MDxV3S
    -----END CERTIFICATE-----
  certificate_fingerprint: 62f29209182316ed1ad6678339671991f74276988a81c0388a6c7b641518273d
  driver: lxc
  driver_version: 3.2.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "false"
    seccomp_listener: "false"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 4.18.0-21-generic
  lxc_features:
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    seccomp_notify: "true"
  project: default
  server: lxd
  server_clustered: false
  server_name: icarus-X550JK
  server_pid: 3638
  server_version: "3.17"
  storage: zfs
  storage_version: 0.7.9-3ubuntu6
```
   * Kernel version: 4.18.0-21-generic
   * LXC version: 3.17
   * LXD version: 3.17
   * Storage backend in use: zfs

# Issue Description 
I was follow an instruction to build a template image. But I fail to start it when I call `lxc start`

# Steps to reproduce

 1. `sudo snap install lxd`
 2. `sudo lxd init`
 3. `sudo lxc remote add tuna-images https://mirrors.tuna.tsinghua.edu.cn/lxc-images/ --protocol=simplestreams --public`
4. `sudo lxc image copy tuna-images:ubuntu/16.04 local: --alias ubuntu/16.04 --copy-aliases --public`
5. `sudo lxc profile set default nvidia.runtime true`
6. `sudo lxc profile device add default gpu gpu id=0`
7. `sudo lxc init ubuntu/16.04 template -p default`
8. `sudo lxc start template` then it shows:
```
Error: Failed to run: /snap/lxd/current/bin/lxd forkstart template /var/snap/lxd/common/lxd/containers /var/snap/lxd/common/lxd/logs/template/lxc.conf: 
Try `lxc info --show-log template` for more info
```

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
```
Name: template
Location: none
Remote: unix://
Architecture: x86_64
Created: 2019/09/30 16:34 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:

lxc template 20190930165510.723 ERROR    conf - conf.c:run_buffer:352 - Script exited with status 1
lxc template 20190930165510.723 ERROR    conf - conf.c:lxc_setup:3653 - Failed to run mount hooks
lxc template 20190930165510.723 ERROR    start - start.c:do_start:1321 - Failed to setup container "template"
lxc template 20190930165510.723 ERROR    sync - sync.c:__sync_wait:62 - An error occurred in another process (expected sequence number 5)
lxc template 20190930165510.723 WARN     network - network.c:lxc_delete_network_priv:3377 - Failed to rename interface with index 8 from "eth0" to its initial name "veth833609a6"
lxc template 20190930165510.723 ERROR    lxccontainer - lxccontainer.c:wait_on_daemonized_start:873 - Received container state "ABORTING" instead of "RUNNING"
lxc template 20190930165510.723 ERROR    start - start.c:__lxc_start:2039 - Failed to spawn container "template"
lxc 20190930165510.854 WARN     commands - commands.c:lxc_cmd_rsp_recv:135 - Connection reset by peer - Failed to receive response for command "get_state"
```
 - [ ] Container configuration (`lxc config show NAME --expanded`)
```
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Ubuntu xenial amd64 (20190929_07:42)
  image.os: Ubuntu
  image.release: xenial
  image.serial: "20190929_07:42"
  image.type: squashfs
  nvidia.runtime: "true"
  volatile.base_image: 2b9288c6403fab1ba9baf6be6f5b506e69c930f1f6950cd6151ff773135c1cea
  volatile.eth0.hwaddr: 00:16:3e:a8:df:27
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: STOPPED
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  gpu:
    id: "0"
    type: gpu
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment] 2019-09-30 17:24
Can you run:
```
sudo lxc profile set default nvidia.runtime false
sudo lxc start template
```

See if it's the NVIDIA integration that's the problem?

**Comment by IcarusWizard** [comment] 2019-10-01 01:22
Yes, it solve the problem. Thanks!   
But I really need to use GPU inside my container, do you have any suggestion about how I can do it?
The nvidia dirver and cuda work perfectly on my local machine and I have also install nvidia-container-runtime through the instruction [here](https://github.com/NVIDIA/nvidia-container-runtime). I don't see any reasons that it cannot work in the container.

**Comment by stgraber** [comment] 2019-10-01 01:36
Try running this as root:
```
NVC_DEBUG_FILE=/var/snap/lxd/common/nvidia.log nsenter -t $(pgrep daemon.start) -m -- env PATH=/snap/lxd/current/bin/:${PATH} LD_LIBRARY_PATH=/snap/lxd/current/lib/ nvidia-container-cli info --csv
```

Then post both the output of that command and the content of `/var/snap/lxd/common/nvidia.log`

**Comment by IcarusWizard** [comment] 2019-10-01 01:45
The above command outputs 
```
nvidia-container-cli.real: initialization error: cuda error: unknown error
```
And in `/var/snap/lxd/common/nvidia.log`, it says:
```
-- WARNING, the following logs are for debugging purposes only --

I1001 01:41:26.764538 29386 nvc.c:281] initializing library context (version=1.0.6, build=5823754b8577d16fabf25a6ef6a1d58f7ff1e5dd)
I1001 01:41:26.764641 29386 nvc.c:255] using root /var/lib/snapd/hostfs/
I1001 01:41:26.764658 29386 nvc.c:256] using ldcache /etc/ld.so.cache
I1001 01:41:26.764673 29386 nvc.c:257] using unprivileged user 65534:65534
I1001 01:41:26.764913 29387 driver.c:133] starting driver service
I1001 01:41:26.773936 29386 driver.c:233] driver service terminated with signal 15
```
It seems the problem is caused by nvidia-container-cli?

**Comment by stgraber** [comment] 2019-10-01 01:49
Yeah, it doesn't appear to be happy with your system's libraries somehow.

**Comment by stgraber** [comment] 2019-10-01 01:50
What does:
 - dpkg -l | grep nvidia
 - dpkg -l | grep cuda

Show on your system?

**Comment by IcarusWizard** [comment] 2019-10-01 02:00
* `dpkg -l | grep nvidia`
```
ii  libnvidia-compute-410:amd64                     410.48-0ubuntu1                              amd64        NVIDIA libcompute package
ii  libnvidia-container-dev:amd64                   1.0.4-1                                      amd64        NVIDIA container runtime library (development files)
ii  libnvidia-container-tools                       1.0.4-1                                      amd64        NVIDIA container runtime library (command-line tools)
ii  libnvidia-container1:amd64                      1.0.4-1                                      amd64        NVIDIA container runtime library
ii  nvidia-container-runtime                        3.1.4-1                                      amd64        NVIDIA container runtime
ii  nvidia-container-toolkit                        1.0.5-1                                      amd64        NVIDIA container runtime hook
```
* `dpkg -l | grep cuda`
```
rc  cuda-cublas-10-0                                10.0.130-1                                   amd64        CUBLAS native runtime libraries
rc  cuda-cudart-10-0                                10.0.130-1                                   amd64        CUDA Runtime native Libraries
rc  cuda-cudart-dev-10-0                            10.0.130-1                                   amd64        CUDA Runtime native dev links, headers
rc  cuda-cufft-10-0                                 10.0.130-1                                   amd64        CUFFT native runtime libraries
rc  cuda-cupti-10-0                                 10.0.130-1                                   amd64        CUDA profiling tools interface.
rc  cuda-curand-10-0                                10.0.130-1                                   amd64        CURAND native runtime libraries
rc  cuda-cusolver-10-0                              10.0.130-1                                   amd64        CUDA solver native runtime libraries
rc  cuda-cusparse-10-0                              10.0.130-1                                   amd64        CUSPARSE native runtime libraries
rc  cuda-npp-10-0                                   10.0.130-1                                   amd64        NPP native runtime libraries
rc  cuda-nsight-compute-10-0                        10.0.130-1                                   amd64        NVIDIA Nsight Compute
rc  cuda-nvcc-10-0                                  10.0.130-1                                   amd64        CUDA nvcc
rc  cuda-nvgraph-10-0                               10.0.130-1                                   amd64        NVGRAPH native runtime libraries
rc  cuda-nvjpeg-10-0                                10.0.130-1                                   amd64        NVJPEG native runtime libraries
rc  cuda-nvprof-10-0                                10.0.130-1                                   amd64        CUDA Profiler tools
rc  cuda-nvrtc-10-0                                 10.0.130-1                                   amd64        NVRTC native runtime libraries
rc  cuda-nvtx-10-0                                  10.0.130-1                                   amd64        NVIDIA Tools Extension
ii  cuda-repo-ubuntu1804-10-0-local-10.0.130-410.48 1.0-1                                        amd64        cuda repository configuration files
rc  cuda-toolkit-10-0                               10.0.130-1                                   amd64        CUDA Toolkit 10.0 meta-package
rc  cuda-visual-tools-10-0                          10.0.130-1                                   amd64        CUDA visual tools
ii  libcudnn7                                       7.6.0.64-1+cuda10.0                          amd64        cuDNN runtime libraries
ii  libcudnn7-dev                                   7.6.0.64-1+cuda10.0                          amd64        cuDNN development libraries and headers
ii  libcudnn7-doc                                   7.6.0.64-1+cuda10.0                          amd64        cuDNN documents and samples
```
* nvidia-smi
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.26       Driver Version: 430.26       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 850M    Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   52C    P5    N/A /  N/A |    153MiB /  2004MiB |      8%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      2884      G   /usr/lib/xorg/Xorg                            72MiB |
|    0      3025      G   /usr/bin/gnome-shell                          79MiB |
+-----------------------------------------------------------------------------+
```
I think it is probably because I have manually update the nvidia driver through a runfile.

**Comment by stgraber** [comment] 2019-10-01 02:14
Yeah, that's likely the issue because I'm running Ubuntu 18.04 with the packaged nvidia 430 drivers and it's working fine here.

The packages I have installed are:
```
root@vm10:~# dpkg -l | grep nvidia
ii  libnvidia-cfg1-430:amd64              430.26-0ubuntu0.18.04.2           amd64        NVIDIA binary OpenGL/GLX configuration library
ii  libnvidia-compute-430:amd64           430.26-0ubuntu0.18.04.2           amd64        NVIDIA libcompute package
ii  nvidia-compute-utils-430              430.26-0ubuntu0.18.04.2           amd64        NVIDIA compute utilities
ii  nvidia-dkms-430                       430.26-0ubuntu0.18.04.2           amd64        NVIDIA DKMS package
ii  nvidia-headless-no-dkms-430           430.26-0ubuntu0.18.04.2           amd64        NVIDIA headless metapackage - no DKMS
ii  nvidia-kernel-common-430              430.26-0ubuntu0.18.04.2           amd64        Shared files used with the kernel module
ii  nvidia-kernel-source-430              430.26-0ubuntu0.18.04.2           amd64        NVIDIA kernel source package
ii  nvidia-utils-430                      430.26-0ubuntu0.18.04.2           amd64        NVIDIA driver support binaries
root@vm10:~# 
```

**Comment by stgraber** [comment] 2019-10-01 02:15
Tentatively closing the issue as this appears caused by the use of out of distro NVIDIA binaries which are confusing nvidia-container (unable to find cuda). Installing the distribution packages of the same 430 driver will hopefully be enough to fix things.

**Closed by stgraber** 2019-10-01 02:15 UTC
Labels: Incomplete

**Comment by IcarusWizard** [comment] 2019-10-01 03:04
Hi, I reinstall the driver through apt. Now, it can correctly start, but in the container, when I call `nvidia-smi`, it says `No devices were found`.
My default setting is 
```
config:
  nvidia.runtime: "true"
description: Default LXD profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  gpu:
    id: "0"
    type: gpu
  root:
    path: /
    pool: default
    type: disk
name: default
used_by:
- /1.0/containers/template
```
Do I need to re-config something to make it work?

**Comment by stgraber** [comment] 2019-10-01 03:14
Can you show `lxc info --resources`?

My guess is that card id 0 isn't your NVIDIA GPU.

**Comment by IcarusWizard** [comment] 2019-10-01 03:17
```
CPU (x86_64):
  Vendor: GenuineIntel
  Name: Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
  Caches:
    - Level 1 (type: Data): 33kB
    - Level 1 (type: Instruction): 33kB
    - Level 2 (type: Unified): 262kB
    - Level 3 (type: Unified): 6MB
  Cores:
    - Core 0
      Frequency: 2266Mhz
      NUMA node: 0
      Threads:
        - 0 (id: 0, online: true)
        - 1 (id: 4, online: true)
    - Core 1
      Frequency: 2291Mhz
      NUMA node: 0
      Threads:
        - 0 (id: 1, online: true)
        - 1 (id: 5, online: true)
    - Core 2
      Frequency: 2245Mhz
      NUMA node: 0
      Threads:
        - 0 (id: 2, online: true)
        - 1 (id: 6, online: true)
    - Core 3
      Frequency: 2287Mhz
      NUMA node: 0
      Threads:
        - 0 (id: 3, online: true)
        - 1 (id: 7, online: true)
  Frequency: 2272Mhz (min: 800Mhz, max: 3500Mhz)

Memory:
  Free: 9.09GB
  Used: 3.37GB
  Total: 12.47GB

GPUs:
  Card 0:
    NUMA node: 0
    Vendor: Intel Corporation (8086)
    Product: 4th Gen Core Processor Integrated Graphics Controller (0416)
    PCI address: 0000:00:02.0
    Driver: i915 (4.18.0-21-generic)
    DRM:
      ID: 0
      Card: card0 (226:0)
      Control: controlD64 (226:0)
      Render: renderD128 (226:128)
  Card 1:
    NUMA node: 0
    Vendor: NVIDIA Corporation (10de)
    Product: GM107M [GeForce GTX 850M] (1391)
    PCI address: 0000:01:00.0
    Driver: nvidia (430.26)
    DRM:
      ID: 1
      Card: card1 (226:1)
      Render: renderD129 (226:129)
    NVIDIA information:
      Architecture: 5.0
      Brand: GeForce
      Model: GeForce GTX 850M
      CUDA Version: 10.2
      NVRM Version: 430.26
      UUID: GPU-8bdc6f00-e59d-4574-19e1-8f6ba63004e1

NICs:
  Card 0:
    NUMA node: 0
    Vendor: Realtek Semiconductor Co., Ltd. (10ec)
    Product: RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (8168)
    PCI address: 0000:04:00.1
    Driver: r8169 (2.3LK-NAPI)
    Ports:
      - Port 0 (ethernet)
        ID: enp4s0f1
        Address: 54:a0:50:04:ab:64
        Supported modes: 10baseT/Half, 10baseT/Full, 100baseT/Half, 100baseT/Full, 1000baseT/Half, 1000baseT/Full
        Supported ports: twisted pair, media-independent
        Port type: media-independent
        Transceiver type: internal
        Auto negotiation: true
        Link detected: false
  Card 1:
    NUMA node: 0
    Vendor: Broadcom Inc. and subsidiaries (14e4)
    Product: BCM43142 802.11b/g/n (4365)
    PCI address: 0000:03:00.0
    Driver: wl (4.18.0-21-generic)
    Ports:
      - Port 0 (ethernet)
        ID: wlp3s0
        Address: 18:cf:5e:bf:1a:cc
        Auto negotiation: false
        Link detected: false

Disks:
  Disk 0:
    NUMA node: 0
    ID: sda
    Device: 8:0
    Model: HGST HTS541010A9
    Type: scsi
    Size: 1.00TB
    Read-Only: false
    Removable: false
    Partitions:
      - Partition 1
        ID: sda1
        Device: 8:1
        Read-Only: false
        Size: 380.00GB
      - Partition 2
        ID: sda2
        Device: 8:2
        Read-Only: false
        Size: 577.45GB
      - Partition 3
        ID: sda3
        Device: 8:3
        Read-Only: false
        Size: 21.49GB
      - Partition 4
        ID: sda4
        Device: 8:4
        Read-Only: false
        Size: 21.26GB
  Disk 1:
    NUMA node: 0
    ID: sdb
    Device: 8:16
    Model: KINGSTON SA400S3
    Type: scsi
    Size: 120.03GB
    Read-Only: false
    Removable: false
    Partitions:
      - Partition 1
        ID: sdb1
        Device: 8:17
        Read-Only: false
        Size: 102.76MB
      - Partition 2
        ID: sdb2
        Device: 8:18
        Read-Only: false
        Size: 134.22MB
      - Partition 3
        ID: sdb3
        Device: 8:19
        Read-Only: false
        Size: 117.83GB
      - Partition 4
        ID: sdb4
        Device: 8:20
        Read-Only: false
        Size: 912.26MB
      - Partition 5
        ID: sdb5
        Device: 8:21
        Read-Only: false
        Size: 1.05GB

```
Yeah, I guess you are right, so we can I do?

**Comment by stgraber** [comment] 2019-10-01 03:19
Instead of `id: "0"`, replace that with `id: "1"`

**Comment by stgraber** [comment] 2019-10-01 03:19
`lxc profile edit default`

**Comment by IcarusWizard** [comment] 2019-10-01 03:22
Problem solved! Thanks a lot!
