### ISSUE TITLE
Unable to create VM on IBM Z DPM Partition

### ISSUE THREAD

**Issue by ltrager** [lxc/lxd#8606] opened 2021-03-25 20:50 UTC
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-70-generic
   * LXC version: 4.0.6 | 5.2.0
   * LXD version:4.12
   * Storage backend in use: dir

# Issue description

I am unable to launch a VM on an IBM Z DPM Partition.

# Steps to reproduce

```
root@ta05-canonical:~# lxc launch --vm ubuntu:20.04
Creating the instance
Instance name is: assured-toad              
Starting assured-toad
Error: Failed to run: forklimits limit=memlock:unlimited:unlimited -- /snap/lxd/19819/bin/qemu-system-s390x -S -name assured-toad -uuid b00cf2b7-d0a0-4a3e-9b34-e93be7f6ec24 -daemonize -cpu host -nographic -serial chardev:console -nodefaults -no-reboot -no-user-config -sandbox on,obsolete=deny,elevateprivileges=allow,spawn=deny,resourcecontrol=deny -readconfig /var/snap/lxd/common/lxd/logs/assured-toad/qemu.conf -pidfile /var/snap/lxd/common/lxd/logs/assured-toad/qemu.pid -D /var/snap/lxd/common/lxd/logs/assured-toad/qemu.log -chroot /var/snap/lxd/common/lxd/virtual-machines/assured-toad -runas lxd: char device redirected to /dev/pts/0 (label console)
: Process exited with a non-zero value
Try `lxc info --show-log local:assured-toad` for more info
root@ta05-canonical:~# lxc info --show-log local:assured-toad
Name: assured-toad
Location: none
Remote: unix://
Architecture: s390x
Created: 2021/03/25 20:45 UTC
Status: Stopped
Type: virtual-machine
Profiles: default

Log:

qemu-system-s390x:/var/snap/lxd/common/lxd/logs/assured-toad/qemu.conf:130: 'virtio-9p-ccw' is not a valid device model name
```

**Comment by stgraber** [comment] 2021-03-25 21:21
Our development LPAR appears to be broken or deleted, I requested a new one so hopefully I can reproduce the issue tomorrow.

It's a bit odd though as I definitely tested on s390x after we added 9p support, maybe a regression caused by the QEMU version we're using in the snap. Anyway, shouldn't be too hard to sort out once I have access to an LPAR again.

**Comment by stgraber** [comment] 2021-03-26 17:35
Managed to reproduce this on my LPAR

**Comment by stgraber** [comment] 2021-03-26 19:08
Really looks like the 9p-ccw driver is just plain missing in current qemu, not sure what's up with that...

**Comment by stgraber** [comment] 2021-03-26 19:18
Found one small fix we need to make to LXD to fix CCW networking which regressed when we added multi-queue support to our network config, that's a trivial fix which will be merged shortly.

On the 9p front, it looks like it was a regression in qemu 5.2.0. I found a recent commit which claims to fix it, so giving that a shot in a local snap build, if that works, we'll include the fix in our snaps.

**Comment by stgraber** [comment] 2021-03-26 19:58
Fix merged in LXD for the network side of things, we'll cherry-pick into the other snaps shortly.
The snap packaging for 4.0 and latest has also been updated to include the 9p fix.

**Closed by stgraber** 2021-03-26 19:58 UTC
