### ISSUE TITLE
Odd /dev/null + /dev/zero go+rw bits dropping, with no way to reset them

### ISSUE THREAD

**Issue by davidfavor** [lxc/lxd#5914] opened 2019-07-05 23:33 UTC
Machine level - Ubuntu Bionic + LXD-3.14

Containers - Ubuntu Bionic

What seems to happen intermittently... on only one machine out of many, is the group/other rw permission drops off /dev/null + /dev/zero, from a container view only.

```
net16 # lxc exec net16-jasites bash
bash: /dev/null: Permission denied
bash: /dev/null: Permission denied
bash: /dev/null: Permission denied

lxd: net16-jasites # ll /dev/{null,zero}
crw------- 1 nobody nogroup 1, 3 Jun 26 11:22 /dev/null
crw------- 1 nobody nogroup 1, 5 Jun 26 11:22 /dev/zero
```
Machine level view seems correct...
```
net16 # cdlxd
net16 # cd net16-jasites/rootfs/dev
net16 # pwd
/var/snap/lxd/common/lxd/storage-pools/default/containers/net16-jasites/rootfs/dev
net16 # ll null zero
crw-rw-rw- 1 1000000 1000000 1, 3 Jan 26  2018 null
crw-rw-rw- 1 1000000 1000000 1, 5 Jan 26  2018 zero
```
If I remove permissions at machine level, I see permission from the machine view + inside the container, no permission changes I make on the devices take effect.

It's like some other filesystem if mounted over these devices inside the container.

All containers are effected.

If I stop/start one of these containers, all processes fail to start, as /dev/null can't be accessed.

If I reboot, problem is fixed for a few hours to a few days, then all of a sudden returns.

Let me know if anyone has an idea about how to fix this.

Thanks.

**Comment by davidfavor** [comment] 2019-07-05 23:37
Output of mount seems correct...
```
lxd: net16-jasites # mount | egrep -e /dev/null -e /dev/zero
udev on /dev/null type devtmpfs (rw,nosuid,relatime,size=32777844k,nr_inodes=8194461,mode=755)
udev on /dev/zero type devtmpfs (rw,nosuid,relatime,size=32777844k,nr_inodes=8194461,mode=755)
```

**Comment by davidfavor** [comment] 2019-07-05 23:39
Exact machine Kernel running, so this isn't the Kernel 4.18 namespace bug...
```
net16 # uname -a
Linux net16.faststablehosting.com 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by davidfavor** [comment] 2019-07-06 10:38
Had to finally reboot server, as logrotate was about to run, which would likely have caused many processes to die upon restart.

Still be great if I had some fix, rather than a reboot.

Thanks!

**Comment by stgraber** [comment] 2019-07-06 16:17
Look at the permissions on those files in /dev of the host as that's where they come from and so likely where the problem is

**Comment by davidfavor** [comment] 2019-07-06 16:20
Host files were all correct.

Let me know the mechanism of how container dev files are mapped to host files, so I can come up with a fix for this without rebooting.

**Comment by davidfavor** [comment] 2019-07-06 16:22
In other words...

1) host /dev files are correct

2) /var/snap/lxd/common/lxd/storage-pools/default/containers/*/rootfs/dev are correct

3) Inside container, /dev files are incorrect

**Comment by stgraber** [comment] 2019-07-06 17:18
/dev files in the container are bind-mount from /dev on the host

**Comment by davidfavor** [comment] 2019-07-06 17:34
Hum... Let me know what script or setup to get into to see what might be wrong...

In other words, where the commands live which create the bind mounts, so I can look at logs + also issue manual bind mount commands.

Have to track down this problem + fix it.

Thanks.

**Comment by stgraber** [comment] 2019-07-06 22:56
Can you show: 
 - lxc exec CONTAINER -- ls -lh /dev
 - lxc exec CONTAINER -- cat /proc/self/mountinfo
 - ls -lh /dev
 - ls -lh /var/snap/lxd/common/lxd/mntns/dev
 - cat /proc/$(pgrep daemon.start)/mountinfo

The setup of the bind-mount is done inside liblxc in the autodev handling functions, that's in the https://github.com/lxc/lxc C codebase.

**Comment by davidfavor** [comment] 2019-07-07 12:31
I just realize, looking at data above, I never posted the machine's ll /dev/{null,zero}, so maybe you're correct.

Maybe the machine level /dev files permission actually changed, which would account for all containers showing the exact same behavior.

Right now, since I had to reboot the machine, everything's working.

Next time this behavior occurs, I'll collect + post all requested data.

**Comment by davidfavor** [comment] 2019-07-07 12:32
Random Question: If the machine's /dev/{null,zero} permissions are actually changing...

If you've seen this behavior before, let me know probably sources of this problem to consider.

Thanks.

**Comment by davidfavor** [comment] 2019-07-07 13:07
Just started inotifywait running in background tracking all /dev/null + /dev/zero changes.

If this occurs again, I should have a timestamp of exactly when any ATTR changes occurred.

**Comment by stgraber** [comment] 2019-07-08 18:06
I'm tentatively closing this issue as we do not have any logic in LXD itself which would explain a change in permissions, so it's almost certainly some outside factor, most likely messing with your host's /dev.

If once you track it down, it turns out to be something that LXD or a container did, we can open an issue where appropriate.

**Closed by stgraber** 2019-07-08 18:06 UTC
Labels: Incomplete

**Comment by davidfavor** [comment] 2019-10-02 16:10
https://bugs.launchpad.net/ubuntu/+source/udev/+bug/1846367 relates to upstream Ubuntu bug opened, relating to this problem.

Temp Fix: Change /etc/apt/apt.conf.d/10periodic - APT::Periodic::Update-Package-Lists == 0 to disable all unattended upgrades.

Then defer updating the udev package, till a machine reboot is acceptable.

**Comment by davidfavor** [comment] 2019-12-07 16:51
Setting APT::Periodic::Update-Package-Lists == 0 seems to have no effect.

This seems not to be an LXD issue.

The problem occurs when many host/machine level /dev/* files permissions change.

Fix I've implemented...

1) Capture all /dev/* file ownership + permissions into a repair script.

2) Track /dev/null using incron

3) Anytime permissions drop (specifically /dev/null changes from 666 to anything else), capture the exact timestamp when permissions dropped + run the repair script from step 1.

Hopefully I can capture enough information to extend the upstream Ubuntu issue for a fix.

Currently, there's no fix because the source of the problem hasn't been traced yet.

Another fix, for non-production machines, is simply to reboot.
