### ISSUE TITLE
Unale to start any LXC container

### ISSUE THREAD

**Issue by linsun** [lxc/lxd#2407] opened 2016-09-21 02:29 UTC
# Required information

 * Distribution: Ubuntu
 * Distribution version:  16.04.1
 * The output of "lxc info" or if that fails:
   * Kernel version: 
 # uname -r
4.4.0-28-generic
   * LXC version:
# lxc --version
2.0.4
   * LXD version:
# lxd --version
2.0.4
   * Storage backend in use: zfs

# Issue description

I cannot get my lxc container to start.  This was with a ubuntu 16.04.1 VM in IBM Softlayer data center.   

# Steps to reproduce

 1. Step one:  launch lxc container using cmd "lxc launch ubuntu-daily:16.04 docker1 -p default -p docker".  it failed...

# Information to attach

# lxc launch ubuntu-daily:16.04 docker1 -p default -p docker
Creating docker1
Retrieving image: 100%
Starting docker1
error: Error calling 'lxd forkstart docker1 /var/lib/lxd/containers /var/log/lxd/docker1/lxc.conf': err='exit status 1'
  lxc 20160921022229.240 ERROR lxc_utils - utils.c:safe_mount:1692 - Operation not permitted - Failed to mount proc onto /usr/lib/x86_64-linux-gnu/lxc/proc
  lxc 20160921022229.240 ERROR lxc_conf - conf.c:lxc_mount_auto_mounts:743 - Operation not permitted - error mounting proc on /usr/lib/x86_64-linux-gnu/lxc/proc flags 14
  lxc 20160921022229.240 ERROR lxc_conf - conf.c:lxc_setup:3732 - failed to setup the automatic mounts for 'docker1'
  lxc 20160921022229.240 ERROR lxc_start - start.c:do_start:834 - failed to setup the container
  lxc 20160921022229.240 ERROR lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 3)
  lxc 20160921022229.241 ERROR lxc_start - start.c:__lxc_start:1354 - failed to spawn 'docker1'

# lxc info docker1
Name: docker1
Architecture: x86_64
Created: 2016/09/21 02:22 UTC
Status: Stopped
Type: persistent
Profiles: default, docker

~# lxc info --show-log docker1
Name: docker1
Architecture: x86_64
Created: 2016/09/21 02:22 UTC
Status: Stopped
Type: persistent
Profiles: default, docker

Log:

            lxc 20160921022228.965 INFO     lxc_start - start.c:lxc_check_inherited:252 - closed inherited fd 3
            lxc 20160921022228.965 INFO     lxc_start - start.c:lxc_check_inherited:252 - closed inherited fd 8
            lxc 20160921022228.970 INFO     lxc_container - lxccontainer.c:do_lxcapi_start:797 - Attempting to set proc title to [lxc monitor] /var/lib/lxd/containers docker1
            lxc 20160921022228.972 INFO     lxc_start - start.c:lxc_check_inherited:252 - closed inherited fd 8
            lxc 20160921022228.972 INFO     lxc_lsm - lsm/lsm.c:lsm_init:48 - LSM security driver AppArmor
            lxc 20160921022228.973 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .reject_force_umount  # comment this to allow umount -f;  not recommended.
            lxc 20160921022228.973 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for reject_force_umount action 0
            lxc 20160921022228.973 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:216 - Setting seccomp rule to reject force umounts

            lxc 20160921022228.973 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for reject_force_umount action 0
            lxc 20160921022228.973 INFO     lxc_seccomp - seccomp.c:do_resolve_add_rule:216 - Setting seccomp rule to reject force umounts

            lxc 20160921022228.973 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .[all].
            lxc 20160921022228.973 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .kexec_load errno 1.
            lxc 20160921022228.973 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for kexec_load action 327681
            lxc 20160921022228.973 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for kexec_load action 327681
            lxc 20160921022228.973 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .open_by_handle_at errno 1.
            lxc 20160921022228.973 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for open_by_handle_at action 327681
            lxc 20160921022228.973 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for open_by_handle_at action 327681
            lxc 20160921022228.973 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .init_module errno 1.
            lxc 20160921022228.973 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for init_module action 327681
            lxc 20160921022228.973 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for init_module action 327681
            lxc 20160921022228.973 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .finit_module errno 1.
            lxc 20160921022228.973 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for finit_module action 327681
            lxc 20160921022228.973 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for finit_module action 327681
            lxc 20160921022228.973 INFO     lxc_seccomp - seccomp.c:parse_config_v2:342 - processing: .delete_module errno 1.
            lxc 20160921022228.973 INFO     lxc_seccomp - seccomp.c:parse_config_v2:446 - Adding native rule for delete_module action 327681
            lxc 20160921022228.973 INFO     lxc_seccomp - seccomp.c:parse_config_v2:449 - Adding compat rule for delete_module action 327681
            lxc 20160921022228.973 INFO     lxc_seccomp - seccomp.c:parse_config_v2:456 - Merging in the compat seccomp ctx into the main one
            lxc 20160921022228.973 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/bin/lxd callhook /var/lib/lxd 4 start' for container 'docker1', config section 'lxc'
            lxc 20160921022228.975 INFO     lxc_start - start.c:lxc_check_inherited:252 - closed inherited fd 3
            lxc 20160921022228.975 INFO     lxc_start - start.c:lxc_check_inherited:252 - closed inherited fd 8
            lxc 20160921022228.980 INFO     lxc_monitor - monitor.c:lxc_monitor_sock_name:178 - using monitor sock name lxc/d78a9d7e97b4b375//var/lib/lxd/containers
            lxc 20160921022229.134 DEBUG    lxc_start - start.c:setup_signal_fd:290 - sigchild handler set
            lxc 20160921022229.135 DEBUG    lxc_console - console.c:lxc_console_peer_default:469 - no console peer
            lxc 20160921022229.135 INFO     lxc_start - start.c:lxc_init:489 - 'docker1' is initialized
            lxc 20160921022229.135 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 100000 range 65536
            lxc 20160921022229.135 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 100000 range 65536
            lxc 20160921022229.137 DEBUG    lxc_start - start.c:__lxc_start:1327 - Not dropping cap_sys_boot or watching utmp
            lxc 20160921022229.137 INFO     lxc_start - start.c:resolve_clone_flags:1014 - Cloning a new user namespace
            lxc 20160921022229.140 DEBUG    lxc_conf - conf.c:instantiate_veth:2615 - instantiated veth 'veth2R4SDM/veth71LQLY', index is '15'
            lxc 20160921022229.140 INFO     lxc_cgroup - cgroups/cgroup.c:cgroup_init:68 - cgroup driver cgroupfs-ng initing for docker1
            lxc 20160921022229.216 DEBUG    lxc_conf - conf.c:lxc_assign_network:3058 - move 'eth0' to '22639'
            lxc 20160921022229.216 NOTICE   lxc_start - start.c:do_start:778 - switching to gid/uid 0/0 in new user namespace
            lxc 20160921022229.217 DEBUG    lxc_conf - conf.c:setup_rootfs:1215 - mounted '/var/lib/lxd/containers/docker1/rootfs' on '/usr/lib/x86_64-linux-gnu/lxc'
            lxc 20160921022229.217 INFO     lxc_conf - conf.c:setup_utsname:843 - 'docker1' hostname has been setup
            lxc 20160921022229.240 DEBUG    lxc_conf - conf.c:setup_hw_addr:2146 - mac address '00:16:3e:b6:1f:a3' on 'eth0' has been setup
            lxc 20160921022229.240 DEBUG    lxc_conf - conf.c:setup_netdev:2373 - 'eth0' has been setup
            lxc 20160921022229.240 INFO     lxc_conf - conf.c:setup_network:2394 - network has been setup
            lxc 20160921022229.240 INFO     lxc_conf - conf.c:mount_autodev:1072 - Mounting container /dev
            lxc 20160921022229.240 INFO     lxc_conf - conf.c:mount_autodev:1095 - Mounted tmpfs onto /usr/lib/x86_64-linux-gnu/lxc/dev
            lxc 20160921022229.240 INFO     lxc_conf - conf.c:mount_autodev:1113 - Mounted container /dev
            lxc 20160921022229.240 ERROR    lxc_utils - utils.c:safe_mount:1692 - Operation not permitted - Failed to mount proc onto /usr/lib/x86_64-linux-gnu/lxc/proc
            lxc 20160921022229.240 ERROR    lxc_conf - conf.c:lxc_mount_auto_mounts:743 - Operation not permitted - error mounting proc on /usr/lib/x86_64-linux-gnu/lxc/proc flags 14
            lxc 20160921022229.240 ERROR    lxc_conf - conf.c:lxc_setup:3732 - failed to setup the automatic mounts for 'docker1'
            lxc 20160921022229.240 ERROR    lxc_start - start.c:do_start:834 - failed to setup the container
            lxc 20160921022229.240 ERROR    lxc_sync - sync.c:__sync_wait:57 - An error occurred in another process (expected sequence number 3)
            lxc 20160921022229.241 WARN     lxc_conf - conf.c:lxc_delete_network:2919 - failed to remove interface 15 'eth0'
            lxc 20160921022229.241 ERROR    lxc_start - start.c:__lxc_start:1354 - failed to spawn 'docker1'
            lxc 20160921022229.276 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/share/lxcfs/lxc.reboot.hook' for container 'docker1', config section 'lxc'
            lxc 20160921022229.783 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/bin/lxd callhook /var/lib/lxd 4 stop' for container 'docker1', config section 'lxc'
            lxc 20160921022229.914 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - command get_cgroup failed to receive response
            lxc 20160921022229.914 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - command get_cgroup failed to receive response
            lxc 20160921022229.939 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 100000 range 65536
            lxc 20160921022229.939 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 100000 range 65536
            lxc 20160921022529.728 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 100000 range 65536
            lxc 20160921022529.728 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 100000 range 65536
            lxc 20160921022529.735 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 100000 range 65536
            lxc 20160921022529.735 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 100000 range 65536
            lxc 20160921022727.893 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 100000 range 65536
            lxc 20160921022727.894 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 100000 range 65536
            lxc 20160921022727.901 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type u nsid 0 hostid 100000 range 65536
            lxc 20160921022727.901 INFO     lxc_confile - confile.c:config_idmap:1500 - read uid map: type g nsid 0 hostid 100000 range 65536

Let me know if any other info is needed

**Comment by stgraber** [comment] 2016-09-21 03:52
Can you paste the content of /proc/mounts on the host?

**Comment by linsun** [comment] 2016-09-21 13:02
root@my-server2:~# /proc/mounts 
-bash: /proc/mounts: Permission denied
root@my-server2:~# sudo /proc/mounts 
sudo: /proc/mounts: command not found

**Comment by techtonik** [comment] 2016-09-21 13:53
@linsun use `cat /proc/mounts`. For how long are you using Linux?

@stgraber is it ok that `-p` option specified twice? Do key values get merged in this case?

**Comment by linsun** [comment] 2016-09-21 14:08
@techtonik Thanks!  ah, sorry, didn't realize that is a file, blame on morning craziness!  -p specified twice worked for me before.  In fact, I had trouble when just using -p docker by itself without -p default.

root@my-server2:~# cat /proc/mounts
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,nosuid,relatime,size=2031780k,nr_inodes=507945,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=409600k,mode=755 0 0
/dev/xvda2 / ext4 rw,relatime,data=ordered 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=26,pgrp=1,timeout=0,minproto=5,maxproto=5,direct 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
none /proc/xen xenfs rw,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
/dev/xvda1 /boot ext3 rw,relatime,data=ordered 0 0
tmpfs /run/lxcfs/controllers tmpfs rw,relatime,size=100k,mode=700 0 0
blkio /run/lxcfs/controllers/blkio cgroup rw,relatime,blkio 0 0
pids /run/lxcfs/controllers/pids cgroup rw,relatime,pids 0 0
hugetlb /run/lxcfs/controllers/hugetlb cgroup rw,relatime,hugetlb 0 0
memory /run/lxcfs/controllers/memory cgroup rw,relatime,memory 0 0
net_cls,net_prio /run/lxcfs/controllers/net_cls,net_prio cgroup rw,relatime,net_cls,net_prio 0 0
freezer /run/lxcfs/controllers/freezer cgroup rw,relatime,freezer 0 0
devices /run/lxcfs/controllers/devices cgroup rw,relatime,devices 0 0
perf_event /run/lxcfs/controllers/perf_event cgroup rw,relatime,perf_event 0 0
cpuset /run/lxcfs/controllers/cpuset cgroup rw,relatime,cpuset 0 0
cpu,cpuacct /run/lxcfs/controllers/cpu,cpuacct cgroup rw,relatime,cpu,cpuacct 0 0
name=systemd /run/lxcfs/controllers/name=systemd cgroup rw,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
lxcfs /var/lib/lxcfs fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,relatime 0 0
lxd/images/b7309c1106fc81df4adf74ef36c0866d198e48e4cb9bffdae29bb76a56c995c4 /var/lib/lxd/images/b7309c1106fc81df4adf74ef36c0866d198e48e4cb9bffdae29bb76a56c995c4.zfs zfs ro,relatime,xattr,noacl 0 0
lxd/containers/docker1 /var/lib/lxd/containers/docker1.zfs zfs rw,relatime,xattr,noacl 0 0
/dev/xvda2 /var/lib/lxd/shmounts ext4 rw,relatime,data=ordered 0 0
tmpfs /run/user/0 tmpfs rw,nosuid,nodev,relatime,size=409600k,mode=700 0 0

**Comment by stgraber** [comment] 2016-09-21 18:14
Ok, so the problem is /proc/xen which is causing the kernel overmounting protection to kick in.

We fixed this bug in the Ubuntu kernel a few weeks ago and it looks like you are 10 kernel updates behind.

Make sure your system is up to date, then reboot, that should get you on the 4.4.0-38 kernel which has this issue fixed.

**Comment by stgraber** [comment] 2016-09-21 18:16
This was fixed in 4.4.0-35 to be precise, any of the kernels after that should be fine.

**Comment by linsun** [comment] 2016-09-21 18:52
thanks!  that makes sense - I will try update the kernel to latest

**Comment by linsun** [comment] 2016-09-21 20:10
Confirmed after moving to 4.4.0-36 this is fixed!  thanks

**Closed** 2016-09-21 20:18 UTC
