### ISSUE TITLE
lxd zfs corrupted on profile cat update

### ISSUE THREAD

**Issue by bschumacher** [lxc/lxd#3634] opened 2017-08-04 20:35 UTC
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
  storage.zfs_pool_name: lxd
api_extensions:
- id_map
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:--- SNIP ---
  architectures:
  - x86_64
  - i686
  certificate: |--- SNIP ---
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-89-generic
  server: lxd
  server_pid: 3267
  server_version: 2.0.10
  storage: dir
  storage_version: ""
   * Kernel version: 4.4.0-89-generic
   * LXC version:2.0.10
   * LXD version:2.0.10
   * Storage backend in use:zfs

# Issue description

Updating lxc profile via cat destroys zfs.

A brief description of what failed or what could be improved.

ZFS should not have been affected at all, backend settings were not updated. Only one line in the config should have changed.

# Steps to reproduce

1. vi default.yaml
2. Paste contents:
```
config: {}
description: Default LXD profile
devices:
  eth0:  
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
name: default
```
3. cat default.yaml | lxc profile edit default

# Information to attach

 - [ ] any relevant kernel output (`dmesg`)
 - [ ] container log (`lxc info NAME --show-log`)
 - [ ] main daemon log (`cat /var/log/lxd/lxd.log`)
 - [ ] output of the client with --debug
 - [ ] output of the daemon with --debug
lvl=eror msg="Could not initialize storage type ZFS: cannot open 'lxd': dataset does not exist - falling 
error: cannot open 'lxd': dataset does not exist

**Comment by stgraber** [comment] 2017-08-04 20:37
That "lxc profile edit default" didn't touch your ZFS storage pool.

Can you please include:
 - /var/log/lxd/lxd.log
 - "dmesg" output

Looks like your zpool didn't come online for some reason.

**Comment by bschumacher** [comment] 2017-08-04 20:43
lvl=info msg="Stopping REST API handler:" t=2017-08-04T15:06:00-0500
lvl=info msg=" - closing socket" socket=[::]:8443 t=2017-08-04T15:06:00-0500
lvl=info msg=" - skipping socket-activated socket" socket=/var/lib/lxd/unix.socket t=2017-08-04T15:06:00-0500
lvl=info msg="Stopping /dev/lxd handler" t=2017-08-04T15:06:00-0500
lvl=info msg="Stopped /dev/lxd handler" t=2017-08-04T15:06:00-0500
lvl=info msg="Unmounting temporary filesystems" t=2017-08-04T15:06:00-0500
lvl=info msg="Done unmounting temporary filesystems" t=2017-08-04T15:06:00-0500
lvl=info msg="Closing the database" t=2017-08-04T15:06:00-0500
lvl=info msg="Saving simplestreams cache" t=2017-08-04T15:06:00-0500
lvl=info msg="Saved simplestreams cache" t=2017-08-04T15:06:00-0500
lvl=info msg="LXD 2.0.10 is starting in normal mode" path=/var/lib/lxd t=2017-08-04T15:08:04-0500
lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2017-08-04T15:08:04-0500
lvl=info msg="Kernel uid/gid map:" t=2017-08-04T15:08:04-0500
lvl=info msg=" - u 0 0 4294967295" t=2017-08-04T15:08:04-0500
lvl=info msg=" - g 0 0 4294967295" t=2017-08-04T15:08:04-0500
lvl=info msg="Configured LXD uid/gid map:" t=2017-08-04T15:08:04-0500
lvl=info msg=" - u 0 100000 65536" t=2017-08-04T15:08:04-0500
lvl=info msg=" - g 0 100000 65536" t=2017-08-04T15:08:04-0500
lvl=eror msg="Could not initialize storage type ZFS: cannot open 'lxd': dataset does not exist - falling back to dir" t=2017-08-04T15:08:04-0500


Already rebooted hoping that zfs would remount magically.

zpool was already online, applying the profile destroyed it somehow.

**Comment by stgraber** [comment] 2017-08-04 20:47
What does "zpool status" show at this point?
Does /var/lib/lxd/zfs.img exist?

**Comment by bschumacher** [comment] 2017-08-04 20:53
All the zfs files for the containers do exist though.

**Comment by bschumacher** [comment] 2017-08-04 21:19
I could probably recreate everything, I made a new zfs.img file and started adding stuff back to it manually, lxd database error message disappeared, containers show as stopped.

But I can't figure out how to set the origin property...

**Comment by bschumacher** [comment] 2017-08-04 21:32
Ah yeah no nevermind, those are just mount points.

**Comment by bschumacher** [comment] 2017-08-04 21:42
I would recommend not having ZFS the default option if ZFS is installed, way too easy for catastrophic data loss.

To get my lxd back to good I had to delete all containers, all images lxd.db and do a lxd init.

**Comment by bschumacher** [comment] 2017-08-04 21:47
I'm about to destroy another server to see if I can get some more info... lol.

**Comment by bschumacher** [comment] 2017-08-04 21:53
Hmm, other server did not die.

I bet apparmor is the culprit:

[  103.458019] audit: type=1400 audit(1501883366.126:15): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/usr/bin/lxc-start" pid=3835 comm="apparmor_parser"

**Comment by stgraber** [comment] 2017-08-04 22:00
Nope, apparmor isn't the problem either. That log message just means that the apparmor profile of the container was changed, which is what you'd assume to happen on startup.

**Comment by stgraber** [comment] 2017-08-04 22:01
Closing this issue for now since there's unfortunately no working reproducing steps available and the machine that had the issue has since been cleaned and re-setup, erasing anything we could have used to try to debug this.

**Closed by stgraber** 2017-08-04 22:01 UTC
Labels: Incomplete

**Comment by bschumacher** [comment] 2017-08-04 22:17
Aug  4 15:11:07 --- systemd[1]: Started Session 1 of user ---.
Aug  4 15:11:07 --- systemd[4052]: Reached target Paths.
Aug  4 15:11:07 --- systemd[4052]: Reached target Sockets.
Aug  4 15:11:07 --- systemd[4052]: Reached target Timers.
Aug  4 15:11:07 --- systemd[4052]: Reached target Basic System.
Aug  4 15:11:07 --- systemd[4052]: Reached target Default.
Aug  4 15:11:07 --- systemd[4052]: Startup finished in 11ms.
Aug  4 15:11:07 --- systemd[1]: Started User Manager for UID 1000.
Aug  4 15:11:38 --- lxd[3923]: container=----db lvl=eror msg="Failed opening container" t=2017-08-04T15:11:38-0500
Aug  4 15:11:38 --- lxd[3923]: container=-----db lvl=eror msg="Failed opening container" t=2017-08-04T15:11:38-0500
Aug  4 15:11:38 --- lxd[3923]: container=----db lvl=eror msg="Failed opening container" t=2017-08-04T15:11:38-0500
Aug  4 15:11:38 --- lxd[3923]: container=--- lvl=eror msg="Failed opening container" t=2017-08-04T15:11:38-0500
Aug  4 15:11:38 --- lxd[3923]: container=--- lvl=eror msg="Failed opening container" t=2017-08-04T15:11:38-0500
Aug  4 15:11:38 --- lxd[3923]: container=---- lvl=eror msg="Failed opening container" t=2017-08-04T15:11:38-0500
Aug  4 15:11:38 --- lxd[3923]: container=--- lvl=eror msg="Failed opening container" t=2017-08-04T15:11:38-0500
Aug  4 15:11:38 --- lxd[3923]: container=--- lvl=eror msg="Failed opening container" t=2017-08-04T15:11:38-0500
Aug  4 15:11:38 --- lxd[3923]: container=--- lvl=eror msg="Failed opening container" t=2017-08-04T15:11:38-0500
Aug  4 15:11:38 --- lxd[3923]: container=-----db lvl=eror msg="Failed opening container" t=2017-08-04T15:11:38-0500
Aug  4 15:13:02 --- lxd[3923]: container=-----db lvl=eror msg="Failed opening container" t=2017-08-04T15:13:02-0500
Aug  4 15:13:02 --- lxd[3923]: container=----db lvl=eror msg="Failed opening container" t=2017-08-04T15:13:02-0500
Aug  4 15:13:02 --- lxd[3923]: container=----db lvl=eror msg="Failed opening container" t=2017-08-04T15:13:02-0500
Aug  4 15:13:02 --- lxd[3923]: container=---- lvl=eror msg="Failed opening container" t=2017-08-04T15:13:02-0500
Aug  4 15:13:02 --- lxd[3923]: container=---- lvl=eror msg="Failed opening container" t=2017-08-04T15:13:02-0500
Aug  4 15:13:02 --- lxd[3923]: container=---- lvl=eror msg="Failed opening container" t=2017-08-04T15:13:02-0500
Aug  4 15:13:02 --- lxd[3923]: container=---- lvl=eror msg="Failed opening container" t=2017-08-04T15:13:02-0500
Aug  4 15:13:02 --- lxd[3923]: container=---- lvl=eror msg="Failed opening container" t=2017-08-04T15:13:02-0500
Aug  4 15:13:02 --- lxd[3923]: container=---- lvl=eror msg="Failed opening container" t=2017-08-04T15:13:02-0500
Aug  4 15:13:02 --- lxd[3923]: container=-----db lvl=eror msg="Failed opening container" t=2017-08-04T15:13:02-0500
Aug  4 15:13:31 --- systemd[1]: Stopping LXD - main daemon...
Aug  4 15:13:31 --- systemd[1]: Stopped LXD - main daemon.
Aug  4 15:13:31 -- systemd[1]: Starting LXD - main daemon...
Aug  4 15:13:31 --- kernel: [  390.769345] audit_printk_skb: 24 callbacks suppressed
Aug  4 15:13:31 --- kernel: [  390.769346] audit: type=1400 audit(1501877611.921:20): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/usr/bin/lxc-start" pid=4399 comm="apparmor_parser"
Aug  4 15:13:31 --- kernel: [  390.772653] audit: type=1400 audit(1501877611.925:21): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="lxc-container-default" pid=4403 comm="apparmor_parser"
Aug  4 15:13:31 --- kernel: [  390.772657] audit: type=1400 audit(1501877611.925:22): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="lxc-container-default-cgns" pid=4403 comm="apparmor_parser"
Aug  4 15:13:31 --- kernel: [  390.772660] audit: type=1400 audit(1501877611.925:23): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="lxc-container-default-with-mounting" pid=4403 comm="apparmor_parser"
Aug  4 15:13:31 --- kernel: [  390.772662] audit: type=1400 audit(1501877611.925:24): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="lxc-container-default-with-nesting" pid=4403 comm="apparmor_parser"
Aug  4 15:13:31 --- lxd[4405]: lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2017-08-04T15:13:31-0500
Aug  4 15:13:31 --- lxd[4405]: lvl=eror msg="Could not initialize storage type ZFS: cannot open 'lxd': dataset does not exist - falling back to dir" t=2017-08-04T15:13:31-0500
Aug  4 15:13:31 --- systemd[1]: Started LXD - main daemon.

**Comment by bschumacher** [comment] 2017-08-04 22:19
There's the syslog output from when the command was applied.

App armor messages come after it tries to open them, so probably not apparmor.

**Comment by stgraber** [comment] 2017-08-05 05:28
Do you have more logs available? Ideally it'd be nice to see from the previous LXD startup until that time it restarted at 15:13 on the 4th.

LXD 2.0.x doesn't have support for our storage API, which means the codebase doesn't contain any function that's capable of removing a zfs pool or the zfs loop file. That's unlike more recent LXD (2.11 or higher) where we technically do have code which could do that, but obviously don't ever have LXD make calls to that on its own (it's only in an API call from the user and only allowed if the pool is empty).

So I'm still pretty confused as to how the zfs.img file would have disappeared and even more so, how the zpool would have vanished during runtime, considering that even removing zfs.img would technically keep the zpool working properly until reboot (due to the way Linux handles deleted files).
