### ISSUE TITLE
lxd does not start: failed to apply update 19: CHECK constraint failed with sqlite 3.37.0

### ISSUE THREAD

**Issue by spartan057** [lxc/lxd#9736] opened 2022-01-02 12:04 UTC
# Required information

 * Distribution: Arch Linux
 * Distribution version: Rolling / current
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.15.12
   * LXC version: 4.0.11
   * LXD version: 4.21
   * Storage backend in use: ZFS

# Issue description

Upgrading from lxd 3.16 to 4.21 (quite a strech, I know) I face the following error while starting lxd: "Failed to initialize global database: failed to ensure schema: failed to apply update 19: CHECK constraint failed".

# Steps to reproduce

Starting lxd 4.21 with my database file, reproducible on different archlinux installations. I'm happy to provide a tar ball of the database directory privately (780MB). 

# Information to attach
[lxd.log.txt](https://github.com/lxc/lxd/files/7799027/lxd.log.txt)
[lxd_debug_ouput.txt](https://github.com/lxc/lxd/files/7799028/lxd_debug_ouput.txt)

**Comment by tomponline** [comment] 2022-01-02 12:45
What version of sqlite are you using?

**Comment by spartan057** [comment] 2022-01-02 12:59
It's sqlite 3.37.0

**Comment by tomponline** [comment] 2022-01-02 13:03
It'll likely be the same issue in the snap package we saw, https://github.com/lxc/lxd-pkg-snap/commit/8174f4c5129e51ff7e7800641a6c51c9de2377ea, but not figured out why this only occurs with latest sqlite yet.

**Comment by spartan057** [comment] 2022-01-02 13:21
Downgrading to sqlite 3.36.0 solved the problem, lxd starts again. Thank you very much. Please let me know if I can support you in debugging the original issue.

Also one db related error log appears: `sql: Scan error on column index 2, name \"expiry_date\": converting NULL to string is unsupported`, but this doesn't look related to the sql version to me.

**Comment by tomponline** [comment] 2022-01-02 13:24
Can you provide the full error and when it occurred?

**Comment by stgraber** [comment] 2022-01-02 13:26
Yes, that's a breakage in sqlite 3.37.0, we have reverted to 3.36.0 for this reason in LXD itself.
Upstream sqlite has now released 3.37.1 but we haven't tested that yet to see if it helps.

**Comment by stgraber** [comment] 2022-01-02 13:26
Closing for now as current state of investigation is that it's a regression caused by sqlite upstream and not a LXD bug, would be good to know if 3.37.1 fixed it though.

**Comment by spartan057** [comment] 2022-01-02 14:28
Regarding sqlite version 3.37.1, the error still occurs:

```
# sqlite3
SQLite version 3.37.1 2021-12-30 15:30:28
sqlite> .version
SQLite 3.37.1 2021-12-30 15:30:28 378629bf2ea546f73eee84063c5358439a12f7300e433f18c9e1bddd948dalt1
```

Error message is unchanged:

```
DBUG[01-02|15:26:01] Updating global DB schema from 19 to 20 
DBUG[01-02|15:26:01] Database error: &errors.errorString{s:"failed to apply update 19: CHECK constraint failed"} 
EROR[01-02|15:26:01] Failed to start the daemon               err="Failed to initialize global database: failed to ensure schema: failed to apply update 19: CHECK constraint failed"
```

**Comment by spartan057** [comment] 2022-01-02 14:39
@tomponline: This is the complete log for the expiry_date error. It appears immediately while starting, and periodically afterwards. The log is from a fresh lxd start and contains the first occurence of the error.

[lxd_startup_log.txt](https://github.com/lxc/lxd/files/7799209/lxd_startup_log.txt)

The respective table looks like this:

```
sqlite> SELECT * FROM storage_volumes_snapshots;
id|storage_volume_id|name|description|expiry_date
96|8|before-upgrade-2019-12-01||
97|8|before-upgrade-2019-12-01_2||
```

**Comment by tomponline** [comment] 2022-01-02 14:52
Thanks will take a look at that.

**Comment by stgraber** [comment] 2022-01-02 19:08
Still seems very likely to be a sqlite regression as we have been running daily upgrade tests for years and things only broke with 3.37.0 to be fixed when we downgraded the snap to 3.36.0. Would be good if someone with some time you track down a much smaller reproducer and file a bug against sqlite and link it here.

**Comment by tomponline** [comment] 2022-01-02 19:46
Yeah I'll keep this case open to look at the expiry_date issue on 3.36.0

**Comment by stgraber** [comment] 2022-01-02 22:29
Oh, I somehow missed that post, yeah, that NULL conversion thing looks like something on our end that we should definitely sort out. It's not something that's showed up in the automated tests so would be interesting to track down.

**Comment by tomponline** [comment] 2022-01-04 09:15
@spartan057 can you show the output of `sqlite> .schema storage_volumes_snapshots` from db.bin?

**Comment by tomponline** [comment] 2022-01-04 09:16
> Edit: I updated the expiry date with `UPDATE storage_volumes_snapshots SET expiry_date = '2050-01-02 00:00:00+00:00';`

You cannot update the db.bin file directly.

**Comment by tomponline** [comment] 2022-01-04 12:13
> Oh, I somehow missed that post, yeah, that NULL conversion thing looks like something on our end that we should definitely sort out. It's not something that's showed up in the automated tests so would be interesting to track down.

I've got a fix for the NULL conversion issue. However it also appears there is an issue with how the zero time is returned from dqlite due to timezone conversion, which although is already kind of handled (fudged) in some places, the wider issue is that manually editing a snapshot expiry doesn't result in the same time being returned after you've edited it (due to the time zone conversion issue). I'm going to try and track down where this is happening, as it might be in dqlite itself (cc @MathieuBordere ).

**Closed** 2022-01-04 16:21 UTC
Labels: Bug, Incomplete
