### ISSUE TITLE
monit freezes within lxd

### ISSUE THREAD

**Issue by patrickd-** [lxc/lxd#1357] opened 2015-11-26 09:51 UTC
I've used monit on ubuntu 14.04 for a long time and I never had any problem with it.
But within a LXD container it seems to go into a never ending sleep.
(Still I'm not sure wether this is monit or lxd specific)

```
root@sandbox:/spawner# service monit status
 * monit is running
root@sandbox:/spawner# service monit stop
 * Stopping daemon monitor monit
   ...fail!
root@sandbox:/spawner# ps -lA | grep monit
1 D     0  1624     1  0  80   0 - 26082 fuse_r ?        00:00:21 monit
root@sandbox:/spawner# pkill -9 monit
root@sandbox:/spawner# ps -lA | grep monit
1 D     0  1624     1  0  80   0 - 26082 fuse_r ?        00:00:21 monit
```

The only way to stop it seems to be restarting the container.

Please let me know if I should execute any other commands.

**Comment by stgraber** [comment] 2015-12-10 22:01
can you run it under strace so we can have an idea as to what it's doing?

**Comment by stgraber** [comment] 2015-12-10 22:02
looks like it gets stuck on I/O wait somehow and if that never succeeds, then it's most likely a kernel bug of some sort.

**Comment by stgraber** [comment] 2015-12-10 22:02
oh, actually, no, the mention of fuse_r suggests it may be a lxcfs bug, anyway, the strace output would help us see what's actually causing the problem.

**Comment by stgraber** [comment] 2015-12-10 22:03
@hallyn FYI, a potential lxcfs bug ^

**Comment by patrickd-** [comment] 2015-12-12 12:11
strace -p X seems to freeze as well.

Thanks for looking into this!

**Comment by hallyn** [comment] 2015-12-23 19:59
@patrickd-  - could you tell me which ppas you're using?  I'll try to reproduce it with some guesses in the meantime.

**Comment by patrickd-** [comment] 2015-12-23 20:37
I'm on Ubuntu 14.04

The following was (on 22. Nov 2015) necessary for me to get it working there:
sudo add-apt-repository ppa:ubuntu-lxc/lxd-stable
sudo apt-get update
sudo apt-get autoremove
sudo apt-get autoclean
sudo apt-get install lxd
sudo add-apt-repository -r ppa:ubuntu-lxc/lxd-stable
sudo apt-get update
sudo apt-get upgrade

(For reasons I don't understand) Without these steps the containers werent brigded and not able to access the internet.

PPA list of the host:
https://gist.github.com/patrickd-/fb9e0ffa1666235a6e8a

**Comment by hallyn** [comment] 2015-12-23 21:04
Ok i've got monit in a 14.04 lxd container on 14.04 host, it seems fine.

I'm running 0.13-0ubuntu6~ubuntu14.04.1~ppa1 from ppa:ubuntu-lxc/daily .

**Comment by hallyn** [comment] 2015-12-23 21:12
no, lxd-stable ppa has the same lxcfs version.

**Comment by hallyn** [comment] 2015-12-23 21:21
Does this happen immediately on startup?  If not, can you reliably trigger it some way?

**Comment by patrickd-** [comment] 2015-12-23 21:44
nope, it just happened after 30 mins - 2 hours.
it was configured to monitor the apache2 process

**Comment by hallyn** [comment] 2015-12-23 21:46
Ah - can you share the configuration for that?

**Comment by patrickd-** [comment] 2015-12-23 21:54
cat /etc/monit/conf.d/apache2
```
 check process apache with pidfile /var/run/apache2/apache2.pid
   group www
   group apache
   start program = "/etc/init.d/apache2 start"
   stop program  = "/etc/init.d/apache2 stop"
   if 4 restarts within 20 cycles then timeout
   if failed host localhost port 80 with protocol http and request "/" with timeout 2 seconds for 2 times within 5 cycles then restart
   depend apache_bin
   depend apache_rc

 check file apache_bin with path /usr/sbin/apache2
   group apache
   include /etc/monit/templates/rootbin

 check file apache_rc with path /etc/init.d/apache2
   group apache
   include /etc/monit/templates/rootbin
```

**Comment by hallyn** [comment] 2015-12-23 22:30
Not yet reproduced, still running.

Would it be possible for you to stop the containers on one machine, stop lxcfs, then run

gdb lxcfs
 # run /var/lib/lxcfs

in a terminal, then restart the containers, reproduce the crash, and see if anything funky is going on through gdb?

Also, doing a 'lsof | grep $(pidof monit)' while monit is hung could be useful.

**Comment by patrickd-** [comment] 2015-12-23 22:56
if you put
```
 set httpd port 2812 and
    use address localhost  # only accept connection from localhost
    allow localhost        # allow localhost to connect to the server and
```
into your monitrc

and do
$ monit status

does it show the current time at "data collected"?
For me it shows the datetime monit got stuck

(will followup with your request)

**Comment by patrickd-** [comment] 2015-12-23 22:58
```
# lsof | grep $(pidof monit)                                                                                                                                                                                                               
monit     22113           root  cwd       DIR                9,2      4096  25430084 /
monit     22113           root  rtd       DIR                9,2      4096  25430084 /
monit     22113           root  txt       REG                9,2    534728  25445677 /usr/bin/monit
monit     22113           root  mem       REG                9,2     47712  25696705 /lib/x86_64-linux-gnu/libnss_files-2.19.so
monit     22113           root  mem       REG                9,2     47760  25696767 /lib/x86_64-linux-gnu/libnss_nis-2.19.so
monit     22113           root  mem       REG                9,2     97296  25696749 /lib/x86_64-linux-gnu/libnsl-2.19.so
monit     22113           root  mem       REG                9,2     39824  25696743 /lib/x86_64-linux-gnu/libnss_compat-2.19.so
monit     22113           root  mem       REG                9,2     14664  25696754 /lib/x86_64-linux-gnu/libdl-2.19.so
monit     22113           root  mem       REG                9,2    104936  25696733 /lib/x86_64-linux-gnu/libaudit.so.1.0.0
monit     22113           root  mem       REG                9,2   1840928  25696581 /lib/x86_64-linux-gnu/libc-2.19.so
monit     22113           root  mem       REG                9,2   1930528  25696758 /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
monit     22113           root  mem       REG                9,2    387256  25696763 /lib/x86_64-linux-gnu/libssl.so.1.0.0
monit     22113           root  mem       REG                9,2     43368  25696706 /lib/x86_64-linux-gnu/libcrypt-2.19.so
monit     22113           root  mem       REG                9,2    141574  25696741 /lib/x86_64-linux-gnu/libpthread-2.19.so
monit     22113           root  mem       REG                9,2     55856  25696755 /lib/x86_64-linux-gnu/libpam.so.0.83.1
monit     22113           root  mem       REG                9,2    149120  25696710 /lib/x86_64-linux-gnu/ld-2.19.so
monit     22113           root    0u      CHR                1,3       0t0      1029 /dev/null
monit     22113           root    1u      CHR                1,3       0t0      1029 /dev/null
monit     22113           root    2u      CHR                1,3       0t0      1029 /dev/null
monit     22113           root    3u      REG                9,2     88281  25450669 /var/log/monit.log
monit     22113           root    4u      REG                9,2      1160    786446 /var/lib/monit/state
monit     22113           root    5u     IPv4           12128234       0t0       TCP localhost:2812 (LISTEN)
monit     22113 22114     root  cwd       DIR                9,2      4096  25430084 /
monit     22113 22114     root  rtd       DIR                9,2      4096  25430084 /
monit     22113 22114     root  txt       REG                9,2    534728  25445677 /usr/bin/monit
monit     22113 22114     root  mem       REG                9,2     47712  25696705 /lib/x86_64-linux-gnu/libnss_files-2.19.so
monit     22113 22114     root  mem       REG                9,2     47760  25696767 /lib/x86_64-linux-gnu/libnss_nis-2.19.so
monit     22113 22114     root  mem       REG                9,2     97296  25696749 /lib/x86_64-linux-gnu/libnsl-2.19.so
monit     22113 22114     root  mem       REG                9,2     39824  25696743 /lib/x86_64-linux-gnu/libnss_compat-2.19.so
monit     22113 22114     root  mem       REG                9,2     14664  25696754 /lib/x86_64-linux-gnu/libdl-2.19.so
monit     22113 22114     root  mem       REG                9,2    104936  25696733 /lib/x86_64-linux-gnu/libaudit.so.1.0.0
monit     22113 22114     root  mem       REG                9,2   1840928  25696581 /lib/x86_64-linux-gnu/libc-2.19.so
monit     22113 22114     root  mem       REG                9,2   1930528  25696758 /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
monit     22113 22114     root  mem       REG                9,2    387256  25696763 /lib/x86_64-linux-gnu/libssl.so.1.0.0
monit     22113 22114     root  mem       REG                9,2     43368  25696706 /lib/x86_64-linux-gnu/libcrypt-2.19.so
monit     22113 22114     root  mem       REG                9,2    141574  25696741 /lib/x86_64-linux-gnu/libpthread-2.19.so
monit     22113 22114     root  mem       REG                9,2     55856  25696755 /lib/x86_64-linux-gnu/libpam.so.0.83.1
monit     22113 22114     root  mem       REG                9,2    149120  25696710 /lib/x86_64-linux-gnu/ld-2.19.so
monit     22113 22114     root    0u      CHR                1,3       0t0      1029 /dev/null
monit     22113 22114     root    1u      CHR                1,3       0t0      1029 /dev/null
monit     22113 22114     root    2u      CHR                1,3       0t0      1029 /dev/null
monit     22113 22114     root    3u      REG                9,2     88281  25450669 /var/log/monit.log
monit     22113 22114     root    4u      REG                9,2      1160    786446 /var/lib/monit/state
monit     22113 22114     root    5u     IPv4           12128234       0t0       TCP localhost:2812 (LISTEN)
```

**Comment by hallyn** [comment] 2015-12-24 00:07
On Wed, Dec 23, 2015 at 02:56:57PM -0800, Patrick Drotleff wrote:
> if you put
> ```
>  set httpd port 2812 and
>     use address localhost  # only accept connection from localhost
>     allow localhost        # allow localhost to connect to the server and
> ```
> into your monitrc
> 
> and do
> $ monit status
> 
> does it show the current time at "data collected"?

yes, and monit keeps running.

**Comment by hallyn** [comment] 2015-12-24 00:08
Hm, no /proc files in the lsof output.

**Comment by hallyn** [comment] 2015-12-24 02:29
Which kernel are you running?

**Comment by patrickd-** [comment] 2015-12-24 02:35
# uname -a
Linux 3.13.0-49-generic #83-Ubuntu SMP Fri Apr 10 20:11:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by alitvak69** [comment] 2016-01-07 11:40
Please forgive me for jumping on this but I am seeing another problem with monit in containers.  In my case monit doesn't send show any activity on monitoring ports of the services like ssh, mysql, SIP.  It looks like it check pid and then does nothing else.  I tried monit 5.15 and 5.9.  Monit doesn't restart the processes but strace doesn't show it doing anything on network.

Have you noticed that?

**Comment by stgraber** [comment] 2016-02-29 22:06
```
root@monit:~# apt install monit
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libfreetype6 os-prober
Use 'apt-get autoremove' to remove them.
Suggested packages:
  exim4 postfix mail-transport-agent
The following NEW packages will be installed:
  monit
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 286 kB of archives.
After this operation, 771 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu/ trusty/universe monit amd64 1:5.6-2 [286 kB]
Fetched 286 kB in 0s (317 kB/s)
Selecting previously unselected package monit.
(Reading database ... 24987 files and directories currently installed.)
Preparing to unpack .../monit_1%3a5.6-2_amd64.deb ...
Unpacking monit (1:5.6-2) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for ureadahead (0.100.0-16) ...
Setting up monit (1:5.6-2) ...
monit: Cannot translate 'monit' to FQDN name -- Name or service not known
 * Starting daemon monitor monit                                                                                                                        [ OK ] 
Processing triggers for ureadahead (0.100.0-16) ...
root@monit:~# service monit status
 * monit is running
root@monit:~# ps aux | grep monit
root      8982  0.0  0.0  34804  1652 ?        S    22:04   0:00 /usr/bin/monit -c /etc/monit/monitrc
root      9006  0.0  0.0   8868   616 ?        S+   22:04   0:00 grep --color=auto monit
root@monit:~# service monit stop
 * Stopping daemon monitor monit                                                                                                                        [ OK ] 
root@monit:~# ps aux | grep monit
root@monit:~# service monit start
monit: Cannot translate 'monit' to FQDN name -- Name or service not known
 * Starting daemon monitor monit                                                                                                                        [ OK ] 
root@monit:~# ps aux | grep monit
root      9043  0.0  0.0  34804  1676 ?        S    22:05   0:00 /usr/bin/monit -c /etc/monit/monitrc
root      9054  0.0  0.0   8868   740 ?        S+   22:05   0:00 grep --color=auto monit
root@monit:~# uname -a
Linux monit 4.4.0-8-generic #23~lxc201602240907 SMP Wed Feb 24 15:18:30 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
root@monit:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty
root@monit:~# 
```

That's with current LXD on Ubuntu 16.04 using the default kernel there, doesn't look like it's getting stuck anymore.

It could have been a kernel bug, or some bad interaction with lxcfs or cgroups, in any case, this doesn't appear to be an issue with current, lxd, lxc and kernel, so closing this issue.

**Comment by stgraber** [comment] 2016-02-29 22:10
Oh, just saw now the comment where you say it only happens after a while...

I'm still reasonably sure that this isn't a LXD issue. LXD and LXC only setup the container, they don't actively mess with it afterwards.

If this still happens to you when running current lxc, lxcfs and lxd (either from Ubuntu 16.04 or using the PPA), then I'd recommend you try to upgrade your kernel, ideally to a cgns capable kernel (Ubuntu 16.04's 4.4 would be best). That would rule out any lxcfs interaction.

I'm still closing this here as purely from a LXD point of view, this doesn't appear to be a bug on our side.

**Closed by stgraber** 2016-02-29 22:10 UTC
Labels: Bug

**Comment by hallyn** [comment] 2016-02-29 22:27
On Mon, Feb 29, 2016 at 02:10:09PM -0800, Stéphane Graber wrote:
> Oh, just saw now the comment where you say it only happens after a while...
> 
> I'm still reasonably sure that this isn't a LXD issue. LXD and LXC only setup the container, they don't actively mess with it afterwards.
> 
> If this still happens to you when running current lxc, lxcfs and lxd (either from Ubuntu 16.04 or using the PPA), then I'd recommend you try to upgrade your kernel, ideally to a cgns capable kernel (Ubuntu 16.04's 4.4 would be best). That would rule out any lxcfs interaction.

...  well, no, i'd actually think the lxcfs procfiles to be more likely
to be causing monit to freeze, so I for one wouldn't expect the cgns kernel
to stop lxcfs-caused freezes from happening.

**Comment by stgraber** [comment] 2016-02-29 22:41
I guess you're right. I was thinking that decreasing the load on lxcfs (all the cgroup reads) would make it less likely to lock up should it be the source of the problem.

**Comment by hallyn** [comment] 2016-02-29 22:44
Yup and it's even possible that the bug really is in only the cgroupfs
emulation part of lxcfs.  I'm just asking the original submitter to
keep lxcfs in the loop :)

Thanks!

**Comment by alitvak69** [comment] 2016-03-01 07:07
Stephane,

Thank you  for responding.  Would current versions mean those that come
from 16.04 ppa,  i.e. eventually stable / production?

**Comment by stgraber** [comment] 2016-03-01 16:44
@achanda Yes, either running 16.04 itself in a VM or some similar test environment or using our ppa:ubuntu-lxc/stable PPA which contains backports of all of those for older versions (except for the kernel).
