### ISSUE TITLE
Microcloud Init - Failed to get system resources of peer :  No auth secret in response

### ISSUE THREAD

**Issue by evoelise** [lxc/lxd#11706] opened 2023-05-20 11:17 UTC
When trying to init microcloud in a 3 server cluster I get the following error:

`Error: Failed to get system resources of peer "r520-03": No auth secret in response`

I am using the edge version of lxd as I want to try this with the new lxd GUI. 
I am using the latest version of microcloud on a fresh installation of Ubuntu 22.04.
Ubuntu and all snaps fully updated.

What can I do to diagnose this issue and resolve it?

To reproduce on 3 servers with a fresh install of Ubuntu Server 22.04 

```
sudo snap install lxd
sudo snap refresh lxd --edge
sudo snap install microceph microovn microcloud
```
Then run the init command:

```
testuser@r520-02:~$ sudo lxd --version
4.0.9
testuser@r520-02:~$ sudo microcloud --version
0.1
testuser@r520-02:~$ sudo uname -a
Linux r520-02 5.15.0-72-generic #79-Ubuntu SMP Wed Apr 19 08:22:18 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
testuser@r520-02:~$ sudo microcloud init
Using address "192.168.1.127" for MicroCloud
Limit search for other MicroCloud servers to 192.168.1.127/24? (yes/no) [default=yes]:
Scanning for eligible servers ...

 Selected "r520-03" at "192.168.1.128"
 Selected "r520-04" at "192.168.1.123"

Error: Failed to get system resources of peer "r520-04": No auth secret in response
```

This is shown in the syslog
`May 20 11:12:27 r520-02 kernel: [ 4768.307666] audit: type=1400 audit(1684581147.188:146): apparmor="DENIED" operation="open" profile="snap.microcloud.microcloud" name="/var/lib/snapd/hostfs/etc/ssl/certs/ca-certificates.crt" pid=5993 comm="microcloud" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
`

More information that may be useful:

```
testuser@r520-02:~$ snap services
Service            Startup   Current   Notes
lxd.activate       enabled   inactive  -
lxd.daemon         enabled   active    socket-activated
microceph.daemon   enabled   active    -
microceph.mds      disabled  inactive  -
microceph.mgr      disabled  inactive  -
microceph.mon      disabled  inactive  -
microceph.osd      disabled  inactive  -
microceph.rgw      disabled  inactive  -
microcloud.daemon  enabled   active    -
microovn.central   disabled  inactive  -
microovn.chassis   disabled  inactive  -
microovn.daemon    enabled   active    -
microovn.switch    disabled  inactive  -

testuser@r520-02:~$ snap list
Name        Version        Rev    Tracking       Publisher   Notes
core20      20230503       1891   latest/stable  canonical✓  base
core22      20230503       634    latest/stable  canonical✓  base
lxd         git-407205d    23988  4.0/edge       canonical✓  -
microceph   0+git.fdf6d5e  338    latest/stable  canonical✓  -
microcloud  0+git.9cb7ccd  412    latest/stable  canonical✓  -
microovn    0+git.f8a4497  91     latest/stable  canonical✓  -
snapd       2.59.2         19122  latest/stable  canonical✓  snapd

```

**Comment by tomponline** [comment] 2023-05-20 11:39
This error comes from microcloud and not lxd.

Its also a duplicate of https://github.com/canonical/microcloud/issues/107

**Closed by tomponline** 2023-05-20 11:39 UTC

**Comment by evoelise** [comment] 2023-05-20 12:08
Thanks tomponline - realised it was a microcloud issue but when I searched for microcloud issues on github I only saw these being reported in this project. Also it does not look to be the same issue as [canonical/microcloud#107](https://github.com/canonical/microcloud/issues/107) as this looks like an auth issue not a ovn/networking issue.

I have re-raised this in the microcloud project.

**Comment by tomponline** [comment] 2023-05-20 12:27
There's a few different errors on that issue, but the general issue seems to be that microcloud can't be initialized and there's one or more race conditions occurring.

**Comment by evoelise** [comment] 2023-05-20 12:35
> There's a few different errors on that issue, but the general issue seems to be that microcloud can't be initialized and there's one or more race conditions occurring.

Could be. This issue for me happens every time I try to init - it's not an intermittent issue. As my symptoms differ from what is reported in the other issue it is still useful I hope to raise this as a different issue, even if the cause is the same.

**Comment by tomponline** [comment] 2023-05-20 12:47
Ive never been able to complete the initialization either, fails with one of those 3 errors randomly
