### ISSUE TITLE
Can't change kernel.shmmax in lxd container

### ISSUE THREAD

**Issue by ackerleytng** [lxc/lxd#1372] opened 2015-12-04 02:11 UTC
I'm trying to install gitlab in an lxd container.

It's failing because postgresql requires a higher shmmax than the allocated 33554432 that the lxd container has.

How do I increase `kernel.shmmax` for the container?

I've tried running the container as privileged (I'm not sure what effect this has, since after doing

```
lxc config set gitlab security.privileged true
```

I don't seem to see any differences in my experience with the container (ssh, etc all the same))

When I try to set `kernel.shmmax` in the container, I get this

```
$ sudo sysctl -w kernel.shmmax 335544320
sysctl: setting key "kernel.shmmax": Read-only file system
```

**Comment by tomposmiko** [comment] 2015-12-04 09:50
You can set it on the host machine.

**Comment by ackerleytng** [comment] 2015-12-04 12:47
How do I set it in the host machine? The value for `kernel.shmmax` in the host machine is some large value that I don't remember, but it's definitely greater than 33554432.

**Comment by tomposmiko** [comment] 2015-12-04 12:57
Hmm, what about if you use unconfined container?

**Comment by ackerleytng** [comment] 2015-12-04 14:29
I should set `lxc.aa_profile = unconfined`, right? Any idea where that config should go or how to set it?

Anyway, I just tried on https://linuxcontainers.org/lxd/try-it/. The container (first) there has the same `kernel.shmmax` as the host (18446744073692774399). Any idea why that is the case? How might I set the container to have the same `kernel.shmmax` as the host on my own lxd? (To set up first on that trial thing, I followed the steps on that page, didn't do anything special)

**Comment by srkunze** [comment] 2015-12-04 15:53
> You can set it on the host machine.

**Comment by srkunze** [comment] 2015-12-04 15:54
> You can set it on the host machine.

Maybe, it's just me, but I got the feeling that containers should not influence the kernel of the host.

**Comment by ak5** [comment] 2015-12-06 09:08
I have the same issue here #1351

Was also trying to install Gitlab.

Changing the host settings do not influence the container ones.

**Comment by stgraber** [comment] 2015-12-10 21:30
Duplicate of #1351, closing.

**Closed by stgraber** 2015-12-10 21:30 UTC

**Comment by oerdnj** [comment] 2017-04-19 10:49
On Debian/Ubuntu system do this before upgrade:
```
dpkg-divert --local --divert /opt/gitlab/embedded/cookbooks/gitlab/definitions/sysctl.rb.gitlab --add /opt/gitlab/embedded/cookbooks/gitlab/definitions/sysctl.rb
edit /opt/gitlab/embedded/cookbooks/gitlab/definitions/sysctl.rb # and remove/comment-out the block starting with `# Load the settings right away`
```

The only downside is that you need to monitor the changes there, and update the `sysctl.rb` with the contents of `sysctl.rb.gitlab` if it has changed.
