### ISSUE TITLE
5 second delay due to Websocket timeout prevents retrieving operation status (raises Not Found)

### ISSUE THREAD

**Issue by maikeueule** [lxc/lxd#2797] opened 2017-01-17 16:06 UTC
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: ubuntu
 * Distribution version: xenial
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version:
   * LXD version:
   * Storage backend in use:
 lxc info
apiextensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses:
[...]
  architectures:
  - x86_64
  - i686
  certificate: |
[...]
  certificatefingerprint: [...]
  driver: lxc
  driverversion: 2.0.6
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-53-generic
  server: lxd
  serverpid: 22895
  serverversion: 2.6.2
  storage: zfs
  storageversion: "5"
config:
  core.https_address: 0.0.0.0:8443
  core.trust_password: true
  storage.zfs_pool_name: lxd-zfs-pool
public: false

# Issue description

The issue cannot be deterministically reproduced, althrough it happens with lxc commandline client (lxc exec), pylxd (container.execute) or using the REST API directly. The problem can be reproduced by many commands, even container creation.

Example (i kept only information of interest)
while true; do time lxc exec CONTAINER "ip addr show"; done 
real 0m0,456s
real 0m0,485s
[...]
real 0m5,521s
[...]

From my investigation, it seems related to the use of websockets for retrieving stdout/stderr. In certain conditions that i cannot determine, the websocket is not closed until there is a 5 second timeout. Unfortunately, this 5 second timeout prevent the retrieving of the operation (which is purged from LXD database) and i see clearly the REST call for retrieving the operation to fail with NotFound exception.

Thanks for any help on this issue.

**Comment by brauner** [comment] 2017-01-17 17:59
Hi, thanks for the bug report. Can you please see if you can reproduce this issue with `LXD 2.7`?

**Comment by maikeueule** [comment] 2017-01-17 22:55
Hi, thanks for your prompt answer.

Using the 2.7 version from the lxd ppa, I have exactly the same issues. 

Just as a side note, until I could reproduce it with commandline client, I first thought of a pylxd issue and commented on issue that seems similar, eg
https://github.com/lxc/pylxd/issues/182
While I'm not sure, it could in fact be the same problem (same 5 second delay...)

I have some code that trigger the code almost everytime, unfortunately that I cannot share in the immediate future, so I am available for any further test on this issue.

**Comment by maikeueule** [comment] 2017-01-17 23:16
Using such commands on my side triggers the issue almost all the time

while true; do time ssh LXDHOST lxc exec CONTAINER "ip addr show"; done

**Comment by stgraber** [comment] 2017-01-18 03:04
Does this only happen when passing an invalid command to LXD?

    lxc exec CONTAINER "ip addr show"

Is invalid because there are no binaries called "ip addr show". The valid command would be:

    lxc exec CONTAINER ip addr show


See:

```
stgraber@dakara:~$ lxc exec zesty "ip addr show"

stgraber@dakara:~$ lxc exec zesty ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
500: eth0@if501: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:16:3e:a8:34:79 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.156.0.64/24 brd 10.156.0.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fd42:a4f6:6365:4106:216:3eff:fea8:3479/64 scope global mngtmpaddr dynamic
       valid_lft 3151sec preferred_lft 3151sec
    inet6 fe80::216:3eff:fea8:3479/64 scope link
       valid_lft forever preferred_lft forever
```

**Comment by stgraber** [comment] 2017-01-18 03:05
I've just finished a loop of 1000 "time lxc exec zesty "ip addr show"" without seeing any one of them taking more than 100ms.

**Comment by raindylong** [comment] 2017-01-18 03:53
Same as @stgraber , run 2000 times "time lxc exec mycontainer ip addr show" , every time is less than 100ms (the containers are running ubuntu & centos) .
`sudo lxc --version
2.7
sudo lxd --version
2.7`

**Comment by maikeueule** [comment] 2017-01-18 09:00
Sorry, I made a mistake when trying to provide a command to reproduce the issue. I will continue investigating the issue and come back to you. Thanks for your time so far.

**Comment by maikeueule** [comment] 2017-01-18 09:52
New attempt, this time using pylxd.

Small test script:

> cat test.py 
> #!/usr/bin/env python3
> 
> import os, sys, shlex, pylxd
> 
> URL='https://localhost:8443'
> CONTAINER='ANONYMIZED'
> DEFAULT_CERT_PATH = './client_cert.pem'
> DEFAULT_KEY_PATH = './client_key.pem'
> 
> cmd = sys.argv[1]
> 
> client = pylxd.Client(endpoint = URL,
>         cert=(DEFAULT_CERT_PATH, DEFAULT_KEY_PATH),
>         verify=False)
> 
> container = client.containers.get(CONTAINER)
> print(cmd)
> print(container.execute(shlex.split(cmd)))
> 

Sometimes it works, and does so in a series.

> while true; do ./test.py "ip addr show"; done
> /usr/lib/python3/dist-packages/urllib3/connectionpool.py:794: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
>   InsecureRequestWarning)
> ip addr show
> ContainerExecuteResult(exit_code=0, stdout='1536: eth0@if1537: <BROADCAST,MULTICAST,UP,LOWER_UP>  [... ] \n', stderr='')
> /usr/lib/python3/dist-packages/urllib3/connectionpool.py:794: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
>   InsecureRequestWarning)

Sometimes it fails with NotFound again in a series.

> while true; do ./test.py "ip addr show"; done
> /usr/lib/python3/dist-packages/urllib3/connectionpool.py:794: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
>   InsecureRequestWarning)
> ip addr show
> Traceback (most recent call last):
>   File "./test.py", line 18, in <module>
>     print(container.execute(shlex.split(cmd)))
>   File "/usr/local/lib/python3.5/dist-packages/pylxd/models/container.py", line 243, in execute
>     operation = self.client.operations.get(operation_id)
>   File "/usr/local/lib/python3.5/dist-packages/pylxd/models/operation.py", line 37, in get
>     response = client.api.operations[operation_id].get()
>   File "/usr/local/lib/python3.5/dist-packages/pylxd/client.py", line 103, in get
>     self._assert_response(response, stream=kwargs.get('stream', False))
>   File "/usr/local/lib/python3.5/dist-packages/pylxd/client.py", line 68, in _assert_response
>     raise exceptions.NotFound(response)
> pylxd.exceptions.NotFound: not found

It seems the command does not matter much as soon as it executes "fast enough" (a wild guess). Using "hostname" is equivalent. Using "sleep 1" never triggers the bug.

**Comment by maikeueule** [comment] 2017-02-06 09:35
I managed to narrow the issue down a bit. 
It seems some commands trigger this error while trying to setup the pipes to read stdin from the Websocket.

lvl=dbug msg="Got error getting next reader websocket: close 1000 (normal), &{%!s(*os.file=&{102 slave <nil>})}" t=2017-02-06T10:22:13+0100 

This causes the WebSocket connection not to be closed and have the client wait until the websocket is destroyed when the operation is deleted on LXD side. And since the operation is no more present, we have the NotFound error.

I traced through the code, but not being familiar with go makes it a bit hard for me :)

**Comment by stgraber** [comment] 2017-02-06 19:24
@brauner Does that ring a bell?
@maikeueule am I right in assuming that you're on LXD 2.8 by now (you said you were using the PPA)?

**Comment by maikeueule** [comment] 2017-02-06 20:59
Yes the problem persists across all version up until 2.8. I noticed that in some scenarios where the error occurs deterministically (commands which completes "fast"), i could suppress it by executing "sleep 0.1 && COMMAND". Still I could not see where this could have an impact in the code which wait for websockets for stdin/stdout and stderr to be connected before running the command. 

The call that fails is in container_exec.go : 
>           <-shared.WebsocketRecvStream(ttys[i], s.conns[i])
Why it fails and why does this prevent the closing of the websocket is still unclear.

**Comment by brauner** [comment] 2017-02-06 21:28
Nah, @stgraber, doesn't ring a bell. It's not a problem I've encountered so far. To be honest, this is still very confusing so I'm just going to ask a couple of questions:

1. Is there a reliable reproducer by now?
  Without one I feel like there's barely a way to tackle this issue.
2. Does this occur in interactive or non-interactive mode or in both?
3. Can you reliably reproduce it using only lxc client tools (e.g. `lxc exec`)?
4. Is this only reproducible using the Python bindings? (Related to the 3.)

@stgraber, @maikeueule, do we know where the 5s delay/wait comes from? Is there a valid code-path that has this as timeout?

**Comment by maikeueule** [comment] 2017-02-06 21:46
I posted a small python script that triggers the issue on my side in the previous posts. The bug is not specific to python bindings, but we did not managed to get a successful reproduce so far. If the script that I posted does not trigger the issue on your side, i'll have make other attempts.

The 5 seconds delay corresponds to the operations purge in operations.go
>   time.AfterFunc(time.Second*5, func() {
which triggers the closing of the websocket somehow.

The weird thing is that despite the error, all pty/tty handlers are closed by LXD, but the stdin websocket remains unclosed.

**Comment by jordanauge** [comment] 2017-09-27 15:05
Hi,

I did not have the time to test yet, but i wonder to what extent this can be linked to the following report, updated very recently:
https://github.com/lxc/pylxd/issues/210

**Comment by maikeueule** [comment] 2017-09-27 15:08
Hi,

While I could not test yet, I feel like there is a link with the following report, updated very recently.
https://github.com/lxc/pylxd/issues/210

**Comment by stgraber** [comment] 2017-09-27 21:53
That one was a ws4py bug though right?

**Comment by maikeueule** [comment] 2017-09-28 10:21
Sure, but I was wondering to what extent the websocket library used by lxc could have similar issues. What i observed iirc was that the websocket connecting was timing out after 5 seconds, and at that time, the Operation was removed from the LXD database thus triggering the NotFound error.

In noted this comment in particular: "WebSocketManager is using level-triggered polling & blocking I/O, and so expects to be woken up whenever there is something to recv. The ssl sockets, however, will buffer in-memory, which epoll/select/etc. can't see."

**Comment by benjamincburns** [comment] 2019-04-01 21:47
I seem to be reproducing this issue quite reliably. I'm authoring a new LXD client library in TypeScript, and I'm in the process of adding `exec` return code support. If I attempt to `GET /1.0/operations/<id>` after the process I `exec` exits, I get a 404, and I cannot read the return value.

The code is here: https://github.com/trufflesuite/ts-lxd/blob/cd23b688119894a9e3003be406486385ee15576d/test/integration.test.ts#L193

The relevant line causes a `GET` to `/1.0/operations/<id>`, where `id` is the ID of the `exec` operation that was created during the beginning of the test. On my machine this always fails with an unhandled promise rejection due to a 404 being returned from `/1.0/operations/<id>`. It seems as though the operation disappears once the exec process exits.

Output of `lxc info` on my machine:

```
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- candid_authentication
- candid_config
- candid_config_key
- usb_optional_vendorid
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: 🤔
  certificate_fingerprint: 
  driver: lxc
  driver_version: 3.0.3
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.18.0-16-generic
  server: lxd
  server_pid: 530
  server_version: 3.0.3
  storage: zfs
  storage_version: 0.7.9-3ubuntu6
  server_clustered: false
  server_name: 🤔
  project: ""
```

**Comment by benjamincburns** [comment] 2019-04-01 21:52
Instructions for running that reproduction:

1. Install a recent version of nodejs (I highly recommend using [NVM](https://github.com/creationix/nvm) if you don't already)
2. Clone the repo and switch to the relevant branch: `git clone https://github.com/trufflesuite/ts-lxd.git && cd ts-lxd && git checkout lxd-exec-bug-repro`
3. Install dependencies (also builds the project): `npm install`
4. Run tests (only runs the test which includes the repro): `npm run test`

If you want to see requests & responses dumped to the console, do `DEBUG="ts-lxd:request" npm run test`.

**Comment by benjamincburns** [comment] 2019-04-01 22:07
I get the impression that the "correct" way to do this might be to open a separate request to `/1.0/operations/<id>/wait` and let that responding be an indicator of process termination. If this assumption is correct, I have a few other concerns...

1. How long of a timeout should I set?
2. Assuming I set a timeout and refresh the request when it expires, what happens if the process terminates while I'm refreshing said request?
3. Assuming I set an infinite timeout, how do I protect against infrastructure issues causing the request to hang indefinitely?

It would be much nicer, I think, if the exit code were sent via the control websocket on `exec` process termination.

**Comment by benjamincburns** [comment] 2019-04-01 22:28
Turns out I'm stupid and my library prepends `/1.0` to the beginning of the URL path, so I was in effect requesting `/1.0/1.0/operations/<id>`. Please disregard my previous messages.

**Comment by stgraber** [comment] 2019-09-23 20:02
Other than some rare issues with pylxd, we've never seen this hit anyone else in any other bindings or tests, so I'm going to close this issue at least for now.

If someone comes up with a clear reproducer or log showing such an issue on current LXD, please comment here and we'll gladly re-open the issue.

**Closed by stgraber** 2019-09-23 20:02 UTC
Labels: Bug, Incomplete
