### ISSUE TITLE
raw.idmap [ug]id-only settings causes strange mappings

### ISSUE THREAD

**Issue by cyphar** [lxc/lxd#5571] opened 2019-03-15 01:20 UTC
# Required information

 * Distribution: openSUSE Tumbleweed
 * Distribution version: 20190310

<details>
<summary>Output of "lxc info".</summary>

```
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIB9DCCAXqgAwIBAgIQVny+MTRKdIDBVDgmyQQ3LDAKBggqhkjOPQQDAzAzMRww
    GgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRMwEQYDVQQDDApyb290QHlhdmlu
    MB4XDTE5MDMxNDE0NTc0N1oXDTI5MDMxMTE0NTc0N1owMzEcMBoGA1UEChMTbGlu
    dXhjb250YWluZXJzLm9yZzETMBEGA1UEAwwKcm9vdEB5YXZpbjB2MBAGByqGSM49
    AgEGBSuBBAAiA2IABKG7IPdeJAe+1vrDPHoxsTGS569hT8IhycE9CY1o8+dypScO
    ljBOCFlacJgccg0FFkFwDMvSwfkoMrxVuXC3TkPfpOL7yrDufen1QL6WoeOL8td+
    hXvQb9qvJcWx47uWnaNTMFEwDgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsG
    AQUFBwMBMAwGA1UdEwEB/wQCMAAwHAYDVR0RBBUwE4IFeWF2aW6HBMCoK2yHBKwR
    AAEwCgYIKoZIzj0EAwMDaAAwZQIxAOg5rUFcCoTfB8yn+UcDeetjFbq1D1PjK7MB
    vKGaDANkHylq0xkmqV0vQ4nqxESWYgIwcCOMVz8cOfYC9CWLo+NtujfSwWavkGA8
    0duvyKYSNVIIFIIMyxWXqftbelzUToot
    -----END CERTIFICATE-----
  certificate_fingerprint: a883425462751a6a5ef8a9b73a382c22944c125cd1d9d662233dfc69e8cba5a3
  driver: lxc
  driver_version: 3.1.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 5.0.0-rc4-cyphar
  server: lxd
  server_pid: 557
  server_version: "3.11"
  storage: btrfs
  storage_version: "4.4"
  server_clustered: false
  server_name: yavin
  project: default
```
</details>

# Issue description

When using `raw.idmap` to map *only* a `uid` or `gid` (not `both`), one would expect that such "punch outs" shouldn't affect the other id type (I was trying to create a profile which would give users access to `video` and `audio` as well as a bunch of Xorg-related devices).

However, it appears that a `uid` mapping ends up with the corresponding `gid` being *unmapped* in the container. In addition, I've noticed that the mapping appears to include the entire `sub{u,g}id` space for the `lxd` user -- which appears to also be a bug.

# Steps to reproduce

First, set up `bad-profile`:

```
% lxc profile show bad-profile
config:
  raw.idmap: |
    uid 1000 1000
    gid 500 500
description: bad profile
devices: {}
name: bad-profile
used_by: []
```

And now start a container with it:

```
% lxc launch -p default -p bad-profile ubuntu:18.04 c1
Creating c1
Starting c1
```

And now check `/proc/self/[ug]id_map`.

```
% lxc exec c1 cat /proc/self/uid_map # uid 500 is unmapped
         0    1000000        500
       501    1000501        499
      1000       1000          1
      1001    1001001  999998999
% lxc exec c1 cat /proc/self/gid_map # gid 1000 is unmapped
         0    1000000        500
       500        500          1
       501    1000501        499
      1001    1001001  999998999
```

My `/etc/sub[ug]id`:

```
% cat /etc/subuid
lxd:1000000:1000001
% cat /etc/subgid
lxd:1000000:1000001
```

I've noticed that if you set `security.idmap.isolated=true` this issue gets resolved.

# Information to attach

* [`lxc config show c1 --expanded`](https://github.com/lxc/lxd/files/2969052/c1.txt)
* [`lxc monitor` log](https://github.com/lxc/lxd/files/2969049/monitor.log)

**Comment by stgraber** [comment] 2019-03-15 01:55
Hmm, yeah, there's something odd going on with the uig/gid handling, the generated internal structs don't make much sense either, I'll track this down tomorrow.

Assuming you're using the snap package, it's normal that /etc/subuid and /etc/subgid are ignored.
The snap doesn't ship those files in its version of /etc nor do we try to integrate with the host's one.
Instead we fallback to a built-in map starting at 1000000 and of size 1000000000 (if I recall correctly).
So that part may be behaving as intended.

In fact, the fact that we're not using subuid/subgid + newuidmap/newgidmap is the reason why the hole punch worked at all in your configuration as otherwise, you'd have needed individual entries for the uid and gid you wanted punched through (which would cause problems with other software assuming a single map per user).

**Comment by stgraber** [comment] 2019-03-15 01:56
```
    {"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":500}
    {"Isuid":false,"Isgid":true,"Hostid":500,"Nsid":500,"Maprange":1}
    {"Isuid":true,"Isgid":true,"Hostid":1000501,"Nsid":501,"Maprange":499}
    {"Isuid":true,"Isgid":false,"Hostid":1000,"Nsid":1000,"Maprange":1}
    {"Isuid":true,"Isgid":true,"Hostid":1001001,"Nsid":1001,"Maprange":999998999}
```

That's the internal structs for this case on my system, I'll do further testing and try to track down the source tomorrow.

**Comment by cyphar** [comment] 2019-03-15 02:59
The issue wasn't necessarily that it's being ignored -- it's that it's mapping *all* of the uids/gids that are given to `lxd` which means that you end up with non-isolated containers actually being able to `setresuid` to isolated container mappings.

My initial assumption was that non-isolated just means that the "base" mapping is used (but is the same size as isolated mappings), and for isolated containers a new section of the id-space is allocated. Otherwise, "isolated" would mean that it's only isolated from *other* isolated containers and not the default non-isolated ones (which feels a bit weird to me).

**Comment by stgraber** [comment] 2019-03-15 12:19
Yeah, that's expected behavior. If we were to do things again from scratch, we'd probably do it differently but the issue is that when we introduced `security.idmap.isolated`, this behavior was already in place.

Changing behavior would break anyone with a container which uses over 65536 uid/gid as is pretty common for people using centralized authentication (libnss-ldap/sssd both use uid/gid > 100000).

I guess we could make it clearer that if you're using security.idmap.isolated, you should use it for the entire system.

**Comment by stgraber** [comment] 2019-03-15 15:51
Ok, tracked it down to entries that are marked as both uid and gid, this isn't something that works well when we need to hole punch after and in every other case, we're tracking the two types independently so let's do it here too.

```
stgraber@castiana:~/data/code/lxc/lxd (stgraber/master)$ lxc exec test -- cat /proc/self/uid_map
         0    1000000       1000
      1000       1000          1
      1001    1001001  999998999
stgraber@castiana:~/data/code/lxc/lxd (stgraber/master)$ lxc exec test -- cat /proc/self/gid_map
         0    1000000        500
       500        500          1
       501    1000501  999999499
```

**Closed** 2019-03-15 16:43 UTC
