### ISSUE TITLE
Uevent-based matching for `unix-char` and `unix-block`

### ISSUE THREAD

**Issue by jsimonetti** [lxc/lxd#1750] opened 2016-03-12 17:51 UTC
It appears possible (for example with this library https://github.com/jessta/udev) to add udev device hotplug monitoring to lxd.

Allowing one to add devices similar to udev rules:
`lxc config device add ct1 udev subsystem="usb" attrs.idVendor="10c4" attrs.idProduct="ea60" group="serial" mode="0666" path=/dev/ttyUSB0`

And have this particular device auto mounted inside ct1 as /dev/ttyUSB0 at insert time would sound like a dream come true and one of the last hurdles I have to take to fully containerise all my current systems.

**Comment by stgraber** [comment] 2016-03-12 18:12
Yeah, we already have a uevent handler so we could do something like that, however we need to make sure the design is somewhat generic at the API level.

**Comment by stgraber** [comment] 2016-07-27 10:30
So I think there are two different cases, one is to dynamically pass unix-char/unix-block devices as they appear/disappear on the host.

The other case is to pass raw USB devices. I'm re-titling this bug to make it clear that it's about the former.

**Comment by pavlodvornikov** [comment] 2017-10-12 14:18
Is there any activity on this issue ?

**Comment by stgraber** [comment] 2017-10-12 14:23
Nope, it's not been a priority for us so far. We'd certainly be happy to review a branch that implements this though.

**Comment by pavlodvornikov** [comment] 2017-10-12 14:29
I am trying to use [usb-hotplug-with-lxd-containers](https://stgraber.org/2017/03/27/usb-hotplug-with-lxd-containers/) to connect to usb serial device from lxc container with no luck. The main problem that mentioned device apeears in container as raw usb device. I cant get serial interface to this device. 
```
root@test:~# modprobe usbserial vendor=0x0403 product=0x6001
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.10.0-19-generic/modules.dep.bin'
modprobe: FATAL: Module usbserial not found in directory /lib/modules/4.10.0-19-generic
```

**Comment by stgraber** [comment] 2017-10-12 14:36
Indeed, the USB passthrough is for libusb devices which serial USB ports aren't.

You can manually pass such devices using the "unix-char" device type. For hotplug, for now you'd need to use a custom udev rule on your host. Or contribute to LXD and add that particular feature.

**Comment by stgraber** [comment] 2017-11-04 00:36
Just to update this issue on what I think should be done here. I think we need a new unix-hotplug device type which would allow for /dev entries related to a device filter to be added to the container as they become available.

At its most basic, we'd be looking at:

    lxc config device add c1 usb-console unix-hotplug vendorid=067b productid=2303 required=true

This would then add any device node associated with this particular device to the container.
The options are the same as the usb device type but rather than passing /dev/bus/usb/... entries, we'd be looking at the udev database to track down any device nodes under /dev which are tied to that particular device.

More filters may be added later to deal with other types of device.

Other than having to track down those devices (likely through udev), the difficulty will also be to properly clean them up when they're disconnected. We want to make sure that a container can start with the devices pre-connected, or can have the devices connected later and then have them disconnected at any point with everything being cleaned up properly.

**Comment by Catramen** [comment] 2019-03-22 17:46
Should this be merged to 3995?

**Comment by stgraber** [comment] 2019-03-22 17:50
No, this is different and is why we split the issue in half in the first place.
See: https://github.com/lxc/lxd/issues/1750#issuecomment-341858481

**Comment by nvertigo21** [comment] 2019-04-15 15:28
I'd also like to see this feature. Passing a joystick through to a container for RetroPie but when the uevent changes on the host, I have to manually edit the container config.

**Comment by stgraber** [comment] 2019-04-15 16:06
Until then you can probably use a udev hook to run `lxc config device add` for you.

**Comment by splett2** [comment] 2019-09-23 16:47
hi, lily and I would like to claim this issue for our group.

**Comment by splett2** [comment] 2019-11-10 21:22
@stgraber 

Hi, we're going to start on this now. A few preliminary questions: 

1. in the example interface you gave:
lxc config device add c1 usb-console unix-hotplug vendorid=067b productid=2303 required=true

Would we also want to give a path, so that devices of vendorid 067b, productid 2303 are automatically mounted at a particular path? 

2. Also, it looks like devices.go already has a uevent listener (deviceEventListener) that runs USB event handlers , would USB events include both unix-char/block device events as well as USB device events? , or would we want to add a new channel for unix-char/block events.

**Comment by stgraber** [comment] 2019-11-10 21:40
1) That may be tricky as a particular device getting plugged in may result in multiple devices appearing in /dev, so for this one it may be best to not allow a path be provided, instead resolving what devices to pass in for the provided event

2) Right now the usb part of the uevent handler filters specifically for add/removed event of the usb device itself. That's the usb subsystem even prior to any driver involvement, so I don't believe that those events will help you figure out what devices to pass in. Instead you'll need to listen to later events for when the device nodes appear, check if those are related to devices you care about and if so, inject those devices.

Assuming you have a Linux system with USB around, you can take a look at the events using `udevadm monitor`, then plugging in a USB stick, a phone over USB or if you have one around, a USB serial adapter.

A USB stick should result in a /dev/sdX device showing up, a phone depending on configuration may show up as a block or as some kind of serial device (usually /dev/ttyACMX), a serial port will show up as either /dev/ttyACMX or /dev/ttyUSBX.

**Comment by splett2** [comment] 2019-11-12 19:17
So we would want to listen for udev events instead of uevents, I'm guessing, and from what I could glean from reading this https://github.com/systemd/systemd/blob/master/src/libudev/libudev-monitor.c
it looks like udev events still occur on the same socket as uevents but with group of 2 instead of 1.

**Comment by stgraber** [comment] 2019-11-12 21:33
My understanding was that udev was reacting to uevents, `udevadm monitor` being a nice way to see them but ultimately what we care about reacting on are the same raw uevents that triggered udev.

@brauner do you know what's going on with that group field?

**Comment by brauner** [comment] 2019-11-12 21:35
udev generates it's own events and the are _not_ from the kernel, i.e. they are specific to udev. See
```c
static MonitorNetlinkGroup monitor_netlink_group_from_string(const char *name) {
        if (!name)
                return MONITOR_GROUP_NONE;
        if (streq(name, "udev"))
                return MONITOR_GROUP_UDEV;
        if (streq(name, "kernel"))
                return MONITOR_GROUP_KERNEL;
        return _MONITOR_NETLINK_GROUP_INVALID;
}
```

**Comment by brauner** [comment] 2019-11-12 21:35
i.e. only the ones marked with `kernel` are actually from the kernel. these are the one you're usually interested in

**Comment by splett2** [comment] 2019-11-13 01:52
Ah, I think I misinterpreted what you meant by 
> Right now the usb part of the uevent handler filters specifically for add/removed event of the usb device itself. That's the usb subsystem even prior to any driver involvement, so I don't believe that those events will help you figure out what devices to pass in. Instead you'll need to listen to later events for when the device nodes appear, check if those are related to devices you care about and if so, inject those devices.

So if my understanding is right, we would be interested in adding a new channel to deviceNetLinkListener, filtering by subsystem block or char, passing that to a set of handler that would be installed by a new device type that we create (akin to usb.go/unix.go/etc) that can filter on product/vendor ID to handle hotplugging appropriately.

**Comment by stgraber** [comment] 2019-11-13 05:41
Yeah, the way I would do it is by modifying the uevent logic in LXD to just log every single event we get from the kernel. Then play with some USB devices to figure out what are the relevant events on plug/unplug which we can use to track down the device nodes that need to be passed in.

Once you have that, then you'd indeed want a new section in the uevent handler to process those specific events and match them with containers that showed interest for those devices.

**Comment by Lilyjjo** [comment] 2019-11-14 01:09
David and I are trying to figure out how to interact with the udev database. We're considering using the go package udev (https://godoc.org/github.com/farjump/go-libudev#Enumerate) or trying to read directly from the udev database file, but for this second option we're stuck because we are struggling to find this file's location. Would it be okay to use this go udev package or do you know where this database file is?

**Comment by stgraber** [comment] 2019-11-14 07:41
@Lilyjjo what do you need out of the udev database?

The only other case where we directly pull stuff from udev is in `lxd/resources` where we directly read some block data out of `/run/udev/data`.

**Comment by splett2** [comment] 2019-11-16 22:53
we wanted to use the udev database in our unix_hotplug device's Start function to determine whether a device with a matching vendor/product ID are present in the host. We took a look at how this was done for USB devices, but we weren't able to find files vendorID/productID file for the block device we were using.

**Comment by splett2** [comment] 2019-11-19 00:30
another issue we're running into is that when we plug in our USB stick, kernel block subsystem events don't have enough information to identify the device, for ex. we get a message like

add@/devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.0/host5/target5:0:0/5:0:0:0/block/sdbACTION=addDEVPATH=/devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.0/host5/target5:0:0/5:0:0:0/block/sdbSUBSYSTEM=blockMAJOR=8MINOR=16DEVNAME=sdbDEVTYPE=diskSEQNUM=8128

however, the udev event emitted after udev processes that message from the kernel is more detailed, and actually has the vendor ID and model ID to identify the device ie:

 libudev����((1��{����ACTION=addDEVPATH=/devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.0/host5/target5:0:0/5:0:0:0/block/sdbSUBSYSTEM=blockDEVNAME=/dev/sdbDEVTYPE=diskSEQNUM=8326MAJOR=8MINOR=16USEC_INITIALIZED=1610650787ID_VENDOR=USBID_VENDOR_ENC=USB\x20\x20\x20\x20\x20ID_VENDOR_ID=8633ID_MODEL=Flash_DiskID_MODEL_ENC=Flash\x20Disk\x20\x20\x20\x20\x20\x20ID_MODEL_ID=800aID_REVISION=1.00ID_SERIAL=USB_Flash_Disk_5CC8D82708168AD9-0:0ID_SERIAL_SHORT=5CC8D82708168AD9ID_TYPE=diskID_INSTANCE=0:0ID_BUS=usbID_USB_INTERFACES=:080650:ID_USB_INTERFACE_NUM=00ID_USB_DRIVER=usb-storageDEVLINKS=/dev/disk/by-id/usb-USB_Flash_Disk_5CC8D82708168AD9-0:0 /dev/disk/by-path/pci-0000:00:14.0-usb-0:1:1.0-scsi-0:0:0:0 /dev/disk/by-label/USB\x20DISK /dev/disk/by-uuid/BCD0-8B21ID_PATH=pci-0000:00:14.0-usb-0:1:1.0-scsi-0:0:0:0ID_PATH_TAG=pci-0000_00_14_0-usb-0_1_1_0-scsi-0_0_0_0ID_FS_LABEL=USB_DISKID_FS_LABEL_ENC=USB\x20DISKID_FS_UUID=BCD0-8B21ID_FS_UUID_ENC=BCD0-8B21ID_FS_VERSION=FAT32ID_FS_TYPE=vfatID_FS_USAGE=filesystem.ID_FS_TYPE_NEW=vfat.MM_USBIFNUM=00TAGS=:systemd:

so we're thinking about using udev events to handle hotplugging of unix-char/unix-block devices, by adding a function similar to deviceNetLinkListener that listens to udev events rather than kernel uevents. Does this seem like a reasonable action?

**Comment by stgraber** [comment] 2019-11-19 03:58
Does setting `Groups` to `3` rather than `1` in `deviceNetlinkListener` get you both of the event groups?

According to kernel documentation, `Groups` is a bitmask to select what netlink multicast groups to connect to, so you should be able to connect to both and save a go routine and netlink fd.

**Comment by Lilyjjo** [comment] 2019-11-22 18:04
@stgraber 
Hi, 

So an update on what we're planning for the implementation:
1.) Modifying deviceNetlinkListener to listen on group 3 (this does allow us to get both udev and kernel events in the same go routine) and adding a new channel for unix-hotplug devices in deviceEventListener
2.) creating unix_hotplug.go to manage the new device type unixHotplug, and creating device_utils_unix_hotplug_events.go to handle the corresponding UnixHotplugEvents. These two files will be similar in logic to how the USB device was written 
3.) Using a go libudev package (https://github.com/farjump/go-libudev) to help us resolve devices when Start() is called on the unix-hotplug devices. The issue we're trying to solve here is finding which devices exist at the time of the Start() call. The usb handler version of this problem just collects devices from "/sys/bus/usb/devices" but we're running into the issue that the devices corresponding to the unix block and char types inside of the /sys/block don't have product and vendor IDs in their uevent files like the same usb entries do. This GitHub package allows us to search the udev database for devices based on the product and vendor IDs, which we then can use to resolve which device nodes are attached to the returned matching device.

Questions: 
- Is it okay to use a 3rd party go package? Using this go-libudev package for (3) requires that the machine have installed on it the Debian package libudev-dev. It also then needs this go package added to the go workspace from it's GitHub. We're not sure if that's something the LXD community likes to do. An alternative we can try doing is writing a C extension so we don't have to include this 3rd party package, but we'd still need the libudev-dev Debian package

**Comment by stgraber** [comment] 2019-11-26 07:29
Approach sounds go. Using go-libudev is fine for now. We may or may not switch to directly reading the udev database, but that's something that I can take a look at later, not a blocker for this work.

**Comment by Lilyjjo** [comment] 2019-11-28 16:42
@stgraber 
Hello,

We've got the code working and are almost ready to submit a pull request, we just have to write the tests and organize the commits. We did have a few more questions before we do:
1.) Should we make the product ID or vendor ID mandatory? We're not sure what the expected behavior is of the code if no product or vendor ID is specified 
2.) Should we add to api.go/api-extentions.md? We're not sure what qualifies as an api extension
3.) We've added a new method called 'unixDeviceSetupBlockNum()' which is basically the same method as 'unixDeviceSetupCharNum()' except the fake config it makes is a unix-block type instead of unix-char. Would you prefer we combine these two methods into something more generic and change all of the uses of 'unixDeviceSetupCharNum()' to use the new generic method?

**Comment by tomponline** [comment] 2019-11-28 16:52
@Lilyjjo in response to question 3, it would be good to see the draft PR first to understand how much re-use there are between the 2 functions as to whether its worth combining them or not. Thanks

**Comment by tomponline** [comment] 2019-11-28 16:54
@Lilyjjo if you have added any new config keys or values then this would count as an API extension as I understand it.

**Comment by stgraber** [comment] 2019-11-28 21:08
@Lilyjjo yeah, one of productID or vendorID must be provided, we may change that later if adding other ways to match the devices, but for now, one of the two is needed at a minimum.

And yeah, this needs an API extension, anything which adds a new user visible functionality does, we use those strings to allow various clients to detect whether a particular LXD server will support the feature they're trying to use.

**Comment by Lilyjjo** [comment] 2019-11-29 17:43
@stgraber @tomponline 
Hi,

We made a pull request for the question of the generalization of  'unixDeviceSetupCharNum()'.

Our code works like the USB code does from the manual testing we've done. We based the unix-hotplug device's logic off of the USB device's logic and we're having some odd behaviors that the USB device code also has:
(1)  If a running container has a hotplug device that has required=true, if the hotplug device is removed from the host, the running container doesn't stop even though it is now missing a required device (the device is removed/clean up properly). If we stop and then start the container, the container will still fail to launch due to the device missing. Is this the expected behavior?
(2)  If we have LXD running with a running container inside of it who has a hotplug device with an entry in the /dev folder, if we stop LXD and remove the hotplugged device and then start LXD again, the container still has the device inside of the /dev folder even though there is no device backing it on the host. The USB and our unix-hotplug code both do this. Do y'all have recommendation on how to fix this?

Finally, we're struggling on writing tests for our unix-hotplug device code. We were going to copy the USB device code tests since the logic is similar, but we're having difficulty finding tests for the USB device code. Are there tests for the USB device somewhere? 

Thanks

**Comment by stgraber** [comment] 2019-11-29 20:12
1) Yes, that is the expected behavior. `required` is only enforced during startup, we don't actually want containers getting stopped if the device later goes missing.

2) Not sure how much we can really do about this case and I suspect it's likely fine to ignore right now given that LXD restarts last only a few seconds. Indeed a device going away during that time interval wouldn't be noticed as no uevent handler will be running to detect it.

3) I believe both usb and unix-hotplug are effectively untestable code, at least as far as our testsuite is concerned. We could probably trick the kernel by using nested containers and injected uevents to act like a device got added, but it's one case where the complexity of the test logic would far exceed that of the tested feature... For now, lets just rely on manual testing.

**Comment by stgraber** [comment] 2020-02-02 21:24
This has now been implemented.

**Closed by stgraber** 2020-02-02 21:24 UTC
Labels: API, Documentation, Feature
