### ISSUE TITLE
Cannot start multiple containers with static IP/MAC with LXD 2.16

### ISSUE THREAD

**Issue by vtlrazin** [lxc/lxd#3641] opened 2017-08-08 10:52 UTC
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: Ubuntu
 * Distribution version: Ubuntu 16.04.3 LTS

 * The output of "lxc info" or if that fails: 

```
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 10.143.119.23:8443
  - 10.10.23.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |****
  certificate_fingerprint: ****
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-87-generic
  server: lxd
  server_pid: 4821
  server_version: "2.16"
  storage: dir
  storage_version: "1"

```
   * Kernel version: 4.4.0-87-generic
   * LXC version: 2.0.8
   * LXD version: 2.16
   * Storage backend in use: dir

# Issue description
When I try to start multiple containers with provided MAC address only last get expected IP address from dnsmasq configuration file.
Example:
`for i in {2..10}; do lxc init ubuntu:16.04 c23$i; lxc config set c23$i volatile.eth0.hwaddr "00:16:3e:23:01:$(printf '%02x' $i)";lxc start c23$i; done`

A brief description of what failed or what could be improved.

When I start single container with the same command it's working properly.
Example:
`for i in {2..2}; do lxc init ubuntu:16.04 c23$i; lxc config set c23$i volatile.eth0.hwaddr "00:16:3e:23:01:$(printf '%02x' $i)";lxc start c23$i; done`

# Steps to reproduce

 1. Install Ubuntu 16.04.3 LTS

 2. Install latest LXD (LXD 2.16)
     
 `#add-apt-repository ppa:ubuntu-lxc/lxd-stable`
 `#apt-get update && apt-get install lxd -y`

 3. Provide initial configuration:
     ` #lxd init`
 4. Change settings of default switch lxdbr0
     ` #lxc network set lxdbr0 ipv6.address=none ipv4.address=10.10.23.1/24 ipv4.nat=true raw.dnsmasq="conf-file=/etc/dnsmasq.conf.lab"`
 
 5. Add host information to dnsmasq.conf.lab
     ` #for i in {2..10}; do echo "dhcp-host=00:16:3e:23:01:$(printf '%02x' $i),c23$i,10.10.23.$i" >> /etc/dnsmasq.conf.lab ; done
`
Example of dnsmasq.conf.lab:

 ```
# cat /etc/dnsmasq.conf.lab
domain=lab-ml.cloudx.mlnx
log-queries
log-dhcp
dhcp-option=6,8.8.8.8,8.8.4.4
dhcp-host=00:16:3e:23:01:02,c232,10.10.23.2
dhcp-host=00:16:3e:23:01:03,c233,10.10.23.3
dhcp-host=00:16:3e:23:01:04,c234,10.10.23.4
dhcp-host=00:16:3e:23:01:05,c235,10.10.23.5
dhcp-host=00:16:3e:23:01:06,c236,10.10.23.6
dhcp-host=00:16:3e:23:01:07,c237,10.10.23.7
dhcp-host=00:16:3e:23:01:08,c238,10.10.23.8
dhcp-host=00:16:3e:23:01:09,c239,10.10.23.9
dhcp-host=00:16:3e:23:01:0a,c2310,10.10.23.10

```

 6. Restart lxd service
       `#systemctl restart lxd`

LXD service status:

```
# systemctl status lxd | cat
\u25cf lxd.service - LXD - main daemon
   Loaded: loaded (/lib/systemd/system/lxd.service; indirect; vendor preset: enabled)
   Active: active (running) since Tue 2017-08-08 11:26:36 IDT; 9s ago
     Docs: man:lxd(1)
  Process: 31474 ExecStartPost=/usr/bin/lxd waitready --timeout=600 (code=exited, status=0/SUCCESS)
  Process: 31462 ExecStartPre=/usr/lib/x86_64-linux-gnu/lxc/lxc-apparmor-load (code=exited, status=0/SUCCESS)
 Main PID: 31473 (lxd)
    Tasks: 32
   Memory: 345.8M
      CPU: 761ms
   CGroup: /system.slice/lxd.service
           \u251c\u250031473 /usr/bin/lxd --group lxd --logfile=/var/log/lxd/lxd.log
           \u2514\u250031538 dnsmasq --strict-order --bind-interfaces --pid-file=/var/lib/lxd/networks/lxdbr0/dnsmasq.pid --except-interface=lo --interface=lxdbr0 --listen-address=10.10.23.1 --dhcp-no-override --dhcp-authoritative --dhcp-leasefile=/var/lib/lxd/networks/lxdbr0/dnsmasq.leases --dhcp-hostsfile=/var/lib/lxd/networks/lxdbr0/dnsmasq.hosts --dhcp-range 10.10.23.2,10.10.23.254,1h -s lxd -S /lxd/ --conf-file=/var/lib/lxd/networks/lxdbr0/dnsmasq.raw -u lxd

Aug 08 11:26:36 clx-mld-23 dnsmasq[31538]: using local addresses only for domain lxd
Aug 08 11:26:36 clx-mld-23 dnsmasq[31538]: reading /etc/resolv.conf
Aug 08 11:26:36 clx-mld-23 dnsmasq[31538]: using local addresses only for domain lxd
Aug 08 11:26:36 clx-mld-23 dnsmasq[31538]: using nameserver 10.143.119.101#53
Aug 08 11:26:36 clx-mld-23 dnsmasq[31538]: using nameserver 8.8.8.8#53
Aug 08 11:26:36 clx-mld-23 dnsmasq[31538]: read /etc/hosts - 5 addresses
Aug 08 11:26:36 clx-mld-23 dnsmasq-dhcp[31538]: read /var/lib/lxd/networks/lxdbr0/dnsmasq.hosts
Aug 08 11:26:36 clx-mld-23 dnsmasq[31538]: read /etc/hosts - 5 addresses
Aug 08 11:26:36 clx-mld-23 dnsmasq-dhcp[31538]: read /var/lib/lxd/networks/lxdbr0/dnsmasq.hosts
Aug 08 11:26:36 clx-mld-23 systemd[1]: Started LXD - main daemon.
```

 7. Start nine containers with script:
      `#for i in {2..10}; do lxc init ubuntu:16.04 c23$i; lxc config set c23$i volatile.eth0.hwaddr "00:16:3e:23:01:$(printf '%02x' $i)";lxc start c23$i; done`

after start we can see:

 ```
# lxc ls
+-------+---------+---------------------+------+------------+-----------+
| NAME  |  STATE  |        IPV4         | IPV6 |    TYPE    | SNAPSHOTS |
+-------+---------+---------------------+------+------------+-----------+
| c2310 | RUNNING | 10.10.23.10 (eth0)  |      | PERSISTENT | 0         |
+-------+---------+---------------------+------+------------+-----------+
| c232  | RUNNING | 10.10.23.141 (eth0) |      | PERSISTENT | 0         |
+-------+---------+---------------------+------+------------+-----------+
| c233  | RUNNING | 10.10.23.142 (eth0) |      | PERSISTENT | 0         |
+-------+---------+---------------------+------+------------+-----------+
| c234  | RUNNING | 10.10.23.143 (eth0) |      | PERSISTENT | 0         |
+-------+---------+---------------------+------+------------+-----------+
| c235  | RUNNING | 10.10.23.144 (eth0) |      | PERSISTENT | 0         |
+-------+---------+---------------------+------+------------+-----------+
| c236  | RUNNING | 10.10.23.145 (eth0) |      | PERSISTENT | 0         |
+-------+---------+---------------------+------+------------+-----------+
| c237  | RUNNING | 10.10.23.146 (eth0) |      | PERSISTENT | 0         |
+-------+---------+---------------------+------+------------+-----------+
| c238  | RUNNING | 10.10.23.147 (eth0) |      | PERSISTENT | 0         |
+-------+---------+---------------------+------+------------+-----------+
| c239  | RUNNING | 10.10.23.148 (eth0) |      | PERSISTENT | 0         |
+-------+---------+---------------------+------+------------+-----------+
```

# Information to attach

 - [ ] any relevant kernel output (`dmesg`)
         no errors
 - [ ] container log (`lxc info NAME --show-log`)
Logs of two containers c232 and c2310

```
#lxc config show c232
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 16.04 LTS amd64 (release) (20170803)
  image.label: release
  image.os: ubuntu
  image.release: xenial
  image.serial: "20170803"
  image.version: "16.04"
  volatile.base_image: e18a3ad7d8b1978670bfa01d03ca4736d3a221a4dd38dab406062cdb09245381
  volatile.eth0.hwaddr: 00:16:3e:23:01:02
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
devices: {}
ephemeral: false
profiles:
- default
stateful: false
description: ""

# lxc config show c2310
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 16.04 LTS amd64 (release) (20170803)
  image.label: release
  image.os: ubuntu
  image.release: xenial
  image.serial: "20170803"
  image.version: "16.04"
  volatile.base_image: e18a3ad7d8b1978670bfa01d03ca4736d3a221a4dd38dab406062cdb09245381
  volatile.eth0.hwaddr: 00:16:3e:23:01:0a
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
devices: {}
ephemeral: false
profiles:
- default
stateful: false
description: ""

```

 - [ ] main daemon log (`cat /var/log/lxd/lxd.log`)

Part of /var/log/lxd/lxd.log with creating containers:

```
ephemeral=false lvl=info msg="Creating container" name=c232 t=2017-08-08T13:13:09+0300
ephemeral=false lvl=info msg="Created container" name=c232 t=2017-08-08T13:13:09+0300
action=start created=2017-08-08T10:13:09+0000 ephemeral=false lvl=info msg="Starting container" name=c232 stateful=false t=2017-08-08T13:13:11+0300 used=1970-01-01T00:00:00+0000
action=start created=2017-08-08T10:13:09+0000 ephemeral=false lvl=info msg="Started container" name=c232 stateful=false t=2017-08-08T13:13:11+0300 used=1970-01-01T00:00:00+0000
ephemeral=false lvl=info msg="Creating container" name=c233 t=2017-08-08T13:13:11+0300
ephemeral=false lvl=info msg="Created container" name=c233 t=2017-08-08T13:13:11+0300
action=start created=2017-08-08T10:13:11+0000 ephemeral=false lvl=info msg="Starting container" name=c233 stateful=false t=2017-08-08T13:13:13+0300 used=1970-01-01T00:00:00+0000
action=start created=2017-08-08T10:13:11+0000 ephemeral=false lvl=info msg="Started container" name=c233 stateful=false t=2017-08-08T13:13:14+0300 used=1970-01-01T00:00:00+0000
ephemeral=false lvl=info msg="Creating container" name=c234 t=2017-08-08T13:13:14+0300
ephemeral=false lvl=info msg="Created container" name=c234 t=2017-08-08T13:13:14+0300
action=start created=2017-08-08T10:13:14+0000 ephemeral=false lvl=info msg="Starting container" name=c234 stateful=false t=2017-08-08T13:13:15+0300 used=1970-01-01T00:00:00+0000
action=start created=2017-08-08T10:13:14+0000 ephemeral=false lvl=info msg="Started container" name=c234 stateful=false t=2017-08-08T13:13:16+0300 used=1970-01-01T00:00:00+0000
ephemeral=false lvl=info msg="Creating container" name=c235 t=2017-08-08T13:13:16+0300
ephemeral=false lvl=info msg="Created container" name=c235 t=2017-08-08T13:13:16+0300
action=start created=2017-08-08T10:13:16+0000 ephemeral=false lvl=info msg="Starting container" name=c235 stateful=false t=2017-08-08T13:13:17+0300 used=1970-01-01T00:00:00+0000
action=start created=2017-08-08T10:13:16+0000 ephemeral=false lvl=info msg="Started container" name=c235 stateful=false t=2017-08-08T13:13:17+0300 used=1970-01-01T00:00:00+0000
ephemeral=false lvl=info msg="Creating container" name=c236 t=2017-08-08T13:13:18+0300
ephemeral=false lvl=info msg="Created container" name=c236 t=2017-08-08T13:13:18+0300
action=start created=2017-08-08T10:13:18+0000 ephemeral=false lvl=info msg="Starting container" name=c236 stateful=false t=2017-08-08T13:13:19+0300 used=1970-01-01T00:00:00+0000
action=start created=2017-08-08T10:13:18+0000 ephemeral=false lvl=info msg="Started container" name=c236 stateful=false t=2017-08-08T13:13:19+0300 used=1970-01-01T00:00:00+0000
ephemeral=false lvl=info msg="Creating container" name=c237 t=2017-08-08T13:13:19+0300
ephemeral=false lvl=info msg="Created container" name=c237 t=2017-08-08T13:13:19+0300
action=start created=2017-08-08T10:13:19+0000 ephemeral=false lvl=info msg="Starting container" name=c237 stateful=false t=2017-08-08T13:13:21+0300 used=1970-01-01T00:00:00+0000
action=start created=2017-08-08T10:13:19+0000 ephemeral=false lvl=info msg="Started container" name=c237 stateful=false t=2017-08-08T13:13:21+0300 used=1970-01-01T00:00:00+0000
ephemeral=false lvl=info msg="Creating container" name=c238 t=2017-08-08T13:13:21+0300
ephemeral=false lvl=info msg="Created container" name=c238 t=2017-08-08T13:13:21+0300
action=start created=2017-08-08T10:13:21+0000 ephemeral=false lvl=info msg="Starting container" name=c238 stateful=false t=2017-08-08T13:13:23+0300 used=1970-01-01T00:00:00+0000
action=start created=2017-08-08T10:13:21+0000 ephemeral=false lvl=info msg="Started container" name=c238 stateful=false t=2017-08-08T13:13:23+0300 used=1970-01-01T00:00:00+0000
ephemeral=false lvl=info msg="Creating container" name=c239 t=2017-08-08T13:13:23+0300
ephemeral=false lvl=info msg="Created container" name=c239 t=2017-08-08T13:13:23+0300
action=start created=2017-08-08T10:13:23+0000 ephemeral=false lvl=info msg="Starting container" name=c239 stateful=false t=2017-08-08T13:13:25+0300 used=1970-01-01T00:00:00+0000
action=start created=2017-08-08T10:13:23+0000 ephemeral=false lvl=info msg="Started container" name=c239 stateful=false t=2017-08-08T13:13:25+0300 used=1970-01-01T00:00:00+0000
ephemeral=false lvl=info msg="Creating container" name=c2310 t=2017-08-08T13:13:25+0300
ephemeral=false lvl=info msg="Created container" name=c2310 t=2017-08-08T13:13:25+0300
action=start created=2017-08-08T10:13:25+0000 ephemeral=false lvl=info msg="Starting container" name=c2310 stateful=false t=2017-08-08T13:13:28+0300 used=1970-01-01T00:00:00+0000
action=start created=2017-08-08T10:13:25+0000 ephemeral=false lvl=info msg="Started container" name=c2310 stateful=false t=2017-08-08T13:13:32+0300 used=1970-01-01T00:00:00+0000

```

 - [ ] output of the client with --debug
 - [ ] output of the daemon with --debug

**Comment by stgraber** [comment] 2017-08-08 18:35
You may want to check /var/log/syslog to confirm that the containers are reaching dnsmasq with the expected MAC address. If that's the case, then it feels like a dnsmasq bug to me as LXD's job in your environment is really just to start the container with the MAC you set.

**Comment by vtlrazin** [comment] 2017-08-09 18:30
Hi Stéphane,

Please see below part of  /var/log/syslog with confirmation that the container are reaching dnsmasq with the expected MAC address

```
Aug  9 21:28:33 clx-mld-23 dnsmasq-dhcp[23733]: 2425051424 available DHCP range: 10.10.23.2 -- 10.10.23.254
Aug  9 21:28:33 clx-mld-23 dnsmasq-dhcp[23733]: 2425051424 client provides name: c232
Aug  9 21:28:36 clx-mld-23 dnsmasq-dhcp[23733]: 2425051424 DHCPDISCOVER(lxdbr0) 00:16:3e:23:01:02
Aug  9 21:28:36 clx-mld-23 dnsmasq-dhcp[23733]: 2425051424 tags: known, lxdbr0
Aug  9 21:28:36 clx-mld-23 dnsmasq-dhcp[23733]: 2425051424 DHCPOFFER(lxdbr0) 10.10.23.77 00:16:3e:23:01:02
Aug  9 21:28:36 clx-mld-23 dnsmasq-dhcp[23733]: 2425051424 requested options: 1:netmask, 28:broadcast, 2:time-offset, 3:router,
Aug  9 21:28:36 clx-mld-23 dnsmasq-dhcp[23733]: 2425051424 requested options: 15:domain-name, 6:dns-server, 119:domain-search,
Aug  9 21:28:36 clx-mld-23 dnsmasq-dhcp[23733]: 2425051424 requested options: 12:hostname, 44:netbios-ns, 47:netbios-scope,
Aug  9 21:28:36 clx-mld-23 dnsmasq-dhcp[23733]: 2425051424 requested options: 26:mtu, 121:classless-static-route, 42:ntp-server
Aug  9 21:28:36 clx-mld-23 dnsmasq-dhcp[23733]: 2425051424 next server: 10.10.23.1
Aug  9 21:28:36 clx-mld-23 dnsmasq-dhcp[23733]: 2425051424 sent size:  1 option: 53 message-type  2
Aug  9 21:28:36 clx-mld-23 dnsmasq-dhcp[23733]: 2425051424 sent size:  4 option: 54 server-identifier  10.10.23.1
Aug  9 21:28:36 clx-mld-23 dnsmasq-dhcp[23733]: 2425051424 sent size:  4 option: 51 lease-time  2h
Aug  9 21:28:36 clx-mld-23 dnsmasq-dhcp[23733]: 2425051424 sent size:  4 option: 58 T1  1h
Aug  9 21:28:36 clx-mld-23 dnsmasq-dhcp[23733]: 2425051424 sent size:  4 option: 59 T2  1h45m
Aug  9 21:28:36 clx-mld-23 dnsmasq-dhcp[23733]: 2425051424 sent size:  4 option:  1 netmask  255.255.255.0
Aug  9 21:28:36 clx-mld-23 dnsmasq-dhcp[23733]: 2425051424 sent size:  4 option: 28 broadcast  10.10.23.255
Aug  9 21:28:36 clx-mld-23 dnsmasq-dhcp[23733]: 2425051424 sent size:  4 option:  3 router  10.10.23.1
Aug  9 21:28:36 clx-mld-23 dnsmasq-dhcp[23733]: 2425051424 sent size: 18 option: 15 domain-name  lab-ml.cloudx.mlnx
Aug  9 21:28:36 clx-mld-23 dnsmasq-dhcp[23733]: 2425051424 sent size:  4 option: 12 hostname  c232
Aug  9 21:28:36 clx-mld-23 dnsmasq-dhcp[23733]: 2425051424 sent size:  8 option:  6 dns-server  8.8.8.8, 8.8.4.4

```
As we can see container ask expected MAC address but receive random IPV4.

B.R.
Vitaliy

**Comment by stgraber** [comment] 2017-08-10 04:10
Hi,

Okay, so that suggests that there's nothing actually wrong with LXD in this case but that it's instead a dnsmasq issue that you're running into.

That being said, you could also set the static DHCP assignment through LXD, which may help:
```
stgraber@castiana:~$ for i in {2..10}; do lxc init ubuntu:16.04 c23$i; lxc config device add c23$i eth0 nic nictype=bridged parent=lxdbr0 ipv4.address=10.204.119.$((i+100));lxc start c23$i; done
Creating c232
Device eth0 added to c232
Creating c233
Device eth0 added to c233
Creating c234
Device eth0 added to c234
Creating c235
Device eth0 added to c235
Creating c236
Device eth0 added to c236
Creating c237
Device eth0 added to c237
Creating c238
Device eth0 added to c238
Creating c239
Device eth0 added to c239
Creating c2310
Device eth0 added to c2310
```

```
root@castiana:~# lxc list c2
+-------+---------+-----------------------+----------------------------------------------+------------+-----------+
| NAME  |  STATE  |         IPV4          |                     IPV6                     |    TYPE    | SNAPSHOTS |
+-------+---------+-----------------------+----------------------------------------------+------------+-----------+
| c2310 | RUNNING | 10.204.119.110 (eth0) | 2001:470:b368:4242:216:3eff:fe64:c999 (eth0) | PERSISTENT | 0         |
+-------+---------+-----------------------+----------------------------------------------+------------+-----------+
| c232  | RUNNING | 10.204.119.102 (eth0) | 2001:470:b368:4242:216:3eff:fe53:5181 (eth0) | PERSISTENT | 0         |
+-------+---------+-----------------------+----------------------------------------------+------------+-----------+
| c233  | RUNNING | 10.204.119.103 (eth0) | 2001:470:b368:4242:216:3eff:fee9:a37a (eth0) | PERSISTENT | 0         |
+-------+---------+-----------------------+----------------------------------------------+------------+-----------+
| c234  | RUNNING | 10.204.119.104 (eth0) | 2001:470:b368:4242:216:3eff:fefd:c9ab (eth0) | PERSISTENT | 0         |
+-------+---------+-----------------------+----------------------------------------------+------------+-----------+
| c235  | RUNNING | 10.204.119.105 (eth0) | 2001:470:b368:4242:216:3eff:fe66:7442 (eth0) | PERSISTENT | 0         |
+-------+---------+-----------------------+----------------------------------------------+------------+-----------+
| c236  | RUNNING | 10.204.119.106 (eth0) | 2001:470:b368:4242:216:3eff:fefa:d220 (eth0) | PERSISTENT | 0         |
+-------+---------+-----------------------+----------------------------------------------+------------+-----------+
| c237  | RUNNING | 10.204.119.107 (eth0) | 2001:470:b368:4242:216:3eff:feed:b5c0 (eth0) | PERSISTENT | 0         |
+-------+---------+-----------------------+----------------------------------------------+------------+-----------+
| c238  | RUNNING | 10.204.119.108 (eth0) | 2001:470:b368:4242:216:3eff:fef5:4d3f (eth0) | PERSISTENT | 0         |
+-------+---------+-----------------------+----------------------------------------------+------------+-----------+
| c239  | RUNNING | 10.204.119.109 (eth0) | 2001:470:b368:4242:216:3eff:fe1c:d17d (eth0) | PERSISTENT | 0         |
+-------+---------+-----------------------+----------------------------------------------+------------+-----------+
```

That being said, I'm not sure why LXD handling this would work any better than what you're doing, seeing how LXD generates dhcp-host entries for you in this case:

```
root@castiana:~# grep c2 /var/lib/lxd/networks/lxdbr0/dnsmasq.hosts 
00:16:3e:64:c9:99,id:*,10.204.119.110,c2310
00:16:3e:53:51:81,id:*,10.204.119.102,c232
00:16:3e:e9:a3:7a,id:*,10.204.119.103,c233
00:16:3e:fd:c9:ab,id:*,10.204.119.104,c234
00:16:3e:66:74:42,id:*,10.204.119.105,c235
00:16:3e:fa:d2:20,id:*,10.204.119.106,c236
00:16:3e:ed:b5:c0,id:*,10.204.119.107,c237
00:16:3e:f5:4d:3f,id:*,10.204.119.108,c238
00:16:3e:1c:d1:7d,id:*,10.204.119.109,c239
```

**Comment by stgraber** [comment] 2017-08-10 16:09
Tentatively closing this issue. So far it looks like having LXD manage the dhcp hosts list seems to be working fine here, but I'm not sure why that'd fix your issue...

I'd suggest you file a bug report with dnsmasq upstream, showing that you do have a static lease defined for the MAC address of the container, that the container hits dnsmasq with that same MAC but then gets a different IP. If that's expected behavior and additional configuration is needed to have dnsmasq behave, then please comment here and we'll adapt LXD's dnsmasq config to match (but I'm not seeing anything obvious in the man page).

**Closed by stgraber** 2017-08-10 16:09 UTC
Labels: Incomplete
