### ISSUE TITLE
Container hangs when exiting from bash

### ISSUE THREAD

**Issue by pulnarayana1** [lxc/lxd#2133] opened 2016-06-17 19:31 UTC
Container hangs when some background job is triggered inside the container and then tried to exit from the container.

Running on Ubuntu 16.04

sudo lxc info lxd-cnt-1071
Name: lxd-cnt-1071
Architecture: x86_64
Created: 2016/06/17 18:52 UTC
Status: Running
Type: persistent
Profiles: default
Pid: 13994
Ips:
  eth0:	inet	10.200.3.202	vethE6BH4L
  eth0:	inet6	fe80::216:3eff:fedb:be32	vethE6BH4L
  lo:	inet	127.0.0.1
  lo:	inet6	::1
Resources:
  Processes: 20
  Disk usage:
    root: 643.95MB
  Memory usage:
    Memory (current): 15.69MB
    Memory (peak): 38.77MB
  Network usage:
    eth0:
      Bytes received: 2.78kB
      Bytes sent: 1.01kB
      Packets received: 18
      Packets sent: 10
    lo:
      Bytes received: 288 bytes
      Bytes sent: 288 bytes
      Packets received: 4
      Packets sent: 4

**Steps to reproduce:**

sudo lxc exec lxd-cnt-1071 bash
root@lxd-cnt-1071:~# yes >& /dev/null &
[1] 347
root@lxd-cnt-1071:~# exit
exit

The Process is running in the background, but unable to close the terminal, it just hangs up.

**Comment by stgraber** [comment] 2016-06-17 19:40
Duplicate of #1677

**Closed by stgraber** 2016-06-17 19:40 UTC
