### ISSUE TITLE
Operation not permitted - error mounting sysfs

### ISSUE THREAD

**Issue by alnat2** [lxc/lxd#1027] opened 2015-08-19 17:00 UTC
Hi !
After upgrade to 3.16.0-46-generic #62~14.04.1-Ubuntu, I got the error:

` " error Error calling 'lxd forkstart graph-node /var/lib/lxd/containers /var/log/lxd/graph-node/lxc.conf': err='exit status 1' ". `

My lxc.log:

lxc 1440002458.105 ERROR    lxc_conf - conf.c:lxc_mount_auto_mounts:819 - Operation not permitted - error mounting sysfs on /usr/liib/x86_64-linux-gnu/lxc/sys flags 14
lxc 1440002458.105 ERROR    lxc_conf - conf.c:lxc_setup:3791 - failed to setup the automatic mounts for 'graph-node'
lxc 1440002458.105 ERROR    lxc_start - start.c:do_start:702 - failed to setup the container
 lxc 1440002458.105 ERROR    lxc_sync - sync.c:__sync_wait:51 - invalid sequence number 1. expected 2
lxc 1440002458.105 WARN     lxc_conf - conf.c:lxc_delete_network:2990 - failed to remove interface '(null)'
  lxc 1440002458.128 ERROR    lxc_start - start.c:__lxc_start:1172 - failed to spawn 'graph-node'

System: ubuntu 14.04, lxd version 0.15(lxd stable repo)

If I use 3.16.0-45 kernel, the container starts without errors.

**Comment by antitoine** [comment] 2015-08-19 17:27
I confirm the error, I have the same problem.

**Comment by stgraber** [comment] 2015-08-19 18:33
Sounds like a kernel bug. Can you paste your /proc/mounts?

I suspect this to be due to the overmounting bugfix in the upstream kernel... @hallyn

**Comment by alnat2** [comment] 2015-08-19 18:43
lrwxrwxrwx 1 root root 11 Aug 19 21:35 /proc/mounts -> self/mounts

**Comment by stgraber** [comment] 2015-08-19 18:55
The content of it please

**Comment by alnat2** [comment] 2015-08-19 19:01
rootfs / rootfs rw 0 0
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,relatime,size=4027712k,nr_inodes=1006928,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=814344k,mode=755 0 0
/dev/disk/by-uuid/57a2899a-904d-4dac-acf9-5f4778f1d071 / ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
none /sys/fs/cgroup tmpfs rw,relatime,size=4k,mode=755 0 0
none /sys/fs/fuse/connections fusectl rw,relatime 0 0
none /sys/kernel/debug debugfs rw,relatime 0 0
none /sys/kernel/security securityfs rw,relatime 0 0
none /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
none /run/shm tmpfs rw,nosuid,nodev,relatime 0 0
none /run/user tmpfs rw,nosuid,nodev,noexec,relatime,size=102400k,mode=755 0 0
none /sys/fs/pstore pstore rw,relatime 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,relatime,cpuset,clone_children 0 0
cgroup /sys/fs/cgroup/cpu cgroup rw,relatime,cpu 0 0
cgroup /sys/fs/cgroup/cpuacct cgroup rw,relatime,cpuacct 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,relatime,memory 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,relatime,devices 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,relatime,freezer 0 0
cgroup /sys/fs/cgroup/net_cls cgroup rw,relatime,net_cls 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,relatime,blkio 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,relatime,perf_event,release_agent=/run/cgmanager/agents/cgm-release-agent.perf_event 0 0
cgroup /sys/fs/cgroup/net_prio cgroup rw,relatime,net_prio 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,relatime,hugetlb,release_agent=/run/cgmanager/agents/cgm-release-agent.hugetlb 0 0
cgmfs /run/cgmanager/fs tmpfs rw,relatime,size=100k,mode=755 0 0
/dev/md7 /share ext4 rw,relatime,data=ordered 0 0
/dev/md1 /home ext4 rw,relatime,data=ordered 0 0
/dev/md2 /usr ext4 rw,relatime,data=ordered 0 0
/dev/md3 /tmp ext4 rw,relatime,data=ordered 0 0
/dev/md5 /backs ext4 rw,relatime,data=ordered 0 0
/dev/md6 /vms ext4 rw,relatime,data=ordered 0 0
/dev/md9 /share/multi ext4 rw,relatime,data=ordered 0 0
/dev/md10 /share/video ext4 rw,relatime,data=ordered 0 0
/dev/md8 /share/picts ext4 rw,relatime,data=ordered 0 0
systemd /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,release_agent=/run/cgmanager/agents/cgm-release-agent.systemd,name=system$
/dev/disk/by-uuid/57a2899a-904d-4dac-acf9-5f4778f1d071 /var/lib/docker/aufs ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
none /var/lib/docker/aufs/mnt/50f97cde6f837e0001db919a2d61948b28079c3ab9b9de78081c89b8e6b4ef00 aufs rw,relatime,si=674f64a78f6abf4f,dio,dirperm$
proc /run/docker/netns/50f97cde6f83 proc rw,nosuid,nodev,noexec,relatime 0 0
lxcfs /var/lib/lxcfs fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
/dev/disk/by-uuid/57a2899a-904d-4dac-acf9-5f4778f1d071 /var/lib/lxd/shmounts ext4 rw,relatime,errors=remount-ro,data=ordered 0 0

**Comment by stgraber** [comment] 2015-08-19 19:04
Ok, that looks normal, we'll need to reproduce this and figure out what changed in the kernel and have it fixed ASAP.

@hallyn

**Comment by POIMann** [comment] 2015-08-21 15:46
I've the same problem.
Broken lxd and service downtime for three days now.
Is there a hotfix available?
Thanks in advance!

**Comment by tych0** [comment] 2015-08-21 15:49
After some discussion with our kernel team, the next SRU'd kernel should be released soon with the fix for this. I'm not sure exactly which version it is, but if you want to use the kernel team's ppa for a bit that'll have it as well.

**Comment by stgraber** [comment] 2015-08-21 16:28
You could also upgrade your kernel to the lts-vivid version which doesn't have that specific issue.

**Comment by POIMann** [comment] 2015-08-21 17:06
Upgrading to lts-vivid is a safe bet, thanks!

**Comment by stgraber** [comment] 2015-08-21 20:15
Closing this one as it's not a LXD issue and we've forwarded the report to our kernel guys.

**Closed by stgraber** 2015-08-21 20:15 UTC
