### ISSUE TITLE
live migration : Error (sk-packet.c:420): Can't bind packet socket: Invalid argument

### ISSUE THREAD

**Issue by arsiesys** [lxc/lxd#1668] opened 2016-02-26 18:18 UTC
Hello, there is my issue :) : 

# Required information
 * Distribution: Ubuntu
 * Distribution version: 14.04
 * The output of "lxc info" 
```
apicompat: 0
auth: trusted
environment:
  addresses:
  - xxx.xxx.xxx.xxx:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
xxxxxx
    -----END CERTIFICATE-----
  driver: lxc
  driverversion: 2.0.0.rc2
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 3.13.0-79-generic
  server: lxd
  serverpid: 1035
  serverversion: 2.0.0.beta4
  storage: btrfs
  storageversion: "3.12"
config:
  core.https_address: xx.xx.xx.xx:8443
  core.trust_password: true
public: false
```
Same configuration on remote server (but do not use btrfs for test).

# Issue description
lxc live migration failed with error : 
error: Error transferring container data: restore failed:
(00.197685)   1269: Error (sk-packet.c:420): Can't bind packet socket: Invalid argument
(00.208241) Error (cr-restore.c:1304): 15147 killed by signal 9
(00.208498) Error (cr-restore.c:2130): Restoring FAILED.
Please note that I used the last criu sources available on both hosts.

# Steps to reproduce
- init  a new clean container with debian wheezy amd64
- apply migratable and default profile
- start container
- lxc copy test lxd2:

# Information to attach
last container log on source host :
```
lxc 20160226190741.901 DEBUG    lxc_commands - commands.c:lxc_cmd_handler:893 - peer has disconnected
            lxc 20160226190741.970 DEBUG    lxc_start - start.c:signal_handler:337 - container init process exited
            lxc 20160226190741.970 DEBUG    lxc_start - start.c:__lxc_start:1312 - unknown exit status for init: 9
            lxc 20160226190741.970 DEBUG    lxc_start - start.c:__lxc_start:1317 - Pushing physical nics back to host namespace
            lxc 20160226190741.970 DEBUG    lxc_start - start.c:__lxc_start:1320 - Tearing down virtual network devices used by container
            lxc 20160226190741.970 WARN     lxc_conf - conf.c:lxc_delete_network:2904 - failed to remove interface 52 'eth0'
            lxc 20160226190741.970 INFO     lxc_error - error.c:lxc_error_set_and_log:55 - child <17587> ended on signal (9)
            lxc 20160226190741.970 WARN     lxc_conf - conf.c:lxc_delete_network:2904 - failed to remove interface 52 'eth0'
            lxc 20160226190741.970 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/share/lxcfs/lxc.reboot.hook' for container 'test', config section 'lxc'
            lxc 20160226190742.474 INFO     lxc_conf - conf.c:run_script_argv:367 - Executing script '/usr/bin/lxd callhook /var/lib/lxd 369 stop' for container 'test', config section 'lxc'
            lxc 20160226190742.641 WARN     lxc_cgmanager - cgmanager.c:cgm_get:989 - do_cgm_get exited with error
            lxc 20160226191156.452 WARN     lxc_cgmanager - cgmanager.c:cgm_get:989 - do_cgm_get exited with error
```

end of migration log on destination host : 
```
pie: 1d6134
pie: vdso: image [vdso] 0x7ffeed1d6000-0x7ffeed1d8000 [vvar] 0xfffffff>
pie: fffffffff-0xffffffffffffffff
pie: vdso: Runtime vdso mismatches dumpee, generate proxy
pie: vdso: jmp: 0x7ffeed1d6000/0x700 -> 0x24000/0x700 (index 0)
pie: vdso: jmp: 0x7ffeed1d6000/0xf80 -> 0x24000/0xfc0 (index 1)
pie: vdso: jmp: 0x7ffeed1d6000/0xca0 -> 0x24000/0xcb0 (index 2)
pie: vdso: jmp: 0x7ffeed1d6000/0xf60 -> 0x24000/0xfa0 (index 3)
pie: Restoring EXE link
pie: Restoring scheduler params 0.0.0
pie: 1362: Restored
(00.197494)   1269: Restoring resources
(00.197503)   1269: Opening fdinfo-s
(00.197507)   1269: 	Restoring fd 0 (state -> prepare)
(00.197512)   1269: 	Restoring fd 1 (state -> prepare)
(00.197514)   1269: 	Restoring fd 2 (state -> prepare)
(00.197516)   1269: 	Restoring fd 3 (state -> prepare)
(00.197519)   1269: 	Restoring fd 4 (state -> prepare)
(00.197521)   1269: 	Restoring fd 5 (state -> prepare)
(00.197523)   1269: 	Restoring fd 20 (state -> prepare)
(00.197525)   1269: 	Restoring fd 21 (state -> prepare)
(00.197527)   1269: 	Restoring fd 0 (state -> create)
(00.197548)   1269: 		Create fd for 0
(00.197555)   1269: 	Restoring fd 1 (state -> create)
(00.197568)   1269: 		Create fd for 1
(00.197572)   1269: 	Restoring fd 2 (state -> create)
(00.197578)   1269: 		Create fd for 2
(00.197582)   1269: 	Restoring fd 3 (state -> create)
(00.197591)   1269: 		Create fd for 3
(00.197595)   1269: 	Restoring fd 4 (state -> create)
(00.197599)   1269: Opening packet socket id 0xd
(00.197685)   1269: Error (sk-packet.c:420): Can't bind packet socket: Invalid argument
pie: Task 1269  exited, status= 1
(00.208241) Error (cr-restore.c:1304): 15147 killed by signal 9
(00.208498) Error (cr-restore.c:2130): Restoring FAILED.
```

**Comment by stgraber** [comment] 2016-02-26 18:21
Live migration only really works with a 4.4 kernel or higher and with a very very recent CRIU (more recent than packaged).

@tych0 would really be nice to have some check for kernel + CRIU somehow so that folks get a clear error back :)

**Comment by arsiesys** [comment] 2016-02-26 18:36
Oh ok ! Again, thanks for the information ^^'.

**Comment by tych0** [comment] 2016-02-26 20:12
@stgraber it does check the version in liblxc and fails if it's not high enough, that's the only way it got this far.

As for this error, this is probably another unimplemented socket type. Can you post the dump log too? It should be in `/var/log/lxd/$containername/migration_dump_*.log` on the source host. Can you also post the output of `ip a` from the container?

**Comment by arsiesys** [comment] 2016-02-26 21:29
Hello !
I tried to get all asked data :)
http://satsu.eu/share/migration_dump_2016-02-26T21:56:56+01:00.log
http://satsu.eu/share/migration_restore_2016-02-26T20:57:22Z.log
http://satsu.eu/share/profile_migratable.txt
http://satsu.eu/share/ip_a.txt

**Comment by arsiesys** [comment] 2016-02-28 13:00
Oh, please note that on btrfs, when migration failed, the temporary btrfs subvolume is not removed : 
```
ID 520 gen 244217 top level 5 path snapshots/test/.migration-send-1d056199-2b86-4e63-81d7-33024f129d42/.root
ID 524 gen 244250 top level 5 path snapshots/test/.migration-send-e1532815-c116-41d5-a45b-c659d5ca2529/.root
ID 525 gen 244254 top level 5 path snapshots/test/.migration-send-297a431c-bbc5-4fbb-8c71-224eff5f0085/.root
ID 526 gen 244259 top level 5 path snapshots/test/.migration-send-98aae72e-ec4f-4946-bfce-b22a470fcac4/.root
ID 527 gen 244295 top level 5 path snapshots/test/.migration-send-caa4ad89-d781-4096-8d97-ced8b3175aa8/.root
ID 528 gen 244298 top level 5 path snapshots/test/.migration-send-3d316891-a618-4be8-a050-927ada50f4ec/.root
ID 529 gen 244303 top level 5 path snapshots/test/.migration-send-5835d7ce-cc01-48b5-9522-bf66b15d16da/.root
ID 530 gen 244309 top level 5 path snapshots/test/.migration-send-bac8c9a8-9ee7-45ab-b674-b746fb211986/.root
ID 531 gen 244310 top level 5 path snapshots/test/.migration-send-06da6463-6180-4230-bf9b-ca7d09a1ba19/.root
ID 532 gen 244313 top level 5 path snapshots/test/.migration-send-d43417cd-507c-4b44-acdc-48941d7a9ffe/.root
```
(need to be manually removed)

**Comment by stgraber** [comment] 2016-02-29 22:27
At the very least we should fix the btrfs subvolume leak issue :)

**Comment by arsiesys** [comment] 2016-03-03 22:33
Hello :) !

I made a test with the latest version of ubuntu (16.04) and lxd 2 beta 4. (kernel 4.4 + criu 2.0)
With a live migration of a debian wheezy, i got the "Can't bind packet socket: Invalid argument" error.

With a centos 7, i got : 
root@ubdesk:/var/log/lxd/test# lxc copy centos ubsrv:
error: Error transferring container data: restore failed:
(00.092356) Error (cgroup.c:1240): cg: Failed writing 0-3 to cpuset//lxc/centoss/cpuset.cpus
(00.582490)     18: Error (cgroup.c:1009): cg: Can't move 18 into systemd//lxc/centos/system.slice/systemd-journald.service/tasks (-1/-1): No such file or directory
(00.582497)     18: Error (cgroup.c:1124): cg: Can't move into systemd//lxc/centos/system.slice/systemd-journald.service/tasks (-1/-1): No such file or directory
(00.582567)     43: Error (cgroup.c:1009): cg: Can't move 43 into systemd//lxc/centos/system.slice/console-getty.service/tasks (-1/-1): No such file or directory
(00.582573)     43: Error (cgroup.c:1124): cg: Can't move into systemd//lxc/centos/system.slice/console-getty.service/tasks (-1/-1): No such file or directory
(00.582886)      1: Error (cr-restore.c:1306): 18 exited, status=1
(00.594670) Error (cr-restore.c:1308): 7906 killed by signal 9
(00.623099) Error (cr-restore.c:2138): Restoring FAILED.

**Comment by tych0** [comment] 2016-03-04 14:45
Which hash of criu are you using exactly? There are some patches recently that fix the issue you mention with xenial.

As for the cpuset.cpus issue, do you have cpusets configured anywhere on the host? Can you describe the configuration?

r.e. the socket bind issue, it would be handy to know what task is doing that so I can install it and reproduce. I can write you a patch to print some debugging info, but I haven't had time to look at it yet.

**Comment by tych0** [comment] 2016-03-04 16:48
Actually, I think your cpuset bug is just a really old bug in CRIU. It should be fixed by:

https://lists.openvz.org/pipermail/criu/2016-March/026028.html

**Comment by arsiesys** [comment] 2016-03-04 18:23
Hello,

Thanks for your return.

It was criu (I cloned git last night :p) : 
root@ubdesk:/home/kyon# criu --version
Version: 2.0
GitID: v1.8-455-gbddfc1b

I updated to the last revision : GitID: v1.8-457-g8b33970, It seems that your patch was applied on this revision.

--- test again with centos -- 
```
root@ubdesk:/opt/criu# lxc move centos ubsrv:
error: Error transferring container data: restore failed:
(00.217328)     46: Error (cgroup.c:1009): cg: Can't move 46 into systemd//lxc/centos/system.slice/console-getty.service/tasks (-1/-1): No such file or directory
(00.217825)     46: Error (cgroup.c:1124): cg: Can't move into systemd//lxc/centos/system.slice/console-getty.service/tasks (-1/-1): No such file or directory
(00.218279)      1: Error (cr-restore.c:1306): 46 exited, status=1
(00.227421) Error (cr-restore.c:1308): 3458 killed by signal 9
(00.260537) Error (cr-restore.c:2138): Restoring FAILED.
```

--- test again with xenial ubuntu -- 
As last time, first move ok, if i try to reverse back to old host, I get this : 
```
root@ubsrv:/opt/criu# lxc move ub ubdesk:
error: Error transferring container data: checkpoint failed:
(00.005947) Error (ptrace.c:197): Unseizable non-zombie 2696 found, state S, err -1/10
```

```
r.e. the socket bind issue, it would be handy to know what task is doing that so I can install it and reproduce. I can write you a patch to print some debugging info, but I haven't had time to look at it yet.
```
If I can help by doing or testing something, tell me. I can't help in dev. but if I can help by testing and provide data, I will :).

```
As for the cpuset.cpus issue, do you have cpusets configured anywhere on the host? Can you describe the configuration?
```
No specific configuration from my side, It was on a fresh Xenial and LXD install + last git rev of criu.

**Comment by tych0** [comment] 2016-03-04 18:36
On Fri, Mar 04, 2016 at 10:23:56AM -0800, arsiesys wrote:
> Hello,
> 
> Thanks for your return.
> 
> It was criu (I cloned git last night :p) : 
> root@ubdesk:/home/kyon# criu --version
> Version: 2.0
> GitID: v1.8-455-gbddfc1b
> 
> I updated to the last revision : GitID: v1.8-457-g8b33970, It seems that your patch was applied on this revision.

Yep, that's the latest, so,

> --- test again with centos -- 
> ```
> root@ubdesk:/opt/criu# lxc move centos ubsrv:
> error: Error transferring container data: restore failed:
> (00.217328)     46: Error (cgroup.c:1009): cg: Can't move 46 into systemd//lxc/centos/system.slice/console-getty.service/tasks (-1/-1): No such file or directory
> (00.217825)     46: Error (cgroup.c:1124): cg: Can't move into systemd//lxc/centos/system.slice/console-getty.service/tasks (-1/-1): No such file or directory
> (00.218279)      1: Error (cr-restore.c:1306): 46 exited, status=1
> (00.227421) Error (cr-restore.c:1308): 3458 killed by signal 9
> (00.260537) Error (cr-restore.c:2138): Restoring FAILED.
> ```

Can you post the full dump and restore logs for this? Sounds like
something goofy is going on.

> --- test again with xenial ubuntu -- 
> As last time, first move ok, if i try to reverse back to old host, I get this : 
> ```
> root@ubsrv:/opt/criu# lxc move ub ubdesk:
> error: Error transferring container data: checkpoint failed:
> (00.005947) Error (ptrace.c:197): Unseizable non-zombie 2696 found, state S, err -1/10
> ```

Did you update CRIU on both hosts? This is an issue with restore, so
the CRIU on the restore host needs to be updated as well. If so, can
you post the full dump and restore logs?

> ```
> r.e. the socket bind issue, it would be handy to know what task is doing that so I can install it and reproduce. I can write you a patch to print some debugging info, but I haven't had time to look at it yet.
> ```
> If I can help by doing or testing something, tell me. I can't help in dev. but if I can help by testing and provide data, I will :).

Ok, I'll see about writing a patch soon to help debug.

**Comment by arsiesys** [comment] 2016-03-04 18:55
Hello,

Yes, I updated criu on both host (same for LXD, I upgraded to the new RC1).

There is logs files : 
http://satsu.eu/share/1668_centos/
http://satsu.eu/share/1668_xenial/

**Comment by tych0** [comment] 2016-03-04 19:15
On Fri, Mar 04, 2016 at 10:55:53AM -0800, arsiesys wrote:
> Hello,
> 
> Yes, I updated criu on both host (same for LXD, I upgraded to the new RC1).
> 
> There is logs files : 
> http://satsu.eu/share/1668_centos/
> http://satsu.eu/share/1668_xenial/

If you still have the container running that was migrated, can you cat
/proc/2636/cgroup for it (2636 looks like it should be the init pid
for the container based on your logs).

Looks like there might be an off by one error somewhere:

(00.203868)      1: cg:   `-> freezer//lxc/xeniall/tasks

(two ls instead of one)

**Comment by tych0** [comment] 2016-03-04 19:17
On Fri, Mar 04, 2016 at 12:14:58PM -0700, Tycho Andersen wrote:
> On Fri, Mar 04, 2016 at 10:55:53AM -0800, arsiesys wrote:
> > Hello,
> > 
> > Yes, I updated criu on both host (same for LXD, I upgraded to the new RC1).
> > 
> > There is logs files : 
> > http://satsu.eu/share/1668_centos/
> > http://satsu.eu/share/1668_xenial/
> 
> If you still have the container running that was migrated, can you cat
> /proc/2636/cgroup for it (2636 looks like it should be the init pid
> for the container based on your logs).
> 
> Looks like there might be an off by one error somewhere:
> 
> (00.203868)      1: cg:   `-> freezer//lxc/xeniall/tasks
> 
> (two ls instead of one)

Of course, it's not a bug everywhere:

(00.203780)      1: cg:   `-> blkio//lxc/xeniall/tasks
(00.203800)      1: cg:   `-> cpu,cpuacct//lxc/xeniall/tasks
(00.203824)      1: cg:   `-> cpuset//lxc/xeniall/tasks
(00.203847)      1: cg:   `-> devices//lxc/xenial/init.scope/tasks
(00.203868)      1: cg:   `-> freezer//lxc/xeniall/tasks
(00.203886)      1: cg:   `-> hugetlb//lxc/xeniall/tasks
(00.203903)      1: cg:   `-> memory//lxc/xeniall/tasks
(00.203921)      1: cg:   `-> systemd//lxc/xenial/init.scope/tasks
(00.203942)      1: cg:   `-> net_cls,net_prio//lxc/xeniall/tasks
(00.204222)      1: cg:   `-> perf_event//lxc/xeniall/tasks
(00.204267)      1: cg:   `-> pids//lxc/xenial/init.scope/tasks

:(

**Comment by arsiesys** [comment] 2016-03-04 19:28
I closed the container but I reproduced it and got the container id : 
```
(00.000021) Probing sock diag modules
(00.036252) Done probing
(00.039158) ========================================
(00.039170) Dumping processes (pid: 1717)
(00.039171) ========================================
...
(00.039707) freezer.state=FROZEN                                                            
(00.039795) Error (ptrace.c:197): Unseizable non-zombie 1717 found, state S, err -1/10      
(00.039800) Unlock network                                                                  
root@ubsrv02:/var/log/lxd/xenial# cat /proc/1717/cgroup                                     
11:pids:/lxc/xenial/init.scope                                                              
10:devices:/lxc/xenial/init.scope                                                           
9:blkio:/lxc/xeniall                                                                        
8:hugetlb:/lxc/xeniall                                                                      
7:memory:/lxc/xeniall                                                                       
6:net_cls,net_prio:/lxc/xeniall                                                             
5:cpuset:/lxc/xeniall                                                                       
4:cpu,cpuacct:/lxc/xeniall                                                                  
3:perf_event:/lxc/xeniall                                                                   
2:freezer:/lxc/xeniall                                                                      
1:name=systemd:/lxc/xenial/init.scope                                                       
```

**Comment by tych0** [comment] 2016-03-04 19:28
Can you also try running the restore with https://github.com/tych0/criu/commit/e8b86fad950aff19250e47770c8d5efc60af27c2

?

Thanks

**Comment by tych0** [comment] 2016-03-04 19:28
Yep, looks like an off by one error :(. I think we need some more sophisticated testing in the rewriting engine.

**Comment by arsiesys** [comment] 2016-03-04 19:38
root@ubsrv02:/var/log/lxd/xenial# criu --version
Version: 2.0
GitID: v1.2-2416-ge8b86fa

http://satsu.eu/share/1668_xenial/second_move_criucustom/

**Comment by tych0** [comment] 2016-03-04 19:39
Do you have the restore logs from that run?

**Comment by arsiesys** [comment] 2016-03-04 19:42
Sorry, misunderstanding, I replaced the dump.

**Comment by tych0** [comment] 2016-03-04 19:50
No problem, thanks for testing!

I think I see the issue, can you try: https://github.com/tych0/criu/commit/33736a5b4fc42e1a48333f82ed3f9a5786f724ab

and post those logs? (or just try to migrate back, it should work)

**Comment by arsiesys** [comment] 2016-03-04 19:58
```
make[2] : on entre dans le répertoire « /opt/criu_custom/criu »
  CC       cgroup.o
cgroup.c: In function ‘rewrite_cgsets’:
cgroup.c:1598:52: error: passing argument 1 of ‘strlen’ makes pointer from integer without a cast [-Werror=int-conversion]
     bool prefix_has_slash = cg->cgns_prefix[strlen(cg->cgns_prefix)];
                                                    ^
In file included from cgroup.c:4:0:
/usr/include/string.h:398:15: note: expected ‘const char *’ but argument is of type ‘uint32_t {aka unsigned int}’
 extern size_t strlen (const char *__s)
               ^
cgroup.c:1598:44: error: subscripted value is neither array nor pointer nor vector
     bool prefix_has_slash = cg->cgns_prefix[strlen(cg->cgns_prefix)];
                                            ^
cgroup.c:1598:10: error: unused variable ‘prefix_has_slash’ [-Werror=unused-variable]
     bool prefix_has_slash = cg->cgns_prefix[strlen(cg->cgns_prefix)];
          ^
cc1: all warnings being treated as errors
/opt/criu_custom/scripts/nmk/scripts/rules.mk:53 : la recette pour la cible « cgroup.o » a échouée
```

**Comment by tych0** [comment] 2016-03-04 20:10
On Fri, Mar 04, 2016 at 11:58:47AM -0800, arsiesys wrote:
> ```
> make[2] : on entre dans le répertoire « /opt/criu_custom/criu »
>   CC       cgroup.o
> cgroup.c: In function ‘rewrite_cgsets’:
> cgroup.c:1598:52: error: passing argument 1 of ‘strlen’ makes pointer from integer without a cast [-Werror=int-conversion]
>      bool prefix_has_slash = cg->cgns_prefix[strlen(cg->cgns_prefix)];
>                                                     ^
> In file included from cgroup.c:4:0:
> /usr/include/string.h:398:15: note: expected ‘const char *’ but argument is of type ‘uint32_t {aka unsigned int}’
>  extern size_t strlen (const char *__s)
>                ^
> cgroup.c:1598:44: error: subscripted value is neither array nor pointer nor vector
>      bool prefix_has_slash = cg->cgns_prefix[strlen(cg->cgns_prefix)];
>                                             ^
> cgroup.c:1598:10: error: unused variable ‘prefix_has_slash’ [-Werror=unused-variable]
>      bool prefix_has_slash = cg->cgns_prefix[strlen(cg->cgns_prefix)];
>           ^
> cc1: all warnings being treated as errors
> /opt/criu_custom/scripts/nmk/scripts/rules.mk:53 : la recette pour la cible « cgroup.o » a échouée
> ```

Ugh, apologies, ad799e06941d6bfb73f9a235838069417336d143 should be the
right one.

**Comment by arsiesys** [comment] 2016-03-04 20:23
http://satsu.eu/share/1668_xenial/test_4/

It worked fine :).

**Comment by arsiesys** [comment] 2016-03-04 20:27
Note also that live migrate of centos is worked too :o.

**Comment by tych0** [comment] 2016-03-04 20:44
```
(00.092356) Error (cgroup.c:1240): cg: Failed writing 0-3 to cpuset//lxc/centoss/cpuset.cpus
```

Looks like it was the same problem :). Anyway, I'll clean the patch up and send it to the CRIU ML shortly. Thanks for your help! I'll ping you later about the network issue with a debugging patch for that too.

**Comment by tych0** [comment] 2016-03-15 19:52
Hi @ariesys, can you still reproduce the socket bind error? If so, send me an email (tycho.andersen@canonical.com) and I can work with you on debugging it. Since this is a CRIU issue and not a LXD one, I'll go ahead and close this.

**Closed by tych0** 2016-03-15 19:52 UTC
Labels: Bug
