### ISSUE TITLE
Prometheus with built in metrics returns SSL error

### ISSUE THREAD

**Issue by lutenica** [lxc/lxd#9498] opened 2021-11-08 15:50 UTC
# Required information

 * Distribution: Debian
 * Distribution version: 10.11
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.19.0-17-amd64
   * LXC version: 4.19
   * LXD version: 4.19
   * Storage backend in use: BTRFS

# Issue description

As per the new metrics endpoint documentation described [here](https://linuxcontainers.org/lxd/docs/master/metrics) on a cluster of 3 machines I sign one certificate and try to connect via cURL. That works as expected and I get the metric data. 

When proceeding with setting it up via Prometheus itself I use the configuration given in the docs, however the node returns:

`"https://$local.$domain:8443/1.0/metrics": x509: certificate is valid for $local, not $local.$domain`

I did try changing the node certificate itself but then the others would not accept it into the cluster. Changing the cluster cert resulted in it breaking further where none could join back. 

# Additional information

 - Unfortunately no logs are generated for the actual daemon and HTTP requests in neither the systemd journal or the /var/snap directory.
- Prometheus details: Version 2.24.1+ds; 
- I've tried with the cert added as metrics only or with full trust, to no avail.
- I did run this in the IRC channel but since that is rather hectic at times I figured it might be good to have it reported here as well. 
- I didn't see anything in 4.20 to indicate fixes to this effect, also the snap is not yet available, but I will test with it and update this.

**Comment by stgraber** [comment] 2021-11-08 15:57
Not a bug so will close this but basically you have two options:
 - `insecure_skip_verify: true` in the prometheus config to ignore the self-signed LXD certificate.
 - Update the cluster certificate with a valid certificate for whatever FQDN your cluster uses. Use `lxc cluster update-certificate` to have LXD deploy the new certificate for you on all cluster members.

Ideally we'd want to have an option in prometheus to validate the certificate but not bother validating the DNS name as that would work best in this case.

In my own deployment, I'm currently using the `insecure_skip_verify: true` option as most of my other prometheus endpoints are plain HTTP anyway (so not any worse), though if I wanted to keep TLS everywhere, I'd generate a new self-signed certificate for my cluster, make sure that all IP addresses and DNS names of all the cluster members are part of the certificate, then deploy that using `lxc cluster update-certificate` and then provide the certificate to prometheus.

**Closed by stgraber** 2021-11-08 15:57 UTC
