### ISSUE TITLE
Can't create new container after canceling

### ISSUE THREAD

**Issue by laralar** [lxc/lxd#3424] opened 2017-06-18 11:35 UTC
# Required information

 * Distribution: ubuntu 
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-79-generic
   * LXC version: 2.0.8
   * LXD version: 2.14
   * Storage backend in use: btrfs

# Issue description

I was going to create a container, and messed up with the name, then I pressed Ctrl_C and tried to create the container again. but I cant. 
I get the following output

root@node8:/var/lib/lxd/images# lxc launch ubuntu:x test3
Creating test3
error: UNIQUE constraint failed: storage_volumes.storage_pool_id, storage_volumes.name, storage_volumes.type
root@node8:/var/lib/lxd/images# lxc launch ubuntu:x test3
Creating test3
error: open /var/lib/lxd/images/1e59027d1d58873fc7e23f769232cd4846c6d675ea292bc71037fafc1547649d: no such file or directory
root@node8:/var/lib/lxd/images# 

# Steps to reproduce

I don't know if I can reproduce it or not. there are some production servers there and I don't want to pipe out everything anre reinstall. 

# Information to attach

 - [ ] any relevant kernel output (dmesg)
 - [ ] container log (lxc info NAME --show-log)
 - [ ] main daemon log (/var/log/lxd.log)
ephemeral=false lvl=info msg="Creating container" name=test3 t=2017-06-18T17:02:17+0530
ephemeral=false lvl=info msg="Created container" name=test3 t=2017-06-18T17:02:18+0530
created=2017-06-18T11:32:17+0000 ephemeral=false lvl=info msg="Deleting container" name=test3 t=2017-06-18T17:02:18+0530 used=1970-01-01T00:00:00+0000
created=2017-06-18T11:32:17+0000 ephemeral=false lvl=info msg="Deleted container" name=test3 t=2017-06-18T17:02:18+0530 used=1970-01-01T00:00:00+0000
ephemeral=false lvl=info msg="Creating container" name=test3 t=2017-06-18T17:02:56+0530
ephemeral=false lvl=info msg="Created container" name=test3 t=2017-06-18T17:02:57+0530
created=2017-06-18T11:32:56+0000 ephemeral=false lvl=info msg="Deleting container" name=test3 t=2017-06-18T17:02:57+0530 used=1970-01-01T00:00:00+0000
created=2017-06-18T11:32:56+0000 ephemeral=false lvl=info msg="Deleted container" name=test3 t=2017-06-18T17:02:57+0530 used=1970-01-01T00:00:00+0000

 - [ ] output of the client with --debug
 - [ ] output of the daemon with --debug

**Comment by brauner** [comment] 2017-06-18 11:43
Yeah, we currently do not support cancelling container creation. What does `lxc list` show?

**Comment by laralar** [comment] 2017-06-18 12:54
The containers are not there.

Fine if it's not supported. But now I can't create any new container.

It's seems that the database got something and didn't roll out back and it's corrupted.

Any workaround to fix the DB and being able to create new containers again?

**Comment by laralar** [comment] 2017-06-18 12:56
Basically I created a container with lxc launch, immediately after the message creating xxxx I pressed control C.

After that I can't create any new containers

Start stop of exceeding containers works fine

**Comment by brauner** [comment] 2017-06-18 13:56
@laralar, yeah the db seems to be messed up. So what should help you is:

    sqlite3 /var/lib/lxd/lxd.db "DELETE FROM containers WHERE name='test3'"
    sqlite3 /var/lib/lxd/lxd.db "DELETE FROM storage_volumes WHERE name='test3'"

can you also verify that no storage volume for the container has been created in the storage pool you are using. If so, delete it and you should be good to go.

**Comment by laralar** [comment] 2017-06-18 13:58
thanks,  I don't  have access to the server right now.  i'll try tomorrow and update.

**Comment by stgraber** [comment] 2017-06-18 18:01
Please don't run the commands above, they will leave records behind in the database.
@brauner when giving such SQL commands, don't forget that sqlite3 doesn't cascade by default.

**Comment by stgraber** [comment] 2017-06-18 18:04
First you should try:
 - lxc delete test3

With a bit of luck, that will let you clear the DB records.

If not, then you should do: sudo sqlite3 /var/lib/lxd/lxd.db
And then type in:

    PRAGMA foreign_keys=ON;
    DELETE FROM containers WHERE name='test3';
    DELETE FROM storage_volumes WHERE name='test3';

Can you also provide us with your /var/log/lxd/lxd.log?

As @brauner mentioned, we don't support canceling with ctrl+c right now, but that normally means that hitting ctrl+c will still have LXD create the container for you in the background, not lead to a half-created container as we're seeing here.

**Comment by brauner** [comment] 2017-06-18 18:17
sqlite3 doesn't cascade?

**Comment by stgraber** [comment] 2017-06-19 04:28
@brauner only if you tell it to :)

That's what the PRAGMA statement above does.

**Comment by laralar** [comment] 2017-06-19 05:36
lxd.log.. The problem started with creating zential container which I misspelled the name.

lxc list only shows the previous containers before this happens, none of these ones is shown 

The DB seems to be OK, there is nothing to delete.  Maybe the Filesystem?
sqlite> select * from containers ;
1|abdf-runner1||2|0|0|0|1497704398|2017-06-17 13:08:09.223647172+00:00
2|abdf-runner2||2|0|0|0|1497704633|2017-06-17 13:08:53.772380654+00:00
3|abdf-runner3||2|0|0|0|1497704814|2017-06-17 13:09:36.108389796+00:00
4|abdf-runner4||2|0|0|0|1497704982|2017-06-17 13:12:36.806647307+00:00
5|abdf-runner5||2|0|0|0|1497705154|2017-06-18 11:28:56.740586085+00:00
6|abdf-runner||2|0|0|0|1497705391|0
7|base-gitlab-runner||2|0|0|0|1497705644|0
8|base-gitlab-runner/gitlab-runnerdefault||2|1|0|0|1497705720|0
9|gitlab||2|0|0|0|1497769694|2017-06-18 10:32:40.376124801+00:00
sqlite> select * from storage_volumes;
1|abdf-runner1||2|0
2|abdf-runner2||2|0
3|abdf-runner3||2|0
4|abdf-runner4||2|0
5|abdf-runner5||2|0
6|abdf-runner||2|0
7|base-gitlab-runner||2|0
8|base-gitlab-runner/gitlab-runnerdefault||2|0
9|gitlab||2|0




I pressed Ctrl-C and tried to create the container with the correct name zentyal, but I couldn't

I tried to reproduce on the demo servers, and effectively, the containers are created in the background, and they stay in stopped state, but the DB doesn;t get corrupted

As you can see in the log there is normally one message "Creating..." following immediately by "Created..."  But in this particular case, there is 
"Creating zential"  followed by
"Creating zentyal" (Before the previous container was created)  
"Created zentyal"
"Deleting zentyal" (I didn't deleted this one, it was deleted automatically probably because of the DB error
"Deleted zentyal"
"Created zential"  (Only Here the first container was created !! )
"Deleting zential"
"Deleted zential"

And from them onwards were just normal tests without the Ctrl C.. zentyalsrv , test, test3, etc.. etc.. 

As you can see later on, stopping and starting of already existing containers works fine.


`
ephemeral=false lvl=info msg="Creating container" name=zential t=2017-06-18T16:54:02+0530
ephemeral=false lvl=info msg="Creating container" name=zentyal t=2017-06-18T16:54:02+0530
ephemeral=false lvl=info msg="Created container" name=zentyal t=2017-06-18T16:54:03+0530
created=2017-06-18T11:24:02+0000 ephemeral=false lvl=info msg="Deleting container" name=zentyal t=2017-06-18T16:54:03+0530 used=1970-01-01T00:00:00+0000
created=2017-06-18T11:24:02+0000 ephemeral=false lvl=info msg="Deleted container" name=zentyal t=2017-06-18T16:54:04+0530 used=1970-01-01T00:00:00+0000
ephemeral=false lvl=info msg="Created container" name=zential t=2017-06-18T16:54:04+0530
created=2017-06-18T11:24:02+0000 ephemeral=false lvl=info msg="Deleting container" name=zential t=2017-06-18T16:54:04+0530 used=1970-01-01T00:00:00+0000
created=2017-06-18T11:24:02+0000 ephemeral=false lvl=info msg="Deleted container" name=zential t=2017-06-18T16:54:04+0530 used=1970-01-01T00:00:00+0000
ephemeral=false lvl=info msg="Creating container" name=zentyalsrv t=2017-06-18T16:54:41+0530
ephemeral=false lvl=info msg="Created container" name=zentyalsrv t=2017-06-18T16:54:42+0530
created=2017-06-18T11:24:41+0000 ephemeral=false lvl=info msg="Deleting container" name=zentyalsrv t=2017-06-18T16:54:42+0530 used=1970-01-01T00:00:00+0000
created=2017-06-18T11:24:41+0000 ephemeral=false lvl=info msg="Deleted container" name=zentyalsrv t=2017-06-18T16:54:43+0530 used=1970-01-01T00:00:00+0000
ephemeral=false lvl=info msg="Creating container" name=test t=2017-06-18T16:56:45+0530
ephemeral=false lvl=info msg="Created container" name=test t=2017-06-18T16:56:46+0530
created=2017-06-18T11:26:45+0000 ephemeral=false lvl=info msg="Deleting container" name=test t=2017-06-18T16:56:46+0530 used=1970-01-01T00:00:00+0000
created=2017-06-18T11:26:45+0000 ephemeral=false lvl=info msg="Deleted container" name=test t=2017-06-18T16:56:47+0530 used=1970-01-01T00:00:00+0000
ephemeral=false lvl=info msg="Creating container" name=test t=2017-06-18T16:57:12+0530
ephemeral=false lvl=info msg="Created container" name=test t=2017-06-18T16:57:12+0530
created=2017-06-18T11:27:11+0000 ephemeral=false lvl=info msg="Deleting container" name=test t=2017-06-18T16:57:12+0530 used=1970-01-01T00:00:00+0000
created=2017-06-18T11:27:11+0000 ephemeral=false lvl=info msg="Deleted container" name=test t=2017-06-18T16:57:13+0530 used=1970-01-01T00:00:00+0000
ephemeral=false lvl=info msg="Creating container" name=test2 t=2017-06-18T16:57:18+0530
ephemeral=false lvl=info msg="Created container" name=test2 t=2017-06-18T16:57:18+0530
created=2017-06-18T11:27:17+0000 ephemeral=false lvl=info msg="Deleting container" name=test2 t=2017-06-18T16:57:19+0530 used=1970-01-01T00:00:00+0000
created=2017-06-18T11:27:17+0000 ephemeral=false lvl=info msg="Deleted container" name=test2 t=2017-06-18T16:57:19+0530 used=1970-01-01T00:00:00+0000
action=shutdown created=2017-06-17T13:12:34+0000 ephemeral=false lvl=info msg="Shutting down container" name=abdf-runner5 t=2017-06-18T16:58:49+0530 timeout=-1s used=2017-06-17T13:20:55+0000
action=shutdown created=2017-06-17T13:12:34+0000 ephemeral=false lvl=info msg="Shut down container" name=abdf-runner5 t=2017-06-18T16:58:52+0530 timeout=-1s used=2017-06-17T13:20:55+0000
action=start created=2017-06-17T13:12:34+0000 ephemeral=false lvl=info msg="Starting container" name=abdf-runner5 stateful=false t=2017-06-18T16:58:56+0530 used=2017-06-17T13:20:55+0000
ephemeral=false lvl=info msg="Creating container" name=test3 t=2017-06-18T17:02:17+0530
ephemeral=false lvl=info msg="Created container" name=test3 t=2017-06-18T17:02:18+0530
created=2017-06-18T11:32:17+0000 ephemeral=false lvl=info msg="Deleting container" name=test3 t=2017-06-18T17:02:18+0530 used=1970-01-01T00:00:00+0000
created=2017-06-18T11:32:17+0000 ephemeral=false lvl=info msg="Deleted container" name=test3 t=2017-06-18T17:02:18+0530 used=1970-01-01T00:00:00+0000
ephemeral=false lvl=info msg="Creating container" name=test3 t=2017-06-18T17:02:56+0530
ephemeral=false lvl=info msg="Created container" name=test3 t=2017-06-18T17:02:57+0530
created=2017-06-18T11:32:56+0000 ephemeral=false lvl=info msg="Deleting container" name=test3 t=2017-06-18T17:02:57+0530 used=1970-01-01T00:00:00+0000
created=2017-06-18T11:32:56+0000 ephemeral=false lvl=info msg="Deleted container" name=test3 t=2017-06-18T17:02:57+0530 used=1970-01-01T00:00:00+0000
lvl=info msg="Expiring log files" t=2017-06-18T18:19:44+0530
lvl=info msg="Done expiring log files" t=2017-06-18T18:19:44+0530
lvl=info msg="Pruning expired images" t=2017-06-18T18:19:48+0530
lvl=info msg="Done pruning expired images" t=2017-06-18T18:19:48+0530
lvl=info msg="Updating images" t=2017-06-18T18:19:48+0530
lvl=info msg="Done updating images" t=2017-06-18T18:19:48+0530
lvl=info msg="Updating images" t=2017-06-19T00:19:48+0530
lvl=info msg="Done updating images" t=2017-06-19T00:19:48+0530
lvl=info msg="Updating images" t=2017-06-19T06:19:48+0530
lvl=info msg="Done updating images" t=2017-06-19T06:19:48+0530


`

**Comment by laralar** [comment] 2017-06-19 05:37
The storage pools neither got created

root@node8:/var/lib/lxd# btrfs su li .
ID 261 gen 4340 top level 5 path lxd
ID 262 gen 72 top level 261 path storage-pools/default
ID 263 gen 1314 top level 262 path storage-pools/default/containers
ID 264 gen 116 top level 262 path storage-pools/default/snapshots
ID 265 gen 1955 top level 262 path storage-pools/default/images
ID 266 gen 72 top level 262 path storage-pools/default/custom
ID 267 gen 4349 top level 263 path storage-pools/default/containers/abdf-runner1
ID 269 gen 4349 top level 263 path storage-pools/default/containers/abdf-runner2
ID 272 gen 4349 top level 263 path storage-pools/default/containers/abdf-runner3
ID 273 gen 4348 top level 263 path storage-pools/default/containers/abdf-runner4
ID 275 gen 4345 top level 263 path storage-pools/default/containers/abdf-runner5
ID 277 gen 112 top level 263 path storage-pools/default/containers/abdf-runner
ID 278 gen 117 top level 263 path storage-pools/default/containers/base-gitlab-runner
ID 279 gen 115 top level 264 path storage-pools/default/snapshots/base-gitlab-runner/gitlab-runnerdefault
ID 287 gen 4350 top level 263 path storage-pools/default/containers/gitlab

**Comment by laralar** [comment] 2017-06-19 05:43
This command tells there is a violated constraint

root@node8:~# lxc launch ubuntu:x  test
Creating test
error: UNIQUE constraint failed: storage_volumes.storage_pool_id, storage_volumes.name, storage_volumes.type

however there is no such container in the DB



sqlite> select storage_pool_id, name,type from storage_volumes;
2|abdf-runner|0
2|abdf-runner1|0
2|abdf-runner2|0
2|abdf-runner3|0
2|abdf-runner4|0
2|abdf-runner5|0
2|base-gitlab-runner|0
2|base-gitlab-runner/gitlab-runnerdefault|0
2|gitlab|0
sqlite> 


And I get the two different error messages alternated
root@node8:~# lxc launch ubuntu:x  test
Creating test
error: open /var/lib/lxd/images/1e59027d1d58873fc7e23f769232cd4846c6d675ea292bc71037fafc1547649d: no such file or directory
root@node8:~# lxc launch ubuntu:x  test
Creating test
error: UNIQUE constraint failed: storage_volumes.storage_pool_id, storage_volumes.name, storage_volumes.type
root@node8:~# lxc launch ubuntu:x  test
Creating test
error: open /var/lib/lxd/images/1e59027d1d58873fc7e23f769232cd4846c6d675ea292bc71037fafc1547649d: no such file or directory
root@node8:~# lxc launch ubuntu:x  test
Creating test
error: UNIQUE constraint failed: storage_volumes.storage_pool_id, storage_volumes.name, storage_volumes.type


ephemeral=false lvl=info msg="Creating container" name=test t=2017-06-19T11:11:26+0530
ephemeral=false lvl=info msg="Created container" name=test t=2017-06-19T11:11:27+0530
created=2017-06-19T05:41:26+0000 ephemeral=false lvl=info msg="Deleting container" name=test t=2017-06-19T11:11:28+0530 used=1970-01-01T00:00:00+0000
created=2017-06-19T05:41:26+0000 ephemeral=false lvl=info msg="Deleted container" name=test t=2017-06-19T11:11:28+0530 used=1970-01-01T00:00:00+0000
ephemeral=false lvl=info msg="Creating container" name=test t=2017-06-19T11:11:33+0530
ephemeral=false lvl=info msg="Created container" name=test t=2017-06-19T11:11:33+0530
created=2017-06-19T05:41:32+0000 ephemeral=false lvl=info msg="Deleting container" name=test t=2017-06-19T11:11:34+0530 used=1970-01-01T00:00:00+0000
created=2017-06-19T05:41:32+0000 ephemeral=false lvl=info msg="Deleted container" name=test t=2017-06-19T11:11:34+0530 used=1970-01-01T00:00:00+0000
ephemeral=false lvl=info msg="Creating container" name=test t=2017-06-19T11:11:36+0530
ephemeral=false lvl=info msg="Created container" name=test t=2017-06-19T11:11:37+0530
created=2017-06-19T05:41:36+0000 ephemeral=false lvl=info msg="Deleting container" name=test t=2017-06-19T11:11:38+0530 used=1970-01-01T00:00:00+0000
created=2017-06-19T05:41:36+0000 ephemeral=false lvl=info msg="Deleted container" name=test t=2017-06-19T11:11:38+0530 used=1970-01-01T00:00:00+0000
ephemeral=false lvl=info msg="Creating container" name=test t=2017-06-19T11:11:40+0530
ephemeral=false lvl=info msg="Created container" name=test t=2017-06-19T11:11:41+0530
created=2017-06-19T05:41:40+0000 ephemeral=false lvl=info msg="Deleting container" name=test t=2017-06-19T11:11:41+0530 used=1970-01-01T00:00:00+0000
created=2017-06-19T05:41:40+0000 ephemeral=false lvl=info msg="Deleted container" name=test t=2017-06-19T11:11:41+0530 used=1970-01-01T00:00:00+0000

**Comment by laralar** [comment] 2017-06-19 05:43
And the image is there

root@node8:~# lxc image list
+------------+--------------+--------+---------------------------------------------+--------+----------+------------------------------+
|   ALIAS    | FINGERPRINT  | PUBLIC |                 DESCRIPTION                 |  ARCH  |   SIZE   |         UPLOAD DATE          |
+------------+--------------+--------+---------------------------------------------+--------+----------+------------------------------+
| x (9 more) | 1e59027d1d58 | no     | ubuntu 16.04 LTS amd64 (release) (20170610) | x86_64 | 153.78MB | Jun 18, 2017 at 7:14am (UTC) |
+------------+--------------+--------+---------------------------------------------+--------+----------+------------------------------+

**Comment by brauner** [comment] 2017-06-19 09:17
@laralar, can you also check that there are not left-over entries in the `storage_volumes_config` table?

**Comment by laralar** [comment] 2017-06-19 09:38
It's empty,

sqlite> select * from storage_volumes_config;
sqlite>

Did the storage configuration got corrupted?

**Comment by brauner** [comment] 2017-06-19 09:39
@laralar, can you please try to delete the image the container is supposed to be created from. I suspect that the image creation actually failed and not the container creation.

**Comment by laralar** [comment] 2017-06-19 09:53
I did before, deletede the image and copied it back from another local server where I have it instead of ubuntu:x

I'm doing it again removing the image (lxc image delete 1e59027d1d58) and (lxc launch ubuntu:x test).. 
I'll update in a few minutes (for some reason internet connection from that server is slow.)

There are no traces of the test or half-broken containers in the database
[lxd.db.sql.txt](https://github.com/lxc/lxd/files/1084509/lxd.db.sql.txt)

**Comment by laralar** [comment] 2017-06-19 10:19
This error:
error: UNIQUE constraint failed: storage_volumes.storage_pool_id, storage_volumes.name, storage_volumes.type

Seems to me that it is trying to insert a new storage volume violating the constraint.  The name is not there  (any name fails) 

CREATE TABLE storage_volumes (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    storage_pool_id INTEGER NOT NULL,
    type INTEGER NOT NULL,
    UNIQUE (storage_pool_id, name, type),
    FOREIGN KEY (storage_pool_id) REFERENCES storage_pools (id) ON DELETE CASCADE
);
 That will only give if we are trying to insert the same name again?  but it's not there.

**Comment by laralar** [comment] 2017-06-19 10:48
Could it be that the problem is related to the way I am importing the image:

lxc image copy devaprasad:1e59027d1d58 local: --copy-aliases
Image copied successfully!        

this works fine and it is really fast.


lxc image copy devaprasad:1e59027d1d58873fc7e23f769232cd4846c6d675ea292bc71037fafc1547649d local: --copy-aliases

or 

lxc image copy devaprasad:x local: --copy-aliases


Takes forever and I have to stop it.
 it creates a subdirectory named lxd_post_584312426 and another named lxd_build_463813495

The I get the error:

 lxc launch ubuntu:x test
Creating test
error: open /var/lib/lxd/images/1e59027d1d58873fc7e23f769232cd4846c6d675ea292bc71037fafc1547649d: no such file or directory
because in that directory there is only 
drwx------ 1 root root        62 Jun 19 16:09 .
drwxr-xr-x 1 root root       234 Jun 19 16:09 ..
-rw-r--r-- 1 root root       840 Jun 19 16:09 1e59027d1d58
-rw-r--r-- 1 root root 161251328 Jun 19 16:09 1e59027d1d58.rootfs


However in another server where I am trying to copy from, I have 
root@iotsysadmin:/var/lib/lxd/images# ls -la
total 157670
drwx------  2 root root         4 Jun 18 12:18 .
drwxr-xr-x 12 root root        16 Jun 19 15:26 ..
-rw-r--r--  1 root root       840 Jun 18 12:07 1e59027d1d58873fc7e23f769232cd4846c6d675ea292bc71037fafc1547649d
-rw-r--r--  1 root root 161251328 Jun 18 12:12 1e59027d1d58873fc7e23f769232cd4846c6d675ea292bc71037fafc1547649d.rootfs

**Comment by laralar** [comment] 2017-06-19 10:48
This worked!

root@node8:/var/lib/lxd/images# mv 1e59027d1d58 1e59027d1d58873fc7e23f769232cd4846c6d675ea292bc71037fafc1547649d
root@node8:/var/lib/lxd/images# mv 1e59027d1d58.rootfs 1e59027d1d58873fc7e23f769232cd4846c6d675ea292bc71037fafc1547649d.rootfs

This is how I am copying the images:


lxc image copy devaprasad:1e59027d1d58 local: --copy-aliases
Image copied successfully!        


For some reason 

lxc image copy devaprasad:1e59027d1d58873fc7e23f769232cd4846c6d675ea292bc71037fafc1547649d local: --copy-aliases

or 

lxc image copy devaprasad:x local: --copy-aliases


are too slow

**Comment by laralar** [comment] 2017-06-19 10:51
so .. the issue was not because of the Ctrl-C.. Ctrl-C and DB integrity were fine 
It seems that the issue is with the copy using a short hash name and being inserted in the DB with the full hash, plus being put in the images folder with the short name

Then the container creation assumes that the the checksum that is already in the DB exists, goes and looks for the file, but the file has the short name. It doesnt find it. it fails creating the container

**Comment by laralar** [comment] 2017-06-19 10:56
and basically I never created any container in this server before, the internet connection is too slow, that is why I had to use an intermediate server.. or maybe I did but using local:1e59027d1d58   This I don't remember

**Comment by brauner** [comment] 2017-06-19 11:00
@albertodonato did you change something here recently and have a clue what's going on?

**Comment by laralar** [comment] 2017-06-19 11:24
> This worked!

root@node8:/var/lib/lxd/images# mv 1e59027d1d58 1e59027d1d58873fc7e23f769232cd4846c6d675ea292bc71037fafc1547649d
root@node8:/var/lib/lxd/images# mv 1e59027d1d58.rootfs 1e59027d1d58873fc7e23f769232cd4846c6d675ea292bc71037fafc1547649d.rootfs

> 


Basically after I copy the container with
lxc image copy devaprasad:1e59027d1d58 local: --copy-aliases

The files are created as 1e59027d1d58  and 1e59027d1d58.rootfs under /var/lib/lxd/images

I rename and after that I can create containers again

**Comment by laralar** [comment] 2017-06-19 11:26
I tried to reproduce in the lxd demo server. but I can't, the file gets the correct name.  I am using 2.14 and the demo server has 2.09 I dont know if that makes a difference

**Comment by laralar** [comment] 2017-06-19 11:52
PS.  I am using a 2.12 server where the image is stored and a 2.14 client where I am importing the image and gets the short file name

**Comment by laralar** [comment] 2017-06-19 12:28
Summary: 

I updated to 2.14 the server where I'm storing the image and the issue is still there.  also the client is using 2.14 

lxc image copy devaprasad:1e59027d1d58 local: --copy-aliases
ls -la
total 157476
drwx------ 1 root root        62 Jun 19 17:29 .
drwxr-xr-x 1 root root       234 Jun 19 17:29 ..
-rw-r--r-- 1 root root       840 Jun 19 17:28 1e59027d1d58
-rw-r--r-- 1 root root 161251328 Jun 19 17:29 1e59027d1d58.rootfs

lxc launch ubuntu:x test
Creating test
error: open /var/lib/lxd/images/1e59027d1d58873fc7e23f769232cd4846c6d675ea292bc71037fafc1547649d: no such file or directory

mv 1e59027d1d58 1e59027d1d58873fc7e23f769232cd4846c6d675ea292bc71037fafc1547649d
mv 1e59027d1d58.rootfs 1e59027d1d58873fc7e23f769232cd4846c6d675ea292bc71037fafc1547649d.rootfs

lxc launch ubuntu:x test
Creating test
error: UNIQUE constraint failed: storage_volumes.storage_pool_id, storage_volumes.name, storage_volumes.type  
# I SUSPECT THIS IS IRRELEVANT, because it cleans the DB, the previous error left some data in the DB and this one fixes it.  Immediately I create a new container and works (the renaming of the iamge files worked

lxc launch ubuntu:x test
Creating test
Starting test

Now.. I deleted the image from the server and got it again (just in case)
lxc image copy ubuntu:x local: --copy-aliases

in the client:
lxc image copy devaprasad:1e59027d1d58 local: --copy-aliases
ls -la
total 157480
drwx------ 1 root root        62 Jun 19 17:43 .
drwxr-xr-x 1 root root       234 Jun 19 17:43 ..
-rw-r--r-- 1 root root       840 Jun 19 17:42 1e59027d1d58
-rw-r--r-- 1 root root 161251328 Jun 19 17:43 1e59027d1d58.rootfs


I can't reproduce neither create this environment in the demo server I cant create a container and update from either 2.12 (ubuntu 17.04) or 2.09 (ubuntu 16.04) to lxd 2.14  Im using btrfs

**Comment by laralar** [comment] 2017-06-19 12:29
sorry for the bold text.. I don't know how It got displayed like that..

**Comment by laralar** [comment] 2017-06-19 13:46
OK.. Some new findings. I have an empty host  Ubuntu 16.04 lxd 2.09 rootfs on btrfs

lxd init with dir pool
lxc image copy devaprasad:1e59027d1d58 local: --copy-aliases
1e59027d1d58873fc7e23f769232cd4846c6d675ea292bc71037fafc1547649d
1e59027d1d58873fc7e23f769232cd4846c6d675ea292bc71037fafc1547649d.btrfs
1e59027d1d58873fc7e23f769232cd4846c6d675ea292bc71037fafc1547649d.rootfs

works fine.. the file is created with the full name

upgraded the same server to 2.14
lxd init with dir pool
lxc image copy devaprasad:1e59027d1d58 local: --copy-aliases
1e59027d1d58  1e59027d1d58.rootfs

the file get copied with the short name

rolled back to 2.0.9
lxd init with dir pool
lxc image copy devaprasad:1e59027d1d58 local: --copy-aliases
1e59027d1d58873fc7e23f769232cd4846c6d675ea292bc71037fafc1547649d
1e59027d1d58873fc7e23f769232cd4846c6d675ea292bc71037fafc1547649d.btrfs
1e59027d1d58873fc7e23f769232cd4846c6d675ea292bc71037fafc1547649d.rootfs

installed again 2.14
lxd init with dir pool
lxc image copy devaprasad:1e59027d1d58 local: --copy-aliases
1e59027d1d58  1e59027d1d58.rootfs

It can be reproduced again and again.

**Comment by laralar** [comment] 2017-06-21 09:25
Another issue on lxc image copy

root@node7:/var/lib/lxd# rm -Rf images
root@node7:/var/lib/lxd# lxc image copy node8:7a7ff654cbd8f5f09bec03aa19d8d7d92649127d18659036a963b1ea63f90d25 local: --copy-aliases
Image copied successfully!

And nothing was copied because the images directory was removed.

**Comment by laralar** [comment] 2017-06-24 09:00
Same issue happens to me when copying/moving a container from another server after a fresh installation.  It seems that in some cases, lxd init doesn't create containers and images directory.  It is not that I deleted them on purpose.  But no information is given.

When copying a container though, an error is given.  when copying an image no error is giving, but instead you get the previous successful message.

**Comment by stgraber** [comment] 2017-06-26 02:56
I'll take a look at this. I suspect things will be quite different now with the new client library we just landed, but still want to check what happened in 2.14.

As for the earlier comment. The demo server actually does run LXD 2.14, don't believe what "dpkg -l" tells you on it, use "lxd --version" instead as we build our own binaries that are then put over the ones coming from the package :)

**Comment by albertodonato** [comment] 2017-06-26 09:12
I can confirm the issue copying images between two LXD servers using the short hash (the files get created with the short hash as name and never get removed).

Also, if the `images/` directory is removed while lxd is running, following image copy don't error.

Both issues are no longer present in current master.

**Comment by brauner** [comment] 2017-06-26 09:18
Cool, if it is fixed in master we can close this since `2.15` will be released soon.

**Comment by stgraber** [comment] 2017-06-26 18:50
I'm re-opening because the new client library doesn't explain why the server side of this issue would have been resolved. Yes, current git master won't trivially reproduce this because our client is now smarter, but it sounds like the backend may still be broken.

**Comment by stgraber** [comment] 2017-06-26 18:50
Anyway, I'll take a look into this myself.

**Comment by stgraber** [comment] 2017-06-26 22:02
Confirmed that the new client will report an error on copy if you destroy images/:
```
root@vm02:/var/lib/lxd# /home/ubuntu/lxc image copy images:alpine/edge local:
error: Failed remote image download:
 - https://images.linuxcontainers.org: mkdir /var/lib/lxd/images/lxd_build_199222217: no such file or directory
```

**Comment by stgraber** [comment] 2017-06-26 22:21
Reproduced the short hash issue on current LXD. Working on a fix for it now.

**Closed** 2017-06-27 00:24 UTC
Labels: Bug

**Comment by faphdev** [comment] 2018-03-21 03:33
Hello,
Is it still an issue with version 2.21?
I am getting the same symptoms but cannot provide a detailed report as laralar.
