### ISSUE TITLE
Failed to run: ip link  ... RTNETLINK answers: File exists

### ISSUE THREAD

**Issue by knutov** [lxc/lxd#8924] opened 2021-06-21 06:59 UTC
In case conatiner is not stopping fast (when something is wrong like disk space outage was happened inside container and lxc stop was very long) it is often not possible to start container:
```
root@server:~# lxc start c123
Error: Failed preparing container for start: Failed to start device "eth0": Failed to create the veth interfaces veth0c123 and veth9783dad0: Failed to run: ip link add veth0c123 type veth peer name veth9783dad0: RTNETLINK answers: File exists
```

Temporary solution to fix is `ip link delete veth0c123`. Then it is starting normally.

Ubuntu 18.04
latest stable LXD 4.15 from snap
all continers are with routed network.

**Comment by tomponline** [comment] 2021-06-21 07:50
Does this happen every time?

When you get the error, please can you show the output of `ip a` and `ip r` on the LXD host please?

**Comment by knutov** [comment] 2021-06-21 14:43
Yes, it happens almost every time if container was not able to stop fast enough.

`ip a` and `ip r` shows those interfaces are existing (can't show output now - all containers were restarted recently).

Every time scenario looks the same:

```
lxd stop $ct
...
timeout OR ctrl+c

This operation can't be cancelled (interrupt two more times to force)
Error: User signaled us three times, exiting. The remote operation will keep running
(after ctrl+c)

optionally inside container #reboot

and this issue will definitely happened here.
```

I had multiple times cases when lxd was not able stop container at all or in reasonable time in case of disk quota outage inside or multiple OOMs happened inside ct.

Sometimes I had to restart LXD with all containers (or the whole server) to restart such container, sometimes I was able to do reboot from inside ct, and I saw several times when container was actually stopped about 40 minutes after `lxd stop $ct` without additional manual changes. Network interfaces were up in such cases, so I have to do `ip link delete` every time in this situation.

**Comment by tomponline** [comment] 2021-06-21 14:46
When this happens, have you tried doing `lxc stop -f <instance>` to force a stop and cleanup?

**Comment by knutov** [comment] 2021-06-21 14:56
I did it today, but ct was already stopped at this time (I suppose thanks to `reboot` inside ct which takes time too, I did not know it was successful at the time I tried `lxc stop --force`):

```
# lxc stop c123 --force
Error: The container is already stopped
```

**Comment by tomponline** [comment] 2021-06-21 14:58
Yes you'll need to do it when the container is running.

E.g if you run `lxc stop <instance>` and nothing happens, try instead `lxc stop -f <instance>` and check the NIC device clean up occurs.

The normal `lxc stop <instance>` just requests the guest OS to shutdown, but if it pauses or doesn't respond, then LXD will wait indefinitely and will not consider the instance stopped or trigger NIC cleanup.

**Comment by knutov** [comment] 2021-06-21 15:00
so what exactly happens when I use `--force` switch? Should I always use it?

**Comment by tomponline** [comment] 2021-06-21 15:02
> so what exactly happens when I use `--force` switch? Should I always use it?

`--force` will forcefully end the container's OS (like turning off the power button) and then will proceed to perform host-side device cleanup as normal.

You should normally use `lxc stop` without `-f`, but if you find you're guest OS is not shutting down cleanly, then you can provide a timeout `--timeout` flag and then use `-f`.

**Comment by knutov** [comment] 2021-06-21 15:13
So, correct way is something like `lxc stop $ct --timeout 10 || lxc stop $ct --force`, do I understand right? 

Can I be sure `lxc stop --force` will be always able to stop ct at a reasonable time (less than minute for example)?

**Comment by tomponline** [comment] 2021-06-21 16:32
I'll close this now, but feel free to reopen if you experience any further problems with NIC cleanup.

**Closed by tomponline** 2021-06-21 16:32 UTC
Labels: Incomplete

**Comment by knutov** [comment] 2021-07-23 05:05
I had this situation today again and it was caused by `reboot` inside ct. So it was regular reboot and I had to manual fix it from node side again. It still looks like something not ok on LXD side may be near go aync functions or something like that.

I did save `ip a` and `ip r` this time:

```
~# ip a | grep veth0c123
9: veth63966950@veth0c123: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
10: veth0c123@veth63966950: <NO-CARRIER,BROADCAST,MULTICAST,UP,M-DOWN> mtu 1500 qdisc noqueue state LOWERLAYERDOWN group default qlen 1000

~# ip r | grep veth0c123
1.2.3.4 dev veth0c123 scope link linkdown
```
(ip masked to 1.2.3.4 from real for security reason)

**Comment by tomponline** [comment] 2021-07-23 08:03
Does `veth0c123` exist in `ip a` output?

We've not been able to reproduce and we run many automated daily tests.

**Comment by knutov** [comment] 2021-07-23 08:11
Yes, it does:

```
9: veth63966950@veth0c123: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 00:16:3e:f7:53:71 brd ff:ff:ff:ff:ff:ff
10: veth0c123@veth63966950: <NO-CARRIER,BROADCAST,MULTICAST,UP,M-DOWN> mtu 1500 qdisc noqueue state LOWERLAYERDOWN group default qlen 1000
    link/ether 16:5c:36:ff:7f:3b brd ff:ff:ff:ff:ff:ff
    inet6 fe80::145c:36ff:feff:7f3b/64 scope link
       valid_lft forever preferred_lft forever
```

Ubuntu 18.04, 5.4.0-64-generic, latest lxd from snap.

This is production server, will lxd debug affect cpu usage?
Is there any way to enable it without restarting lxd?

**Comment by tomponline** [comment] 2021-07-23 08:13
Can you confirm specific LXD version please.

Reloading LXD does not restart your containers.
Depending on how much activity you are doing with LXD, debugging can produce a lot of disk writes due to logging, but this is only happens when LXD activity is happening, not on activity inside your containers.

**Comment by knutov** [comment] 2021-07-23 08:18
```
# snap version
snap    2.51.1
snapd   2.51.1
series  16
ubuntu  18.04
kernel  5.4.0-64-generic


# snap info lxd
...
snap-id:      J60k4JY0HppjwOjW8dZdYc8obXKxujRu
tracking:     latest/stable
refresh-date: 3 days ago, at 00:19 MSK
channels:
  latest/stable:    4.16        2021-07-19 (21039) 71MB -
```

ok, I did `sudo snap set lxd daemon.debug=true; sudo systemctl reload snap.lxd.daemon`

**Comment by tomponline** [comment] 2021-07-23 08:22
OK thanks.

You can run `sudo tail -f /var/snap/lxd/common/lxd/logs/lxd.log` to see what is being written if you are unsure about the amount of overhead being added.

Next time it happens it would be useful to see a copy of that file along with the actions you were doing at the time and the name of the affected container thanks.

**Comment by knutov** [comment] 2023-02-20 12:58
For history: the problem was solved after few upgrades of LXD and switching to Ubuntu 20.04 with 5.15 LTS kernels

Unfortunately we lost our debug logs for the previous time.
