### ISSUE TITLE
Arch images for LXD?

### ISSUE THREAD

**Issue by kenokabe** [lxc/lxd#1575] opened 2016-02-08 02:04 UTC
Hi, I want to run Arch-linux continer on LXD.

Linux Containers
http://images.linuxcontainers.org/images/
seems not have Arch images. 
Can you advice what to do. Thanks.

**Comment by ChlorideCull** [comment] 2016-02-09 09:31
I have hosted a tarball of my personal build [on my server](http://changeling.devurandom.net/arch2016.tar.xz).

Things to note:

* As of right now, make will segfault because of a non-backported bugfix.
* eth0 only performs IPv6 DHCP for direct bridging to the internet, if you want to use the standard lxcbr0, name it eth1.
* I was having trouble generating keys for pacman-key, so **signature validation is disabled. I'd recommend getting it working again as soon as possible.**

**Comment by stgraber** [comment] 2016-02-15 00:57
The way to get arch images on images.linuxcontainers.org is to get archlinux to work with the tooling in github.com/lxc/lxc-ci and then added to the jenkins server at jenkins.linuxcontainers.org.

After that, you'll be getting daily builds of those images and if they're confirmed to work inside unprivileged containers, they'll show up in LXD when using images.linuxcontainers.org

**Comment by stgraber** [comment] 2016-02-15 00:59
I'm closing this issue as there's nothing that the LXD team can really do about this.

You can either use the image kindly provided by @ChlorideCull or if you want automatic daily images, help with getting archlinux to work with the lxc-ci tooling so everyone can benefit from daily images.

Such work would be tracked under the separate lxc/lxc-ci repository where pull requests are certainly most appreciated.

**Closed by stgraber** 2016-02-15 00:59 UTC

**Comment by ChlorideCull** [comment] 2016-02-15 10:53
I'm willing to work on it, I've filed an issue over there asking for more information about what's required.

**Comment by theblazehen** [comment] 2016-06-08 13:12
ChlorideCull: Any news / any chance you still have a copy of that tarball?

**Comment by ChlorideCull** [comment] 2016-06-09 08:00
Haven't really worked on it more. The issue for it on lxc-ci is here
https://github.com/lxc/lxc-ci/issues/5

AppArmor still breaks some vital services, so it's not really worth
pursuing until it's fixed.

ChlorideCull: Any news / any chance you still have a copy of that tarball?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/lxc/lxd/issues/1575#issuecomment-224584086>, or mute
the thread
<https://github.com/notifications/unsubscribe/AEvxpxb7g3FD6nD3KnzncqRrm1mbIK53ks5qJr-7gaJpZM4HVPMz>
.
