### ISSUE TITLE
Requesting example of /etc/netplan YAML file to describe one or more public IPs

### ISSUE THREAD

**Issue by davidfavor** [lxc/lxd#3977] opened 2017-10-26 15:22 UTC
With the release of Ubuntu Artful, /etc/netplan is now used, so normal declarations for public container IPs in /etc/network/interfaces no longer works.

Someone please post a working /etc/netplan YAML file to associate one or more public IPs with a container.

Thanks.

**Comment by jfgibbins** [comment] 2017-10-26 15:41
are you currently using eni format for cloud-init?  If so, update according to this, to use version 1 or 2, preferably 2 going forward.

https://github.com/lxc/lxd/blob/master/doc/cloud-init.md
http://cloudinit.readthedocs.io/en/latest/topics/network-config.html

Example cloud-init version 1:
  user.network-config: |
    ---
    version: 1
    config:
    - type: physical
      name: eth0
    - type: nameserver
      address:
      - x.x.x.x
      search:
      - xxx.local
      - xxx.org
    - type: vlan
      name: mgmt
      vlan_link: eth0
      vlan_id: 1000
      subnets:
      - address: x.x.x.x/12
        control: auto
        type: static
    - type: vlan
      name: eth0.1200
      vlan_link: eth0
      vlan_id: 1200
      subnets:
      - address: x.x.x.x/24
        gateway: x.x.x.x
        control: auto
        type: static
    ...

Below is the stuff for netplan, but remember, with cloud-init, you don't write this file directly.  You do it according to the above.  But if you really want to stick with the removed version, create your own image of artful that includes the package with ifupdown, etc.

http://people.canonical.com/~mtrudel/netplan/
http://manpages.ubuntu.com/manpages/zesty/man5/netplan.5.html
https://wiki.ubuntu.com/Netplan/Design
https://insights.ubuntu.com/2017/07/05/quick-and-easy-network-configuration-with-netplan/

**Comment by davidfavor** [comment] 2017-10-26 17:30
I'm using a standard install.
```
lxc init ubuntu:artful/amd64 net11-ubuntu-artful
```
Which produces /etc/netplan/50-cloud-init.yaml with contents of...
```
# This file is generated from information provided by
# the datasource.  Changes to it will not persist across an instance.
# To disable cloud-init's network configuration capabilities, write a file
# /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with the following:
# network: {config: disabled}
network:
    version: 2
    ethernets:
        eth0:
            dhcp4: true
```
Normally I'd create an eth0:1 alias with a single IP (addresses: [144.217.34.1/32]) + I the netplan docs are horribly terse.

I've tried many combinations of syntax based on the man pages.

No joy.

The above YAML file you posted will likely not work, because this will mix V1 + V2 netplan files, which the docs suggest won't work.

I'm looking for something like...
```
# Define container's public IP
network:
   version: 2
   ethernets:
      eth0
        match:
          eth0
            set-name: eth0:1
            addresses: [144.217.34.1/32]
```
Just simple syntax to create eth0:1 associated with eth0 with a single IP address assigned.

If you have an example that covers this use case, pass it along.

**Comment by jfgibbins** [comment] 2017-10-26 19:26
network:
    version: 2
    ethernets:
        eth0:
            dhcp4: true
            addresses:
            - 192.168.22.14/27
            gateway4: 192.168.22.1
            match:
                macaddress: 00:15:0a:08:00:05
            nameservers:
                addresses:
                - 192.168.23.2
                - 8.8.8.8
                search:
                - exemplary
            set-name: eth0

**Comment by jfgibbins** [comment] 2017-10-26 19:42
Be sure to read https://cloudinit.readthedocs.io/en/latest/topics/network-config-format-v2.html#
There are lots of examples, including how to do static and dhcp on same interface including the very first one https://cloudinit.readthedocs.io/en/latest/topics/network-config-format-v2.html#examples

**Comment by stgraber** [comment] 2017-10-26 21:17
thanks @jfgibbins 

Closing this issue as LXD is just passing strings through and we're unfortunately no cloud-init experts :)
I could have dug some local examples but @jfgibbins did that for me :)

**Closed by stgraber** 2017-10-26 21:17 UTC

**Comment by davidfavor** [comment] 2017-10-26 21:22
@stgraber, be great if you post how you accomplish this.

The following seems to work + this destroys the 10.X.X.X address inside the container, so may cause problems.

I realize this is not technically an LXD problem + without working networking, LXD is useful as a brick.
```
network:
    version: 2
    ethernets:
        eth0:
            match:
              name: eth0
            addresses:
            - 144.217.34.1/32
            set-name: eth0:1
```

**Comment by jfgibbins** [comment] 2017-10-26 21:32
@davidfavor You'll have to explain more in depth.  What 10.x address?  There's nothing in your example to either set or get an address other than 144.x loopback address.

**Comment by davidfavor** [comment] 2017-10-26 22:04
Creating a container produces this...
```
net11 # lxc init ubuntu:artful/amd64 net11-ubuntu-artful

net11 # lxc start net11-ubuntu-artful

net11 # lxc list net11-ubuntu-artful
+---------------------+---------+----------------------+-----------------------------------------------+------------+-----------+
|        NAME         |  STATE  |         IPV4         |                     IPV6                      |    TYPE    | SNAPSHOTS |
+---------------------+---------+----------------------+-----------------------------------------------+------------+-----------+
| net11-ubuntu-artful | RUNNING | 10.118.125.91 (eth0) | fd42:3336:560c:b2c1:216:3eff:fe3b:2998 (eth0) | PERSISTENT | 0         |
+---------------------+---------+----------------------+-----------------------------------------------+------------+-----------+
```
Adding an IPV4 public interface inside a container usually produces both a 10.X.X.X address + the public IP, like this...
```
net11 # lxc list net11-ubuntu-zesty
+--------------------+---------+--------------------------------+-----------------------------------------------+------------+-----------+
|        NAME        |  STATE  |              IPV4              |                     IPV6                      |    TYPE    | SNAPSHOTS |
+--------------------+---------+--------------------------------+-----------------------------------------------+------------+-----------+
| net11-ubuntu-zesty | RUNNING | 144.217.34.0 (eth0)            | fd42:3336:560c:b2c1:216:3eff:feff:4c15 (eth0) | PERSISTENT | 0         |
|                    |         | 10.118.125.29 (eth0)           |                                               |            |           |
+--------------------+---------+--------------------------------+-----------------------------------------------+------------+-----------+
```
This use to be easy to do via a simple entry in the interfaces file, of the form...
```
# Public IP
auto eth0:1
iface eth0:1 inet static
    netmask 255.255.255.255
    address 144.217.34.0
```
Which would simply create an eth0 alias of eth0:1 which left the 10.X.X.X address intact + added the public IP, allowing bi-directional packet flow between host + container + between all containers on the machine.

I'm looking for how to do this via netplan + I haven't found any docs yet which explain how to configure a simple eth0:1 alias.

If you know how, pass it along.

**Comment by jfgibbins** [comment] 2017-10-26 22:06
But I still don't see in any of your conifig where the 10.x address comes from.  And FYI, there is no alias in netplan.  There treated as secondary IP addresses per the man page as follows.  Same as link above. 

dhcp4: <(bool)>

Enable DHCP for IPv4. Off by default.

dhcp6: <(bool)>

Enable DHCP for IPv6. Off by default.

addresses: <(sequence of scalars)>

Add static addresses to the interface in addition to the ones received through DHCP or RA. Each sequence entry is in CIDR notation, i. e. of the form addr/prefixlen . addr is an IPv4 or IPv6 address as recognized by inet_pton``(3) and ``prefixlen the number of bits of the subnet.

Example: addresses: [192.168.14.2/24, 2001:1::1/64]

**Comment by davidfavor** [comment] 2017-10-26 22:10
10.118.125.91 == 10.X.X.X

**Comment by davidfavor** [comment] 2017-10-26 22:14
Problem is this. I can easily set my 144.217.34.1/32 address, except each time I get it set, the 10.X.X.X address is obliterated, which use to be required for various packet flow, between containers + host.

**Comment by jfgibbins** [comment] 2017-10-26 22:19
Yes, I know the 10 address, but you haven't shown how and where you're getting it from.  It has to be assigned statically or by dhcp and you haven't specified either in your netplan file.  I'm going to take a guess, and assume you're using out of the box networking that LXD typically installs with, and that you're getting the 10.x from a dhcp server.  If so, then if you used my example, or that of the links I sent you, the problem is that you deleted the line that says 'dhcp4: true'.  Read the following:

https://cloudinit.readthedocs.io/en/latest/topics/network-config-format-v2.html#common-properties-for-all-device-types  namely the entries for dhcp4 and addresses as well as the first example that shows dhcp and the second example that shows dhcp and static on the same interface.
https://cloudinit.readthedocs.io/en/latest/topics/network-config-format-v2.html#examples

Also, from a networking standpoint, the 144.217.34.1/32 is a loopback, so should probably be assigned to a lo interface rather than the eth0.

example for you to try taken from above and link.

network:
    version: 2
    ethernets:
        eth0:
            dhcp4: true
            addresses:
            - 144.217.34.1/32
            match:
                name: eth0
           set-name: eth0

Again, there is NO alias.  They are now secondary interfaces.  You could also take the loopback address off the eth0 and set it up as a loopback interface.

**Comment by davidfavor** [comment] 2017-10-26 22:21
The 10.X.X.X address is automatically assigned be default when a container is created by invoking /etc/netplan/50-cloud-init.yaml
```
# This file is generated from information provided by
# the datasource.  Changes to it will not persist across an instance.
# To disable cloud-init's network configuration capabilities, write a file
# /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with the following:
# network: {config: disabled}
network:
    version: 2
    ethernets:
        eth0:
            dhcp4: true
```
I'll try your example above.

**Comment by jfgibbins** [comment] 2017-10-26 22:23
So the 10.x was dhcp, which means with the dhcp4: true deleted, it was only going to set the 144.x address.  You need to have both in your config.

**Comment by davidfavor** [comment] 2017-10-26 22:26
That seemed to do the trick. Now I see...
```
net11 # lxc list net11-ubuntu-artful
+---------------------+---------+--------------------------------+-----------------------------------------------+------------+-----------+
|        NAME         |  STATE  |              IPV4              |                     IPV6                      |    TYPE    | SNAPSHOTS |
+---------------------+---------+--------------------------------+-----------------------------------------------+------------+-----------+
| net11-ubuntu-artful | RUNNING | 144.217.34.1 (eth0)            | fd42:3336:560c:b2c1:216:3eff:fe3b:2998 (eth0) | PERSISTENT | 0         |
|                     |         | 10.118.125.91 (eth0)           |                                               |            |           |
+---------------------+---------+--------------------------------+-----------------------------------------------+------------+-----------+
```
Which seems correct.

So the /etc/netplan/50-cloud-init.yaml is treated as a NOP + completely usurped.

If you happen to know how the /etc/netplan/50-cloud-init.yaml is generated (I can't seem to find the template in /var/lib or /etc/cloud), let me know.

If this file is a NOP, I'd rather completely remove it, so there's no confusion, thinking it adds to any configuration.

Thanks for your help!

**Comment by davidfavor** [comment] 2017-10-26 22:27
@stgraber, I'd still like to hear how your accomplish your netplan setup in an OVH environment, as you've mentioned your setup is similar to mine.

Thanks.

**Comment by jfgibbins** [comment] 2017-10-26 22:37
@davidfavor there won't be a template file in /etc/cloud, same as with ifupdown.  LXD passes in user.network-config to the /var/lib/cloud/seed/nocloud-net/network-config file, from there, like with ifupdown, it's interpreted by cloud-init and written to /etc/netplan/50* rather than /etc/network/interfaces.d/50*.  As far as getting rid of /etc/netplan/50*, if you do that, then you're network config will be left to the default, which is to only assign dhcp to eth0.   This is the same behavior as pre 17.10.  Were you configuring your network with cloud-init before?  If so, what format were you using?  ENI, Version 1/2?

# This file is generated from information provided by
# the datasource.  Changes to it will not persist across an instance.
# To disable cloud-init's network configuration capabilities, write a file
# /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with the following:
# network: {config: disabled}
network:
    version: 2
    ethernets:
        eth0:
            dhcp4: true

**Comment by davidfavor** [comment] 2017-10-26 22:43
With ENI, I just added a simple file to /etc/network/interfaces of the form...
```
# Loopback
auto lo
iface lo inet loopback

# DHCP container to host connector
auto eth0 
iface eth0 inet dhcp

# Public IP
auto eth0:1
iface eth0:1 inet static
    netmask 255.255.255.255
    address 144.217.34.1
```

**Comment by davidfavor** [comment] 2017-10-26 22:48
This seems to do the trick.
```
# In container
rm -f /etc/netplan/50-cloud-init.yaml
echo "network: {config: disabled}" > /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg

# outside container
lxc restart net11-ubuntu-artful
```
At this point the file is destroyed + never gets regenerated.

Thanks!

**Comment by jfgibbins** [comment] 2017-10-26 22:50
but why would you want to wipe out your network config?  you'll just have to set it manually anytime you reboot the container.  What you did is exactly the same as rm -f /etc/network/interfaces.d/50-cloud-init.cfg pre-17.10.

**Comment by davidfavor** [comment] 2017-10-26 23:31
/etc/netplan/60-public-init.yaml contains entire network setup.

Since there are no aliases + 60-public-init.yaml destroys all 50-cloud-init.yaml setup, due to how netplan works, 50-cloud-init.yaml becomes a NOP file.

NOP files create confusion, when people see them + imagine they have some purpose.

The /etc/netplan/60-public-init.yaml lives across boots + encapsulates the entire network setup, so anyone can glance in /etc/netplan + see exactly how network config is handled, with no confusion.

I run 100s of LXD containers, across many machines + confusion is a killer, when anything circles the drain + has to be debugged.

**Comment by jfgibbins** [comment] 2017-10-26 23:36
so you're manually creating the 60 file then and not even using cloud-init then for network?  in which case, just use 
# /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with the following:
# network: {config: disabled}
before you launch the container, to prevent the 50 file from being created in the first place.  Doing it afterwards will have no effect

**Comment by davidfavor** [comment] 2017-10-27 12:32
Yep. This seems to do the trick.

Thanks for all your help.

You saved me a truckload of time.

**Comment by davidfavor** [comment] 2017-10-27 17:43
Note: For netplan based systems, ifconfig no longer returns all IPs. Use the following instead...
```
ip address
```
which will show all /etc/netplan assigned IPs, including IP ranges + 10.X.X.X addresses assigned by LXD.

**Comment by jfgibbins** [comment] 2017-10-27 18:26
Going forward with 17.10, that's going to be true of just about all previous network type commands, ifupdown, net-tools, etc.  (announced back in 2009, https://lists.debian.org/debian-devel/2009/03/msg00780.html,  took them a while though, lol) Almost all commands have been deprecated in favor of iproute2 package based commands.

**Comment by jfgibbins** [comment] 2017-10-27 18:53
Not very happy with the whole netplan change going on.  Way to many things missing and broken.  It's not even close to ready for even just testing, let alone as a finished product, and they've already pushed it into the builds as the primary package.  The launchpad site for it is woefully neglected and behind.  My bet is if they leave it as is going into 18.04, the first thng everyone will be doing is writing scripts to remove netplan and restore a functioning network.

**Comment by stgraber** [comment] 2017-10-27 19:27
@davidfavor I only run LTS releases of Ubuntu so haven't yet had to deal with netplan on any of those systems.

**Comment by davidfavor** [comment] 2017-10-28 13:24
@stgraber - I'm trying to get ahead of the game by understanding how netplan works. If you make any netplan progress, be good to hear what you find.

@jfgibbins - Provided enough info to get LXD working with netplan + there are many... oddities... Like **ifconfig** seems broken now, so **ip address** must be used instead. Also resolvconf is now dead (thank goodness) + the replacement system is ill defined.

**Comment by jfgibbins** [comment] 2017-11-01 23:44
@davidfavor might be helpful to you, but rather than looking up netplan, reference systemd-networkd.  Mind you the current version is 232 in xenial, 234 artful, and 235 comes out in bionic.  Looking forward to 235, adds a lot of features, but going to try and work with the netplan group to get it working as there are a lot of features missing, and more being added to systemd 235

**Comment by davidfavor** [comment] 2017-12-02 13:51
After wrestling with this a good bit. I'll stick with Zesty, till Bionic releases, then figure out how to upgrade all my containers.

**Comment by davidfavor** [comment] 2017-12-02 13:53
@jfgibbins - Thanks for all your great updates.

I've bookmarked this issue for the sad day when I have to get netplan working.

**Comment by bodleytunes** [comment] 2018-05-09 18:34
uninstall netplan and install ifupdown?

the only downer i see with netplan is the lack of support for setting up OvS networking at the moment..

**Comment by Coconutdog** [comment] 2020-03-09 08:22
My working config for 2 x NICs. The 10.1.6.0/24 network is the management network for my Cisco gear.

`---
network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s25:
       dhcp4: no
       dhcp6: no
       addresses:
        - 10.1.1.58/24
        - 2001:xxxx:4121:3b10::58/64
        - fe80::58/64
       gateway4: 10.1.1.1
       gateway6: 2001:xxxx:4121:3b10::1941
       nameservers:
         addresses:
          - 192.231.203.132
          - 192.231.203.3
          - 2001:xxxx:1::1
          - 2001:xxxx:2::2
       routes:
         - to: 0.0.0.0/32
           via: 10.1.1.1
           metric: 100
#
    enp4s0:
       dhcp4: no
       dhcp6: no
       addresses:
        - 10.1.6.58/24
        - 2001:xxxx:4121:3b60::58/64
        - fe80::58/64
       gateway4: 10.1.6.1
       gateway6: 2001:xxxx:4121:3b60::1941
       nameservers:
         addresses:
          - 192.231.203.132
          - 192.231.203.3
          - 2001:xxxx:1::1
          - 2001:xxxx:2::2
       routes:
         - to: 0.0.0.0/32
           via: 10.1.6.1
           metric: 200
#
...`
