### ISSUE TITLE
cgroup is not removed when stopping container

### ISSUE THREAD

**Issue by gianfurrer** [lxc/lxd#11108] opened 2022-11-10 15:44 UTC
# Required information

 * Distribution: Debian
 * Distribution version: Bullseye 11.5 
 * The output of "lxc info" or if that fails:
```
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- snapshot_schedule_aliases
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
- firewall_driver
- projects_limits
- container_syscall_intercept_hugetlbfs
- limits_hugepages
- container_nic_routed_gateway
- projects_restrictions
- custom_volume_snapshot_expiry
- volume_snapshot_scheduling
- trust_ca_certificates
- snapshot_disk_usage
- clustering_edit_roles
- container_nic_routed_host_address
- container_nic_ipvlan_gateway
- resources_usb_pci
- resources_cpu_threads_numa
- resources_cpu_core_die
- api_os
- container_nic_routed_host_table
- container_nic_ipvlan_host_table
- container_nic_ipvlan_mode
- resources_system
- images_push_relay
- network_dns_search
- container_nic_routed_limits
- instance_nic_bridged_vlan
- network_state_bond_bridge
- usedby_consistency
- custom_block_volumes
- clustering_failure_domains
- resources_gpu_mdev
- console_vga_type
- projects_limits_disk
- network_type_macvlan
- network_type_sriov
- container_syscall_intercept_bpf_devices
- network_type_ovn
- projects_networks
- projects_networks_restricted_uplinks
- custom_volume_backup
- backup_override_name
- storage_rsync_compression
- network_type_physical
- network_ovn_external_subnets
- network_ovn_nat
- network_ovn_external_routes_remove
- tpm_device_type
- storage_zfs_clone_copy_rebase
- gpu_mdev
- resources_pci_iommu
- resources_network_usb
- resources_disk_address
- network_physical_ovn_ingress_mode
- network_ovn_dhcp
- network_physical_routes_anycast
- projects_limits_instances
- network_state_vlan
- instance_nic_bridged_port_isolation
- instance_bulk_state_change
- network_gvrp
- instance_pool_move
- gpu_sriov
- pci_device_type
- storage_volume_state
- network_acl
- migration_stateful
- disk_state_quota
- storage_ceph_features
- projects_compression
- projects_images_remote_cache_expiry
- certificate_project
- network_ovn_acl
- projects_images_auto_update
- projects_restricted_cluster_target
- images_default_architecture
- network_ovn_acl_defaults
- gpu_mig
- project_usage
- network_bridge_acl
- warnings
- projects_restricted_backups_and_snapshots
- clustering_join_token
- clustering_description
- server_trusted_proxy
- clustering_update_cert
- storage_api_project
- server_instance_driver_operational
- server_supported_storage_drivers
- event_lifecycle_requestor_address
- resources_gpu_usb
- clustering_evacuation
- network_ovn_nat_address
- network_bgp
- network_forward
- custom_volume_refresh
- network_counters_errors_dropped
- metrics
- image_source_project
- clustering_config
- network_peer
- linux_sysctl
- network_dns
- ovn_nic_acceleration
- certificate_self_renewal
- instance_project_move
- storage_volume_project_move
- cloud_init
- network_dns_nat
- database_leader
- instance_all_projects
- clustering_groups
- ceph_rbd_du
- instance_get_full
- qemu_metrics
- gpu_mig_uuid
- event_project
- clustering_evacuation_live
- instance_allow_inconsistent_copy
- network_state_ovn
- storage_volume_api_filtering
- image_restrictions
- storage_zfs_export
- network_dns_records
- storage_zfs_reserve_space
- network_acl_log
- storage_zfs_blocksize
- metrics_cpu_seconds
- instance_snapshot_never
- certificate_token
- instance_nic_routed_neighbor_probe
- event_hub
- agent_nic_config
- projects_restricted_intercept
- metrics_authentication
- images_target_project
- cluster_migration_inconsistent_copy
- cluster_ovn_chassis
- container_syscall_intercept_sched_setscheduler
- storage_lvm_thinpool_metadata_size
- storage_volume_state_total
- instance_file_head
- instances_nic_host_name
- image_copy_profile
- container_syscall_intercept_sysinfo
- clustering_evacuation_mode
- resources_pci_vpd
- qemu_raw_conf
- storage_cephfs_fscache
- network_load_balancer
- vsock_api
- instance_ready_state
- network_bgp_holdtime
- storage_volumes_all_projects
- metrics_memory_oom_total
- storage_buckets
- storage_buckets_create_credentials
- metrics_cpu_effective_total
- projects_networks_restricted_access
- storage_buckets_local
- loki
- acme
- internal_metrics
- cluster_join_token_expiry
- remote_token_expiry
- init_preseed
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 172.16.0.254:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    xxx
    -----END CERTIFICATE-----
  certificate_fingerprint: xxx
  driver: lxc
  driver_version: 5.0.1
  firewall: nftables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    idmapped_mounts: "false"
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.10.0-18-amd64
  lxc_features:
    cgroup2: "true"
    core_scheduling: "true"
    devpts_fd: "true"
    idmapped_mounts_v2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Debian GNU/Linux
  os_version: "11"
  project: default
  server: lxd
  server_clustered: false
  server_event_mode: full-mesh
  server_name: master
  server_pid: 891
  server_version: "5.7"
  storage: btrfs
  storage_version: 5.4.1
  storage_supported_drivers:
  - name: lvm
    version: 2.03.07(2) (2019-11-30) / 1.02.167 (2019-11-30) / 4.43.0
    remote: false
  - name: btrfs
    version: 5.4.1
    remote: false
  - name: ceph
    version: 15.2.16
    remote: true
  - name: cephfs
    version: 15.2.16
    remote: true
  - name: cephobject
    version: 15.2.16
    remote: true
  - name: dir
    version: "1"
    remote: false
```

# Issue description

We have a server that creates and removes a lot of LXD containers. The tool we use to do that is `pylxd`.
Over time, the server was running out of memory. We noticed that the cgroups created by lxd were not removed properly, even if the container does not exist anymore. Since every cgroup had still some memory allocated, we identified that this was eating up all of our memory.

The logs of the container which cgroups are not removed show the following warning:
```
lxc test-container 20221110144214.806 WARN     cgfsng - ../src/src/lxc/cgroups/cgfsng.c:cgroup_tree_remove:489 - Permission denied - Failed to destroy 10(lxc.payload.test-container)
```

After quite a thorough investigation, we were able to narrow the issue. The following conditions must be true in order for the cgroups **not** to be removed when a container is stopped:

1. The container config needs to contain `raw.idmap: "both 0 0"` (`both 1 1` also works, but something like `both 50000 50000` doesn't)
2. The container system needs to be fully started (`systemctl is-system-running` equals "running" or "degraded")
3. A command from a different user than `root` must be executed on the container
4. The container must be stopped by force (`pylxd` does that by default, the `lxc` CLI however doesn't)

If any of the conditions listed do no occur, the container log does not include the warning listed above and the cgroup is removed as expected.

So we currently have a workaround that the cgroups are removed by telling `pylxd` not to stop the containers with force (`container.stop(force=False)`), but we still would like to find out why exactly this is happening.

# Steps to reproduce

I created a bash script which can be run on a Debian bullseye host which has LXD installed:

```bash
CONTAINER_NAME=test-container
lxc launch images:debian/buster $CONTAINER_NAME --config raw.idmap="both 0 0"

sleep 1 # wait for system to be in running state
if ! lxc exec $CONTAINER_NAME -- sh -c 'systemctl is-system-running' | grep -qE "running|degraded"; then
  echo "System was not running after 1 second. Increase the sleep time"
  lxc delete $CONTAINER_NAME --force
  exit 1
fi

# add testuser to run a command from
lxc exec $CONTAINER_NAME -- sh -c 'adduser --disabled-password --gecos \"\" testuser'

# run command as different user than root
lxc exec $CONTAINER_NAME -- sh -c 'runuser -l testuser -s /bin/bash -c "id"'

# stop container with force
lxc stop $CONTAINER_NAME --force

lxc delete $CONTAINER_NAME
```

After running the script the directory (aka cgroup) of the container still exists:
```shell
ls /sys/fs/cgroup/lxc.payload.test-container
# or
systemd-cgtop | grep test-container
```

# Information to attach

Output of `lxc info test-container --show-log`:

```
Name: test-container
Status: STOPPED
Type: container
Architecture: x86_64
Created: 2022/11/10 15:27 UTC
Last Used: 2022/11/10 15:27 UTC

Log:

lxc test-container 20221110152730.775 WARN     conf - ../src/src/lxc/conf.c:lxc_map_ids:3592 - newuidmap binary is missing
lxc test-container 20221110152730.775 WARN     conf - ../src/src/lxc/conf.c:lxc_map_ids:3598 - newgidmap binary is missing
lxc test-container 20221110152730.776 WARN     conf - ../src/src/lxc/conf.c:lxc_map_ids:3592 - newuidmap binary is missing
lxc test-container 20221110152730.776 WARN     conf - ../src/src/lxc/conf.c:lxc_map_ids:3598 - newgidmap binary is missing
lxc test-container 20221110152732.129 WARN     conf - ../src/src/lxc/conf.c:lxc_map_ids:3592 - newuidmap binary is missing
lxc test-container 20221110152732.129 WARN     conf - ../src/src/lxc/conf.c:lxc_map_ids:3598 - newgidmap binary is missing
lxc test-container 20221110152732.378 WARN     conf - ../src/src/lxc/conf.c:lxc_map_ids:3592 - newuidmap binary is missing
lxc test-container 20221110152732.378 WARN     conf - ../src/src/lxc/conf.c:lxc_map_ids:3598 - newgidmap binary is missing
lxc test-container 20221110152732.833 WARN     conf - ../src/src/lxc/conf.c:lxc_map_ids:3592 - newuidmap binary is missing
lxc test-container 20221110152732.833 WARN     conf - ../src/src/lxc/conf.c:lxc_map_ids:3598 - newgidmap binary is missing
lxc test-container 20221110152733.422 WARN     conf - ../src/src/lxc/conf.c:lxc_map_ids:3592 - newuidmap binary is missing
lxc test-container 20221110152733.422 WARN     conf - ../src/src/lxc/conf.c:lxc_map_ids:3598 - newgidmap binary is missing
lxc test-container 20221110152733.424 WARN     cgfsng - ../src/src/lxc/cgroups/cgfsng.c:cgroup_tree_remove:489 - Permission denied - Failed to destroy 10(lxc.payload.test-container)
```

Output of `lxc config show test-container --expanded`:
```
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Debian buster amd64 (20221109_05:25)
  image.os: Debian
  image.release: buster
  image.serial: "20221109_05:25"
  image.type: squashfs
  image.variant: default
  raw.idmap: both 0 0
  volatile.base_image: ef4b022453b7c76f507240807e3e78f411732e8777fba0b45925e82ddf944c5e
  volatile.cloud-init.instance-id: 4130719e-a48f-4509-9e8b-3766974f233b
  volatile.eth0.hwaddr: 00:16:3e:91:54:6d
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":true,"Hostid":0,"Nsid":0,"Maprange":1},{"Isuid":true,"Isgid":false,"Hostid":1000001,"Nsid":1,"Maprange":999999999},{"Isuid":true,"Isgid":true,"Hostid":0,"Nsid":0,"Maprange":1},{"Isuid":false,"Isgid":true,"Hostid":1000001,"Nsid":1,"Maprange":999999999}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":true,"Hostid":0,"Nsid":0,"Maprange":1},{"Isuid":true,"Isgid":false,"Hostid":1000001,"Nsid":1,"Maprange":999999999},{"Isuid":true,"Isgid":true,"Hostid":0,"Nsid":0,"Maprange":1},{"Isuid":false,"Isgid":true,"Hostid":1000001,"Nsid":1,"Maprange":999999999}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":true,"Hostid":0,"Nsid":0,"Maprange":1},{"Isuid":true,"Isgid":false,"Hostid":1000001,"Nsid":1,"Maprange":999999999},{"Isuid":true,"Isgid":true,"Hostid":0,"Nsid":0,"Maprange":1},{"Isuid":false,"Isgid":true,"Hostid":1000001,"Nsid":1,"Maprange":999999999}]'
  volatile.last_state.power: STOPPED
  volatile.last_state.ready: "false"
  volatile.uuid: f4763bd9-4eca-44d1-aa7b-4cb5360ffe39
devices:
  eth0:
    name: eth0
    network: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

 - [x] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)  [lxc.monitor.log](https://github.com/lxc/lxd/files/9982425/lxc.monitor.log)

**Comment by tomponline** [comment] 2022-11-18 13:34
Confirmed reproduced, thanks for the script!

**Comment by tomponline** [comment] 2022-11-18 14:10
So I have confirmed this using `ubuntu/jammy` images too.

Also using the command `lxc exec $CONTAINER_NAME -- sh -c 'su testuser -c id'` which doesn't invoke systemd-logind also shows the same problem.

What is left behind is:

```
lxc.payload.test-container/user.slice/user-1001.slice                   -      -    28.0K        -
```

And looking at the logs inside the container, normally this is removed by systemd after a few seconds after the command has finished.

But, I found that if the container is forcefully stopped before that after command duration has occurred (seems to be 15 seconds) 
then the cgroup is left behind (as well as its parents).

So one workaround would be to sleep for 15s before initiating the `lxc stop -f` command.
Alternatively you can also attempt to try and stop the container gracefully, but with a timeout and then forcefully shutdown.

e.g.

```
lxc stop $CONTAINER_NAME --timeout=15|| lxc stop $CONTAINER_NAME --force
```

@stgraber @brauner have you come across anything like this before? Where if the root user inside the container is mapped to the real root user, then the lxc monitor isn't able to clean up non-root cgroups left behind?

**Comment by tomponline** [comment] 2022-11-24 10:40
Any ideas @mihalicyn ?

**Comment by brauner** [comment] 2022-11-24 11:34
This is a permission issue by having the cgroup tree removal code run in a minimal user namespace if the container is unprivileged. We can trivially fix this by not running the cgroup removal code in a userns if the lxc monitor is root.

**Comment by brauner** [comment] 2022-11-24 11:47
This should do it https://github.com/lxc/lxc/pull/4231

**Comment by tomponline** [comment] 2022-11-24 11:48
Thanks! Once thats merged I'll test it locally with LXD.

**Closed** 2022-11-24 13:00 UTC
Labels: Bug

**Comment by tomponline** [comment] 2022-11-24 16:09
@brauner your PR fixes this issue nicely, thanks.

**Comment by gianfurrer** [comment] 2022-11-25 14:34
Thank you for the quick resolvement of this issue!
