### ISSUE TITLE
Release 2.9.2 - zfs - 'dataset does not exist' when launching with profile with root size defined

### ISSUE THREAD

**Issue by testeddoughnut** [lxc/lxd#2929] opened 2017-02-22 13:18 UTC
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04.2 LTS
 * The output of "lxc info" or if that fails:
```root@infra1:~# lxc info
config:
  core.https_address: 0.0.0.0:8443
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 192.168.0.6:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFOzCCAyOgAwIBAgIRAJwhtxp+YiwDXP+A6BfB29kwDQYJKoZIhvcNAQELBQAw
    NDEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEUMBIGA1UEAwwLcm9vdEBp
    bmZyYTEwHhcNMTcwMjE5MDI0MzA3WhcNMjcwMjE3MDI0MzA3WjA0MRwwGgYDVQQK
    ExNsaW51eGNvbnRhaW5lcnMub3JnMRQwEgYDVQQDDAtyb290QGluZnJhMTCCAiIw
    DQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBANd3wWWqVy70YK0cj49FC62fJQzm
    p0db5llY5lJHcWVWqCuIp2EQrnhDJbd2qjtF3AHdRQErI44IfrzBIuzqo3eOnlfL
    tv/DQBc8456aXA0vJYo2tSWi1B3PMUO03YbpYaKdIgLN6P5O+h/AI588a8XyTlnt
    OURMN5MymyhcU4nChzqyzTjzIQ/agb4q25UhLG+jy5GaJcixvzGxQhiZRyRdBQ4z
    2fqV/6pQdhSOn7xVsFM/AvE0Yevr8c/hyBm+qbpwy19TK0T0FFKVzVf+wXJkA1YW
    ccG929BVi1MKSSgxZZWeK3FhRMmT4zpIvvlikJ9Qd+N0vkAIyzzSpiC6zcNAHluj
    LGv0a7INoBtDETME2Q0pi6uWjRH0x74EGDLWqbDtQ0jY/oiKSWLsDHKqnR7JYW+y
    qlrGeZJVVOXuSnH8qjATa7Bn+umyHVKKamjmH0S4g+qyTdeEb298k8jGEhODgQtq
    8QZLf6lO+rx8R3+ugRHV6qHMXJ/JIjmBBZNwZPiPZR2rBG4krq1QWRDhCnYT1O11
    k+13e+7FHYkmCobiu1o8UuiLC83Exd4zwa3JYslEFN2yfpsSgklkwRwL3kN/t7Nq
    3eOjHRFNvzPGGLpFTq3XjQckA9C53I0OsnRm3En/xnzUSm6ZXpkhq0GSNMY4GNBV
    lTgtWYOaw/R4ZyYvAgMBAAGjSDBGMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAK
    BggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMBEGA1UdEQQKMAiCBmluZnJhMTANBgkq
    hkiG9w0BAQsFAAOCAgEAZbyv3tajqWkpB6plR86zF6whdRCLjdHXr+jSz+RmZb2R
    VYmFdILqsIW8Qm86yM6ZFAthbwYAg5UDRq1gAmOozK4rLSXxB8PZsk+Llpgvi/ME
    jE4yNLmBoSAyATzg5d5e3mghGFDlsvBkKSbInNt0MbFpx3RWsWB9Xw32zejk8y3k
    v+c7LYT3f3y0olfZ4zIyYyL4fwRzkNv0iIvJCiiPTDfceTjOqc1OxmrZNgPEX8DL
    h0MWKqI5OVvwUj+tlZLe+j018PFuW3FGP+GCqz63PIbyeAI/+e0hKj7M5+m8hIZR
    wNjKEXq2WrjoFh/K9mBfA4W24CruwOSc6zk59Zh/VB9yTAaXsED/XSinY0jT8XOD
    uCmtGU4XaqpWTKLhvW3IUMZdn8GzRrAAQ5DgToBK+PGm6JR92ZFEPtxEyZNHvZ7y
    mM+7DC6uBX/9lOUVgxe09tP7Fw+CNiy9cSjZuUzhqoqtwPAMyqqYMOf++jcdZ29M
    goFWchWCEvs/6ZZcX7zqMAqRbjAJA/NUskixRJhQ8jAPdb3rTW8kwZzFcIeDpPoL
    kwstDefOLvPS6EXeIE7utcIerBTAjpRk5SYvYbd9+M+BJvCgyMZmJfrkz+ZGurp4
    gAonOJczsjUHNS1kNTpOJE5H9vdOtigU/BEcWN0jK9ibni5P9d6Di7DzqMpnBCE=
    -----END CERTIFICATE-----
  certificate_fingerprint: e99bc30d7b3b7dd03cbe0c4f4102e1f51231c48ae1d2a5bc223cfb37c3fe7774
  driver: lxc
  driver_version: 2.0.7
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-64-generic
  server: lxd
  server_pid: 3282
  server_version: 2.9.2
  storage: zfs
  storage_version: 0.6.5.6-0ubuntu15
   * Kernel version: Linux infra1 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
   * LXC version: 2.0.7-0ubuntu1~ubuntu16.04.1~ppa1
   * LXD version: 2.9.2-0ubuntu1~ubuntu16.04.1~ppa1
   * Storage backend in use: zfs
```

# Issue description

This is my storage pool:
```
root@infra1:~# lxc storage show lxd
config:
  size: 4TB
  source: lxd
name: lxd
driver: zfs
used_by:
- /1.0/containers/git1
- /1.0/containers/ipa1
- /1.0/images/2552d6a35e09a0a569fe925aaa99d9f1aacfa96afbb93176d50daa46c4fa59df
```

This is a profile I have:
```
root@infra1:~# lxc profile show 8GB
config:
  limits.memory: 8GB
  limits.memory.enforce: hard
  limits.memory.swap: "false"
  limits.memory.swap.priority: "0"
description: 8GB RAM
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: lxd
    size: 100GB
    type: disk
name: 8GB
used_by:
- /1.0/containers/ipa1
```
I was able to create instances with this profile without issue prior to upgrading to 2.9.2. This is what happens if I create an instance now:

```
root@infra1:~# lxc launch images:centos/7 foreman1 --profile 8GB
Creating foreman1
error: Failed to set ZFS config: cannot open 'lxd/containers/foreman1': dataset does not exist
```

If I remove the 'size' option the container is created successfully. I can even add the 'size' option back into the profile after the container is created and it updates the container's size properly.

# Steps to reproduce

 1. Use a profile that has a size constraint on a disk from a zfs pool
 2. Launch from that profile

# Information to attach

 - [ ] any relevant kernel output (dmesg) - None
 - [ ] container log (lxc info NAME --show-log) - No container is created
 - [x] main daemon log (/var/log/lxd.log) - logs as follows:
```
root@infra1:~# journalctl --no-pager --unit=lxd --since='2017-02-22 06:46'
-- Logs begin at Wed 2017-02-22 06:02:53 CST, end at Wed 2017-02-22 06:46:06 CST. --
Feb 22 06:46:06 infra1 lxd[3282]: driver=storage/zfs lvl=eror msg="zfs set failed" output="cannot open 'lxd/containers/foreman1': dataset does not exist\n" t=2017-02-22T06:46:06-0600
Feb 22 06:46:06 infra1 lxd[3282]: ephemeral=false lvl=eror msg="Failed creating container" name=foreman1 t=2017-02-22T06:46:06-0600
```
 - [x] output of the client with --debug: https://gist.github.com/testeddoughnut/ff081b2ca32a77790370b5c4962a8571
 - [x] output of the daemon with --debug: https://gist.github.com/testeddoughnut/4078bff39bba203406ed10148610ce83

Some of the timestamps in the provided output don't exactly match up as I didn't have debug enabled when I was first gathering the output. I enabled it for the relevant parts.

**Comment by brauner** [comment] 2017-02-22 16:00
Ok, I think I pinned down the issue and a fix will be in `2.9.3` which we'll release soon!

**Comment by brauner** [comment] 2017-02-22 16:42
Right, the issue is that `ContainerSetQuota()` is called before the dataset actually exists. This problem existed before as well but didn't surface. With the new storage API we update the root disk device information in `containerCreateInternal()` this step is taking place before the actual container storage creation and hence, the call to `Update()` will try to set a dataset property on a non-existing dataset.

**Comment by brauner** [comment] 2017-02-22 17:30
Should be fixed by https://github.com/lxc/lxd/pull/2925.

**Closed** 2017-02-23 03:55 UTC
