### ISSUE TITLE
Error : error: Error transferring container data: Unable to connect to: xx.xx.xx.xx:8443

### ISSUE THREAD

**Issue by mou1234** [lxc/lxd#2019] opened 2016-05-11 21:24 UTC
* The output of "lxc info" or if that fails:
driver: lxc
  driverversion: 2.0.0
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.8-040408-generic
  server: lxd
  serverpid: 1350
  serverversion: 2.0.0
  storage: dir
  storageversion: ""
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
public: false

# Issue description
I tried to migrate the container to another machine from the cli.It worked for some machines but for some machines migration errored out as below
I couldnt find any other errors in the logs

Error : error: Error transferring container data: Unable to connect to: xx.xx.xx.xx:8443

 - [ ] container log (lxc info NAME --show-log)

lxc 20160511211820.933 DEBUG    lxc_commands - commands.c:lxc_cmd_get_state:579 - 'a1' is in 'RUNNING' state
            lxc 20160511211820.933 DEBUG    lxc_commands - commands.c:lxc_cmd_handler:893 - peer has disconnected
            lxc 20160511211820.933 DEBUG    lxc_commands - commands.c:lxc_cmd_handler:893 - peer has disconnected
            lxc 20160511211820.933 DEBUG    lxc_commands - commands.c:lxc_cmd_handler:893 - peer has disconnected
            lxc 20160511211820.933 DEBUG    lxc_commands - commands.c:lxc_cmd_get_state:579 - 'a1' is in 'RUNNING' state
            lxc 20160511211820.933 DEBUG    lxc_commands - commands.c:lxc_cmd_handler:893 - peer has disconnected
            lxc 20160511211820.933 DEBUG    lxc_commands - commands.c:lxc_cmd_handler:893 - peer has disconnected

**Comment by stgraber** [comment] 2016-05-11 21:25
That usually means that your target host couldn't connect to the source host to fetch the data.

**Comment by mou1234** [comment] 2016-05-11 21:28
Thanks Stgraber
I was able to migrate container from the target machine to source machinebut .I couldn't do it in the vice versa

**Comment by stgraber** [comment] 2016-05-11 21:30
Sounds like you have some kind of firewall in between or the IP address being used isn't routed from the target. #553 will fix that kind of problem.

**Comment by mou1234** [comment] 2016-05-11 21:42
yah .I have changed the firewall settings.Now i have tried again to migrate the container.
I got the below error.Now the issue seems to be with criu restoration in the destination Machine

Error transferring container data: restore failed:\n(00.952651)   2021: Error (arch/x86/crtools.c:341): FPU xsave area present, but host cpu doesn\'t support it\n(00.954261)   2087: Error (arch/x86/crtools.c:341): FPU xsave area present, but host cpu doesn\'t support it\n(00.954797)   2086: Error (sk-unix.c:901): sk unix: Can\'t connect 0x4ab5 socket: Connection refused\n(00.956056)   2085: Error (arch/x86/crtools.c:341): FPU xsave area present, but host cpu doesn\'t support it\n(00.956365)   1803: Error (sk-unix.c:901): sk unix: Can\'t connect 0x53a6 socket: Connection refused\n(00.956849)      1: Error (cr-restore.c:1384): 2021 exited, status=1\n(00.959750) Error (cr-restore.c:1387): 24267 killed by signal 9: Killed\n(00.959936) Error (files-reg.c:516):  `- XFail [/dev/null.cr_link.cr.1.ghost] ghost: No such file or directory\n(00.960199) Error (cr-restore.c:2223): Restoring FAILED.' } }


Source Cpu info
cat /proc/cpuinfo

cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
stepping	: 4
microcode	: 0x416
cpu MHz		: 2500.108
cache size	: 25600 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology eagerfpu pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm fsgsbase smep erms xsaveopt
bugs		:
bogomips	: 5000.21
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:


Destination CPU info:
cat /proc/cpuinfo
processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 21
model		: 2
model name	: AMD Opteron(tm) Processor 4332 HE
stepping	: 0
microcode	: 0x600081f
cpu MHz		: 3000.138
cache size	: 2048 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat clflush mmx fxsr sse sse2 syscall nx mmxext fxsr_opt lm rep_good nopl extd_apicid pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes f16c hypervisor lahf_lm cr8_legacy abm sse4a misalignsse 3dnowprefetch xop fma4 tbm arat vmmcall
bugs		: fxsave_leak sysret_ss_attrs
bogomips	: 6000.27
TLB size	: 1536 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 48 bits physical, 48 bits virtual
power management:

Thanks

**Comment by stgraber** [comment] 2016-05-11 21:57
Can you file the CRIU bug at https://launchpad.net/ubuntu/+source/criu/+filebug ?

See https://www.stgraber.org/2016/04/25/lxd-2-0-live-migration-912/ for what to include in the report.

I'm closing this LXD issue as it's basically a duplicate of #553

**Closed by stgraber** 2016-05-11 21:57 UTC
