### ISSUE TITLE
Nictype: routed broken on multiple VLANs setup

### ISSUE THREAD

**Issue by s3rj1k** [lxc/lxd#7152] opened 2020-04-07 18:01 UTC
Issue is similar to this one https://github.com/lxc/lxd/issues/7123

Multiple VLANs setup like (`ip a`):
```
2: ens1f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:1b:21:bc:d1:48 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::21b:21ff:febc:d148/64 scope link
       valid_lft forever preferred_lft forever
10: vlan221@ens1f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:1b:21:bc:d1:48 brd ff:ff:ff:ff:ff:ff
    inet 192.168.127.110/27 brd 5.149.127.127 scope global vlan221
       valid_lft forever preferred_lft forever
    inet6 fe80::21b:21ff:febc:d148/64 scope link
       valid_lft forever preferred_lft forever
11: vlan220@ens1f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:1b:21:bc:d1:48 brd ff:ff:ff:ff:ff:ff
    inet 192.168.127.80/27 brd 5.149.127.95 scope global vlan220
       valid_lft forever preferred_lft forever
    inet6 fe80::21b:21ff:febc:d148/64 scope link
       valid_lft forever preferred_lft forever
```

On container start interface is created:
```
16: vethae8770ca@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether fe:7b:54:5c:e3:7c brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 169.254.0.1/32 scope global vethae8770ca
       valid_lft forever preferred_lft forever
    inet6 fe80::fc7b:54ff:fe5c:e37c/64 scope link
       valid_lft forever preferred_lft forever
```

Container IP is `192.168.127.81`.

To actually get a working network on container, this command must be run:
`ip route add local 192.168.127.81/32 dev vethae8770ca`

This is also an ProxyARP issue as with https://github.com/lxc/lxd/issues/7123

Routes on physical node (`ip r`):
```
default via 192.168.127.97 dev vlan221 proto static
192.168.127.64/27 dev vlan220 proto kernel scope link src 192.168.127.80
192.168.127.81 dev vethae8770ca scope link
192.168.127.96/27 dev vlan221 proto kernel scope link src 192.168.127.110
```

Policy routing (`ip rule list`)_[this is not related to the issue with ARP]_:
```
0:      from all lookup local
2201:   from all iif vlan220 lookup 4220
2202:   from 192.168.127.69/27 lookup 4220
2211:   from all iif vlan221 lookup 4221
2212:   from 192.168.127.96/27 lookup 4221
32766:  from all lookup main
32767:  from all lookup default
```

Custom routing table 4220 (`ip r list table 4220`):
```
default via 192.168.127.65 dev vlan220
```

Custom routing table 4221 (`ip r list table 4221`):
```
default via 192.168.127.97 dev vlan221
```

There are other two issues with `nictype: routed`
 - reading the docs for this type I had an impression that IP addresses inside CT **are configured by LXD**, just like with `nictype: ipvlan`, this **is not the case**.
 - Automatic Private IP Addressing (`ipv4.host_address`), that field should have more options.

Consider adding this options to `ipv4.host_address`:
 - manual setup.
 - auto-generated IP in 169.254.0.1 through 169.254.255.254 range (default option).
 - disabled, `veth` does not have APIPA set.

**Comment by s3rj1k** [comment] 2020-04-07 18:02
@tomponline Can you please look at this?

**Comment by tomponline** [comment] 2020-04-08 09:04
@s3rj1k please could you open a separate issue for the improvements you suggested, along with use cases explaining what you are aiming to use them for? That way they won't get lost if we close this card for the primary issue reported. Thanks

Now, with the issue in question. I need to test this using VLANs like #7123 as really proxy ARP should work as normal with them, but it maybe the kernel is not doing it for some reason.

I'm not convinced (yet) about the `local` route approach, especially with `routed` NIC types, because local routes have the effect normally of making that behave like an IP alias on the host (i.e the host responds to packets and doesn't route them into the container), which is not what we want here.

You also mentioned that you expected `routed` to configure the IP address and gateway. You are correct it does do that. However if you are not seeing that happen, have you checked that the network setup process inside the container isn't erasing the settings configured by LXD as it starts (netplan does this).

**Comment by tomponline** [comment] 2020-04-08 14:41
@s3rj1k I did some testing on this today, here is my setup:

On LXD host:

Create an VLAN interface called `enp4s0f0.100`
````
sudo ip link add link enp4s0f0 name enp4s0f0.100 type vlan id 100
sudo ip add add 10.0.0.2/24 dev enp4s0f0.100
sudo ip link set enp4s0f0.100 up
```

On remote host in same VLAN:

```
sudo ip link add link eth0 name eth0 type vlan id 100
sudo ip add add 10.0.0.1/24 dev eth0.100
sudo ip link set eth0.100 up
```

Back on LXD host, create container and setup routed NIC:
```
lxc init ubuntu:18.04 c1
lxc config device add c1 eth0 nic nictype=routed parent=enp4s0f0 vlan=100 ipv4.address=10.0.0.3
lxc start c1
lxc shell c1
Modify /etc/netplan/50-cloud-init.yaml to:
network:
    version: 2
exit
lxc stop c1
lxc start c1
lxc ls c1
+------+---------+-----------------+------+-----------+-----------+
| NAME |  STATE  |      IPV4       | IPV6 |   TYPE    | SNAPSHOTS |
+------+---------+-----------------+------+-----------+-----------+
| c1   | RUNNING | 10.0.0.3 (eth0) |      | CONTAINER | 0         |
+------+---------+-----------------+------+-----------+-----------+
```

Check ping between hosts:

On remote host:
```
ping 10.0.0.3
ping 10.0.0.3
PING 10.0.0.3 (10.0.0.3): 56 data bytes
64 bytes from 10.0.0.3: seq=0 ttl=63 time=220.396 ms
64 bytes from 10.0.0.3: seq=1 ttl=63 time=0.316 ms
64 bytes from 10.0.0.3: seq=2 ttl=63 time=0.315 ms
64 bytes from 10.0.0.3: seq=3 ttl=63 time=0.325 ms
^C
--- 10.0.0.3 ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max = 0.315/55.338/220.396 ms
```

On LXD host:
```
lxc exec c1 -- ping 10.0.0.1
PING 10.0.0.1 (10.0.0.1) 56(84) bytes of data.
64 bytes from 10.0.0.1: icmp_seq=1 ttl=63 time=0.288 ms
64 bytes from 10.0.0.1: icmp_seq=2 ttl=63 time=0.343 ms
64 bytes from 10.0.0.1: icmp_seq=3 ttl=63 time=0.351 ms
64 bytes from 10.0.0.1: icmp_seq=4 ttl=63 time=0.377 ms
^C
--- 10.0.0.1 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3057ms
rtt min/avg/max/mdev = 0.288/0.339/0.377/0.039 ms
```

So this seems to work fine with VLAN.

I have noticed there is some improvements to the way we validate sysctl settings on VLAN parents though so will put up a PR for that.

I've also noticed that the Linux kernel will not respond to proxy ARP entries unless the parent interface has an IP address on it that is part of the same subnet as the IP being proxied. Perhaps that is what you are experiencing?

**Comment by s3rj1k** [comment] 2020-04-08 19:43
@tomponline About local routes you can check this great article: 
https://alexaf.gitlab.io/posts/arp_proxy_going_rogue_pt1/
local routes are needed for non-local IPs it just does not work without them

**Comment by s3rj1k** [comment] 2020-04-08 19:45
@tomponline I'll do other issues them this main problem gets solved, as in this current state LXD is unusable for my setup and this is sad :(

**Comment by s3rj1k** [comment] 2020-04-08 19:50
@tomponline 

```
I've also noticed that the Linux kernel will not respond to proxy ARP entries unless the parent interface has an IP address on it that is part of the same subnet as the IP being proxied. Perhaps that is what you are experiencing?
```

My IPs are from same subnets, you can see in original example.

`192.168.` prefix is used to hide real IP networks from public, I am actually using none private IP address block for tests.

**Comment by s3rj1k** [comment] 2020-04-08 19:52
@tomponline I can give you access to a server instance with this setup if needed.

**Comment by s3rj1k** [comment] 2020-04-08 20:41
@tomponline To replicate issue please add another VLAN to your setup and check that IP from this VLAN **is not in default route network**

Also check your email please :)

**Comment by s3rj1k** [comment] 2020-04-09 08:10
Ok, preliminarily tests show that issue occurs then policy routing is set to routed 2-nd VLAN network space through proper VLAN interface.
In this setup kernel does not know that it has to do ARP for 2-nd VLAN network on none-default gateway interface.

This is how Policy Routing is set up to replicated this issue:
```
# ip rule list
0:      from all lookup local
2202:   from 192.168.127.69/27 lookup 4220
32766:  from all lookup main
32767:  from all lookup default
# ip r l table 4220
default via 192.168.127.65 dev vlan220
```

**Comment by tomponline** [comment] 2020-04-09 14:43
Confirmed using 2 VLANs without default gateway works OK:

LXD host trunk port and 2 VLAN interfaces (100 and 101):

```
10: enp4s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 6c:b3:11:1c:09:52 brd ff:ff:ff:ff:ff:ff
19: enp4s0f0.100@enp4s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 6c:b3:11:1c:09:52 brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.2/24 scope global enp4s0f0.100
       valid_lft forever preferred_lft forever
    inet6 fe80::6eb3:11ff:fe1c:952/64 scope link 
       valid_lft forever preferred_lft forever
20: enp4s0f0.101@enp4s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 6c:b3:11:1c:09:52 brd ff:ff:ff:ff:ff:ff
    inet 10.0.1.2/24 scope global enp4s0f0.101
       valid_lft forever preferred_lft forever
    inet6 fe80::6eb3:11ff:fe1c:952/64 scope link 
       valid_lft forever preferred_lft forever
```

Two containers:

```
lxc init ubuntu:18.04 c1 # Disable netplan for eth0
lxc init ubuntu:18.04 c2 # Disable netplan for eth0
lxc config device add c1 eth0 nic nictype=routed name=eth0 parent=enp4s0f0 vlan=100 ipv4.address=10.0.0.3
lxc config device add c2 eth0 nic nictype=routed name=eth0 parent=enp4s0f0 vlan=101 ipv4.address=10.0.1.3
lxc start c1 c2
lxc ls 
+------+---------+-----------------+------+-----------+-----------+
| NAME |  STATE  |      IPV4       | IPV6 |   TYPE    | SNAPSHOTS |
+------+---------+-----------------+------+-----------+-----------+
| c1   | RUNNING | 10.0.0.3 (eth0) |      | CONTAINER | 0         |
+------+---------+-----------------+------+-----------+-----------+
| c2   | RUNNING | 10.0.1.3 (eth1) |      | CONTAINER | 0         |
+------+---------+-----------------+------+-----------+-----------+
```

```
ip neigh show proxy
169.254.0.1 dev vethf08cbda4  proxy
169.254.0.1 dev veth2249e31e  proxy
10.0.1.3 dev enp4s0f0.101  proxy
10.0.0.3 dev enp4s0f0.100  proxy
```

```
ip r
10.0.0.3 dev veth2249e31e scope link 
10.0.1.3 dev vethf08cbda4 scope link 
10.0.0.0/24 dev enp4s0f0.100 proto kernel scope link src 10.0.0.2 
10.0.1.0/24 dev enp4s0f0.101 proto kernel scope link src 10.0.1.2 
```

On another host on the connect with a trunk port:

```
3: eth0.100@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP qlen 1000
    link/ether 28:92:4a:32:0c:e2 brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.1/24 scope global eth0.100
       valid_lft forever preferred_lft forever
    inet6 fe80::2a92:4aff:fe32:ce2/64 scope link 
       valid_lft forever preferred_lft forever
4: eth0.101@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP qlen 1000
    link/ether 28:92:4a:32:0c:e2 brd ff:ff:ff:ff:ff:ff
    inet 10.0.1.1/24 scope global eth0.101
       valid_lft forever preferred_lft forever
    inet6 fe80::2a92:4aff:fe32:ce2/64 scope link 
       valid_lft forever preferred_lft forever
```

```
ip r
10.0.0.0/24 dev eth0.100 scope link  src 10.0.0.1 
10.0.1.0/24 dev eth0.101 scope link  src 10.0.1.1 
```

Tests from remote host:

```
ping 10.0.0.3 -c 3
PING 10.0.0.3 (10.0.0.3): 56 data bytes
64 bytes from 10.0.0.3: seq=0 ttl=63 time=0.374 ms
64 bytes from 10.0.0.3: seq=1 ttl=63 time=0.281 ms
64 bytes from 10.0.0.3: seq=2 ttl=63 time=0.341 ms

--- 10.0.0.3 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.281/0.332/0.374 ms
```

```
ping 10.0.1.3 -c 3
PING 10.0.1.3 (10.0.1.3): 56 data bytes
64 bytes from 10.0.1.3: seq=0 ttl=63 time=0.361 ms
64 bytes from 10.0.1.3: seq=1 ttl=63 time=0.283 ms
64 bytes from 10.0.1.3: seq=2 ttl=63 time=0.339 ms

--- 10.0.1.3 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.283/0.327/0.361 ms
```

I'm not that familiar with policy routing, how would you expect the proxy ARP to use the multiple routing tables?

**Comment by s3rj1k** [comment] 2020-04-09 15:20
@tomponline Policy routing is need for fixing issue when CT will answer from default gateway interface instead of the interface that has respected network (of CT) defined to it.

How you can check:
 - start `tcpdump -ni eth0.100 icmp`
 - start `tcpdump -ni eth0.101 icmp`
 - `ping 10.0.1.3`
 - `ping 10.0.0.3`

What you want to see in this tcpdumps, that request and response of each ping are on same interface.

What you will see without policy routing: requests/responses (depends on a starting side of ping, from CT or from remote location) for network that has none default route will send requests/responses from default route interface, this is wrong and should be avoided.

One reason that you do not see this, you do your lab setup with Private address space.

To see this problem in wild, do a lab setup with real IP space.

**Comment by tomponline** [comment] 2020-04-09 15:32
@s3rj1k yes I see what you mean I think (trying to ping the remote host between subnets doesn't work) as it doesn't route to the default gateway but instead tries to resolve ARP locally over the vlan interface.

**Comment by tomponline** [comment] 2020-04-15 08:16
@s3rj1k I've re-created this issue in my environment.

Confirmed that proxy ARP doesn't take effect without adding a static route for the container into the custom routing table:

```
 ip rule list
0:	from all lookup local 
32765:	from all iif enp4s0f0.100 lookup 100 
32766:	from all lookup main 
32767:	from all lookup default 
```

```
ip r show table main
default via 192.168.1.2 dev enp3s0 proto dhcp metric 100 
10.0.0.0/24 dev enp4s0f0.100 proto kernel scope link src 10.0.0.2 
10.0.0.3 dev vethae345b81 scope link 
169.254.0.0/16 dev enp3s0 scope link metric 1000 
192.168.1.0/24 dev enp3s0 proto kernel scope link src 192.168.1.109 metric 100 
```
```
ip r show table 100
10.0.0.0/24 dev enp4s0f0.100 scope link 
```

We can also see the ARP resolution attempts (and no replies) from the remote node on the LXD node's VLAN interface:

```
tcpdump -nn -i enp4s0f0.100
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on enp4s0f0.100, link-type EN10MB (Ethernet), capture size 262144 bytes
09:03:11.978014 ARP, Request who-has 10.0.0.3 tell 10.0.0.1, length 46
09:03:13.960229 ARP, Request who-has 10.0.0.3 tell 10.0.0.1, length 46
```

Ping from remote node on VLAN 100 fails in this case.

But adding a static route for the container into the custom routing table succeeds:

```
ip r add table 100 10.0.0.3 dev vethae345b81
```

We can see pings flowing:

```
tcpdump -nn -i enp4s0f0.100
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on enp4s0f0.100, link-type EN10MB (Ethernet), capture size 262144 bytes
09:04:12.975554 IP 10.0.0.1 > 10.0.0.3: ICMP echo request, id 29962, seq 435, length 64
09:04:12.975812 IP 10.0.0.3 > 10.0.0.1: ICMP echo reply, id 29962, seq 435, length 64
09:04:13.975818 IP 10.0.0.1 > 10.0.0.3: ICMP echo request, id 29962, seq 436, length 64
09:04:13.975892 IP 10.0.0.3 > 10.0.0.1: ICMP echo reply, id 29962, seq 436, length 64
```

It is also worth noting that removing the container's static route from the `main` routing table is also not recommended. This is counter intuitive because in principle it should not be needed anymore. However I found in my tests that when this static route was removed the LXD host the stopped replying to ARP resolution requests for the container's gateway `169.254.0.1` on the container's host interface `vethae345b81`.

E.g.

```
ip r del 10.0.0.3 dev vethae345b81
```

```
tcpdump -nn -i vethae345b81
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on vethae345b81, link-type EN10MB (Ethernet), capture size 262144 bytes
09:06:50.016617 IP 10.0.0.1 > 10.0.0.3: ICMP echo request, id 29962, seq 592, length 64
09:06:50.016577 ARP, Request who-has 169.254.0.1 tell 10.0.0.3, length 28
09:06:51.016850 IP 10.0.0.1 > 10.0.0.3: ICMP echo request, id 29962, seq 593, length 64
09:06:51.040582 ARP, Request who-has 169.254.0.1 tell 10.0.0.3, length 28
09:06:52.017120 IP 10.0.0.1 > 10.0.0.3: ICMP echo request, id 29962, seq 594, length 64
09:06:53.017380 IP 10.0.0.1 > 10.0.0.3: ICMP echo request, id 29962, seq 595, length 64
09:06:53.017421 ARP, Request who-has 169.254.0.1 tell 10.0.0.3, length 28
```

It occurred to me that this may be reverse path filtering kicking in (as rp filtering seems to check the main routing table).

````
sysctl net.ipv4.conf.all.log_martians=1
````

And sure enough:

```
[ 4437.137227] IPv4: martian source 169.254.0.1 from 10.0.0.3, on dev vethae345b81
[ 4437.137231] ll header: 00000000: ff ff ff ff ff ff 5e f5 7d 4c a2 27 08 06
```

Even adding an additional policy rule to filter traffic from the container's interface into the custom routing table did not help.

```
ip rule show
0:	from all lookup local 
32763:	from 10.0.0.0/24 lookup 100 
32764:	from all iif vethae345b81 lookup 100 
32765:	from all iif enp4s0f0.100 lookup 100 
32766:	from all lookup main 
32767:	from all lookup default 
```

As we enable rp_filtering at two levels for `routed` NICs by default (using both rp_filter sysctl and iptables rp_filter module) I will ensure that we still add a static route for the container to the host's main table to ensure that rp filtering doesn't block the container's gateway ARP resolution.

Speaking with @stgraber we have decided upon adding a `host_table` setting to the `routed` NIC type which will take a routing table number which we will add static routes to in addition to the main routing table. This will only take a numeric routing table ID so that it will work inside snap.

**Comment by s3rj1k** [comment] 2020-04-15 10:15
@tomponline This https://github.com/lxc/lxd/pull/7192 should also help with `ipvlan` https://github.com/lxc/lxd/issues/7123

And Yay !

Thanks @tomponline, @stgraber

**Closed** 2020-04-15 15:26 UTC
Labels: Feature
