### ISSUE TITLE
XHProf php extension can see all cpu cores

### ISSUE THREAD

**Issue by k-hristov** [lxc/lxd#3131] opened 2017-03-30 11:30 UTC
* Distribution: Ubuntu
 * Distribution version: 16.04 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.8.0-39-generic
   * LXC version: 
   * LXD version: 2.0.9
   * Storage backend in use: ZFS

# Issue description

I have a container that acts as a web server. We use php 5.6 and xhprof extension is also installed. At phpinfo() in the xhprof section there is a column "CPU num" which shows all CPUs of the physical machine. 

The container has a limit of 4 CPUs only.

Here is a screenshot:
http://prntscr.com/eqah1c

# Steps to reproduce

 1. Create container
 2. Limit CPU cores 
 3. install php, php-xhprof and run phpinfo();

**Comment by brauner** [comment] 2017-03-30 12:33
There are quite a bunch of ways to retrieve what cores are available on a given system aside from proc which we virtualize with lxcfs. So if this phone stuff is doing something like that I fear there is nothing we can do about it. But can you show the output of proc cpuinfo and also ensure that you have lxcfs installed and running.

**Comment by dann1** [comment] 2017-03-30 12:45
Yesterday I saw something similar, I limited the CPUs in a continainer to 1, and typing `cat /proc/cpuinfo | grep proces`  showed me 1 core, however, I typed `lscpu` and I saw 2 cores, here is the ouput

```
 cat /proc/cpuinfo | grep proces
processor       : 0
```

```
lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             2
NUMA node(s):          1
Vendor ID:             AuthenticAMD
CPU family:            21
Model:                 19
Model name:            AMD A10-5757M APU with Radeon(tm) HD Graphics
Stepping:              1
CPU MHz:               2495.466
BogoMIPS:              4990.93
Hypervisor vendor:     VMware
Virtualization type:   full
L1d cache:             16K
L1i cache:             64K
L2 cache:              2048K
NUMA node0 CPU(s):     0,1
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl tsc_reliable nonstop_tsc aperfmperf pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic popcnt aes xsave avx f16c hypervisor lahf_lm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw xop fma4 tbm vmmcall bmi1 arat
```

- Distribution: Ubuntu
- Distribution version: 16.04 LTS
-   driver: lxc
-  driverversion: 2.0.7
-  kernel: Linux
-  kernelarchitecture: x86_64
-  kernelversion: 4.4.0-63-generic
-  server: lxd
-  serverpid: 1515
-  serverversion: 2.0.9
-  storage: btrfs
-  storageversion: "4.4"

**Comment by k-hristov** [comment] 2017-03-30 12:50
On host machine lxcfs
`
root@srv02:~# dpkg -l |grep lxcfs
ii  lxcfs                              2.0.6-0ubuntu1~16.04.1          amd64        FUSE based filesystem for LXC
root@srv02:~# /etc/init.d/lxcfs status
● lxcfs.service - FUSE filesystem for LXC
   Loaded: loaded (/lib/systemd/system/lxcfs.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2017-03-01 14:30:53 EET; 4 weeks 1 days ago
     Docs: man:lxcfs(1)
 Main PID: 14156 (lxcfs)
    Tasks: 7
   Memory: 27.9M
      CPU: 54min 39.876s
   CGroup: /system.slice/lxcfs.service
           └─14156 /usr/bin/lxcfs /var/lib/lxcfs/

Mar 01 14:30:53 srv02 lxcfs[14156]:   1: fd:   6: devices
Mar 01 14:30:53 srv02 lxcfs[14156]:   2: fd:   7: cpuset
Mar 01 14:30:53 srv02 lxcfs[14156]:   3: fd:   8: freezer
Mar 01 14:30:53 srv02 lxcfs[14156]:   4: fd:   9: perf_event
Mar 01 14:30:53 srv02 lxcfs[14156]:   5: fd:  10: hugetlb
Mar 01 14:30:53 srv02 lxcfs[14156]:   6: fd:  11: pids
Mar 01 14:30:53 srv02 lxcfs[14156]:   7: fd:  12: cpu,cpuacct
Mar 01 14:30:53 srv02 lxcfs[14156]:   8: fd:  13: memory
Mar 01 14:30:53 srv02 lxcfs[14156]:   9: fd:  14: blkio
Mar 01 14:30:53 srv02 lxcfs[14156]:  10: fd:  15: name=systemd
`
 
on container:
`
cat /proc/cpuinfo |grep processor
processor	: 0
processor	: 1
processor	: 2
processor	: 3
`

**Comment by brauner** [comment] 2017-03-30 13:16
As I said this is likely caused by lscpu and this php stuff by reading this info from sysfs rather than proc. We may end up virtualizing some of sys too. There might already be a lxcfs issue for this. If not might be worth to open one. (@stgraber, @hallyn)

**Comment by stgraber** [comment] 2017-03-30 16:07
Yeah, we do have a lxcfs issue for /sys/class/cpu, it's here: https://github.com/lxc/lxcfs/issues/88
The other lxcfs bug mentioned above was about the syscall way of grabbing that same information which we unfortunately can't do anything about.

Closing the LXD side of this report as that's a lxcfs or kernel issue instead.

**Closed by stgraber** 2017-03-30 16:07 UTC
