### ISSUE TITLE
Ubuntu Artful (17.10) containers are missing their network configuration on Debian host

### ISSUE THREAD

**Issue by BobVul** [lxc/lxd#4262] opened 2018-02-19 06:15 UTC
# Issue description

This seems similar to #3954.

I can only reproduce it on LXD 2.21 on Debian Stretch (via Snap). 2.0.11 on a Ubuntu Xenial host does not have this issue.

On the Debian host, the container has no IPv4 address and is missing a `/etc/netplan/50-cloud-init.yaml` file. On the Ubuntu host, the container has a DHCP-assigned IPv4 address and has the `/etc/netplan/50-cloud-init.yaml` file.

Not sure yet if it's because of Debian, Snap or the newer version - I currently don't have any other test systems.

```
root@artful:~# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
67: eth0@if68: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:16:3e:e8:99:fd brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::216:3eff:fee8:99fd/64 scope link
       valid_lft forever preferred_lft forever
root@artful:~# ls /etc/netplan
root@artful:~# ls /var/lib/cloud
seed
root@artful:~# ls /var/lib/cloud/seed/nocloud-net/
meta-data  network-config  user-data  vendor-data
```

# Steps to reproduce

 1. Start with a Debian Stretch host with ZFS and a default LXD install via Snap. Containers live in a dataset on the root zpool.
 2. `lxc launch ubuntu:artful artful`
 3. `lxc exec artful bash`
 4. At this point, `ping 8.8.8.8` fails. `ip addr` shows no address on the eth0 interface. `/etc/netplan` is empty (missing cloud-init default config).

# Required information

 * Distribution: Debian
 * Distribution version: Stretch
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.9.0-4-amd64
   * LXC version: 2.21
   * LXD version: 2.21
   * Storage backend in use: ZFS

```config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  certificate_fingerprint: 7c130ecffca7dd414f1219fcd75164afe44d0508a041dfb060020042da80db25
  driver: lxc
  driver_version: 2.1.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.9.0-4-amd64
  server: lxd
  server_pid: 25114
  server_version: "2.21"
  storage: zfs
  storage_version: 0.6.5.9-5
```

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
None logged since container start
 - [x] Container log (`lxc info NAME --show-log`)

```
Name: artful
Remote: unix://
Architecture: x86_64
Created: 2018/02/19 05:46 UTC
Status: Running
Type: persistent
Profiles: default
Pid: 26372
Ips:
  eth0: inet6   fe80::216:3eff:fefe:4a20        vethIJRJJF
  lo:   inet    127.0.0.1
  lo:   inet6   ::1
Resources:
  Processes: 1
  Disk usage:
    root: 8.23MB
  CPU usage:
    CPU usage (in seconds): 0
  Memory usage:
    Memory (current): 4.18MB
    Memory (peak): 5.04MB
  Network usage:
    lo:
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0
    eth0:
      Bytes received: 718B
      Bytes sent: 648B
      Packets received: 9
      Packets sent: 8

Log:

            lxc 20180219054701.194 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20180219054701.194 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20180219054701.235 WARN     lxc_conf - conf.c:lxc_map_ids:2672 - newuidmap binary is missing
            lxc 20180219054701.235 WARN     lxc_conf - conf.c:lxc_map_ids:2678 - newgidmap binary is missing
            lxc 20180219054701.236 WARN     lxc_conf - conf.c:lxc_map_ids:2672 - newuidmap binary is missing
            lxc 20180219054701.236 WARN     lxc_conf - conf.c:lxc_map_ids:2678 - newgidmap binary is missing
            lxc 20180219054701.364 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20180219054701.364 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
```

 - [x] Container configuration (`lxc config show NAME --expanded`)
```
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 17.10 amd64 (release) (20180126)
  image.label: release
  image.os: ubuntu
  image.release: artful
  image.serial: "20180126"
  image.version: "17.10"
  volatile.base_image: 41eb905c444d169b9dbb2d8435692699872680441269789ca740ea7c1dbde9d7
  volatile.eth0.hwaddr: 00:16:3e:fe:4a:20
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

 - [x] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
```
ephemeral=false lvl=info msg="Creating container" name=artful t=2018-02-19T05:46:57+0000
ephemeral=false lvl=info msg="Created container" name=artful t=2018-02-19T05:46:57+0000
lvl=warn msg="Unable to update backup.yaml at this time." name=artful t=2018-02-19T05:47:01+0000
action=start created=2018-02-19T05:46:57+0000 ephemeral=false lvl=info msg="Starting container" name=artful stateful=false t=2018-02-19T05:47:01+0000 used=1970-01-01T00:00:00+0000
action=start created=2018-02-19T05:46:57+0000 ephemeral=false lvl=info msg="Started container" name=artful stateful=false t=2018-02-19T05:47:01+0000 used=1970-01-01T00:00:00+0000
```

 - [ ] Output of the client with --debug

 - [x] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

Gist: https://gist.github.com/BobVul/6c92a8f26c6c3d13681bb26c08a91cf4

**Comment by BobVul** [comment] 2018-02-19 06:18
In fact, looking into it more:

* The cloud-init logs are never created. I suppose that means it failed to run.
* Much like @weycrest mentioned in [their comment](https://github.com/lxc/lxd/issues/3954#issuecomment-362899581), many expected daemons (including systemd) are not started:

Debian host:

```
  PID TTY          TIME CMD
    1 ?        00:00:00 systemd
   36 ?        00:00:00 bash
   57 ?        00:00:00 ps
```

Ubuntu host:

```
  PID TTY          TIME CMD
    1 ?        00:00:00 systemd
   50 ?        00:00:00 systemd-journal
   55 ?        00:00:00 systemd-udevd
  147 ?        00:00:00 systemd-network
  192 ?        00:00:00 rsyslogd
  193 ?        00:00:00 systemd-logind
  194 ?        00:00:00 systemd-resolve
  195 ?        00:00:00 cron
  196 ?        00:00:00 dbus-daemon
  199 ?        00:00:00 accounts-daemon
  200 ?        00:00:00 snapd
  202 ?        00:00:00 atd
  214 console  00:00:00 agetty
  215 ?        00:00:00 polkitd
  217 ?        00:00:00 sshd
  301 ?        00:00:40 lxd
  321 ?        00:00:00 bash
  338 ?        00:00:00 ps
```

I'll see if I can get 2.21 up on another Ubuntu host for comparison.

**Comment by stgraber** [comment] 2018-02-19 06:25
That looks like systemd crashed early into boot. This can happen as the result of an unusual cgroup layout as systemd will just plain crash in such cases.

**Comment by stgraber** [comment] 2018-02-19 06:26
Going to look into this on our test runner to see whether it affects our Debian install too and if there's an easy fix for this.

**Comment by BobVul** [comment] 2018-02-19 06:56
Ok, 2.21 on Snap on Ubuntu 16.04 works. So it seems to be just a Debian thing.

I probably should mention that Zesty and previous works fine on Debian. So just a Debian host / Artful container thing.

**Comment by stgraber** [comment] 2018-02-19 06:57
Ok, so looks like the issue is that your kernel supports the unified cgroup hierarchy but the host systemd didn't configure it, so the container can mount it but can't configure anything inside it...

There are two options there, one is to convince systemd in the container to not attempt to use the unified hierarchy, the other is to create and set it up properly on the host so that the container is happy.

**Comment by BobVul** [comment] 2018-02-19 06:59
Is that something that should be handled by LXD, or by the image maintainers?

**Comment by stgraber** [comment] 2018-02-19 07:01
Neither unfortunately, it's something that maybe systemd itself can be taught to handle properly.
The workaround is:

```
root@snap-debian-stretch:~# lxc config set ubuntu-1710 raw.lxc "lxc.init.cmd=/sbin/init systemd.legacy_systemd_cgroup_controller=true"
root@snap-debian-stretch:~# lxc restart ubuntu-1710 --force
```

**Comment by stgraber** [comment] 2018-02-19 07:06
LXD doesn't know what the container is going to be running, what it does is for every existing cgroup on the system, it creates a suitable path and then unshares a mount namespace.

The image itself is just a plain copy of the distribution with its version of systemd, the image and in fact the container don't know what's mounted on the host. In most cases, if the kernel supports cgroup2, the systemd that comes with the distro will be making use of it, which then makes all containers work. If the kernel has cgroup2 disabled, then again, all is well.

The problem is when your kernel has cgroup2 enabled but your host doesn't configure it, because the containers will detect its presence and attempt to use it, failing with permission problems.

The workaround above should be fine to use and even put in a profile on such systems.
It may be possible to make systemd handle errors and falling back in such cases, but it's already a very weird and complex logic to handle cgroup1 alone, hybrid cgroup1/cgroup2 and cgroup2 alone, so not sure how open they'd be to making it more complex.

@brauner may have ideas there.

Closing the LXD issue as I don't believe there's really anything we should be doing for this, other than try to get systemd to improve its behavior there.

**Closed by stgraber** 2018-02-19 07:06 UTC

**Comment by BobVul** [comment] 2018-02-19 07:17
Well, that's a deep rabbithole. And it looks like they [might want to drop cgroup1](https://lists.freedesktop.org/archives/systemd-devel/2017-November/039760.html) at some point.

Thanks for the workaround. I guess I'm stuck with it until I can update the host (and assuming Buster/AppArmor doesn't break more things).

Would it make any sense to apply this workaround automatically? Assuming it's possible to detect the case of cgroup2 enabled but not configured, and that applying it on a container that does not support cgroup2 should have no effect. Though it's probably a rare enough case that it's not worth cluttering the code - I'll add it to a profile anyway.

**Comment by stgraber** [comment] 2018-02-19 17:03
@BobVul can you share your /proc/self/mountinfo from the host as well as /proc/self/cgroup?
Also, are you running any privileged containers on this machine?

I was just thinking that it's odd that the container could mount a cgroup2 hierarchy at all if it was never initialized by something, but that something could be a privileged container...

**Comment by BobVul** [comment] 2018-02-19 23:23
@stgraber I have three Debian hosts I've confirmed this happens on.

* #&#x200B;1 has a single privileged container (Debian Stretch inside the container, which presumably does the same as the host and does not use cgroup2). This one boots from ZFS root.
* #&#x200B;2 is almost identical to #&#x200B;1 but has no privileged containers.
* #&#x200B;3 has no privileged containers - in fact, I've cleaned it up (deleted the only other container) and rebooted, and it still occurs. This one is a Scaleway VM (kvm) that has been kexec'd into the distro standard kernel (`4.9.0-5-amd64`).

From #&#x200B;1:

```
root@amaterasu:~# cat /proc/self/mountinfo
17 22 0:17 / /sys rw,nosuid,nodev,noexec,relatime shared:7 - sysfs sysfs rw
18 22 0:4 / /proc rw,nosuid,nodev,noexec,relatime shared:12 - proc proc rw
19 22 0:6 / /dev rw,nosuid,relatime shared:2 - devtmpfs udev rw,size=16411552k,nr_inodes=4102888,mode=755
20 19 0:18 / /dev/pts rw,nosuid,noexec,relatime shared:3 - devpts devpts rw,gid=5,mode=620,ptmxmode=000
21 22 0:19 / /run rw,nosuid,noexec,relatime shared:5 - tmpfs tmpfs rw,size=3284768k,mode=755
22 0 0:20 / / rw,relatime shared:1 - zfs tank/ROOT/debian rw,xattr,noacl
23 17 0:16 / /sys/kernel/security rw,nosuid,nodev,noexec,relatime shared:8 - securityfs securityfs rw
24 19 0:21 / /dev/shm rw,nosuid,nodev shared:4 - tmpfs tmpfs rw
25 21 0:22 / /run/lock rw,nosuid,nodev,noexec,relatime shared:6 - tmpfs tmpfs rw,size=5120k
26 17 0:23 / /sys/fs/cgroup ro,nosuid,nodev,noexec shared:9 - tmpfs tmpfs ro,mode=755
27 26 0:24 / /sys/fs/cgroup/systemd rw,nosuid,nodev,noexec,relatime shared:10 - cgroup cgroup rw,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd
28 17 0:25 / /sys/fs/pstore rw,nosuid,nodev,noexec,relatime shared:11 - pstore pstore rw
29 26 0:26 / /sys/fs/cgroup/pids rw,nosuid,nodev,noexec,relatime shared:13 - cgroup cgroup rw,pids
30 26 0:27 / /sys/fs/cgroup/net_cls,net_prio rw,nosuid,nodev,noexec,relatime shared:14 - cgroup cgroup rw,net_cls,net_prio
31 26 0:28 / /sys/fs/cgroup/blkio rw,nosuid,nodev,noexec,relatime shared:15 - cgroup cgroup rw,blkio
32 26 0:29 / /sys/fs/cgroup/cpu,cpuacct rw,nosuid,nodev,noexec,relatime shared:16 - cgroup cgroup rw,cpu,cpuacct
33 26 0:30 / /sys/fs/cgroup/cpuset rw,nosuid,nodev,noexec,relatime shared:17 - cgroup cgroup rw,cpuset
34 26 0:31 / /sys/fs/cgroup/freezer rw,nosuid,nodev,noexec,relatime shared:18 - cgroup cgroup rw,freezer
35 26 0:32 / /sys/fs/cgroup/perf_event rw,nosuid,nodev,noexec,relatime shared:19 - cgroup cgroup rw,perf_event
36 26 0:33 / /sys/fs/cgroup/devices rw,nosuid,nodev,noexec,relatime shared:20 - cgroup cgroup rw,devices
37 26 0:34 / /sys/fs/cgroup/memory rw,nosuid,nodev,noexec,relatime shared:21 - cgroup cgroup rw,memory
38 17 0:7 / /sys/kernel/debug rw,relatime shared:22 - debugfs debugfs rw
39 19 0:35 / /dev/hugepages rw,relatime shared:23 - hugetlbfs hugetlbfs rw
40 18 0:36 / /proc/sys/fs/binfmt_misc rw,relatime shared:24 - autofs systemd-1 rw,fd=36,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=19762
41 21 0:37 / /run/rpc_pipefs rw,relatime shared:25 - rpc_pipefs sunrpc rw
42 19 0:15 / /dev/mqueue rw,relatime shared:26 - mqueue mqueue rw
97 22 7:0 / /snap/lxd/5408 ro,nodev,relatime shared:27 - squashfs /dev/loop0 ro
70 22 7:1 / /snap/core/3748 rw,relatime shared:28 - squashfs /dev/loop1 ro
72 22 0:39 / /root/cloud rw shared:29 - zfs tank/datastore/cloud rw,xattr,noacl
74 22 0:40 / /tank rw shared:30 - zfs tank rw,xattr,noacl
76 74 0:41 / /tank/datastore rw shared:31 - zfs tank/datastore rw,xattr,noacl
78 74 0:42 / /tank/images rw shared:32 - zfs tank/images rw,xattr,noacl
80 74 0:43 / /tank/kvm rw shared:33 - zfs tank/kvm rw,xattr,noacl
82 80 0:44 / /tank/kvm/disks rw shared:34 - zfs tank/kvm/disks rw,xattr,noacl
84 74 0:45 / /tank/misc rw shared:35 - zfs tank/misc rw,xattr,noacl
136 21 0:19 /snapd/ns /run/snapd/ns rw,nosuid,noexec,relatime - tmpfs tmpfs rw,size=3284768k,mode=755
214 17 0:52 / /sys/fs/fuse/connections rw,relatime shared:84 - fusectl fusectl rw
342 40 0:60 / /proc/sys/fs/binfmt_misc rw,relatime shared:87 - binfmt_misc binfmt_misc rw
232 22 7:2 / /snap/core/3887 ro,nodev,relatime shared:187 - squashfs /dev/loop2 ro
277 22 7:3 / /snap/lxd/5841 ro,nodev,relatime shared:191 - squashfs /dev/loop3 ro
322 21 0:55 / /run/user/0 rw,nosuid,nodev,relatime shared:189 - tmpfs tmpfs rw,size=3284764k,mode=700
333 22 7:4 / /snap/core/4017 ro,nodev,relatime shared:193 - squashfs /dev/loop4 ro
391 136 0:3 mnt:[4026532866] /run/snapd/ns/lxd.mnt rw - nsfs nsfs rw
root@amaterasu:~# cat /proc/self/cgroup
10:memory:/user.slice/user-0.slice/session-8080.scope
9:devices:/user.slice/user-0.slice/session-8080.scope
8:perf_event:/
7:freezer:/
6:cpuset:/
5:cpu,cpuacct:/user.slice/user-0.slice/session-8080.scope
4:blkio:/user.slice/user-0.slice/session-8080.scope
3:net_cls,net_prio:/
2:pids:/user.slice/user-0.slice/session-8080.scope
1:name=systemd:/user.slice/user-0.slice/session-8080.scope
0::/
```

From the Scaleway VM (#&#x200B;3):

```
root@scw-ed6eec:~# cat /proc/self/mountinfo
16 21 0:16 / /sys rw,nosuid,nodev,noexec,relatime shared:7 - sysfs sysfs rw
17 21 0:4 / /proc rw,nosuid,nodev,noexec,relatime shared:12 - proc proc rw
18 21 0:6 / /dev rw,nosuid,relatime shared:2 - devtmpfs udev rw,size=1015324k,nr_inodes=253831,mode=755
19 18 0:17 / /dev/pts rw,nosuid,noexec,relatime shared:3 - devpts devpts rw,gid=5,mode=620,ptmxmode=000
20 21 0:18 / /run rw,nosuid,noexec,relatime shared:5 - tmpfs tmpfs rw,size=205244k,mode=755
21 0 254:0 / / rw,relatime shared:1 - ext4 /dev/vda rw,data=ordered
22 16 0:15 / /sys/kernel/security rw,nosuid,nodev,noexec,relatime shared:8 - securityfs securityfs rw
23 18 0:19 / /dev/shm rw,nosuid,nodev shared:4 - tmpfs tmpfs rw
24 20 0:20 / /run/lock rw,nosuid,nodev,noexec,relatime shared:6 - tmpfs tmpfs rw,size=5120k
25 16 0:21 / /sys/fs/cgroup ro,nosuid,nodev,noexec shared:9 - tmpfs tmpfs ro,mode=755
26 25 0:22 / /sys/fs/cgroup/systemd rw,nosuid,nodev,noexec,relatime shared:10 - cgroup cgroup rw,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd
27 16 0:23 / /sys/fs/pstore rw,nosuid,nodev,noexec,relatime shared:11 - pstore pstore rw
28 25 0:24 / /sys/fs/cgroup/perf_event rw,nosuid,nodev,noexec,relatime shared:13 - cgroup cgroup rw,perf_event
29 25 0:25 / /sys/fs/cgroup/devices rw,nosuid,nodev,noexec,relatime shared:14 - cgroup cgroup rw,devices
30 25 0:26 / /sys/fs/cgroup/pids rw,nosuid,nodev,noexec,relatime shared:15 - cgroup cgroup rw,pids
31 25 0:27 / /sys/fs/cgroup/cpu,cpuacct rw,nosuid,nodev,noexec,relatime shared:16 - cgroup cgroup rw,cpu,cpuacct
32 25 0:28 / /sys/fs/cgroup/freezer rw,nosuid,nodev,noexec,relatime shared:17 - cgroup cgroup rw,freezer
33 25 0:29 / /sys/fs/cgroup/cpuset rw,nosuid,nodev,noexec,relatime shared:18 - cgroup cgroup rw,cpuset
34 25 0:30 / /sys/fs/cgroup/net_cls,net_prio rw,nosuid,nodev,noexec,relatime shared:19 - cgroup cgroup rw,net_cls,net_prio
35 25 0:31 / /sys/fs/cgroup/memory rw,nosuid,nodev,noexec,relatime shared:20 - cgroup cgroup rw,memory
36 25 0:32 / /sys/fs/cgroup/blkio rw,nosuid,nodev,noexec,relatime shared:21 - cgroup cgroup rw,blkio
37 18 0:33 / /dev/hugepages rw,relatime shared:22 - hugetlbfs hugetlbfs rw
38 18 0:14 / /dev/mqueue rw,relatime shared:23 - mqueue mqueue rw
39 17 0:34 / /proc/sys/fs/binfmt_misc rw,relatime shared:24 - autofs systemd-1 rw,fd=35,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=9633
40 16 0:7 / /sys/kernel/debug rw,relatime shared:25 - debugfs debugfs rw
67 21 7:0 / /snap/core/3748 rw,relatime shared:26 - squashfs /dev/loop0 ro
69 21 7:1 / /snap/lxd/5785 ro,nodev,relatime shared:27 - squashfs /dev/loop1 ro
71 21 7:2 / /snap/lxd/5833 ro,nodev,relatime shared:28 - squashfs /dev/loop2 ro
73 21 7:3 / /snap/core/4017 ro,nodev,relatime shared:29 - squashfs /dev/loop3 ro
75 21 7:4 / /snap/core/3887 ro,nodev,relatime shared:30 - squashfs /dev/loop4 ro
77 21 7:5 / /snap/lxd/5841 ro,nodev,relatime shared:31 - squashfs /dev/loop5 ro
123 20 0:18 /snapd/ns /run/snapd/ns rw,nosuid,noexec,relatime - tmpfs tmpfs rw,size=205244k,mode=755
151 123 0:3 mnt:[4026532197] /run/snapd/ns/lxd.mnt rw - nsfs nsfs rw
200 16 0:41 / /sys/fs/fuse/connections rw,relatime shared:76 - fusectl fusectl rw
219 20 0:44 / /run/user/0 rw,nosuid,nodev,relatime shared:79 - tmpfs tmpfs rw,size=205240k,mode=700
333 39 0:50 / /proc/sys/fs/binfmt_misc rw,relatime shared:81 - binfmt_misc binfmt_misc rw
root@scw-ed6eec:~# cat /proc/self/cgroup
10:blkio:/user.slice/user-0.slice/session-1.scope
9:memory:/user.slice/user-0.slice/session-1.scope
8:net_cls,net_prio:/
7:cpuset:/
6:freezer:/
5:cpu,cpuacct:/user.slice/user-0.slice/session-1.scope
4:pids:/user.slice/user-0.slice/session-1.scope
3:devices:/user.slice/user-0.slice/session-1.scope
2:perf_event:/
1:name=systemd:/user.slice/user-0.slice/session-1.scope
0::/
```

**Comment by stgraber** [comment] 2018-02-19 23:29
Ok, so that shows that the unified hierarchy is setup by the kernel (that's the "0" controller above) but isn't mounted anywhere (would be /sys/fs/cgroup/unified).

systemd in the container must detect cgroup2 either by looking at /proc/self/cgroup or /proc/filesystems and so attempts to use it, which kinda works in that the kernel will let it mount it, but then blows up on permission errors...
