### ISSUE TITLE
Requirements for the client part of LXD to control remotes

### ISSUE THREAD

**Issue by techtonik** [lxc/lxd#762] opened 2015-06-13 23:42 UTC
Hi,

Can I control remote container from a RPi or Mac OS or even Windows with Go installed? Is that feasible with current client/server architecture of LXD?

**Comment by tych0** [comment] 2015-06-14 01:01
On Sat, Jun 13, 2015 at 04:42:39PM -0700, anatoly techtonik wrote:
> Hi,
> 
> Can I control remote container from a RPi or Mac OS or even Windows with Go installed? Is that feasible with current client/server architecture of LXD?

Yes, I did some work a while ago to make sure that the `lxc`
executable didn't link against anything unreasonable (like liblxc), so
this should be possible. If not, please file a bug, because we do want
`lxc` to have mostly reasonable dependencies.

**Comment by techtonik** [comment] 2015-06-14 03:58
@tych0 - #761 is that bug. There is no `libintl` + `GCC` on my non-Linux system, so trying to run LXD from source fails.

**Comment by stgraber** [comment] 2015-06-15 18:06
Should be resolved with the branch that got merged earlier.

**Closed by stgraber** 2015-06-15 18:06 UTC

**Comment by techtonik** [comment] 2015-06-16 15:04
The `go get` still fails without `gcc`:
```
...
golang.org/x/crypto/ssh/terminal
# github.com/mattn/go-sqlite3
exec: "gcc": executable file not found in %PATH%
gopkg.in/yaml.v2
```

**Comment by stgraber** [comment] 2015-06-16 15:09
Right, you need gcc itself to compile the embedded C code, but not gccgo.

**Comment by stgraber** [comment] 2015-06-16 15:10
There's no real way around this, Go by design allows embedding C code and when doing so, a C compiler is required. Go uses gcc which is available on pretty much all OS and architectures, though it may also support other C compilers (and our C code isn't using gcc-isms).

**Comment by techtonik** [comment] 2015-06-17 12:36
Is it possible to install "compiled stuff" for use with Go instead of rebuilding everything from source? Python allows to pack embedded code into wheels and distribute them through PyPI just for those cases.

**Comment by stgraber** [comment] 2015-06-17 16:03
Note that in python, "compiled" isn't actually compiled. pyc is an intermediary byte-code which is still arch and OS neutral. It's basically the interpreter internal representation of the parsed .py file.

To compare to the python world, what you're asking us to do is find a way to ship C extension modules in a way that work on all operating systems and architectures and that, even in python isn't possible :)

**Comment by techtonik** [comment] 2015-06-18 07:42
I really meant `compiled`. Into pyd. Take a look at https://pypi.python.org/pypi/libsass distribution for example. It ships extensions modules in wheels that work for every platform. It is also possible to stuff all compiled modules into one wheel and choose the one for the platform dynamically.
