### ISSUE TITLE
Containers stopped getting an ip address

### ISSUE THREAD

**Issue by killua-eu** [lxc/lxd#8906] opened 2021-06-17 09:18 UTC
# Required information

 * Distribution: ubuntu (on azure)
 * Distribution version: "20.04.2 LTS (Focal Fossa)"
 * The output of "lxc info" or if that fails:

```
root@industra1:/home/killua# lxc info
config:
  cluster.https_address: 10.0.1.11:8443
  core.https_address: 10.0.1.11:8443
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- snapshot_schedule_aliases
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
- firewall_driver
- projects_limits
- container_syscall_intercept_hugetlbfs
- limits_hugepages
- container_nic_routed_gateway
- projects_restrictions
- custom_volume_snapshot_expiry
- volume_snapshot_scheduling
- trust_ca_certificates
- snapshot_disk_usage
- clustering_edit_roles
- container_nic_routed_host_address
- container_nic_ipvlan_gateway
- resources_usb_pci
- resources_cpu_threads_numa
- resources_cpu_core_die
- api_os
- container_nic_routed_host_table
- container_nic_ipvlan_host_table
- container_nic_ipvlan_mode
- resources_system
- images_push_relay
- network_dns_search
- container_nic_routed_limits
- instance_nic_bridged_vlan
- network_state_bond_bridge
- usedby_consistency
- custom_block_volumes
- clustering_failure_domains
- resources_gpu_mdev
- console_vga_type
- projects_limits_disk
- network_type_macvlan
- network_type_sriov
- container_syscall_intercept_bpf_devices
- network_type_ovn
- projects_networks
- projects_networks_restricted_uplinks
- custom_volume_backup
- backup_override_name
- storage_rsync_compression
- network_type_physical
- network_ovn_external_subnets
- network_ovn_nat
- network_ovn_external_routes_remove
- tpm_device_type
- storage_zfs_clone_copy_rebase
- gpu_mdev
- resources_pci_iommu
- resources_network_usb
- resources_disk_address
- network_physical_ovn_ingress_mode
- network_ovn_dhcp
- network_physical_routes_anycast
- projects_limits_instances
- network_state_vlan
- instance_nic_bridged_port_isolation
- instance_bulk_state_change
- network_gvrp
- instance_pool_move
- gpu_sriov
- pci_device_type
- storage_volume_state
- network_acl
- migration_stateful
- disk_state_quota
- storage_ceph_features
- projects_compression
- projects_images_remote_cache_expiry
- certificate_project
- network_ovn_acl
- projects_images_auto_update
- projects_restricted_cluster_target
- images_default_architecture
- network_ovn_acl_defaults
- gpu_mig
- project_usage
- network_bridge_acl
- warnings
- projects_restricted_backups_and_snapshots
- clustering_join_token
- clustering_description
- server_trusted_proxy
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 10.0.1.11:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    ...
    -----END CERTIFICATE-----
  certificate_fingerprint: c11f.....ee6e90
  driver: qemu | lxc
  driver_version: 5.2.0 | 4.0.9
  firewall: nftables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.8.0-1033-azure
  lxc_features:
    cgroup2: "true"
    devpts_fd: "true"
    idmapped_mounts_v2: "false"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Ubuntu
  os_version: "20.04"
  project: default
  server: lxd
  server_clustered: true
  server_name: az01
  server_pid: 26903
  server_version: "4.15"
  storage: zfs | dir
  storage_version: 0.8.4-1ubuntu11.2 | 1
```

# Issue description

Logged into the host to see all containers without an IP

```
# lxc list
+----------------+---------+------+------+-----------+-----------+----------+
|      NAME      |  STATE  | IPV4 | IPV6 |   TYPE    | SNAPSHOTS | LOCATION |
+----------------+---------+------+------+-----------+-----------+----------+
| az01-crawl     | RUNNING |      |      | CONTAINER | 0         | az01     |
+----------------+---------+------+------+-----------+-----------+----------+
| az01-crawl2    | RUNNING |      |      | CONTAINER | 1         | az01     |
+----------------+---------+------+------+-----------+-----------+----------+
| az01-gitea     | RUNNING |      |      | CONTAINER | 2         | az01     |
+----------------+---------+------+------+-----------+-----------+----------+
| az01-lamp      | RUNNING |      |      | CONTAINER | 0         | az01     |
+----------------+---------+------+------+-----------+-----------+----------+
| az01-mailtrain | RUNNING |      |      | CONTAINER | 2         | az01     |
+----------------+---------+------+------+-----------+-----------+----------+
| az01-nodered   | RUNNING |      |      | CONTAINER | 1         | az01     |
+----------------+---------+------+------+-----------+-----------+----------+
| az01-proxy     | RUNNING |      |      | CONTAINER | 0         | az01     |
+----------------+---------+------+------+-----------+-----------+----------+
| az01-stackedit | RUNNING |      |      | CONTAINER | 0         | az01     |
+----------------+---------+------+------+-----------+-----------+----------+
| az01-wekan     | RUNNING |      |      | CONTAINER | 0         | az01     |
+----------------+---------+------+------+-----------+-----------+----------+
```

restarted the VM, didn't help. The dmesg has

```
[  420.687052] audit: type=1400 audit(1623920571.038:181): apparmor="STATUS" operation="profile_load" label="lxd-az01-nodered_</var/snap/lxd/common/lxd>//&:lxd-az01-nodered_<var-snap-lxd-common-lxd>:unconfined" name="lxc-container-default" pid=29386 comm="apparmor_parser"
[  420.687056] audit: type=1400 audit(1623920571.038:182): apparmor="STATUS" operation="profile_load" label="lxd-az01-nodered_</var/snap/lxd/common/lxd>//&:lxd-az01-nodered_<var-snap-lxd-common-lxd>:unconfined" name="lxc-container-default-cgns" pid=29386 comm="apparmor_parser"
[  420.687059] audit: type=1400 audit(1623920571.038:183): apparmor="STATUS" operation="profile_load" label="lxd-az01-nodered_</var/snap/lxd/common/lxd>//&:lxd-az01-nodered_<var-snap-lxd-common-lxd>:unconfined" name="lxc-container-default-with-mounting" pid=29386 comm="apparmor_parser"
[  420.687062] audit: type=1400 audit(1623920571.038:184): apparmor="STATUS" operation="profile_load" label="lxd-az01-nodered_</var/snap/lxd/common/lxd>//&:lxd-az01-nodered_<var-snap-lxd-common-lxd>:unconfined" name="lxc-container-default-with-nesting" pid=29386 comm="apparmor_parser"
[  420.691451] audit: type=1400 audit(1623920571.042:185): apparmor="STATUS" operation="profile_load" label="lxd-az01-nodered_</var/snap/lxd/common/lxd>//&:lxd-az01-nodered_<var-snap-lxd-common-lxd>:unconfined" name="/usr/bin/lxc-start" pid=29393 comm="apparmor_parser"
[  420.698307] audit: type=1400 audit(1623920571.046:186): apparmor="STATUS" operation="profile_load" label="lxd-az01-nodered_</var/snap/lxd/common/lxd>//&:lxd-az01-nodered_<var-snap-lxd-common-lxd>:unconfined" name="/usr/bin/man" pid=29394 comm="apparmor_parser"
[  420.698311] audit: type=1400 audit(1623920571.046:187): apparmor="STATUS" operation="profile_load" label="lxd-az01-nodered_</var/snap/lxd/common/lxd>//&:lxd-az01-nodered_<var-snap-lxd-common-lxd>:unconfined" name="man_filter" pid=29394 comm="apparmor_parser"
[  420.698313] audit: type=1400 audit(1623920571.046:188): apparmor="STATUS" operation="profile_load" label="lxd-az01-nodered_</var/snap/lxd/common/lxd>//&:lxd-az01-nodered_<var-snap-lxd-common-lxd>:unconfined" name="man_groff" pid=29394 comm="apparmor_parser"
[  420.703455] audit: type=1400 audit(1623920571.054:189): apparmor="STATUS" operation="profile_load" label="lxd-az01-nodered_</var/snap/lxd/common/lxd>//&:lxd-az01-nodered_<var-snap-lxd-common-lxd>:unconfined" name="/sbin/dhclient" pid=29387 comm="apparmor_parser"
[  420.703459] audit: type=1400 audit(1623920571.054:190): apparmor="STATUS" operation="profile_load" label="lxd-az01-nodered_</var/snap/lxd/common/lxd>//&:lxd-az01-nodered_<var-snap-lxd-common-lxd>:unconfined" name="/usr/lib/NetworkManager/nm-dhcp-client.action" pid=29387 comm="apparmor_parser"
[  423.049538] lxdfan0: port 10(veth6e09503e) entered blocking state
[  423.049542] lxdfan0: port 10(veth6e09503e) entered disabled state
[  423.054438] device veth6e09503e entered promiscuous mode
[  423.303105] physvBNErD: renamed from vethf16af303
[  423.324170] eth0: renamed from physvBNErD
[  423.342395] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[  423.342439] lxdfan0: port 10(veth6e09503e) entered blocking state
[  423.342442] lxdfan0: port 10(veth6e09503e) entered forwarding state
[  423.501267] lxdfan0: port 11(vethf18c5397) entered blocking state
[  423.501270] lxdfan0: port 11(vethf18c5397) entered disabled state
[  423.501358] device vethf18c5397 entered promiscuous mode
[  423.501398] lxdfan0: port 11(vethf18c5397) entered blocking state
[  423.501400] lxdfan0: port 11(vethf18c5397) entered forwarding state
[  423.799087] physfWN9bv: renamed from veth88777c8a
[  423.818494] eth0: renamed from physfWN9bv
[  444.974981] kauditd_printk_skb: 45 callbacks suppressed
[  444.975001] audit: type=1400 audit(1623920595.326:236): apparmor="DENIED" operation="open" namespace="root//lxd-az01-wekan_<var-snap-lxd-common-lxd>" profile="snap.wekan.mongodb" name="/sys/block/" pid=32332 comm="mongod" requested_mask="r" denied_mask="r" fsuid=1000000 ouid=0
```

**Comment by Deradon** [comment] 2021-06-17 11:02
Can confirm. Suddenly containers stopped getting IPs.
`lxd` installed on host via snap.

Working Revision: 20684
Broken Revision: 20760

## Workaround: `snap revert lxd`

After reverting `lxd` via snap to the previous Revision containers getting IPs again.

```shell
$ lxc list | grep gitlab
| gitlab            | RUNNING |      |      | CONTAINER | 0         |

$ snap list | grep lxd
lxd     4.15      20760  latest/stable  canonical*  -

$ snap revert lxd
lxd reverted to 4.15

$ lxc restart gitlab
$ lxc list | grep gitlab
| gitlab            | RUNNING | 10.196.204.97 (eth0) | fd42:3e13:2958:7d58:216:3eff:fe7e:86d4 (eth0) | CONTAINER | 0         |

$ snap list | grep lxd
lxd     4.15      20684  latest/stable  canonical*  -
```

**Comment by tomponline** [comment] 2021-06-17 11:05
Can you check https://github.com/lxc/lxd/issues/8905#issuecomment-863126071 and see if it helps.

**Comment by tomponline** [comment] 2021-06-17 11:06
Can you show output of `lxc network show <network>` (e.g. `lxc network show lxdbr0`)

**Comment by killua-eu** [comment] 2021-06-17 15:46
```
lxc network show lxdfan0
config:
  bridge.mode: fan
  fan.underlay_subnet: 10.0.1.0/24
  ipv4.nat: "true"
  raw.dnsmasq: |
    auth-zone=lxd
    dns-loop-detect
description: ""
name: lxdfan0
type: bridge
used_by:
- /1.0/instances/az01-crawl
- /1.0/instances/az01-crawl2
- /1.0/instances/az01-gitea
- /1.0/instances/az01-lamp
- /1.0/instances/az01-mailtrain
- /1.0/instances/az01-nodered
- /1.0/instances/az01-proxy
- /1.0/instances/az01-stackedit
- /1.0/instances/az01-wekan
- /1.0/profiles/default
managed: true
status: Created
locations:
- az01
```

**Comment by tomponline** [comment] 2021-06-17 15:49
Duplicate of https://github.com/lxc/lxd/issues/8905

You need to remove "auth-zone" from `raw.dnsmasq`.

The error is now logged since https://github.com/lxc/lxd/pull/8914

**Closed by tomponline** 2021-06-17 15:49 UTC
Labels: Bug

**Comment by killua-eu** [comment] 2021-06-17 15:55
i unsetted the whole raw.dnesmaq, works. So, how do I ensure now, that I get name resolution working for containername.lxd from within containers? Without the setting, I sometinmes got .lxd and sometimes .local (if I remember correctly) in previous (2.x) versions of lxd.

**Comment by tomponline** [comment] 2021-06-17 15:56
As the other case I linked to say, the actual dnsmasq error from core20 is:

```
dnsmasq: --auth-server required when an auth zone is defined.
```

So if you're going to use the `auth-zone` setting you'll also need to provide a `auth-server` setting.

**Comment by killua-eu** [comment] 2021-06-17 16:14
I see! So in my case,
- dns-loop-detect
- auth-server=<???>,lxdfan0
- auth-zone=lxd

what should be the auth-server in my case? localhost? or the lxdfan0 ip? something else? DNS is scary and this is a prod environment that got hit, so I'm hoping for some basic guidance before breaking things.

**Comment by tomponline** [comment] 2021-06-17 16:17
@killua-eu I'm not sure, what was the reason you enable `auth-zone` in the first place, the "Without the setting, I sometinmes got .lxd and sometimes .local (if I remember correctly) in previous (2.x) versions of lxd." seems like it could be of date now, so might be worth trying without it.

**Comment by tomponline** [comment] 2021-06-17 16:19
@killua-eu that would also be better from a stability point of view, as the settings in `raw.dnsmasq` are unknown and don't get tested.

**Comment by killua-eu** [comment] 2021-06-17 16:28
Ok, last question :) Is the name-resolution tested somehow? Do the current versions provide a stable mechanism that will allow host->container and container->container name resolution?

**Comment by tomponline** [comment] 2021-06-17 16:30
@killua-eu container->container name resolution is provided and tested as standard.

For host->container, we have recently updated our docs with such a solution using systemd-networkd on the host, see https://linuxcontainers.org/lxd/docs/master/networks##integration-with-systemd-resolved
