### ISSUE TITLE
Copy/move custom volumes between projects

### ISSUE THREAD

**Issue by fling-** [lxc/lxd#7341] opened 2020-05-10 04:38 UTC
`lxc storage volume` subcommands are missing --target-project option.
It is possible to move containers between projects but custom volumes are being left behind.

**Comment by stgraber** [comment] 2020-05-10 16:17
Yeah, this isn't currently possible but is something we should eventually add.

**Comment by presztak** [comment] 2021-06-02 21:45
@stgraber this issue looks interesting but I think this is duplicate of  #8236. Am i right?

**Comment by stgraber** [comment] 2021-06-02 22:58
Indeed, let me close this one and clear the other as the assignee isn't responding.

**Closed by stgraber** 2021-06-02 22:58 UTC
Labels: API, Documentation, Feature
