### ISSUE TITLE
Create failed due to datasetd dependent on the image snapshot

### ISSUE THREAD

**Issue by Saviq** [lxc/lxd#8081] opened 2020-10-27 07:50 UTC
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.10
 * [The output of "lxc info"](https://github.com/lxc/lxd/files/5443624/lxc_info.txt)

# Issue description

Instances fail to launch when a `zfs destroy` fails. This is likely some corruption in my LXD+ZFS's state, but maybe there is something that can be done about it?

```plain
"Create instance from image: Failed to run: zfs destroy rpool/lxd/images/2f456602cd86a6dc4d50102f028729421fece7e68f7c8aec6d8af5d9bbc681bf@readonly: cannot destroy 'rpool/lxd/images/2f456602cd86a6dc4d50102f028729421fece7e68f7c8aec6d8af5d9bbc681bf@readonly': snapshot has dependent clones\nuse '-R' to destroy the following datasets:\nrpool/lxd/virtual-machines/multipass_dazzling-hare\nrpool/lxd/virtual-machines/multipass_admirable-tick",
```

I have, since, resolved this by removing those datasets and even recreating them does not result in the same problem, so I couldn't really say what's gone wrong. Maybe what I'm attaching here will shed a light.

# Information to attach

 - [x] [journald.log](https://github.com/lxc/lxd/files/5443680/journal.log)

**Comment by stgraber** [comment] 2020-10-27 12:39
Did those two dependent VMs actually exist in LXD?

If so, destroy shouldn't have been called, instead LXD should have performed a rename.

The fact that this is happening during a new instance creation is odd too.

**Comment by Saviq** [comment] 2020-10-28 08:10
> Did those two dependent VMs actually exist in LXD?

Not at the time of the error.

> If so, destroy shouldn't have been called, instead LXD should have performed a rename.
> 
> The fact that this is happening during a new instance creation is odd too.

Indeed…

**Comment by stgraber** [comment] 2020-10-28 16:49
Ok, so the real issue would be why we had leftover datasets in this case more than the error afterwards.

I looked over that logic yesterday and we do re-create the dataset (and hit the codepath above) if we need to create a VM with a root disk smaller than what was done the last time around. The logic will perform a rename if we know it's still in use, though in your case, this failed due to those leftover datasets.

The one way I managed to reproduce something similar was by creating a dozen VMs in parallel, randomly varying their sizes. This eventually managed to race the storage logic and cause similar breakage.

I've pushed a fix last night which does locking when a new image decompress operation is needed, so that took care of the case I could reproduce.


If you ever find a way to reproduce those leftover datasets, do let us know as that's really the core of the issue for you and it'd be good to sort it out!

**Closed by stgraber** 2020-10-28 16:49 UTC
Labels: Incomplete
