### ISSUE TITLE
unused config keys are silently ignored

### ISSUE THREAD

**Issue by tych0** [lxc/lxd#2179] opened 2016-07-05 20:52 UTC
If I try to save something like:

```
name: unpriv
profiles:
- default
config:
  volatile.base_image: f452cda3bccb2903e56d53e402b9d35334b4276783d098a879be5d74b04e62e2
  volatile.eth0.hwaddr: 00:16:3e:1e:8a:97
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
devices:
  root:
    path: /
    type: disk
ephemeral: false
not-a-valid-config-key: foo
```

it just eats `not-a-valid-config-key`. It would be nice to give an error here.

**Comment by stgraber** [comment] 2016-07-05 21:21
It's not so much an unused config key as an unused json key (one that doesn't match a field in the struct).

@howbazaar was telling me that Juju is working on fixing exactly this issue with a stricter json.Decode that basically returns an error for any field that's provided by the user but doesn't exist in the target struct.

**Comment by stgraber** [comment] 2017-07-03 02:46
So with the way LXD currently works, I'm not sure that we can/should fix this.

The problem is that we rely somewhat on it ignoring keys that it doesn't know about when a newer client talks to an older LXD. We don't allow the user to attempt to use features that aren't supported by the target LXD but our client library will always send the full API struct, including those fields that aren't known by the remote.

This is all because we're mapping from Go structs to JSON back to Go structs. The first step means we get extra fields in our JSON and the last means those get ignored. If we fix the last step, we'll also need to make significant changes in our client to selectively drop JSON fields based on API extensions, massively complicating the codebase.

As as result, I'm closing this issue. We've not seen it being a big issue in practice as we internally now always use shared/api which prevents such typo type issues from being possible and other users haven't reported problems to us. If this validation would benefit some users, we could possibly add it under a HTTP header (strict mode kind of thing) which API clients could then opt into.

If there's interest for that compromise, please comment in this issue and we'll consider re-opening it.

**Closed by stgraber** 2017-07-03 02:46 UTC
Labels: Feature
