### ISSUE TITLE
Container move with CRIU fails with Btrfs

### ISSUE THREAD

**Issue by MarkGavalda** [lxc/lxd#2522] opened 2016-10-18 15:43 UTC
When trying to move a container without snapshots, it fails:
error: Error transferring container data: exit status 1
on the other machine:
```
Oct 18 15:37:42 lxd-21 lxd[5435]: t=2016-10-18T15:37:42+0000 lvl=eror msg="problem with btrfs receive" output="ERROR: cannot find parent subvolume\n"
Oct 18 15:37:42 lxd-21 lxd[5435]: t=2016-10-18T15:37:42+0000 lvl=eror msg="Error during migration sink" err="exit status 1"
```

S/w version on both machines:
```
CRIU: Version: 2.7 GitID: v2.7 (built from git repo today)
  driver: lxc
  driverversion: 2.0.5
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.8.0-22-generic
  server: lxd
  serverpid: 5447
  serverversion: 2.4.1
  storage: btrfs
  storageversion: 4.8.1
```

**Comment by stgraber** [comment] 2016-10-18 16:14
Both hosts are on btrfs? Are they both the same Ubuntu version too?

**Comment by MarkGavalda** [comment] 2016-10-18 16:17
@stgraber yes and yes.

**Comment by stgraber** [comment] 2016-10-18 16:54
Does the same work when the container isn't running?

**Comment by stgraber** [comment] 2016-10-18 16:54
CRIU has had a bunch of issues with btrfs in the past. I'm not sure if 2.7 fixes them all.

**Comment by stgraber** [comment] 2016-10-18 16:54
@brauner

**Comment by brauner** [comment] 2016-10-18 16:59
Can you please post or better append all of the criu related log and `lxd.log` from both hosts?

**Comment by stgraber** [comment] 2016-10-18 17:05
Also please try to run "criu check" on both hosts. In the past that'd just segfault, causing the error you're seeing.

**Comment by MarkGavalda** [comment] 2016-10-18 17:37
@stgraber when I first compile criu from the git repo on a brand spanking new machine (Ubuntu 16.10) `criu check` works fine. I have it in my auto-install script to make sure it works.
However if I try to run it now (after a Btrfs-based LXD was initiated on the machine) it's like you said: Segmentation fault (core dumped).

**Comment by stgraber** [comment] 2016-10-18 17:45
Right, that's because criu crashes when you have a unix socket on btrfs which LXD does when it starts.

Alright, so the issue is still CRIU being broken on systems using btrfs. Once CRIU is fixed things should work just fine (as they do on zfs).

I'm going to close this issue as there's unfortunately nothing we can really do about it in LXD itself.
@brauner was looking into the CRIU bug before and sent a patch upstream to try to make things work again, though clearly that wasn't included in 2.7 or wasn't sufficient.

We're tracking this issue here: https://bugs.launchpad.net/ubuntu/+source/criu/+bug/1620805

**Closed by stgraber** 2016-10-18 17:45 UTC

**Comment by MarkGavalda** [comment] 2016-10-18 17:54
I don't think it's the same problem though. Obviously `criu check` not working is not optimal, however this is a separate error.
@brauner here are the relevant log entries from both machines:
sender:
```
t=2016-10-18T15:37:29+0000 lvl=info msg="Migrating container" used=2016-10-18T15:17:53+0000 statedir=/tmp/lxd_checkpoint_337231506 actionscript=true stop=true name=MiI-marktest1018 created=2016-10-17T10:53:59+0000 ephemeral=false
t=2016-10-18T15:37:43+0000 lvl=eror msg="Error collecting checkpoint log file" err="open /tmp/lxd_checkpoint_337231506/dump.log: no such file or directory"
t=2016-10-18T15:37:43+0000 lvl=info msg="Migrated container" actionscript=true stop=true name=MiI-marktest1018 created=2016-10-17T10:53:59+0000 ephemeral=false used=2016-10-18T15:17:53+0000 statedir=/tmp/lxd_checkpoint_337231506
```

receiver:
```
t=2016-10-18T15:37:42+0000 lvl=eror msg="problem with btrfs receive" output="ERROR: cannot find parent subvolume\n"
t=2016-10-18T15:37:42+0000 lvl=eror msg="Error during migration sink" err="exit status 1"
t=2016-10-18T15:37:42+0000 lvl=info msg="Deleting container" name=MiI-marktest1018 created=2016-10-18T15:36:58+0000 ephemeral=false used=1970-01-01T00:00:00+0000
t=2016-10-18T15:37:42+0000 lvl=info msg="Deleted container" name=MiI-marktest1018 created=2016-10-18T15:36:58+0000 ephemeral=false used=1970-01-01T00:00:00+0000
```

**Comment by MarkGavalda** [comment] 2016-10-18 18:02
If there are snapshots involved, the error is the following:
```
error: Error transferring container data: migration dump failed
(00.162795) Error (criu/sk-netlink.c:73): The socket has data to read
(00.162806) Error (criu/cr-dump.c:1316): Dump files (pid: 21516) failed with -1
(00.201130) Error (criu/cr-dump.c:1636): Dumping FAILED.
```
Should I move this issue to criu's issue tracker?

**Comment by brauner** [comment] 2016-10-18 18:04
Can you try again, immediately after the fail. This seems like a common error we observe. @tych0

**Comment by MarkGavalda** [comment] 2016-10-18 18:14
Interestingly on the second try and from then on it says:
`lvl=eror msg="problem with btrfs receive" output="ERROR: cannot find parent subvolume\n"`

**Comment by stgraber** [comment] 2016-10-18 18:23
Can you check dmesg on both hosts? I'd expect criu crashing to show up in there if that's the issue.

**Comment by MarkGavalda** [comment] 2016-10-18 20:05
Nothing in dmesg about criu crashing. If I enter `criu check` then I can see the segfault in dmesg too.

This is interesting though, never seen it before:
```
[31238.213288] cgroup: new mount options do not match the existing superblock, will be ignored
```

**Comment by tych0** [comment] 2016-10-19 05:05
`(00.162795) Error (criu/sk-netlink.c:73): The socket has data to read` this is a known issue; the workaround is simply to try again.

`lvl=eror msg="problem with btrfs receive" output="ERROR: cannot find parent subvolume\n"` this seems like the/a real problem. Any chance you can run with both LXDs in debug mode to get more info?

**Comment by stgraber** [comment] 2016-10-19 12:24
That cannot find parent subvolume was what we were getting last time when CRIU crashed during live migration, wasn't btrfs related at all, it just happens to be the confusing error we send back :)

So before debugging btrfs receive, it'd be good to check if cold migration works with that setup, if it does, it's not going to be a btrfs issue.

**Comment by brauner** [comment] 2016-10-19 14:17
@tych0, Pavel was hesitant. But Adrian picked it up I thought. That's why I stopped looking.

**Comment by tych0** [comment] 2016-10-19 14:21
On Wed, Oct 19, 2016 at 07:17:30AM -0700, Christian Brauner wrote:
> @tych0, Pavel was hesitant. But Adrian picked it up I thought. That's why I stopped looking.

Ah, Pavel is the only maintainer of criu, so he's the guy who has to
take the patch :)

Tycho

**Comment by brauner** [comment] 2016-10-19 14:31
No, I meant, that Adrian was aware of the issue and started discussing/working on it I thought. :)

**Comment by tych0** [comment] 2016-10-19 14:47
On Wed, Oct 19, 2016 at 07:31:02AM -0700, Christian Brauner wrote:
> No, I meant, that Adrian was aware of the issue and started discussing/working on it I thought. :)

Oh, ok. I didn't follow the thread that closely, so maybe he did. I
haven't seen anything come by, but I haven't really been looking
either.

The only btrfs related patch I see is:
aca9b701561b182815df83124445e1947b740e49, and before that the last one
that mentions btrfs was from me; does that patch fix the bug you're
thinking of?

**Comment by MarkGavalda** [comment] 2016-10-19 15:05
> it'd be good to check if cold migration works with that setup

It does! When the container is stopped, the lxc move process goes through without issues.

**Comment by samgaw** [comment] 2016-12-01 17:49
I'm seeing the same problem on fresh install between two identical nodes:
  - Debian Stretch (4.8.7-1)
  - lxc-info --version (2.0.6)
  - criu --version (2.8)
  - LXD installed from master

Cold migrations of containers work as expected. Remote commands from one node to the other are also fine.

During a live migration, on the source node lxd errors:
```
dump failed after successful restore?: "migration dump failed\n(01.808507)
Error (criu/action-scripts.c:116): One of more action scripts failed"
```

On the receiving node, lxd errors:
```
problem with btrfs receive   output="ERROR: cannot find parent subvolume\n"
Error during migration sink  err="exit status 1"
```

Any thoughts?

**Comment by stgraber** [comment] 2016-12-01 17:55
It's the usual CRIU failure on btrfs (which raises that odd unrelated LXD error). I don't think upstream has fixed it yet or even done much looking into it.

**Comment by samgaw** [comment] 2016-12-01 21:36
Thanks @stgraber. Are there any known issues with ZFS before I rebuild the test machines?

**Comment by stgraber** [comment] 2016-12-01 21:49
Not that I'm aware of. I've always used ZFS for my live migration demos, so it's definitely one of the most reliable backends for that.
