### ISSUE TITLE
container not starting after LXD update

### ISSUE THREAD

**Issue by nlienard** [lxc/lxd#2640] opened 2016-11-24 11:55 UTC
After updating lxd, my container is not starting anymore.

    root@inxovh-hy001 (node4):~# lxc info
    apistatus: stable
    apiversion: "1.0"
    auth: trusted
    environment:
      addresses:
      - 10.0.0.4:8443
      architectures:
      - x86_64
      - i686
      driver: lxc
      driverversion: 2.0.5
      kernel: Linux
      kernelarchitecture: x86_64
      kernelversion: 4.4.0-45-generic
      server: lxd
      serverpid: 453
      serverversion: "2.6"
     storage: zfs
      storageversion: "5"
    config:
      core.https_address: 10.0.0.4:8443
      core.trust_password: true
      storage.zfs_pool_name: zdata/lxd
    public: false

here the update:

    root@inxovh-hy001 (node4):~# apt install lxd
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    The following additional packages will be installed:
      lxd-client
    The following packages will be upgraded:
      lxd lxd-client
    2 to upgrade, 0 to newly install, 0 to remove and 67 not to upgrade.
    Need to get 4,653 kB of archives.
    After this operation, 509 kB disk space will be freed.
    Do you want to continue? [Y/n] y
    Get:1 http://ppa.launchpad.net/ubuntu-lxc/stable/ubuntu xenial/main amd64 lxd amd64 2.6-    0ubuntu2~ubuntu16.04.1~ppa1 [2,725 kB]
    Get:2 http://ppa.launchpad.net/ubuntu-lxc/stable/ubuntu xenial/main amd64 lxd-client amd64 2.6-    0ubuntu2~ubuntu16.04.1~ppa1 [1,928 kB]
    Fetched 4,653 kB in 0s (14.8 MB/s)
    (Reading database ... 110824 files and directories currently installed.)
    Preparing to unpack .../lxd_2.6-0ubuntu2~ubuntu16.04.1~ppa1_amd64.deb ...
    Warning: Stopping lxd.service, but it can still be activated by:
      lxd.socket
    Unpacking lxd (2.6-0ubuntu2~ubuntu16.04.1~ppa1) over (2.5-0ubuntu1~ubuntu16.04.1~ppa1) ...
    Preparing to unpack .../lxd-client_2.6-0ubuntu2~ubuntu16.04.1~ppa1_amd64.deb ...
    Unpacking lxd-client (2.6-0ubuntu2~ubuntu16.04.1~ppa1) over (2.5-0ubuntu1~ubuntu16.04.1~ppa1) ...
    Processing triggers for man-db (2.7.5-1) ...
    Processing triggers for systemd (229-4ubuntu12) ...
    Processing triggers for ureadahead (0.100.0-19) ...
    Setting up lxd-client (2.6-0ubuntu2~ubuntu16.04.1~ppa1) ...
    Setting up lxd (2.6-0ubuntu2~ubuntu16.04.1~ppa1) ...
    insserv: Script sysprobe is broken: incomplete LSB comment.
    insserv: missing `Provides:' entry: please add.
    insserv: missing `Required-Start:' entry: please add even if empty.
    insserv: missing `Required-Stop:'  entry: please add even if empty.
    insserv: script ceph.mon-2: service ceph already provided!

Then :

    root@inxovh-hy001 (node4):~# lxc list
    +----------------+---------+--------------------------------+------+------------+-----------+
    |      NAME      |  STATE  |              IPV4              | IPV6 |    TYPE    | SNAPSHOTS |
    +----------------+---------+--------------------------------+------+------------+-----------+
    | cephA-003      | RUNNING | 192.168.10.245 (eth0)          |      | PERSISTENT | 0         |
    +----------------+---------+--------------------------------+------+------------+-----------+
    | inxovh-db003   | RUNNING | 192.168.6.203 (eth0)           |      | PERSISTENT | 0         |
    |                |         | 192.168.5.203 (eth1)           |      |            |           |
    +----------------+---------+--------------------------------+------+------------+-----------+
    | inxovh-ldap002 | RUNNING | 192.168.10.217 (eth0)          |      | PERSISTENT | 0         |
    +----------------+---------+--------------------------------+------+------------+-----------+
    | inxovh-mx001   | RUNNING | 192.168.10.236 (eth0)          |      | PERSISTENT | 0         |
    |                |         | 192.168.6.236 (eth1)           |      |            |           |
    +----------------+---------+--------------------------------+------+------------+-----------+
    | inxovh-rdc001  | STOPPED |                                |      | PERSISTENT | 0         |
    +----------------+---------+--------------------------------+------+------------+-----------+
    | inxovh-wvc001  | STOPPED |                                |      | PERSISTENT | 0         |
    +----------------+---------+--------------------------------+------+------------+-----------+
    | inxovh-xy001   | RUNNING | 192.168.10.224 (eth0)          |      | PERSISTENT | 0         |
    +----------------+---------+--------------------------------+------+------------+-----------+

Starting one container which were stoped during the update:

    root@inxovh-hy001 (node4):~# lxc start inxovh-rdc001
    error: Container is busy running a start operation
    Try `lxc info --show-log inxovh-rdc001` for more info

The error:

    root@inxovh-hy001 (node4):~# lxc info --show-log inxovh-rdc001
    Name: inxovh-rdc001
    Remote: unix:/var/lib/lxd/unix.socket
    Architecture: x86_64
    Created: 2016/10/26 15:12 UTC
    Status: Running
    Type: persistent
    Profiles: default
    Pid: 925
    Ips:
      eth0: inet    192.168.10.211  vethLPUHJ5
      eth0: inet6   fe80::216:3eff:fe39:88e6        vethLPUHJ5
      lo:   inet    127.0.0.1
      lo:   inet6   ::1
    Resources:
      Processes: 73
      Disk usage:
        root: 796.77MB
      CPU usage:
        CPU usage (in seconds): 4
      Memory usage:
        Memory (current): 214.09MB
        Memory (peak): 231.55MB
      Network usage:
        eth0:
          Bytes received: 33.62kB
          Bytes sent: 107.51kB
          Packets received: 427
          Packets sent: 215
        lo:
          Bytes received: 0 bytes
          Bytes sent: 0 bytes
          Packets received: 0
          Packets sent: 0

    Log:

                lxc 20161124124945.328 WARN     lxc_seccomp - seccomp.c:do_resolve_add_rule:265 - Seccomp: failed to resolve syscall: .
                lxc 20161124124945.328 WARN     lxc_seccomp - seccomp.c:do_resolve_add_rule:266 - This syscall will NOT be blacklisted.
                lxc 20161124124945.328 WARN     lxc_seccomp - seccomp.c:do_resolve_add_rule:265 - Seccomp: failed to resolve syscall: .
                lxc 20161124124945.328 WARN     lxc_seccomp - seccomp.c:do_resolve_add_rule:266 - This syscall will NOT be blacklisted.
                lxc 20161124124945.720 WARN     lxc_start - start.c:signal_handler:338 - invalid pid for SIGCHLD

Any help is welcome.

thanks

**Comment by nlienard** [comment] 2016-11-24 11:59
And now it works:

    root@inxovh-hy001 (node4):~# lxc start inxovh-rdc001
    root@inxovh-hy001 (node4):~#


i didn't do anything more.

**Comment by nlienard** [comment] 2016-11-24 14:46
"systemctl status -l" show s

     │ ├─lxd.service
           │ │ ├─ 7840 [lxc monitor] /var/lib/lxd/containers inxovh-xy001
           │ │ ├─13035 /usr/bin/lxd --group lxd --logfile=/var/log/lxd/lxd.log
           │ │ ├─13039 /usr/bin/lxd --group lxd --logfile=/var/log/lxd/lxd.log
           │ │ ├─14401 [lxc monitor] /var/lib/lxd/containers cephA-003
           │ │ ├─15329 /usr/bin/lxd --group lxd --logfile=/var/log/lxd/lxd.log
           │ │ ├─15330 /usr/bin/lxd --group lxd --logfile=/var/log/lxd/lxd.log
           │ │ ├─16604 [lxc monitor] /var/lib/lxd/containers inxovh-db003
           │ │ ├─22726 [lxc monitor] /var/lib/lxd/containers inxovh-mx001
           │ │ ├─26211 [lxc monitor] /var/lib/lxd/containers inxovh-rdc001
           │ │ ├─26397 /usr/bin/lxd --group lxd --logfile=/var/log/lxd/lxd.log
           │ │ ├─26398 /usr/bin/lxd --group lxd --logfile=/var/log/lxd/lxd.log
           │ │ ├─27267 [lxc monitor] /var/lib/lxd/containers inxovh-rdc002
           │ │ ├─28965 /usr/bin/lxd --group lxd --logfile=/var/log/lxd/lxd.log
           │ │ ├─29914 /usr/lib/x86_64-linux-gnu/lxc/lxc-monitord /var/lib/lxd/containers 13
           │ │ ├─30221 /usr/bin/lxd --group lxd --logfile=/var/log/lxd/lxd.log
           │ │ ├─30223 /usr/bin/lxd --group lxd --logfile=/var/log/lxd/lxd.log
           │ │ ├─32091 [lxc monitor] /var/lib/lxd/containers inxovh-ldap002
           │ │ └─32119 [lxc monitor] /var/lib/lxd/containers inxovh-rdc003

**Comment by nlienard** [comment] 2016-11-24 15:14
after the upgrade, i can't copy/move containers to another node. it hangs.

here strace

    ELg6T92E32tgS+aMWl2HU\n99Z8OQeuK8RylfgdABBqmJtqev7GNKL1xnb7SiziVTDgmuGWVNcBycNAwNBNyiTB\nDyilQ8176cTJttFWV0RGyPiEbVhriMWZzJ9s95KgJVHrf3elJ4+D9sz+0gCVlQ9U\nhoQSiG2UxK9SUKDpUPAe49MGdVN+crxF2iEZurlRYHCIheKQRqAfpyLdQPP263Kx\nBw==\n-----END     CERTIFICATE-----\n", 4016) = 3504
    read(3, "", 512)                        = 0
    close(3)                                = 0
    mmap(0xc820200000, 1048576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1,     0) = 0xc820200000
    mmap(0xc81ffe8000, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc81ffe8000
    futex(0xc82016c108, FUTEX_WAKE, 1)      = 1
    socket(PF_INET, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 3
    setsockopt(3, SOL_SOCKET, SO_BROADCAST, [1], 4) = 0
    connect(3, {sa_family=AF_INET, sin_port=htons(8443), sin_addr=inet_addr("10.0.0.3")}, 16) = -1 EINPROGRESS (Operation now in progress)
    epoll_ctl(4, EPOLL_CTL_ADD, 3, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=3793175256,     u64=140543713034968}}) = 0
    futex(0xc82016c108, FUTEX_WAKE, 1)      = 1
    futex(0xe19878, FUTEX_WAIT, 0, {9, 999670037}) = 0
    futex(0xe19cd0, FUTEX_WAKE, 1)          = 1
    futex(0xe19c10, FUTEX_WAKE, 1)          = 1
    epoll_wait(4, [], 128, 0)               = 0
    futex(0xe1a888, FUTEX_WAIT, 0, NULL)    = 0
futex(0xc82016d508, FUTEX_WAKE, 1)      = 1
    futex(0xe19ce8, FUTEX_WAKE, 1)          = 0
    futex(0xe19c10, FUTEX_WAKE, 1)          = 1
    futex(0xe19cc0, FUTEX_WAIT, 0, {0, 100000}) = -1 EAGAIN (Resource temporarily unavailable)
    futex(0xc82016c108, FUTEX_WAKE, 1)      = 1
    futex(0xc82006e508, FUTEX_WAKE, 1)      = 1
    futex(0xc82003cd08, FUTEX_WAKE, 1)      = 1
    futex(0xc820254d08, FUTEX_WAKE, 1)      = 1
    futex(0xc82016d508, FUTEX_WAKE, 1)      = 1
    futex(0xc8204b4108, FUTEX_WAKE, 1)      = 1
    futex(0xc82006e908, FUTEX_WAKE, 1)      = 1
    futex(0xc82003c908, FUTEX_WAKE, 1)      = 1
    futex(0xc82049c108, FUTEX_WAKE, 1)      = 1
    futex(0xc82006ed08, FUTEX_WAKE, 1)      = 1
    futex(0xe19c10, FUTEX_WAKE, 1)          = 1
    futex(0xe19ed0, FUTEX_WAIT, 0, NULL)    = 0
epoll_wait(4, [], 128, 0)               = 0
    futex(0xe19cd0, FUTEX_WAKE, 1)          = 1
    futex(0xe19c10, FUTEX_WAKE, 1)          = 1
    futex(0xc82016d508, FUTEX_WAKE, 1)      = 1
    rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [], 8) = 0
    mmap(NULL, 8392704, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7fd2d1ffc000
    mprotect(0x7fd2d1ffc000, 4096, PROT_NONE) = 0
    clone(child_stack=0x7fd2d27fbff0,     flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CL    ONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7fd2d27fc9d0,     tls=0x7fd2d27fc700, child_tidptr=0x7fd2d27fc9d0) = 18806
    rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
    futex(0xe1a888, FUTEX_WAIT, 0, NULL)    = 0
    futex(0xe1a888, FUTEX_WAIT, 0, NULL)    = 0
    futex(0xe1a888, FUTEX_WAIT, 0, NULL

**Comment by brauner** [comment] 2016-11-24 15:31
Can you please provide information about what distro you're using? Also, did you upgrade from or to a PPA? Because your `LXD` server version is `2.6` while your client version is `2.0.5`.

**Comment by nlienard** [comment] 2016-11-24 15:32
root@inxovh-hy001 (node4):~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial


root@inxovh-hy001 (node4):~# dpkg -l |egrep "lxd|lxc"
ii  liblxc1                              2.0.5-0ubuntu4~ubuntu16.04.1~ppa1   amd64        Linux Containers userspace tools (library)
ii  lxc-common                           2.0.5-0ubuntu4~ubuntu16.04.1~ppa1   amd64        Linux Containers userspace tools (common tools)
ii  lxcfs                                2.0.5-0ubuntu1~ubuntu16.04.1~ppa1   amd64        FUSE based filesystem for LXC
ii  lxd                                  2.6-0ubuntu2~ubuntu16.04.1~ppa1     amd64        Container hypervisor based on LXC - daemon
ii  lxd-client                           2.6-0ubuntu2~ubuntu16.04.1~ppa1     amd64        Container hypervisor based on LXC - client
ii  lxd-tools                            2.6-0ubuntu2~ubuntu16.04.1~ppa1     amd64        Container hypervisor based on LXC - extra tools

**Comment by nlienard** [comment] 2016-11-24 15:33
i just found this also:

    root@inxovh-hy001 (node4):~# cat /etc/apt/sources.list.d/ppa_ubuntu_lxc_stable_trusty.list.distUpgrade
    deb http://ppa.launchpad.net/ubuntu-lxc/stable/ubuntu trusty main

**Comment by nlienard** [comment] 2016-11-24 15:38
In apt search, i can see there is another lxc version:

    lxc/xenial,xenial 2.0.5-0ubuntu4~ubuntu16.04.1~ppa1 all
      Transitional package for lxc1

    lxc2/xenial,xenial 2.6-0ubuntu2~ubuntu16.04.1~ppa1 all
      Container hypervisor based on LXC - metapackage

So should i remove lxc and install lxc2 instead of ?

My setup is f****d ? my containers are in prod :(

**Comment by brauner** [comment] 2016-11-24 15:50
No, the `lxc` package you're seeing would not install `LXD`. That is all in order so don't worry about that.

**Comment by nlienard** [comment] 2016-11-24 15:53
what should i do ? why is my client 2.0.5 ? how can i fix that ? thanks

**Comment by stgraber** [comment] 2016-11-24 18:34
The "lxc" command line comes from the lxd-client package, which is at the right version.

The "lxc" package is (as marked above) a "transitional" package for lxc1 so that upgrades work properly. You can remove it and it won't change a thing to your system. The "lxc1" package contains the old (pre-LXD) tools for low level LXC (lxc-* commands).

**Comment by nlienard** [comment] 2016-11-24 22:24
Ok. thanks. 

Then why am i experiencing issue with remote copy ?

**Comment by stgraber** [comment] 2016-11-24 22:34
No idea with the information provided so far.

Can you please post "lxc info" (no argument) for both the source and target server?
Also can you tell us if that's live migration or cold (container stopped) migration?
And does the container have any snapshot?

There have been occasional report of migration issues with particularly large containers but we've never had enough information to reproduce or debug this. Just in case, can you start a tiny, clean container and attempt to migrate it, to confirm that the issue affects all copies/moves?

    lxc launch images:alpine/edge alpine
    lxc move alpine target:

Should do.

**Comment by nlienard** [comment] 2016-11-24 23:05
there are no snapshot done with lxc but there are plenty snapshots done by myself directly with ZFS.
Could it be an issue ?

**Comment by nlienard** [comment] 2016-11-24 23:10
root@inxovh-hy003 (node3):~# lxc launch images:alpine/edge alpine
    Creating alpine
    Retrieving image: 100% (3.40MB/s)
    Starting alpine
    root@inxovh-hy003 (node3):~# lxc stop alpine
    root@inxovh-hy003 (node3):~# lxc move alpine node2:

Now it is hanging.

On remote node, i don't see any zfs datavol alpine, neither in "lxc list", nothing. :(

**Comment by stgraber** [comment] 2016-11-24 23:18
Ok, this may be related to #2644 so we'll take a look at this one once the other one is resolved.

**Comment by stgraber** [comment] 2016-11-24 23:19
Well, this issue is definitely the same as #2644 actually, the copy/move issue may be different but you already filed another one for this. Closing this one as duplicate.

**Comment by stgraber** [comment] 2016-11-24 23:20
Hmm, I'm confused with all your issues, the other copy issue seems to be related to live migration.

**Comment by stgraber** [comment] 2016-11-25 01:33
So I think I also reproduced your copy/move issue here. To confirm my theory, can you please post "lxc info node3:" and "lxc info node2:"?

**Closed** 2016-11-25 02:44 UTC
