### ISSUE TITLE
image copied by 'image copy ubuntu-daily:zesty local: --alias zesty --auto-update' disappeared

### ISSUE THREAD

**Issue by smoser** [lxc/lxd#2967] opened 2017-02-27 15:58 UTC
The template below is mostly useful for bug reports and support questions.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution: ubuntu
 * Distribution version: zesty
 * lxd version: 2.9.3-0ubuntu2
 * lxc info:

        config: {}
        api_extensions:
        - storage_zfs_remove_snapshots
        - container_host_shutdown_timeout
        - container_syscall_filtering
        - auth_pki
        - container_last_used_at
        - etag
        - patch
        - usb_devices
        - https_allowed_credentials
        - image_compression_algorithm
        - directory_manipulation
        - container_cpu_time
        - storage_zfs_use_refquota
        - storage_lvm_mount_options
        - network
        - profile_usedby
        - container_push
        - container_exec_recording
        - certificate_update
        - container_exec_signal_handling
        - gpu_devices
        - container_image_properties
        - migration_progress
        - id_map
        - network_firewall_filtering
        - network_routes
        - storage
        - file_delete
        - file_append
        - network_dhcp_expiry
        api_status: stable
        api_version: "1.0"
        auth: trusted
        public: false
        environment:
          addresses: []
          architectures:
          - x86_64
          - i686
          certificate: |
            -----BEGIN CERTIFICATE-----
            MIIHhjCCBW6gAwIBAgIQTrZA/IdKStvMzx/cpZ0F8TANBgkqhkiG9w0BAQsFADA2
            ..
            rvc10de6jzB7zw==
            -----END CERTIFICATE-----
          certificate_fingerprint: 79835e469ddd6eb1c253801988b8b950bbe87e83c1d21ee8bea8ff2b6ec4df95
          driver: lxc
          driver_version: 2.0.7
          kernel: Linux
          kernel_architecture: x86_64
          kernel_version: 4.9.0-15-generic
          server: lxd
          server_pid: 1181
          server_version: 2.9.3
          storage: zfs
          storage_version: 0.6.5.8-0ubuntu7

# Issue description
Yesterday I ran the following (following https://github.com/lxc/lxd/issues/1746)

    $ lxc image copy ubuntu-daily:zesty local: --alias zesty --auto-update
    $ lxc launch zesty z1
    $ lxc delete --force z1

Today I came in and ran

    $ lxc launch zesty z1
    error: can't get info for image 'zesty': not found

I expected that the '--auto-update' would keep this around even after all containers from it were deleted.  If that is not the case, what is the proper way to do that?

**Comment by brauner** [comment] 2017-02-27 16:05
Isn't the point of #1746 to *turn off* the auto update flag?

**Comment by smoser** [comment] 2017-02-27 16:14
Well, see the orginal issue.
I wanted to just run something that populated images, basically saying "I want to 'track' ubuntu images for releases X Y Z".
Stephane gave the 'copy' command above, which used to do what i wanted.

At the end of that bug, I suggested that there should be a way to add an alias that gets kept around but does *not* automatically get moved forward.

**Comment by stgraber** [comment] 2017-02-27 16:48
This sounds like what I fixed yesterday.
https://github.com/lxc/lxd/commit/806d55c88562ab82b32d2d8563c20a8ec9bdac98

@smoser your understanding is right. The problem is that there is a bug where LXD deletes all images its updating on startup if it's not used by any downstream storage pools... Will be in tomorrow LXD 2.10 release.

**Closed by stgraber** 2017-02-27 16:48 UTC
