### ISSUE TITLE
Failed to remove ZFS backed container

### ISSUE THREAD

**Issue by Roosterfish** [lxc/lxd#3805] opened 2017-09-16 19:25 UTC
# Required information

 * Distribution: ubuntu
 * Distribution version: 16.04
   * Kernel version: 4.4.0-93-generic
   * LXC version: 2.17
   * LXD version: 2.17
   * Storage backend in use: ZFS

# Issue description

If you try to migrate a container with storage quota attached to the root device to another host and that process failed due to a too small amount of the quota on the target machine, you will get an error when trying to delete the container on the origin machine.  

# Steps to reproduce

At first you have to add a remote host. Let's call it `remote`.

 0. lxc init ubuntu:trusty/amd64 c0
 1. lxc copy c0 c1
 2. lxc config device add c1 root size 500MB
 3. lxc copy/move c1 remote:c1 (Should fail with: Error transferring container data: exit status 1)
 4. lxc delete c1

After executing the `lxc delete`, the following error occurs:
```
error: Failed to destroy ZFS filesystem: cannot destroy snapshot space/containers/c1@migration-send-d919d919-53bd-45a2-9e62-28d01a92a625: dataset is busy
cannot destroy snapshot space/containers/c1@migration-send-982013b3-157c-4bef-9b27-f2e684caf18c: dataset is busy
cannot destroy snapshot space/containers/c1@migration-send-81ff649b-6d4e-48dd-9a2e-522e33a1c3ff: dataset is busy
cannot destroy snapshot space/containers/c1@migration-send-d9f4ef5a-450b-47ee-8a46-d0cc11c74632: dataset is busy
cannot destroy snapshot space/containers/c1@migration-send-b0063726-9926-481d-b556-8faaf6b11115: dataset is busy
cannot destroy snapshot space/containers/c1@migration-send-9ba009b0-13c3-4554-9ece-2bfa24d8255c: dataset is busy
cannot destroy snapshot space/containers/c1@migration-send-7a8aaafe-dc7d-4f83-915c-6d78ad8db567: dataset is busy
cannot destroy snapshot space/containers/c1@migration-send-86e4af2f-5cb6-42f5-8bf2-75327a7564f4: dataset is busy
cannot destroy snapshot space/containers/c1@migration-send-bc9f420e-c493-41ca-93ba-f038df50b911: dataset is busy
cannot destroy snapshot space/containers/c1@migration-send-741b707f-7a00-4bdb-a902-efdfd56ad39b: dataset is busy
cannot destroy snapshot space/containers/c1@migration-send-bb1af27f-04a4-4131-9e1e-e6578602a4e6: dataset is busy
cannot destroy snapshot space/containers/c1@migration-send-216d35ea-9605-4da3-b725-57cdd160d101: dataset is busy
cannot destroy snapshot space/containers/c1@migration-send-33eaeb3e-3ea3-4c81-bf42-b3e10b55fd67: dataset is busy
```
If have tried it multiple times (therefore the amount of errors) until I checked the logs of the target machine which stated:
```
lvl=eror msg="problem with zfs recv: cannot receive new filesystem stream: destination space/containers/c1 space quota exceeded\n." t=2017-09-16T21:14:38+0200
err="exit status 1" lvl=eror msg="Error during migration sink" t=2017-09-16T21:14:38+0200
created=2017-09-16T19:14:26+0000 ephemeral=false lvl=info msg="Deleting container" name=c1 t=2017-09-16T21:14:38+0200 used=1970-01-01T00:00:00+0000
created=2017-09-16T19:14:26+0000 ephemeral=false lvl=info msg="Deleted container" name=c1 t=2017-09-16T21:14:38+0200 used=1970-01-01T00:00:00+0000
```
I know I can solve the problem with increasing the quota, but I think it is a bug that you can't delete a container whose migration to another host failed.

**Comment by Roosterfish** [comment] 2017-09-16 19:53
The container can be deleted without any errors after rebooting the host.

**Comment by brauner** [comment] 2017-09-20 08:40
So what seems to happen here is that the `zfs send` call never exits. When I start to `strace` it it immediately exists and I can delete the container.

**Comment by brauner** [comment] 2017-09-20 10:18
@stgraber, this is some weird websocket stuff that seems to be going on somehow the `ioutil.ReadAll()` call hangs on reading from `stderr` if I skip that call and explicitly call `stderr.Close()` for the `stderr` pipe it still hangs in `Wait()` with `S+`. You're more familiar with the websocket code so you might have a better idea of what's going on here. Stopping the receiving side's daemon won't help either.

**Comment by stgraber** [comment] 2017-12-18 08:05
@brauner any chance you can look into this again?

**Comment by brauner** [comment] 2017-12-18 15:02
Not reproducible with `LXD 2.17` and `zfsutils-linux` version `0.6.5.11-1ubuntu3`. There is however still one noticeable performance impact caused by `zfs receive`:
When getting close to reaching the file system quota the sending side requested on the receiving side `zfs receive` becomes extremely slow in reading the received data from the buffer. I assume it's the kernel buffer because `zfs receive` hangs in `D+` state which indicates that it is in a syscall which can only be `read()`. One can verify that the dataset on the receiving side is very slowly filling up. I take it that `zfs receive` is doing this to ensure that the quota is never exceeded by a big amount before failing. I believe there's nothing we can do on the LXD side of things.

**Comment by stgraber** [comment] 2017-12-19 22:27
@brauner so should we close this then?

**Comment by brauner** [comment] 2017-12-19 23:19
On Tue, Dec 19, 2017 at 10:27:48PM +0000, Stéphane Graber wrote:
> @brauner so should we close this then?

Yeah, I think so.

**Closed** 2017-12-19 23:22 UTC

**Comment by jaytaylor** [comment] 2018-01-20 19:59
I am currently hitting the error:

    jay-z@jaytaylo.com:~$ sudo lxc delete --force x
    error: Failed to destroy ZFS filesystem: cannot destroy 'tank/containers/x': dataset is busy

Versions:

    jay-z@jaytaylor.com:~$ sudo lxd --version
    2.21
    jay-z@jaytaylor.com:~$ sudo lxc --version
    2.21
    jay-z@jaytaylor.com:~$ dpkg -l | grep zfs
    ii  libzfs2linux                     0.6.5.6-0ubuntu18                          amd64        Native OpenZFS filesystem library for Linux
    ii  zfs-doc                          0.6.5.6-0ubuntu18                          all          Native OpenZFS filesystem documentation and examples.
    ii  zfs-zed                          0.6.5.6-0ubuntu18                          amd64        OpenZFS Event Daemon (zed)
    ii  zfsutils-linux                   0.6.5.6-0ubuntu18                          amd64        Native OpenZFS management utilities for Linux

    jay-z@jaytaylor.com:~$ lsb_release -a
    No LSB modules are available.
    Distributor ID:	Ubuntu
    Description:	Ubuntu 16.04.3 LTS
    Release:	16.04
    Codename:	xenial

    jay-z@jaytaylor.com:~$ uname -a
    Linux ip-10-33-11-208 4.4.0-1044-aws #53-Ubuntu SMP Mon Dec 11 13:49:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

@stgraber Is there any additional information I can provide which would be helpful?

**Comment by stgraber** [comment] 2018-01-20 20:07
@jaytaylor not really, that's pretty much your typical ZFS bug... a reboot will fix it, otherwise, it may also fix itself after some time, no real way to know when...

**Comment by pat-s** [comment] 2018-02-20 14:18
Also just came across this error. There should be a better option than being forced to reboot :/

**Comment by Roosterfish** [comment] 2018-02-20 21:28
@pat-s Haven't tested this bug with the current release candidate. Which version are you using right now?

**Comment by pat-s** [comment] 2018-02-21 09:24
v2.21 (stable snap channel)

**Comment by melato** [comment] 2018-12-04 14:48
The strace workaround works for me, so I did not have to reboot.

> ps -ef | grep zfs

If you see processes like this:

> zfs send z/lxd/containers/otp2@migration-send-5b57f2a9-8a23-45f2-b869-1e3e735d9


then do:

> sudo strace -p {pid}


The process will exit and when all of them are gone, I can delete the container.

I was doing "lxc copy --container-only --refresh ..." and I had interrupted it with CTRL-C.

lxd 3.7 snap 9664
