### ISSUE TITLE
tcpdump in unprivileged container: unable to write to stdout/stderr

### ISSUE THREAD

**Issue by candlerb** [lxc/lxd#2930] opened 2017-02-22 14:54 UTC
# Required information

 * Distribution: ubuntu
 * Distribution version: 16.04
 * The output of "lxc info"

~~~
apiextensions:
- id_map
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: <SNIP>
  certificatefingerprint:  <SNIP>
  driver: lxc
  driverversion: 2.0.6
  kernel: Linux
  kernelarchitecture: x86_64
  kernelversion: 4.4.0-62-generic
  server: lxd
  serverpid: 6550
  serverversion: 2.0.8
  storage: btrfs
  storageversion: "4.4"
config:
  images.auto_update_cached: "false"
  images.auto_update_interval: "0"
public: false
~~~

# Issue description

tcpdump is not working in unprivileged containers.

At first I thought this was something to do with capabilities (#2507).  However tcpdump is able to capture packets and write them to a pcap file. It simply cannot write to stdout/stderr!

# Steps to reproduce

1. Create two Ubuntu 16.04 containers, one privileged, one not.
2. ssh into each one, and then use `sudo -s` to get root. (Do not use `lxc exec` because of [another issue](https://bugs.launchpad.net/ubuntu/+source/lxd/+bug/1641236))
3. Inside one run `tcpdump -i eth0 -nn not tcp port 22`, and ping from the other.

tcpdump in the privileged container works just fine.

tcpdump in the unprivileged container does not show any output. But if I run strace on it I see errors attempting to access stdout and stderr:

~~~
ioctl(1, TCGETS, 0x7fff97c8d680)        = -1 ENOTTY (Inappropriate ioctl for device)
...
write(2, "tcpdump: verbose output suppress"..., 75) = -1 EACCES (Permission denied)
write(2, "listening on eth0, link-type EN1"..., 74) = -1 EACCES (Permission denied)
~~~

This is very weird.  Even more weird: the following command *does* capture packets:

~~~
tcpdump -i eth0 -nn -w foo.pcap
~~~

The file foo.pcap grows. This proves it's nothing to do with network capture perms.

But the following command shows no output:

~~~
tcpdump -r foo.pcap -nn
~~~

And again it's because it can't write to stdout:

~~~
fstat(1, 0x7ffe2fb5eb10)                = -1 EACCES (Permission denied)
read(3, "", 4096)                       = 0
write(1, "14:34:30.618180 IP6 fe80::c609:6"..., 1740) = -1 EACCES (Permission denied)
~~~

I had originally thought this was to do with [capabilities](http://man7.org/linux/man-pages/man7/capabilities.7.html).  But if I run `capsh --print` inside both containers, they both have `cap_net_raw` and `cap_net_admin`.  In fact, the unprivileged container has two additional capabilities!  (`cap_mac_override` and `cap_mac_admin`)

So now I suspect that apparmor is at fault.

#### dmesg

dmesg output generated by the following steps:

* start tcpdump
* wait 5 seconds
* send 1 ping from other side
* wait 5 seconds
* stop tcpdump

~~~
[429020.685987] audit: type=1400 audit(1487774339.708:3597): apparmor="DENIED" operation="file_inherit" namespace="root//lxd-srv2-campus1_<var-lib-lxd>" profile="/usr/sbin/tcpdump" name="/dev/pts/0" pid=12539 comm="tcpdump" requested_mask="wr" denied_mask="wr" fsuid=100000 ouid=101001
[429020.686000] audit: type=1400 audit(1487774339.708:3598): apparmor="DENIED" operation="file_inherit" namespace="root//lxd-srv2-campus1_<var-lib-lxd>" profile="/usr/sbin/tcpdump" name="/dev/pts/0" pid=12539 comm="tcpdump" requested_mask="wr" denied_mask="wr" fsuid=100000 ouid=101001
[429020.686013] audit: type=1400 audit(1487774339.708:3599): apparmor="DENIED" operation="file_inherit" namespace="root//lxd-srv2-campus1_<var-lib-lxd>" profile="/usr/sbin/tcpdump" name="/dev/pts/0" pid=12539 comm="tcpdump" requested_mask="wr" denied_mask="wr" fsuid=100000 ouid=101001
[429020.686022] audit: type=1400 audit(1487774339.708:3600): apparmor="DENIED" operation="file_inherit" namespace="root//lxd-srv2-campus1_<var-lib-lxd>" profile="/usr/sbin/tcpdump" name="/dev/pts/0" pid=12539 comm="tcpdump" requested_mask="wr" denied_mask="wr" fsuid=100000 ouid=101001
[429020.716725] device eth0 entered promiscuous mode
[429020.741308] audit: type=1400 audit(1487774339.764:3601): apparmor="DENIED" operation="file_perm" info="Failed name lookup - disconnected path" error=-13 namespace="root//lxd-srv2-campus1_<var-lib-lxd>" profile="/usr/sbin/tcpdump" name="apparmor/.null" pid=12539 comm="tcpdump" requested_mask="w" denied_mask="w" fsuid=100000 ouid=0
[429020.741330] audit: type=1400 audit(1487774339.764:3602): apparmor="DENIED" operation="file_perm" info="Failed name lookup - disconnected path" error=-13 namespace="root//lxd-srv2-campus1_<var-lib-lxd>" profile="/usr/sbin/tcpdump" name="apparmor/.null" pid=12539 comm="tcpdump" requested_mask="w" denied_mask="w" fsuid=100000 ouid=0
[429021.716785] audit: type=1400 audit(1487774340.740:3603): apparmor="DENIED" operation="getattr" info="Failed name lookup - disconnected path" error=-13 namespace="root//lxd-srv2-campus1_<var-lib-lxd>" profile="/usr/sbin/tcpdump" name="apparmor/.null" pid=12539 comm="tcpdump" requested_mask="r" denied_mask="r" fsuid=100000 ouid=0
[429030.630448] audit: type=1400 audit(1487774349.652:3604): apparmor="DENIED" operation="file_perm" info="Failed name lookup - disconnected path" error=-13 namespace="root//lxd-srv2-campus1_<var-lib-lxd>" profile="/usr/sbin/tcpdump" name="apparmor/.null" pid=12539 comm="tcpdump" requested_mask="w" denied_mask="w" fsuid=100000 ouid=0
[429030.630543] audit: type=1400 audit(1487774349.652:3605): apparmor="DENIED" operation="file_perm" info="Failed name lookup - disconnected path" error=-13 namespace="root//lxd-srv2-campus1_<var-lib-lxd>" profile="/usr/sbin/tcpdump" name="apparmor/.null" pid=12539 comm="tcpdump" requested_mask="w" denied_mask="w" fsuid=100000 ouid=0
[429030.630555] audit: type=1400 audit(1487774349.652:3606): apparmor="DENIED" operation="file_perm" info="Failed name lookup - disconnected path" error=-13 namespace="root//lxd-srv2-campus1_<var-lib-lxd>" profile="/usr/sbin/tcpdump" name="apparmor/.null" pid=12539 comm="tcpdump" requested_mask="w" denied_mask="w" fsuid=100000 ouid=0
[429030.630565] audit: type=1400 audit(1487774349.652:3607): apparmor="DENIED" operation="file_perm" info="Failed name lookup - disconnected path" error=-13 namespace="root//lxd-srv2-campus1_<var-lib-lxd>" profile="/usr/sbin/tcpdump" name="apparmor/.null" pid=12539 comm="tcpdump" requested_mask="w" denied_mask="w" fsuid=100000 ouid=0
[429030.630574] audit: type=1400 audit(1487774349.652:3608): apparmor="DENIED" operation="file_perm" info="Failed name lookup - disconnected path" error=-13 namespace="root//lxd-srv2-campus1_<var-lib-lxd>" profile="/usr/sbin/tcpdump" name="apparmor/.null" pid=12539 comm="tcpdump" requested_mask="w" denied_mask="w" fsuid=100000 ouid=0
[429030.630584] audit: type=1400 audit(1487774349.652:3609): apparmor="DENIED" operation="file_perm" info="Failed name lookup - disconnected path" error=-13 namespace="root//lxd-srv2-campus1_<var-lib-lxd>" profile="/usr/sbin/tcpdump" name="apparmor/.null" pid=12539 comm="tcpdump" requested_mask="w" denied_mask="w" fsuid=100000 ouid=0
[429030.630593] audit: type=1400 audit(1487774349.652:3610): apparmor="DENIED" operation="file_perm" info="Failed name lookup - disconnected path" error=-13 namespace="root//lxd-srv2-campus1_<var-lib-lxd>" profile="/usr/sbin/tcpdump" name="apparmor/.null" pid=12539 comm="tcpdump" requested_mask="w" denied_mask="w" fsuid=100000 ouid=0
[429030.630687] device eth0 left promiscuous mode
~~~

#### privileged container

~~~
$ lxc config show srv1-campus1
name: srv1-campus1
profiles:
- br-cnd11
config:
  security.privileged: "true"
  volatile.base_image: 315bedd32580c3fb79fd2003746245b9fe6a8863fc9dd990c3a2dc90f4930039
  volatile.eth0.hwaddr: 00:16:3e:25:c5:bf
  volatile.idmap.base: "0"
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
devices:
  root:
    path: /
    type: disk
ephemeral: false

root@srv1:~# capsh --print
Current: = cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_syslog,cap_wake_alarm,cap_block_suspend,37+ep
Bounding set =cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_syslog,cap_wake_alarm,cap_block_suspend,37
Securebits: 00/0x0/1'b0
 secure-noroot: no (unlocked)
 secure-no-suid-fixup: no (unlocked)
 secure-keep-caps: no (unlocked)
uid=0(root)
gid=0(root)
groups=0(root)
~~~

#### unprivileged container

~~~
$ lxc config show srv2-campus1
name: srv2-campus1
profiles:
- br-cnd11
config:
  volatile.base_image: 315bedd32580c3fb79fd2003746245b9fe6a8863fc9dd990c3a2dc90f4930039
  volatile.eth0.hwaddr: 00:16:3e:33:9c:29
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  root:
    path: /
    type: disk
ephemeral: false

root@srv2:~# capsh --print
Current: = cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,cap_wake_alarm,cap_block_suspend,37+ep
Bounding set =cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,cap_wake_alarm,cap_block_suspend,37
Securebits: 00/0x0/1'b0
 secure-noroot: no (unlocked)
 secure-no-suid-fixup: no (unlocked)
 secure-keep-caps: no (unlocked)
uid=0(root)
gid=0(root)
groups=0(root)
~~~

#### Related

[LP#1641236](https://bugs.launchpad.net/ubuntu/+source/lxd/+bug/1641236) describes a problem with tcpdump buffering stdout when launched from `lxc exec`, and since it involves apparmor, it may be related.

However that issue is specifically about opening a pty on the host, and then passing it into the container.  Here, the pty is created inside the container (by sshd).

**Comment by candlerb** [comment] 2017-02-22 15:24
The containers were built a couple of weeks ago, and I see that a new tcpdump package been released since then:

~~~
(New) Version: 4.9.0-1ubuntu1~ubuntu16.04.1
(Old) Version: 4.7.4-1ubuntu1
~~~

However, upgrading inside the container didn't make a difference.

There is also a new version of lxd (2.0.9 vs 2.0.8). Updating the host and then restarting the container also made no difference.  Still have:

~~~
write(2, "tcpdump: verbose output suppress"..., 75) = -1 EACCES (Permission denied)
write(2, "listening on eth0, link-type EN1"..., 74) = -1 EACCES (Permission denied)
~~~

**Comment by stgraber** [comment] 2017-02-22 16:41
What you're describing is exactly that bug you mentioned (https://bugs.launchpad.net/ubuntu/+source/lxd/+bug/1641236).

Feel free to comment in the bug to indicate that you ran into it and it'd be great if this could be fixed. Maybe we can get some more traction on the apparmor team for this.

It's effectively a kernel bug in the apparmor implementation and not something we can do anything about in LXD proper.

You do have a few workarounds available though:
 - Using ssh instead of "lxc exec" should work fine (as ssh will allocate its own pts pair)
 - Using "lxc exec" and then running a "script" session should have the same effect as ssh
 - You can turn off the tcpdump apparmor profile by symlinking the profile to /etc/apparmor.d/disable/ then reload apparmor in the container (or reboot it).

I'm closing this issue since there's nothing we can do in LXD itself and we're already tracking this apparmor problem on Launchpad. Feel free to comment and subscribe to the bug over there.

**Closed by stgraber** 2017-02-22 16:41 UTC

**Comment by candlerb** [comment] 2017-02-22 16:45
> Using ssh instead of "lxc exec" should work fine (as ssh will allocate its own pts pair)

Sorry, but that's *exactly* what I'm doing: I'm ssh'ing into the container and I am *not* using lxc exec.

So is this not a different problem altogether?

**Comment by candlerb** [comment] 2017-02-22 16:50
> Using "lxc exec" and then running a "script" session should have the same effect as ssh

This does not work either:

~~~
script foo
tcpdump -i eth0 -nn
~~~

... whether I first ssh into the container and sudo, or I lxc exec into the container.

**Comment by stgraber** [comment] 2017-02-22 17:25
@candlerb hmm, sorry, I missed that. Yes, that would be a different apparmor bug then...

Can you file another issue at https://launchpad.net/ubuntu/+source/apparmor/+filebug
Mentioning that you tried ssh and script so it shouldn't be the inherited pts issue.

I'm assuming disabling that apparmor profile does fix the issue for you though, right?

**Comment by candlerb** [comment] 2017-02-22 17:46
Yes, this does fix it, thank you:

~~~
# ln -s /etc/apparmor.d/usr.sbin.tcpdump /etc/apparmor.d/disable/
~~~

**Comment by stgraber** [comment] 2017-02-22 17:50
Cool. If you do file a bug on Launchpad, please post the link here and I'll subscribe the LXD team to it.

**Comment by candlerb** [comment] 2017-02-22 18:01
https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/1667016

**Comment by gpatel-fr** [comment] 2019-02-21 22:44
Just wanted to add that:
- this problem still exists on Ubuntu 18.04
- after removing the apparmor profile restarting the container helps (obvious if you know apparmor I guess)
- tshark works out of the box.

**Comment by johnbchron** [comment] 2019-06-13 16:45
This problem persists on Ubuntu 19.04

**Comment by candlerb** [comment] 2019-06-13 17:03
@stgraber: you appear to have marked this issue [LP#1667016](https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/1667016)  as a duplicate of [LP#1641236](https://bugs.launchpad.net/ubuntu/+source/lxd/+bug/1641236) - when you agreed earlier it was a different issue and asked me to open a separate bug report

**Comment by jlokier** [comment] 2021-04-21 16:41
Please reopen this issue, it is obvious, reproducible, and not fixed.

tcpdump still broken in an LXD Ubuntu 21.04 container on an Ubuntu 20.10 host.

- Logged in over SSH to the container
- Ubuntu 21.04 container, on Ubuntu 20.10 host (but given the 4 years history of this bug, probably all versions).
- `tcpdump` just returns with no output when run, and no clue to the error, because it can't write anything to stdout/stderr.
- It has the appearance of a weird crash untl you `strace` to see what's going on.
- The `ln -s` suggestion has no effect by itself, you have to restart AppArmor.
- But testarting AppArmor (with the `ln -s) has no effect either (another bug!).
- I've read you have to restart the container, but mine is being used, I can't restart it.
- If you can't restart the container, what can you do?

Simplest workaround is to rename or copy `tcpdump`.  Silly I know, but it's what works:

    elsewhere$ ssh container
    container$ sudo tcpdump -i lo # Nothing is output due to this LXC bug.
    container$ echo $?
    1
    container$

Workaround without restarting the container:

    container$ cp -p /usr/sbin/tcpdump .
    container$ sudo ./tcpdump -i lo # Works!
    tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
    listening on lo, link-type EN10MB (Ethernet), capture size 262144 bytes
    ... etc

**Comment by tomponline** [comment] 2021-04-21 16:59
FWIW I tend to use `tcpdump -l` which I find works.

**Comment by jlokier** [comment] 2021-04-21 17:07
I was about to write another handy workaround.  `tcpdump -l` by itself doesn't work, but if piped though `cat` it does:

    container$ sudo tcpdump -l -i lo | cat    container$ echo $?
    tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
    listening on lo, link-type EN10MB (Ethernet), capture size 262144 bytes
    ... etc

Without the `cat` it doesn't work:

    container$ sudo tcpdump -l -i lo     # Nothing is output due to this LXC bug.
    container$ echo $?
    1
    container$

**Comment by candlerb** [comment] 2021-04-21 17:10
Have you tried exactly the following, inside the container?

~~~
ln -s /etc/apparmor.d/usr.sbin.tcpdump /etc/apparmor.d/disable/
apparmor_parser -R /etc/apparmor.d/disable/
~~~

This works for me in all the host/container combinations I use - but I only use LTS versions so haven't tried 20.10 / 21.04

**Comment by tomponline** [comment] 2021-04-21 17:22
From looking further up the thread it seems this an apparmor bug so probably best to post on the linked issue. Thanks

**Comment by candlerb** [comment] 2021-04-21 17:27
Correctly disabling apparmor for tcpdump, using the commands shown, will prove it one way or the other.

**Comment by yuklia** [comment] 2021-09-08 14:49
Hi! Issue still exists:
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
```

**Comment by Dacesilian** [comment] 2022-02-16 06:56
Mentioned solution doesn't work on Ubuntu 21.10 (GNU/Linux 5.13.19-4-pve x86_64).

**Comment by sbromberger** [comment] 2022-03-21 13:29
Just ran into this as well. Piping to `cat` produces output; without it, it looks like trying to write to FD 2 is causing "permission denied" errors and causing tcpdump to terminate.

**Comment by kenemar** [comment] 2022-12-06 15:33
I encountered this issue on an unprivileged Ubuntu 20.04 container on Proxmox version
`pve-manager/7.2-3/c743d6c1 (running kernel: 5.15.30-2-pve)`

I could pipe output from `tcpdump` to file or `cat` but wouldn't give me any output on the terminal.

Backup container, destroy and restore as privileged took care of the issue.

**Comment by wdoekes** [comment] 2023-02-06 09:15
Put:
```
/dev/pts/* rw,
```
in `/etc/apparmor.d/local/usr.bin.tcpdump` inside the container (and restart/reload apparmor).

That should fix things.

**Comment by candlerb** [comment] 2023-02-06 09:51
Thank you! I've tested this. With Ubuntu 18.04 or 20.04, it needs to be `usr.sbin.tcpdump`, i.e.

```
echo "/dev/pts/* rw," >/etc/apparmor.d/local/usr.sbin.tcpdump
systemctl reload apparmor
```

But with 22.04 it's `usr.bin.tcpdump` as you said.
