### ISSUE TITLE
Enhancement to cli by allowing regexp

### ISSUE THREAD

**Issue by jfgibbins** [lxc/lxd#3671] opened 2017-08-16 22:04 UTC
If possible, the use of regular expressions on the cli for commands would be handy, particularly for lxc exec, and other commands as possible  Particularly if the commands could spawn separately and run concurrently rather than sequentially.  Example

lxc exec Container1 -- bash some command
lxc exec Container2 -- bash some command
...
lxc exec Container99 -- bash some command

consolidated to follows
lxc exec Container* -- bash some command

**Comment by stgraber** [comment] 2017-08-17 04:05
The only commands that could support this would be "lxc start/stop/pause/delete", all others don't make sense when targeting multiple containers (from the top of my head anyway).

"lxc exec" is actually a perfect example of a command which cannot target multiple containers as commands may be interactive and even if not, you don't want to end up mixing stdout/stderr of multiple containers.

**Comment by jfgibbins** [comment] 2017-08-17 04:13
Well, I was thinking lxc exec in particular would be useful, like how terraform will spin up multiple concurrently, but your point about interactive is well taken.  Maybe a halt/warning if used on exec, unless "-f --force", similar to deleting a running container.

**Comment by stgraber** [comment] 2017-08-17 04:20
Duplicate of https://github.com/lxc/lxd/issues/1045

**Comment by stgraber** [comment] 2017-08-17 04:20
(This discussion sounded familiar, just found another issue which is pretty much identical :))

**Closed by stgraber** 2017-08-17 04:20 UTC
