### ISSUE TITLE
LXD containers don't inherit rlimits from LXD

### ISSUE THREAD

**Issue by syswipe** [lxc/lxd#3186] opened 2017-04-18 13:45 UTC
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04.1 LTS
 * The output of "lxc info" :

```
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 10.64.20.102:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFrTCCA5WgAwIBAgIQJqDQep/MDQ2EJWsqf43NTzANBgkqhkiG9w0BAQsFADAy
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRIwEAYDVQQDDAlyb290QGgx
    MDIwHhcNMTYxMTMwMTYzMzA0WhcNMjYxMTI4MTYzMzA0WjAyMRwwGgYDVQQKExNs
    aW51eGNvbnRhaW5lcnMub3JnMRIwEAYDVQQDDAlyb290QGgxMDIwggIiMA0GCSqG
    SIb3DQEBAQUAA4ICDwAwggIKAoICAQC/hy/Cz12jP055cuFFMJxjFfQ+EiEIBdIe
    AG+zBW2mbL+9Y7XQgyc7XPZ4EfNZscjBLVNVY3cY5j+mNEGWnuQJyGhpppz+zxSA
    xKMwvX5+pezzomRg4rFD4IVn4vgZ/42bNN4qrFyBhulPTrjVfw2FZMVmMOJ5SoZS
    gkThRMyPrBiU+KbFhBaA26NVkYWyQD/WMH80xp8BdAl1dBQveH+Ul38GVbVOvLcB
    w5nmakXxTKhFqUWJeSt4ONrN8Ko44mg5CsWPobwJ3Wqky9qV3oYbw5U63wDWwf3d
    5+xwr11HjsKLl4PqMpE6ervnY+INSvVY3VZ39uELn/xeARoiSeKhdBulceypLAEs
    ltIbmGSG2cNVEN6hOgoqsiZXvsgCArK9XDUpHwrqMW9MZsm/bs75zhNRwLa0nUnm
    5xjTZ6Oh8idoABTsXSs/BDaS0/Te925IW1lKkoZQzJzS73Z3cFySetdYUV482+Ol
    InedkqQZICNmJx3KvcMxHv824uQrWkeUh7NYO8djvic4K5jYnwb68dkVWmyVcAUs
    m53TnG98N3iIehkaUUlFrnsSVUrPYDn6hPazsBqaauT4EOlJIcviiigNEtGdngcX
    fMF8bHVtce9a0xN8rXAUewgFm5426yuvUdWklmyeZgNY0fQaJhCX8wK1baI3D2jO
    /dlurEZ6lQIDAQABo4G+MIG7MA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggr
    BgEFBQcDATAMBgNVHRMBAf8EAjAAMIGFBgNVHREEfjB8ggRoMTAyghtmZTgwOjoy
    MTA6ZTBmZjpmZTBkOmQ4ZTAvNjSCDzEwLjY0LjIwLjEwMi8yNIIcZmU4MDo6OTAw
    MDpiZGZmOmZlOTQ6ZmU4Yi82NIIcZmU4MDo6NzA2MjpkM2ZmOmZlZDM6NTI4Yy82
    NIIKZmU4MDo6MS82NDANBgkqhkiG9w0BAQsFAAOCAgEAbearigw/bnPcfYJUtHGR
    m2I0JqDDyhWyrqOoiUg1QPbML3P79k8loYoMsHpeP/UoaNQ65EPWOVdLsmhvq4ov
    OLGKN3ZgUdfu+ZAw8EQgI8gYd+mul8lD/S+6/4zE1tegPFhJHY4Ot67lfV4AigIF
    veQ/8VYO/4g/OvCzzMwKfKeAo+c9wCEvgc4BqJtbuaj7MF458GDhk8lJDDeF3Shw
    qxGxc88irBZkO0sf9FeFvAZf4Mn+qNsjwfn10URwXg4AQdcglCn7vPhM8/qldBBe
    FoBbiQFzErECzs5gRcxnkypJ05ZckC3NvdRffK+zm8t56jdZ9aXygdVYjP7ZLlkP
    d7ekd2HycLUBJrdzwrEYrQFBP/CqdrBXYCaxhXkFXwkXRPAFthyKfa2OACcxk61w
    LBUitGnbPOc96OeHD7A2Nv71Nv64ZFH7rP9vcrJK3Sfj1PDpG8E3/AeMxnAmrizU
    s6qBT7BAY+M6EvsJV13IlBiyGPDUfTIak4I6sEwMi5UT43e3mVvyxIhpf/mqGBoY
    9FX2skLIN1nbKXUR0nogzJenvF6ZVr/Ybz/vynoupOXVJxlYHhBaeitcs4sdu/z5
    g78CbbYcn8tIcTi+3GU571VggHELucoF90ZiM8RnQjWlBaX7oV1MR1RyARZXdluB
    NTrTjnRNe+Sjb4p0DPdfigw=
    -----END CERTIFICATE-----
  certificate_fingerprint: 145f538b2db1a89dd3cbf1496cf6e27ca52c5c5adffd64b84c9ffe1a9e34f2d1
  driver: lxc
  driver_version: 2.0.7
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-72-generic
  server: lxd
  server_pid: 22318
  server_version: "2.12"
  storage: zfs
  storage_version: 0.6.5.6-0ubuntu15
```

I stumbled upon a strange behavior of LXD. All my containers shows me NOFILE limit 65536

```
prlimit -p `lxc info test-c1 | grep Pid | awk '{print $2}'` | grep NOFILE
NOFILE     max number of open files             65536     65536
```

Inside container ulimit -n shows the same value.

But! My system settings from /etc/security/limis.conf is 1048576, and /lib//systemd/system/lxd.service specify LimitNOFILE as infinity.
Why my containers starts with wrong value? How can i change it?

**Comment by brauner** [comment] 2017-04-18 13:55
This rather smells like a systemd bug if at all.

**Comment by syswipe** [comment] 2017-04-19 08:14
Ok, but, systemd reacts to lxd.service changes as expected. I changed LimitNOFILE from infinity to 1048576
and lxd starts with
NOFILE     max number of open files             1048576   1048576
but all containers still running with NOFILE 65536.
Any suggestion? or workaround?

**Comment by kfix** [comment] 2017-04-19 23:26
@syswipe you are hitting lxc/lxc#1175

**Comment by stgraber** [comment] 2017-04-20 05:09
Yeah, we merged a change to LXC which would allow setting rlimits through container config.

But I'm still confused as to why containers get their own limit right now in the first place. I'd absolutely expect them to inherit from the parent (LXD in this case), unless "lxd forkexec" is somehow causing the prlimits to be reset?

If that's the case, then we may be able to workaround that by having forkexec mirror LXD's own rlimit prior to spawning the container.

**Comment by stgraber** [comment] 2017-04-24 01:07
@brauner is that something you can take a look at? Basically just making sure that lxd itself gets the right rlimits from systemd, then see whether forkstart gets the same rlimits as lxd itself, if it doesn't have it mirror them. If it does, then look at why LXC is somehow causing rlimits to be reset on container start.

**Comment by brauner** [comment] 2017-04-24 09:37
@stgraber I'm looking into this now.

**Comment by brauner** [comment] 2017-04-24 10:25
A couple of notes:
- Setting `LimitsNOFILE=infinity` in the `systemd` service file for `LXD` will reliably cause `NOFILE`  to be set to `65536`. Where the exact value comes from I'm currently unsure about. What I can definitely say is that `infinity` is not really working as a `NOFILE` limit. This is correct behavior from the kernel's perspective since setting it to `infinity` will mean you're trying to set `NOFILE > $(cat /proc/sys/fs/nr_open)` which should be `1048576` on a standard kernel. So you could e.g. try to set `prlimit -p $(pidof lxd) -n 1048577` and you'd get an `EPERM`. It's not the nicest way to implement this kernel-wise or libc-wise. It would be smarter to interpret `infinity` or `unlimited` in this case as give me the value in `/proc/sys/fs/nr_open` but that's something we could change.
- I can't reproduce. The limits are respected on my system. Did you make sure to a) restart the daemon and b) restart any containers?

**Comment by brauner** [comment] 2017-04-24 11:22
Ok, this is more interesting than I thought at first. Not respecting the ulimits is definitely `systemd`'s fault:
- Using an non-`systemd` distro like `Alpine`:
  - Giving `LXD` a `NOFILE` limit of `100000` or `5000` will be respected by `openrc`.
- Using a `systemd` distro like `Ubuntu`:
  - Giving `LXD` a `NOFILE` limit of `5000` will be respected by `systemd` since it can't crank the value to `65536` because of `EPERM`.
  - Giving `LXD` a `NOFILE` limit of `100000` will _not_ be respected by `systemd` since it can crank the value to `65536`.

**Comment by brauner** [comment] 2017-04-24 12:24
In the meantime @Blub and I managed to track down the culprit in `systemd`. It hardcodes `64*1024` into it's default limits. We should change that.

**Comment by stgraber** [comment] 2017-04-24 15:42
@brauner ok, so the only actionable bug for LXD is that our systemd unit shouldn't use infinity for NOFILE?

We have:
```
LimitNOFILE=infinity
LimitNPROC=infinity
TasksMax=infinity
```

So we should change LimitNOFILE to 1048576. Do we also need to change the other two to pid_max or is the kernel sane about processes?

**Comment by brauner** [comment] 2017-04-24 15:48
@stgraber, the kernel seems sane about the other stuff. It's only the `NOFILE` option afaik. Note however, that we can try to set it to `1048576` but `/proc/sys/fs/nr_open` is configurable, I think. What we'd need is a way to detect the kernel (compiled) limit and then set it.

**Comment by brauner** [comment] 2017-04-24 15:52
So you'd need to detect the currently allowed maximum for newly starting processes by looking at `/proc/sys/fs/nr_open` currently.

**Comment by brauner** [comment] 2017-04-24 15:53
If the value get's lowered afterwards it doesn't have an effect on already running processes.

**Comment by stgraber** [comment] 2017-04-24 15:57
@brauner well, I'm doing this from a systemd service definition so I can't exactly go read files in /sys :)

**Comment by stgraber** [comment] 2017-04-24 15:57
I can bump it to the expected maximum and if the user did something to lower it, they get to keep the pieces.

**Comment by brauner** [comment] 2017-04-24 17:17
@stgraber, sounds good enough. :) The good news is that this value is hard-coded into the kernel sources as 1024*1024 iirc.

**Comment by stgraber** [comment] 2017-04-24 17:44
:)

**Comment by kfix** [comment] 2017-04-24 18:48
could this snippet go into doc/production-setup.md for anybody else that would be unhappy with only 1M file handles provided by this issue's proposed fix?
```
$ cat /etc/systemd/system/lxd.service.d/nofiles.conf
[Service]
ExecStartPre=/usr/bin/prlimit -p 1 --nofile=65536:184467440
LimitNOFILE=infinity
LimitNOFILESoft=infinity

$ cat /etc/sysctl.d/90-lxd.conf
fs.file-max=20000000
# ^ total system file handles
fs.nr_open=184467440
# ^ total allowable file handles per process
```

An exacerbating issue is that one can't manually prlimit PID1 using the infinity constant that `man prlimit` suggests would "unlimit" a process to the highest possible maximum.
```
$ sudo strace prlimit -p 1 --nofile=65536:unlimited
prlimit64(1, RLIMIT_NOFILE, {rlim_cur=64*1024, rlim_max=RLIM64_INFINITY}, NULL) = -1 EPERM (Operation not permitted)
```
it seems the kernel only accepts explicit values that are lower than fs.nr_open (& effectively below fs.file_max): https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/commit/?id=60fd760fb9ff7034360bab7137c917c0330628c2

I wonder if the real fix is that systemd should only be setting its soft limit (rlim_cur) [to 64k](https://github.com/systemd/systemd/commit/4096d6f5879aef73e20dd7b62a01f447629945b0#diff-108b33cf1bd0765d116dd401376ca356R1154) and not its hard limit (rlim_max)?

systemd also does not seem to have an explicit setting for adjusting PID1's own hard limit, where "infinity" could be polled from fs.nr_open.

**Comment by stgraber** [comment] 2017-04-24 19:35
Commited a fix to our packaging branch, we'll now bump to 1048576 by default. Folks who really need more can indeed bump the sysctl and then bump the systemd unit, though they'd have to be careful of potential races.

And none of this is particularly useful until someone makes systemd use those bumped limits in containers in the first place. I've confirmed that this work using containers that use better behaving init systems.

**Closed by stgraber** 2017-04-24 19:35 UTC

**Comment by brauner** [comment] 2017-04-25 09:13
Sent a patch to `systemd` that should lead newer versions of `systemd` to respect container nofile limits: https://github.com/systemd/systemd/pull/5795
