### ISSUE TITLE
Cannot use lxc.network.script.down

### ISSUE THREAD

**Issue by scottmckenzie** [lxc/lxd#588] opened 2015-05-04 21:56 UTC
I have added the following config to an lxd profile:
`raw.lxc: lxc.network.script.down=/usr/local/bin/lxc-ovs`

After this `lxc list` returns:
`error: loading config file for the container failed`

The same error is output if I add an lxc.network.script.down option to a conf file in /usr/share/lxc/config/common.conf.d/.

lxd version is 0.8.1-0ubuntu1~ubuntu14.04.1~ppa1

**Comment by stgraber** [comment] 2015-05-04 22:34
Does it make any difference if you set "lxc.network.0.script.down" instead?

**Comment by scottmckenzie** [comment] 2015-05-04 23:15
Same result with `lxc.network.0.script.down`.

**Comment by stgraber** [comment] 2015-05-05 16:52
Ok, thanks for testing. I'll try to take a look at this at the same time I look into other config issues. Probably not before the end of the week though.

**Comment by hallyn** [comment] 2015-05-11 03:29
I created a new container, and ran the command

lxc config set t1 raw.lxc lxc.network.script.down=/usr/local/bin/lxc-ovs

I created /usr/local/bin/lxc-ovs containing:
#!/bin/sh
echo "hi there, i'm running" >> /tmp/run1

and made it executable:

chmod ugo+x /usr/local/bin/lxc-ovs

After that 'lxc list' worked for me, and after a 'lxc start t1; lxc stop t1' the file /tmp/run1 was created containing "hi there, I'm running".

So I cannot reproduce this bug.

**Comment by scottmckenzie** [comment] 2015-05-11 04:57
The bug is present when adding the key/value pair to a profile applied to a container(s).

I just tested adding directly to a container and it worked as in your example.  So thanks for the workaround, I will use that in the mean time.

Please try this to reproduce (assuming your container t1 still exists):
`lxc config profile create p1`
`lxc config profile set p1 raw.lxc lxc.network.script.down=/usr/local/bin/lxc-ovs`
`lxc config profile apply t1 p1`
`lxc list`

**Comment by hallyn** [comment] 2015-05-11 18:32
Thanks - I see it now.  The problem is that the script.down is being applied to the container before the network configuration itself.

A related annoyance is that once a profile is bad you cannot use 'lxc config' to fix it.

**Comment by stgraber** [comment] 2015-05-11 20:39
The fix for this issue has now been merged, closing this issue.

**Closed by stgraber** 2015-05-11 20:39 UTC
Labels: Bug
