### ISSUE TITLE
copying between ZFS and LVM hosts fail

### ISSUE THREAD

**Issue by MarkGavalda** [lxc/lxd#3168] opened 2017-04-11 23:33 UTC
Trying to copy a non-running snapshot/container from a ZFS to an LVM storage pool based machine we get the following:
```
command fails with:
error: Migration failed on target host: Error transferring container data: websocket: bad handshake

relevant entry from lxd.log:
lvl=eror msg="Rsync receive failed: /var/lib/lxd/containers/gRG-test/: exit status 10: rsync: [generator] write error: Broken pipe (32)\nrsync error: error in socket IO (code 10) at io.c(820) [generator=3.1.1]\n" t=2017-04-11T23:25:35+0000
```

# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04.2

## Sender
config:
  core.https_address: 10.0.0.1
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 10.0.0.1:8443
  architectures:
  - x86_64
  - i686
  driver: lxc
  driver_version: 2.0.7
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-72-generic
  server: lxd
  server_pid: 3719
  server_version: "2.12"
  storage: zfs
  storage_version: 0.6.5.6-0ubuntu15

## Receiver:
config:
  core.https_address: 10.0.0.2
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 10.0.0.2:8443
  architectures:
  - x86_64
  - i686
  driver: lxc
  driver_version: 2.0.7
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.8.0-46-generic
  server: lxd
  server_pid: 2394
  server_version: "2.12"
  storage: lvm
  storage_version: 2.02.133(2) (2015-10-30) / 1.02.110 (2015-10-30) / 4.35.0

**Comment by stgraber** [comment] 2017-04-12 02:23
@brauner is that something you can look into?

**Comment by brauner** [comment] 2017-04-12 14:34
Yes, will do today or tomorrow.

**Comment by MarkGavalda** [comment] 2017-04-12 19:26
Interestingly it doesn't happen all the time. Today we had 4 containers that were made of the same original container at different points in time and two of them were transferred successfully, two of them failed with the exact same error msg as above. Tried it with different kernel versions too, that didn't have any effect on the success rate. Let me know if I can help in any way.

**Comment by brauner** [comment] 2017-04-13 09:41
@MarkGavalda, does it happen only when copying from  `ZFS -> LVM` or also when using a different backend, e.g. `{BTRFS, DIR} -> LVM`? And also only when copying to `LVM` or do you see it in other combinations?

**Comment by brauner** [comment] 2017-04-13 10:53
And does it only appear with containers that have snapshots or also when they have none?

**Comment by brauner** [comment] 2017-04-13 12:43
I've been running container copies betwen zfs and lvm in a tight loop and was unable to reproduce this error so far.

**Comment by MarkGavalda** [comment] 2017-04-13 13:27
@brauner I just tested with btrfs -> LVM and immediately ran into the same issue. LXD 2.12 on both machines. What kind of other logs should I provide?

**Comment by MarkGavalda** [comment] 2017-04-13 13:32
@brauner I tried copying containers

- without snapshots
- with snapshots
- an exact snapshot of a container to the LVM machine as a new container

all failed. Could it be that there's something in the content of these containers that produces this error?

**Comment by brauner** [comment] 2017-04-13 14:03
Are these containers freshly created? If not, could you try if a freshly created container works fine.

**Comment by brauner** [comment] 2017-04-13 14:05
And yes, if it is possible for you to run the two lxd instances in debug mode:

    lxd --debug --group lxd

and then provide all logs in

    /var/log/lxd

for lxd itself and the failing containers from both LXD instances that would indeed by very helpful.

**Comment by MarkGavalda** [comment] 2017-04-13 14:14
They're not freshly created, a new one seems to transfer without issues! Also not all older containers fail, even of the same group of containers (forked from the same original container at different points in time).
These are production machines so I won't be able to run lxd in debug mode here however I can build two identical test machines, copy the containers to those and do all kinds of tests there. Please allow me a few days to do that.

**Comment by brauner** [comment] 2017-04-13 14:51
@MarkGavalda, yeah sure! Thanks for going through the trouble.

**Comment by brauner** [comment] 2017-04-13 15:16
Another thing, both servers run the same LXD version?

**Comment by MarkGavalda** [comment] 2017-04-17 12:48
@brauner yes, all servers run the exact same LXD version.
Quick update: I tried copying one of the failed containers between a Btrfs (from) and a ZFS (to) machine and that failed right away too! So it looks like this affects all storage backends and is not LVM specific.

**Comment by brauner** [comment] 2017-04-17 13:45
If this is a bug it is in the rsync code which is hit when you copy between different storage backends. I will try to reproduce this tomorrow but I'd still very much would like to see the logs I requested if you happen to find some time to do this. :)

**Comment by MarkGavalda** [comment] 2017-04-17 15:57
Yep I've been building those servers today, here you go:
**Sender - ZFS**
lxd log: https://pastebin.com/15AbuEab
container log: https://pastebin.com/bgSrBXAW
**Receiver:**
lxd log: https://pastebin.com/gK4ijdsi
container log: https://pastebin.com/kH8HLZiV

I will keep this VMs around for the next few days if you need me to run any other tests please let me know, I'll run them right away! Thanks.

**Comment by brauner** [comment] 2017-04-17 16:27
@stgraber, looking at the logs above I wonder if this is the same issue as we have seen on Jenkins and that the rsync error is a red herring. The operation vanishes and rsync gets a closed connection error.

**Comment by stgraber** [comment] 2017-04-17 16:38
@brauner I don't see how that could be. The operation isn't considered as started until the target server connects to the source and once it does it keeps the connection open until it's done, therefore keeping the source operation running. The race you fixed wouldn't come into play during the rsync, it only shows up after the rsync is done and the target server has disconnected from the source.

**Comment by brauner** [comment] 2017-04-17 16:48
I'm looking for an explanation of the closed connection error or bad socket io to rsync and the operation vanishing is the one that first comes to mind. Or we're somehow using rsync options that cause it to die on broken symlinks but than rsync would report this error actually.

**Comment by stgraber** [comment] 2017-04-17 16:50
@brauner LXD doesn't support canceling operations, so the operation vanishing wouldn't terminate the websocket connection anyway. What could cause the error is rsync on the source exiting for some reason or the whole source daemon crashing and getting respawned.

**Comment by stgraber** [comment] 2017-04-17 16:54
Relevant target log:
```
DBUG[04-17|13:29:50] handling                                 ip=@ method=POST url=/1.0/containers
DBUG[04-17|13:29:50]
  {
    "architecture": "x86_64",
    "config": {
      "boot.autostart": "true"
    },
    "devices": {
      "root": {
        "path": "/",
        "pool": "default",
        "type": "disk"
      }
    },
    "ephemeral": false,
    "name": "test-1492353885-autobackup",
    "profiles": [
      "default"
    ],
    "source": {
      "base-image": "f4c4c60a6b752a381288ae72a1689a9da00f8e03b732c8d1b8a8fcd1a8890800",
      "certificate": "",
      "mode": "pull",
      "operation": "https://lxd-test-1:8443/1.0/operations/7ae4315f-5259-406c-b0d4-ce08acce3543",
      "secrets": {
        "control": "43f4dca5a1fa8775edbba9d845adb7d2cef97852fce3af81cc4dd9fdea71f2a4",
        "fs": "7e452c91b2517d5f7867a4c380207d8e7a27910472207ffc1253c0c77e76a73b"
      },
      "type": "migration"
    }
  }
DBUG[04-17|13:29:50] Responding to container create
DBUG[04-17|13:29:50] No valid storage pool in the container's local root disk device and profiles found.
INFO[04-17|13:29:50] Creating container                       ephemeral=false name=test-1492353885-autobackup
DBUG[04-17|13:29:50] Initializing an LVM driver.
INFO[04-17|13:29:50] Created container                        ephemeral=false name=test-1492353885-autobackup
DBUG[04-17|13:29:50] Creating empty LVM storage volume for container "test-1492353885-autobackup" on storage pool "lxd".
DBUG[04-17|13:34:20] Created empty LVM storage volume for container "test-1492353885-autobackup" on storage pool "lxd".
DBUG[04-17|13:34:20] Mounting LVM storage volume for container "test-1492353885-autobackup" on storage pool "lxd".
DBUG[04-17|13:34:20] Mounted LVM storage volume for container "test-1492353885-autobackup" on storage pool "lxd".
WARN[04-17|13:34:20] Unable to update backup.yaml at this time. name=test-1492353885-autobackup
DBUG[04-17|13:34:20] Unmounting LVM storage volume for container "test-1492353885-autobackup" on storage pool "lxd".
DBUG[04-17|13:34:20] Unmounted LVM storage volume for container "test-1492353885-autobackup" on storage pool "lxd".
DBUG[04-17|13:34:20] New task operation: 46df485c-28ae-4a03-9588-6c855822fba7
DBUG[04-17|13:34:20] Started task operation: 46df485c-28ae-4a03-9588-6c855822fba7
DBUG[04-17|13:34:20]
  {
    "type": "async",
    "status": "Operation created",
    "status_code": 100,
    "operation": "/1.0/operations/46df485c-28ae-4a03-9588-6c855822fba7",
    "error_code": 0,
    "error": "",
    "metadata": {
      "id": "46df485c-28ae-4a03-9588-6c855822fba7",
      "class": "task",
      "created_at": "2017-04-17T13:34:20.400388676Z",
      "updated_at": "2017-04-17T13:34:20.400388676Z",
      "status": "Running",
      "status_code": 103,
      "resources": {
        "containers": [
          "/1.0/containers/test-1492353885-autobackup"
        ]
      },
      "metadata": null,
      "may_cancel": false,
      "err": ""
    }
  }
DBUG[04-17|13:34:20] handling                                 ip=@ method=GET url=/1.0/operations/46df485c-28ae-4a03-9588-6c855822fba7/wait
DBUG[04-17|13:34:21] Mounting LVM storage volume for container "test-1492353885-autobackup" on storage pool "lxd".
DBUG[04-17|13:34:21] Mounted LVM storage volume for container "test-1492353885-autobackup" on storage pool "lxd".
DBUG[04-17|13:34:22] Updated metadata for task operation: 46df485c-28ae-4a03-9588-6c855822fba7
DBUG[04-17|13:34:23] Updated metadata for task operation: 46df485c-28ae-4a03-9588-6c855822fba7
DBUG[04-17|13:34:24] Updated metadata for task operation: 46df485c-28ae-4a03-9588-6c855822fba7
DBUG[04-17|13:34:25] Updated metadata for task operation: 46df485c-28ae-4a03-9588-6c855822fba7
DBUG[04-17|13:34:26] Updated metadata for task operation: 46df485c-28ae-4a03-9588-6c855822fba7
DBUG[04-17|13:34:27] Updated metadata for task operation: 46df485c-28ae-4a03-9588-6c855822fba7
DBUG[04-17|13:34:28] Updated metadata for task operation: 46df485c-28ae-4a03-9588-6c855822fba7
DBUG[04-17|13:34:29] Updated metadata for task operation: 46df485c-28ae-4a03-9588-6c855822fba7
DBUG[04-17|13:34:30] Updated metadata for task operation: 46df485c-28ae-4a03-9588-6c855822fba7
DBUG[04-17|13:34:31] Updated metadata for task operation: 46df485c-28ae-4a03-9588-6c855822fba7
DBUG[04-17|13:34:32] Updated metadata for task operation: 46df485c-28ae-4a03-9588-6c855822fba7
DBUG[04-17|13:34:33] Updated metadata for task operation: 46df485c-28ae-4a03-9588-6c855822fba7
DBUG[04-17|13:34:33] Got message barrier, resetting stream
EROR[04-17|13:34:33] Error during migration sink              err="exit status 10"
INFO[04-17|13:34:33] Deleting container                       created=2017-04-17T13:29:50+0000 ephemeral=false name=test-1492353885-autobackup used=1970-01-01T00:00:00+0000
DBUG[04-17|13:34:33] containerDeleteSnapshots                 container=test-1492353885-autobackup
DBUG[04-17|13:34:33] Got err writing crypto/tls: use of closed connection
DBUG[04-17|13:34:33] Deleting LVM storage volume for container "test-1492353885-autobackup" on storage pool "lxd".
EROR[04-17|13:34:33] Rsync receive failed: /var/lib/lxd/containers/test-1492353885-autobackup/: exit status 10: rsync: [generator] write error: Broken pipe (32)
rsync error: error in socket IO (code 10) at io.c(820) [generator=3.1.1]
 
DBUG[04-17|13:34:33] Unmounting LVM storage volume for container "test-1492353885-autobackup" on storage pool "lxd".
DBUG[04-17|13:34:52] Unmounted LVM storage volume for container "test-1492353885-autobackup" on storage pool "lxd".
DBUG[04-17|13:34:53] Deleted LVM storage volume for container "test-1492353885-autobackup" on storage pool "lxd".
INFO[04-17|13:34:53] Deleted container                        created=2017-04-17T13:29:50+0000 ephemeral=false name=test-1492353885-autobackup used=1970-01-01T00:00:00+0000
DBUG[04-17|13:34:53] Failure for task operation: 46df485c-28ae-4a03-9588-6c855822fba7: Error transferring container data: exit status 10
DBUG[04-17|13:34:53]
  {
    "type": "sync",
    "status": "Success",
    "status_code": 200,
    "operation": "",
    "error_code": 0,
    "error": "",
    "metadata": {
      "id": "46df485c-28ae-4a03-9588-6c855822fba7",
      "class": "task",
      "created_at": "2017-04-17T13:34:20.400388676Z",
      "updated_at": "2017-04-17T13:34:33.199526021Z",
      "status": "Failure",
      "status_code": 400,
      "resources": {
        "containers": [
          "/1.0/containers/test-1492353885-autobackup"
        ]
      },
      "metadata": {
        "fs_progress": "test-1492353885-autobackup: 1.57GB (133.67MB/s)"
      },
      "may_cancel": false,
      "err": "Error transferring container data: exit status 10"
    }
  }
```

Relevant source log:
```
DBUG[04-17|13:29:50] handling                                 ip=10.240.0.24:50218 method=POST url=/1.0/containers/test-1492353885-autobackup
DBUG[04-17|13:29:50]
  {
    "live": false,
    "migration": true
  }
DBUG[04-17|13:29:50] New websocket operation: 7ae4315f-5259-406c-b0d4-ce08acce3543
DBUG[04-17|13:29:50] Started websocket operation: 7ae4315f-5259-406c-b0d4-ce08acce3543
DBUG[04-17|13:29:50]
  {
    "type": "async",
    "status": "Operation created",
    "status_code": 100,
    "operation": "/1.0/operations/7ae4315f-5259-406c-b0d4-ce08acce3543",
    "error_code": 0,
    "error": "",
    "metadata": {
      "id": "7ae4315f-5259-406c-b0d4-ce08acce3543",
      "class": "websocket",
      "created_at": "2017-04-17T13:29:50.166813741Z",
      "updated_at": "2017-04-17T13:29:50.166813741Z",
      "status": "Running",
      "status_code": 103,
      "resources": {
        "containers": [
          "/1.0/containers/test-1492353885-autobackup"
        ]
      },
      "metadata": {
        "control": "43f4dca5a1fa8775edbba9d845adb7d2cef97852fce3af81cc4dd9fdea71f2a4",
        "fs": "7e452c91b2517d5f7867a4c380207d8e7a27910472207ffc1253c0c77e76a73b"
      },
      "may_cancel": false,
      "err": ""
    }
  }
DBUG[04-17|13:29:50] Found cert                               k=0
DBUG[04-17|13:29:50] handling                                 ip=10.240.0.24:50220 method=GET url=/1.0
DBUG[04-17|13:29:50] Found cert                               k=0
DBUG[04-17|13:29:50] Initializing a ZFS driver.
DBUG[04-17|13:29:50]
  {
    "type": "sync",
    "status": "Success",
    "status_code": 200,
    "operation": "",
    "error_code": 0,
    "error": "",
    "metadata": {
      "config": {
        "core.https_address": "10.240.0.19",
        "core.trust_password": true
      },
      "api_extensions": [
        "storage_zfs_remove_snapshots",
        "container_host_shutdown_timeout",
        "container_syscall_filtering",
        "auth_pki",
        "container_last_used_at",
        "etag",
        "patch",
        "usb_devices",
        "https_allowed_credentials",
        "image_compression_algorithm",
        "directory_manipulation",
        "container_cpu_time",
        "storage_zfs_use_refquota",
        "storage_lvm_mount_options",
        "network",
        "profile_usedby",
        "container_push",
        "container_exec_recording",
        "certificate_update",
        "container_exec_signal_handling",
        "gpu_devices",
        "container_image_properties",
        "migration_progress",
        "id_map",
        "network_firewall_filtering",
        "network_routes",
        "storage",
        "file_delete",
        "file_append",
        "network_dhcp_expiry",
        "storage_lvm_vg_rename",
        "storage_lvm_thinpool_rename",
        "network_vlan",
        "image_create_aliases",
        "container_stateless_copy"
      ],
      "api_status": "stable",
      "api_version": "1.0",
      "auth": "trusted",
      "public": false,
      "environment": {
        "addresses": [
          "10.240.0.19:8443"
        ],
        "architectures": [
          "x86_64",
          "i686"
        ],
        "certificate": "",
        "certificate_fingerprint": "",
        "driver": "lxc",
        "driver_version": "2.0.7",
        "kernel": "Linux",
        "kernel_architecture": "x86_64",
        "kernel_version": "4.8.0-46-generic",
        "server": "lxd",
        "server_pid": 5970,
        "server_version": "2.12",
        "storage": "zfs",
        "storage_version": "0.6.5.8-0ubuntu4.1"
      }
    }
  }
DBUG[04-17|13:34:21] allowing untrusted GET                   ip=10.240.0.24:50252 url="/1.0/operations/7ae4315f-5259-406c-b0d4-ce08acce3543/websocket?secret=43f4dca5a1fa8775edbba9d845adb7d2cef97852fce3af81cc4dd9fdea71f2a4"
DBUG[04-17|13:34:21] Connected websocket operation: 7ae4315f-5259-406c-b0d4-ce08acce3543
DBUG[04-17|13:34:21] Handled websocket operation: 7ae4315f-5259-406c-b0d4-ce08acce3543
DBUG[04-17|13:34:21] allowing untrusted GET                   ip=10.240.0.24:50254 url="/1.0/operations/7ae4315f-5259-406c-b0d4-ce08acce3543/websocket?secret=7e452c91b2517d5f7867a4c380207d8e7a27910472207ffc1253c0c77e76a73b"
DBUG[04-17|13:34:21] Connected websocket operation: 7ae4315f-5259-406c-b0d4-ce08acce3543
DBUG[04-17|13:34:21] Handled websocket operation: 7ae4315f-5259-406c-b0d4-ce08acce3543
DBUG[04-17|13:34:21] Initializing a ZFS driver.
DBUG[04-17|13:34:21] Mounting ZFS storage volume for container "test-1492353885-autobackup" on storage pool "default".
DBUG[04-17|13:34:21] Mounted ZFS storage volume for container "test-1492353885-autobackup" on storage pool "default".
DBUG[04-17|13:34:22] Updated metadata for websocket operation: 7ae4315f-5259-406c-b0d4-ce08acce3543
DBUG[04-17|13:34:23] Updated metadata for websocket operation: 7ae4315f-5259-406c-b0d4-ce08acce3543
DBUG[04-17|13:34:24] Updated metadata for websocket operation: 7ae4315f-5259-406c-b0d4-ce08acce3543
DBUG[04-17|13:34:25] Updated metadata for websocket operation: 7ae4315f-5259-406c-b0d4-ce08acce3543
DBUG[04-17|13:34:26] Updated metadata for websocket operation: 7ae4315f-5259-406c-b0d4-ce08acce3543
DBUG[04-17|13:34:27] Updated metadata for websocket operation: 7ae4315f-5259-406c-b0d4-ce08acce3543
DBUG[04-17|13:34:28] Updated metadata for websocket operation: 7ae4315f-5259-406c-b0d4-ce08acce3543
DBUG[04-17|13:34:29] Updated metadata for websocket operation: 7ae4315f-5259-406c-b0d4-ce08acce3543
DBUG[04-17|13:34:30] Updated metadata for websocket operation: 7ae4315f-5259-406c-b0d4-ce08acce3543
DBUG[04-17|13:34:31] Updated metadata for websocket operation: 7ae4315f-5259-406c-b0d4-ce08acce3543
DBUG[04-17|13:34:32] Updated metadata for websocket operation: 7ae4315f-5259-406c-b0d4-ce08acce3543
DBUG[04-17|13:34:33] Updated metadata for websocket operation: 7ae4315f-5259-406c-b0d4-ce08acce3543
DBUG[04-17|13:34:33] sending write barrier
EROR[04-17|13:34:33] Rsync send failed: /var/lib/lxd/containers/test-1492353885-autobackup/: exit status 10: rsync: [sender] write error: Broken pipe (32)
rsync error: error in socket IO (code 10) at io.c(820) [sender=3.1.1]
 
DBUG[04-17|13:34:33] Didn't write all of buf
DBUG[04-17|13:34:33] Failure for websocket operation: 7ae4315f-5259-406c-b0d4-ce08acce3543: exit status 10
```

Everything else in the logs are caused by the client attempting to re-do the migration using alternate IPs which fail as the source operation has already died.

**Comment by stgraber** [comment] 2017-04-17 16:56
So we see that 1.57GB have been transferred properly before we hit the failure.

The "sending write barrier" on the source side immediately before the connection collapses suggests that it's a source side problem.

**Comment by MarkGavalda** [comment] 2017-04-17 17:19
@stgraber Seems to be relevant information that `lxc info` for this particular container on the zfs machine says:
```
  Disk usage:
    root: 2.47GB
```

**Comment by brauner** [comment] 2017-04-17 19:40
@MarkGavalda, how much ram is available at the time of failure, maybe this is a memory issue on the source.

**Comment by stgraber** [comment] 2017-04-17 19:52
dmesg output on source and target would be useful to rule out memory issues and segfaults since both would be logged in there

**Comment by brauner** [comment] 2017-04-17 21:41
Also, this could be related to https://github.com/lxc/lxd/issues/2494.

**Comment by stgraber** [comment] 2017-04-18 06:08
@brauner yes, it did remind me of that issue. If we can finally get our hands on a somewhat reliable reproducer we may be able to finally resolve it.

**Comment by brauner** [comment] 2017-04-18 09:10
@MarkGavalda, since you happen to be able to reliably reproduce this can you please give precise instructions for a reproducer?
Also, is it possible for you to apply the following patch to LXD master, built a binary and try to reproduce from with this binary on both hosts if you can reproduce?

```
From c76790c90d13050fa686bb883d250d388d925db7 Mon Sep 17 00:00:00 2001
From: Christian Brauner <christian.brauner@ubuntu.com>
Date: Tue, 18 Apr 2017 11:05:02 +0200
Subject: [PATCH] rsync: make our netcat handle EAGAIN

In particular, some filesystems give this, and golang's io.Copy doesn't
understand it and calls it an error. So let's instead just mask it and have
io.Copy try again.

Signed-off-by: Tycho Andersen <tycho.andersen@canonical.com>
---
 lxd/main_netcat.go | 19 ++++++++++++++++++-
 1 file changed, 18 insertions(+), 1 deletion(-)

diff --git a/lxd/main_netcat.go b/lxd/main_netcat.go
index f5be1b3c..f173964e 100644
--- a/lxd/main_netcat.go
+++ b/lxd/main_netcat.go
@@ -6,6 +6,7 @@ import (
 	"net"
 	"os"
 	"sync"
+	"syscall"
 )
 
 // Netcat is called with:
@@ -34,7 +35,7 @@ func cmdNetcat(args []string) error {
 	wg.Add(1)
 
 	go func() {
-		io.Copy(os.Stdout, conn)
+		io.Copy(os.Stdout, hideAgainReader{conn})
 		conn.Close()
 		wg.Done()
 	}()
@@ -47,3 +48,19 @@ func cmdNetcat(args []string) error {
 
 	return nil
 }
+
+type hideAgainReader struct {
+	r io.Reader
+}
+
+func (hr hideAgainReader) Read(p []byte) (int, error) {
+	n, err := hr.r.Read(p)
+	if err != nil {
+		// golang's io.Copy doesn't understand EAGAIN, so let's mask it
+		if errno, ok := err.(syscall.Errno); ok && errno == syscall.EAGAIN {
+			return n, nil
+		}
+	}
+
+	return n, err
+}
-- 
2.11.0

```

**Comment by MarkGavalda** [comment] 2017-04-18 10:54
dmesg is "empty" I checked that right away, no errors and nothing relevant to this problem. plenty of memory is still available (50GB+) and we have swap as well.

**Comment by MarkGavalda** [comment] 2017-04-18 11:39
@brauner can I contact you privately somehow? as these are test machines only I could give you access to them and you could try anything you want to get this resolved; I think that would be a lot quicker than going through me all the time?

**Comment by brauner** [comment] 2017-04-18 12:03
@MarkGavalda sure, just use `christian.brauner@ubuntu.com`. :)

**Comment by MarkGavalda** [comment] 2017-04-18 13:01
I built LXD with the patch included, unfortunately the result is the same:
sender:
```
DBUG[04-18|12:58:46] Updated metadata for websocket operation: 1528122a-a0f5-4a07-aded-29e18a40a80e 
DBUG[04-18|12:58:47] sending write barrier 
DBUG[04-18|12:58:47] Didn't write all of buf 
EROR[04-18|12:58:47] Rsync send failed: /var/lib/lxd/containers/test-1492353885-autobackup/: exit status 10: rsync: [sender] write error: Broken pipe (32)
rsync error: error in socket IO (code 10) at io.c(820) [sender=3.1.1]
 
DBUG[04-18|12:58:47] Unmounting ZFS storage volume for container "test-1492353885-autobackup" on storage pool "default". 
DBUG[04-18|12:58:48] Unmounted ZFS storage volume for container "test-1492353885-autobackup" on storage pool "default". 
DBUG[04-18|12:58:48] Failure for websocket operation: 1528122a-a0f5-4a07-aded-29e18a40a80e: exit status 10
```

receiver:
```
DBUG[04-18|12:58:46] Updated metadata for task operation: 8b719d68-a1ee-42f6-8bc0-e5fd9f1d01bc 
DBUG[04-18|12:58:47] Got message barrier, resetting stream 
EROR[04-18|12:58:47] Error during migration sink              err="exit status 10"
DBUG[04-18|12:58:47] Got err writing write tcp 10.240.0.24:58910->10.240.0.19:8443: write: connection reset by peer 
INFO[04-18|12:58:47] Deleting container                       created=2017-04-18T12:54:02+0000 ephemeral=false name=test-1492353885-autobackup used=1970-01-01T00:00:00+0000
DBUG[04-18|12:58:47] containerDeleteSnapshots                 container=test-1492353885-autobackup
DBUG[04-18|12:58:47] Deleting LVM storage volume for container "test-1492353885-autobackup" on storage pool "lxd". 
EROR[04-18|12:58:47] Rsync receive failed: /var/lib/lxd/containers/test-1492353885-autobackup/: exit status 10: rsync: [generator] write error: Broken pipe (32)
rsync error: error in socket IO (code 10) at io.c(820) [generator=3.1.1]
 
DBUG[04-18|12:58:47] Unmounting LVM storage volume for container "test-1492353885-autobackup" on storage pool "lxd". 
DBUG[04-18|12:59:04] Unmounted LVM storage volume for container "test-1492353885-autobackup" on storage pool "lxd". 
DBUG[04-18|12:59:05] Deleted LVM storage volume for container "test-1492353885-autobackup" on storage pool "lxd". 
INFO[04-18|12:59:05] Deleted container                        created=2017-04-18T12:54:02+0000 ephemeral=false name=test-1492353885-autobackup used=1970-01-01T00:00:00+0000
DBUG[04-18|12:59:05] Failure for task operation: 8b719d68-a1ee-42f6-8bc0-e5fd9f1d01bc: Error transferring container data: exit status 10 
DBUG[04-18|12:59:05] 
	{
		"type": "sync",
		"status": "Success",
		"status_code": 200,
		"operation": "",
		"error_code": 0,
		"error": "",
		"metadata": {
			"id": "8b719d68-a1ee-42f6-8bc0-e5fd9f1d01bc",
			"class": "task",
			"created_at": "2017-04-18T12:58:31.78048637Z",
			"updated_at": "2017-04-18T12:58:46.997996959Z",
			"status": "Failure",
			"status_code": 400,
			"resources": {
				"containers": [
					"/1.0/containers/test-1492353885-autobackup"
				]
			},
			"metadata": {
				"fs_progress": "test-1492353885-autobackup: 1.57GB (106.72MB/s)"
			},
			"may_cancel": false,
			"err": "Error transferring container data: exit status 10"
		}
	} 
```

**Comment by brauner** [comment] 2017-04-18 13:04
@MarkGavalda, I will take a look on the server soon. :)

**Comment by brauner** [comment] 2017-04-18 13:36
Hm, the "Didn't write all of buf" error in the websocket code might be caused by `EAGAIN` again. This we could probably detect and handle aka retry the write.

**Comment by brauner** [comment] 2017-04-18 18:27
@MarkGavalda, replied to your mail just now.

**Comment by brauner** [comment] 2017-04-19 14:49
So I'm debugging this quite a lot on the servers @MarkGavalda provided access to. So far I have no nice explanation lined up.

**Closed** 2017-04-20 01:58 UTC
