### ISSUE TITLE
feature request: LVM storage quotas

### ISSUE THREAD

**Issue by Laguna-x** [lxc/lxd#3014] opened 2017-03-04 10:25 UTC
https://github.com/lxc/lxd/blob/master/doc/storage-backends.md
shows no quotas implemented with LVM, as we know.
so, lvm let us use keys with size manipulation of volumes, like 
```
{-l|--extents LogicalExtentsNumber[%{VG|FREE|ORIGIN}] |
         -L|--size LogicalVolumeSize[bBsSkKmMgGtTpPeE]}
        [--poolmetadatasize MetadataVolumeSize[bBsSkKmMgG]
```
Will it be implemented in future?

**Comment by stgraber** [comment] 2017-03-04 19:23
Duplicate of #1205

**Closed by stgraber** 2017-03-04 19:23 UTC
