### ISSUE TITLE
error: strange behavior with starting containers and unmounting /usr/lib/.../lxc

### ISSUE THREAD

**Issue by Laguna-x** [lxc/lxd#3255] opened 2017-04-29 14:48 UTC
```
root@mSys:/home/netadmin# lxc network create lxdTemp ipv4.address=none ipv6.address=none ipv4.nat=false ipv6.nat=false
Network lxdTemp created
root@mSys:/home/netadmin# lxc launch ubuntu temp
Создание temp

The container you are starting doesn't have any network attached to it.
  To create a new network, use: lxc network create
  To attach a network to a container, use: lxc network attach

Starting temp
root@mSys:/home/netadmin# lxc network attach lxdTemp temp
root@mSys:/home/netadmin# ovs-vsctl add-port ovsvlan12 lxdTemp
root@mSys:/home/netadmin# lxc exec temp /bin/bash
root@temp:~# ifconfig
root@temp:~# ifup eth0
root@temp:~# exit
root@mSys:/home/netadmin# lxc stop temp
error: shutting down the container failed
Try `lxc info --show-log temp` for more info
root@mSys:/home/netadmin# lxc info --show-log temp
Name: temp
Remote: unix:/var/lib/lxd/unix.socket
Архитектура: x86_64
Создано: 2017/04/29 14:38 UTC
Status: Stopped
Type: persistent
Profiles: default

Журнал:

            lxc 20170429143823.110 ERROR    lxc_monitor - monitor.c:lxc_monitord_spawn:369 - Failed to exec lxc-monitord.
            lxc 20170429143823.113 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20170429143823.114 ERROR    lxc_monitor - monitor.c:lxc_monitord_spawn:369 - Failed to exec lxc-monitord.
            lxc 20170429143823.115 ERROR    lxc_monitor - monitor.c:lxc_monitor_open:218 - Failed to connect to monitor socket. Retrying in 10 ms.
            lxc 20170429143823.126 ERROR    lxc_monitor - monitor.c:lxc_monitor_open:218 - Failed to connect to monitor socket. Retrying in 50 ms.
            lxc 20170429143823.176 ERROR    lxc_monitor - monitor.c:lxc_monitor_open:218 - Failed to connect to monitor socket. Retrying in 100 ms.
            lxc 20170429143823.276 ERROR    lxc_monitor - monitor.c:lxc_monitor_open:223 - Failed to connect to monitor socket: Connection refused.
            lxc 20170429143823.585 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20170429143823.585 WARN     lxc_start - start.c:signal_handler:322 - Invalid pid for SIGCHLD. Received pid 19870, expected pid 19871.
            lxc 20170429144221.200 ERROR    lxc_monitor - monitor.c:lxc_monitord_spawn:369 - Failed to exec lxc-monitord.
            lxc 20170429144221.203 ERROR    lxc_monitor - monitor.c:lxc_monitor_open:218 - Failed to connect to monitor socket. Retrying in 10 ms.
            lxc 20170429144221.213 ERROR    lxc_monitor - monitor.c:lxc_monitor_open:218 - Failed to connect to monitor socket. Retrying in 50 ms.
            lxc 20170429144221.263 ERROR    lxc_monitor - monitor.c:lxc_monitor_open:218 - Failed to connect to monitor socket. Retrying in 100 ms.
            lxc 20170429144221.308 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20170429144221.308 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20170429144221.357 WARN     lxc_monitor - monitor.c:lxc_monitor_fifo_send:111 - Failed to open fifo to send message: No such file or directory.
            lxc 20170429144221.363 ERROR    lxc_monitor - monitor.c:lxc_monitor_open:223 - Failed to connect to monitor socket: Connection refused.
            lxc 20170429144222.760 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:172 - Command get_cgroup failed to receive response: Connection reset by peer.

root@mSys:/home/netadmin# lxc info
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  driver: lxc
  driver_version: 2.0.7
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.8.0-46-generic
  server: lxd
  server_pid: 5612
  server_version: "2.12"
  storage: lvm
  storage_version: 2.02.133(2) (2015-10-30) / 1.02.110 (2015-10-30) / 4.35.0
root@mSys:/home/netadmin# lxc list | grep temp
| temp    | STOPPED |                                |      | PERSISTENT | 0         |
root@mSys:/home/netadmin# lxc image list | grep ubuntu
| ubuntu   | 7afa1fadc0b1 | no     | Ubuntu xenial amd64 (20170422_03:49)  | x86_64 | 81.91MB  | Apr 22, 2017 at 1:33pm (UTC)  |
| ubuntu-c | f4c028336761 | no     | Ubuntu-Core 16 amd64 (20170418_19:01) | x86_64 | 203.31MB | Apr 22, 2017 at 1:36pm (UTC)  |

```

and so on other containers. What can be matter?

**Comment by stgraber** [comment] 2017-05-02 01:45
So the problem is that LXD can't connect to the container's monitor socket and lxc-monitord failed to spawn too.

Can you please:
 - Post the output of "dmesg"
 - Install "debsums" (apt install debsums) and then post the output of "debsums -sa"

**Comment by Laguna-x** [comment] 2017-05-04 15:19
```
root@mSys:/home/netadmin# lxc start temp
root@mSys:/home/netadmin# lxc stop temp
error: shutting down the container failed
Try `lxc info --show-log temp` for more info
root@mSys:/home/netadmin# dmesg
[163090.642688] EXT4-fs (dm-54): mounted filesystem with ordered data mode. Opts: discard
[163090.867748] EXT4-fs (dm-54): mounted filesystem with ordered data mode. Opts: discard
[163090.992188] audit: type=1400 audit(1493911015.318:42): apparmor="STATUS" operation="profile_load" profile="unconfined" name="lxd-temp_</var/lib/lxd>" pid=19612 comm="apparmor_parser"
[163091.050987] lxdTemp: port 1(vethLVRJYN) entered blocking state
[163091.050990] lxdTemp: port 1(vethLVRJYN) entered disabled state
[163091.051116] device vethLVRJYN entered promiscuous mode
[163091.051321] IPv6: ADDRCONF(NETDEV_UP): vethLVRJYN: link is not ready
[163091.127978] eth0: renamed from veth56NRH5
[163091.151962] IPv6: ADDRCONF(NETDEV_CHANGE): vethLVRJYN: link becomes ready
[163091.152055] lxdTemp: port 1(vethLVRJYN) entered blocking state
[163091.152057] lxdTemp: port 1(vethLVRJYN) entered forwarding state
[163093.285680] audit: type=1400 audit(1493911017.610:43): apparmor="STATUS" operation="profile_load" label="lxd-temp_</var/lib/lxd>//&:lxd-temp_<var-lib-lxd>://unconfined" name="/usr/sbin/named" pid=20062 comm="apparmor_parser"
[163093.305976] audit: type=1400 audit(1493911017.630:44): apparmor="STATUS" operation="profile_load" label="lxd-temp_</var/lib/lxd>//&:lxd-temp_<var-lib-lxd>://unconfined" name="/usr/sbin/mysqld" pid=20061 comm="apparmor_parser"
[163093.307155] audit: type=1400 audit(1493911017.634:45): apparmor="STATUS" operation="profile_load" label="lxd-temp_</var/lib/lxd>//&:lxd-temp_<var-lib-lxd>://unconfined" name="/usr/sbin/clamd" pid=20060 comm="apparmor_parser"
[163093.315387] audit: type=1400 audit(1493911017.642:46): apparmor="STATUS" operation="profile_load" label="lxd-temp_</var/lib/lxd>//&:lxd-temp_<var-lib-lxd>://unconfined" name="/sbin/dhclient" pid=20058 comm="apparmor_parser"
[163093.315397] audit: type=1400 audit(1493911017.642:47): apparmor="STATUS" operation="profile_load" label="lxd-temp_</var/lib/lxd>//&:lxd-temp_<var-lib-lxd>://unconfined" name="/usr/lib/NetworkManager/nm-dhcp-client.action" pid=20058 comm="apparmor_parser"
[163093.315405] audit: type=1400 audit(1493911017.642:48): apparmor="STATUS" operation="profile_load" label="lxd-temp_</var/lib/lxd>//&:lxd-temp_<var-lib-lxd>://unconfined" name="/usr/lib/NetworkManager/nm-dhcp-helper" pid=20058 comm="apparmor_parser"
[163093.315412] audit: type=1400 audit(1493911017.642:49): apparmor="STATUS" operation="profile_load" label="lxd-temp_</var/lib/lxd>//&:lxd-temp_<var-lib-lxd>://unconfined" name="/usr/lib/connman/scripts/dhclient-script" pid=20058 comm="apparmor_parser"
[163093.323949] audit: type=1400 audit(1493911017.650:50): apparmor="STATUS" operation="profile_load" label="lxd-temp_</var/lib/lxd>//&:lxd-temp_<var-lib-lxd>://unconfined" name="/usr/bin/freshclam" pid=20059 comm="apparmor_parser"
[163093.712693] audit: type=1400 audit(1493911018.038:51): apparmor="DENIED" operation="file_inherit" namespace="root//lxd-temp_<var-lib-lxd>" profile="/usr/bin/freshclam" name="/run/systemd/journal/stdout" pid=20089 comm="freshclam" requested_mask="wr" denied_mask="wr" fsuid=165536 ouid=165536
[163096.577820] audit_printk_skb: 96 callbacks suppressed
[163096.577823] audit: type=1400 audit(1493911020.902:84): apparmor="DENIED" operation="getattr" info="Failed name lookup - disconnected path" error=-13 namespace="root//lxd-temp_<var-lib-lxd>" profile="/usr/bin/freshclam" name="apparmor/.null" pid=20089 comm="freshclam" requested_mask="r" denied_mask="r" fsuid=165643 ouid=0
[163096.577841] audit: type=1400 audit(1493911020.902:85): apparmor="DENIED" operation="file_perm" info="Failed name lookup - disconnected path" error=-13 namespace="root//lxd-temp_<var-lib-lxd>" profile="/usr/bin/freshclam" name="apparmor/.null" pid=20089 comm="freshclam" requested_mask="w" denied_mask="w" fsuid=165643 ouid=0
[163096.644600] audit: type=1400 audit(1493911020.970:86): apparmor="DENIED" operation="file_inherit" namespace="root//lxd-temp_<var-lib-lxd>" profile="/usr/sbin/mysqld" name="/run/systemd/journal/stdout" pid=20401 comm="mysqld" requested_mask="wr" denied_mask="wr" fsuid=165651 ouid=165536
[163096.644616] audit: type=1400 audit(1493911020.970:87): apparmor="DENIED" operation="file_inherit" namespace="root//lxd-temp_<var-lib-lxd>" profile="/usr/sbin/mysqld" name="/run/systemd/journal/stdout" pid=20401 comm="mysqld" requested_mask="wr" denied_mask="wr" fsuid=165651 ouid=165536
[163096.650150] audit: type=1400 audit(1493911020.974:88): apparmor="DENIED" operation="file_perm" info="Failed name lookup - disconnected path" error=-13 namespace="root//lxd-temp_<var-lib-lxd>" profile="/usr/bin/freshclam" name="apparmor/.null" pid=20089 comm="freshclam" requested_mask="w" denied_mask="w" fsuid=165643 ouid=0
[163096.708275] audit: type=1400 audit(1493911021.034:89): apparmor="DENIED" operation="file_perm" info="Failed name lookup - disconnected path" error=-13 namespace="root//lxd-temp_<var-lib-lxd>" profile="/usr/bin/freshclam" name="apparmor/.null" pid=20089 comm="freshclam" requested_mask="w" denied_mask="w" fsuid=165643 ouid=0
[163096.708306] audit: type=1400 audit(1493911021.034:90): apparmor="DENIED" operation="file_perm" info="Failed name lookup - disconnected path" error=-13 namespace="root//lxd-temp_<var-lib-lxd>" profile="/usr/bin/freshclam" name="apparmor/.null" pid=20089 comm="freshclam" requested_mask="w" denied_mask="w" fsuid=165643 ouid=0
[163096.708350] audit: type=1400 audit(1493911021.034:91): apparmor="DENIED" operation="file_perm" info="Failed name lookup - disconnected path" error=-13 namespace="root//lxd-temp_<var-lib-lxd>" profile="/usr/bin/freshclam" name="apparmor/.null" pid=20089 comm="freshclam" requested_mask="w" denied_mask="w" fsuid=165643 ouid=0
[163096.708374] audit: type=1400 audit(1493911021.034:92): apparmor="DENIED" operation="file_perm" info="Failed name lookup - disconnected path" error=-13 namespace="root//lxd-temp_<var-lib-lxd>" profile="/usr/bin/freshclam" name="apparmor/.null" pid=20089 comm="freshclam" requested_mask="w" denied_mask="w" fsuid=165643 ouid=0
[163096.708403] audit: type=1400 audit(1493911021.034:93): apparmor="DENIED" operation="file_perm" info="Failed name lookup - disconnected path" error=-13 namespace="root//lxd-temp_<var-lib-lxd>" profile="/usr/bin/freshclam" name="apparmor/.null" pid=20089 comm="freshclam" requested_mask="w" denied_mask="w" fsuid=165643 ouid=0
[163102.223124] audit_printk_skb: 63 callbacks suppressed
[163102.223126] audit: type=1400 audit(1493911026.546:115): apparmor="DENIED" operation="file_inherit" namespace="root//lxd-temp_<var-lib-lxd>" profile="/sbin/dhclient" name="/run/systemd/journal/stdout" pid=20691 comm="dhclient" requested_mask="wr" denied_mask="wr" fsuid=165536 ouid=165536
[163102.223140] audit: type=1400 audit(1493911026.546:116): apparmor="DENIED" operation="file_inherit" namespace="root//lxd-temp_<var-lib-lxd>" profile="/sbin/dhclient" name="/run/systemd/journal/stdout" pid=20691 comm="dhclient" requested_mask="wr" denied_mask="wr" fsuid=165536 ouid=165536
[163102.225377] audit: type=1400 audit(1493911026.550:117): apparmor="DENIED" operation="file_perm" namespace="root//lxd-temp_<var-lib-lxd>" profile="/sbin/dhclient" name="/apparmor/.null" pid=20691 comm="dhclient" requested_mask="w" denied_mask="w" fsuid=165536 ouid=0
[163102.225389] audit: type=1400 audit(1493911026.550:118): apparmor="DENIED" operation="file_perm" namespace="root//lxd-temp_<var-lib-lxd>" profile="/sbin/dhclient" name="/apparmor/.null" pid=20691 comm="dhclient" requested_mask="w" denied_mask="w" fsuid=165536 ouid=0
[163103.225743] audit: type=1400 audit(1493911027.550:119): apparmor="DENIED" operation="file_perm" namespace="root//lxd-temp_<var-lib-lxd>" profile="/sbin/dhclient" name="/apparmor/.null" pid=20691 comm="dhclient" requested_mask="w" denied_mask="w" fsuid=165536 ouid=0
[163103.225940] audit: type=1400 audit(1493911027.550:120): apparmor="DENIED" operation="file_perm" namespace="root//lxd-temp_<var-lib-lxd>" profile="/sbin/dhclient" name="/apparmor/.null" pid=20691 comm="dhclient" requested_mask="w" denied_mask="w" fsuid=165536 ouid=0
[163103.226040] audit: type=1400 audit(1493911027.550:121): apparmor="DENIED" operation="file_perm" namespace="root//lxd-temp_<var-lib-lxd>" profile="/sbin/dhclient" name="/apparmor/.null" pid=20691 comm="dhclient" requested_mask="w" denied_mask="w" fsuid=165536 ouid=0
[163103.226112] audit: type=1400 audit(1493911027.550:122): apparmor="DENIED" operation="file_perm" namespace="root//lxd-temp_<var-lib-lxd>" profile="/sbin/dhclient" name="/apparmor/.null" pid=20691 comm="dhclient" requested_mask="w" denied_mask="w" fsuid=165536 ouid=0
[163103.226201] audit: type=1400 audit(1493911027.550:123): apparmor="DENIED" operation="file_perm" namespace="root//lxd-temp_<var-lib-lxd>" profile="/sbin/dhclient" name="/apparmor/.null" pid=20691 comm="dhclient" requested_mask="w" denied_mask="w" fsuid=165536 ouid=0
[163103.226281] audit: type=1400 audit(1493911027.550:124): apparmor="DENIED" operation="file_perm" namespace="root//lxd-temp_<var-lib-lxd>" profile="/sbin/dhclient" name="/apparmor/.null" pid=20691 comm="dhclient" requested_mask="w" denied_mask="w" fsuid=165536 ouid=0
[163103.440084] lxdTemp: port 1(vethLVRJYN) entered disabled state
[163103.614981] lxdTemp: port 1(vethLVRJYN) entered disabled state
[163103.617945] device vethLVRJYN left promiscuous mode
[163103.617950] lxdTemp: port 1(vethLVRJYN) entered disabled state
```

```
root@mSys:/home/netadmin# debsums -sa
debsums: changed file /etc/init.d/networking (from ifupdown package)
debsums: changed file /etc/dhcp/dhcpd.conf (from isc-dhcp-server package)
debsums: missing file /usr/lib/x86_64-linux-gnu/lxc/README (from liblxc1 package)
debsums: missing file /usr/lib/x86_64-linux-gnu/lxc/lxc-apparmor-load (from lxc-common package)
debsums: missing file /usr/lib/x86_64-linux-gnu/lxc/lxc-monitord (from lxc-common package)
debsums: missing file /usr/lib/x86_64-linux-gnu/lxc/lxc-user-nic (from lxc-common package)
debsums: missing file /usr/lib/x86_64-linux-gnu/lxc/hooks/unmount-namespace (from lxc-templates package)
debsums: missing file /usr/lib/x86_64-linux-gnu/lxc/lxc-containers (from lxc1 package)
debsums: missing file /usr/lib/x86_64-linux-gnu/lxc/lxc-net (from lxc1 package)
```

**Comment by brauner** [comment] 2017-05-05 12:36
Can you show:

```
- ls -al /usr/lib/x86_64-linux-gnu/lxc
-  cat /proc/1/mounts
```
please?

**Comment by brauner** [comment] 2017-05-05 12:42
So the monitor failing to exec is pretty suspicious in my opinion. You either have the binary on a filesystem that has the `noexec` flag set or the binary got deleted, or the path where it is located got unmounted, or you are under insane memory pressure.

**Comment by Laguna-x** [comment] 2017-05-06 08:45
@brauner thanks for a way to lookup. somehow fs in /usr/lib/x86_64-linux-gnu/lxc was not mounted by system on boot .
```
root@mSys:/usr/local/bin# ls -al /usr/lib/x86_64-linux-gnu/lxc
итого 16
drwxr-xr-x  2 root root  4096 апр 22 12:36 .
drwxr-xr-x 18 root root 12288 май  4 18:13 ..
root@mSys:/usr/local/bin# cat /etc/fstab
-cutted-
/dev/mapper/Data-usr_lib_x86__lxc /usr/lib/x86_64-linux-gnu/lxc ext4    defaults        0       2
-cutted-
root@mSys:/usr/local/bin# ls -al /usr/lib/x86_64-linux-gnu/lxc
итого 120
drwxr-xr-x  4 root root  4096 апр 22 13:16 .
drwxr-xr-x 18 root root 12288 май  4 18:13 ..
drwxr-xr-x  2 root root  4096 апр 22 13:16 hooks
drwx------  2 root root 16384 апр 22 12:34 lost+found
-rwxr-xr-x  1 root root   521 мар  9 21:35 lxc-apparmor-load
-rwxr-xr-x  1 root root  2965 мар  9 21:35 lxc-containers
-rwxr-xr-x  1 root root 18472 мар  9 21:36 lxc-monitord
-rwxr-xr-x  1 root root  9240 мар  9 21:35 lxc-net
-rwsr-xr-x  1 root root 38984 мар  9 21:36 lxc-user-nic
-rw-r--r--  1 root root   189 мар  9 21:35 README
```

**Comment by Laguna-x** [comment] 2017-05-10 09:54
found it, finaly.
```
root@mSys:/home/netadmin# mount | grep /usr/lib/x86_64-linux-gnu/lxc
root@mSys:/home/netadmin# mount /usr/lib/x86_64-linux-gnu/lxc
root@mSys:/home/netadmin# mount | grep /usr/lib/x86_64-linux-gnu/lxc
/dev/mapper/Data-usr_lib_x86__lxc on /usr/lib/x86_64-linux-gnu/lxc type ext4 (rw,relatime,data=ordered)
root@mSys:/home/netadmin# lxc start odoo
error: The container is already running
Try `lxc info --show-log odoo` for more info
root@mSys:/home/netadmin# mount | grep /usr/lib/x86_64-linux-gnu/lxc
/dev/mapper/Data-usr_lib_x86__lxc on /usr/lib/x86_64-linux-gnu/lxc type ext4 (rw,relatime,data=ordered)
root@mSys:/home/netadmin# lxc stop odoo
root@mSys:/home/netadmin# mount | grep /usr/lib/x86_64-linux-gnu/lxc
/dev/mapper/Data-usr_lib_x86__lxc on /usr/lib/x86_64-linux-gnu/lxc type ext4 (rw,relatime,data=ordered)
root@mSys:/home/netadmin# lxc start odoo
root@mSys:/home/netadmin# mount | grep /usr/lib/x86_64-linux-gnu/lxc
root@mSys:/home/netadmin# cat /etc/fstab | grep /lxc
/dev/mapper/Data-usr_lib_x86__lxc /usr/lib/x86_64-linux-gnu/lxc ext4    defaults        0       2

```

**Comment by brauner** [comment] 2017-05-10 10:34
Locking the issue for now once I've sent a patch for it I unlock it for comments again.

**Comment by brauner** [comment] 2017-05-10 12:53
So I've tracked down the issue and it's caused by `liblxc` and I've already sent a patch. We just need to discuss it a little. :)

**Comment by brauner** [comment] 2017-05-11 00:23
Closed by https://github.com/lxc/lxc/pull/1547 .

**Closed by brauner** 2017-05-11 00:23 UTC
Labels: Bug, Incomplete
