### ISSUE TITLE
Error: UNIQUE constraint failed: images.fingerprint

### ISSUE THREAD

**Issue by schu** [lxc/lxd#4976] opened 2018-08-26 09:39 UTC
LXD version 3.0.2 (stable-3.0), 927a1b7afe7c0f967da4617e873456935d84d8c4, built from source, storage backend is btrfs.

`lxc publish ...` fails with `Error: UNIQUE constraint failed: images.fingerprint`.

```
[...]
+ lxc snapshot kubedee-container-image-b01edcb-dirty-setup snap
+ lxc publish kubedee-container-image-b01edcb-dirty-setup/snap --alias kubedee-container-image-b01edcb-dirty kubedee-version=b01edcb-dirty
Error: UNIQUE constraint failed: images.fingerprint
```

LXD debug log:

```
[...]
DBUG[08-26|11:23:13] handling                                 ip=@ method=POST url=/1.0/containers/kubedee-container-image-b01edcb-dirty-setup/snapshots                                                           
DBUG[08-26|11:23:13] Mounting BTRFS storage volume for container "kubedee-container-image-b01edcb-dirty-setup" on storage pool "kubedee"                                                                           
DBUG[08-26|11:23:13] Mounting BTRFS storage pool "kubedee"
DBUG[08-26|11:23:13] Mounted BTRFS storage volume for container "kubedee-container-image-b01edcb-dirty-setup" on storage pool "kubedee"                                                                            
DBUG[08-26|11:23:13] New task operation: 396f437d-55a9-4c4c-8822-e5909549c688
DBUG[08-26|11:23:13] Started task operation: 396f437d-55a9-4c4c-8822-e5909549c688
DBUG[08-26|11:23:13] Database error: &errors.errorString{s:"sql: no rows in result set"}
DBUG[08-26|11:23:13] handling                                 ip=@ method=GET url=/1.0/operations/396f437d-55a9-4c4c-8822-e5909549c688                                                                             
INFO[08-26|11:23:14] Creating container                       ephemeral=false name=kubedee-container-image-b01edcb-dirty-setup/snap                                                                                
INFO[08-26|11:23:14] Created container                        ephemeral=false name=kubedee-container-image-b01edcb-dirty-setup/snap                                                                                
DBUG[08-26|11:23:14] Creating BTRFS storage volume for snapshot "kubedee-container-image-b01edcb-dirty-setup" on storage pool "kubedee"                                                                            
DBUG[08-26|11:23:14] Mounting BTRFS storage pool "kubedee"
DBUG[08-26|11:23:16] Created BTRFS storage volume for snapshot "kubedee-container-image-b01edcb-dirty-setup" on storage pool "kubedee"                                                                             
DBUG[08-26|11:23:16] Initializing BTRFS storage volume for snapshot "kubedee-container-image-b01edcb-dirty-setup/snap" on storage pool "kubedee"                                                                   
DBUG[08-26|11:23:16] Mounting BTRFS storage pool "kubedee"
DBUG[08-26|11:23:17] Initialized BTRFS storage volume for snapshot "kubedee-container-image-b01edcb-dirty-setup/snap" on storage pool "kubedee"                                                                    
DBUG[08-26|11:23:17] Stopping BTRFS storage volume for snapshot "kubedee-container-image-b01edcb-dirty-setup/snap" on storage pool "kubedee"                                                                       
DBUG[08-26|11:23:17] Mounting BTRFS storage pool "kubedee"
DBUG[08-26|11:23:17] Stopped BTRFS storage volume for snapshot "kubedee-container-image-b01edcb-dirty-setup/snap" on storage pool "kubedee"                                                                        
DBUG[08-26|11:23:17] Success for task operation: 396f437d-55a9-4c4c-8822-e5909549c688
DBUG[08-26|11:23:17] handling                                 ip=@ method=GET url=/1.0
DBUG[08-26|11:23:17] Disconnected event listener: 7dc52d8a-6be1-49bc-9bd4-cba11962203d
DBUG[08-26|11:23:17] handling                                 ip=@ method=GET url=/1.0/events
DBUG[08-26|11:23:17] New event listener: 639e1f7a-7193-4ef3-a846-eaa89ddb0852
DBUG[08-26|11:23:17] handling                                 ip=@ method=POST url=/1.0/images
DBUG[08-26|11:23:17] New task operation: 02fad25b-1bec-49be-974f-d693802f5b6e
DBUG[08-26|11:23:17] Started task operation: 02fad25b-1bec-49be-974f-d693802f5b6e
DBUG[08-26|11:23:17] handling                                 ip=@ method=GET url=/1.0/operations/02fad25b-1bec-49be-974f-d693802f5b6e                                                                             
INFO[08-26|11:23:17] Exporting container                      created=2018-08-26T11:23:13+0200 ephemeral=false name=kubedee-container-image-b01edcb-dirty-setup/snap used=1970-01-01T01:00:00+0100                 
DBUG[08-26|11:23:17] Initializing BTRFS storage volume for snapshot "kubedee-container-image-b01edcb-dirty-setup/snap" on storage pool "kubedee"                                                                   
DBUG[08-26|11:23:17] Mounting BTRFS storage pool "kubedee"
DBUG[08-26|11:23:17] Initialized BTRFS storage volume for snapshot "kubedee-container-image-b01edcb-dirty-setup/snap" on storage pool "kubedee"                                                                    
INFO[08-26|11:23:21] Exported container                       created=2018-08-26T11:23:13+0200 ephemeral=false name=kubedee-container-image-b01edcb-dirty-setup/snap used=1970-01-01T01:00:00+0100                 
DBUG[08-26|11:23:23] Stopping BTRFS storage volume for snapshot "kubedee-container-image-b01edcb-dirty-setup/snap" on storage pool "kubedee"                                                                       
DBUG[08-26|11:23:23] Mounting BTRFS storage pool "kubedee"
DBUG[08-26|11:23:23] Stopped BTRFS storage volume for snapshot "kubedee-container-image-b01edcb-dirty-setup/snap" on storage pool "kubedee"                                                                        
DBUG[08-26|11:23:59] Database error: &errors.errorString{s:"sql: no rows in result set"}
INFO[08-26|11:24:04] Dqlite: closing client
DBUG[08-26|11:24:04] Database error: &errors.errorString{s:"driver: bad connection"}
DBUG[08-26|11:24:04] Retry failed db interaction (driver: bad connection)
INFO[08-26|11:24:04] Dqlite: handling new connection (fd=23)
INFO[08-26|11:24:04] Dqlite: connected address=0 attempt=0
DBUG[08-26|11:24:04] Database error: bindings.Error{Code:2067, Message:"UNIQUE constraint failed: images.fingerprint"}                                                                                             
DBUG[08-26|11:24:05] Failure for task operation: 02fad25b-1bec-49be-974f-d693802f5b6e: UNIQUE constraint failed: images.fingerprint
```

**Comment by stgraber** [comment] 2018-08-26 22:35
I've tried with both the master branch and with 3.0.2 and am unable to reproduce this in either environments.

Are you running a single node or a cluster? Does the issue happen consistently?

If so, can you show `lxd sql global "SELECT * FROM images;"`?

**Comment by stgraber** [comment] 2018-08-26 23:34
Ah, I think I figured it out, you're actually in a case where you should have gotten `The image already exists: FINGERPRINT` but you didn't because of likely unrelated database error which masked this.

Specifically those lines:
```
INFO[08-26|11:24:04] Dqlite: closing client
DBUG[08-26|11:24:04] Database error: &errors.errorString{s:"driver: bad connection"}
DBUG[08-26|11:24:04] Retry failed db interaction (driver: bad connection)
INFO[08-26|11:24:04] Dqlite: handling new connection (fd=23)
INFO[08-26|11:24:04] Dqlite: connected address=0 attempt=0
```

The timing lines up with when LXD would have checked whether the image already exists, our logic checks if we get an error (any error) and if we do, assume it means the record is missing and so should go ahead, this is obviously terrible error handling and I'll fix that.

In this case you should have received "driver: bad connection" as an error and publishing should have halted there. Not ideal and likely an indication of a go-dqlite bug, but better than what happened.

@freeekanayaka FYI, that closing/bad-connection/... stuff looks like a potential go-dqlite issue

**Closed** 2018-08-27 07:42 UTC
Labels: Bug
