### ISSUE TITLE
Crosscompiling lxd for a ppc64 Embedded target Fails

### ISSUE THREAD

**Issue by cordong2956** [lxc/lxd#2273] opened 2016-08-10 20:41 UTC
What version of Go are you using (go version)?
go version go1.6.3 linux/amd64

What operating system and processor architecture are you using (go env)?
Linux ubuntu 3.13.0-91-generic #138-Ubuntu SMP Fri Jun 24 17:00:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

What did you do? My goal is to crosscompile lxd for a ppc64 Embedded target.
CC="/opt/fsl-qoriq/2.0/sysroots/x86_64-fslsdk-linux/usr/bin/powerpc64-fsl-linux/powerpc64-fsl-linux-gcc"
CGO_CFLAGS="-I/opt/fsl-qoriq/2.0/sysroots/ppc64e6500-fsl-linux/usr/include --sysroot=/opt/fsl-qoriq/2.0/sysroots/ppc64e6500-fsl-linux/usr/lib64"
CGO_ENABLED="1"
CGO_LDFLAGS=" --static -L/opt/fsl-qoriq/2.0/sysroots/ppc64e6500-fsl-linux/usr/lib64 --sysroot=/opt/fsl-qoriq/2.0/sysroots/ppc64e6500-fsl-linux"
GOARCH="ppc64"
GOOS="linux"
GOPATH="/home/gcordon/Downloads/GIT/XL/lxd/.gopath"
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/loca/go/bin:/usr/local/go/bin:/opt/fsl-qoriq/2.0/sysroots/ppc64e6500-fsl-linux/usr/include/linux:/opt/fsl-qoriq/2.0/sysroots/ppc64e6500-fsl-linux/usr/include/asm:/opt/fsl-qoriq/2.0/sysroots/ppc64e6500-fsl-linux/usr/lib64"

What did you expect to see?
go get -t -v -d ./...
go get -t -v -d ./...
go get -t -v -d ./...
go install -v ./...
#go build -v ./...
LXD built successfully

What did you see instead?

Must a few times due to go get race

go get -t -v -d ./...
go get -t -v -d ./...
go get -t -v -d ./...
go install -v ./...
runtime/cgo

runtime/cgo

cannot load imported symbols from ELF file $WORK/runtime/cgo/obj/_cgo.o: no symbol section
make: *** [default] Error 2

**Comment by stgraber** [comment] 2016-08-10 20:49
Seems like the Go compiler is attempting to use a native architecture library when resolving the symbols that are used by LXD. That may be for the C library or maybe liblxc, both of which we use from LXD and dynamically link against.

I've no idea what the cross compilation story is with Go when combined with cgo, so you may run into some problems there that would have to be fixed in the compiler/linker itself.

LXD does build perfectly fine on ppc, ppc64 and ppc64el when built directly on the target hardware.

**Comment by cordong2956** [comment] 2016-08-11 22:43
Hi stgraber,

Today I attempted to build LXD on my ppc64 target and I got the following errors:

What version of Go are you using (go version)?
Go Version 1.6.3

What operating system and processor architecture are you using (go env)?
root@t4240rdb:/tmp/lxd/.gopath/src/github.com/lxc/lxd# go env
GOARCH="ppc64"
GOBIN=""
GOEXE=""
GOHOSTARCH="ppc64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/tmp/lxd/.gopath"
GORACE=""
GOROOT="/tmp/go-linux-ppc64-bootstrap"
GOTOOLDIR="/tmp/go-linux-ppc64-bootstrap/pkg/tool/linux_ppc64"
CC="gcc"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build145500303=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

What did you do?
The goal is to build lxd on my ppc64 target.

1.) I created a go-linux-ppc64-bootstrap
2.) configure enviroment variables
3.) /tmp/lxd/.gopath/src/github.com/lxc/lxd


What did you expect to see?

See a working build.

What did you see instead?

I see the following errors:

github.com/lxc/lxd/shared
# github.com/lxc/lxd/test/deps
/tmp/go-linux-ppc64-bootstrap/pkg/tool/linux_ppc64/link: $WORK/net.a(_go_.o): cannot use dynamic imports with -d flag
/tmp/go-linux-ppc64-bootstrap/pkg/tool/linux_ppc64/link: $WORK/runtime/cgo.a(_go_.o): cannot use dynamic imports with -d flag
/tmp/go-build525211153/net.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-build525211153/net.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-build525211153/net.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-build525211153/net.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-build525211153/net.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-build525211153/net.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-build525211153/net.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-build525211153/net.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-build525211153/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-build525211153/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-build525211153/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-build525211153/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-build525211153/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-build525211153/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-build525211153/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-build525211153/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-build525211153/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-build525211153/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-build525211153/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-linux-ppc64-bootstrap/pkg/tool/linux_ppc64/link: too many errors
# github.com/lxc/lxd/lxd-bridge/lxd-bridge-proxy
/tmp/go-linux-ppc64-bootstrap/pkg/tool/linux_ppc64/link: $WORK/net.a(_go_.o): cannot use dynamic imports with -d flag
/tmp/go-linux-ppc64-bootstrap/pkg/tool/linux_ppc64/link: $WORK/runtime/cgo.a(_go_.o): cannot use dynamic imports with -d flag
/tmp/go-build525211153/net.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-build525211153/net.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-build525211153/net.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-build525211153/net.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-build525211153/net.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-build525211153/net.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-build525211153/net.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-build525211153/net.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-build525211153/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-build525211153/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-build525211153/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-build525211153/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-build525211153/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-build525211153/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-build525211153/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-build525211153/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-build525211153/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-build525211153/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-build525211153/runtime/cgo.a(_all.o): unknown relocation type 51; compiled without -fpic?
/tmp/go-linux-ppc64-bootstrap/pkg/tool/linux_ppc64/link: too many errors
github.com/lxc/lxd
github.com/lxc/lxd/fuidshift
github.com/lxc/lxd/shared/logging
github.com/lxc/lxd/shared/termios
github.com/lxc/lxd/lxc
github.com/lxc/lxd/test/lxd-benchmark
# github.com/lxc/lxd/fuidshift
/tmp/go-linux-ppc64-bootstrap/pkg/tool/linux_ppc64/link: $WORK/github.com/lxc/lxd/shared.a(_go_.o): cannot use dynamic imports with -d flag
/tmp/go-linux-ppc64-bootstrap/pkg/tool/linux_ppc64/link: $WORK/net.a(_go_.o): cannot use dynamic imports with -d flag
/tmp/go-linux-ppc64-bootstrap/pkg/tool/linux_ppc64/link: $WORK/os/user.a(_go_.o): cannot use dynamic imports with -d flag
/tmp/go-linux-ppc64-bootstrap/pkg/tool/linux_ppc64/link: $WORK/runtime/cgo.a(_go_.o): cannot use dynamic imports with -d flag
# github.com/lxc/lxd/test/lxd-benchmark
/tmp/go-linux-ppc64-bootstrap/pkg/tool/linux_ppc64/link: $WORK/github.com/lxc/lxd/shared.a(_go_.o): cannot use dynamic imports with -d flag
/tmp/go-linux-ppc64-bootstrap/pkg/tool/linux_ppc64/link: $WORK/net.a(_go_.o): cannot use dynamic imports with -d flag
/tmp/go-linux-ppc64-bootstrap/pkg/tool/linux_ppc64/link: $WORK/os/user.a(_go_.o): cannot use dynamic imports with -d flag
/tmp/go-linux-ppc64-bootstrap/pkg/tool/linux_ppc64/link: $WORK/runtime/cgo.a(_go_.o): cannot use dynamic imports with -d flag
github.com/lxc/lxd/lxd
# github.com/lxc/lxd/lxc
/tmp/go-linux-ppc64-bootstrap/pkg/tool/linux_ppc64/link: $WORK/github.com/lxc/lxd/shared.a(_go_.o): cannot use dynamic imports with -d flag
/tmp/go-linux-ppc64-bootstrap/pkg/tool/linux_ppc64/link: $WORK/github.com/lxc/lxd/shared/termios.a(_go_.o): cannot use dynamic imports with -d flag
/tmp/go-linux-ppc64-bootstrap/pkg/tool/linux_ppc64/link: $WORK/net.a(_go_.o): cannot use dynamic imports with -d flag
/tmp/go-linux-ppc64-bootstrap/pkg/tool/linux_ppc64/link: $WORK/os/user.a(_go_.o): cannot use dynamic imports with -d flag
/tmp/go-linux-ppc64-bootstrap/pkg/tool/linux_ppc64/link: $WORK/runtime/cgo.a(_go_.o): cannot use dynamic imports with -d flag
/tmp/go-linux-ppc64-bootstrap/pkg/tool/linux_ppc64/link: $WORK/github.com/gosexy/gettext.a(_go_.o): cannot use dynamic imports with -d flag
# github.com/lxc/lxd/lxd
/tmp/go-linux-ppc64-bootstrap/pkg/tool/linux_ppc64/link: $WORK/github.com/lxc/lxd/lxd.a(_go_.o): cannot use dynamic imports with -d flag
/tmp/go-linux-ppc64-bootstrap/pkg/tool/linux_ppc64/link: $WORK/gopkg.in/lxc/go-lxc.v2.a(_go_.o): cannot use dynamic imports with -d flag
/tmp/go-linux-ppc64-bootstrap/pkg/tool/linux_ppc64/link: $WORK/github.com/lxc/lxd/shared.a(_go_.o): cannot use dynamic imports with -d flag
/tmp/go-linux-ppc64-bootstrap/pkg/tool/linux_ppc64/link: $WORK/net.a(_go_.o): cannot use dynamic imports with -d flag
/tmp/go-linux-ppc64-bootstrap/pkg/tool/linux_ppc64/link: $WORK/github.com/mattn/go-sqlite3.a(_go_.o): cannot use dynamic imports with -d flag
/tmp/go-linux-ppc64-bootstrap/pkg/tool/linux_ppc64/link: $WORK/runtime/cgo.a(_go_.o): cannot use dynamic imports with -d flag
/tmp/go-linux-ppc64-bootstrap/pkg/tool/linux_ppc64/link: $WORK/os/user.a(_go_.o): cannot use dynamic imports with -d flag
make: *** [default] Error 2

**Comment by stgraber** [comment] 2016-08-11 22:48
I'd suggest you try to build a simple hello world kind of thing see if that works. If it doesn't then get that working first. Then if you're still running into problems, the issue is most likely with your compiler's cgo support/configuration.

powerpc64 (64bit big-endian) isn't an architecture that we build on right now as Ubuntu doesn't support it, but we do build on both powerpc (32bit big-endian using gccgo) and ppc64el (64bit big-endian using golang) and haven't run into any such issues, so the problem is most likely with your setup.

**Comment by cordong2956** [comment] 2016-08-12 13:28
Thanks! stgraber,

The issue seems to be around the GO compilers support of "cgo" on ppc64 big-endian)

I was able to build a Helloworld example with no issues:

root@t4240rdb:/tmp/go# go build -x ./test/helloworld.go
WORK=/tmp/go-build157933705
mkdir -p $WORK/command-line-arguments/_obj/
mkdir -p $WORK/command-line-arguments/_obj/exe/
cd /tmp/go/test
/tmp/go-linux-ppc64-bootstrap/pkg/tool/linux_ppc64/compile -o $WORK/command-line-arguments.a -trimpath $WORK -p main -complete -buildid 13fdccd15b72c3a0e6f7e6c2ead064d666285afe -D _/tmp/go/test -I $WORK -pack ./helloworld.go
cd .
/tmp/go-linux-ppc64-bootstrap/pkg/tool/linux_ppc64/link -o $WORK/command-line-arguments/_obj/exe/a.out -L $WORK -extld=gcc -buildmode=exe -buildid=13fdccd15b72c3a0e6f7e6c2ead064d666285afe $WORK/command-line-arguments.a
mv $WORK/command-line-arguments/_obj/exe/a.out helloworld
root@t4240rdb:/tmp/go#
root@t4240rdb:/tmp/go# ./helloworld
hello, world

As a reference can you send your configuration/ build steps for (32 bit powerpc Big-endian using GCCGO) ?

**Comment by stgraber** [comment] 2016-08-12 15:23
We build on the Ubuntu build farm, so don't touch the compiler itself.

You could install an Ubuntu powerpc build (big-endian, 64bit kernel, 32bit userspace), then install the golang-go package which should install a working gccgo for you.

https://launchpad.net/ubuntu/+source/lxd/2.0.3-0ubuntu1~ubuntu16.04.2/+build/10194577

Is one of our current powerpc builds, you can see the build log there and even grab that compiled powerpc 32bit binaries.

**Closed** 2016-09-23 20:59 UTC
Labels: Incomplete
