### ISSUE TITLE
"dataset is busy" when attempting to delete a container running the ZFS storage backend

### ISSUE THREAD

**Issue by amartin3225** [lxc/lxd#11168] opened 2022-11-28 21:05 UTC
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.15.0 (HWE)
   * LXD version: 5.0.1 (also can be reproduced on 5.8)
   * Storage backend in use: ZFS (I can reproduce with 0.8.3 as well as 2.1.x from `ppa:jonathonf/zfs`)

# Issue description

When attempting to delete a container (e.g. with `lxc delete mycontainer` or `lxc delete --force mycontainer`), I receive the following error:

```
Error: Error deleting storage volume: Failed to run: zfs destroy -r lxd/containers/mycontainer: exit status 1 (cannot destroy 'lxd/containers/mycontainer': dataset is busy)
```

This leaves me with "stuck" containers that I cannot remove. A reboot of the server resolves the problem and allows me to delete the containers, but this is not an acceptable solution as production container hosts cannot be rebooted frequently.

# Steps to reproduce

I have the following profiles:
```
$ lxc profile show default
config:
  boot.autostart: "true"
  limits.cpu: "4"
  limits.memory: 8GB
  snapshots.expiry: 1w
  snapshots.schedule: '@daily'
description: Default LXD profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  root:
    path: /
    pool: default
    size: 50GiB
    type: disk
name: default
used_by: []

$ lxc profile show dataset-is-busy
config:
  user.user-data: |
    #cloud-config
    package_update: true
description: debug dataset-is-busy errors
devices: {}
name: dataset-is-busy
used_by: []
```

I then attempt to launch a container as follows, applying both profiles, and then delete it:
```
lxdhostserver ~ $ name=mycontainer ; lxc launch ubuntu:20.04 local:${name} --profile default --profile dataset-is-busy; time timeout 10m /snap/bin/lxc exec local:${name} -- bash -c 'cloud-init status --wait'; lxc list | grep ${name} ; lxc delete --force ${name}
Creating mycontainer
Starting mycontainer
.........................
status: done

real    6m1.771s
user    0m0.142s
sys     0m0.251s
| mycontainer              | RUNNING | 192.168.1.17 (eth0) |      | CONTAINER | 0         |
Error: Error deleting storage volume: Failed to run: zfs destroy -r lxd/containers/mycontainer: exit status 1 (cannot destroy 'lxd/containers/mycontainer': dataset is busy)
```

As you can see, the "dataset is busy" error occurs. Now if I do the exact same thing but without the `dataset-is-busy` profile, it works and successfully deletes the container:
```
lxdhostserver ~ $ name=mycontainer ; lxc launch ubuntu:20.04 local:${name} --profile default; time timeout 10m /snap/bin/lxc exec local:${name} -- bash -c 'cloud-init status --wait'; lxc list | grep ${name} ; lxc delete --force ${name}
Creating mycontainer
Starting mycontainer
.........................
status: done

real    6m1.771s
user    0m0.142s
sys     0m0.251s
| mycontainer              | RUNNING | 192.168.1.18 (eth0) |      | CONTAINER | 0         |
```

I can reproduce this issue both on the `5.0/stable` channel as well as `latest/stable` (currently on 5.8).

# Information to attach

 - [x] Container log (`lxc info NAME --show-log`)
 - [x] Container configuration (`lxc config show NAME --expanded`)
[container_configuration.txt](https://github.com/lxc/lxd/files/10107509/container_configuration.txt)
[container_log.txt](https://github.com/lxc/lxd/files/10107510/container_log.txt)

**Comment by amartin3225** [comment] 2022-11-29 16:48
I did some additional debugging on the ZFS side that I documented [here](https://zfsonlinux.topicbox.com/groups/zfs-discuss/Tdd4af919192955af/determine-the-source-of-dataset-is-busy).

**Comment by tomponline** [comment] 2022-11-29 16:49
What does `sudo nsenter --mount=/run/snapd/ns/lxd.mnt -- findmnt` show?

**Comment by amartin3225** [comment] 2022-11-29 17:25
If I run `sudo nsenter --mount=/run/snapd/ns/lxd.mnt -- findmnt | grep mycontainer`, there are no results. If I look for anything related to LXD, I see the following:
```
$ sudo nsenter --mount=/run/snapd/ns/lxd.mnt -- findmnt | grep lxd
| `-/tmp                                                                                        /dev/nvme0n1p2[/tmp/snap.lxd/tmp]                      ext4            rw,relatime,errors=remount-ro
| |-/var/snap/lxd/common/lxd/storage-pools                                                      /dev/nvme0n1p2[/var/snap/lxd/common/lxd/storage-pools] ext4            rw,relatime,errors=remount-ro
| | |-/var/snap/lxd/common/lxd/storage-pools/default/containers/myothercontainer12              storage/containers/myothercontainer12                  zfs             rw,relatime,xattr,posixacl
| | |-/var/snap/lxd/common/lxd/storage-pools/default/containers/myothercontainer13              storage/containers/myothercontainer13                  zfs             rw,relatime,xattr,posixacl
| | |-/var/snap/lxd/common/lxd/storage-pools/default/containers/myothercontainer15              storage/containers/myothercontainer15                  zfs             rw,relatime,xattr,posixacl
| | |-/var/snap/lxd/common/lxd/storage-pools/default/containers/my-other-test-container-1       storage/containers/my-other-test-container-1           zfs             rw,relatime,xattr,posixacl
| | `-/var/snap/lxd/common/lxd/storage-pools/default/containers/my-other-test-container-2       storage/containers/my-other-test-container-2           zfs             rw,relatime,xattr,posixacl
| |-/var/snap/lxd/common/lxd/devices                                                            /dev/nvme0n1p2[/var/snap/lxd/common/lxd/devices]       ext4            rw,relatime,errors=remount-ro
| |-/var/snap/lxd/common/ns                                                                     tmpfs                                                  tmpfs           rw,relatime,size=1024k,mode=700,inode64
| |-/var/snap/lxd/common/shmounts                                                               tmpfs                                                  tmpfs           rw,relatime,size=1024k,mode=711,inode64
| | |-/var/snap/lxd/common/shmounts/lxcfs                                                       lxcfs                                                  fuse.lxcfs      rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other
| | `-/var/snap/lxd/common/shmounts/instances                                                   tmpfs                                                  tmpfs           rw,relatime,size=100k,mode=711,inode64
| `-/var/snap/lxd/common/lxd/devlxd                                                             tmpfs                                                  tmpfs           rw,relatime,size=100k,mode=755,inode64
|     |-/var/lib/snapd/hostfs/snap/lxd/23541                                                    /dev/loop8                                             squashfs        ro,nodev,relatime,errors=continue
|     |-/var/lib/snapd/hostfs/snap/lxd/23983                                                    /dev/loop10                                            squashfs        ro,nodev,relatime,errors=continue
|     |-/var/lib/snapd/hostfs/var/snap/lxd/common/ns                                            tmpfs                                                  tmpfs           rw,relatime,size=1024k,mode=700,inode64
| |-/snap/lxd/23541                                                                             /dev/loop8                                             squashfs        ro,nodev,relatime,errors=continue
| |-/snap/lxd/23983                                                                             /dev/loop10                                            squashfs        ro,nodev,relatime,errors=continue
```

**Comment by tomponline** [comment] 2022-12-05 11:47
I've tried this in the `latest/edge` snap channel on Ubuntu 22.04 and have not been able to recreate:

```
lxc storage create zfs zfs
lxc profile show dataset-is-busy
config:
  user.user-data: |
    #cloud-config
    package_update: true
description: debug dataset-is-busy errors
devices: {}
name: dataset-is-busy
used_by: []
```

```
name=mycontainer ; lxc launch ubuntu:20.04 local:${name} --profile default -s zfs --profile dataset-is-busy; time timeout 10m /snap/bin/lxc exec local:${name} -- bash -c 'cloud-init status --wait'; lxc list | grep ${name} ; lxc delete --force ${name}
Creating mycontainer
Starting mycontainer
.............................................................................................................
status: done

real	0m32.793s
user	0m0.026s
sys	0m0.703s
| mycontainer | RUNNING | 10.66.3.39 (eth0) | fd42:ca95:584e:b025:216:3eff:fe2b:f2e7 (eth0) | CONTAINER | 0         |
```

Ran this several times without issue.

Do you see same issue on `latest/edge` channel?

**Comment by amartin3225** [comment] 2022-12-05 20:59
Yes, I'm still able to reproduce the issue on `latest/edge`. I can only reproduce this issue on Ubuntu 20.04 (regardless of which snap channel is used).

**Comment by tomponline** [comment] 2022-12-05 21:09
Thanks I'll try it on 20.04 too.

How do you list the files in the delete queue BTW?

**Comment by tomponline** [comment] 2022-12-06 11:02
Tried Focal host today and not been able to reproduce.

Have you tried doing something like `lxc stop -f ${name}; sleep 10; sleep lxc delete ${name}` and see if that helps.
That would tell us that its a temporary thing that is holding up the delete.

**Comment by amartin3225** [comment] 2022-12-06 13:30
> How do you list the files in the delete queue BTW?

See the fairly complete example [here](https://zfsonlinux.topicbox.com/groups/zfs-discuss/Tdd4af919192955af-M99aee152fd064ef09a397c2e/determine-the-source-of-dataset-is-busy). First start out by listing the entire contents of the dataset for the container as follows and save to a file:
```
# zdb -dddddd lxd/containers/mycontainer > /tmp/zdb
```
Then look for "delete queue" in the output and with that object there should be one or more IDs associated with it, e.g. 40714 in this example:
```
    Object  lvl   iblk   dblk  dsize  dnsize  lsize   %full  type
        33    1   128K    512      0     512    512  100.00  ZFS delete queue (K=inherit) (Z=inherit)
        dnode flags: USED_BYTES USERUSED_ACCOUNTED USEROBJUSED_ACCOUNTED
        dnode maxblkid: 0
        microzap: 512 bytes, 1 entries

                9f0a = 40714
```

Then for each of those IDs, re-run and specify the ID:
```
# zdb -dddddd lxd/containers/mycontainer 40714
```

If that output contains a "parent" ID, then again re-run with the "parent" ID and repeat until it finally gives you the filename.

---

> Tried Focal host today and not been able to reproduce.

I've also been unable to reproduce on a blank/fresh focal VM. I can reproduce on a number of pre-existing systems which have additional configuration applied, so I'm trying to isolate what about them seems to introduce this behavior (e.g. am I setting something like `xattr=sa` on the zpool which does it, is some other package installed, etc).

> Have you tried doing something like lxc stop -f ${name}; sleep 10; sleep lxc delete ${name} and see if that helps.
That would tell us that its a temporary thing that is holding up the delete.

This definitely does not work; the dataset remains "busy" until the next reboot (no matter how many hours/days you wait). Some guidance on the zfs-discuss mailing list suggested that if you mount the dataset, that may cause the delete queue to flush, so even though `mountpoint=legacy` is normally set on LXD datasets, I tried setting it to a directory and mounting the dataset just to see if that would help but unfortunately no change in behavior, the aforementioned file still remained in the delete queue.

**Comment by amartin3225** [comment] 2022-12-06 13:34
Yes, I see that one file/dir, `/rootfs/var/lib/update-notifier`. To me that seems consistent with the idea that the following cloud-init config triggers this behavior since it's obviously doing an `apt-get update` which I believe would touch the above directory:
```
config:
  user.user-data: |
    #cloud-config
    package_update: true
```

**Comment by tomponline** [comment] 2022-12-06 13:41
Can you remove `update-notifier` package from the container?

**Comment by amartin3225** [comment] 2022-12-06 13:53
Unfortunately it looks like it's not installed:
```
# lxc shell mycontainer
root@mycontainer:~# apt-get purge update-notifier
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package 'update-notifier' is not installed, so not removed
The following package was automatically installed and is no longer required:
  libfreetype6
Use 'apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
root@mycontainer:~# ls -l /var/lib/update-notifier/
total 6
-rw-r--r-- 1 root root   0 Dec  5 20:28 dpkg-run-stamp
drwxr-xr-x 3 root root   3 Dec  1 09:54 package-data-downloads
-rw-r--r-- 1 root root 149 Dec  5 20:28 updates-available
drwxr-xr-x 2 root root   2 Apr 25  2022 user.d
```

However I do see the following:
```
root@mycontainer:~# dpkg -S /var/lib/update-notifier
update-manager-core, ubuntu-release-upgrader-core, update-notifier-common: /var/lib/update-notifier
root@mycontainer:~# apt-get purge update-manager-core ubuntu-release-upgrader-core update-notifier-common
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libfreetype6 python3-debian python3-distupgrade python3-update-manager
Use 'apt autoremove' to remove them.
The following packages will be REMOVED:
  ubuntu-release-upgrader-core* ubuntu-server* update-manager-core* update-notifier-common*
0 upgraded, 0 newly installed, 4 to remove and 3 not upgraded.
After this operation, 1787 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 38098 files and directories currently installed.)
Removing ubuntu-server (1.450.2) ...
Removing update-notifier-common (3.192.30.11) ...
Removing update-manager-core (1:20.04.10.10) ...
Removing ubuntu-release-upgrader-core (1:20.04.39) ...
Processing triggers for man-db (2.9.1-1) ...
(Reading database ... 37901 files and directories currently installed.)
Purging configuration files for update-notifier-common (3.192.30.11) ...
Purging configuration files for ubuntu-release-upgrader-core (1:20.04.39) ...
dpkg: warning: while removing ubuntu-release-upgrader-core, directory '/var/lib/update-notifier' not empty so not removed
root@mycontainer:~# rm -rf /var/lib/update-notifier/
root@mycontainer:~# ls -l /var/lib/update-notifier
ls: cannot access '/var/lib/update-notifier': No such file or directory
```

Even after removing the above packages, I still get "dataset is busy" when attempting to delete the container. I think the problem is the item in the delete queue is pre-existing and not at all related to the other files in the same directory (e.g. it's just an inode, not at all associated with the other remaining inodes left in `/var/lib/update-notifier`) so removing the directory and remaining files at this point has no effect. If there was a way to try the above with cloud-init *before* `package_update: true` runs, that would be worth a try but I'm not sure how to do that.

**Comment by amartin3225** [comment] 2022-12-07 16:54
One more data point that might provide a clue as to the source of this problem - normally these datasets which are stuck as "dataset is busy" can be fixed by simply rebooting (e.g. after rebooting I can run `zfs destroy lxd/containers/mycontainer` and it will work). However, I came across one dataset that continues to return "dataset is busy" even after multiple reboots. I then tried masking the snapd and LXD services, rebooting again so that these services will not have been started during the current boot, and I was immediately able to delete the dataset:
```
myhost ~ # zfs destroy -r lxd/containers/mycontainer3
cannot destroy 'lxd/containers/mycontainer3': dataset is busy

myhost ~ # systemctl mask snapd.service
Created symlink /etc/systemd/system/snapd.service → /dev/null.
myhost ~ # systemctl mask snapd.seeded.service
Created symlink /etc/systemd/system/snapd.seeded.service → /dev/null.
myhost ~ # systemctl mask snapd.apparmor.service
Created symlink /etc/systemd/system/snapd.apparmor.service → /dev/null.
myhost ~ # systemctl mask snap.lxd.workaround.service
Created symlink /etc/systemd/system/snap.lxd.workaround.service → /dev/null.
myhost ~ # systemctl disable snap.lxd.daemon.service

myhost ~ # reboot
Connection to myhost closed by remote host.
Connection to myhost closed.
 $ ssh root@myhost
Welcome to Ubuntu 20.04.1 LTS ....
myhost ~ # zfs destroy -r lxd/containers/mycontainer3
myhost ~ #
```

This seems to indicate that some part of the snapd or lxd.snap.daemon processes is what is holding the ZFS dataset open and preventing it from being destroyed.

**Comment by amartin3225** [comment] 2022-12-15 12:59
Additional work with bpftrace indicates that the EBUSY is coming from [dsl_destroy_head_check_impl()](https://github.com/openzfs/zfs/blob/master/module/zfs/dsl_destroy.c#L764) but I have been unsuccessful in attempting to compile a custom version of ZFS with `printk`s throughout this function to learn more.

As an alternative, I removed the snap version of LXD and installed [Debian's apt version of LXD](https://wiki.debian.org/LXD) and was unable to reproduce this problem using the apt package. This seems to confirm that the problem has something to do with how snapd interacts with LXD.

**Comment by tomponline** [comment] 2023-01-05 08:23
As this appears to be related to the snap/ZFS issue https://github.com/lxc/lxd-pkg-snap/issues/61 as it cannot be reproduced when not using the snap, I'll close this one.

**Closed by tomponline** 2023-01-05 08:23 UTC
Labels: Incomplete

**Comment by amartin3225** [comment] 2023-01-05 15:23
We've identified the antivirus program present on these systems as the reason this occurs; it adds a kernel module that must do some type of analysis of system calls or filesystem access which appears to dramatically slow down LXD container creation and also must be holding open files in the ZFS dataset (thus keeping the dataset "busy"). Disabling this kernel module resolves the problem, so it seems that picking an antivirus program that is specifically aware of containers or ZFS is the solution. Thanks for all of the help.

**Comment by kamzar1** [comment] 2023-02-25 14:06
Host: Ubuntu 22.04
lxd     5.11-ad0b61e  24483  latest/stable

```
lxc launch ubuntu:22.04 Jam1 --vm
lxc delete --force Jam1
```

Error: Error deleting storage volume: Failed to run: zfs destroy -r zp3/pl2/virtual-machines/303_Jam1.block: exit status 1 (cannot destroy 'zp3/pl2/virtual-machines/303_Jam1.block': dataset is busy)
@tomponline 
"As this appears to be related to the snap/ZFS issue"
Are there any other mode of LXD around, beside heavilly promoted snap?
This keeps happening and reboot a production server is not a solution.

**Comment by tomponline** [comment] 2023-02-26 18:35
Please shiw sudo zfs list output?

**Comment by tomponline** [comment] 2023-02-26 18:36
> This keeps happening and reboot a production server is not a solution.

Agreed, but without reproducer we haven't been able to fix it.

**Comment by tomponline** [comment] 2023-02-26 18:38
> Are there any other mode of LXD around, beside heavilly promoted snap?

This only affects zfs pools. But not all zfs pools as try aa we might we cannot reproduce it.

**Comment by justinclift** [comment] 2023-09-02 06:07
Investigating this problem a bit now, and have narrowed things down quite a lot.

(It's affecting the containers on some of our Ubuntu 20.04 production hosts. :wink:)

The behaviour is the same as others have reported:

```
# lxc rm demo
Error: Error deleting storage volume: Failed to run: zfs destroy -r pool1/lxd/containers/demo: exit status 1 (cannot destroy 'pool1/lxd/containers/demo': dataset is busy)
```

The ZFS dataset in question:

```
# zfs list pool1/lxd/containers/demo
NAME                        USED  AVAIL     REFER  MOUNTPOINT
pool1/lxd/containers/demo  27.8G   594G     28.1G  legacy
```

The container itself is in the `STOPPED` state, and has been for weeks:

```
# lxc list demo
+------+---------+------+------+-----------+-----------+
| NAME |  STATE  | IPV4 | IPV6 |   TYPE    | SNAPSHOTS |
+------+---------+------+------+-----------+-----------+
| demo | STOPPED |      |      | CONTAINER | 0         |
+------+---------+------+------+-----------+-----------+
```

From the many, many similar issues others have reported, it looks to be useful checking whether the dataset is (somehow) mounted by anything:

```
# grep demo /proc/*/mounts
/proc/1775731/mounts:pool1/lxd/containers/demo /var/snap/lxd/common/lxd/storage-pools/default/containers/demo zfs rw,relatime,xattr,posixacl 0 0
/proc/1776914/mounts:pool1/lxd/containers/demo /var/snap/lxd/common/lxd/storage-pools/default/containers/demo zfs rw,relatime,xattr,posixacl 0 0
/proc/1777641/mounts:pool1/lxd/containers/demo /var/snap/lxd/common/lxd/storage-pools/default/containers/demo zfs rw,relatime,xattr,posixacl 0 0
/proc/1778397/mounts:pool1/lxd/containers/demo /var/snap/lxd/common/lxd/storage-pools/default/containers/demo zfs rw,relatime,xattr,posixacl 0 0
```

Yep, it is.  There are four processes where it's still mounted, which is clearly the problem.  

Checking what those processes are sheds some light:

```
# ps -ef | grep "1775731\|1776914\|1777641\|1778397"
root     1775731       1  0 Mar05 ?        13:29:44 lxcfs /var/snap/lxd/common/var/lib/lxcfs -p /var/snap/lxd/common/lxcfs.pid
root     1776914       1  0 Mar05 ?        00:00:00 [lxc monitor] /var/snap/lxd/common/lxd/containers customerA
root     1777641       1  0 Mar05 ?        00:00:00 [lxc monitor] /var/snap/lxd/common/lxd/containers customerB
root     1778397       1  0 Mar05 ?        00:00:00 [lxc monitor] /var/snap/lxd/common/lxd/containers customerC
```

At least the `lxc monitor` process for *other* containers is somehow mounting it, as well as one instance of `lxcfs`.

Looking at the mount list for one of those shows it's indeed mounting *all* of the available containers:

```
# cat /proc/1776914/mounts | grep lxd/containers
pool1/lxd/containers/customerA /var/snap/lxd/common/lxd/storage-pools/default/containers/customerA zfs rw,relatime,xattr,posixacl 0 0
pool1/lxd/containers/demo /var/snap/lxd/common/lxd/storage-pools/default/containers/demo zfs rw,relatime,xattr,posixacl 0 0
pool1/lxd/containers/customerB /var/snap/lxd/common/lxd/storage-pools/default/containers/customerB zfs rw,relatime,xattr,posixacl 0 0
pool1/lxd/containers/customerC /var/snap/lxd/common/lxd/storage-pools/default/containers/customerC zfs rw,relatime,xattr,posixacl 0 0
pool1/lxd/containers/customerD /var/snap/lxd/common/lxd/storage-pools/default/containers/customerD zfs rw,relatime,xattr,posixacl 0 0
```

Checking the other `lxcfs` and `lxc monitor` processes, they're all indeed doing the same thing.

This seems like some form of bug with how `lxcfs`/`lxc monitor` are deciding what to mount.  Instead of narrowly mounting things for just their particular container, they're each mounting *all* of the LXD datasets.

Which naturally leads to the issue we're seeing, and others have reported.

Version wise, this is happening with LXD 5.17 on Ubuntu 20.04:

```
# snap list
Name    Version       Rev    Tracking       Publisher   Notes
core20  20230801      2015   latest/stable  canonical✓  base
core22  20230801      864    latest/stable  canonical✓  base
lxd     5.17-e5ead86  25505  latest/stable  canonical✓  -
snapd   2.60.3        20092  latest/stable  canonical✓  snapd
```

This specific production box has been online for quite a while though, so snap is likely to have auto-upgraded lxd several times.  Those actual running processes were started back in March, so I'm unsure what version they're actually running.

Anyone have thoughts?

**Comment by justinclift** [comment] 2023-09-02 06:20
Interesting, umounting the dataset from just a single one of those namespaces seems to have triggered the others to also unmount it.

Doing the unmount:

```
# nsenter -t 1776914 -m -- bash
/ # mount | grep demo
pool1/lxd/containers/demo on /var/snap/lxd/common/lxd/storage-pools/default/containers/demo type zfs (rw,relatime,xattr,posixacl)
/ # umount pool1/lxd/containers/demo
/ # exit
```

And now it's gone from *all* of the processes:

```
# grep demo /proc/*/mounts
#
```

That's almost like those processes were all sharing the same namespace.  Weird?

Anyway, removing the stopped container now works:

```
# lxc rm demo
```

And zfs list no longer has the dataset.  Seems like a win. :smile:

**Comment by tomponline** [comment] 2023-09-04 07:17
@justinclift if you have a reproducer for this issue we can reopen and investigate.

**Comment by justinclift** [comment] 2023-09-04 07:54
@tomponline No reproducer for it yet.  We just occasionally see this happening on our longer running production servers (currently all Ubuntu 20.04).

It doesn't happen often enough for us to get really upset about it (so far), as it seems fixable by going through the above process.
