### ISSUE TITLE
UNIX socket availability right after installing LXD from snap

### ISSUE THREAD

**Issue by fnordahl** [lxc/lxd#4265] opened 2018-02-21 00:08 UTC
# Required information

 * Distribution: Ubuntu
 * Distribution version: Trusty (on Travis CI)
 
# Issue description

Directly after installing LXD from a snap the UNIX socket is not available for communication with LXD. This is a difference in behavior from installing from the deb.

You can view changes required to my Travis LXD setup to make this work [here](https://github.com/fnordahl/travis-lxd/commit/7b5b39f9d0f862a6322a9d3a418f4c9bbe79c6a7).

# Steps to reproduce

 1. Install lxd from snap
 2. Immediately attempt to communicate with the LXD socket (run sudo lxd init for example)
 3. Observe that socket communication fails
 1. Install lxd from deb
 2. Immediately attempt to communicate with the LXD socket (run sudo lxd init for example)
 3. Observe that socket communication succeeds

# Information to attach
 * Full output from test-run can be viewed [here](https://travis-ci.org/fnordahl/flux-capacitor/builds/344097604).
 * The output of "lxc info"
```
$ sudo su travis -c 'lxc info --debug'
If this is your first time running LXD on this machine, you should also run: lxd init
To start your first container, try: lxc launch ubuntu:16.04
DBUG[02-21|00:04:00] Connecting to a local LXD over a Unix socket 
DBUG[02-21|00:04:00] Sending request to LXD                   etag= method=GET url=http://unix.socket/1.0
DBUG[02-21|00:04:00] Got response struct from LXD 
DBUG[02-21|00:04:00] 
	{
		"config": {},
		"api_extensions": [
			"storage_zfs_remove_snapshots",
			"container_host_shutdown_timeout",
			"container_stop_priority",
			"container_syscall_filtering",
			"auth_pki",
			"container_last_used_at",
			"etag",
			"patch",
			"usb_devices",
			"https_allowed_credentials",
			"image_compression_algorithm",
			"directory_manipulation",
			"container_cpu_time",
			"storage_zfs_use_refquota",
			"storage_lvm_mount_options",
			"network",
			"profile_usedby",
			"container_push",
			"container_exec_recording",
			"certificate_update",
			"container_exec_signal_handling",
			"gpu_devices",
			"container_image_properties",
			"migration_progress",
			"id_map",
			"network_firewall_filtering",
			"network_routes",
			"storage",
			"file_delete",
			"file_append",
			"network_dhcp_expiry",
			"storage_lvm_vg_rename",
			"storage_lvm_thinpool_rename",
			"network_vlan",
			"image_create_aliases",
			"container_stateless_copy",
			"container_only_migration",
			"storage_zfs_clone_copy",
			"unix_device_rename",
			"storage_lvm_use_thinpool",
			"storage_rsync_bwlimit",
			"network_vxlan_interface",
			"storage_btrfs_mount_options",
			"entity_description",
			"image_force_refresh",
			"storage_lvm_lv_resizing",
			"id_map_base",
			"file_symlinks",
			"container_push_target",
			"network_vlan_physical",
			"storage_images_delete",
			"container_edit_metadata",
			"container_snapshot_stateful_migration",
			"storage_driver_ceph",
			"storage_ceph_user_name",
			"resource_limits",
			"storage_volatile_initial_source",
			"storage_ceph_force_osd_reuse",
			"storage_block_filesystem_btrfs",
			"resources",
			"kernel_limits",
			"storage_api_volume_rename",
			"macaroon_authentication",
			"network_sriov",
			"console",
			"restrict_devlxd",
			"migration_pre_copy",
			"infiniband",
			"maas_network"
		],
		"api_status": "stable",
		"api_version": "1.0",
		"auth": "trusted",
		"public": false,
		"auth_methods": [
			"tls"
		],
		"environment": {
			"addresses": [],
			"architectures": [
				"x86_64",
				"i686"
			],
			"certificate": "-----BEGIN CERTIFICATE-----\nMIIFwjCCA6qgAwIBAgIRAMKZfgbx3aNT0WUfn3i9yw8wDQYJKoZIhvcNAQELBQAw\nXTEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzE9MDsGA1UEAww0cm9vdEB0\ncmF2aXMtam9iLTA2ZDNiNDlhLTdhNDMtNDIxYy05ZGQxLWM2YjhjYTgyYmY4MDAe\nFw0xODAyMjEwMDA0MDBaFw0yODAyMTkwMDA0MDBaMF0xHDAaBgNVBAoTE2xpbnV4\nY29udGFpbmVycy5vcmcxPTA7BgNVBAMMNHJvb3RAdHJhdmlzLWpvYi0wNmQzYjQ5\nYS03YTQzLTQyMWMtOWRkMS1jNmI4Y2E4MmJmODAwggIiMA0GCSqGSIb3DQEBAQUA\nA4ICDwAwggIKAoICAQC3V4v1TuhrKDEKp1ZgsJ9cUXZSXWQb3IYGh+YPi/HloPlQ\nr3KCsRg2IQEce9KNMOPFrLEouZMYfdyhk5hsROFa3SADHg2ajHRaku+5J+chEA6C\nWcymhAI8kKflXucL7QBeeb6KeFL6cMEG+LRPfe3o709MhnynuHP8kRZtfl6Gpfxd\nYo2V1xAaVOBHWyiG4N1VWNQo7QWwMv8TNOK2TtrJXUisXVfIoDN9zzl24DFeiQ4D\njkv3vB7VvH1EA5EwE3JKuSyZ79k0Dn7qe3pciBBgn34fUsQ6kFoUMuGzy2BWkgkG\nRr7dv42eUmyWvyBBf5h91dCTWloqEYd7IJ89DY/qczuLc3FLHn7r4cs4jtHUZP+4\ncTMyf+xOXIQxV6XMJ5j65qTpvEf64+yZaUVkNF/8RNzrxJKO5TqisdY1KNWlS0Nc\nS2lxV1ZeCJPhjzHybHEK0baJbULTVRi2JJsxCF7ZfC3SCK3DLGUB+KtGeIvb/0HQ\ncMz1a6YUAIVLECMw+Yd1l9JRzYCrqItxCYEOs2UD9Yx18RnMCd/hxuWCixl4fY2g\n9n9nWtQEsUvyco7hd9b3y0aF1c9MOrs+J2klX3Rt3nUGqgdiKNyARMH+fJxzb/N2\nI2yYlkf48Azs5tuaerO2/HiGBdmSTqP+fViuTDowbc2W/GSyKAG7iwn2N583LQID\nAQABo30wezAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYD\nVR0TAQH/BAIwADBGBgNVHREEPzA9gi90cmF2aXMtam9iLTA2ZDNiNDlhLTdhNDMt\nNDIxYy05ZGQxLWM2YjhjYTgyYmY4MIcEChQAOocErBEAATANBgkqhkiG9w0BAQsF\nAAOCAgEAC4jTA+Y5J8gTUCy4hkx61b/0vmR6Rdfh76BMcqjziEtExeGjT6x0Io4R\naWYQ0pYYdifFFj7oWJsdiY7eisgfcaVsraF94UKzjhPb5UO8oYrVhhUdP96JZm1W\nqcjhM+u+7IYIEQlWq0lFCSgOhuX/lggEtthBOyHw7ppGckQIinHGo5Yy6TxohZxR\nrcMDmB69OASVU7OXz8ha7vSvrpnz31YZxBMGmv8Ce3EMSA7njoqmnI2qf7GtheX0\nfzi8kLobaE4S0aRf/mhlyOBnHMCiNNbhhyPDFpiji0LNLbX87lCCcau09yIWA3+y\n6/V4EfSpsPIkOEyQFglcf1ZGgHATMPNlqg6kI/DqLtxVHDyL8HSsrsK6d5KxcSF2\nj4F+WR0lFg/oub6GX/Z1ISnjtd0vftL7cTmFdDEHOZKyXmvfFwf8XrfsFL8umeUs\n2K6Vy3PODKr74xM+qWUzKscsAeW7sRL0IHOSOQ50vyvlm0nBohfwcGkFx7N1CCnF\nljraCWZAsUfNt/ELICzfHkxxFyno2ZtbBVngbXeThXphLrPa643ogRXJmQgOrKa9\n1LXleEsXPXP1QVxvjh+XZOcS6LbGZoESkRUkE7l1tLhPbv94rF35hMgLeUbtsB6r\n63UUJvalXDNkbokVJLYxJmdbkCNs2ZJsL54MuCk4xa5iPb/Bi7I=\n-----END CERTIFICATE-----\n",
			"certificate_fingerprint": "851e00c8207aac3c393ae7c6e7952fe5cdbb42f70a12a4289bb7c7600a357036",
			"driver": "lxc",
			"driver_version": "2.1.1",
			"kernel": "Linux",
			"kernel_architecture": "x86_64",
			"kernel_version": "4.4.0-101-generic",
			"server": "lxd",
			"server_pid": 25899,
			"server_version": "2.21",
			"storage": "",
			"storage_version": ""
		}
	} 
DBUG[02-21|00:04:00] Sending request to LXD                   etag= method=GET url=http://unix.socket/1.0
DBUG[02-21|00:04:00] Got response struct from LXD 
DBUG[02-21|00:04:00] 
	{
		"config": {},
		"api_extensions": [
			"storage_zfs_remove_snapshots",
			"container_host_shutdown_timeout",
			"container_stop_priority",
			"container_syscall_filtering",
			"auth_pki",
			"container_last_used_at",
			"etag",
			"patch",
			"usb_devices",
			"https_allowed_credentials",
			"image_compression_algorithm",
			"directory_manipulation",
			"container_cpu_time",
			"storage_zfs_use_refquota",
			"storage_lvm_mount_options",
			"network",
			"profile_usedby",
			"container_push",
			"container_exec_recording",
			"certificate_update",
			"container_exec_signal_handling",
			"gpu_devices",
			"container_image_properties",
			"migration_progress",
			"id_map",
			"network_firewall_filtering",
			"network_routes",
			"storage",
			"file_delete",
			"file_append",
			"network_dhcp_expiry",
			"storage_lvm_vg_rename",
			"storage_lvm_thinpool_rename",
			"network_vlan",
			"image_create_aliases",
			"container_stateless_copy",
			"container_only_migration",
			"storage_zfs_clone_copy",
			"unix_device_rename",
			"storage_lvm_use_thinpool",
			"storage_rsync_bwlimit",
			"network_vxlan_interface",
			"storage_btrfs_mount_options",
			"entity_description",
			"image_force_refresh",
			"storage_lvm_lv_resizing",
			"id_map_base",
			"file_symlinks",
			"container_push_target",
			"network_vlan_physical",
			"storage_images_delete",
			"container_edit_metadata",
			"container_snapshot_stateful_migration",
			"storage_driver_ceph",
			"storage_ceph_user_name",
			"resource_limits",
			"storage_volatile_initial_source",
			"storage_ceph_force_osd_reuse",
			"storage_block_filesystem_btrfs",
			"resources",
			"kernel_limits",
			"storage_api_volume_rename",
			"macaroon_authentication",
			"network_sriov",
			"console",
			"restrict_devlxd",
			"migration_pre_copy",
			"infiniband",
			"maas_network"
		],
		"api_status": "stable",
		"api_version": "1.0",
		"auth": "trusted",
		"public": false,
		"auth_methods": [
			"tls"
		],
		"environment": {
			"addresses": [],
			"architectures": [
				"x86_64",
				"i686"
			],
			"certificate": "-----BEGIN CERTIFICATE-----\nMIIFwjCCA6qgAwIBAgIRAMKZfgbx3aNT0WUfn3i9yw8wDQYJKoZIhvcNAQELBQAw\nXTEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzE9MDsGA1UEAww0cm9vdEB0\ncmF2aXMtam9iLTA2ZDNiNDlhLTdhNDMtNDIxYy05ZGQxLWM2YjhjYTgyYmY4MDAe\nFw0xODAyMjEwMDA0MDBaFw0yODAyMTkwMDA0MDBaMF0xHDAaBgNVBAoTE2xpbnV4\nY29udGFpbmVycy5vcmcxPTA7BgNVBAMMNHJvb3RAdHJhdmlzLWpvYi0wNmQzYjQ5\nYS03YTQzLTQyMWMtOWRkMS1jNmI4Y2E4MmJmODAwggIiMA0GCSqGSIb3DQEBAQUA\nA4ICDwAwggIKAoICAQC3V4v1TuhrKDEKp1ZgsJ9cUXZSXWQb3IYGh+YPi/HloPlQ\nr3KCsRg2IQEce9KNMOPFrLEouZMYfdyhk5hsROFa3SADHg2ajHRaku+5J+chEA6C\nWcymhAI8kKflXucL7QBeeb6KeFL6cMEG+LRPfe3o709MhnynuHP8kRZtfl6Gpfxd\nYo2V1xAaVOBHWyiG4N1VWNQo7QWwMv8TNOK2TtrJXUisXVfIoDN9zzl24DFeiQ4D\njkv3vB7VvH1EA5EwE3JKuSyZ79k0Dn7qe3pciBBgn34fUsQ6kFoUMuGzy2BWkgkG\nRr7dv42eUmyWvyBBf5h91dCTWloqEYd7IJ89DY/qczuLc3FLHn7r4cs4jtHUZP+4\ncTMyf+xOXIQxV6XMJ5j65qTpvEf64+yZaUVkNF/8RNzrxJKO5TqisdY1KNWlS0Nc\nS2lxV1ZeCJPhjzHybHEK0baJbULTVRi2JJsxCF7ZfC3SCK3DLGUB+KtGeIvb/0HQ\ncMz1a6YUAIVLECMw+Yd1l9JRzYCrqItxCYEOs2UD9Yx18RnMCd/hxuWCixl4fY2g\n9n9nWtQEsUvyco7hd9b3y0aF1c9MOrs+J2klX3Rt3nUGqgdiKNyARMH+fJxzb/N2\nI2yYlkf48Azs5tuaerO2/HiGBdmSTqP+fViuTDowbc2W/GSyKAG7iwn2N583LQID\nAQABo30wezAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYD\nVR0TAQH/BAIwADBGBgNVHREEPzA9gi90cmF2aXMtam9iLTA2ZDNiNDlhLTdhNDMt\nNDIxYy05ZGQxLWM2YjhjYTgyYmY4MIcEChQAOocErBEAATANBgkqhkiG9w0BAQsF\nAAOCAgEAC4jTA+Y5J8gTUCy4hkx61b/0vmR6Rdfh76BMcqjziEtExeGjT6x0Io4R\naWYQ0pYYdifFFj7oWJsdiY7eisgfcaVsraF94UKzjhPb5UO8oYrVhhUdP96JZm1W\nqcjhM+u+7IYIEQlWq0lFCSgOhuX/lggEtthBOyHw7ppGckQIinHGo5Yy6TxohZxR\nrcMDmB69OASVU7OXz8ha7vSvrpnz31YZxBMGmv8Ce3EMSA7njoqmnI2qf7GtheX0\nfzi8kLobaE4S0aRf/mhlyOBnHMCiNNbhhyPDFpiji0LNLbX87lCCcau09yIWA3+y\n6/V4EfSpsPIkOEyQFglcf1ZGgHATMPNlqg6kI/DqLtxVHDyL8HSsrsK6d5KxcSF2\nj4F+WR0lFg/oub6GX/Z1ISnjtd0vftL7cTmFdDEHOZKyXmvfFwf8XrfsFL8umeUs\n2K6Vy3PODKr74xM+qWUzKscsAeW7sRL0IHOSOQ50vyvlm0nBohfwcGkFx7N1CCnF\nljraCWZAsUfNt/ELICzfHkxxFyno2ZtbBVngbXeThXphLrPa643ogRXJmQgOrKa9\n1LXleEsXPXP1QVxvjh+XZOcS6LbGZoESkRUkE7l1tLhPbv94rF35hMgLeUbtsB6r\n63UUJvalXDNkbokVJLYxJmdbkCNs2ZJsL54MuCk4xa5iPb/Bi7I=\n-----END CERTIFICATE-----\n",
			"certificate_fingerprint": "851e00c8207aac3c393ae7c6e7952fe5cdbb42f70a12a4289bb7c7600a357036",
			"driver": "lxc",
			"driver_version": "2.1.1",
			"kernel": "Linux",
			"kernel_architecture": "x86_64",
			"kernel_version": "4.4.0-101-generic",
			"server": "lxd",
			"server_pid": 25899,
			"server_version": "2.21",
			"storage": "",
			"storage_version": ""
		}
	} 
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFwjCCA6qgAwIBAgIRAMKZfgbx3aNT0WUfn3i9yw8wDQYJKoZIhvcNAQELBQAw
    XTEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzE9MDsGA1UEAww0cm9vdEB0
    cmF2aXMtam9iLTA2ZDNiNDlhLTdhNDMtNDIxYy05ZGQxLWM2YjhjYTgyYmY4MDAe
    Fw0xODAyMjEwMDA0MDBaFw0yODAyMTkwMDA0MDBaMF0xHDAaBgNVBAoTE2xpbnV4
    Y29udGFpbmVycy5vcmcxPTA7BgNVBAMMNHJvb3RAdHJhdmlzLWpvYi0wNmQzYjQ5
    YS03YTQzLTQyMWMtOWRkMS1jNmI4Y2E4MmJmODAwggIiMA0GCSqGSIb3DQEBAQUA
    A4ICDwAwggIKAoICAQC3V4v1TuhrKDEKp1ZgsJ9cUXZSXWQb3IYGh+YPi/HloPlQ
    r3KCsRg2IQEce9KNMOPFrLEouZMYfdyhk5hsROFa3SADHg2ajHRaku+5J+chEA6C
    WcymhAI8kKflXucL7QBeeb6KeFL6cMEG+LRPfe3o709MhnynuHP8kRZtfl6Gpfxd
    Yo2V1xAaVOBHWyiG4N1VWNQo7QWwMv8TNOK2TtrJXUisXVfIoDN9zzl24DFeiQ4D
    jkv3vB7VvH1EA5EwE3JKuSyZ79k0Dn7qe3pciBBgn34fUsQ6kFoUMuGzy2BWkgkG
    Rr7dv42eUmyWvyBBf5h91dCTWloqEYd7IJ89DY/qczuLc3FLHn7r4cs4jtHUZP+4
    cTMyf+xOXIQxV6XMJ5j65qTpvEf64+yZaUVkNF/8RNzrxJKO5TqisdY1KNWlS0Nc
    S2lxV1ZeCJPhjzHybHEK0baJbULTVRi2JJsxCF7ZfC3SCK3DLGUB+KtGeIvb/0HQ
    cMz1a6YUAIVLECMw+Yd1l9JRzYCrqItxCYEOs2UD9Yx18RnMCd/hxuWCixl4fY2g
    9n9nWtQEsUvyco7hd9b3y0aF1c9MOrs+J2klX3Rt3nUGqgdiKNyARMH+fJxzb/N2
    I2yYlkf48Azs5tuaerO2/HiGBdmSTqP+fViuTDowbc2W/GSyKAG7iwn2N583LQID
    AQABo30wezAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYD
    VR0TAQH/BAIwADBGBgNVHREEPzA9gi90cmF2aXMtam9iLTA2ZDNiNDlhLTdhNDMt
    NDIxYy05ZGQxLWM2YjhjYTgyYmY4MIcEChQAOocErBEAATANBgkqhkiG9w0BAQsF
    AAOCAgEAC4jTA+Y5J8gTUCy4hkx61b/0vmR6Rdfh76BMcqjziEtExeGjT6x0Io4R
    aWYQ0pYYdifFFj7oWJsdiY7eisgfcaVsraF94UKzjhPb5UO8oYrVhhUdP96JZm1W
    qcjhM+u+7IYIEQlWq0lFCSgOhuX/lggEtthBOyHw7ppGckQIinHGo5Yy6TxohZxR
    rcMDmB69OASVU7OXz8ha7vSvrpnz31YZxBMGmv8Ce3EMSA7njoqmnI2qf7GtheX0
    fzi8kLobaE4S0aRf/mhlyOBnHMCiNNbhhyPDFpiji0LNLbX87lCCcau09yIWA3+y
    6/V4EfSpsPIkOEyQFglcf1ZGgHATMPNlqg6kI/DqLtxVHDyL8HSsrsK6d5KxcSF2
    j4F+WR0lFg/oub6GX/Z1ISnjtd0vftL7cTmFdDEHOZKyXmvfFwf8XrfsFL8umeUs
    2K6Vy3PODKr74xM+qWUzKscsAeW7sRL0IHOSOQ50vyvlm0nBohfwcGkFx7N1CCnF
    ljraCWZAsUfNt/ELICzfHkxxFyno2ZtbBVngbXeThXphLrPa643ogRXJmQgOrKa9
    1LXleEsXPXP1QVxvjh+XZOcS6LbGZoESkRUkE7l1tLhPbv94rF35hMgLeUbtsB6r
    63UUJvalXDNkbokVJLYxJmdbkCNs2ZJsL54MuCk4xa5iPb/Bi7I=
    -----END CERTIFICATE-----
  certificate_fingerprint: 851e00c8207aac3c393ae7c6e7952fe5cdbb42f70a12a4289bb7c7600a357036
  driver: lxc
  driver_version: 2.1.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-101-generic
  server: lxd
  server_pid: 25899
  server_version: "2.21"
  storage: ""
  storage_version: ""
```
 - [X] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
```
$ sudo cat /var/snap/lxd/common/lxd/logs/lxd.log
lvl=info msg="LXD 2.21 is starting in normal mode" path=/var/snap/lxd/common/lxd t=2018-02-21T00:03:59+0000
lvl=info msg="Kernel uid/gid map:" t=2018-02-21T00:03:59+0000
lvl=info msg=" - u 0 0 4294967295" t=2018-02-21T00:03:59+0000
lvl=info msg=" - g 0 0 4294967295" t=2018-02-21T00:03:59+0000
lvl=info msg="Configured LXD uid/gid map:" t=2018-02-21T00:03:59+0000
lvl=info msg=" - u 0 1000000 1000000000" t=2018-02-21T00:03:59+0000
lvl=info msg=" - g 0 1000000 1000000000" t=2018-02-21T00:03:59+0000
lvl=warn msg="AppArmor support has been disabled because of lack of kernel support" t=2018-02-21T00:03:59+0000
lvl=info msg="LXD isn't socket activated" t=2018-02-21T00:04:00+0000
lvl=info msg="Starting /dev/lxd handler:" t=2018-02-21T00:04:00+0000
lvl=info msg=" - binding devlxd socket" socket=/var/snap/lxd/common/lxd/devlxd/sock t=2018-02-21T00:04:00+0000
lvl=info msg="REST API daemon:" t=2018-02-21T00:04:00+0000
lvl=info msg=" - binding Unix socket" socket=/var/snap/lxd/common/lxd/unix.socket t=2018-02-21T00:04:00+0000
lvl=info msg="Pruning expired images" t=2018-02-21T00:04:00+0000
lvl=info msg="Done pruning expired images" t=2018-02-21T00:04:00+0000
lvl=info msg="Expiring log files" t=2018-02-21T00:04:00+0000
lvl=info msg="Done expiring log files" t=2018-02-21T00:04:00+0000
lvl=info msg="Updating instance types" t=2018-02-21T00:04:00+0000
lvl=info msg="Updating images" t=2018-02-21T00:04:00+0000
lvl=info msg="Done updating images" t=2018-02-21T00:04:00+0000
```
 - [X] Output of the client with --debug
```
$ sudo su travis -c 'lxc info --debug'
DBUG[02-21|00:03:56] Connecting to a local LXD over a Unix socket 
DBUG[02-21|00:03:56] Sending request to LXD                   etag= method=GET url=http://unix.socket/1.0
LXD socket not found; is LXD installed and running?
```

**Comment by stgraber** [comment] 2018-02-21 00:32
Yeah, that's caused by a difference on how systemd units are handled. As snapd itself generates our systemd unit, there's not a great deal we can do.

Once socket activation support is fully landed on all distributions we care about and in snapcraft, then we should be able to use the same setup we had with the deb, avoiding that period of time where lxd is starting but not yet listening on the socket.

Until then, if scripting LXD, you can workaround this by calling `lxd waitready` in your script, which will effectively poll the socket for you until it's ready and then return.

Closing as not a LXD issue but a snapd limitation that we've been pushing to fix for a while now.

**Closed by stgraber** 2018-02-21 00:32 UTC

**Comment by fnordahl** [comment] 2018-02-21 08:09
I did not know about `lxd waitready`, thank you for enlightening me!
