### ISSUE TITLE
Apparmor warnings with LXD snap

### ISSUE THREAD

**Issue by markshuttle** [lxc/lxd#3662] opened 2017-08-15 06:48 UTC
Using the LXD snap on Ubuntu 17.10 I see these:

Warning from /var/lib/snapd/apparmor/profiles/snap.lxd.benchmark (/var/lib/snapd/apparmor/profiles/snap.lxd.benchmark line 389): Unconfined exec qualifier (ux) allows some dangerous environment variables to be passed to the unconfined process; 'man 5 apparmor.d' for details.
Warning from /var/lib/snapd/apparmor/profiles/snap.lxd.check-kernel (/var/lib/snapd/apparmor/profiles/snap.lxd.check-kernel line 389): Unconfined exec qualifier (ux) allows some dangerous environment variables to be passed to the unconfined process; 'man 5 apparmor.d' for details.
Warning from /var/lib/snapd/apparmor/profiles/snap.lxd.daemon (/var/lib/snapd/apparmor/profiles/snap.lxd.daemon line 389): Unconfined exec qualifier (ux) allows some dangerous environment variables to be passed to the unconfined process; 'man 5 apparmor.d' for details.
Warning from /var/lib/snapd/apparmor/profiles/snap.lxd.lxd (/var/lib/snapd/apparmor/profiles/snap.lxd.lxd line 389): Unconfined exec qualifier (ux) allows some dangerous environment variables to be passed to the unconfined process; 'man 5 apparmor.d' for details.

I suspect they are appropriate because of the unusually high level of privileges LXD requires. Nevertheless, since they are there by design, I wonder if these warnings should be shown? There's not much a user can do about them if they want LXD. In general, warnings make sense if the result is actionable. Otherwise, the system should have a policy which is defensible and warning-free.

**Comment by stgraber** [comment] 2017-08-15 15:38
Those warnings appear to come from the apparmor policy parser when applying the lxd-support interface which contains:
```
/usr/sbin/aa-exec ux,
```

I don't believe there's anything LXD or the LXD snap itself can do about this. Either we need to move the lxd-support interface away from "ux" which would prevent us from getting useful environment variables from snapd (LD_LIBRARY_PATH is one of them I believe) or change the apparmor parser so that it doesn't log those warnings in the first place.

@jdstrand what do you think is the best way to get rid of those aa-parser warnings?

**Comment by jdstrand** [comment] 2017-08-15 16:32
This is coming from the way snapd is calling apparmor_parser. Discussing this with @tyhicks, snapd should be made to made to pass '--quiet' unless SNAPD_DEBUG=1 is set. I'll take care of this.

**Comment by stgraber** [comment] 2017-08-15 16:37
Thanks @jdstrand.

Closing this issue since this was confirmed to be a snapd bug and will be fixed over there.

**Closed by stgraber** 2017-08-15 16:37 UTC
Labels: External
