### ISSUE TITLE
Running container suddenly producing config errors when using exec

### ISSUE THREAD

**Issue by bigjools** [lxc/lxd#2607] opened 2016-11-10 10:52 UTC
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-42-generic
   * LXC version: 2.0.5
   * LXD version: 2.5-0ubuntu1~ubuntu16.04.1~ppa1
   * Storage backend in use: directory

# Issue description

```
ed@li157-164:/etc/apache2$ lxc exec wordpress bash
error: Error opening startup config file: "loading config file for the container failed"

ed@li157-164:/etc/apache2$ lxc config show wordpress
name: wordpress
profiles:
- default
config:
  boot.autostart: "1"
  volatile.base_image: 615070e4260de515886f2368daeb4bd0d0cd84fe5b53bacacda0873492ccbd4e
  volatile.eth0.hwaddr: 00:16:3e:73:9e:2c
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
devices:
  root:
    path: /
    type: disk
ephemeral: false

```

# Steps to reproduce

No idea, this started happening on a previously-working container, which is still running. lxd was upgraded in the meantime from the version used for deployment but I can't recall which version.

# Information to attach

 - [ ] any relevant kernel output (dmesg)
 - [ ] container log (lxc info NAME --show-log)
 - [x ] main daemon log (/var/log/lxd.log)
```
t=2016-11-10T05:45:53-0500 lvl=info msg="Executing command" environment="[HOME=/root TERM=screen-bce USER=root PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin]" args="[/usr/bin/lxd forkexec wordpress /var/lib/lxd/containers /var/log/lxd/wordpress/lxc.conf -- env HOME=/root TERM=screen-bce USER=root PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin -- cmd bash]"
t=2016-11-10T05:45:53-0500 lvl=info msg="Executed command" exit_status=255 environment="[HOME=/root TERM=screen-bce USER=root PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin]" args="[/usr/bin/lxd forkexec wordpress /var/lib/lxd/containers /var/log/lxd/wordpress/lxc.conf -- env HOME=/root TERM=screen-bce USER=root PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin -- cmd bash]"
```
 - [ ] output of the client with --debug
 - [ ] output of the daemon with --debug

**Comment by tych0** [comment] 2016-11-10 13:04
On Thu, Nov 10, 2016 at 02:52:47AM -0800, bigjools wrote:
> 
> # Required information
> 
>  * Distribution: Ubuntu
>  * Distribution version: 16.04
>  * The output of "lxc info" or if that fails:
>    * Kernel version: 4.4.0-42-generic
>    * LXC version: 2.0.5
>    * LXD version: 2.5-0ubuntu1~ubuntu16.04.1~ppa1
>    * Storage backend in use: directory

Can you run the output of `lxc info`? I believe we know the cause of
this bug, but the output of `lxc info` would confirm.

Thanks!

**Comment by stgraber** [comment] 2016-11-10 13:07
And please do so BEFORE restarting LXD as we suspect that a LXD restart will fix the issue and prevent us from further debugging it.

**Comment by bigjools** [comment] 2016-11-10 22:39
I deliberately didn't restart anything just in case :)

```
apiextensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
apistatus: stable
apiversion: "1.0"
auth: trusted
environment:
  addresses: []
  architectures:
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIF8zCCA9ugAwIBAgIRAJMni0xVXx6OvHA2hBPy6E0wDQYJKoZIhvcNAQELBQAw
    NzEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEXMBUGA1UEAwwOcm9vdEBs
    aTE1Ny0xNjQwHhcNMTYxMDExMDAyMzEyWhcNMjYxMDA5MDAyMzEyWjA3MRwwGgYD
    VQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRcwFQYDVQQDDA5yb290QGxpMTU3LTE2
    NDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAMXbPE7Z4M9col2/y1Te
    rwXLs+KnDml8LqEZcpn0Oko0E/VytbYg7VU/maB/Kttfdj1vEvs6VfhPmnBdNxFB
    VZzo22O/qNf8n2Hd7uajcBflsSAAP+CMJI7UbYhzC6FQQErpbBzHJGgBy9sLiZgX
    pCzk8GbQ7DrIbQU4XtHTpES3KETFnWFqQ+YB4oYmnK+yhnBzwIqjWgDuIZ5rFyA3
    /M8eWGgbAzx3lIQqPysKfGTGnTpn7zufqF9aWemZ6lq4ZQC+WHcIHIzooT/3UIfU
    KDYYKAKBvXb89ZzxVy+9Q6vgLsQ/JWFs7N8iMj9FcFl9TznedXURrz/UhSDAPdNb
    quzToejEFfWq8W8vJdcceSVmEVySA9JEd/VRYjOKwL5L3xbgTC1ggSGqEgyMgBDZ
    iCXYxUpOmwNiOC2D5bgY7SZnhzmkwlXitsmxUVf9IbpP9jmEG+gFAUe1qwnpZ7mB
    BAHKQVatuvYwePiawem1dgip1f7qySTIyWlUYc8V2papOMvte99AFl65l+4EQO5b
    bNE8GpuAFWi4bSgq1VV6Dn0tygl23qWsx0wl20Y15IzZO3jgJtbB9/EAMqFKrxTN
    /Ssr6t1kcOoxXSf5VNDFvghqx+V+cg70TkdMT1IvgoWf56x6oJUdi5wDcXudlSQ/
    I4Ja6wqUbnCMfjy4d610/y1VAgMBAAGjgfkwgfYwDgYDVR0PAQH/BAQDAgWgMBMG
    A1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwgcAGA1UdEQSBuDCBtYIJ
    bGkxNTctMTY0ghIxNzMuMjMwLjE0Ny4xNjQvMjSCITI2MDA6M2MwMTo6ZjAzYzo5
    MWZmOmZlZGY6ZmQxYS82NIIcZmU4MDo6ZjAzYzo5MWZmOmZlZGY6ZmQxYS82NIIL
    MTAuOC4wLjEvMzKCHGZlODA6OjEwMjk6ZGFjZjpiNjE4OjVkNmQvNjSCHGZlODA6
    Ojc0NmM6NzdmZjpmZTRlOjI0M2YvNjSCCmZlODA6OjEvNjQwDQYJKoZIhvcNAQEL
    BQADggIBAEPG9F1LaFufjG70u6wY+1pUjA2ePysGX5Wu43kaTA7v+BXrUSkJzBmq
    +pZAausttsUy0J2d0RG3tOm6bu3tDv7dyzBssGFxVevEsX71zuHGw2UW6LnDQL3a
    Y8uZH+s7kqe9y40upoF5UkjoX56wdMhJRMAP6Fj3D0ubXmlmSqQd50K3HsTIz75U
    nbnv5QLPZVu1mlPHCCAW/cj/rHvnLGpNNXZ6XRpyclnFty1zoSNhRYepqKtcE0xi
    dYMSsAuEve45olN7wRFzrWLqE3vFTvOeooaJsxHSQKb1roiiWvZf0ggEFh0LZ/Wx
    tZYrTyfOyTdkAyKLoNfUfDYC2hNZmC6PwIFzZ+KsoOyuPJRQksXhyaUtt60/g4rS
    bDZvk/Xnfn8nqrrBXGq2PFKLfnOz/HThxjo4PFunwb8V6bV0LqSxEszchQIz3c3h
    gJSM/ahBmrhirMp350Y/BplNl3Dp1J3KSy9BD9kdxOn6UGYna380liFSObmSRa6z
    OHwl6xVlq1VCeJd0ev9gtgmGZjk3spQccmNLnVXRNQDiwYlLGzguem3fCXzLGBij
    lMykqnCmTs5S2J4tu/W34rEGX75plQqtNqRe99qsUAYADIFrdP+bQi1Jd5JIFgyR
    FUqfB8/bjtb+wdSTmyt/JLd3/+O8soKUXc2i5urp9S5Q+xYF6vN1
    -----END CERTIFICATE-----
  certificatefingerprint: d8aaa343915c695525c54591423e68eb946d60f0f92a162ec4286dfc0ebfa777
  driver: lxc
  driverversion: 2.0.5
  kernel: Linux
  kernelarchitecture: i686
  kernelversion: 4.4.0-42-generic
  server: lxd
  serverpid: 2879
  serverversion: 2.4.1
  storage: dir
  storageversion: ""
config: {}
public: false
```

**Comment by stgraber** [comment] 2016-11-11 10:28
Cool, so that confirms what we thought, for some reason, you're still running 2.4.1 despite having upgraded to 2.5. Can you attach /var/log/lxd/lxd.log and /var/log/dpkg.log?

It's going to be a packaging bug, hopefully I can figure it out with those two logs.

To fix your LXD, just run "systemctl restart lxd" and it'll come back up as 2.5 and the problem will be gone.

**Comment by bigjools** [comment] 2016-11-11 10:36
I'm not sure there's much in the lxd log, it's been rotated out from the pertinent time of when the package was installed on October 30 (yeah, I only just noticed this problem):

```
2016-10-30 07:16:33 configure lxd-client:i386 2.5-0ubuntu1~ubuntu16.04.1~ppa1 <none>
2016-10-30 07:16:33 status unpacked lxd-client:i386 2.5-0ubuntu1~ubuntu16.04.1~ppa1
2016-10-30 07:16:33 status half-configured lxd-client:i386 2.5-0ubuntu1~ubuntu16.04.1~ppa1
2016-10-30 07:16:33 status installed lxd-client:i386 2.5-0ubuntu1~ubuntu16.04.1~ppa1
2016-10-30 07:16:33 configure lxd:i386 2.5-0ubuntu1~ubuntu16.04.1~ppa1 <none>
2016-10-30 07:16:33 status unpacked lxd:i386 2.5-0ubuntu1~ubuntu16.04.1~ppa1
2016-10-30 07:16:33 status unpacked lxd:i386 2.5-0ubuntu1~ubuntu16.04.1~ppa1
2016-10-30 07:16:33 status unpacked lxd:i386 2.5-0ubuntu1~ubuntu16.04.1~ppa1
2016-10-30 07:16:33 status unpacked lxd:i386 2.5-0ubuntu1~ubuntu16.04.1~ppa1
2016-10-30 07:16:33 status unpacked lxd:i386 2.5-0ubuntu1~ubuntu16.04.1~ppa1
2016-10-30 07:16:33 status half-configured lxd:i386 2.5-0ubuntu1~ubuntu16.04.1~ppa1
2016-10-30 07:16:34 status installed lxd:i386 2.5-0ubuntu1~ubuntu16.04.1~ppa1
```

**Comment by stgraber** [comment] 2016-11-11 11:38
@bigjools what's odd in the log above is that there is no reference to the previous version (2.4.1). Is there some more context above this perhaps or was that rotated too?

**Comment by bigjools** [comment] 2016-11-11 11:43
My bad, sorry. Here's the reference to that
```
2016-10-30 07:16:10 upgrade lxd:i386 2.4.1-0ubuntu1~ubuntu16.04.1~ppa1 2.5-0ubuntu1~ubuntu16.04.1~ppa1
2016-10-30 07:16:10 status half-configured lxd:i386 2.4.1-0ubuntu1~ubuntu16.04.1~ppa1
2016-10-30 07:16:10 status unpacked lxd:i386 2.4.1-0ubuntu1~ubuntu16.04.1~ppa1
2016-10-30 07:16:10 status half-installed lxd:i386 2.4.1-0ubuntu1~ubuntu16.04.1~ppa1
2016-10-30 07:16:11 status half-installed lxd:i386 2.4.1-0ubuntu1~ubuntu16.04.1~ppa1
2016-10-30 07:16:11 status unpacked lxd:i386 2.5-0ubuntu1~ubuntu16.04.1~ppa1
2016-10-30 07:16:11 status unpacked lxd:i386 2.5-0ubuntu1~ubuntu16.04.1~ppa1
2016-10-30 07:16:11 upgrade lxd-client:i386 2.4.1-0ubuntu1~ubuntu16.04.1~ppa1 2.5-0ubuntu1~ubuntu16.04.1~ppa1
2016-10-30 07:16:11 status half-configured lxd-client:i386 2.4.1-0ubuntu1~ubuntu16.04.1~ppa1
2016-10-30 07:16:11 status unpacked lxd-client:i386 2.4.1-0ubuntu1~ubuntu16.04.1~ppa1
2016-10-30 07:16:11 status half-installed lxd-client:i386 2.4.1-0ubuntu1~ubuntu16.04.1~ppa1
2016-10-30 07:16:11 status half-installed lxd-client:i386 2.4.1-0ubuntu1~ubuntu16.04.1~ppa1
2016-10-30 07:16:11 status unpacked lxd-client:i386 2.5-0ubuntu1~ubuntu16.04.1~ppa1
2016-10-30 07:16:11 status unpacked lxd-client:i386 2.5-0ubuntu1~ubuntu16.04.1~ppa1
```

**Comment by stgraber** [comment] 2016-11-11 11:51
Thanks, hopefully that'll be enough for me to reproduce this here. I suspect it's racy as we'd otherwise have seen a lot more of it. I've only seen it myself on one of my 20+ machines and had one other report of it besides you.

**Comment by bigjools** [comment] 2016-11-11 12:09
No worries, good luck with the fix :)

**Comment by stgraber** [comment] 2016-11-25 00:16
I pushed a packaging fix for this in 2.6 and 2.0.6 (basically always restarts the daemon post-upgrade, just in case).

**Closed by stgraber** 2016-11-25 00:16 UTC

**Comment by eviweb** [comment] 2017-10-20 10:18
Hi,
for info, I've got the same issue with the version 2.19 snap package.
Unfortunately I had to restart the LXD service and have no logs.

**Comment by michaeldye** [comment] 2018-04-03 17:11
I encountered this on 3.0.0, rev 6429 and a long-running container.  See attached logs.

[lxc-container-debug-info.txt](https://github.com/lxc/lxd/files/1872585/lxc-container-debug-info.txt)
[lxc-server-debug-info.txt](https://github.com/lxc/lxd/files/1872586/lxc-server-debug-info.txt)

**Comment by stgraber** [comment] 2018-04-03 17:16
@michaeldye most likely reason would be that your container or one of its profile uses a now-deprecated (renamed) liblxc config key inside raw.lxc. Try restarting the container. If that succeeds then the problem will likely be fixed, if that fails, then it's almost certainly a `raw.lxc` config that you need to update.
