### ISSUE TITLE
Possible Memory Leak in LXD (Ubuntu 18.04)

### ISSUE THREAD

**Issue by mattgarber** [lxc/lxd#4769] opened 2018-07-10 14:18 UTC
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info":

config:
  images.auto_update_interval: "0"
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    [REDACTED]
    -----END CERTIFICATE-----
  certificate_fingerprint: [REDACTED]
  driver: lxc
  driver_version: 3.0.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-24-generic
  server: lxd
  server_pid: 958
  server_version: 3.0.1
  storage: dir
  storage_version: "1"
  server_clustered: false
  server_name: web01

# Issue description

Memory usage of the `lxd` daemon itself seems to balloon over time (~50-100MB/day) for a reason I can't determine. Upon initial startup, memory consumption of the daemon itself is approx. 35MB. After an uptime of 6 days, daemon memory usage is ~600MB, and hits ~650MB on day 7. Processes within the container appear to be using roughly the same amount of memory, and no additional LXD capabilities (e.g., snapshots, live migration) are being utilized.

# Steps to reproduce

 1. Restart `lxd` and observe resident memory usage.
 2. Wait 5-10 days.
 3. Observe `lxd` resident memory usage.
 4. (Repeat.)

# Information to attach

 - [ ] Container log (`lxc info NAME --show-log`)

Name: web
Remote: unix://
Architecture: x86_64
Created: 2018/06/04 18:35 UTC
Status: Running
Type: persistent
Profiles: default
Pid: 1176
Ips:
  eth0:	inet	10.0.0.4	vethfa26db8d
  eth0:	inet6	fe80::216:3eff:fea4:3519	vethfa26db8d
  lo:	inet	127.0.0.1
  lo:	inet6	::1
Resources:
  Processes: 16
  CPU usage:
    CPU usage (in seconds): 103
  Memory usage:
    Memory (current): 238.34MB
    Memory (peak): 380.96MB
  Network usage:
    eth0:
      Bytes received: 6.90MB
      Bytes sent: 378.79kB
      Packets received: 4886
      Packets sent: 4026
    lo:
      Bytes received: 0B
      Bytes sent: 0B
      Packets received: 0
      Packets sent: 0

Log:

 - [ ] Container configuration (`lxc config show NAME --expanded`)

architecture: x86_64
config:
  boot.autostart: "1"
  image.architecture: amd64
  image.description: ubuntu 18.04 LTS amd64 (release) (20180522)
  image.label: release
  image.os: ubuntu
  image.release: bionic
  image.serial: "20180522"
  image.version: "18.04"
  volatile.base_image: 9879a79ac2b208c05af769089f0a6c3cbea8529571e056c82e96f1468cd1f610
  volatile.eth0.hwaddr: 00:16:3e:a4:35:19
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":100000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":100000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    ipv4.address: 10.0.0.4
    nictype: bridged
    parent: lxdbr0
    security.mac_filtering: "true"
    type: nic
  root:
    path: /
    pool: default
    type: disk
  www:
    path: /www
    source: /www
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""

 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)

(/var/log/lxd/lxd.log is currently empty.)

Up 6 days
----------
PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
958 root      20   0 1288188 599696  17052 S  0.5 29.4 161:10.65 lxd
  
Up 7 days
----------
PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
958 root      20   0 1338156 651284  16272 S  0.3 31.9 193:23.91 lxd

**Comment by stgraber** [comment] 2018-07-10 14:44
So there are a couple of known leaks in liblxc which have been fixed and may improve the situation, we have those included in the snap package and they will be in the next round of SRUs for those using the debs (likely another 3 weeks to a month, as that process takes quite a while).

Unless you absolutely depend on the deb for your system, I'd recommend switching over to the same version of LXD but from the snap package, that way if the leak still happens we'll be able to far quicker debug and resolve it (turnaround for a fix in the snap is about a day vs a month for the deb).

To switch over and stay on LXD 3.0.1, you'd do:

    sudo snap install lxd --channel=3.0/stable
    sudo lxd.migrate

**Comment by mattgarber** [comment] 2018-07-10 16:11
Unfortunately, these servers will need to stay tracking the debs, so I guess I'll have to wait and test the next round of SRUs to see if the liblxc fixes take care of this. Thank you!

**Comment by stgraber** [comment] 2018-07-10 16:50
Just sent a PR to enable a built-in pprof server so we can grab memory information, goroutines, ... in such cases without having to restart the daemon with a bunch of debug options.

https://github.com/lxc/lxd/pull/4770

**Comment by mattgarber** [comment] 2018-07-10 17:12
That'd be a great addition. I don't remember leaks like this (1,000+%) happening on any of my test 16.04 boxes, only recently under 18.04, so hopefully that could also be used to catch memory regressions earlier, too.

👍

**Comment by stgraber** [comment] 2018-07-10 21:44
So thanks to the new tooling, I can confirm that it's not an obvious Go reference issue as that memory is well accounted for. Adding some test code, it appears that we're leaking about 10kB of RAM per full container load even with the stable snap.

Going to refresh to current upstream liblxc to see if that fixes it, if so then we'll have to figure out what commits to cherry-pick.

**Comment by mattgarber** [comment] 2018-07-10 22:21
I restarted `lxd` again this afternoon to watch the memory increase rate, and my deb version appears to be leaking approx. 3.6-3.8MB/hour. Upon first start, it uses ~32MB, and six hours later, it's using ~55MB. This also holds true when compared with my earlier numbers of ~650MB after 7 days -- an increase of ~3.6MB/hour across 168h. Additionally, my workload isn't starting/stopping/restarting any containers during this period of observation; this is purely continuing to run the one container started automatically at daemon startup.

- 2018-07-10 12:00
PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
978 root      20   0  687672  32124  21156 S  0.3  1.6   0:00.29 lxd

- 2018-07-10 18:15
PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
978 root      20   0  734244  55404  22160 S  0.3  2.7   0:50.19 lxd

**Comment by stgraber** [comment] 2018-07-11 02:20
So I've been investigating a few potential sources of leaks. One of them appears to be with the database as seen below. First try a simple query that doesn't actually fetch any real record:

```
root@vm10:~# grep VmRSS /proc/${PID}/status ; for i in $(seq 50); do lxd sql global "SELECT 1;"; done >/dev/null; sleep 3 ; grep VmRSS /proc/${PID}/status
VmRSS:	   39156 kB
VmRSS:	   39156 kB

root@vm10:~# grep VmRSS /proc/${PID}/status ; for i in $(seq 50); do lxd sql global "SELECT 1;"; done >/dev/null; sleep 3 ; grep VmRSS /proc/${PID}/status
VmRSS:	   39400 kB
VmRSS:	   39400 kB
```

So that's 50 dummy queries and no extra allocation, all good.

Now lets try with a query that we know will return 80 rows (I have 80 containers on this system):

```
root@vm10:~# grep VmRSS /proc/${PID}/status ; for i in $(seq 50); do lxd sql global "SELECT * FROM containers;"; done >/dev/null; sleep 3 ; grep VmRSS /proc/${PID}/status
VmRSS:	   47212 kB
VmRSS:	   48448 kB
root@vm10:~# grep VmRSS /proc/${PID}/status ; for i in $(seq 50); do lxd sql global "SELECT * FROM containers;"; done >/dev/null; sleep 3 ; grep VmRSS /proc/${PID}/status
VmRSS:	   48448 kB
VmRSS:	   49472 kB
```

So we seem to leak about 1.1MB of RAM or about 0.27kB per row.

Lets look at row counts quickly:

```
root@vm10:~# lxd sql global "SELECT COUNT(*) FROM containers;"
+----------+
| COUNT(*) |
+----------+
| 80       |
+----------+
root@vm10:~# lxd sql global "SELECT COUNT(*) FROM containers_config;"
+----------+
| COUNT(*) |
+----------+
| 1040     |
+----------+
```

Now lets try something much worse by querying all those config rows:

```
root@vm10:~# grep VmRSS /proc/${PID}/status ; for i in $(seq 50); do lxd sql global "SELECT * FROM containers_config;"; done >/dev/null; sleep 3 ; grep VmRSS /proc/${PID}/status
VmRSS:	   49472 kB
VmRSS:	   56908 kB
root@vm10:~# grep VmRSS /proc/${PID}/status ; for i in $(seq 50); do lxd sql global "SELECT * FROM containers_config;"; done >/dev/null; sleep 3 ; grep VmRSS /proc/${PID}/status
VmRSS:	   56908 kB
VmRSS:	   63360 kB
```

So seeing a leak of about 7MB or about 0.14kB per row.

I tried doing the same with a forced GC run prior to returning and didn't see a difference, pprof also doesn't show any matching memory allocation so it's likely somewhere in the C code or some unsafe pointers.

**Comment by stgraber** [comment] 2018-07-11 03:54
We don't have that much going on in the background, only scheduled tasks are daily update of instance types and automatic update of images every 6 hours or so. There are also a few more triggers for things like changing CPU configuration, change in network, devices being added/removed to the system and other changes to /dev in general.

Pretty much all of those could technically cause a containerLoad but with the leak I'm seeing here, it'd take a lot of that to make up 3.6MB/hour so there may be something else going on on your system.

Could you run `lxc monitor` in a terminal for an hour and confirm that you see no activity in there?

**Comment by stgraber** [comment] 2018-07-11 03:54
(and confirm that during that same hour the RSS did grow by a few MBs)

**Comment by mattgarber** [comment] 2018-07-11 11:08
Here's `lxc monitor` output I left running for 6.5 hours overnight with timestamp bookends; the only entry was from the initial output, and RSS of `lxd` grew from ~78MB to ~101MB during that time, continuing to hit the same rate.


Wed Jul 11 00:36:42 EDT 2018
VmRSS:	   77896 kB

metadata:
  context: {}
  level: dbug
  message: 'New event listener: cbaa24fc-73c7-4183-84bd-09ce27a42f87'
timestamp: "2018-07-11T00:36:43.438782196-04:00"
type: logging

Wed Jul 11 07:03:15 EDT 2018
VmRSS:	  100960 kB

**Comment by stgraber** [comment] 2018-07-11 13:50
Ok, thanks

**Comment by freeekanayaka** [comment] 2018-07-11 14:18
I've found a clear leak in the go-grpc-sql package (fixed in the PR referenced above), plus I've reduced the frequency of raft snashots in #4774.

These two changes (especially the first) seem to solve or at least greatly mitigate what was observed by @stgraber (selecting lots of rows).

**Comment by stgraber** [comment] 2018-07-11 14:44
Ok, thanks, we'll merge that and I'll re-test the resulting the edge snap to look for more leaks.

**Comment by stgraber** [comment] 2018-07-11 20:20
I'm now seeing less than 300bytes of RSS increase after a `lxc list` so that's pretty encouraging.
I'll wait a few minutes to see if Go then runs the garbage collector and gets us rid of that too.

**Comment by stgraber** [comment] 2018-07-11 22:29
Haven't seen any obvious background leak in the past hour or so, running more DB tests don't show any new leak. Memory usage is going up and down based on usage but staying at around 50MB here when idle (with 80 containers).

So looks like things are much better indeed. I'll arrange for fixes to go in stable branches and be cherry-picked to the snap very soon.

Unfortunately for users of the deb, it will take a few weeks before 3.0.2 ships with the fix.

**Closed by stgraber** 2018-07-11 22:29 UTC

**Comment by mattgarber** [comment] 2018-07-12 02:02
Thanks again – I'll hopefully see the improvement with the 3.0.2 debs!

**Comment by stgraber** [comment] 2018-07-12 03:04
Yeah, until then, I guess you could put a cron.hourly script which just runs `systemctl restart lxd`.
That's super hackish but should be perfectly safe. The only issue is if you have a running `lxc exec` session at the time of the restart, you'll get disconnected.

**Comment by mattgarber** [comment] 2018-07-12 03:38
Yep, that's basically what I'm doing! Definitely a hack, but works for me until the updates are pushed out. 👍
