### ISSUE TITLE
Lxd Cluster hangs with too many lxd processes

### ISSUE THREAD

**Issue by shantur** [lxc/lxd#4827] opened 2018-07-25 10:15 UTC
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.15.0-23-generic
   * LXC version: Snap Edge (git-c70d857)
   * LXD version: 3.2
   * Storage backend in use: ZFS and Ceph

# Issue description

I have an LXD cluster of 5 machines. Every day i see some lxd on some nodes not responding. `lxc list` hangs infinitely The container on these nodes show `ERROR` on using `lxc list --fast`. On logging into one of the nodes i found that there are many lxd processes alive. 

`lxd --logfile /var/snap/lxd/common/lxd/logs/lxd.log --group lxd`

All lxc commands are hanging except for `lxc cluster list`
```

+--------+---------------------------+----------+---------+----------------------------------------+
|  NAME  |            URL            | DATABASE |  STATE  |                MESSAGE                 |
+--------+---------------------------+----------+---------+----------------------------------------+
| gen8-1 | https://10.187.21.31:8443 | YES      | ONLINE  | fully operational                      |
+--------+---------------------------+----------+---------+----------------------------------------+
| gen8-2 | https://10.187.21.32:8443 | YES      | ONLINE  | fully operational                      |
+--------+---------------------------+----------+---------+----------------------------------------+
| gen8-3 | https://10.187.21.33:8443 | YES      | ONLINE  | fully operational                      |
+--------+---------------------------+----------+---------+----------------------------------------+
| gen8-4 | https://10.187.21.34:8443 | NO       | BLOCKED | waiting for other nodes to be upgraded |
+--------+---------------------------+----------+---------+----------------------------------------+
| gen8-5 | https://10.187.21.35:8443 | NO       | BLOCKED | waiting for other nodes to be upgraded |
+--------+---------------------------+----------+---------+----------------------------------------+

```
# Steps to reproduce

Not sure how to reproduce

# Information to attach

/var/snap/lxd/common/lxd/logs/lxd.log is empty.

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by freeekanayaka** [comment] 2018-07-25 10:53
We have indeed observed issues when upgrading a LXD cluster using the snap. The fact that you are using the edge channel makes it a lot more likely that you will be hitting those issues, since the edge snap gets refreshed at every commit in master.

For now the workaround is to kill all dangling lxd processes and restart the systemd unit (systemctl restart snap.lxd.daemon).

As mentioned, f you use the stable channel, the chance of hitting this bug should be much lower. We'll be working on it, but so far we could not reproduce it.

**Comment by freeekanayaka** [comment] 2018-07-25 11:58
With "I have same version lxd snap installed in my claster" I presume you mean that "lxc info" reports the same version on every node? (e.g. "Snap Edge (git-c70d857)").

Even in that case, the fact that you have multiple lxd processes running on the same node is an evidence of the upgrade bug, which is likely to break internal notifications and make "lxc cluster list" show the BLOCKED status.

**Comment by stgraber** [comment] 2018-07-25 14:53
Could you post a `ps fauxww` output from one of the affected systems?
I'm interested to see if those `lxd` processes are part of the same group of processes and also see whether they're stuck on I/O wait or something else.

**Comment by stgraber** [comment] 2018-07-25 14:55
@freeekanayaka note that @shantur isn't talking about `waitready` processes here so that's likely something a bit different from what you saw in the past. It could be a case of a sub-task of LXD that got stuck somehow or if it's a previous instance of the daemon, it'd be one that didn't write a pid file nor has an open socket (as either of those would get killed) which would be pretty puzzling.

@shantur could you also post the full output of `journalctl -u snap.lxd.daemon | cat`?

**Comment by shantur** [comment] 2018-07-26 09:34
@stgraber: I ended up re-creating my cluster from scratch using stable snap. I will keep an eye and post here if i get similar issue again.

**Comment by stgraber** [comment] 2018-07-26 14:00
Okay, we'll close this for now then as we don't have enough information to debug this further.
Please comment here if it happens again and we'll re-open.

**Closed by stgraber** 2018-07-26 14:00 UTC
Labels: Incomplete
