### ISSUE TITLE
lxc exec not returning

### ISSUE THREAD

**Issue by ctataryn** [lxc/lxd#1810] opened 2016-03-27 04:42 UTC
I have a scenario where I push the following script to a container of mine:

**myapp_deploy.sh**
```
#!/bin/sh
pid=$(cat /tmp/myapp.pid)
if [ "$(ps -o comm= -p "$pid")" = "java" ]; then
  echo "Killing the previous myapp process"
  kill $pid
else echo "Could not find a previously running myapp process"
fi
cd ~/deploy
echo "Launching myapp"
nohup java -Dconfig.file=./myapp.conf -jar myapp.jar &
echo "$!" > /tmp/myapp.pid
sleep 5
```

I am issuing my command via remote ssh to the server hosting my containers. The command is as follows:
```
sudo lxc file push --mode=0775 myapp_deploy.sh csapp-1/root/deploy/
sudo lxc exec csapp-1 -- /root/deploy/myapp_deploy.sh
```
The problem is, the `lxc exec` command above never terminates. I would have thought since I'm using `nohup` and backgrounding (`&`) my `java` process that everything would be fine.

What I'm trying to accomplish is to simply run my script and get-the-heck-out while it happily runs in the container.

Any suggestions?

**Comment by ctataryn** [comment] 2016-03-27 15:35
I just realized I posed in the lxd issue tracker, not sure if you want me to repost this under: lxc/lxc (or if you feel it appropriate you can move it for me)

**Comment by stgraber** [comment] 2016-03-27 19:28
It's the right issue tracker, but this is a duplicate of #1677

**Closed by stgraber** 2016-03-27 19:28 UTC
