### ISSUE TITLE
lxc push/pull of files in /var/lib/cloud not available after init.

### ISSUE THREAD

**Issue by smoser** [lxc/lxd#3088] opened 2017-03-18 01:56 UTC
# Required information

 * Distribution: Ubuntu 
 * Distribution version: zesty
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version: 2.11-0ubuntu4
   * LXD version: 2.11-0ubuntu4
   * Storage backend in use: zfs

# Issue description
I can't push or pull a file in /var/lib/cloud/seed (/var/lib/cloud/seed/nocloud-net/meta-data)
immediately after `lxc init`.  I'm almost certain this used to work.

# Steps to reproduce

 1. `lxc init  ubuntu-daily:zesty zesty1`
 2. `lxc file pull zesty1/var/lib/cloud/seed/nocloud-net/meta-data -`
      that results in `error: not found`

**Comment by stgraber** [comment] 2017-03-19 01:35
It used to work a long time ago. Nowadays, the templates are run when the container start. That's needed so that all container properties, devices, ... are properly defined, allowing users to do "lxc init", then alter the container configuration and finally do "lxc start".

This behavior is present in all supported LXD releases (it was SRUed as bugfix a while ago).

**Comment by stgraber** [comment] 2017-03-19 01:36
Closing this since it's not a bug but in fact expected behavior.

**Closed by stgraber** 2017-03-19 01:35 UTC

**Comment by smoser** [comment] 2017-03-20 16:26
well, your argument does make some sense, but it means that the rendered templates *cannot* be looked at or updated without a 'start'.  which is kind of unfortunate.
luckily, the 'lxc-chroot' that i have (https://gist.github.com/smoser/49444542158f2e5f88f1/#file-lxc-chroot) does do a 'start', so all the things get rendered, but has none of the other side affects of starting a container with /sbin/init.
