### ISSUE TITLE
Why `lxc exec $lxc_name pwd > file.txt` is no longer non-interactive?

### ISSUE THREAD

**Issue by adamryczkowski** [lxc/lxd#5519] opened 2019-02-23 17:16 UTC
In LXC 3.03 if I needed to get something out of the container in script I could use the syntax
```
lxc exec $lxc_name -- command > redirect_file.txt
```
With LXC 3.10 it no longer works. The script waits until user press Enter. It can be bypassed with

```
echo '\n' | lxc exec $lxc_name -- command > redirect_file.txt
```
but that pipe breaks some of the advanced bash code I wrote that initializes and polishes LXC containers. It would be so much easier, if `lxc exec $lxc_name -- command > redirect_file.txt` was non-interactive, like it used to be.

Note, that without a redirection
```
lxc exec $lxc_name -- command
```
does not wait for new line.

I tried `--mode=non-interactive` but it changes nothing.

**Comment by stgraber** [comment] 2019-02-23 22:09
@joelhockey e2379cf367ef76f1b42f5a747c475c18cbdf6cac is causing this behavior?
Any idea on a fix?

**Comment by joelhockey** [comment] 2019-02-24 23:42
@smibarber - any thoughts?

**Comment by stgraber** [comment] 2019-02-25 09:00
Given how widespread this issue is right now, we'll revert this commit for now, I'd rather have a goroutine leak than hung processes everywhere :)

**Comment by adamryczkowski** [comment] 2019-02-25 13:29
@stgraber  
`snap refresh lxd` did not update the lxd to the working state. If that does not help, can you point me to the instructions how do I manually downgrade the `lxd` in my machines to revert that unfortunate commit.

**Comment by stgraber** [comment] 2019-02-25 14:23
The revert isn't available yet, it's going through CI now.

**Comment by adamryczkowski** [comment] 2019-02-25 18:13
It works now, thanks!

**Comment by stgraber** [comment] 2019-02-25 20:27
Re-opening as we didn't fix the issue so much as reverted the change that caused it, this revert means that we are now leaking goroutines and wasting CPU, so this still needs fixing.

**Comment by smibarber** [comment] 2019-02-26 07:46
It looks like the hang is down in [`ReaderToChannel`](https://github.com/lxc/lxd/blob/master/shared/util.go#L257), which makes sense if stdin is a tty. That read will block until a newline.

I think that the issue is the heuristic for determining whether or not to run in interactive mode. It should be sufficient to just check if stdin is a tty, like openssh does, vs checking that both stdout and stdin are ttys.

**Comment by brauner** [comment] 2019-02-26 07:48
Fwiw, we have the same logic in LXC already.

**Comment by stgraber** [comment] 2019-02-26 08:46
No, that's wrong.

If you only check stdin, then you would be running the command above in interactive mode, meaning that the output will be rendered on a PTS device with a size, causing truncation of output.

The right heuristic IS to check whether either stdin or stdout is a non-terminal target and go in non-interactive mode in that case. That's actually exactly what SSH does:

```
stgraber@castiana:~/data/code/lxc/lxd (stgraber/master)$ ssh shell.stgraber.org
Last login: Tue Feb 26 07:56:46 2019 from 2001:470:b368:1035::50
stgraber@shell01:~$ ls -lh /proc/self/fd/
total 0
lrwx------ 1 stgraber domain admins 64 Feb 26 08:46 0 -> /dev/pts/5
lrwx------ 1 stgraber domain admins 64 Feb 26 08:46 1 -> /dev/pts/5
lrwx------ 1 stgraber domain admins 64 Feb 26 08:46 2 -> /dev/pts/5
lr-x------ 1 stgraber domain admins 64 Feb 26 08:46 3 -> /var/lib/sss/mc/passwd
lr-x------ 1 stgraber domain admins 64 Feb 26 08:46 4 -> /var/lib/sss/mc/group
lr-x------ 1 stgraber domain admins 64 Feb 26 08:46 5 -> /proc/975409/fd
stgraber@shell01:~$ logout
Shared connection to shell.stgraber.org closed.
stgraber@castiana:~/data/code/lxc/lxd (stgraber/master)$ ssh shell.stgraber.org ls -lh /proc/self/fd/ < /dev/null
total 0
lr-x------ 1 stgraber domain admins 64 Feb 26 08:46 0 -> pipe:[417352364]
l-wx------ 1 stgraber domain admins 64 Feb 26 08:46 1 -> pipe:[417352365]
l-wx------ 1 stgraber domain admins 64 Feb 26 08:46 2 -> pipe:[417352366]
lr-x------ 1 stgraber domain admins 64 Feb 26 08:46 3 -> /var/lib/sss/mc/passwd
lr-x------ 1 stgraber domain admins 64 Feb 26 08:46 4 -> /var/lib/sss/mc/group
lr-x------ 1 stgraber domain admins 64 Feb 26 08:46 5 -> /proc/975464/fd
stgraber@castiana:~/data/code/lxc/lxd (stgraber/master)$ ssh shell.stgraber.org ls -lh /proc/self/fd/ | tee
total 0
lr-x------ 1 stgraber domain admins 64 Feb 26 08:46 0 -> pipe:[417352554]
l-wx------ 1 stgraber domain admins 64 Feb 26 08:46 1 -> pipe:[417352555]
l-wx------ 1 stgraber domain admins 64 Feb 26 08:46 2 -> pipe:[417352556]
lr-x------ 1 stgraber domain admins 64 Feb 26 08:46 3 -> /var/lib/sss/mc/passwd
lr-x------ 1 stgraber domain admins 64 Feb 26 08:46 4 -> /var/lib/sss/mc/group
lr-x------ 1 stgraber domain admins 64 Feb 26 08:46 5 -> /proc/975509/fd
```

**Comment by brauner** [comment] 2019-02-26 08:50
Ah, sorry, I misread. I read only the last part and thought it was saying `stdin` && `stdout`. Sorry for the confusion.

**Comment by stgraber** [comment] 2019-02-26 10:38
Going to close this one and will comment in the original PR/issue instead.

**Closed by stgraber** 2019-02-26 10:38 UTC
Labels: Bug
