### ISSUE TITLE
Container fails to recieve IPv4 address through DHCP

### ISSUE THREAD

**Issue by fosslinux** [lxc/lxd#6431] opened 2019-11-10 03:10 UTC
# Required information

 * Distribution: Raspbian (Hijacked with Bedrock Linux)
 * Distribution version: Buster
 * The output of "lxc info":

```
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - aarch64
  - armv7l
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIICGTCCAZ+gAwIBAgIRAKaRjVoQMec7pISr3Je8vKowCgYIKoZIzj0EAwMwNTEc
    MBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEVMBMGA1UEAwwMcm9vdEByYXNw
    aXNlMB4XDTE5MTEwNjA5MjMwOFoXDTI5MTEwMzA5MjMwOFowNTEcMBoGA1UEChMT
    bGludXhjb250YWluZXJzLm9yZzEVMBMGA1UEAwwMcm9vdEByYXNwaXNlMHYwEAYH
    KoZIzj0CAQYFK4EEACIDYgAEXQlMuH5LTg2X8h+29XMzsWs7YZ9HPmI+qP3QD7rb
    x2uozuvjAUWCoqD4Ho2M0G4bC0+l1dz8JrwC8lm7cCDwBb6lnGWnazx2eXRnDSw4
    IOn4lk8EaF+X8h+bYk1mRSqYo3MwcTAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAww
    CgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADA8BgNVHREENTAzggdyYXNwaXNlhwTA
    qDAYhwSsFAABhwSsFQABhwSsFgABhwSsEwABhwSsEgABhwSsEQABMAoGCCqGSM49
    BAMDA2gAMGUCMQDYM6E4KZfK8fVC1QsVR0Y7AqfZNmpiYqkrs2uE6yD+Xv3qYE9/
    SgaKZHlJrDtMn+YCMG5USZDFJDz3A65KZKtjNk450/XwEfVDnxFRxfWnM9co9GJ4
    RIM82v2L6LN6JGDw9w==
    -----END CERTIFICATE-----
  certificate_fingerprint: 1d7626992ca8915533169c3e33b5d33a130a18811a14d29c208eb9b1fc24b9bd
  driver: lxc
  driver_version: 3.2.1
  kernel: Linux
  kernel_architecture: aarch64
  kernel_features:
    netnsid_getifaddrs: "false"
    seccomp_listener: "false"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 4.19.75-v8+
  lxc_features:
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    seccomp_notify: "true"
  project: default
  server: lxd
  server_clustered: false
  server_name: raspise
  server_pid: 5594
  server_version: "3.18"
  storage: btrfs
  storage_version: "4.4"
```

(Is from the LXD snap).

# Issue description

Whenever I create a container, it goes an IPv6 address, but not an IPv4 address.

Eg:

```
+------------------+---------+------+-----------------------------------------------+------------+-----------+
|       NAME       |  STATE  | IPV4 |                     IPV6                      |    TYPE    | SNAPSHOTS |
+------------------+---------+------+-----------------------------------------------+------------+-----------+
| apparent-spaniel | RUNNING |      | fd42:4de2:d3ba:fec5:216:3eff:fe07:73d3 (eth0) | PERSISTENT | 0         |
+------------------+---------+------+-----------------------------------------------+------------+-----------+
```

As suggested by various other issues (none of which fixed my problem), manually running `dhclient -v` (as root) gives this output:

```
root@apparent-spaniel:~# dhclient -v
Internet Systems Consortium DHCP Client 4.3.5
Copyright 2004-2016 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/

Listening on LPF/eth0/00:16:3e:07:73:d3
Sending on   LPF/eth0/00:16:3e:07:73:d3
Sending on   Socket/fallback
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 3 (xid=0x922c310b)
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 3 (xid=0x922c310b)
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 3 (xid=0x922c310b)
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 3 (xid=0x922c310b)
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 7 (xid=0x922c310b)
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 12 (xid=0x922c310b)
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 15 (xid=0x922c310b)
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 8 (xid=0x922c310b)
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 9 (xid=0x922c310b)
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 17 (xid=0x922c310b)
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 8 (xid=0x922c310b)
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 9 (xid=0x922c310b)
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 11 (xid=0x922c310b)
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 13 (xid=0x922c310b)
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 9 (xid=0x922c310b)
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 17 (xid=0x922c310b)
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 14 (xid=0x922c310b)
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 20 (xid=0x922c310b)
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 8 (xid=0x922c310b)
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 7 (xid=0x922c310b)
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 7 (xid=0x922c310b)
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 11 (xid=0x922c310b)
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 9 (xid=0x922c310b)
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 9 (xid=0x922c310b)
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 8 (xid=0x922c310b)
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 10 (xid=0x922c310b)
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 20 (xid=0x922c310b)
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 19 (xid=0x922c310b)
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 11 (xid=0x922c310b)
No DHCPOFFERS received.
No working leases in persistent database - sleeping.
```

This happens with all different LXD images tested; Ubuntu 18.04, Debian 10, Void Linux and Alpine 3.9.

Container configuration:

```
architecture: aarch64
config:
  image.architecture: arm64
  image.description: ubuntu 18.04 LTS arm64 (release) (20191021)
  image.label: release
  image.os: ubuntu
  image.release: bionic
  image.serial: "20191021"
  image.type: squashfs
  image.version: "18.04"
  security.syscalls.blacklist: keyctl errno 38
  volatile.base_image: 993957c5d8676bf56ffc12fb74af52fa1badf7f31e6997f5823620ce96aec1d5
  volatile.eth0.host_name: vethd45a2954
  volatile.eth0.hwaddr: 00:16:3e:07:73:d3
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

**Comment by stgraber** [comment] 2019-11-10 03:14
Can you show `iptables -L -n` and `nft -s list ruleset`?

**Comment by stgraber** [comment] 2019-11-10 03:19
More often than not, those kind of issues are caused by some firewalling tool interfering with LXD's networking needs. Docker is known for setting such rules, as can firewalld or ufw in some situations.

**Comment by fosslinux** [comment] 2019-11-10 03:23
Sure can!

`iptables -L -n`:

```
Chain INPUT (policy DROP)
target     prot opt source               destination
ufw-before-logging-input  all  --  0.0.0.0/0            0.0.0.0/0
ufw-before-input  all  --  0.0.0.0/0            0.0.0.0/0
ufw-after-input  all  --  0.0.0.0/0            0.0.0.0/0
ufw-after-logging-input  all  --  0.0.0.0/0            0.0.0.0/0
ufw-reject-input  all  --  0.0.0.0/0            0.0.0.0/0
ufw-track-input  all  --  0.0.0.0/0            0.0.0.0/0

Chain FORWARD (policy DROP)
target     prot opt source               destination
DOCKER-USER  all  --  0.0.0.0/0            0.0.0.0/0
DOCKER-ISOLATION-STAGE-1  all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
DOCKER     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
DOCKER     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
DOCKER     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
DOCKER     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
DOCKER     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
DOCKER     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
ufw-before-logging-forward  all  --  0.0.0.0/0            0.0.0.0/0
ufw-before-forward  all  --  0.0.0.0/0            0.0.0.0/0
ufw-after-forward  all  --  0.0.0.0/0            0.0.0.0/0
ufw-after-logging-forward  all  --  0.0.0.0/0            0.0.0.0/0
ufw-reject-forward  all  --  0.0.0.0/0            0.0.0.0/0
ufw-track-forward  all  --  0.0.0.0/0            0.0.0.0/0

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
ufw-before-logging-output  all  --  0.0.0.0/0            0.0.0.0/0
ufw-before-output  all  --  0.0.0.0/0            0.0.0.0/0
ufw-after-output  all  --  0.0.0.0/0            0.0.0.0/0
ufw-after-logging-output  all  --  0.0.0.0/0            0.0.0.0/0
ufw-reject-output  all  --  0.0.0.0/0            0.0.0.0/0
ufw-track-output  all  --  0.0.0.0/0            0.0.0.0/0

Chain ufw-before-logging-input (1 references)
target     prot opt source               destination

Chain ufw-before-logging-output (1 references)
target     prot opt source               destination

Chain ufw-before-logging-forward (1 references)
target     prot opt source               destination

Chain ufw-before-input (1 references)
target     prot opt source               destination
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
ufw-logging-deny  all  --  0.0.0.0/0            0.0.0.0/0            ctstate INVALID
DROP       all  --  0.0.0.0/0            0.0.0.0/0            ctstate INVALID
ACCEPT     icmp --  0.0.0.0/0            0.0.0.0/0            icmptype 3
ACCEPT     icmp --  0.0.0.0/0            0.0.0.0/0            icmptype 11
ACCEPT     icmp --  0.0.0.0/0            0.0.0.0/0            icmptype 12
ACCEPT     icmp --  0.0.0.0/0            0.0.0.0/0            icmptype 8
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            udp spt:67 dpt:68
ufw-not-local  all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     udp  --  0.0.0.0/0            224.0.0.251          udp dpt:5353
ACCEPT     udp  --  0.0.0.0/0            239.255.255.250      udp dpt:1900
ufw-user-input  all  --  0.0.0.0/0            0.0.0.0/0

Chain ufw-before-output (1 references)
target     prot opt source               destination
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
ufw-user-output  all  --  0.0.0.0/0            0.0.0.0/0

Chain ufw-before-forward (1 references)
target     prot opt source               destination
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
ACCEPT     icmp --  0.0.0.0/0            0.0.0.0/0            icmptype 3
ACCEPT     icmp --  0.0.0.0/0            0.0.0.0/0            icmptype 11
ACCEPT     icmp --  0.0.0.0/0            0.0.0.0/0            icmptype 12
ACCEPT     icmp --  0.0.0.0/0            0.0.0.0/0            icmptype 8
ufw-user-forward  all  --  0.0.0.0/0            0.0.0.0/0

Chain ufw-after-input (1 references)
target     prot opt source               destination
ufw-skip-to-policy-input  udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:137
ufw-skip-to-policy-input  udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:138
ufw-skip-to-policy-input  tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:139
ufw-skip-to-policy-input  tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:445
ufw-skip-to-policy-input  udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:67
ufw-skip-to-policy-input  udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:68
ufw-skip-to-policy-input  all  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type BROADCAST

Chain ufw-after-output (1 references)
target     prot opt source               destination

Chain ufw-after-forward (1 references)
target     prot opt source               destination

Chain ufw-after-logging-input (1 references)
target     prot opt source               destination
LOG        all  --  0.0.0.0/0            0.0.0.0/0            limit: avg 3/min burst 10 LOG flags 0 level 4 prefix "[UFW BLOCK] "

Chain ufw-after-logging-output (1 references)
target     prot opt source               destination

Chain ufw-after-logging-forward (1 references)
target     prot opt source               destination
LOG        all  --  0.0.0.0/0            0.0.0.0/0            limit: avg 3/min burst 10 LOG flags 0 level 4 prefix "[UFW BLOCK] "

Chain ufw-reject-input (1 references)
target     prot opt source               destination

Chain ufw-reject-output (1 references)
target     prot opt source               destination

Chain ufw-reject-forward (1 references)
target     prot opt source               destination

Chain ufw-track-input (1 references)
target     prot opt source               destination

Chain ufw-track-output (1 references)
target     prot opt source               destination
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            ctstate NEW
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            ctstate NEW

Chain ufw-track-forward (1 references)
target     prot opt source               destination

Chain DOCKER (6 references)
target     prot opt source               destination
ACCEPT     tcp  --  0.0.0.0/0            172.21.0.2           tcp dpt:80

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
target     prot opt source               destination
DOCKER-ISOLATION-STAGE-2  all  --  0.0.0.0/0            0.0.0.0/0
DOCKER-ISOLATION-STAGE-2  all  --  0.0.0.0/0            0.0.0.0/0
DOCKER-ISOLATION-STAGE-2  all  --  0.0.0.0/0            0.0.0.0/0
DOCKER-ISOLATION-STAGE-2  all  --  0.0.0.0/0            0.0.0.0/0
DOCKER-ISOLATION-STAGE-2  all  --  0.0.0.0/0            0.0.0.0/0
DOCKER-ISOLATION-STAGE-2  all  --  0.0.0.0/0            0.0.0.0/0
RETURN     all  --  0.0.0.0/0            0.0.0.0/0

Chain DOCKER-ISOLATION-STAGE-2 (6 references)
target     prot opt source               destination
DROP       all  --  0.0.0.0/0            0.0.0.0/0
DROP       all  --  0.0.0.0/0            0.0.0.0/0
DROP       all  --  0.0.0.0/0            0.0.0.0/0
DROP       all  --  0.0.0.0/0            0.0.0.0/0
DROP       all  --  0.0.0.0/0            0.0.0.0/0
DROP       all  --  0.0.0.0/0            0.0.0.0/0
RETURN     all  --  0.0.0.0/0            0.0.0.0/0

Chain DOCKER-USER (1 references)
target     prot opt source               destination
RETURN     all  --  0.0.0.0/0            0.0.0.0/0

Chain ufw-logging-deny (2 references)
target     prot opt source               destination
RETURN     all  --  0.0.0.0/0            0.0.0.0/0            ctstate INVALID limit: avg 3/min burst 10
LOG        all  --  0.0.0.0/0            0.0.0.0/0            limit: avg 3/min burst 10 LOG flags 0 level 4 prefix "[UFW BLOCK] "

Chain ufw-logging-allow (0 references)
target     prot opt source               destination
LOG        all  --  0.0.0.0/0            0.0.0.0/0            limit: avg 3/min burst 10 LOG flags 0 level 4 prefix "[UFW ALLOW] "

Chain ufw-skip-to-policy-input (7 references)
target     prot opt source               destination
DROP       all  --  0.0.0.0/0            0.0.0.0/0

Chain ufw-skip-to-policy-output (0 references)
target     prot opt source               destination
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0

Chain ufw-skip-to-policy-forward (0 references)
target     prot opt source               destination
DROP       all  --  0.0.0.0/0            0.0.0.0/0

Chain ufw-not-local (1 references)
target     prot opt source               destination
RETURN     all  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
RETURN     all  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type MULTICAST
RETURN     all  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type BROADCAST
ufw-logging-deny  all  --  0.0.0.0/0            0.0.0.0/0            limit: avg 3/min burst 10
DROP       all  --  0.0.0.0/0            0.0.0.0/0

Chain ufw-user-input (1 references)
target     prot opt source               destination
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:8096
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:8096
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:22 /* 'dapp_SSH' */
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:3000
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:3000
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:8500
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:8500
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:8501
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:8501
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            multiport dports 80,443 /* 'dapp_Nginx%20Full' */
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:22000 /* 'dapp_syncthing' */
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:21027 /* 'dapp_syncthing' */
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:6600
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:6600
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:6680
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:6680
DROP       all  --  192.168.48.30        0.0.0.0/0
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:2049
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:2049
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:111
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:111
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:34958
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:34958
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:56311
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:56311

Chain ufw-user-output (1 references)
target     prot opt source               destination

Chain ufw-user-forward (1 references)
target     prot opt source               destination

Chain ufw-user-logging-input (0 references)
target     prot opt source               destination

Chain ufw-user-logging-output (0 references)
target     prot opt source               destination

Chain ufw-user-logging-forward (0 references)
target     prot opt source               destination

Chain ufw-user-limit (0 references)
target     prot opt source               destination
LOG        all  --  0.0.0.0/0            0.0.0.0/0            limit: avg 3/min burst 5 LOG flags 0 level 4 prefix "[UFW LIMIT BLOCK] "
REJECT     all  --  0.0.0.0/0            0.0.0.0/0            reject-with icmp-port-unreachable

Chain ufw-user-limit-accept (0 references)
target     prot opt source               destination
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
```

`nft` is command not found.

Since you're looking at firewall kinda things you might like:

`ufw status`:

```
Status: active

To                         Action      From
--                         ------      ----
8096                       ALLOW       Anywhere
SSH                        ALLOW       Anywhere
3000                       ALLOW       Anywhere
8500                       ALLOW       Anywhere
8501                       ALLOW       Anywhere
Nginx Full                 ALLOW       Anywhere
syncthing                  ALLOW       Anywhere
6600                       ALLOW       Anywhere
6680                       ALLOW       Anywhere
Anywhere                   DENY        192.168.48.30
2049                       ALLOW       Anywhere
111                        ALLOW       Anywhere
34958                      ALLOW       Anywhere
56311                      ALLOW       Anywhere
8096 (v6)                  ALLOW       Anywhere (v6)
SSH (v6)                   ALLOW       Anywhere (v6)
3000 (v6)                  ALLOW       Anywhere (v6)
8500 (v6)                  ALLOW       Anywhere (v6)
8501 (v6)                  ALLOW       Anywhere (v6)
Nginx Full (v6)            ALLOW       Anywhere (v6)
syncthing (v6)             ALLOW       Anywhere (v6)
6600 (v6)                  ALLOW       Anywhere (v6)
6680 (v6)                  ALLOW       Anywhere (v6)
2049 (v6)                  ALLOW       Anywhere (v6)
111 (v6)                   ALLOW       Anywhere (v6)
34958 (v6)                 ALLOW       Anywhere (v6)
56311 (v6)                 ALLOW       Anywhere (v6)
```

**Comment by stgraber** [comment] 2019-11-10 03:35
Okay, so you have both ufw and docker playing with your rules.
Docker has that tendency to switch policy from ACCEPT to DROP on INPUT and FORWARD, though that may also have been done on purpose by ufw.

`iptables -L -n -v` would show you hit counters, likely confirming that the DROP policy on INPUT/FORWARD is what's preventing your container networking from working.

The LXD rules also appear to have been flushed, maybe reloading LXD with `systemctl reload snap.lxd.daemon` would be enough for them to re-appear. If not, you may want to configure ufw to allow communications in and out of your LXD bridge (usually lxdbr0).

**Comment by stgraber** [comment] 2019-11-10 03:36
(Closing as this is system firewalling/other packages interfering and not a container networking issue in itself. Still happy to help track down the culprit though.)

**Closed by stgraber** 2019-11-10 03:36 UTC
Labels: Incomplete

**Comment by fosslinux** [comment] 2019-11-10 03:48
Ok, I'll try that. Thanks for that :)

**Comment by fosslinux** [comment] 2019-11-10 05:48
For anyone who finds this thread:

```
ufw allow in on lxdbr0
ufw allow out on lxdbr0
```

Fixed the problem.

**Comment by tomponline** [comment] 2021-05-19 07:59
Also see https://discuss.linuxcontainers.org/t/lxd-bridge-doesnt-work-with-ipv4-and-ufw-with-nftables/10034/17
