### ISSUE TITLE
Can't correct lxd database

### ISSUE THREAD

**Issue by huru2000** [lxc/lxd#1598] opened 2016-02-13 01:04 UTC
Upgraded from 0.27 to 2.0beta2. Crashed during install and now cannot use lxd. Have attempted fresh install. Hangs on "Setting up lxd (2.0.0~beta2-0ubuntu1~ubuntu14.04.1~ppa1) ...". Logs show no errors, only warnings. Not sure if database is corrupt, but I have managed to get installation to show database errors or "error: Get http://unix.socket/1.0/containers?recursion=1: dial unix /var/lib/lxd/unix.socket: connect: no such file or directory".

**Comment by kfix** [comment] 2016-02-13 02:59
I am getting `Feb 12 18:46:37 localhost lxd[13190]: error: no such column: creation_date

**Comment by huru2000** [comment] 2016-02-13 03:01
Yup. I found a post (which I've since managed to lose) which I followed. Bad idea. It tacked on the creation_date string onto the end and torched the db. I've found everything of mine is still intact, but I can't fix the db to use the containers.

**Comment by kfix** [comment] 2016-02-13 03:04
my lxd box is a test machine, so I'm OK with wiping out `/var/lib/lxd/lxd.db`. But is there a schema migration script at all for this upgrade path?

**Comment by huru2000** [comment] 2016-02-13 03:05
You got it. I think that's the sort of thing I'm looking for as well.

**Comment by kfix** [comment] 2016-02-13 03:17
here it is: https://github.com/lxc/lxd-pkg-ubuntu/blob/debian/2.0.0.beta2-0ubuntu1/lxd/db_update.go

**Comment by kfix** [comment] 2016-02-13 03:33
Well, that looks like lxd is just supposed to keep it up-to-spec on its own. There's no updater in the debian/ package hooks.

```
$ sqlite3 /var/lib/lxd/lxd.db '.dump schema'
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE schema (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    version INTEGER NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE (version)
);
INSERT INTO "schema" VALUES(1,6,1444259224);
INSERT INTO "schema" VALUES(2,7,1444772645);
INSERT INTO "schema" VALUES(3,8,1444772645);
INSERT INTO "schema" VALUES(4,9,1444772645);
INSERT INTO "schema" VALUES(5,10,1444772645);
INSERT INTO "schema" VALUES(6,11,1444772645);
INSERT INTO "schema" VALUES(7,12,1444772645);
INSERT INTO "schema" VALUES(8,13,1444772645);
INSERT INTO "schema" VALUES(9,14,1444772645);
INSERT INTO "schema" VALUES(10,15,1444772645);
INSERT INTO "schema" VALUES(11,16,1444772645);
INSERT INTO "schema" VALUES(12,17,1444772645);
INSERT INTO "schema" VALUES(13,18,1450806303);
INSERT INTO "schema" VALUES(14,19,1450806303);
INSERT INTO "schema" VALUES(15,20,1450806303);
COMMIT;
```

**Comment by stgraber** [comment] 2016-02-13 03:35
Hmm, so 21 never got applied in your DB either?

**Comment by huru2000** [comment] 2016-02-13 03:36
Claims malformed database. I can still see the container content in the folders, just can't get the db to use them after the update.

**Comment by huru2000** [comment] 2016-02-13 03:39
If it helps to diagnose, I renamed the malformed file lxd.old and had it make a new one as part of a re-install. It allows LXD to run, but I can't see my images of course.

**Comment by stgraber** [comment] 2016-02-13 03:41
Can you upload your corrupted lxd.db somewhere or e-mail it to me? (stgraber@stgraber.org)

**Comment by kfix** [comment] 2016-02-13 03:42
sure. my dpkg audit trail is here: https://gist.github.com/kfix/f745ad599fe7584d09a3

**Comment by huru2000** [comment] 2016-02-13 03:58
Sent mine via email.

**Comment by stgraber** [comment] 2016-02-13 04:47
@huru2000 Ouch, yeah, your DB file is properly corrupted... All the usual tricks to extract the data from it are failing. Well, short of hexdumping it, extracting all the strings and re-building the DB by hand...

I don't suppose you have a backup of that host which would include some earlier version of the DB file you could use?

If not, well the easiest way to get things back to normal is to move /var/lib/lxd/containers and /var/lib/lxd/images aside, restart lxd, then re-import the images with "lxc image import \<main file\> \<rootfs file if present\> --alias \<alias\>".

Once that's done, for every container you had, do "lxc init \<image\> \<container name\>", then re-apply any configuration you can remember and lastly, run "rsync -aAvP --numeric-ids --sparse --hard-links --delete /path/to/backup/container /var/lib/lxd/containers/\<name\>" which will transfer the content of the container.

**Comment by stgraber** [comment] 2016-02-13 04:52
@kfix yours is very interesting, with it I can totally reproduce the issue I've had a few users mention before where the schema update doesn't seem to be getting applied, trying to figure out why that is now.

**Comment by stgraber** [comment] 2016-02-13 04:57
Oh crap, I see the problem.

**Comment by stgraber** [comment] 2016-02-13 04:58
dbUpdateFromV20 must be rewritten to not require loading containers during the upgrade.

**Comment by stgraber** [comment] 2016-02-13 04:59
the current version breaks when upgrading directly to 2.0.0.beta2 without installing 2.0.0.beta1 first...

**Comment by stgraber** [comment] 2016-02-13 05:02
Well, actually the V20 upgrade code was added a while back so you need a pretty big version jump to run into the bug, but clearly that happens...

**Comment by kfix** [comment] 2016-02-13 08:33
hmm, I'll leave my system alone until beta3 comes down the line. Happy to test anything to help :boot: this :bug:

**Comment by pcdummy** [comment] 2016-02-13 11:06
Having the same problem here, just did an apt-get dist-upgrade now lxd fails:

    E: Unable to locate package sqlite4

**Comment by pcdummy** [comment] 2016-02-13 11:07
root@h1 /home/pcdummy # sqlite3 /var/lib/lxd/lxd.db 
    SQLite version 3.8.2 2013-12-06 14:53:30
    Enter ".help" for instructions
    Enter SQL statements terminated with a ";"
    sqlite> select * from schema;
    1|12|1440125339
    2|13|1440126180
    3|14|1440126180
    4|15|1440126181
    5|16|1449154232
    6|17|1449154232
    7|18|1451491305
    8|19|1451491305
    9|20|1451491305

**Comment by pcdummy** [comment] 2016-02-13 11:23
I manualy fixed it:

    root@h1 /home/pcdummy/go/bin # sqlite3 /var/lib/lxd/lxd.db
    SQLite version 3.8.2 2013-12-06 14:53:30
    Enter ".help" for instructions
    Enter SQL statements terminated with a ";"
    sqlite> ALTER TABLE containers ADD COLUMN creation_date DATETIME NOT NULL DEFAULT 0;
    sqlite> .quit

    root@h1 /home/pcdummy/go/bin # /usr/bin/lxd --group=lxd
    WARN[02-13|12:15:51] CGroup memory swap accounting is disabled, swap limits will be ignored. 
    error: duplicate column name: creation_date

    root@h1 /home/pcdummy/go/bin # sqlite3 /var/lib/lxd/lxd.db
    SQLite version 3.8.2 2013-12-06 14:53:30
    Enter ".help" for instructions
    Enter SQL statements terminated with a ";"
    sqlite> INSERT INTO `schema`(`id`,`version`,`updated_at`) VALUES (11,22,1455362152);
    sqlite> .quit

    root@h1 /home/pcdummy/go/bin # /usr/bin/lxd --group=lxd
    WARN[02-13|12:21:23] CGroup memory swap accounting is disabled, swap limits will be ignored.

**Comment by kfix** [comment] 2016-02-13 18:22
@pcdummy that only works coming from v21. your containers are probably missing some changes.

**Comment by pcdummy** [comment] 2016-02-13 18:44
No it works for v20 too, where i was coming from. I fix v21 and by adding `creation_date` and then remove it to go to v22.

**Comment by stgraber** [comment] 2016-02-13 19:27
I fixed the DB migration issue by replacing the Go logic by a pure-SQL alternative. I sent the branch for review now. Once merged, I'll cherry-pick this fix into the Ubuntu package so that Ubuntu users and users of our PPAs get the fix ASAP.

I believe that this issue combined with multiple concurrent runs of the LXD tools (as triggered by systemd) is what ultimately caused the DB corruption here. While there's sadly nothing I can do about the corrupted database, I think my commit will prevent this from happening to somebody else (at least for this very bug).

**Comment by huru2000** [comment] 2016-02-13 21:48
Stephan, can you say more on the import? I'm a bit daft on the "lxc image import <main file> <rootfs file if present> --alias <alias>". main file? rootfs file from the container? I remember seeing a directory for rootfs. alias I assume is the name I selected for the container?

rootfs$ ls
bin  boot  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var

**Comment by stgraber** [comment] 2016-02-13 22:15
That command is for the images stored in /var/lib/lxd/images/

For the containers, you want the "lxc init" + rsync trick I described afterwards.

**Comment by huru2000** [comment] 2016-02-13 22:16
lxc image import /contback/images/d9092c2fea5a8f1367bf3a0b6b627db95d18ba2ee8412f5ab638f569bb60408d --alias trusty64
error: UNIQUE constraint failed: images.fingerprint

**Closed** 2016-02-14 01:51 UTC

**Comment by huru2000** [comment] 2016-02-14 02:03
This didn't transfer the content. I copied verbatim and replaced the paths. It successfully completes the request but none of the installed services in the containers copied. Example: one of the containers is for zoneminder. Zoneminder doesn't even show as installed. In fact, Apache also doesn't show. Something I'm missing?

Once that's done, for every container you had, do "lxc init <image> <container name>", then re-apply any configuration you can remember and lastly, run "rsync -aAvP --numeric-ids --sparse --hard-links --delete /path/to/backup/container /var/lib/lxd/containers/<name>" which will transfer the content of the container.

**Comment by stgraber** [comment] 2016-02-14 22:47
Sounds like the rsync part didn't happen or wasn't done right. Maybe try the slightly clearer:

    rsync -aAvP --numeric-ids --sparse --hard-links --delete /path/to/backup/containers/CONTAINER_NAME/rootfs/ /var/lib/lxd/containers/CONTAINER_NAME/rootfs/

Run this as root, replacing the source path to where you moved your old /var/lib/lxd/containers and CONTAINER_NAME in both paths to the name of your container.

When running it, you should see one line being printed by file which differs, once rsync is done, your container should be back to the way it was.

**Comment by huru2000** [comment] 2016-02-15 01:13
I eventually got the first version to work. Apparently additional cleanup was needed from the failed updates. Now container content appears to be working. You're a life saver!

**Comment by stgraber** [comment] 2016-02-15 01:33
Great to hear that helped!

**Comment by kfix** [comment] 2016-02-15 19:30
2.0.0~beta2-0ubuntu2 worked, my DB updated & lxd started back up after `apt-get update; apt-get install lxd` with no further intervention.

**Comment by stgraber** [comment] 2016-02-15 22:40
good to hear it worked!
