### ISSUE TITLE
lxc image copy from remote to local doesn't create zfs dataset

### ISSUE THREAD

**Issue by renky** [lxc/lxd#3359] opened 2017-05-29 21:39 UTC
Tried on a fresh installed lxd instance on a fresh installed Ubuntu Server.
Using ZFS as backend.

Creating cointainers (and implicitly caching images) creates a dataset for the image and for the container.
But Copying an image to the local images doesn't do that - all imagefiles that are copied are saved in rootfs in that case

```
zfs list
NAME                    USED  AVAIL  REFER  MOUNTPOINT
zpool1                  531K  1.26T  25.4K  /var/zpool1
zpool1/lxd              127K  1.26T  25.4K  /var/lxd
zpool1/lxd/containers  25.4K  1.26T  25.4K  none
zpool1/lxd/custom      25.4K  1.26T  25.4K  none
zpool1/lxd/deleted     25.4K  1.26T  25.4K  none
zpool1/lxd/images      25.4K  1.26T  25.4K  none
zpool1/vmail           25.4K  1.26T  25.4K  /var/vmail
zpool1/www             36.7K  1.26T  36.7K  /var/www
```

call launch for three times:
lxc launch ubuntu:17.04

```
zfs list
NAME                                                                                 USED  AVAIL  REFER  MOUNTPOINT
zpool1                                                                               330M  1.26T  25.4K  /var/zpool1
zpool1/lxd                                                                           329M  1.26T  25.4K  /var/lxd
zpool1/lxd/containers                                                               19.3M  1.26T  25.4K  none
zpool1/lxd/containers/just-malamute                                                 6.76M  1.26T   310M  /var/lib/lxd/storage-pools/pwhost/containers/just-malamute
zpool1/lxd/containers/learning-basilisk                                             6.75M  1.26T   310M  /var/lib/lxd/storage-pools/pwhost/containers/learning-basilisk
zpool1/lxd/containers/nearby-imp                                                    5.82M  1.26T   310M  /var/lib/lxd/storage-pools/pwhost/containers/nearby-imp
zpool1/lxd/custom                                                                   25.4K  1.26T  25.4K  none
zpool1/lxd/deleted                                                                  25.4K  1.26T  25.4K  none
zpool1/lxd/images                                                                    310M  1.26T  25.4K  none
zpool1/lxd/images/a221591e855f271769b3d780789c25d504b4062475c125f790b97d4afa0539f5   310M  1.26T   310M  none
zpool1/vmail                                                                        25.4K  1.26T  25.4K  /var/vmail
zpool1/www                                                                          36.7K  1.26T  36.7K  /var/www
```
there is now one dataset for the image and three for the containers

now do the copy job:

```
lxc image copy images:ubuntu/yakkety local: --alias ubuntu/yakkety --auto-update
lxc image copy images:ubuntu/yakkety/i386 local: --alias ubuntu/yakkety/i386 --auto-update
lxc image copy images:ubuntu/xenial local: --alias ubuntu/xenial --auto-update
lxc image copy images:ubuntu/xenial/i386 local: --alias ubuntu/xenial/i386 --auto-update
```

and again list

```
zfs list
NAME                                                                                 USED  AVAIL  REFER  MOUNTPOINT
zpool1                                                                               331M  1.26T  25.4K  /var/zpool1
zpool1/lxd                                                                           330M  1.26T  25.4K  /var/lxd
zpool1/lxd/containers                                                               20.3M  1.26T  25.4K  none
zpool1/lxd/containers/just-malamute                                                 6.76M  1.26T   310M  /var/lib/lxd/storage-pools/pwhost/containers/just-malamute
zpool1/lxd/containers/learning-basilisk                                             6.75M  1.26T   310M  /var/lib/lxd/storage-pools/pwhost/containers/learning-basilisk
zpool1/lxd/containers/nearby-imp                                                    6.75M  1.26T   310M  /var/lib/lxd/storage-pools/pwhost/containers/nearby-imp
zpool1/lxd/custom                                                                   25.4K  1.26T  25.4K  none
zpool1/lxd/deleted                                                                  25.4K  1.26T  25.4K  none
zpool1/lxd/images                                                                    310M  1.26T  25.4K  none
zpool1/lxd/images/a221591e855f271769b3d780789c25d504b4062475c125f790b97d4afa0539f5   310M  1.26T   310M  none
zpool1/vmail                                                                        25.4K  1.26T  25.4K  /var/vmail
zpool1/www                                                                          36.7K  1.26T  36.7K  /var/www
```

nothing hapened - same datasets as before - but the images are created on the disk:
```
l /var/lib/lxd/images/
total 495780
-rw-r--r-- 1 root root       672 May 29 23:37 05482d20d7c4b6ffe6ff49175fb17fce716e7b22b9938520e0acca853bf89c4b
-rw-r--r-- 1 root root  85693992 May 29 23:37 05482d20d7c4b6ffe6ff49175fb17fce716e7b22b9938520e0acca853bf89c4b.rootfs
-rw-r--r-- 1 root root       668 May 29 23:37 2373b6551aca33a1dca54b92b99083064c95dee9c5a845ea02b9be5e62a271a7
-rw-r--r-- 1 root root  85904592 May 29 23:37 2373b6551aca33a1dca54b92b99083064c95dee9c5a845ea02b9be5e62a271a7.rootfs
-rw-r--r-- 1 root root       668 May 29 23:37 83a654e147bf8ea1357c87656edafe9111c4a725b35f24883963634e67c5eb7f
-rw-r--r-- 1 root root  86599148 May 29 23:37 83a654e147bf8ea1357c87656edafe9111c4a725b35f24883963634e67c5eb7f.rootfs
-rw-r--r-- 1 root root       848 May 29 23:31 a221591e855f271769b3d780789c25d504b4062475c125f790b97d4afa0539f5
-rw-r--r-- 1 root root 164466688 May 29 23:31 a221591e855f271769b3d780789c25d504b4062475c125f790b97d4afa0539f5.rootfs
-rw-r--r-- 1 root root       672 May 29 23:36 e20cb56bb0734d9533ce7f03f17ef1fdddb3a807390663b2d0d1cffa7fe89b9c
-rw-r--r-- 1 root root  84984948 May 29 23:36 e20cb56bb0734d9533ce7f03f17ef1fdddb3a807390663b2d0d1cffa7fe89b9c.rootfs
```
but really in rootfs...

i think if zfs is used also local stored images should be saved in datasets....

Additional information about installed lxd-version:
 * Distribution: Ubuntu
 * Distribution version: lxc image copy images:ubuntu/zesty local: 

config:
  core.https_address: '[::]:8443'
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 94.130.8.20:8443
  - '[2a01:4f8:10b:c58::2]:8443'
  - 10.239.126.1:8443
  - '[fd42:cbcc:8e58:332a::1]:8443'
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFjTCCA3WgAwIBAgIQboN17DCwREAgcnh6I9OQuDANBgkqhkiG9w0BAQsFADA/
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMR8wHQYDVQQDDBZyb290QGFs
    YXJpY2gucHdob3N0LmRlMB4XDTE3MDUyOTIxMjc0OVoXDTI3MDUyNzIxMjc0OVow
    PzEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEfMB0GA1UEAwwWcm9vdEBh
    bGFyaWNoLnB3aG9zdC5kZTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    AKZszpnMVbd+DFhco/HhDbiV8VZPWaUxWEELcPBRRXopF4yhd/qmgWFPLLN4XmEL
    W2p4dnatdTngsGiFgYeSd+iNgmTgVXqbWkDnkK15czj2f//zZ4Z7Jb/on0uze3iI
    TD8TNGf4qNn7pkeo5KXRMdWbqZPqsQI+U8vBoLcqReGcuXremNp8HumZFb4DDJcv
    8aeMa+XhNNOGV35/LaU0iPi9ByBALqehoZeNgrxApmJHFQvKUONPyBAcT5fBRG21
    l0R7owC117aBjJSjubM42eWi8M7FlRSo9B4lJwVVtFAMWyzhgumec5U8jVrwtRdm
    ShvOkXSruEsNTtDzTJsFIJodWbmlWTYgZCnMcPyYF9YVQ1ZHFZ/eeUTCt28YeeAi
    wfnjW38Smqz+iRDULSNZaounQPMgcwIJHUwpWpve4Iky3inl4qtNh2rM7K2WVNEQ
    zqrEMTVa8O179uPu3rL3gTgYdr7nymV7WshBJVWz2RtJhdLfajhqHM1wLRcpN+QM
    DMZr4IV3gU69SYlO98TfnGLOZMWNTvt4xTeZZiGejPjY7+qtZFJrVHsLQPEwpcrE
    ZdwUExAIEFkM6MxipAsA+R+HEWAmZLaT+GAzuiKuB5oxTlKKT7UNO0rOYcd5YOt2
    2qphVxEidTTjtp9RvNTNKN6lLAIaRyvETt28G3d3owFvAgMBAAGjgYQwgYEwDgYD
    VR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAw
    TAYDVR0RBEUwQ4IRYWxhcmljaC5wd2hvc3QuZGWHBF6CCBSHECoBBPgBCwxYAAAA
    AAAAAAKHBArvfgGHEP1Cy8yOWDMqAAAAAAAAAAEwDQYJKoZIhvcNAQELBQADggIB
    AH3BOAifKv/Bu+OA5BVkfX2BN+7UwN46niIOhgp8ft3ThsvGgM0SPgJ/DjR9XazD
    iqw4w+CKfZwK8ixVbRupmmrp07h9FUxD0z2ApSGYRgdrQayp74rCkMlJYYCJS8Ca
    6OGTOQRWBQb5ew/G6ENFIeUNe//xYstCTxGmdwFkBnlQOKLRLnVymFc3UO1AMk+e
    J8VBqNSZj289HPhfTfOA9x6x9WHbyr88KJYeVhnmS66f8QpacT5gonvel5ZD4RAO
    aoD91jO9c65jJJ5s/FJsHM3JZdP096GfdLwK76TtA9iyerw7vfcKO6RBx+MSWQTx
    cD7ij7wDVhqF9T6FhnjBBkDVTt3cFp3gUT5P1HAiNoaPqFufFcLGcZAZqA8eM+Qa
    agW6xmgvlm3oqG8rhLpPgEUXVMtTEQhrvA34Z02i60hAyPm7xTwWkbs81YYkmHHR
    mPSPD0nhJNE9AiuXpFaP81GxlK9j/mDzYN/cnjCe0z6/1Kl19VgJmG2HlGggtvrg
    npR1LfVaBXCi4AwqGPptsu8zJ7Mbv0FfbLI6BR0pMJcZVwaPWqAncyyWlMNIt0xt
    1fnWvT5CWWLDWVL2X26MeCJRG7Vv+Ts+rrX+1hObnKgEkE9dN9T3WSZKoJJoW6Wx
    leiPjRXeTlztQilZTTN2KsWNrVaN6XNv8Y5/Vux9JXuk
    -----END CERTIFICATE-----
  certificate_fingerprint: 1462434125f2e7849ea9dd9442a6ecc0eb9e80712ce26e3bee0127b52d740549
  driver: lxc
  driver_version: 2.0.7
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.10.0-19-generic
  server: lxd
  server_pid: 31688
  server_version: "2.12"
  storage: zfs
  storage_version: 0.6.5.9-2

**Comment by brauner** [comment] 2017-05-29 21:43
This is intended behavior LXD will only create a dataset for the the image in the pool if a container is created from it. Otherwise the compressed data is simply stored in the local image store.

**Comment by renky** [comment] 2017-05-29 21:45
Ok, thanks for the fast reply
And is there a way to save the local image store also in a zfs dataset?

**Comment by stgraber** [comment] 2017-05-29 21:50
You can move /var/lib/lxd/images to be itself on zfs if you want. You'll need to move the current content aside, create a zfs filesystem with /var/lib/lxd/images as mountpoint and then move the current content back onto it.

That will just move the compressed files to be stored on a zfs filesystem though. You'll never get away from having those files around as the LXD API allows for images to be copied and exported in their original format and there's no reliable way to re-generate the original tarball from a zfs dataset.

**Comment by stgraber** [comment] 2017-05-29 21:51
Closing as there doesn't appear to be an actual LXD bug/issue there.

**Closed by stgraber** 2017-05-29 21:51 UTC

**Comment by renky** [comment] 2017-05-29 21:58
I already tried that - to be honest, that was my first shot, when I saw, that images didn't have a mountpoint. so i did the following (moved away all images before):
```
zfs set mountpoint=/var/lib/lxd/images zpool1/lxd/images

zfs list
NAME                    USED  AVAIL  REFER  MOUNTPOINT
zpool1                  549K  1.26T  25.4K  /var/zpool1
zpool1/lxd              127K  1.26T  25.4K  /var/lxd
zpool1/lxd/containers  25.4K  1.26T  25.4K  none
zpool1/lxd/custom      25.4K  1.26T  25.4K  none
zpool1/lxd/deleted     25.4K  1.26T  25.4K  none
zpool1/lxd/images      25.4K  1.26T  25.4K  /var/lib/lxd/images
zpool1/vmail           25.4K  1.26T  25.4K  /var/vmail
zpool1/www             36.7K  1.26T  36.7K  /var/www
```
now moved back all images
df now shows  that /zpool1/lxd/images has content

and now the following  happens when creating a new container from one of the local images:
```
lxc launch ubuntu/zesty
Creating premium-leopard
error: Failed to create ZFS filesystem: filesystem 'zpool1/lxd/images/f06418beae2369211d7d61f326409a55289ba51b3ee27b1de4cc6a541a010596' can not be mounted due to error 20
cannot mount 'zpool1/lxd/images/f06418beae2369211d7d61f326409a55289ba51b3ee27b1de4cc6a541a010596': Invalid argument
filesystem successfully created, but not mounted
```

**Comment by stgraber** [comment] 2017-05-29 22:43
Oh, I think I see what's going on.

**Comment by stgraber** [comment] 2017-05-29 22:46
@brauner So we have a problem in the ZFS driver where we call zfsPoolVolumeCreate which doesn't set mountpoint=none and then as a second step we call zfsPoolVolumeSet to set the mountpoint.

That's a problem when /var/lib/lxd/images is itself on the zpool as ZFS now attempts to mount over /var/lib/lxd/images/FINGERPRINT which already exists (as the tarball).

I think we should change zfsPoolVolumeCreate to always pass "-o mountpoint=none" and override the few cases we care about after the fact.

Can you check that this is safe and then do it?

**Comment by brauner** [comment] 2017-05-29 23:09
Already had this on my list. :)

**Comment by renky** [comment] 2017-05-30 23:15
Thanks guys - you are all very helpful and fast in answering - that's really great.

**Comment by brauner** [comment] 2017-05-31 00:25
We try to do our best. :)
