### ISSUE TITLE
publish mycont --alias myimg failing with constraint error

### ISSUE THREAD

**Issue by stub42** [lxc/lxd#4982] opened 2018-08-28 12:29 UTC
# Required information

 * Distribution: Ubuntu (snap)
 * Distribution version: 18.04
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version: 3.4
   * LXD version:
   * Storage backend in use:

# Issue description

Using 'lxc publish' to convert a stopped container to an image with an alias is now failing with the error message: `Error: UNIQUE constraint failed: images.fingerprint`

# Steps to reproduce
 1. lxc launch ubuntu:bionic mycont
 2. lxc stop mycont
 3. lxc publish mycont --alias myimg

**Comment by stgraber** [comment] 2018-08-28 17:19
Unable to reproduce this with those steps on the LXD 3.4 snap, so that makes me think it's the same DB issue + bad error handling issue we had reported a few days ago.

The bad error reporting has already been fixed in master, which would then have the dqlite error be surfaced when this happens at which point we can have @freeekanayaka look into the dqlite side of things.

**Comment by stgraber** [comment] 2018-08-28 17:19
https://github.com/lxc/lxd/issues/4976

**Closed by stgraber** 2018-08-28 17:19 UTC
