### ISSUE TITLE
Fix LXC/LXD version mismatches in PPAs

### ISSUE THREAD

**Issue by vince06fr** [lxc/lxd#739] opened 2015-06-06 06:13 UTC
don't know why but today I just try to start my containers and I get : 
```error: exit status 1```

So I try to launch a new container : 
```
$ lxc launch ubuntu/trusty trusty2 
Creating container...done
Starting container...done
error: exit status 1
```

the log say it is a template error : 
```
$ sudo cat /var/log/lxd/vivid/lxc.log
            lxc 20150427012246.178 INFO     lxc_confile - confile.c:config_idmap:1398 - read uid map: type u nsid 0 hostid 100000 range 65536
            lxc 20150427012246.178 INFO     lxc_confile - confile.c:config_idmap:1398 - read uid map: type g nsid 0 hostid 100000 range 65536
            lxc 20150427012246.180 WARN     lxc_cgmanager - cgmanager.c:cgm_get:993 - do_cgm_get exited with error
            lxc 20150427012246.198 INFO     lxc_confile - confile.c:config_idmap:1398 - read uid map: type u nsid 0 hostid 100000 range 65536
            lxc 20150427012246.198 INFO     lxc_confile - confile.c:config_idmap:1398 - read uid map: type g nsid 0 hostid 100000 range 65536
            lxc 20150427012246.200 ERROR    lxc_utils - utils.c:get_template_path:1320 - No such file or directory - bad template: /tmp/lxd_lxc_startconfig_317991061
            lxc 20150427012246.200 ERROR    lxc_container - lxccontainer.c:do_lxcapi_create:1342 - bad template: /tmp/lxd_lxc_startconfig_317991061
```

**Comment by stgraber** [comment] 2015-06-08 11:40
what version of lxd is that?

**Comment by vince06fr** [comment] 2015-06-08 13:13
0.10 on ubuntu vivid

**Comment by stgraber** [comment] 2015-06-08 13:33
Found the problem. The failure you're seeing is caused by a recent API breakage (well, un-breakage but same thing really) in upstream LXC.

LXD in the affected PPAs (those that received the LXC dev snapshot) would have to be rebuilt to fix that. I may do that later today if I find the time, otherwise, LXD 0.11 which will be uploaded tomorrow will fix the problem.

Until then, your best bet is to downgrade your version of LXC.

**Comment by vince06fr** [comment] 2015-06-08 15:02
ok thank you for the answer

**Comment by vince06fr** [comment] 2015-06-10 16:53
so donwgrading work well but upgrading to the new veriosn breack something : 
```
$ lxc start trusty
error: saving config file for the container failed
$ lxc version
0.11
```
```
$ sudo cat /var/log/lxd/trusty/lxc.log
            lxc 20150427012246.663 INFO     lxc_confile - confile.c:config_idmap:1398 - read uid map: type u nsid 0 hostid 100000 range 65536
            lxc 20150427012246.663 INFO     lxc_confile - confile.c:config_idmap:1398 - read uid map: type g nsid 0 hostid 100000 range 65536
            lxc 20150427012246.722 INFO     lxc_confile - confile.c:config_idmap:1398 - read uid map: type u nsid 0 hostid 100000 range 65536
            lxc 20150427012246.722 INFO     lxc_confile - confile.c:config_idmap:1398 - read uid map: type g nsid 0 hostid 100000 range 65536
            lxc 20150427012246.725 ERROR    lxc_utils - utils.c:get_template_path:1320 - No such file or directory - bad template: /tmp/lxd_lxc_startconfig_184392169
            lxc 20150427012246.725 ERROR    lxc_container - lxccontainer.c:do_lxcapi_create:1342 - bad template: /tmp/lxd_lxc_startconfig_184392169
```

**Comment by stgraber** [comment] 2015-06-10 21:54
Ah yeah, that'd probably be because I haven't pushed LXD 0.11 to the daily PPA yet. So you're getting a version of LXD 0.11 which is meant to be run with LXC 1.1.2, not with LXC from git.

**Comment by stgraber** [comment] 2015-06-10 22:03
Ok, so things are a bit messy and because I just screwed up the PPA copy (included binaries rather than triggering a full rebuild), the situation will only be fixed with the next LXD upload to Ubuntu.

This will very likely be tomorrow as I've got some systemd stuff to do in there anyway.

Once that's done, we should have:
 - lxd-git-master (LXD from git + LXC 1.1.2 and current cgmanager and lxcfs)
 - lxd-stable (currently identical to lxd-git-master)
 - daily (current daily version of all projects)
 - stable (current stable version of all projects)

All of them working and being consistent within themselves.

The one thing to keep in mind is that the same package name with the same version but in different PPAs will very likely differ, specifically because of varying ABI in the build dependencies.

That means, you should NEVER have more than one ubuntu-lxc PPA on your system and you should ALWAYS make sure that all linuxcontainers.org packages you have are coming from that one PPA.


So in your case, you seem to want to have both the latest LXD and latest LXC. The PPA which achieves that in a working way is the "ubuntu-lxc/daily" PPA.
Well, at least it will once 0.11-0ubuntu2 is uploaded and we can get it rebuilt against the rest of that PPA.

Hope this clarifies things a bit.

**Comment by stgraber** [comment] 2015-07-01 19:15
Finally fixed

**Closed by stgraber** 2015-07-01 19:15 UTC
Labels: Bug
