### ISSUE TITLE
upgrade stuck in postinst

### ISSUE THREAD

**Issue by panlinux** [lxc/lxd#3595] opened 2017-07-26 12:28 UTC
Ubuntu xenial 16.04 with the lxd-stable PPA. I had 2.15-0ubuntu6~ubuntu16.04.1~ppa1 and it's being upgraded to 2.16-0ubuntu1~ubuntu16.04.1~ppa1.

My morning dist-upgrade got stuck upgrading lxd:
```
Setting up libimage-magick-q16-perl (8:6.8.9.9-7ubuntu5.8) ...
Setting up libimage-magick-perl (8:6.8.9.9-7ubuntu5.8) ...
Setting up libmagickcore-6.q16-2-extra:amd64 (8:6.8.9.9-7ubuntu5.8) ...
Setting up lxd-client (2.16-0ubuntu1~ubuntu16.04.1~ppa1) ...
Setting up lxd (2.16-0ubuntu1~ubuntu16.04.1~ppa1) ...

Progress: [ 85%] [##############################################################################################################################.....................]
``` 

Process listing:
```
root      6026  0.2  0.4 115640 77920 pts/25   S+   09:15   0:01          |   |           \_ apt dist-upgrade
root     10506  0.0  0.0  26320 10936 pts/26   Ss+  09:16   0:00          |   |               \_ /usr/bin/dpkg --status-fd 83 --configure google-chrome-stable:amd64 imagemagick-common:all libmagickcore-6.q16-2:amd64 libmagickwand-6.q16-2:amd64 openjdk-8-jre-headless:amd64 openjdk-8-jre:amd64 imagemagick-6.q16:amd64 imagemagick:amd64 libimage-magick-q16-perl:amd64 libimage-magick-perl:all libmagickcore-6.q16-2-extra:amd64 lxd-client:amd64 lxd:amd64 perlmagick:all xserver-common:all xserver-xorg-legacy:amd64 xserver-xorg-core:amd64 libruby2.3:amd64 ruby2.3:amd64
root     11041  0.0  0.0   4508  1672 pts/26   S+   09:16   0:00          |   |                   \_ /bin/sh /var/lib/dpkg/info/lxd.postinst configure 2.15-0ubuntu6~ubuntu16.04.1~ppa1
root     11144  0.0  0.0  19140  4672 pts/26   S+   09:16   0:00          |   |                       \_ perl /usr/bin/deb-systemd-invoke restart lxd-containers.service
root     11147  0.0  0.0  26172  1344 pts/26   S+   09:16   0:00          |   |                           \_ /bin/systemctl restart lxd-containers.service
root     11148  0.0  0.0  15408  1088 pts/26   S+   09:16   0:00          |   |                               \_ /bin/systemd-tty-ask-password-agent --watch
```

I have a bunch of containers running, but can't list them now with lxd in this state (lxc list gets stuck too). Also, maybe it's relevant, the laptop was resumed from suspend, but that's not remarkable and just works.

UPDATE
While I was filing this bug, something eventually gave up:
```
Setting up lxd (2.16-0ubuntu1~ubuntu16.04.1~ppa1) ...
Job for lxd-containers.service failed because a timeout was exceeded. See "systemctl status lxd-containers.service" and "journalctl -xe" for details.
lxd-containers.service couldn't restart.
Setting up perlmagick (8:6.8.9.9-7ubuntu5.8) ...
Setting up xserver-common (2:1.18.4-0ubuntu0.3) ...
Setting up xserver-xorg-legacy (2:1.18.4-0ubuntu0.3) ...
setting xserver-xorg-legacy/xwrapper/allowed_users from configuration file
Setting up xserver-xorg-core (2:1.18.4-0ubuntu0.3) ...
Setting up libruby2.3:amd64 (2.3.1-2~16.04.2) ...
Setting up ruby2.3 (2.3.1-2~16.04.2) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...

root@nsn7:~# systemctl status lxd-containers.service
● lxd-containers.service - LXD - container startup/shutdown
   Loaded: loaded (/lib/systemd/system/lxd-containers.service; enabled; vendor preset: enabled)
   Active: failed (Result: timeout) since Qua 2017-07-26 09:26:34 BRT; 3min 4s ago
     Docs: man:lxd(1)
 Main PID: 11155 (code=killed, signal=TERM)

Jul 26 09:16:34 nsn7 systemd[1]: Starting LXD - container startup/shutdown...
Jul 26 09:26:34 nsn7 systemd[1]: lxd-containers.service: Start operation timed out. Terminating.
Jul 26 09:26:34 nsn7 systemd[1]: Failed to start LXD - container startup/shutdown.
Jul 26 09:26:34 nsn7 systemd[1]: lxd-containers.service: Unit entered failed state.
Jul 26 09:26:34 nsn7 systemd[1]: lxd-containers.service: Failed with result 'timeout'.
```
And this is all I have in lxd.log:
```
root@nsn7:~# cat /var/log/lxd/lxd.log
lvl=info msg="LXD 2.16 is starting in normal mode" path=/var/lib/lxd t=2017-07-26T09:26:35-0300
lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2017-07-26T09:26:35-0300
lvl=info msg="Kernel uid/gid map:" t=2017-07-26T09:26:35-0300
lvl=info msg=" - u 0 0 4294967295" t=2017-07-26T09:26:35-0300
lvl=info msg=" - g 0 0 4294967295" t=2017-07-26T09:26:35-0300
lvl=info msg="Configured LXD uid/gid map:" t=2017-07-26T09:26:35-0300
lvl=info msg=" - u 0 165536 65536" t=2017-07-26T09:26:35-0300
lvl=info msg=" - g 0 165536 65536" t=2017-07-26T09:26:35-0300

```

Trying to get it running now.

**Comment by brauner** [comment] 2017-07-26 12:31
Can you show `systemctl status lxd`, please?

**Comment by panlinux** [comment] 2017-07-26 12:34
It's kaput:
```
# systemctl status lxd
● lxd.service - LXD - main daemon
   Loaded: loaded (/lib/systemd/system/lxd.service; indirect; vendor preset: enabled)
   Active: activating (start-post) (Result: exit-code) since Qua 2017-07-26 09:33:34 BRT; 37s ago
     Docs: man:lxd(1)
  Process: 26078 ExecStart=/usr/bin/lxd --group lxd --logfile=/var/log/lxd/lxd.log (code=exited, status=1/FAILURE)
  Process: 26064 ExecStartPre=/usr/lib/x86_64-linux-gnu/lxc/lxc-apparmor-load (code=exited, status=0/SUCCESS)
 Main PID: 26078 (code=exited, status=1/FAILURE);         : 26079 (lxd)
    Tasks: 10
   Memory: 412.2M
      CPU: 106ms
   CGroup: /system.slice/lxd.service
           ├─ 5201 dnsmasq --strict-order --bind-interfaces --pid-file=/var/lib/lxd/networks/lxdbr0/dnsmasq.pid --except-interface=lo --interface=lxdbr0 --listen-address
           ├─ 5361 [lxc monitor] /var/lib/lxd/containers squid-ds216
           ├─23131 [lxc monitor] /var/lib/lxd/containers slapd-provider
           ├─24332 [lxc monitor] /var/lib/lxd/containers slapd-consumer
           └─control
             └─26079 /usr/bin/lxd waitready --timeout=600

Jul 26 09:33:34 nsn7 systemd[1]: Starting LXD - main daemon...
Jul 26 09:33:34 nsn7 lxd[26078]: lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2017-07-26T09:33:34-0300
Jul 26 09:33:34 nsn7 lxd[26078]: error: Unable to list containers on zpool: nsn7/lxd
Jul 26 09:33:34 nsn7 systemd[1]: lxd.service: Main process exited, code=exited, status=1/FAILURE
```
I'm now yielding the kill/restart hammer, trying to beat things into shape, but I might have to reboot.

**Comment by brauner** [comment] 2017-07-26 12:36
Yeah, so this is the same bug as #3594. Closing this as a duplicate of it. Please track it over there.

**Closed by brauner** 2017-07-26 12:36 UTC

**Comment by brauner** [comment] 2017-07-26 13:17
I missed the "kaput" joke. Excellent! :)
