### ISSUE TITLE
lxd high cpu usage

### ISSUE THREAD

**Issue by killua-eu** [lxc/lxd#3559] opened 2017-07-16 09:41 UTC
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04.02
 * The output of "lxc info" or if that fails:
```
lxc info
config:
  core.https_address: 0.0.0.0:28443
api_extensions:
- id_map
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 192.168.1.233:28443
  - 10.0.8.1:28443
  - 172.17.0.1:28443
  - 192.168.122.1:28443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
      ...
    -----END CERTIFICATE-----
  certificate_fingerprint: ...
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-83-generic
  server: lxd
  server_pid: 24738
  server_version: 2.0.10
  storage: btrfs
  storage_version: "4.4"
```

# Issue description

Noticed increased fan speed, top revealed lxd's cpu utilization 105+ %. Restarting lxd helps and drops the cpu usage to approx zero. Since I'm just about to leave for a vacation, I set up preemptively monit to watch over lxd and restart it if need be. Alas monit showed a completely different cpu load (around 13% due to how load is calculated), but this brought me to the fact that somehow lxd used 87 threads before monit restarted it. After restart, 14 threads are used and the number is slowly crawling up.

# Steps to reproduce

Didn't yet find a way to reproduce apart from letting lxd fly for 1 or 2 days.

# Information to attach

Dmesg was spammed with

```
[318559.922009] BTRFS error (device sda4): could not find root 8
[318559.932809] BTRFS error (device sda4): could not find root 8
[318559.940071] BTRFS error (device sda4): could not find root 8
[318559.942577] BTRFS error (device sda4): could not find root 8
[318559.949297] BTRFS error (device sda4): could not find root 8
[318559.956728] BTRFS error (device sda4): could not find root 8
[318559.962305] BTRFS error (device sda4): could not find root 8
[318559.963976] BTRFS error (device sda4): could not find root 8
[318559.970651] BTRFS error (device sda4): could not find root 8
[318559.973945] BTRFS error (device sda4): could not find root 8
[318559.982478] BTRFS error (device sda4): could not find root 8
[318560.003259] BTRFS error (device sda4): could not find root 8
```

not sure if this is relevant though.

**Comment by stgraber** [comment] 2017-07-16 13:35
Nope, your log isn't particularly relevant. I very strongly suspect that this is a duplicate of a signal handling issue in "lxc exec" which we've fixed a month or so ago and that will be included in LXD 2.0.11.

We've got some other users who hit this somewhat regularly. it's usually caused by background processes that got spawned as part of an exec session. LXD 2.15 has the fix for this and we've not seen any report of it appearing again with that version, so we're confident that once backport to the stable 2.0 branch and LXD 2.0.11 is released with it, the problem should go away for good.

**Closed by stgraber** 2017-07-16 13:35 UTC
