### ISSUE TITLE
some containers do not start anymore

### ISSUE THREAD

**Issue by alexanderhaensch** [lxc/lxd#5606] opened 2019-03-27 10:30 UTC
# Required information

 * Distribution: gentoo-amd64
 * Distribution version: current
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.19.13-gentoo
   * LXC version: 3.0.3
   * LXD version: 3.8
   * Storage backend in use: btrfs

# Issue description
Some Containers so Not start anymore after running for some time.
I recently upgraded to lxd 3.8  from lxd 3.7 but I think this is not really the problem.
I identified two Ubuntu 18.04 containers not starting anymore. At least one 16.04 container ist still starting. I tested launching fresh containers from images:/ alpine, fedora, debian,ubuntu working fine. Fresh image from ubuntu-daily (https://cloud-images.ubuntu.com/daily ) seems not to work. I fear that the not working containers were created from ubuntu-daily.

# Steps to reproduce

 1. lxd start container

# Information to attach

## cat /var/log/lxd//ubuntu-play/lxc.log
lxc ubuntu-play 20190327100855.449 ERROR    conf - conf.c:run_buffer:335 - Script exited with status 32
lxc ubuntu-play 20190327100855.449 ERROR    conf - conf.c:lxc_setup:3589 - Failed to run mount hooks
lxc ubuntu-play 20190327100855.449 ERROR    start - start.c:do_start:1263 - Failed to setup container "ubuntu-play"
lxc ubuntu-play 20190327100855.449 ERROR    sync - sync.c:__sync_wait:62 - An error occurred in another process (expected sequence number 5)
lxc ubuntu-play 20190327100855.449 WARN     network - network.c:lxc_delete_network_priv:2589 - Operation not permitted - Failed to remove interface "eth0" with index 69
lxc ubuntu-play 20190327100855.449 ERROR    lxccontainer - lxccontainer.c:wait_on_daemonized_start:842 - Received container state "ABORTING" instead of "RUNNING"
lxc ubuntu-play 20190327100855.449 ERROR    start - start.c:__lxc_start:1939 - Failed to spawn container "ubuntu-play"
lxc 20190327100855.453 WARN     commands - commands.c:lxc_cmd_rsp_recv:132 - Connection reset by peer - Failed to receive response for command "get_state"
## lxc config show ubuntu-play --expanded
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 18.04 LTS amd64 (daily) (20180630)
  image.label: daily
  image.os: ubuntu
  image.release: bionic
  image.serial: "20180630"
  image.version: "18.04"
  volatile.base_image: 529fc2fee5c9eeb9d998279499f7841325608a35633ddc26603f184e04a1dce5
  volatile.eth0.hwaddr: 00:16:3e:30:f4:66
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: STOPPED
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""

**Comment by stgraber** [comment] 2019-03-27 14:59
Can you upgrade to LXD 3.11? 3.8 isn't supported.

The error refers to a mount hook failure, LXD itself doesn't use such a hook but lxcfs does.
So this may have something to do with lxcfs on your system and would match someone else's report of a similar behavior (I think also on Gentoo).

A workaround would be to move the lxcfs file out of /usr/share/lxc/config/common.conf.d/ and see if your container then starts fine.

**Comment by stgraber** [comment] 2019-03-27 15:00
Tentatively closing as this was reported against an unsupported LXD version and the error messages are related to a LXC hook which LXD itself didn't put in place so nothing obviously actionable for LXD here.

We'll keep reading the comments though and can re-open if appropriate.

**Closed by stgraber** 2019-03-27 15:00 UTC

**Comment by EvaSDK** [comment] 2019-04-24 15:25
FTR, hit this issue today. Upgrading to LXD 3.11 did not fix it, same error message. I'll look into lxcfs.

**Comment by EvaSDK** [comment] 2019-04-24 15:51
Actually I had to solve this long ago and forgot about it. lxcfs does not create its path in /var/lib to mount cgroups on which stops it from working at all. See https://bugs.launchpad.net/ubuntu/+source/lxcfs/+bug/1756785 for example.

Sure enough. mkdir /var/lib/lxcfs and systemctl restart lxcfs.service later and I can start Ubuntu cloud images again.

**Comment by alexanderhaensch** [comment] 2019-04-25 06:09
I worked around the problem by commenting out the entries in:
/usr/share/lxc/config/common.conf.d/00-lxcfs.conf

I still wonder how the problem is triggered for some containers on certain hosts. There seems to be not much difference between lxd 3.8 to 3.12 and lxcfs 3.0.2 and 3.0.3

When is lxcfs triggered?

**Comment by felonwan** [comment] 2019-07-20 03:35
I got this issue twice: the first time, I copy the container and the copy can start; the seond time, the copied container cannot start after an unexpected poweroff of the host machine, and the 'solution' of the first time doesn't work anymore.

# Required information

Distribution: ubuntu 16.04 -amd64
The output of "lxc info":
...
  driver: lxc
  driver_version: 3.1.0
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "false"
    seccomp_listener: "false"
    shiftfs: "false"
    uevent_injection: "false"
    unpriv_fscaps: "true"
  kernel_version: 4.15.0-50-generic
  lxc_features:
    mount_injection_file: "true"
    network_gateway_device_route: "false"
    network_ipvlan: "false"
    network_l2proxy: "false"
    network_phys_macvlan_mtu: "false"
    seccomp_notify: "false"
  project: default
  server: lxd
  server_version: "3.15"
  storage: zfs
  storage_version: 0.7.5-1ubuntu16.4

# Issue description
This issue seems appeared after the update snap.

# Steps to reproduce
lxd start container


# Information to attach

## the results of 'lxc start lxj1':
Error: Failed to run: /snap/lxd/current/bin/lxd forkstart lxj1 /var/snap/lxd/common/lxd/containers /var/snap/lxd/common/lxd/logs/lxj1/lxc.conf: 
Try `lxc info --show-log lxj1` for more info


## lxc info --show-log lxj1
...
Log:

lxc lxj1 20190720031109.944 WARN     conf - conf.c:lxc_map_ids:2970 - newuidmap binary is missing
lxc lxj1 20190720031109.944 WARN     conf - conf.c:lxc_map_ids:2976 - newgidmap binary is missing
lxc lxj1 20190720031110.406 WARN     conf - conf.c:lxc_map_ids:2970 - newuidmap binary is missing
lxc lxj1 20190720031110.407 WARN     conf - conf.c:lxc_map_ids:2976 - newgidmap binary is missing
lxc lxj1 20190720031110.210 ERROR    conf - conf.c:run_buffer:335 - Script exited with status 1
lxc lxj1 20190720031110.210 ERROR    conf - conf.c:lxc_setup:3642 - Failed to run mount hooks
lxc lxj1 20190720031110.210 ERROR    start - start.c:do_start:1282 - Failed to setup container "lxj1"
lxc lxj1 20190720031110.210 ERROR    sync - sync.c:__sync_wait:62 - An error occurred in another process (expected sequence number 5)
lxc lxj1 20190720031110.282 ERROR    start - start.c:__lxc_start:1975 - Failed to spawn container "lxj1"
lxc lxj1 20190720031110.282 ERROR    lxccontainer - lxccontainer.c:wait_on_daemonized_start:864 - Received container state "ABORTING" instead of "RUNNING"
lxc lxj1 20190720031110.322 WARN     conf - conf.c:lxc_map_ids:2970 - newuidmap binary is missing
lxc lxj1 20190720031110.322 WARN     conf - conf.c:lxc_map_ids:2976 - newgidmap binary is missing
lxc 20190720031110.328 WARN     commands - commands.c:lxc_cmd_rsp_recv:132 - Connection reset by peer - Failed to receive response for command "get_state"

**Comment by felonwan** [comment] 2019-07-21 12:20
Ok, my problem is in fact caused by the command:
lxc config set container-name nvidia.runtime true

This command cannot mount '/dev/nvidia_drm' and 'nvidia-uvm-tools' to the container.

**Comment by felonwan** [comment] 2019-08-06 11:48
> Ok, my problem is in fact caused by the command:
> lxc config set container-name nvidia.runtime true
> 
> This command cannot mount '/dev/nvidia_drm' and 'nvidia-uvm-tools' to the container.
> 
> I reinstalled the NVIDIA driver, and tested 430.34, 418.74, 410.78 and 390.48, none of them can start the container.

I 

> Ok, my problem is in fact caused by the command:
> lxc config set container-name nvidia.runtime true
> 
> This command cannot mount '/dev/nvidia_drm' and 'nvidia-uvm-tools' to the container.
> 
> I reinstalled the NVIDIA driver, and tested 430.34, 418.74, 410.78 and 390.48, none of them can start the container.

Al last, I found that the real problem is the broken assigned gpu device. Delete the broken device, add a new device just works.
