### ISSUE TITLE
Websocket closed after hardware resume from suspend

### ISSUE THREAD

**Issue by crass** [lxc/lxd#9622] opened 2021-12-03 18:57 UTC
# Required information

 * Distribution: Ubuntu
 * Distribution version: Focal
 * The output of "lxc info" or if that fails:
   * [lxc.info.log](https://github.com/lxc/lxd/files/7651654/lxc.info.log)

# Issue description

I noticed that my shell into a container had died with error output `Error: websocket: close 1006 (abnormal closure): unexpected EOF`. Looking in the logs I see:
```
Dec  2 10:21:38 box1 lxd.daemon[7371]: t=2021-12-02T10:21:30-0600 lvl=eror msg="Failed to open file" driver=fanotify err="stale NFS file handle"
Dec  2 10:21:38 box1 lxd.daemon[7371]: message repeated 3 times: [ t=2021-12-02T10:21:30-0600 lvl=eror msg="Failed to open file" driver=fanotify err="stale NFS file handle"]
Dec  3 11:36:40 box1 lxd.daemon[7371]: t=2021-12-03T11:36:32-0600 lvl=eror msg="Failed to open file" driver=fanotify err="stale NFS file handle"
Dec  3 11:36:40 box1 lxd.daemon[7371]: t=2021-12-03T11:36:32-0600 lvl=eror msg="Failed to open file" driver=fanotify err="stale NFS file handle"
Dec  3 11:36:40 box1 lxd.daemon[7371]: t=2021-12-03T11:36:32-0600 lvl=warn msg="Hearbeat for event listener timed out" listener=8866cff2-86e0-459e-9400-3a9a0ce31811
Dec  3 11:36:40 box1 lxd.daemon[7371]: t=2021-12-03T11:36:32-0600 lvl=warn msg="Hearbeat for event listener timed out" listener=b510a97a-209f-4abe-bb8f-50081e3d3e9b
Dec  3 11:36:40 box1 lxd.daemon[7371]: t=2021-12-03T11:36:32-0600 lvl=warn msg="Hearbeat for event listener timed out" listener=143c0195-071a-4039-97b0-c46a42a2fe30
Dec  3 11:36:40 box1 lxd.daemon[7371]: t=2021-12-03T11:36:32-0600 lvl=warn msg="Detected poll(POLLNVAL) event."
Dec  3 11:36:40 box1 lxd.daemon[7371]: message repeated 2 times: [ t=2021-12-03T11:36:32-0600 lvl=warn msg="Detected poll(POLLNVAL) event."]
Dec  3 11:36:40 box1 lxd.daemon[7371]: t=2021-12-03T11:36:32-0600 lvl=warn msg="Detected poll(POLLNVAL) event: exiting."
Dec  3 11:36:40 box1 lxd.daemon[7371]: message repeated 2 times: [ t=2021-12-03T11:36:32-0600 lvl=warn msg="Detected poll(POLLNVAL) event: exiting."]
```

This happened right after resuming from suspend, so I think it may be related. Also, I am not using NFS, so this is not in anyway related to NFS.

# Steps to reproduce

I've not been able to reproduce this by doing a suspend/resume cycle, so this may be unrelated to resume. I've not been able to reproduce the websocket close, but after the second resume LXD does output the `stale NFS file handle` log message.

1. Suspend
2. Resume

# Information to attach

 - [x] Any relevant kernel output (`dmesg`) 
[lxd.stale-nfs-fh.syslog.log](https://github.com/lxc/lxd/files/7651774/lxd.stale-nfs-fh.syslog.log)

 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [x] [Main daemon log](https://github.com/lxc/lxd/files/7651705/lxd.log) (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by stgraber** [comment] 2021-12-03 19:58
Can you show:
 - journalctl -u snap.lxd.daemon -n 300
 - ps fauxww | grep lxd

**Comment by crass** [comment] 2021-12-03 20:11
Here are the requested logs.
[snap.lxd.daemon.log](https://github.com/lxc/lxd/files/7652104/snap.lxd.daemon.log)
[lxd.ps.log](https://github.com/lxc/lxd/files/7652105/lxd.ps.log)

**Comment by stgraber** [comment] 2021-12-03 20:15
And what was the date and time of the problematic suspend/resume which caused this disconnection?
To track things down we'd need a timestamp when the terminal was last known to be functional and timestamp for when you notice it got disconnected.

**Comment by crass** [comment] 2021-12-03 20:46
It was last known to be functional on Dec 2 before the computer was suspended. The resume that I believe triggered the issue was the one subsequent to that suspend and it was just before Dec  3 11:36:32. I didn't notice the disconnect until some minutes later, not after Dec  3 12:37:30 and probably not after Dec  3 12:24:52 (but unsure of the latter date),

**Comment by stgraber** [comment] 2021-12-03 21:42
Ok, so the issue looks like:
```
Dec 03 11:36:40 box1 lxd.daemon[7371]: t=2021-12-03T11:36:32-0600 lvl=warn msg="Hearbeat for event listener timed out" listener=8866cff2-86e0-459e-9400-3a9a0ce31811
Dec 03 11:36:40 box1 lxd.daemon[7371]: t=2021-12-03T11:36:32-0600 lvl=warn msg="Hearbeat for event listener timed out" listener=b510a97a-209f-4abe-bb8f-50081e3d3e9b
Dec 03 11:36:40 box1 lxd.daemon[7371]: t=2021-12-03T11:36:32-0600 lvl=warn msg="Hearbeat for event listener timed out" listener=143c0195-071a-4039-97b0-c46a42a2fe30
```

I think that's coming from some new logic @tomponline added recently. Basically there are heartbeats going on between `lxc exec` and `lxd` so that we can detect when a client's connection broke for one reason or another and can terminate the operation on the server side.

In this case, it looks like the heartbeats either didn't trigger immediately following system resume or the server side got confused by the time jump.

@tomponline ideas?

**Comment by tomponline** [comment] 2021-12-04 07:19
I think the issue is that the current implementation relies on absolute times for calculating timeouts. Instead if we used in flight request counters it wouldn't matter how long between each request if both client and server were asleep.

**Comment by tomponline** [comment] 2021-12-06 15:24
Just to be clear here, is the `lxc` shell into the container running on the same host as the `lxd` server and the container?

**Comment by tomponline** [comment] 2021-12-06 15:45
Although I've not been able to reproduce by pausing a LXD VM running LXD container inside of it using `lxc pause` I've put up https://github.com/lxc/lxd/pull/9632 as a speculative fix for this.

**Comment by crass** [comment] 2021-12-06 17:08
> Just to be clear here, is the `lxc` shell into the container running on the same host as the `lxd` server and the container? And if not, which one is going into suspend?

Yes, `lxc` shell was running on the same host as the `lxd` server. I've not been able to reproduce it either (via a several suspend/resume cycles). I'm thinking it might be triggered by a race condition.

**Closed** 2021-12-07 04:00 UTC
Labels: Bug
