### ISSUE TITLE
Live Migration Fails for Ubuntu 16.10 Container

### ISSUE THREAD

**Issue by jsaintrocc** [lxc/lxd#3086] opened 2017-03-17 22:52 UTC
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04.2 (Host) 16.10 (container)
 * lxc info: http://pastebin.com/nc2CzZA7
 * Storage backend in use: zfs

# Issue description

Doing a live migration of an ubnutu 16.10 container (With apparmor disabled) fails with the message `error: Error transferring container data: websocket: bad handshake`.  Looking at the container log I see:
   ```
   lxc 20170317222336.451 WARN     lxc_start - start.c:signal_handler:322 - Invalid pid for SIGCHLD. Received pid 64562, expected pid 64576.
            lxc 20170317222816.507 ERROR    lxc_criu - criu.c:do_dump:1124 - dump failed with 1
            lxc 20170317222816.507 ERROR    lxc_criu - criu.c:do_dump:1138 - criu output: Will skip in-flight TCP connections
   ```

# Steps to reproduce

 1. Launch the instance (With apparmor disabled profile)
   ```
   lxc launch ubuntu:16.10 lxdnode1:movetest1610
   ```
 
 2. Disable apparmor
   ```
   lxc exec lxdnode1:movetest1610 -- /etc/init.d/apparmor stop
   [ ok ] Stopping apparmor (via systemctl): apparmor.service.
   lxc exec lxdnode1:movetest1610 -- /etc/init.d/apparmor teardown
    * Unloading AppArmor profiles
   lxc exec lxdnode1:movetest1610 -- apt-get -y purge apparmor
   ...
   Removing apparmor (2.10.95-4ubuntu5.1) ...
   Purging configuration files for apparmor (2.10.95-4ubuntu5.1) ...
   ...
   ```

 3. Move Container
    ```
    lxc move lxdnode1:movetest1610 lxdnode2:
    error: Error transferring container data: websocket: bad handshake

# Information to attach

 - lxc info lxdnode1:movetest1610 --show-log
   http://pastebin.com/Upkqr5CK
 - lxc move lxdnode1:movetest1610 lxdnode2: --verbose --debug
   http://pastebin.com/YcrDkr8F

**Comment by stgraber** [comment] 2017-03-17 22:57
We'd need the CRIU logs (migration_ in /var/log/lxd/NAME/) to see what CRIU bug you're hitting.

**Comment by pgassmann** [comment] 2017-03-18 16:09
Same handshake error here. 

16.04 host and container. source: lxd 2.0.9 (main), target: lxd 2.11 (ppa)
Host-Kernel: both: 4.8 (linux-generic-hwe-16.04)

lxc info webtest --show-log
http://pastebin.com/W28UzqYK

migration dump:
http://pastebin.com/9vppAn0d

Last part:
```
(00.154348) Dumping task (pid: 22611)
(00.154355) ========================================
(00.154361) Obtaining task stat ...
(00.154431)
(00.154439) Collecting mappings (pid: 22611)
(00.154445) ----------------------------------------
(00.154674) Error (criu/cr-dump.c:1210): Collect mappings (pid: 22611) failed with -1
(00.154889) Unlock network
(00.154898) Running network-unlock scripts
(00.154911)     [/tmp/lxd_checkpoint_701785680/action.sh]
(00.165747) Unfreezing tasks into 1
(00.165783)     Unseizing 22611 into 1
(00.165802)     Unseizing 23839 into 1
(00.165815)     Unseizing 24059 into 1
(00.165826)     Unseizing 24197 into 1
(00.165843)     Unseizing 24200 into 1
(00.165858)     Unseizing 24265 into 1
(00.165873)     Unseizing 24312 into 1
(00.165925)     Unseizing 24339 into 1
(00.165942)     Unseizing 24347 into 1
(00.165963)     Unseizing 24391 into 1
(00.165979)     Unseizing 24396 into 1
(00.165989)     Unseizing 24394 into 1
(00.165998)     Unseizing 24395 into 1
(00.166010)     Unseizing 24416 into 1
(00.166023)     Unseizing 24442 into 1
(00.166036)     Unseizing 24443 into 1
(00.166103) Error (criu/cr-dump.c:1628): Dumping FAILED.
```

**Comment by stgraber** [comment] 2017-03-19 01:41
There have been a number of similar reports from people running the 4.8 kernel on Ubuntu 16.04. The 4.4 kernel tends to work a bit better.

Note that CRIU support is considered experimental and that such issues are issues in CRIU itself rather than LXD. The LXD team at Canonical has been instructed not to spend time working on upstream CRIU bugs or missing features unless we have paying customers asking for those fixes, so unless those issues are fixed by someone else, things are unlikely to improve.

**Comment by pgassmann** [comment] 2017-03-19 17:39
when I `lxc copy` a running container to a different host, It automatically tries to do a stateful copy. `lxc copy` has no option to ignore the running state.

A workaround is to create a local copy first and then copy/move that to the other host.

Regardless of upstream bugs, the error message could be more helpful, indicating that something with CRIU went wrong.

**Comment by jsaintrocc** [comment] 2017-03-20 20:24
My initial bug report wasn't for live migrating a copy.  Can you please reopen this?

**Comment by stgraber** [comment] 2017-03-20 20:36
Re-opened and marked incomplete since you never provided the information I asked for.

**Comment by stgraber** [comment] 2017-03-20 20:38
The error suggests a CRIU failure which wouldn't be a LXD bug but a CRIU bug (to be tracked at https://launchpad.net/ubuntu/+source/criu/+filebug) and taking into account that note from an earlier comment I gave that we don't work on those issues unless it's for a paid customer.

**Comment by jsaintrocc** [comment] 2017-03-20 20:52
Thank you.  Sorry for the delay: Here is the information you asked for:

http://pastebin.com/Bzvg16n1

For some reason attachments simply aren't working in github so I've pasted as much as I could in pastebin.  It includes the end but not the beginning.

If it's a question of me putting a ticket in to criu I'm happy to do that but could use a little help on figuring out what to even report as a bug.

Thanks, James.

**Comment by jsaintrocc** [comment] 2017-03-20 20:58
Just noticed the version of criu is pretty old (This is true of 16.04 and 16.10)
root@cntnode-cc38-h01:/var/log/lxd/lmtest1610# criu --version
Version: 2.6

Current release is 2.12.

**Comment by stgraber** [comment] 2017-03-20 21:03
```
(03.191552) Running post-dump scripts
(03.191565)     [/tmp/lxd_checkpoint_445851178/action.sh]
(04.718658) Error (criu/action-scripts.c:116): One of more action scripts failed
(04.718737) Post dump script passed with 1
```

@tych0 does that ring a bell?

**Comment by stgraber** [comment] 2017-03-20 22:53
Reproduced your environment here with an extra fix which improves error handling:
```
stgraber@dakara:~/data/code/lxc/lxd (stgraber/new-client)$ lxc move l-djanet:c1 l-nuturo:
error: migration dump failed
(00.144318) Warn  (criu/autofs.c:77): Failed to find pipe_ino option (old kernel?)
(00.831775) Error (criu/parasite-syscall.c:532): Unable to connect a transport socket: Permission denied
(00.831784) Error (criu/parasite-syscall.c:134): Can't block signals for 2566: No such process
(00.831789) Error (criu/cr-dump.c:1244): Can't infect (pid: 2566) with parasite
(00.837235) Error (criu/ptrace.c:54): Unable to detach from 2566: No such process
(00.837528) Error (criu/cr-dump.c:1628): Dumping FAILED.
```

**Comment by stgraber** [comment] 2017-03-20 22:54
though I'm not getting the parasite error here when looking at the full log

**Comment by stgraber** [comment] 2017-03-20 22:55
ah probably because I don't get that far into the code due to apparmor, trying to disable that now

**Comment by stgraber** [comment] 2017-03-20 22:57
Right, exact same error as the reporter now but with the fixed error handling on LXD's side, the reported error to the user is accurate:
```
stgraber@dakara:~/data/code/lxc/lxd (stgraber/new-client)$ lxc move l-djanet:c1 l-nuturo:
error: migration restore failed
(00.036444) Warn  (criu/apparmor.c:421): apparmor namespace /sys/kernel/security/apparmor/policy/namespaces/lxd-c1_<var-lib-lxd> already exists, restoring into it
(00.039222) Warn  (criu/cr-restore.c:853): Set CLONE_PARENT | CLONE_NEWPID but it might cause restore problem,because not all kernels support such clone flags combinations!
(00.118647)      1: Warn  (criu/autofs.c:77): Failed to find pipe_ino option (old kernel?)
(00.121858) Error (criu/cr-restore.c:1024): 2107 killed by signal 11: Segmentation fault
(00.135932) Error (criu/cr-restore.c:1024): 2107 killed by signal 9: Killed
(00.176010) Error (criu/mount.c:3275): mnt: Can't remount root with MS_PRIVATE: No such file or directory
(00.176019) Error (criu/mount.c:3285): mnt: Can't unmount .criu.mntns.J9jl2B: No such file or directory
(00.176027) Error (criu/mount.c:3290): mnt: Can't remove the directory .criu.mntns.J9jl2B: No such file or directory
(00.176530) Error (criu/cr-restore.c:1890): Restoring FAILED.
```

**Comment by stgraber** [comment] 2017-03-20 23:03
Going to tweak the error handling a bit more to show whether the error comes from the source or the target as CRIU confusingly runs some restore code on the source leading to "migration restore failed" on the source host :)

```
stgraber@dakara:~/data/code/lxc/lxd (stgraber/new-client)$ lxc move l-djanet:c1 l-nuturo:
error: Migration failed on source host: migration restore failed
(00.031670) Warn  (criu/apparmor.c:421): apparmor namespace /sys/kernel/security/apparmor/policy/namespaces/lxd-c1_<var-lib-lxd> already exists, restoring into it
(00.034468) Warn  (criu/cr-restore.c:853): Set CLONE_PARENT | CLONE_NEWPID but it might cause restore problem,because not all kernels support such clone flags combinations!
(00.085492)      1: Warn  (criu/autofs.c:77): Failed to find pipe_ino option (old kernel?)
(00.088845) Error (criu/cr-restore.c:1024): 2290 killed by signal 11: Segmentation fault
(00.109173) Error (criu/cr-restore.c:1024): 2290 killed by signal 9: Killed
(00.149206) Error (criu/mount.c:3275): mnt: Can't remount root with MS_PRIVATE: No such file or directory
(00.149215) Error (criu/mount.c:3285): mnt: Can't unmount .criu.mntns.1Ytyco: No such file or directory
(00.149223) Error (criu/mount.c:3290): mnt: Can't remove the directory .criu.mntns.1Ytyco: No such file or directory
(00.149717) Error (criu/cr-restore.c:1890): Restoring FAILED.
```

And for a target error:
```
stgraber@dakara:~/data/code/lxc/lxd (stgraber/new-client)$ lxc move l-djanet:c1 l-nuturo:
error: Migration failed on target host: Error transferring container data: Unable to connect to: [2607:f2c0:f00f:2716:223:8bff:fef3:d6b3]:8443
```

**Comment by jsaintrocc** [comment] 2017-03-20 23:03
"Can't infect with parasite" is typical apparmor getting in the way.  Isn't it?

**Comment by stgraber** [comment] 2017-03-20 23:05
@jsaintrocc correct and that was before I removed apparmor from inside the container, so that makes sense. After removing apparmor from the container, I'm now getting the error trace which shows CRIU segfaulting during dump.

**Comment by jsaintrocc** [comment] 2017-03-20 23:06
Gotcha.  And it's segfaulting trying to connect with IPv6.  I'm headed home for the day but I can try disabling IPv6 tomorrow to see if that is a temporary remedy.

**Comment by stgraber** [comment] 2017-03-20 23:08
Part of the trace also reminds me of some issues we've seen before at https://launchpad.net/ubuntu/+source/criu/+bugs

I'm looking at refreshing our CRIU in Ubuntu 17.04 now so that we're at least in sync with Debian (2.12), if that ends up solving some of that, I'll look into getting the SRU to Ubuntu 16.04.

**Comment by stgraber** [comment] 2017-03-20 23:08
(Again, I'd be doing that on my spare time since we don't have any customer engagements to pay for this...)

**Comment by stgraber** [comment] 2017-03-20 23:09
As for this bug, I'm going to be marking my LXD error handling bugfix as fixing this bug since it now has LXD surface the right error message, making this a CRIU issue.

**Closed** 2017-03-20 23:39 UTC
Labels: Incomplete

**Comment by stgraber** [comment] 2017-03-20 23:53
I've uploaded CRIU 2.12 to Ubuntu 17.04 but note that it does not fix this problem for me, instead I'm now getting:
```
stgraber@dakara:~/data/code/lxc/lxd-pkg-ubuntu (dpm-zesty)$ lxc move l-djanet:c2 l-nuturo:
error: Migration failed on source host: migration dump failed
(00.016320) Warn  (criu/autofs.c:79): Failed to find pipe_ino option (old kernel?)
(00.018999) Warn  (criu/arch/x86/crtools.c:138): Will restore 6697 with interrupted system call
(00.373088) Warn  (criu/arch/x86/crtools.c:138): Will restore 7008 with interrupted system call
(00.817357) Error (criu/tty.c:2222): tty: Unable to find a master for /3
(00.821610) Error (criu/cr-dump.c:1641): Dumping FAILED.
```

Which feels like a new issue that's hitting before the previous problem, so doesn't look like I'll be pushing 2.12 as an SRU unless someone figures out that one upstream.

**Comment by stgraber** [comment] 2017-03-22 04:49
I tracked down that issue and reverted the problematic commit.

You can get the CRIU 2.12 build at https://launchpad.net/ubuntu/+source/criu/2.12-1ubuntu2/+build/12156767/+files/criu_2.12-1ubuntu2_amd64.deb

It will install fine on Ubuntu 16.04 too (was built for Ubuntu 17.04), you just need to install libnet1 as it's a new dependency.

**Comment by adityacloud1** [comment] 2018-06-16 05:49
I am getting the same error as: 
![snapshot dump failed](https://user-images.githubusercontent.com/40225508/41496183-2ac06502-7157-11e8-8fec-f1f4b0271dff.png)
