### ISSUE TITLE
lxc cluster remove won't remove node

### ISSUE THREAD

**Issue by maran** [lxc/lxd#6975] opened 2020-03-04 09:26 UTC
I have a lxc cluster test cluster with four nodes, I wanted to remove one of them.

I tried the following:

```
$ lxc cluster remove ubuntu
Error: Node still has the following custom volumes: maran-test, bcc-maran-5002, bcc-maran-5002/snappyshotty, bcc-testpete-2, test-pool, to-be-renamed
```

These are all Ceph volumes which as far as lxc are concerned are present on all nodes so it should be safe to delete these nodes as the volumes would be unaffected by this.

When I got this error I tried it again with the `--force` added to the mix. This seem to do something but not what I expected. My whole cluster went into a bad state

```
t=2020-03-04T09:05:34+0000 lvl=dbug msg="Retry failed db interaction (driver: bad connection)"
t=2020-03-04T09:05:34+0000 lvl=dbug msg="Database error: &errors.errorString{s:\"driver: bad connection\"}"
t=2020-03-04T09:05:34+0000 lvl=dbug msg="Retry failed db interaction (driver: bad connection)"
```

After restarting all nodes it recovered however as for as the cluster is concerned the fourth server is still part of it.

```
...
+--------------------------+-----------------------------+----------+--------+-------------------+--------------+
| ubuntu                   | https://x.x.x.x:8443 | YES      | ONLINE | fully operational | x86_64       |
+--------------------------+-----------------------------+----------+--------+-------------------+--------------+
```

However issuing any commands on that specific server fails. 

```
root@ubuntu:~# lxc list
Error: cannot fetch node config from database: driver: bad connection
```

So I guess there are two separate issues:

1. I think that `lxc cluster remove` should ignore custom volumes on Ceph as they are not tied to the node itself.
2. A bug might exist where if you force a node removal it doesn't properly remove it from the cluster.

**Comment by freeekanayaka** [comment] 2020-03-04 09:43
First thing: if you use ```--force``` it means that the server being removed is gone **forever** and it's not supposed to be brought up anymore. So just reset/wipe away that specific server and don't run any command from it.

Did ```lxc cluster remove ubuntu --force``` return successfully or did it throw an error too? If it returned successfully you should not see that server anymore in ```lxc cluster list```.

As per ```lxc cluster remove``` with Ceph volumes, it might indeed make sense to relax the concept of "empty node". @stgraber, what do you think?

**Comment by maran** [comment] 2020-03-04 09:54
> First thing: if you use `--force` it means that the server being removed is gone **forever** and it's not supposed to be brought up anymore. So just reset/wipe away that specific server and don't run any command from it.

Yeah that was what I was intending.

> Did lxc cluster remove ubuntu --force return successfully or did it throw an error too? If it returned successfully you should not see that server anymore in lxc cluster list.

I just tried this again because I couldn't remember and it worked successfully this time. Since it's gone now I can't really replicate it again to see what caused the behaviour in the first place, sorry for that.

**Comment by freeekanayaka** [comment] 2020-03-04 09:55
It could be that:

1) the node being remove was still running when you ran ```lxc cluster remove ubuntu --force```, which is always bad (when you ran the command you should have been warned about that)

2) the node being remove was the cluster leader

That would explain why you temporarily got the ```bad connection``` error.

Maybe we should add additional confirmation prompts to ```lxc cluster remove --force```, because people seem to be running it a bit lightheartedly.

**Comment by maran** [comment] 2020-03-04 09:56
> Maybe we should add additional confirmation prompts to lxc cluster remove --force, because people seem to be running it a bit lightheartedly.

For me the warnings were plenty, it is a staging cluster so I wasn't too concerned. I also was not sure I could remove it normally since I had Ceph volumes mounted. If a normal removal works with Ceph I never had to use force to begin with.

**Comment by freeekanayaka** [comment] 2020-03-04 09:58
I'd say to the least we should add an additional prompt like: ```Do you confirm this node is not running right now and will never come back? [Yes/No]. ```

**Comment by freeekanayaka** [comment] 2020-03-04 10:05
> I just tried this again because I couldn't remember and it worked successfully this time. Since it's gone now I can't really replicate it again to see what caused the behaviour in the first place, sorry for that.

Probably the node being remove was the leader and the behavior is a bit undefined if that happen, or at least it's not something we tested nor the code is particularly prepared for. So the original run of ```remove --force``` might have been successful or not, but in both cases the resulting state was likely to be a bit broken (and indeed you were still seeing the node in ```lxc cluster list```).

**Comment by maran** [comment] 2020-03-04 10:07
> I'd say to the least we should add an additional prompt like: `Do you confirm this node is not running right now and will never come back? [Yes/No]. `

That might be good, I must admit I did not fully read the text (tl;dr) and since it was a staging cluster anyway I wasn't too bothered by the results.

**Comment by freeekanayaka** [comment] 2020-03-04 10:12
Probably we can make an additional check, if the node being force-removed is the leader or is not considered offline, the force will fail. That should cover a lot of misuse cases.

**Comment by stgraber** [comment] 2020-03-04 10:35
@freeekanayaka can you take a look at the ceph side of this? We shouldn't flag volume on remove if those are on ceph.

**Comment by freeekanayaka** [comment] 2020-03-04 10:50
@stgraber it seems we don't currently special case ceph in the ```ClusterTx.NodeIsEmpty()``` check:

```go
	// Check if the node has any custom volumes.
	volumes, err := query.SelectStrings(
		c.tx, "SELECT name FROM storage_volumes WHERE node_id=? AND type=?",
		id, StoragePoolVolumeTypeCustom)
	if err != nil {
		return "", errors.Wrapf(err, "Failed to get custom volumes for node %d", id)
	}
	if len(volumes) > 0 {
		message := fmt.Sprintf(
			"Node still has the following custom volumes: %s", strings.Join(volumes, ", "))
		return message, nil
	}
```

**Comment by stgraber** [comment] 2020-03-04 10:52
Right, we should do something in there.

**Comment by stgraber** [comment] 2020-03-04 10:53
The new drivers have a field in their Info struct which tells us if they're remote or not.
If remote, we should ignore their volumes.

**Comment by stgraber** [comment] 2020-03-17 02:10
Reproduced the error:

```
root@vm01:~# lxc cluster remove vm02
Error: Node still has the following custom volumes: blah
```

Will sort out a fix for this tomorrow.

**Closed** 2020-03-17 19:43 UTC
Labels: Bug, Easy
