### ISSUE TITLE
Unable to start containers after Hardware reboot

### ISSUE THREAD

**Issue by syswipe** [lxc/lxd#6056] opened 2019-08-09 12:49 UTC
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04.6
 * The output of "lxc info" or if that fails:
```
config:
  cluster.https_address: 10.0.0.20:8443
  core.https_address: 10.0.0.20:8443
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 10.0.0.20:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFUzCCAzugAwIBAgIRAKa2GJpBtESWVBUr/5QftiAwDQYJKoZIhvcNAQELBQAw
    NjEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEWMBQGA1UEAwwNcm9vdEBq
    b2JwdWx6MTAeFw0xODA2MjAxNDI4NDlaFw0yODA2MTcxNDI4NDlaMDYxHDAaBgNV
    BAoTE2xpbnV4Y29udGFpbmVycy5vcmcxFjAUBgNVBAMMDXJvb3RAam9icHVsejEw
    ggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDGH57cSdm2CTCUsoR+N9Y3
    JNWoXFKmcGa4F4/ZM1IyhzK7ZpWesXNPw1llmKoeUIzt6041XwOR3tk/pU95WDha
    ZXD2ilNiP8ws/5mHWTgfy/56SNbLZIJe6/WfIl9E7eCZewYjCg5XVWw6l+FMzFJk
    E11k6cPsbkIiUMBRzi/3OsfgoBTe34YO5yN7cTi9Y/EtSuCiY2Xav8TTRZ0w4jf3
    FjUyUKNe8+2oQQXgZRypE9o3tjKtP8tAUq3IS3beasin+K0s7fHTrCvHJijFc2gV
    s9jMU+e4HM+o97jsgxHpIpJTA9LUe5bJNvCgLEOX9MmkReyZjBqE5GVzrj3hE+he
    ByAoPN+D8x8AOagNFYPWsprXnvlUgVAxYqzBw5mUT2yzo3iQ+ECiyYic+U++KFSt
    9MRjp0k53uxoB23DqtFc/boM1A4/BerLm/CxiBMP5cYUJc5IC9x1yQXU+j/TgwfN
    dVejyFAYXgn/rbUO8xKTzvNQ3UcDp+3c0hmzZTursTdjmUJISGChltxmr3HefJqs
    V6dbi0XBSVbO9wYjj4CUBPqAEZ6zT6uxkb1V9NyXM0i1tsyV3CFBIu/8aHt947yZ
    XLhZDP5A6BUCP+itt1LTf2ETVBc3dh76XSv7M6jFbb1xfjUJ4RFPuX9yyr1wC2xh
    RXgD/rNoTwwi3qrUqwp/awIDAQABo1wwWjAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0l
    BAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADAlBgNVHREEHjAcgghqb2JwdWx6
    MYcEW719IocECgAAFIcECgAACjANBgkqhkiG9w0BAQsFAAOCAgEAV3M3/lM88wwf
    nAoZJfp8y3jJG8lk418aZT6Ki3BL6//I2ldslgkEcXMAPc7ovr+Xy9AhbMvdOc6h
    oiiDG8njrgaoHBp5LascU5b5F9heQo47BpWM+UOB7jtp1/r4O4E6yichB9wElwrs
    M2op9AnG2CcnqNKW3XTbdWY7eEuwbml3mjGuUJBKGV29qwT9G8+q2/PB1R+7SnTm
    f5gISCYkwiPlixGqRQh0kX63djN2SCqNy5lzDJDRQS07qtHULcmrNEHxf/wt7P1Y
    rtIjBqr1sS2qT04VtQxApsKhlBvouhWYJjhrbj6SaiMv1R5zSUOv73VdICHawnN8
    wosM7RlL4f8jVFc/daIWe8SIqjObUbYXDF5y74v0xM8bSS7ZbQYN61J8Tr+Sfhxk
    H4dDHIQEPKNJ0tauGnU4ZCs/8htGjoVpiN8E9T8DTuetfOpJno2np1PIDMGJ1dKs
    GvWZS398O/dV8bgwh5n4PJaz9TeosqqFmYv9fxu3f73oFDyWvN83QSbACU+H1P4p
    9g75ktTUq13SMztyxO2x7BTm4MsTmo4m7AAnH93I+VVJU0aMdnM9TBcDra8r8GC+
    rDwjqPFjso66d/F3iRcXUCgFrK1NEswFcirOT6ts2b6f039gFZ1/Dp6Ync/r6LOJ
    9rcXw9i4lanGNXaHoOnVdOcSoipsf9E=
    -----END CERTIFICATE-----
  certificate_fingerprint: b5e4f4aa59774e57312c6ee25c2060dcfd36db54150c988a5456d351d6b56697
  driver: lxc
  driver_version: 3.2.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "false"
    seccomp_listener: "false"
    shiftfs: "false"
    uevent_injection: "false"
    unpriv_fscaps: "true"
  kernel_version: 4.4.0-140-generic
  lxc_features:
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    seccomp_notify: "true"
  project: default
  server: lxd
  server_clustered: true
  server_name: cl-node-2
  server_pid: 57061
  server_version: "3.15"
  storage: lvm
  storage_version: 2.02.133(2) (2015-10-30) / 1.02.110 (2015-10-30) / 4.34.0

```
# Issue description

After the unplanned hardware reboot, I'm not able to start some LXC containers. Also, i can't copy/move containers between nodes

# Steps to reproduce

```
lxc start rmq-2 
Error: Failed to run: /snap/lxd/current/bin/lxd forkstart rmq-2 /var/snap/lxd/common/lxd/containers /var/snap/lxd/common/lxd/logs/rmq-2/lxc.conf: 
Try `lxc info --show-log rmq-2` for more info
```
also:
```
lxc copy demo/snap0 demo-new --target cl-node-1
Error: Error transferring container data: exit status 11
```

# Information to attach

`t=2019-08-09T14:45:42+0200 lvl=eror msg="Rsync send failed: /var/snap/lxd/common/lxd/snapshots/demo/snap0/: exit status 11: rsync: write failed on \"/var/snap/lxd/common/lxd/containers/demo-new/rootfs/usr/share/doc/python/faq/programming.html\": No space left on device (28)\nrsync error: error in file IO (code 11) at receiver.c(393) [receiver=3.1.1]\n" `

```
lxc info --show-log rmq-2
Name: rmq-2
Location: cl-node-2
Remote: unix://
Architecture: x86_64
Created: 2018/06/30 10:55 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:

lxc rmq-2 20190809123704.562 ERROR    cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1279 - File exists - Failed to create directory "/sys/fs/cgroup/systemd//lxc.monitor/rmq-2"
lxc rmq-2 20190809123704.563 ERROR    cgfsng - cgroups/cgfsng.c:monitor_create_path_for_hierarchy:1300 - Failed to create cgroup "/sys/fs/cgroup/systemd//lxc.monitor/rmq-2"
lxc rmq-2 20190809123704.563 ERROR    cgfsng - cgroups/cgfsng.c:cgfsng_monitor_create:1390 - Failed to create cgroup "/sys/fs/cgroup/systemd//lxc.monitor/rmq-2"
lxc rmq-2 20190809123704.563 ERROR    cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1279 - File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.monitor/rmq-2-1"
lxc rmq-2 20190809123704.563 ERROR    cgfsng - cgroups/cgfsng.c:monitor_create_path_for_hierarchy:1300 - Failed to create cgroup "/sys/fs/cgroup/cpuset//lxc.monitor/rmq-2-1"
lxc rmq-2 20190809123704.563 ERROR    cgfsng - cgroups/cgfsng.c:cgfsng_monitor_create:1390 - Failed to create cgroup "/sys/fs/cgroup/cpuset//lxc.monitor/rmq-2-1"
lxc rmq-2 20190809123704.563 ERROR    cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1279 - File exists - Failed to create directory "/sys/fs/cgroup/systemd//lxc.monitor/rmq-2-2"
lxc rmq-2 20190809123704.563 ERROR    cgfsng - cgroups/cgfsng.c:monitor_create_path_for_hierarchy:1300 - Failed to create cgroup "/sys/fs/cgroup/systemd//lxc.monitor/rmq-2-2"
lxc rmq-2 20190809123704.563 ERROR    cgfsng - cgroups/cgfsng.c:cgfsng_monitor_create:1390 - Failed to create cgroup "/sys/fs/cgroup/systemd//lxc.monitor/rmq-2-2"
lxc rmq-2 20190809123704.563 ERROR    cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1279 - File exists - Failed to create directory "/sys/fs/cgroup/systemd//lxc.monitor/rmq-2-3"
lxc rmq-2 20190809123704.563 ERROR    cgfsng - cgroups/cgfsng.c:monitor_create_path_for_hierarchy:1300 - Failed to create cgroup "/sys/fs/cgroup/systemd//lxc.monitor/rmq-2-3"
lxc rmq-2 20190809123704.563 ERROR    cgfsng - cgroups/cgfsng.c:cgfsng_monitor_create:1390 - Failed to create cgroup "/sys/fs/cgroup/systemd//lxc.monitor/rmq-2-3"
lxc rmq-2 20190809123704.563 ERROR    cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1279 - File exists - Failed to create directory "/sys/fs/cgroup/systemd//lxc.monitor/rmq-2-4"
lxc rmq-2 20190809123704.563 ERROR    cgfsng - cgroups/cgfsng.c:monitor_create_path_for_hierarchy:1300 - Failed to create cgroup "/sys/fs/cgroup/systemd//lxc.monitor/rmq-2-4"
lxc rmq-2 20190809123704.563 ERROR    cgfsng - cgroups/cgfsng.c:cgfsng_monitor_create:1390 - Failed to create cgroup "/sys/fs/cgroup/systemd//lxc.monitor/rmq-2-4"
lxc rmq-2 20190809123704.563 ERROR    cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1279 - File exists - Failed to create directory "/sys/fs/cgroup/systemd//lxc.monitor/rmq-2-5"
lxc rmq-2 20190809123704.563 ERROR    cgfsng - cgroups/cgfsng.c:monitor_create_path_for_hierarchy:1300 - Failed to create cgroup "/sys/fs/cgroup/systemd//lxc.monitor/rmq-2-5"
lxc rmq-2 20190809123704.563 ERROR    cgfsng - cgroups/cgfsng.c:cgfsng_monitor_create:1390 - Failed to create cgroup "/sys/fs/cgroup/systemd//lxc.monitor/rmq-2-5"
lxc rmq-2 20190809123704.563 ERROR    cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1279 - File exists - Failed to create directory "/sys/fs/cgroup/systemd//lxc.monitor/rmq-2-6"
lxc rmq-2 20190809123704.563 ERROR    cgfsng - cgroups/cgfsng.c:monitor_create_path_for_hierarchy:1300 - Failed to create cgroup "/sys/fs/cgroup/systemd//lxc.monitor/rmq-2-6"
lxc rmq-2 20190809123704.563 ERROR    cgfsng - cgroups/cgfsng.c:cgfsng_monitor_create:1390 - Failed to create cgroup "/sys/fs/cgroup/systemd//lxc.monitor/rmq-2-6"
lxc rmq-2 20190809123704.563 ERROR    cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1279 - File exists - Failed to create directory "/sys/fs/cgroup/systemd//lxc.monitor/rmq-2-7"
lxc rmq-2 20190809123704.563 ERROR    cgfsng - cgroups/cgfsng.c:monitor_create_path_for_hierarchy:1300 - Failed to create cgroup "/sys/fs/cgroup/systemd//lxc.monitor/rmq-2-7"
lxc rmq-2 20190809123704.563 ERROR    cgfsng - cgroups/cgfsng.c:cgfsng_monitor_create:1390 - Failed to create cgroup "/sys/fs/cgroup/systemd//lxc.monitor/rmq-2-7"
lxc rmq-2 20190809123704.563 ERROR    cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1279 - File exists - Failed to create directory "/sys/fs/cgroup/systemd//lxc.monitor/rmq-2-8"
lxc rmq-2 20190809123704.563 ERROR    cgfsng - cgroups/cgfsng.c:monitor_create_path_for_hierarchy:1300 - Failed to create cgroup "/sys/fs/cgroup/systemd//lxc.monitor/rmq-2-8"
lxc rmq-2 20190809123704.563 ERROR    cgfsng - cgroups/cgfsng.c:cgfsng_monitor_create:1390 - Failed to create cgroup "/sys/fs/cgroup/systemd//lxc.monitor/rmq-2-8"
lxc rmq-2 20190809123704.564 ERROR    cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1279 - File exists - Failed to create directory "/sys/fs/cgroup/systemd//lxc.monitor/rmq-2-9"
lxc rmq-2 20190809123704.564 ERROR    cgfsng - cgroups/cgfsng.c:monitor_create_path_for_hierarchy:1300 - Failed to create cgroup "/sys/fs/cgroup/systemd//lxc.monitor/rmq-2-9"
lxc rmq-2 20190809123704.564 ERROR    cgfsng - cgroups/cgfsng.c:cgfsng_monitor_create:1390 - Failed to create cgroup "/sys/fs/cgroup/systemd//lxc.monitor/rmq-2-9"
lxc rmq-2 20190809123704.567 ERROR    lxccontainer - lxccontainer.c:wait_on_daemonized_start:864 - No such file or directory - Failed to receive the container state
```

**Comment by syswipe** [comment] 2019-08-09 13:16
also, I saw the next messages in dmesg:

> [176559.988622] device-mapper: thin: 252:2: reached low water mark for data device: sending event.
> [177000.204699] device-mapper: thin: 252:2: reached low water mark for data device: sending event.
> [177228.067009] EXT4-fs (dm-12): mounted filesystem with ordered data mode. Opts: discard
> [177300.610176] device-mapper: thin: 252:2: reached low water mark for data device: sending event.
> [177601.016082] device-mapper: thin: 252:2: reached low water mark for data device: sending event.
>

**Comment by stgraber** [comment] 2019-08-09 13:39
For the moving part `No space left on device` is a pretty clear indicator of the issue there.
The dmesg output similarly suggests a space related issue?

For your startup error, you can do:
 - lxc config set NAME raw.lxc lxc.log.level=trace
 - lxc start NAME
 - lxc info --show-log NAME

That should get you even more details on the startup failure.

**Comment by syswipe** [comment] 2019-08-09 13:56
> For the moving part `No space left on device` is a pretty clear indicator of the issue there.

yep, i understand, but i can't find the reason. As i can see - there are a lot of free space in Pool.

>   LV                                                                      VG    Attr       LSize   Pool        Origin                                                                  Data%  Meta%  Move Log Cpy%Sync Convert
>   LXDThinPool                                                             local twi-aotz-- 891.25g                                                                                     16.09  3.31                            
> 

lxc info --show-log output - in attachment

**Comment by stgraber** [comment] 2019-08-09 14:53
For the move, my best guess is that your container doesn't have a `root` device with a `size` property directly attached to it (might be coming through a profile), causing the target server to allocate the standard volume size (10GB) which is too small for your container.

Sounds plausible?

**Comment by stgraber** [comment] 2019-08-09 15:04
As for the startup failure, currently my best guess is that there is an issue finding/executing `/sbin/init` in that container.

Can you manually mount the LV of that container somewhere and inspect `rootfs/sbin/init` in there?

**Comment by syswipe** [comment] 2019-08-09 15:33
> For the move, my best guess is that your container doesn't have a `root` device with a `size` property directly attached to it (might be coming through a profile), causing the target server to allocate the standard volume size (10GB) which is too small for your container.
> 
> Sounds plausible?

Unfortunately no. I've mounted container rootfs manually:

`/dev/mapper/local-containers_rmq----2  9.8G  929M  8.3G  10% /mnt/rmq-2
`
there is enough free space

> Can you manually mount the LV of that container somewhere and inspect `rootfs/sbin/init` in there?
```
 ls -l rootfs/sbin/init 
lrwxrwxrwx 1 1000000 1000000 20 Apr  3 13:27 rootfs/sbin/init -> /lib/systemd/systemd
```
also i note, that LVM didn't remove volumes which were deleted via lxc storage delete. When i try to remove ones manually, i get an error:
```
lvremove /dev/local/custom_demo--storage
Do you really want to remove and DISCARD logical volume custom_demo--storage? [y/n]: y
  Thin pool local-LXDThinPool-tpool (252:2) transaction_id is 43, while expected 39.
  Failed to suspend and send message local/LXDThinPool.
  Failed to update pool local/LXDThinPool.
```
sounds like a problem with LVM backend?

**Comment by stgraber** [comment] 2019-08-09 16:33
Can you try:
 - chroot rootfs
 - /sbin/init --help

Just to make sure it's not because of a bad library or corruption of the binary itself as those can cause the kernel to return `no such file or directory` in a pretty confusing way.

**Comment by stgraber** [comment] 2019-08-09 16:35
The `lvremove` failing isn't a good sign, it may be the indication of more underlying LVM problems on that system.

Can you check that `grep custom_demo--storage /proc/*/mountinfo` doesn't return anything, just to make sure that it's not actually in use somewhere. Also maybe run `pvscan --cache` to make sure that what you see in `lvs` matches what's on disk.

As the LXD snap has to use its own copy of the LVM tools, it effectively ends up with its own separate cache, which may or may not explain why the tools on the host are having some difficulties in this case.

**Comment by syswipe** [comment] 2019-08-12 08:49
> grep custom_demo--storage /proc/*/mountinfo
output is empty

> run `pvscan --cache` to make sure that what you see in `lvs` matches what's on disk.
looks like lvs shows all LV correctly

**Comment by syswipe** [comment] 2019-08-12 09:52
> As the LXD snap has to use its own copy of the LVM tools, it effectively ends up with its own separate cache, which may or may not explain why the tools on the host are having some difficulties in this case.

If i understand you properly, LXD's lvm tools may cause some inconsistency? And i'm not able to repair my VG/LV with host tools?

**Comment by stgraber** [comment] 2019-08-12 14:29
The tools themselves are usually fine, the problem is the various caches that LVM maintain as those will go out of sync. That's what `pvscan --cache` normally resolves by re-scanning the devices, extracting the metadata from there and then updating the cache.

You could also try:
 - nsenter -t $(pgrep daemon.start) -m
 - export PATH=/snap/lxd/current/bin/:${PATH}
 - export LD_LIBRARY_PATH=/snap/lxd/current/lib/:/snap/lxd/current/lib/x86_64-linux-gnu/
 - lvs

Or run whatever you want there instead of `lvs`. This will effectively put you in the same environment as the snap with access to the snap's LVM cache and tools.

**Comment by syswipe** [comment] 2019-08-13 07:29
hi, @stgraber 
Today the situation is the next: lxd on node with bad LVM is completely unavailable.
all lxc related commands return the next:
`Error: Get http://unix.socket/1.0: EOF`

```
t=2019-08-13T09:26:00+0200 lvl=info msg="LXD 3.16 is starting in normal mode" path=/var/snap/lxd/common/lxd
t=2019-08-13T09:26:00+0200 lvl=info msg="Kernel uid/gid map:" 
t=2019-08-13T09:26:00+0200 lvl=info msg=" - u 0 0 4294967295" 
t=2019-08-13T09:26:00+0200 lvl=info msg=" - g 0 0 4294967295" 
t=2019-08-13T09:26:00+0200 lvl=info msg="Configured LXD uid/gid map:" 
t=2019-08-13T09:26:00+0200 lvl=info msg=" - u 0 1000000 1000000000" 
t=2019-08-13T09:26:00+0200 lvl=info msg=" - g 0 1000000 1000000000" 
t=2019-08-13T09:26:00+0200 lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." 
t=2019-08-13T09:26:00+0200 lvl=info msg="Kernel features:" 
t=2019-08-13T09:26:00+0200 lvl=info msg=" - netnsid-based network retrieval: no" 
t=2019-08-13T09:26:00+0200 lvl=info msg=" - uevent injection: no" 
t=2019-08-13T09:26:00+0200 lvl=info msg=" - seccomp listener: no" 
t=2019-08-13T09:26:00+0200 lvl=info msg=" - unprivileged file capabilities: yes" 
t=2019-08-13T09:26:00+0200 lvl=info msg=" - shiftfs support: no" 
t=2019-08-13T09:26:00+0200 lvl=info msg="Initializing local database" 
t=2019-08-13T09:26:00+0200 lvl=info msg="Starting /dev/lxd handler:" 
t=2019-08-13T09:26:00+0200 lvl=info msg=" - binding devlxd socket" socket=/var/snap/lxd/common/lxd/devlxd/sock
t=2019-08-13T09:26:00+0200 lvl=info msg="REST API daemon:" 
t=2019-08-13T09:26:00+0200 lvl=info msg=" - binding Unix socket" inherited=true socket=/var/snap/lxd/common/lxd/unix.socket
t=2019-08-13T09:26:00+0200 lvl=info msg=" - binding TCP socket" socket=10.0.0.20:8443
t=2019-08-13T09:26:00+0200 lvl=info msg="Initializing global database" 
t=2019-08-13T09:26:00+0200 lvl=info msg="Initializing storage pools" 
t=2019-08-13T09:26:13+0200 lvl=eror msg="Failed to start the daemon: could not activate volume group \"local\":   15 logical volume(s) in volume group \"local\" now active\n" 
t=2019-08-13T09:26:13+0200 lvl=info msg="Starting shutdown sequence" 
t=2019-08-13T09:26:13+0200 lvl=info msg="Stopping REST API handler:" 
t=2019-08-13T09:26:13+0200 lvl=info msg=" - closing socket" socket=10.0.0.20:8443
t=2019-08-13T09:26:13+0200 lvl=info msg=" - closing socket" socket=/var/snap/lxd/common/lxd/unix.socket
t=2019-08-13T09:26:13+0200 lvl=info msg="Stopping /dev/lxd handler:" 
t=2019-08-13T09:26:13+0200 lvl=info msg=" - closing socket" socket=/var/snap/lxd/common/lxd/devlxd/sock
t=2019-08-13T09:26:13+0200 lvl=info msg="Closing the database" 
```
now i'm trying to move data from stopped containers. But how can i save running containers?

**Comment by syswipe** [comment] 2019-08-13 07:54
Also, when i try to import tarballs on another cluster node, i get an error:
```
lxc image import art.tar.gz --alias art-backup
Error: Image sync between nodes: Image sync between nodes: Post https://10.0.0.20:8443/1.0/images?project=default: net/http: HTTP/1.x transport connection broken: write tcp 10.0.0.10:40962->10.0.0.20:8443: write: connection reset by peer
```
i'm stuck...

**Comment by syswipe** [comment] 2019-08-13 09:46
> * nsenter -t $(pgrep daemon.start) -m
> * export PATH=/snap/lxd/current/bin/:${PATH}
> * export LD_LIBRARY_PATH=/snap/lxd/current/lib/:/snap/lxd/current/lib/x86_64-linux-gnu/
> * lvs

i can't use nsenter because of snap.lxd.daemon restarted continuously, so pids always different.

**Comment by syswipe** [comment] 2019-08-13 10:12
finally my cluster show that all nodes are offline, because of second node shows:

> t=2019-08-13T12:11:03+0200 lvl=info msg="LXD 3.16 is starting in normal mode" path=/var/snap/lxd/common/lxd
> t=2019-08-13T12:11:03+0200 lvl=info msg="Kernel uid/gid map:" 
> t=2019-08-13T12:11:03+0200 lvl=info msg=" - u 0 0 4294967295" 
> t=2019-08-13T12:11:03+0200 lvl=info msg=" - g 0 0 4294967295" 
> t=2019-08-13T12:11:03+0200 lvl=info msg="Configured LXD uid/gid map:" 
> t=2019-08-13T12:11:03+0200 lvl=info msg=" - u 0 1000000 1000000000" 
> t=2019-08-13T12:11:03+0200 lvl=info msg=" - g 0 1000000 1000000000" 
> t=2019-08-13T12:11:03+0200 lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." 
> t=2019-08-13T12:11:03+0200 lvl=info msg="Kernel features:" 
> t=2019-08-13T12:11:03+0200 lvl=info msg=" - netnsid-based network retrieval: no" 
> t=2019-08-13T12:11:03+0200 lvl=info msg=" - uevent injection: no" 
> t=2019-08-13T12:11:03+0200 lvl=info msg=" - seccomp listener: no" 
> t=2019-08-13T12:11:03+0200 lvl=info msg=" - unprivileged file capabilities: yes" 
> t=2019-08-13T12:11:03+0200 lvl=info msg=" - shiftfs support: no" 
> t=2019-08-13T12:11:03+0200 lvl=info msg="Initializing local database" 
> t=2019-08-13T12:11:04+0200 lvl=info msg="Starting /dev/lxd handler:" 
> t=2019-08-13T12:11:04+0200 lvl=info msg=" - binding devlxd socket" socket=/var/snap/lxd/common/lxd/devlxd/sock
> t=2019-08-13T12:11:04+0200 lvl=info msg="REST API daemon:" 
> t=2019-08-13T12:11:04+0200 lvl=info msg=" - binding Unix socket" inherited=true socket=/var/snap/lxd/common/lxd/unix.socket
> t=2019-08-13T12:11:04+0200 lvl=info msg=" - binding TCP socket" socket=10.0.0.20:8443
> t=2019-08-13T12:11:04+0200 lvl=info msg="Initializing global database" 
> t=2019-08-13T12:11:05+0200 lvl=eror msg="Failed to start the daemon: failed to open cluster database: failed to ensure schema: failed to update node version info: database is locked" 

any suggestions?

**Comment by stgraber** [comment] 2019-08-13 14:13
@syswipe any chance I can get onto that system to figure out what's going on?
The error seems pretty weird, it effectively says that everything worked, yet exitted non-zero as if something wrong happened...

**Comment by syswipe** [comment] 2019-08-13 14:27
@stgraber, I've replied to you in private message.

**Comment by stgraber** [comment] 2019-09-03 03:02
@syswipe I believe our conclusion was that a reboot was needed and you were going to do that a bit later. Did that solve it?

(Looked like the kernel being pretty confused about the state of device mapper)

**Comment by syswipe** [comment] 2019-09-04 13:12
Maybe. Or maybe not. In fact, some times later after LVM corruption LXD lost access to the whole cluster because of trouble with cluster database (dqlite). So I stopped my attempt to recover cluster and LVM and restored whole environment from backups...

**Comment by stgraber** [comment] 2019-09-04 16:15
Oh, that's unfortunate. Closing as there seems like there's little for us to do in this issue at this point.
The system I looked at definitely had some weird LVM issues going on which, I don't know about the clustering issues though.

**Closed by stgraber** 2019-09-04 16:15 UTC
Labels: Incomplete
