### ISSUE TITLE
LXC start failed.

### ISSUE THREAD

**Issue by oytunistrator** [lxc/lxd#4720] opened 2018-07-03 07:45 UTC
# Required information

 * Distribution: CentOS 
 * Distribution version:  7.x
 * The output of "lxc info" or if that fails:
```
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 192.168.1.102:8443
  - '[fdc7:4472:c49a::f64]:8443'
  - '[fdc7:4472:c49a:0:8bb2:8122:b740:5c68]:8443'
  - 172.17.0.1:8443
  - 10.87.245.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFmTCCA4GgAwIBAgIQTTEyg9MVk0IL67uwNsRNeDANBgkqhkiG9w0BAQsFADBD
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMSMwIQYDVQQDDBpyb290QGxv
    Y2FsaG9zdC5sb2NhbGRvbWFpbjAeFw0xODA3MDMwNzI4NTdaFw0yODA2MzAwNzI4
    NTdaMEMxHDAaBgNVBAoTE2xpbnV4Y29udGFpbmVycy5vcmcxIzAhBgNVBAMMGnJv
    b3RAbG9jYWxob3N0LmxvY2FsZG9tYWluMIICIjANBgkqhkiG9w0BAQEFAAOCAg8A
    MIICCgKCAgEAwmj2/+KkGtmUSHK2MeUhCzeMacYgc1zPF7RbMo4FBC8nJVIzLg+D
    dIpButzdblbd8kGTE0wMnQumvyNP1uN4ktffpTJ0Nm1I/aGAwMZUuNdqc4H36o7F
    c9ENPi8svTZyZcIvzhfY+Bu7VZLxaj1TD0fciCxPN/O18sk8eVkHYoruvKUCQAH9
    xjzEvlJ8cuBw3RykaoqWkq4pIaR2NDtOq/xJAuyskMMKGk6MRfaEJOZF2UY2kCoM
    vNcUNIbYP+YHWZY6/EEA1EAXu2h75fy0ijcNAeetLT8fTa+JjMg2Pj4AXB+6uhAc
    KajJ5r5Y/dfK+mykzzYSopSmc8vI+oX6NaCerMTigwSAx8tAFaMRm0eqP3nAHYCG
    7zWRq4XjrzOOQUfp+fTokRiLs1U2JluScF567wvbChRdZjT0v66rX0XRRzGpBhIu
    p4PRnhNcmaQsfi78AIaQkG5Kx5iEVb3Uq0LwY8R0oZEWAPUwfzGpUqdcs7AfyAFo
    ZcwBGlaYC3R0/6wcpejGWD7Bn7vJMh3xGFZRH3gqMqvLw/cLwhXMVudmWOHhgkoK
    Yi50pINEt7hl04pa1tNyQ/0MrEyctXYZRTn5aSHH2kTqhfiUykFx/mhGPZgpQmuJ
    4UR7serft7abG1hJkQLJiTN6uXxLAOf5hRNiASj0XT9NkXyL8rNRZAMCAwEAAaOB
    iDCBhTAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYDVR0T
    AQH/BAIwADBQBgNVHREESTBHghVsb2NhbGhvc3QubG9jYWxkb21haW6HBMCoAWaH
    EP3HRHLEmgAAAAAAAAAAD2SHEP3HRHLEmgAAi7KBIrdAXGiHBKwRAAEwDQYJKoZI
    hvcNAQELBQADggIBAFzQ8wE88CnXjkbmQmhl6NbYhlmvyKKibBRrAZMgVW/1UEVk
    Erj7GiVVyDemXLwiy5DxT6LSGVtj0FI2DSF3W5/hnfXqxPzYf1qtPl7BcrhEBqah
    0yJGxNfecuX1+QziwtWu+Ie4ntC2e87ZBqjV1sdpSaRu+vkD1QsM91vjblxkOxNs
    ApKPg7GmNAKG8Apn74wSBuKwqvZl2PPxpsF/96dSHvg2LbztSoj53o1uF0zADymc
    58rdKyxEOY40jn0MamnRQtoZE7ZuruJuzEa/ESFzwHDlpmtqMPpvSu6435Ea1xFi
    Wm3FOmc+shYuhZ1h6Sw07TdWJY8xWCwJqyhnRvN16gQJtBb1FYT6CyN4mG1giEpT
    7g3MqjasMxg5AtTJjg/xpMMNqElo0C0rzKzUX6w4nbS8sLGYVWccNqnTHUQtxhPm
    wLxQuA+VCMKuC1e89O7rf5b17Cn4cwWqRrDal0xqVJStSxxagQf9cVWxf+DBolmI
    b824efclYwRyj0dnYoPX+4u3qT9RR/7pTc4UESrlM87A+AosSEDCtorGvVor0RZp
    CcvNzGeIx4Nq/aTcMCERcm4EbejjGYFIzcAKVRBTjcE21NzVLaf1sFI3U895wvaM
    OezoyDMcFFIVrJcfeYypJmAvxE3UwKqIwSBX2UDq6LxpVUqbuJIuhLX+Q3Ks
    -----END CERTIFICATE-----
  certificate_fingerprint: 576b32284f0abc86757d0259c70532c15e45ebade8d239d69b6c2638a5b221f6
  driver: lxc
  driver_version: 3.0.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 3.10.0-862.3.3.el7.x86_64
  server: lxd
  server_pid: 3673
  server_version: "3.2"
  storage: btrfs
  storage_version: "4.4"
  server_clustered: false
  server_name: localhost.localdomain
```

# Issue description

Installed from snap after lxc init success but lxc start failed.

# Steps to reproduce

 1. lxc start system1
 2. lxc info --show-log system1

# Information to attach
```
Name: system1
Remote: unix://
Architecture: x86_64
Created: 2018/07/03 07:35 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:

lxc system1 20180703074113.872 ERROR    lxc_cgfsng - cgroups/cgfsng.c:create_path_for_hierarchy:1246 - The cgroup "/sys/fs/cgroup/systemd//lxc/system1" already existed
lxc system1 20180703074113.873 ERROR    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_create:1334 - Failed to create cgroup "/sys/fs/cgroup/systemd//lxc/system1"
lxc system1 20180703074113.873 ERROR    lxc_cgfsng - cgroups/cgfsng.c:create_path_for_hierarchy:1246 - The cgroup "/sys/fs/cgroup/systemd//lxc/system1-1" already existed
lxc system1 20180703074113.873 ERROR    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_create:1334 - Failed to create cgroup "/sys/fs/cgroup/systemd//lxc/system1-1"
lxc system1 20180703074113.874 ERROR    lxc_cgfsng - cgroups/cgfsng.c:create_path_for_hierarchy:1246 - The cgroup "/sys/fs/cgroup/systemd//lxc/system1-2" already existed
lxc system1 20180703074113.874 ERROR    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_create:1334 - Failed to create cgroup "/sys/fs/cgroup/systemd//lxc/system1-2"
lxc system1 20180703074113.874 ERROR    lxc_cgfsng - cgroups/cgfsng.c:create_path_for_hierarchy:1246 - The cgroup "/sys/fs/cgroup/systemd//lxc/system1-3" already existed
lxc system1 20180703074113.874 ERROR    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_create:1334 - Failed to create cgroup "/sys/fs/cgroup/systemd//lxc/system1-3"
lxc system1 20180703074113.875 ERROR    lxc_cgfsng - cgroups/cgfsng.c:create_path_for_hierarchy:1246 - The cgroup "/sys/fs/cgroup/systemd//lxc/system1-4" already existed
lxc system1 20180703074113.875 ERROR    lxc_cgfsng - cgroups/cgfsng.c:cgfsng_create:1334 - Failed to create cgroup "/sys/fs/cgroup/systemd//lxc/system1-4"
lxc system1 20180703074113.891 ERROR    lxc_start - start.c:lxc_spawn:1634 - Invalid argument - Failed to clone a new set of namespaces
lxc system1 20180703074113.125 WARN     lxc_network - network.c:lxc_delete_network_priv:2607 - Failed to remove interface "vethYO4KXA" from "lxdbr0": Invalid argument
lxc system1 20180703074113.125 ERROR    lxc_start - start.c:__lxc_start:1887 - Failed to spawn container "system1"
lxc system1 20180703074113.125 ERROR    lxc_container - lxccontainer.c:wait_on_daemonized_start:834 - Received container state "ABORTING" instead of "RUNNING"
lxc system1 20180703074113.125 ERROR    lxc_conf - conf.c:userns_exec_1:4197 - Failed to clone process in new user namespace
lxc system1 20180703074113.125 WARN     lxc_cgfsng - cgroups/cgfsng.c:cgfsng_destroy:1171 - Failed to destroy cgroups
lxc 20180703074113.126 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:130 - Connection reset by peer - Failed to receive response for command "get_state"

```

**Comment by brauner** [comment] 2018-07-03 09:11
```
lxc system1 20180703074113.891 ERROR    lxc_start - start.c:lxc_spawn:1634 - Invalid argument - Failed to clone a new set of namespaces
```
Usually indicates that a namespace isn't enabled, especially on CentOS. Please refer to

https://discuss.linuxcontainers.org/t/centos-7-kernel-514-693-cannot-start-any-nodes-after-update/641/16

and see whether this fixes your issue.

**Comment by oytunistrator** [comment] 2018-07-03 11:14
I tested giving this error;
```
[root@localhost ~]# lxc info --show-log local:system4
Name: system4
Remote: unix://
Architecture: x86_64
Created: 2018/07/03 11:10 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:

lxc system4 20180703111037.860 ERROR    lxc_start - start.c:lxc_spawn:1634 - Invalid argument - Failed to clone a new set of namespaces
lxc system4 20180703111037.881 WARN     lxc_network - network.c:lxc_delete_network_priv:2607 - Failed to remove interface "vethHSTBXU" from "lxdbr0": Invalid argument
lxc system4 20180703111037.881 ERROR    lxc_start - start.c:__lxc_start:1887 - Failed to spawn container "system4"
lxc system4 20180703111037.881 ERROR    lxc_container - lxccontainer.c:wait_on_daemonized_start:834 - Received container state "ABORTING" instead of "RUNNING"
lxc system4 20180703111037.881 ERROR    lxc_conf - conf.c:userns_exec_1:4197 - Failed to clone process in new user namespace
lxc system4 20180703111037.881 WARN     lxc_cgfsng - cgroups/cgfsng.c:cgfsng_destroy:1171 - Failed to destroy cgroups
lxc 20180703111037.883 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:130 - Connection reset by peer - Failed to receive response for command "get_state"


```

**Comment by brauner** [comment] 2018-07-03 11:21
user namespaces seem to be still disabled. Can you do:

```
unshare -U
```
see if that works and if that works try

```
unshare -U -m
```

**Comment by stgraber** [comment] 2018-07-03 13:16
Closing as the problem is system configuration or a bad kernel and not a big in lxd itself.

Note that this doesn't mean we won't keep commenting in this issue just that this doesn't seem to be a LXD bug.

**Closed by stgraber** 2018-07-03 13:16 UTC
