### ISSUE TITLE
LXD 3.6 fails after: Updating global DB schema from 11 to 12

### ISSUE THREAD

**Issue by melato** [lxc/lxd#5165] opened 2018-10-15 11:29 UTC
Distribution:  Ubuntu 18.04.1 LTS
LXC version:  3.6
LXD version: 3.6
Storage backend:  ZFS

lxc init was unresponsive with EOF from http://unix.socket/1.0, so I eventually rebooted.
It still doesn't work.
I then did:
systemctl stop snap.lxd.daemon.service snap.lxd.daemon.unix.socket
pkill -9 lxd
lxd --debug --group lxd

This is the output of the last command:
```
INFO[10-15|14:24:34] LXD 3.6 is starting in normal mode       path=/var/snap/lxd/common/lxd
INFO[10-15|14:24:34] Kernel uid/gid map: 
INFO[10-15|14:24:34]  - u 0 0 4294967295 
INFO[10-15|14:24:34]  - g 0 0 4294967295 
INFO[10-15|14:24:34] Configured LXD uid/gid map: 
INFO[10-15|14:24:34]  - u 0 1000000 1000000000 
INFO[10-15|14:24:34]  - g 0 1000000 1000000000 
WARN[10-15|14:24:34] CGroup memory swap accounting is disabled, swap limits will be ignored. 
DBUG[10-15|14:24:34] Failed to set NETLINK_DUMP_STRICT_CHK socket option 
DBUG[10-15|14:24:34] Running kernel does not support netnsid-based network retrieval 
DBUG[10-15|14:24:34] Running kernel does not support uevent injection 
DBUG[10-15|14:24:34] System supports unprivileged file capabilities 
INFO[10-15|14:24:34] Initializing local database 
INFO[10-15|14:24:34] Initializing database gateway 
INFO[10-15|14:24:34] Start database node                      address= id=1
INFO[10-15|14:24:35] Raft: Restored from snapshot 1-246191-1539554515345 
INFO[10-15|14:24:37] Raft: Initial configuration (index=1): [{Suffrage:Voter ID:1 Address:0}] 
INFO[10-15|14:24:37] Raft: Node at 0 [Leader] entering Leader state 
INFO[10-15|14:24:37] Dqlite: starting event loop 
DBUG[10-15|14:24:37] Dqlite: accepting connections 
INFO[10-15|14:24:37] LXD isn't socket activated 
INFO[10-15|14:24:37] Starting /dev/lxd handler: 
INFO[10-15|14:24:37]  - binding devlxd socket                 socket=/var/snap/lxd/common/lxd/devlxd/sock
INFO[10-15|14:24:37] REST API daemon: 
INFO[10-15|14:24:37]  - binding Unix socket                   socket=/var/snap/lxd/common/lxd/unix.socket
INFO[10-15|14:24:37]  - binding TCP socket                    socket=[::]:8443
INFO[10-15|14:24:37] Initializing global database 
INFO[10-15|14:24:37] Dqlite: handling new connection (fd=20) 
INFO[10-15|14:24:37] Dqlite: connected address=0 attempt=0 
INFO[10-15|14:24:38] Dqlite: closing client 
INFO[10-15|14:24:38] Dqlite: handling new connection (fd=22) 
INFO[10-15|14:24:42] Dqlite: connected address=0 attempt=0 
INFO[10-15|14:24:42] Updating the LXD global schema. Backup made as "global.bak" 
DBUG[10-15|14:24:43] Updating global DB schema from 10 to 11 
DBUG[10-15|14:24:43] Updating global DB schema from 11 to 12 
INFO[10-15|14:24:49] Dqlite: closing client 
WARN[10-15|14:24:49] Failed to rollback transaction after error (failed to apply update 11: Failed to add project_id column: driver: bad connection): driver: bad connection 
DBUG[10-15|14:24:49] Database error: &errors.errorString{s:"failed to apply update 11: Failed to add project_id column: driver: bad connection"} 
DBUG[10-15|14:24:49] Retry failed db interaction (failed to apply update 11: Failed to add project_id column: driver: bad connection) 
INFO[10-15|14:24:49] Dqlite: handling new connection (fd=21) 
INFO[10-15|14:24:54] Dqlite: closing client 
DBUG[10-15|14:24:54] Dqlite: server connection failed err=failed to send Leader request: failed to receive response: failed to receive header: failed to receive header: read unix @->@0003e: i/o timeout address=0 attempt=0 
DBUG[10-15|14:24:54] Dqlite: connection failed err=no available dqlite leader server found attempt=0 
INFO[10-15|14:24:59] Dqlite: closing client 
DBUG[10-15|14:24:59] Dqlite: server connection failed err=failed to send Leader request: failed to receive response: failed to receive header: failed to receive header: read unix @->@0003e: i/o timeout address=0 attempt=1 
DBUG[10-15|14:24:59] Dqlite: connection failed err=no available dqlite leader server found attempt=1 
DBUG[10-15|14:24:59] Database error: failed to begin transaction: failed to create dqlite connection: no available dqlite leader server found 
EROR[10-15|14:24:59] Failed to start the daemon: failed to open cluster database: failed to ensure schema: failed to begin transaction: failed to create dqlite connection: no available dqlite leader server found 
INFO[10-15|14:24:59] Starting shutdown sequence 
INFO[10-15|14:24:59] Stopping REST API handler: 
INFO[10-15|14:24:59]  - closing socket                        socket=[::]:8443
INFO[10-15|14:24:59]  - closing socket                        socket=/var/snap/lxd/common/lxd/unix.socket
INFO[10-15|14:24:59] Stopping /dev/lxd handler: 
INFO[10-15|14:24:59]  - closing socket                        socket=/var/snap/lxd/common/lxd/devlxd/sock
INFO[10-15|14:24:59] Stop database gateway 
INFO[10-15|14:24:59] Stop raft instance 
EROR[10-15|14:24:59] Dqlite: aborting (fd=22 state=body msg=response write error: broken pipe (EPIPE)) 
INFO[10-15|14:24:59] Dqlite: handling new connection (fd=14) 
INFO[10-15|14:24:59] Dqlite: stopping event loop 
INFO[10-15|14:24:59] Dqlite: event loop stopped 
DBUG[10-15|14:24:59] Not unmounting temporary filesystems (containers are still running) 
INFO[10-15|14:24:59] Saving simplestreams cache 
INFO[10-15|14:24:59] Saved simplestreams cache 
Error: failed to open cluster database: failed to ensure schema: failed to begin transaction: failed to create dqlite connection: no available dqlite leader server found
```

content of /var/snap/lxd/common/lxd/logs/lxd.log:
lvl=info msg="LXD 3.6 is starting in normal mode" path=/var/snap/lxd/common/lxd t=2018-10-15T14:14:18+0300
lvl=info msg="Kernel uid/gid map:" t=2018-10-15T14:14:18+0300
lvl=info msg=" - u 0 0 4294967295" t=2018-10-15T14:14:18+0300
lvl=info msg=" - g 0 0 4294967295" t=2018-10-15T14:14:18+0300
lvl=info msg="Configured LXD uid/gid map:" t=2018-10-15T14:14:18+0300
lvl=info msg=" - u 0 1000000 1000000000" t=2018-10-15T14:14:18+0300
lvl=info msg=" - g 0 1000000 1000000000" t=2018-10-15T14:14:18+0300
lvl=warn msg="CGroup memory swap accounting is disabled, swap limits will be ignored." t=2018-10-15T14:14:18+0300
lvl=info msg="Initializing local database" t=2018-10-15T14:14:18+0300
lvl=info msg="Initializing database gateway" t=2018-10-15T14:14:18+0300
address= id=1 lvl=info msg="Start database node" t=2018-10-15T14:14:18+0300
lvl=info msg="Raft: Restored from snapshot 1-246191-1539554515345" t=2018-10-15T14:14:18+0300
lvl=info msg="Raft: Initial configuration (index=1): [{Suffrage:Voter ID:1 Address:0}]" t=2018-10-15T14:14:20+0300
lvl=info msg="Raft: Node at 0 [Leader] entering Leader state" t=2018-10-15T14:14:20+0300
lvl=info msg="Dqlite: starting event loop" t=2018-10-15T14:14:20+0300
lvl=info msg="LXD is socket activated" t=2018-10-15T14:14:20+0300
lvl=info msg="Starting /dev/lxd handler:" t=2018-10-15T14:14:20+0300
lvl=info msg=" - binding devlxd socket" socket=/var/snap/lxd/common/lxd/devlxd/sock t=2018-10-15T14:14:20+0300
lvl=info msg="REST API daemon:" t=2018-10-15T14:14:20+0300
lvl=info msg=" - binding Unix socket" socket=/var/snap/lxd/common/lxd/unix.socket t=2018-10-15T14:14:20+0300
lvl=info msg=" - binding TCP socket" socket=[::]:8443 t=2018-10-15T14:14:20+0300
lvl=info msg="Initializing global database" t=2018-10-15T14:14:20+0300
lvl=info msg="Dqlite: handling new connection (fd=24)" t=2018-10-15T14:14:20+0300
lvl=info msg="Dqlite: connected address=0 attempt=0" t=2018-10-15T14:14:20+0300
lvl=info msg="Dqlite: closing client" t=2018-10-15T14:14:21+0300
lvl=info msg="Dqlite: handling new connection (fd=23)" t=2018-10-15T14:14:21+0300
lvl=info msg="Dqlite: connected address=0 attempt=0" t=2018-10-15T14:14:25+0300
lvl=info msg="Updating the LXD global schema. Backup made as \"global.bak\"" t=2018-10-15T14:14:25+0300
lvl=info msg="Dqlite: closing client" t=2018-10-15T14:14:32+0300
lvl=warn msg="Failed to rollback transaction after error (failed to apply update 11: Failed to add project_id column: driver: bad connection): driver: bad connection" t=2018-10-15T14:14:32+0300
lvl=info msg="Dqlite: handling new connection (fd=24)" t=2018-10-15T14:14:33+0300
lvl=info msg="Dqlite: closing client" t=2018-10-15T14:14:38+0300

**Comment by melato** [comment] 2018-10-15 11:41
The containers are unresponsive after the reboot.  I don't know how to recover.
The initial problem happened after or while I was backing up all running containers, using:
`lxc export $c $BACKUP_DIR/$c.tar.xz --container-only`
I'm mentioning this because lxd has similarly hang in the past during such backup.

**Comment by freeekanayaka** [comment] 2018-10-15 12:12
This should be a dupe of #5162.

**Comment by melato** [comment] 2018-10-15 12:16
Yes it could be a duplicate of #5162.  I hadn't noticed that #5162 also had the failing db updates.

**Closed** 2018-10-15 13:14 UTC
