### ISSUE TITLE
lxd does not start: dir-type storage-pool does not working after upgrade to 3.19(snap)

### ISSUE THREAD

**Issue by schmidtomat** [lxc/lxd#6759] opened 2020-01-23 19:43 UTC
# Required information

 * Distribution:  Ubuntu
 * Distribution version: 18.04.3
 * "lxc info" fails! no lxc command is available (Error: Get http://unix.socket/1.0: EOF)
   * Kernel version: 5.4.13
   * LXD version: 3.19 (snap)
   * Storage backend in use: dir

# Issue description
when lxd is starting it fails with the following error:

 lvl=eror msg="Failed to start the daemon: Failed initializing storage pool \"virts\": Failed to mount '/storage/virts/lxd' on '/var/snap/lxd/common/lxd/storage-pools/virts': no such file or directory"

it worked with 3.18.

# Steps to reproduce

 1. give any lxc command

# Information to attach

dmesg: 
[ 3991.826288] new mount options do not match the existing superblock, will be ignored
[ 4003.322831] new mount options do not match the existing superblock, will be ignored
[ 4014.821516] new mount options do not match the existing superblock, will be ignored
[ 4026.300152] new mount options do not match the existing superblock, will be ignored

 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
t=2020-01-23T20:39:25+0100 lvl=info msg="LXD 3.19 is starting in normal mode" path=/var/snap/lxd/common/lxd
t=2020-01-23T20:39:25+0100 lvl=info msg="Kernel uid/gid map:"
t=2020-01-23T20:39:25+0100 lvl=info msg=" - u 0 0 4294967295"
t=2020-01-23T20:39:25+0100 lvl=info msg=" - g 0 0 4294967295"
t=2020-01-23T20:39:25+0100 lvl=info msg="Configured LXD uid/gid map:"
t=2020-01-23T20:39:25+0100 lvl=info msg=" - u 0 1000000 1000000000"
t=2020-01-23T20:39:25+0100 lvl=info msg=" - g 0 1000000 1000000000"
t=2020-01-23T20:39:25+0100 lvl=info msg="Kernel features:"
t=2020-01-23T20:39:25+0100 lvl=info msg=" - netnsid-based network retrieval: yes"
t=2020-01-23T20:39:25+0100 lvl=info msg=" - uevent injection: yes"
t=2020-01-23T20:39:25+0100 lvl=info msg=" - seccomp listener: yes"
t=2020-01-23T20:39:25+0100 lvl=info msg=" - seccomp listener continue syscalls: no"
t=2020-01-23T20:39:25+0100 lvl=info msg=" - unprivileged file capabilities: yes"
t=2020-01-23T20:39:25+0100 lvl=info msg=" - cgroup layout: hybrid"
t=2020-01-23T20:39:25+0100 lvl=warn msg=" - Couldn't find the CGroup blkio.weight, I/O weight limits will be ignored"
t=2020-01-23T20:39:25+0100 lvl=warn msg=" - Couldn't find the CGroup memory swap accounting, swap limits will be ignored"
t=2020-01-23T20:39:25+0100 lvl=info msg=" - shiftfs support: disabled"
t=2020-01-23T20:39:25+0100 lvl=info msg="Initializing local database"
t=2020-01-23T20:39:25+0100 lvl=dbug msg="Initializing database gateway"
t=2020-01-23T20:39:25+0100 lvl=dbug msg="Start database node" address= id=1
t=2020-01-23T20:39:25+0100 lvl=info msg="Starting /dev/lxd handler:"
t=2020-01-23T20:39:25+0100 lvl=info msg=" - binding devlxd socket" socket=/var/snap/lxd/common/lxd/devlxd/sock
t=2020-01-23T20:39:25+0100 lvl=info msg="REST API daemon:"
t=2020-01-23T20:39:25+0100 lvl=info msg=" - binding Unix socket" inherited=true socket=/var/snap/lxd/common/lxd/unix.socket
t=2020-01-23T20:39:25+0100 lvl=info msg="Initializing global database"
t=2020-01-23T20:39:25+0100 lvl=dbug msg="Dqlite: connected address=1 id=1 attempt=0"
t=2020-01-23T20:39:25+0100 lvl=info msg="Initializing storage pools"
t=2020-01-23T20:39:25+0100 lvl=dbug msg="Initializing and checking storage pool \"default\""
t=2020-01-23T20:39:25+0100 lvl=dbug msg="Mount started" driver=dir pool=default
t=2020-01-23T20:39:25+0100 lvl=dbug msg="Mount finished" driver=dir pool=default
t=2020-01-23T20:39:25+0100 lvl=dbug msg="Initializing and checking storage pool \"virts\""
t=2020-01-23T20:39:25+0100 lvl=dbug msg="Mount started" driver=dir pool=virts
t=2020-01-23T20:39:35+0100 lvl=dbug msg="Mount finished" driver=dir pool=virts
t=2020-01-23T20:39:35+0100 lvl=eror msg="Failed to start the daemon: Failed initializing storage pool \"virts\": Failed to mount '/storage/virts/lxd' on '/var/snap/lxd/common/lxd/storage-pools/virts': no such file or directory"
t=2020-01-23T20:39:35+0100 lvl=info msg="Starting shutdown sequence"
t=2020-01-23T20:39:35+0100 lvl=info msg="Stopping REST API handler:"
t=2020-01-23T20:39:35+0100 lvl=info msg=" - closing socket" socket=/var/snap/lxd/common/lxd/unix.socket
t=2020-01-23T20:39:35+0100 lvl=info msg="Stopping /dev/lxd handler:"
t=2020-01-23T20:39:35+0100 lvl=info msg=" - closing socket" socket=/var/snap/lxd/common/lxd/devlxd/sock
t=2020-01-23T20:39:35+0100 lvl=info msg="Closing the database"
t=2020-01-23T20:39:35+0100 lvl=dbug msg="Stop database gateway"

**Comment by tomponline** [comment] 2020-01-23 19:44
@schmidtomat this looks like a duplicate of https://discuss.linuxcontainers.org/t/3-19-update-lxd-daemon-wont-startup-dir-backend-storage-init-problem/6576 which we are addressing with this patch shortly https://github.com/lxc/lxd/pull/6758

**Comment by stgraber** [comment] 2020-01-23 19:55
Fix has been merged, will push to snap as soon as I'm near my laptop

**Closed** 2020-01-23 19:54 UTC
Labels: Bug

**Comment by schmidtomat** [comment] 2020-01-23 20:05
thanks a lot .. this was fast :)

**Comment by stgraber** [comment] 2020-01-23 21:37
snap is building now, ETA is about 1.5h for it to build, test and be pushed to stable.

**Comment by s3rj1k** [comment] 2020-01-23 22:30
@stgraber not seeing this problem then LXD 3.19 is compiled from source without snap.
Hope this fix would not break dir backend for me :)

**Comment by tomponline** [comment] 2020-01-23 22:31
No it works both with and without snap.

**Comment by s3rj1k** [comment] 2020-01-23 22:32
@tomponline Thanks, I was starting to get nervous )
