### ISSUE TITLE
You can't delete things that are no longer physically present.

### ISSUE THREAD

**Issue by mark0978** [lxc/lxd#4192] opened 2018-01-23 23:15 UTC
# Required information

 * Distribution: ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version:4.4.0-109-generic
   * LXC version: 2.21
   * LXD version: 2.21
   * Storage backend in use: zfs

config:
  core.https_address: '[::]:8443'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 64.96.161.130:8443
  - 10.1.191.1:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFwjCCA6qgAwIBAgIQfypsdsLL4sPA96u/WPNqzzANBgkqhkiG9w0BAQsFADA1
    MRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRUwEwYDVQQDDAxyb290QGJ1
    aWxkMDQwHhcNMTYxMTE3MTUzNzU5WhcNMjYxMTE1MTUzNzU5WjA1MRwwGgYDVQQK
    ExNsaW51eGNvbnRhaW5lcnMub3JnMRUwEwYDVQQDDAxyb290QGJ1aWxkMDQwggIi
    MA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDVf/frOD2AvXZ1OylC13TSXbSG
    l2BtF8FZDBKKh7tmy4A3535XWOMkZpzdhIZ0sMSr3BcL1niSCeshFvi8l5OYkLzi
    FYMK767qj4/7PIzXaJybwUZgh/qmgls+7lTniiK3fIxzrl0ez+iJju9JGahloW/S
    YXJ5T3VQvj36QQAI9GfhmxOhKpevlpnVHcThcsEMi7GnMYn/sCwvaS8SMnD8hhM6
    6GKJxBLW6Yc7mo5JmL+3n3tCnUJrk/KNMayMG5OcVa0ePzw9JLeHe3auCgJZPjgy
    whnHqo2U06GCNZE3iJS/GDl1krGBZpjjiG8YTp4M0s08KlNtf1eb8HPuwAcWOc5b
    Jd1u3dA6tAyxGAukt74clhrNgasAViXiF+GR3p/wBMqLd3il51NxwpQuFDsyxw2N
    tqH+XV6n0VtaO7F2CW2n6paq5NglOKeabvXiG3YVDX/jopw0zLbnR3TOInnnb6g6
    +lOj9t3yLO/ByUf/GWJj2Tu/RblEBj0qraJYfS57fhN7NUUxxp7jEpYd5ERwZD4c
    BlDYABrhPRLcnq7xyqLcStp1nB6fi6ebSpLx5nJOe8qqcYsEqmatDrnPOGjp+Pb2
    hLp+7zyfJbAw83zJdNP66lGOCobcLxkrL3m5pcjQ0/pBg8tv55nLKvaYYnH17z0t
    4e90+uEg4pvLA4sHpwIDAQABo4HNMIHKMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUE
    DDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMIGUBgNVHREEgYwwgYmCB2J1aWxk
    MDSCEDY0Ljk2LjE2MS4xMzAvMjSCJjI2MjA6NTc6NDAwNToxNjE6MjE2OjNlZmY6
    ZmVhZjpjN2UzLzY0ghtmZTgwOjoyMTY6M2VmZjpmZWFmOmM3ZTMvNjSCG2ZlODA6
    OjQ4ODc6OGNmZjpmZTRmOjNhNS82NIIKZmU4MDo6MS82NDANBgkqhkiG9w0BAQsF
    AAOCAgEAjUOXj3XJUyaeCfd+/8X1uvuh1VGOImSuPxwK/c7YH2vxm7EXi2dcSSZL
    3Qyk8HWbYykjQeWMq4CnQ6D0beiCiLj18tQFgT97xUIxewX+07SRJePHd8j46m9/
    BnOXeTNRRlPBTaiI8DS+VvrrbK2MUyIOH5hYLBZOTBXcbLK9LDxzv650kyI1Ioh6
    Fk+o8OAsofix/80SKNN43F3e9tCSF0MQMT+Y+VlGkPwrAx5dfqHxnHCeleET78O3
    fueN3WQqigmr4M2pWPlOnsgASk8n4jXwVaW6FGUkBIEzasrp19QimlxEVL0K62EZ
    SsV1LqQsUJkhhLFpLf24NZgirdwOEG1z5+rqrJTbgbXKLoOc4xHJDyZ54MxPXhOv
    +J6EVwmzztU8yEBPwOYKUgUcKWNLIydkMA7XXYDdo4D3iPxMR82WxpzFP/PQ5eBG
    FsrSix23/B+LJ4opD446hFgobogy/zIvvyLXyr7F9HGLJvUqPjAz9zhDXXbv+LHZ
    nHIOMNMtNJC+by6yYFMloIt6MqHPxhVkbE/+4DzrWX79tBQSlOPEFoR45UzmTMiW
    My6R3SHCFf9P/0PJEOn23mG+0vumyX4g2qAEpPOP/o1cYISEaw/x6Hjop/AfkuI/
    E+TIEQIrihMTyZ5Tx7ujU13X2bSrn9PtByUATrbuxRMYBVSMXW0=
    -----END CERTIFICATE-----
  certificate_fingerprint: 3859cc8b5f746ff8ca27fb9d05e463c8beb303af0395721ccbf43269ee206f67
  driver: lxc
  driver_version: 2.1.1
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-109-generic
  server: lxd
  server_pid: 6097
  server_version: "2.21"
  storage: zfs
  storage_version: 0.6.5.6-0ubuntu16

# Issue description

I run with 2 storage systems, one on hard disk, one on ramdisk.  I launch ephemeral containers on the ramdisk.  When the system goes down, everything on the ramdisk is gone, but lives on in the sqlite db.  After the system comes back up, I have to manually delete things using sqlite3 to get them out of the db so that I can run my CI containers again.  The delete commands return `not found` which is fine as a warning, but they should just delete the db entry if the corresponding entry on the filesystem is missing.

If I don't remove them I cannot launch a new container using the same base image because of unique constraints in the DB.

# Steps to reproduce

I can provide this if you need, but I'm not sure you do.  At the point it goes to print "not found" it simply needs to know the difference between not found in the db and not found on the disk and delete the row in the DB when the disk file is not present.

**Comment by stgraber** [comment] 2018-01-23 23:21
What LXD version is that on?

@brauner did some work some time ago to make it possible to delete stuff that's no longer around, but that was on reasonably recent versions of LXD (2.18 or higher I believe).

**Comment by mark0978** [comment] 2018-01-24 02:46
Sadly I'm on 2.21 and it is still broken :-(  I updated the report with my version numbers, got distracted earlier and failed to put that in before I hit post.

**Comment by stgraber** [comment] 2018-01-24 03:15
Ok, so you're using zfs with LXD 2.21. What exactly is missing in your case? Just the container dataset or the entire zpool? As you're mentioning the use of temporary storage, I suspect it's the entire zpool?

Also just wondering, but wouldn't it be simpler to also have the entirety of LXD storage be on ephemeral storage, therefore getting a blank LXD on restart or would that be too much trouble for you to re-configure on startup? (that's what we do on our own test systems)

**Comment by brauner** [comment] 2018-01-24 09:27
On Tue, Jan 23, 2018 at 11:30:00PM +0000, Stéphane Graber wrote:
> What LXD version is that on?
> 
> @brauner did some work some time ago to make it possible to delete stuff that's no longer around, but that was on reasonably recent versions of LXD (2.18 or higher I believe).

Yes, you should be able to remove most entities when they do not longer
exist. We'd need to know what exactly doesn't exist anymore and what LXD
version you're used when you hit that error.

**Comment by mark0978** [comment] 2018-01-24 16:31
The zpool is destroy on shutdown but then recreated with the same name.  So
the contents of the zpool appear to be gone when what actually happened is
the zpool got recreated without lxd being aware.

Our base image is 2.2GB (sad I know, 1.4GB of "source") so I need the clone
to have happened and all that remains is the fetch/merge.  LXD is creating
a shadow copy on the ramdisk zpool so that while the first startup is slow,
subsequent startups are fast.  The problem comes when trying to remove
these missing parts and getting the Not Found. error.

**Comment by stgraber** [comment] 2018-01-24 18:12
Ok, that should be enough for @brauner to reproduce

**Comment by stgraber** [comment] 2018-02-20 21:44
Ok, so we should have LXD accept deleting stuff from a zpool which exists but where the datasets are gone as that's less likely to cause problems than if the zpool didn't come online for some reason.

**Comment by stgraber** [comment] 2018-02-20 22:55
Hmm, so I'm unable to reproduce your issue here... Our existing logic for removing things that aren't on disk anymore seems to be working as expected for me:

```
root@vm06:~# zfs list -t all
NAME      USED  AVAIL  REFER  MOUNTPOINT
default   230K  14.4G    19K  none
root@vm06:~# lxc init ubuntu:16.04 c1
Creating c1
root@vm06:~# lxc storage volume create default blah
Storage volume blah created

root@vm06:~# zfs list -t all
NAME                                                                                       USED  AVAIL  REFER  MOUNTPOINT
default                                                                                    309M  14.1G    19K  none
default/containers                                                                        4.93M  14.1G    19K  none
default/containers/c1                                                                     4.92M  14.1G   303M  /var/snap/lxd/common/lxd/storage-pools/default/containers/c1
default/custom                                                                              38K  14.1G    19K  none
default/custom/blah                                                                         19K  14.1G    19K  /var/snap/lxd/common/lxd/storage-pools/default/custom/blah
default/images                                                                             303M  14.1G    19K  none
default/images/069b95ed3a60645ee1905b7625a468d1357f00bd61bf096fc597063c6ed42cf1            303M  14.1G   303M  none
default/images/069b95ed3a60645ee1905b7625a468d1357f00bd61bf096fc597063c6ed42cf1@readonly      0      -   303M  -
root@vm06:~# systemctl stop snap.lxd.daemon
root@vm06:~# umount /run/snapd/ns/lxd.mnt
root@vm06:~# zfs destroy -r default/containers
root@vm06:~# zfs destroy -r default/custom
root@vm06:~# zfs destroy -r default/images
root@vm06:~# zfs list -t all
NAME      USED  AVAIL  REFER  MOUNTPOINT
default   294K  14.4G    19K  none

root@vm06:~# systemctl start snap.lxd.daemon
root@vm06:~# lxc list
+------+---------+------+------+------------+-----------+
| NAME |  STATE  | IPV4 | IPV6 |    TYPE    | SNAPSHOTS |
+------+---------+------+------+------------+-----------+
| c1   | STOPPED |      |      | PERSISTENT | 0         |
+------+---------+------+------+------------+-----------+
root@vm06:~# lxc delete c1

root@vm06:~# lxc image list
+-------+--------------+--------+---------------------------------------------+--------+----------+-------------------------------+
| ALIAS | FINGERPRINT  | PUBLIC |                 DESCRIPTION                 |  ARCH  |   SIZE   |          UPLOAD DATE          |
+-------+--------------+--------+---------------------------------------------+--------+----------+-------------------------------+
|       | 069b95ed3a60 | no     | ubuntu 16.04 LTS amd64 (release) (20180126) | x86_64 | 156.10MB | Feb 20, 2018 at 10:53pm (UTC) |
+-------+--------------+--------+---------------------------------------------+--------+----------+-------------------------------+
root@vm06:~# lxc image delete 069

root@vm06:~# lxc storage volume list default
+--------+------+-------------+---------+
|  TYPE  | NAME | DESCRIPTION | USED BY |
+--------+------+-------------+---------+
| custom | blah |             | 0       |
+--------+------+-------------+---------+
root@vm06:~# lxc storage volume delete default blah
Storage volume blah deleted

root@vm06:~# zfs list -t all
NAME      USED  AVAIL  REFER  MOUNTPOINT
default   294K  14.4G    19K  none
```

**Comment by stgraber** [comment] 2018-02-20 22:56
@mark0978 any idea what I'm missing?

**Comment by mark0978** [comment] 2018-02-21 00:51
The only difference I can think of is that my files disappear because the zfs filesystem is dropped and recreated.  But that shouldn't be different than what you are doing.\

My ZFS is in a file on a ramdisk.  After a reboot that ramdisk is gone and has to be recreated.  Once I do that and try to start a new container, the first one fails because the image isn't where lxd things it should be and lxc image delete was returning not found.

I'll see if I can give you the set of commands that I'm using tomorrow.

**Comment by stgraber** [comment] 2018-02-21 02:07
Ah yeah, I'd expect `lxc launch` to be pretty confused at least until the image is removed. I don't know if that launch would somehow make LXD behave differently afterwards than what I did above.

**Comment by stgraber** [comment] 2018-02-23 01:13
@mark0978 any luck?

**Comment by mark0978** [comment] 2018-02-23 04:02
I couldn't take that system down today, it was being used for a release,
but since the release is done I can do it tomorrow.

**Comment by mark0978** [comment] 2018-02-23 14:47
```
$ lxc storage volume list ramdisk
+-------+------------------------------------------------------------------+-------------+---------+
| TYPE  |                               NAME                               | DESCRIPTION | USED BY |
+-------+------------------------------------------------------------------+-------------+---------+
| image | 07943cb07faee0a793fba594a89a10e92b7c4aa60c5ccd640dad4ba93c368202 |             | 1       |
+-------+------------------------------------------------------------------+-------------+---------+
$ lxc storage volume delete ramdisk 07943cb07faee0a793fba594a89a10e92b7c4aa60c5ccd640dad4ba93c368202
error: not found
```

Maybe I'm just using the wrong command to get rid of that image file that is on the ramdisk?

That is "falsely on" the ramdisk that went away and was restored.  I'm not able to delete it without directly modifying the database.

**Comment by stgraber** [comment] 2018-02-23 15:09
```
lxc image delete 07943cb07faee0a793fba594a89a10e92b7c4aa60c5ccd640dad4ba93c368202
```

**Comment by stgraber** [comment] 2018-02-23 15:10
Oh, actually, you could probably only remove it from the pool with:

```
lxc storage volume delete ramdisk image/07943cb07faee0a793fba594a89a10e92b7c4aa60c5ccd640dad4ba93c368202
```

**Comment by stgraber** [comment] 2018-02-23 15:10
That would keep your image in /var/lib/lxd/images intact so you don't need to re-import it.

**Comment by mark0978** [comment] 2018-02-23 15:12
I will try this again now

**Comment by stgraber** [comment] 2018-02-23 18:07
@mark0978 how did that go?

**Comment by mark0978** [comment] 2018-02-23 19:20
mark@build04:~$ lxc storage volume delete ramdisk
image/6eb85b42d32af6ab12da62036b0d9af61a08a5e3a1941ad9ddc1bba8397a3ba7
Storage volume
image/6eb85b42d32af6ab12da62036b0d9af61a08a5e3a1941ad9ddc1bba8397a3ba7
deleted

**Comment by mark0978** [comment] 2018-02-23 19:21
```
lxc storage volume delete ramdisk image/6eb85b42d32af6ab12da62036b0d9af61a08a5e3a1941ad9ddc1bba8397a3ba7
Storage volume image/6eb85b42d32af6ab12da62036b0d9af61a08a5e3a1941ad9ddc1bba8397a3ba7 deleted
```

**Comment by mark0978** [comment] 2018-02-23 19:22
I'm seeing some artifacts though that will be more difficult to cleanup
```
mark@build04:~$ lxc storage volume list ramdisk
+-----------+------------------------------------------------------------------+-------------+---------+
|   TYPE    |                               NAME                               | DESCRIPTION | USED BY |
+-----------+------------------------------------------------------------------+-------------+---------+
| container | mark                                                             |             | 1       |
+-----------+------------------------------------------------------------------+-------------+---------+
| container | new-container                                                    |             | 1       |
+-----------+------------------------------------------------------------------+-------------+---------+
| container | test-21177                                                       |             | 1       |
+-----------+------------------------------------------------------------------+-------------+---------+
```

**Comment by mark0978** [comment] 2018-02-23 19:22
I'm wondering if a better way to do this would be to have something that would sync the sqlstate to the actual filesystem

**Comment by stgraber** [comment] 2018-02-23 19:29
Hmm, so that's odd, those 3 containers are listed in your `lxc storage volume list ramdisk` but don't show up in `lxc list`?

**Comment by mark0978** [comment] 2018-02-23 21:00
Well I would hope not, but I'll have to do a recreate to see.  That's the ramdisk that is wiped with a reboot, so they can't exist since it is a new zpool.

**Comment by stgraber** [comment] 2018-02-23 21:04
Deleting the zpool they're on will not magically have them disappear from the database.
After you get a clean zpool, you still need to:

 - Call `lxc delete` for any container that was on that zpool pre-reset
 - Call `lxc storage volume delete` for any custom or image volumes that were on the zpool pre-reset

After you do that, `lxc storage volume list` should be empty and your system should be back to normal.
Scripting the above should be pretty straightforward.

**Comment by mark0978** [comment] 2018-02-23 21:39
That's what my sqllite delete seems to do too.

**Comment by stgraber** [comment] 2018-02-23 21:45
If the only thing that's left is that row, yes, but it's likely that some properties tied to it are also there and some artifacts leftover from the container are likely left too, none of which are accounted for by your manual DB query.

**Comment by mark0978** [comment] 2018-02-23 21:47
guess I'll have to script it then :-)

**Comment by stgraber** [comment] 2018-02-23 22:11
Closing as things seem to be working as expected here.

If you do see a case where you can't delete something which is reported by the command line tool, we'll look into that. In general, the way to delete things is as follow:
 - Custom storage volume: lxc storage volume delete POOL VOLUME
 - Images: lxc storage volume delete POOL image/FINGERPRINT
 - Containers: lxc delete NAME

**Closed by stgraber** 2018-02-23 22:11 UTC
Labels: Incomplete

**Comment by adgriff2** [comment] 2018-09-06 04:35
@stgraber Sorry to hijack this, but I seem to be having a very similar problem to this closed issue.

```
$ lxc list
+------+-------+------+------+------+-----------+
| NAME | STATE | IPV4 | IPV6 | TYPE | SNAPSHOTS |
+------+-------+------+------+------+-----------+
```

```
$ lxc storage volume list default
+-----------+-----------------------------------------------------+-------------+---------+
|   TYPE    |                        NAME                         | DESCRIPTION | USED BY |
+-----------+-----------------------------------------------------+-------------+---------+
| container | UnifiController/UnifiController-2018-09-03T07-00-01 |             | 1       |
+-----------+-----------------------------------------------------+-------------+---------+
| container | UnifiController4                                    |             | 1       |
+-----------+-----------------------------------------------------+-------------+---------+
| container | UnifiController5                                    |             | 1       |
+-----------+-----------------------------------------------------+-------------+---------+
| container | sterling-mudfish                                    |             | 1       |
+-----------+-----------------------------------------------------+-------------+---------+
```
```
$ lxc storage volume delete default UnifiController4
Error: not found
$ lxc storage volume delete default UnifiController5
Error: not found
$ lxc storage volume delete default sterling-mudfish
Error: not found
$ lxc storage volume delete default UnifiController/UnifiController-2018-09-03T07-00-01
Error: invalid storage volume type name
```
```
$ lxc version
Client version: 3.0.1
Server version: 3.0.1
```

**Comment by stgraber** [comment] 2018-09-06 06:05
@adgriff2 Hmm, odd that you managed to get in that state in the first place, effectively managing to delete a container but not its storage volumes.

I'd say, try running:
 - lxc delete UnifiController4

If this fails with "not found" and doesn't clear the storage volume entry, then just use the big database hammer:
 - lxd sql global "DELETE FROM storage_volumes;"

**Comment by adgriff2** [comment] 2018-09-06 06:55
The sql command did it. I believe it got in this state when I tried to delete the container when the pool wasn't mounted correctly.
