### ISSUE TITLE
Missing blkio.throttle.io_* cgroup stats

### ISSUE THREAD

**Issue by niedbalski** [lxc/lxd#7627] opened 2020-07-06 17:32 UTC
# Required information

 * Distribution: Ubuntu
 * Distribution version: Focal 
 * LXC info: https://paste.ubuntu.com/p/43VwVsjM3v/

# Issue description

All the blkio.throtlle.* metrics are missed from the sysfs cgroup stats.  I see that the pids of the init process
of my lxc container is added to the cgroup tasks correctly.

$ sudo grep -r 125510 /sys/fs/cgroup/blkio/lxc.payload.test/*
/sys/fs/cgroup/blkio/lxc.payload.test/cgroup.procs:125510
/sys/fs/cgroup/blkio/lxc.payload.test/tasks:125510

$ watch -n1 cat /sys/fs/cgroup/blkio/lxc.payload.testing/blkio.throttle.io_service*

Shows no increment in the blk read/write counters, even when running dd inside the lxc container.  The same procedure in docker, shows that io_service* bytes increase correctly over time.

However, none of the blkio.throttle.io* oids are populated, unless I define any of the limits.* (max)
on the lxd profile. When adding the limits to the lxc default profile and restarting the container, I can now see the sysfs stats increasing:

$ cat /sys/fs/cgroup/blkio/lxc.payload.test/blkio.throttle.read_bps_device
253:1 100000000

As a workaround, if the following is set in the root device to an unlimited value (max int64) or via the default profile

$ lxc profile device set limited root limits.max 9223372036854775807B

I see the io_service bytes are indeed displayed in the sysfs oids.

**Comment by stgraber** [comment] 2020-07-06 17:35
@brauner can you take this one?

**Comment by niedbalski** [comment] 2020-07-07 14:05
@stgraber @brauner updated the description.

**Comment by brauner** [comment] 2020-07-07 14:56
> Shows no increment in the blk read/write counters, even when running dd inside the lxc container. The same procedure in docker, shows that io_service* bytes increase correctly over time.

So this works fine for me with:
```
dd if=/dev/zero of=/root/testfile bs=5G count=1
0+1 records in
```
Can you try to reproduce. Remember that `sync` may be required after `dd` so that the bytes are accounted for.

**Comment by niedbalski** [comment] 2020-07-07 15:07
> > Shows no increment in the blk read/write counters, even when running dd inside the lxc container. The same procedure in docker, shows that io_service* bytes increase correctly over time.
> 
> So this works fine for me with:
> 
> ```
> dd if=/dev/zero of=/root/testfile bs=5G count=1
> 0+1 records in
> ```
> 
> Can you try to reproduce. Remember that `sync` may be required after `dd` so that the bytes are accounted for.

Question: Are you reproducing this with the default lxd profile or by adding the limits stanza in the root disk?
with no limits, there will be no io metrics .*bps, so I don't think you'll be able to see the stats increasing even if
the cgroup tasks have the pid set under the blkio controller.

Probably a good  measure here, would be to set the limits.max to 9223372036854775807 by default, therefore
we get the disk stats properly set while not affecting the underlying i/o?

**Comment by brauner** [comment] 2020-07-08 13:29
Yeah, so I'm reproducing this with the default profile, no disk limits applied.

**Comment by stgraber** [comment] 2020-07-23 02:02
@brauner so what do we need to do to resolve this?

**Comment by brauner** [comment] 2020-07-23 06:02
> @brauner so what do we need to do to resolve this?

What I was saying was that I'm still unable yo reproduce this so I'm not sure what we should do here.

**Comment by stgraber** [comment] 2020-07-28 21:57
@brauner Reproduced trivially here on ZFS:

```
root@ubuntu-desktop:~# lxc launch images:ubuntu/20.04 u1
Creating u1
Starting u1
root@ubuntu-desktop:~# cat /sys/fs/cgroup/blkio/lxc.payload.u1/blkio.throttle.io_service*
7:4 Read 1024
7:4 Write 0
7:4 Sync 1024
7:4 Async 0
7:4 Discard 0
7:4 Total 1024
Total 1024
7:4 Read 1024
7:4 Write 0
7:4 Sync 1024
7:4 Async 0
7:4 Discard 0
7:4 Total 1024
Total 1024
7:4 Read 1
7:4 Write 0
7:4 Sync 1
7:4 Async 0
7:4 Discard 0
7:4 Total 1
Total 1
7:4 Read 1
7:4 Write 0
7:4 Sync 1
7:4 Async 0
7:4 Discard 0
7:4 Total 1
Total 1
root@ubuntu-desktop:~# lxc exec u1 bash
root@u1:~# dd if=/dev/zero of=out.img bs=4M count=100
100+0 records in
100+0 records out
419430400 bytes (419 MB, 400 MiB) copied, 0.749741 s, 559 MB/s
root@u1:~# ls -lh out.img 
-rw-r--r-- 1 root root 400M Jul 28 21:56 out.img
root@u1:~# exit
root@ubuntu-desktop:~# cat /sys/fs/cgroup/blkio/lxc.payload.u1/blkio.throttle.io_service*
7:4 Read 1024
7:4 Write 0
7:4 Sync 1024
7:4 Async 0
7:4 Discard 0
7:4 Total 1024
Total 1024
7:4 Read 1024
7:4 Write 0
7:4 Sync 1024
7:4 Async 0
7:4 Discard 0
7:4 Total 1024
Total 1024
7:4 Read 1
7:4 Write 0
7:4 Sync 1
7:4 Async 0
7:4 Discard 0
7:4 Total 1
Total 1
7:4 Read 1
7:4 Write 0
7:4 Sync 1
7:4 Async 0
7:4 Discard 0
7:4 Total 1
Total 1
root@ubuntu-desktop:~# 
```

**Comment by stgraber** [comment] 2020-08-09 17:43
@brauner see above, can you take another look at this please?

**Comment by brauner** [comment] 2020-08-09 19:04
I may fundamentally misunderstand something but blkio uses the Linux page cache which ZFS doesn't use so how is that supposed to work.

See also
https://github.com/openzfs/zfs/issues/1952

**Comment by brauner** [comment] 2020-08-09 20:10
So, `zfs` should not show you _any_ blkio stats. At least on 5.* kernels afaict. Here's what I get with a zfs loop-backed setup on a 5.4 kernel:
```
root@f1-vm:~# cat /sys/fs/cgroup/blkio/lxc.payload.f3/blkio.throttle.*
Total 0
Total 0
Total 0
Total 0
```

So @stgraber what is you kernel version? Are you using shiftfs?

**Comment by stgraber** [comment] 2020-08-09 20:14
5.4.0 and yeah, I do have shiftfs here.

```
stgraber@castiana:~/data/code/builders$ lxc launch images:ubuntu/20.04 u1
Creating u1
Starting u1
stgraber@castiana:~/data/code/builders$ cat /sys/fs/cgroup/blkio/lxc.payload.u1/blkio.throttle.io_service*
Total 0
Total 0
Total 0
Total 0
stgraber@castiana:~/data/code/builders$ lxc exec u1 bash
root@u1:~# dd if=/dev/zero of=out.img bs=4M count=100
100+0 records in
100+0 records out
419430400 bytes (419 MB, 400 MiB) copied, 0.255438 s, 1.6 GB/s
root@u1:~# sync
root@u1:~# ls -lh out.img 
-rw-r--r-- 1 root root 400M Aug  9 20:11 out.img
root@u1:~# exit
stgraber@castiana:~/data/code/builders$ cat /sys/fs/cgroup/blkio/lxc.payload.u1/blkio.throttle.io_service*
259:0 Read 0
259:0 Write 0
259:0 Sync 0
259:0 Async 0
259:0 Discard 0
259:0 Total 0
Total 0
259:0 Read 0
259:0 Write 0
259:0 Sync 0
259:0 Async 0
259:0 Discard 0
259:0 Total 0
Total 0
259:0 Read 0
259:0 Write 1
259:0 Sync 1
259:0 Async 0
259:0 Discard 0
259:0 Total 1
Total 1
259:0 Read 0
259:0 Write 1
259:0 Sync 1
259:0 Async 0
259:0 Discard 0
259:0 Total 1
Total 1
```

**Comment by stgraber** [comment] 2020-08-09 20:15
We probably should make sure that our behavior is correct when on ext4/btrfs, if we get proper metrics on those two, then it's just zfs being zfs.

**Comment by brauner** [comment] 2020-08-09 20:23
So here's me on btrfs loop-backed:
```
root@f1-vm:~# cat /sys/fs/cgroup/blkio/lxc.payload.f1/blkio.throttle.*
7:4 Read 23769088
7:4 Write 7692288
7:4 Sync 31461376
7:4 Async 0
7:4 Discard 0
7:4 Total 31461376
Total 31461376
7:4 Read 23769088
7:4 Write 7692288
7:4 Sync 31461376
7:4 Async 0
7:4 Discard 0
7:4 Total 31461376
Total 31461376
7:4 Read 163
7:4 Write 62
7:4 Sync 225
7:4 Async 0
7:4 Discard 0
7:4 Total 225
Total 225
7:4 Read 163
7:4 Write 62
7:4 Sync 225
7:4 Async 0
7:4 Discard 0
7:4 Total 225
Total 225
root@f1-vm:~# lxc shell f1
root@f1:~# dd if=/dev/zero of=out.img bs=4M count=100
100+0 records in
100+0 records out
419430400 bytes (419 MB, 400 MiB) copied, 0.189385 s, 2.2 GB/s
root@f1:~# logout
root@f1-vm:~# cat /sys/fs/cgroup/blkio/lxc.payload.f1/blkio.throttle.*
7:4 Read 36265984
7:4 Write 7692288
7:4 Sync 43958272
7:4 Async 0
7:4 Discard 0
7:4 Total 43958272
Total 43958272
7:4 Read 36265984
7:4 Write 7692288
7:4 Sync 43958272
7:4 Async 0
7:4 Discard 0
7:4 Total 43958272
Total 43958272
7:4 Read 263
7:4 Write 62
7:4 Sync 325
7:4 Async 0
7:4 Discard 0
7:4 Total 325
Total 325
7:4 Read 263
7:4 Write 62
7:4 Sync 325
7:4 Async 0
7:4 Discard 0
7:4 Total 325
Total 325
root@f1-vm:~# lxc shell f1
root@f1:~# sync
root@f1:~# logout
root@f1-vm:~# cat /sys/fs/cgroup/blkio/lxc.payload.f1/blkio.throttle.*
8:0 Read 0
8:0 Write 57344
8:0 Sync 57344
8:0 Async 0
8:0 Discard 0
8:0 Total 57344
7:4 Read 40591360
7:4 Write 10321920
7:4 Sync 50913280
7:4 Async 0
7:4 Discard 0
7:4 Total 50913280
Total 50970624
8:0 Read 0
8:0 Write 57344
8:0 Sync 57344
8:0 Async 0
8:0 Discard 0
8:0 Total 57344
7:4 Read 40591360
7:4 Write 10321920
7:4 Sync 50913280
7:4 Async 0
7:4 Discard 0
7:4 Total 50913280
Total 50970624
8:0 Read 0
8:0 Write 14
8:0 Sync 14
8:0 Async 0
8:0 Discard 0
8:0 Total 14
7:4 Read 311
7:4 Write 94
7:4 Sync 405
7:4 Async 0
7:4 Discard 0
7:4 Total 405
Total 419
8:0 Read 0
8:0 Write 14
8:0 Sync 14
8:0 Async 0
8:0 Discard 0
8:0 Total 14
7:4 Read 311
7:4 Write 94
7:4 Sync 405
7:4 Async 0
7:4 Discard 0
7:4 Total 405
Total 419
```

**Comment by brauner** [comment] 2020-08-09 20:45
Both `ext4` and `btrfs` look fine to me with the usual inconsistencies that are caused by the blkio controller being the blkio controller.
Maybe I'm still missing something though.
But a few more notes:
- it is really crucial to call `sync` after `dd` or use the `direct` option otherwise the kernel might decide to delay the actual write to whatever time it deems fit and it won't show up in the counters
- `zfs` doesn't go throught the Linux page cache and so blkio is completely meaningless, especially when an overlay fs like `shiftfs` is mounted on top at which point I expected shiftfs write to be accounted for through the page cache but zfs not using it things might get weird
- depending on the type of blkio scheduler used you can end up with

**Comment by brauner** [comment] 2020-08-09 20:51
Both `ext4` and `btrfs` look fine to me with the usual inconsistencies that are caused by the blkio controller being the blkio controller.
Maybe I'm still missing something though.
But a few more notes:
- it is really crucial to call `sync` after `dd` or use the `direct` option otherwise the kernel might decide to delay the actual write to whatever time it deems fit and it won't show up in the counters
- `zfs` doesn't go throught the Linux page cache and so blkio is completely meaningless, especially when an overlay fs like `shiftfs` is mounted on top at which point I expected shiftfs write to be accounted for through the page cache but zfs not using it things might get weird
- depending on the type of blkio scheduler used you can end up with `blkio.io_service_bytes` not updated while `blkio.throttle.io_service_bytes` is updated and their are other quirks like that
- I fail to see how setting or not settings limits would have an effect on whether or not something is accounted for in the `blkio.throttle.io_service*` files

**Comment by stgraber** [comment] 2020-08-09 22:21
Yeah, so on ZFS here, I can see that:
 - Pure I/O doesn't get counted.
 - Sync calls do get counted.
 - Metrics don't show until something which is counted shows up.

So as long as you're on ZFS, those metrics are unlikely to be of much use, I suspect the mentioned Docker containers were on a different storage backend.

It doesn't appear that LXD needs to do anything at the cgroup level to have the tracking begin, we just need to get tracked operations which doesn't really happen with ZFS (see issue referenced above).

Closing as there's nothing we can really do here other than hope that ZFS will soon use normal kernel APIs and so get properly counted.

**Closed by stgraber** 2020-08-09 22:21 UTC
Labels: Bug
