### ISSUE TITLE
`nftables` support for firewalling rules

### ISSUE THREAD

**Issue by stgraber** [lxc/lxd#6223] opened 2019-09-19 08:54 UTC
As more and more Linux distributions switch to nft, we need to cleanup our existing logic and add an nft alternative implementation.

The todo will look something like:

- [x] Centralize all our iptables, ip6tables and ebtables calls into one struct in a separate package, implementing a `firewall` interface.
- [x] Updating all existing code to load that struct (effectively asking for a `firewall` implementation backed by `iptables`)
- [ ] Implement the same interface for nftables
- [ ] Add startup logic to query both iptables and nftables, if we find existing rules in either, we will prefer the backend currently in use on the system, if neither contain rules, we use nft, if both of them do, we also use nft

This should handle all cases we care about in a clean way. Note that we will NOT support using the iptables compat wrappers as we've repeatedly found issues with those, especially around external modules/extensions which aren't properly supported. A native implementation is going to be much more reliable.

**Comment by keyallis** [comment] 2019-09-25 19:47
Myself and my partner from the UT Virtualization class would like to take this issue as part of our class project

**Comment by piluke** [comment] 2019-09-25 21:01
Hi, I'm the partner, could I also be assigned?

**Comment by stgraber** [comment] 2019-09-25 21:07
Thanks, assigned it to you. Unlike the image expiry issue, this one will be a bit trickier and will likely be done through multiple distinct pull requests to make things easier to review.

1) The first stage is to look at all our current uses of the `iptables`, `ip6tables` and `ebtables` commands in the LXD code, understand what each call does and design a list of functions that will perform these actions in a generic way.

2) All those function signatures will then be attached to a Go interface we'll call `firewall` and a first implementation of that interface will be done called `xtables` (generic name covering iptables, ip6tables and ebtables).

3) The LXD `State` struct will grow an additional `Firewall` member which will hold a pointer to the currently used firewall backend. Startup logic will be added to the LXD daemon to set that pointer on startup.

4) All existing calls to ebtables/iptables/ip6tables will be converted to using the relevant `State.Firewall.function()` call

5) A second implementation of the `firewall` interface called `nftables` will be introduced, directly driving nftables and implementing all the same functionality as the existing `xtables`.

6) Detection logic will be added to the daemon startup to decide whether to use `xtables` or `nftables`, setting `State.Firewall` to whichever backend is chosen (and logging an appropriate startup message).

I would expect each of those steps (except for the first) to lead to its own separate pull request, making it easier to review and get things into LXD rather than having one huge code dump at the end.

**Comment by stgraber** [comment] 2019-09-25 21:08
@tomponline and myself will be the main contact points for this one.

**Comment by stgraber** [comment] 2019-09-25 21:08
@tomponline does the above plan sound good to you?

**Comment by tomponline** [comment] 2019-09-26 08:43
@stgraber yep sounds good to me.

Worth making explicit that the interface and the implementations should be in their own package outside of `main`. 

Do you have any initial thoughts on what the logic for step 6 would be?

**Comment by stgraber** [comment] 2019-09-26 12:26
@tomponline what I described in the issue's description:
```
Add startup logic to query both iptables and nftables, if we find existing rules in either, we will prefer the backend currently in use on the system, if neither contain rules, we use nft, if both of them do, we also use nft.
```

**Comment by DannyMTran** [comment] 2019-10-31 19:51
Hi, I was just added to their group. Can I also be assigned?

**Comment by stgraber** [comment] 2019-10-31 19:55
Sure!

**Comment by keyallis** [comment] 2019-11-01 22:19
Just to give an update, we had a defined project given for the virtualization class that we wrapped up last week and then took this week off. We are now going to be actively working on this issue.

I had just a couple questions after looking at the code:

1. What exactly is the distinction between the Containerx and Networkx functions in the lxd/iptables/iptables.go file? They appear to be functionally the same except for logging and location of usage. Does this mean that they are somehow scoped or is that just a style point?

2. You mention in your step 3 that we will need to add logic to the daemon startup. Is that the logic surrounding the Networkx functions? More specifically is that the logic located in the lxd/networks.go file (Setup and Stop functions)?

3. To me it seems like 2 of the functions we can abstract away are the nicBridged setFilters and removeFilters functions. Those functions use helper functions defined on the nicBridged struct (getDHCPStaticIPs, generateFilterEbtablesRules, matchEbtablesRule, generateFilterIptablesRules) that are only used inside of the nic_bridged file. Are these function that we could pull out into the xtables implementation or is there a specific reason they're defined on that struct?

**Comment by stgraber** [comment] 2019-11-01 22:45
1) The difference between the two ends up being the comment which is added to the rule (and visible in `iptables -L -n -v`). This comment is then later used by LXD to locate the rules that are tied to a particular network or container, so it's more than just logging, it's how we get some of the context back from the kernel when listing active rules later on.

2) That's logic we don't currently have as we only have iptables. Once we have both iptables and nft, we need to put logic in place to determine which of the two backend we should use on a given system. That's the logic we'd be looking at adding to the daemon startup function.

3) That logic will need to use the iptables module indeed. Doing some grepping around, right now all calls to "iptables" and "ip6tables" are going through the "iptables" module, that's not yet true for "ebtables" though as that's still directly done in nic_bridge.go.

One thing to keep in mind is that "nft" is very different from "ebtables/iptables/ip6tables", so the arguments currently being passed to the functions in the "iptables" package cannot be translated in any easy way to both commands.

Right now the exported functions from "iptables" all accept "rule ...string" which is then directly passed to the system command, that's the part which varies the most between iptables and nft.

So the first task is to track down all calls to the "iptables" module and understand what each of those do, build up a full list of all of those and anything that's not already using the iptables module and then from that list, see what functions could be written to generically do that job in a way that can then be implemented through either xtables or nft.

**Comment by keyallis** [comment] 2019-11-14 19:26
With the cleaned up pull request created for point 2, I've been looking at the logic for point 3.

You said to add a firewall instance to the state struct, which is easy enough to do. Tracking down the startup logic has proven a bit more difficult. Since the State struct is created with the NewState function, which in turn is called from the Daemon's State function using only arguments gotten from the daemon struct fields, would we also need to create a firewall instance pointer in the Daemon struct?

My understanding is that the Firewall field of the State struct would only really be needed within the context of the device code, so would we need to have the value set every time State is called, or only when State is called and then passed off to the network/device code? Given that, would we want the startup determination logic to be contained in the Daemon init or could it be in the device/network code? Or since the Daemon struct is initialized in it's own init function, is that where we would be adding the logic to see which implementation to use?

**Comment by stgraber** [comment] 2019-11-14 21:38
1) Yes, indeed, you'll need to add a d.firewall and use that to initialize the state struct in NewState.

2) init() in daemon.go should be figuring out whether to do xtables or nftables, create a new instance of the relevant struct and put it in d.firewall which is then used whenever State() is called.

**Comment by keyallis** [comment] 2019-11-16 00:36
I've encountered an issue with circular inclusion that may require points 3 and 4 to be combined

**Comment by keyallis** [comment] 2019-11-16 18:25
After doing some digging I've determined that the issue is because our implementation of the firewall interface includes device, and in turn device includes the firewall interface. The reason we include the device package it so that we can use device.Instance as one of the arguments to the InstanceClear function. Is there a different Instance type we should be using that's outside of the device package or is there some other way we should rethink the firewall interface?

**Comment by tomponline** [comment] 2019-11-16 18:45
@keyallis I would suggest you create your own `Instance` interface in your package with *only* the functions you actually use from the main `Instance` interface. There are plans in the near future to move the `Instance` interface to its own package so that it can be referenced directly, but for now, having your own local package `Instance` interface helps to keep them loosely coupled.

This is why the `device` package has its own `Instance` interface.

**Comment by tomponline** [comment] 2019-11-16 18:46
@keyallis you can see we've done something similar in the `storage` package too https://github.com/lxc/lxd/blob/b58304b88c841c7da8826a6c64f22d7476cfb501/lxd/storage/interfaces.go#L15-L23

**Comment by tomponline** [comment] 2019-11-16 18:48
@keyallis alternatively, as you're only using `inst.Project()` and `inst.Name()` from what I can see, you could just have those passed in as separate args to `InstanceClear`. :)

**Comment by keyallis** [comment] 2019-12-12 19:29
I just wanted to update on the situation of this issue:

The firewall interface has been merged in, the remaining work to be done is to implement the nftables base and firewall interface implementation. This is something we have completed at a basic level but needs to be tested, and cannot be tested with the existing test suite since it uses iptables. There are also some nftables specific implementation points that need to be addressed, for example the creation of tables and chains and possible deletion after usage.
Past that the startup logic needs to be done, but would presumably only be added following the verification of correctness of the nftables package. I imagine testing would also need to be added for the startup logic as well.

This issue ended up being larger and more time intensive than we initially assumed due to various complications as well as incremental changes related to the interface definition. We are currently bumping up on the deadline (tonight at midnight) for the report in our class, so we will be shifting our focus to that for the time being. It's my understanding that @piluke and myself are open to continuing work on this issue once the report is written, though I can really only speak for myself in that regard.

**Comment by stgraber** [comment] 2019-12-12 22:49
Sounds good. And indeed this, similarly to the cgroupv2 work isn't something that can easily be tested in our existing CI.

Instead the aim should be that should the testsuite be run on a system which does use nft, that LXD will use nftables and the testsuite will similarly be checking nft rather than iptables in the checks.

LXD will print a startup message indicating whether it's using xtables or nft, so the testsuite can grep the daemon log and check accordingly.

**Closed** 2020-02-18 14:36 UTC
Labels: Documentation, Feature

**Comment by reterik** [comment] 2021-03-19 22:03
Any estimate on when nftables support will be implemented?

**Comment by stgraber** [comment] 2021-03-19 22:04
It has been for months :)
